terraria-cpp2il-methodrecon: UnityEngine.AndroidJavaObject._GetStatic< FieldType >
_GetStatic< FieldType >()
FieldType UnityEngine.AndroidJavaObject._GetStatic< FieldType > (string fieldName) inline protected
Definition at line 355 of file AndroidJavaObject.cs.
        {
            IntPtr intPtr = this.m_jclass;
            Type type;
            bool flag = AndroidReflection.IsPrimitive(type);
            char staticCharField = AndroidJNISafe.GetStaticCharField(this.m_jclass, intPtr);
            Type type2;
            Type type3;
            bool flag2 = AndroidReflection.IsAssignableFrom(type2, type3);
            IntPtr intPtr2;
            IntPtr staticObjectField = AndroidJNISafe.GetStaticObjectField(intPtr2, intPtr);
            IntPtr intPtr3;
            int staticIntField = AndroidJNISafe.GetStaticIntField(intPtr3, intPtr);
            IntPtr intPtr4;
            string staticStringField = AndroidJNISafe.GetStaticStringField(intPtr4, intPtr);
            IntPtr intPtr5;
            bool staticBooleanField = AndroidJNISafe.GetStaticBooleanField(intPtr5, intPtr);
            IntPtr intPtr6;
            AndroidJavaClass androidJavaClass = AndroidJavaObject.AndroidJavaClassDeleteLocalRef(AndroidJNISafe.GetStaticObjectField(intPtr6, intPtr));
            Debug.LogWarning("Field type <Byte> for Java get field call is obsolete, use field type <SByte> instead");
            IntPtr intPtr7;
            sbyte staticSByteField = AndroidJNISafe.GetStaticSByteField(intPtr7, intPtr);
            IntPtr intPtr8;
            IntPtr staticObjectField2 = AndroidJNISafe.GetStaticObjectField(intPtr8, intPtr);
            IntPtr intPtr9;
            sbyte staticSByteField2 = AndroidJNISafe.GetStaticSByteField(intPtr9, intPtr);
            IntPtr intPtr10;
            short staticShortField = AndroidJNISafe.GetStaticShortField(intPtr10, intPtr);
            IntPtr intPtr11;
            long staticLongField = AndroidJNISafe.GetStaticLongField(intPtr11, intPtr);
            IntPtr intPtr12;
            float staticFloatField = AndroidJNISafe.GetStaticFloatField(intPtr12, intPtr);
            IntPtr intPtr13;
            double staticDoubleField = AndroidJNISafe.GetStaticDoubleField(intPtr13, intPtr);
            throw new InvalidCastException();
        }
References UnityEngine.AndroidJavaObject.AndroidJavaClassDeleteLocalRef(), UnityEngine.AndroidJNISafe.GetStaticBooleanField(), UnityEngine.AndroidJNISafe.GetStaticCharField(), UnityEngine.AndroidJNISafe.GetStaticDoubleField(), UnityEngine.AndroidJNISafe.GetStaticFloatField(), UnityEngine.AndroidJNISafe.GetStaticIntField(), UnityEngine.AndroidJNISafe.GetStaticLongField(), UnityEngine.AndroidJNISafe.GetStaticObjectField(), UnityEngine.AndroidJNISafe.GetStaticSByteField(), UnityEngine.AndroidJNISafe.GetStaticShortField(), UnityEngine.AndroidJNISafe.GetStaticStringField(), UnityEngine.AndroidReflection.IsAssignableFrom(), UnityEngine.AndroidReflection.IsPrimitive(), j__TPar, UnityEngine.Debug.LogWarning(), and UnityEngine.AndroidJavaObject.m_jclass.