terraria-cpp2il-methodrecon: UnityEngine.AndroidJavaObject._Call
_Call()
void UnityEngine.AndroidJavaObject._Call (string methodName, params object[] args) inline protected
Definition at line 271 of file AndroidJavaObject.cs.
        {
            if (args == null)
            {
            }
            IntPtr jobject = this.m_jclass.m_jobject;
            long num = 0L;
            string text;
            IntPtr methodID = _AndroidJNIHelper.GetMethodID(jobject, methodName, text, num != 0L);
            jvalue[] array;
            AndroidJNISafe.CallVoidMethod(this.m_jobject.m_jobject, methodID, array);
        }
References System.array, UnityEngine.AndroidJNISafe.CallVoidMethod(), UnityEngine._AndroidJNIHelper.GetMethodID(), j__TPar, UnityEngine.L, UnityEngine.AndroidJavaObject.m_jclass, UnityEngine.AndroidJavaObject.m_jobject, UnityEngine.GlobalJavaObjectRef.m_jobject, and System.text.
Referenced by UnityEngine.AndroidJavaObject.Call().