terraria-cpp2il-methodrecon: UnityEngine.AndroidJavaObject._CallStatic
_CallStatic()
void UnityEngine.AndroidJavaObject._CallStatic (string methodName, params object[] args) inline protected
Definition at line 337 of file AndroidJavaObject.cs.
        {
            if (args == null)
            {
            }
            string text;
            IntPtr methodID = _AndroidJNIHelper.GetMethodID(this.m_jclass.m_jobject, methodName, text, true);
            jvalue[] array;
            AndroidJNISafe.CallStaticVoidMethod(this.m_jclass.m_jobject, methodID, array);
        }
References System.array, UnityEngine.AndroidJNISafe.CallStaticVoidMethod(), UnityEngine._AndroidJNIHelper.GetMethodID(), j__TPar, UnityEngine.AndroidJavaObject.m_jclass, UnityEngine.GlobalJavaObjectRef.m_jobject, and System.text.
Referenced by UnityEngine.AndroidJavaObject.CallStatic().