terraria-cpp2il-methodrecon: UnityEngine.AndroidJavaObject._Get< FieldType >
_Get< FieldType >()
FieldType UnityEngine.AndroidJavaObject._Get< FieldType > (string fieldName) inline protected
Definition at line 291 of file AndroidJavaObject.cs.
        {
            IntPtr intPtr = this.m_jclass;
            Type type;
            bool flag = AndroidReflection.IsPrimitive(type);
            char charField = AndroidJNISafe.GetCharField(this.m_jobject, intPtr);
            Type type2;
            Type type3;
            bool flag2 = AndroidReflection.IsAssignableFrom(type2, type3);
            IntPtr intPtr2;
            IntPtr objectField = AndroidJNISafe.GetObjectField(intPtr2, intPtr);
            IntPtr intPtr3;
            int intField = AndroidJNISafe.GetIntField(intPtr3, intPtr);
            IntPtr intPtr4;
            string stringField = AndroidJNISafe.GetStringField(intPtr4, intPtr);
            IntPtr intPtr5;
            bool booleanField = AndroidJNISafe.GetBooleanField(intPtr5, intPtr);
            IntPtr intPtr6;
            AndroidJavaClass androidJavaClass = AndroidJavaObject.AndroidJavaClassDeleteLocalRef(AndroidJNISafe.GetObjectField(intPtr6, intPtr));
            Debug.LogWarning("Field type <Byte> for Java get field call is obsolete, use field type <SByte> instead");
            IntPtr intPtr7;
            sbyte sbyteField = AndroidJNISafe.GetSByteField(intPtr7, intPtr);
            IntPtr intPtr8;
            IntPtr objectField2 = AndroidJNISafe.GetObjectField(intPtr8, intPtr);
            IntPtr intPtr9;
            sbyte sbyteField2 = AndroidJNISafe.GetSByteField(intPtr9, intPtr);
            IntPtr intPtr10;
            short shortField = AndroidJNISafe.GetShortField(intPtr10, intPtr);
            IntPtr intPtr11;
            long longField = AndroidJNISafe.GetLongField(intPtr11, intPtr);
            IntPtr intPtr12;
            float floatField = AndroidJNISafe.GetFloatField(intPtr12, intPtr);
            IntPtr intPtr13;
            double doubleField = AndroidJNISafe.GetDoubleField(intPtr13, intPtr);
            throw new InvalidCastException();
        }
References UnityEngine.AndroidJavaObject.AndroidJavaClassDeleteLocalRef(), UnityEngine.AndroidJNISafe.GetBooleanField(), UnityEngine.AndroidJNISafe.GetCharField(), UnityEngine.AndroidJNISafe.GetDoubleField(), UnityEngine.AndroidJNISafe.GetFloatField(), UnityEngine.AndroidJNISafe.GetIntField(), UnityEngine.AndroidJNISafe.GetLongField(), UnityEngine.AndroidJNISafe.GetObjectField(), UnityEngine.AndroidJNISafe.GetSByteField(), UnityEngine.AndroidJNISafe.GetShortField(), UnityEngine.AndroidJNISafe.GetStringField(), UnityEngine.AndroidReflection.IsAssignableFrom(), UnityEngine.AndroidReflection.IsPrimitive(), j__TPar, UnityEngine.Debug.LogWarning(), UnityEngine.AndroidJavaObject.m_jclass, and UnityEngine.AndroidJavaObject.m_jobject.