terraria-cpp2il-methodrecon: System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal
AddDefaultAttributeInternal()
XmlTextReaderImpl.NodeData System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal (string localName, string ns, string prefix, string value, int lineNo, int linePos, int valueLineNo, int valueLinePos, bool isXmlAttribute) inline private
Definition at line 3511 of file XmlTextReaderImpl.cs.
        {
            int stringLength = prefix._stringLength;
            XmlTextReaderImpl.NodeData nodeData = this.AddAttribute(localName, prefix, prefix);
            if (ns != null)
            {
                nodeData.ns = ns;
            }
            nodeData.SetValue(value);
            int num = 1;
            nodeData.isEmptyOrDefault = num != 0;
            string prefix2 = nodeData.prefix;
            int num4;
            if (prefix2._stringLength != 0)
            {
                string xmlNs = this.XmlNs;
                bool flag = Ref.Equal(prefix2, xmlNs);
                this.OnNamespaceDecl(nodeData);
                if (this.attrNeedNamespaceLookup)
                {
                    goto IL_00F2;
                }
                int num2 = this.attrCount;
                string localName2 = nodeData.localName;
                bool flag2 = this.nodes.prefix.Equals(localName2);
                XmlNamespaceManager xmlNamespaceManager = this.namespaceManager;
                XmlTextReaderImpl.NodeData[] array = this.nodes;
                int num3 = this.index;
                num4 = this.attrCount;
            }
            string localName3 = nodeData.localName;
            string xmlNs2 = this.XmlNs;
            bool flag3 = Ref.Equal(localName3, xmlNs2);
            this.OnDefaultNamespaceDecl(nodeData);
            if (!this.attrNeedNamespaceLookup)
            {
                string prefix3 = this.nodes.prefix;
                if (num4 == 0)
                {
                    string defaultNamespace = this.xmlContext.defaultNamespace;
                    this.OnXmlReservedAttribute(nodeData);
                }
            }
            IL_00F2:
            int num5 = 1;
            this.fullAttrCleanup = num5 != 0;
            return nodeData;
        }
References System.Xml.XmlTextReaderImpl.AddAttribute(), System.array, System.Xml.XmlTextReaderImpl.attrCount, System.Xml.XmlTextReaderImpl.attrNeedNamespaceLookup, System.Xml.Ref.Equal(), System.Xml.XmlTextReaderImpl.index, j__TPar, System.Xml.XmlTextReaderImpl.NodeData.localName, System.Xml.XmlTextReaderImpl.namespaceManager, System.Xml.XmlTextReaderImpl.nodes, System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute(), System.value, System.Xml.XmlTextReaderImpl.xmlContext, and System.Xml.XmlTextReaderImpl.XmlNs.