terraria-cpp2il-methodrecon: UnityEngine.UISystemProfilerApi.AddMarker
AddMarker()
static void UnityEngine.UISystemProfilerApi.AddMarker (string name, Object obj) inline static
Definition at line 24 of file UISystemProfilerApi.cs.
        {
            throw new MissingMethodException();
        }
Referenced by UnityEngine.UI.ScrollRect.LateUpdate(), UnityEngine.UI.Button.Press(), UnityEngine.UI.InputField.SendOnEndEdit(), UnityEngine.UI.InputField.SendOnSubmit(), UnityEngine.UI.InputField.SendOnValueChanged(), UnityEngine.UI.Toggle.Set(), UnityEngine.UI.Scrollbar.Set(), UnityEngine.UI.Slider.Set(), UnityEngine.UI.Dropdown.Set(), and UnityEngine.UI.MaskableGraphic.UpdateCull().