terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.ClearInstances
ClearInstances()
static void Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.ClearInstances () inline static
Definition at line 417 of file GeometryBufferInstance.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            bool gameMenu = Main.gameMenu;
            if (num == 0)
            {
            }
            bool mapFullscreen = Main.mapFullscreen;
            if (num == 0)
            {
            }
            float[] bufferZoom = GeometryBufferInstance.bufferZoom;
            Vector2[] bufferListPositions = GeometryBufferInstance.bufferListPositions;
            Vector2 screenPosition = Main.screenPosition;
            GeometryBufferInstance.ClearBuffers();
            GeometryBufferInstance.bufferList.FinaliseInstances();
        }
References Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.bufferList, Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.bufferListPositions, Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.bufferZoom, Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.ClearBuffers(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstanceList.FinaliseInstances(), Terraria.Main.gameMenu, Terraria.Main.mapFullscreen, and Terraria.Main.screenPosition.
Referenced by Microsoft.Xna.Framework.Game.UnityDraw().