terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.EndBuffer
EndBuffer()
static void Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.EndBuffer () inline static
Definition at line 318 of file GeometryBufferInstance.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            int num2 = 1;
            if (num2 == 0)
            {
            }
            Main.FlushBatches();
            if (num2 == 0)
            {
            }
            GeometryBufferInstance.bufferList.FinaliseInstances();
            Vector2[] bufferListPositions = GeometryBufferInstance.bufferListPositions;
            Vector2 screenPosition = Main.screenPosition;
            float caveParallax = Main.caveParallax;
            bool gameMenu = Main.gameMenu;
            int num3 = 1;
            if (num3 == 0)
            {
            }
            if (num3 == 0)
            {
                if (num3 == 0)
                {
                }
                bool gameMenu2 = Main.gameMenu;
                if (num3 == 0)
                {
                }
                int myPlayer = Main.myPlayer;
            }
            if (num3 != 0)
            {
                return;
            }
            GeometryBufferInstanceList[] bufferList = GeometryBufferInstance.bufferList;
            int num4 = 1;
            if (num4 == 0)
            {
            }
            int value = num4.m_value;
        }
References Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.bufferList, Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.bufferListPositions, Terraria.Main.caveParallax, Microsoft.Xna.Framework.Graphics.GeometryBufferInstanceList.FinaliseInstances(), Terraria.Main.FlushBatches(), Terraria.Main.gameMenu, j__TPar, Terraria.Main.myPlayer, Terraria.Main.screenPosition, and System.value.
Referenced by Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), and DistortionRenderTargetManager.EndRenderTarget().