terraria-cpp2il-methodrecon: GUIKeyboardMappings.SetupMappings
SetupMappings()
void GUIKeyboardMappings.SetupMappings () inline
Definition at line 85 of file GUIKeyboardMappings.cs.
    {
        ControllerActionAxis controllerActionAxis;
        this.MovementAxisX = controllerActionAxis;
        ControllerActionAxis movementAxisX = this.MovementAxisX;
        ControllerActionAxis controllerActionAxis2;
        this.MovementAxisY = controllerActionAxis2;
        ControllerActionAxis movementAxisY = this.MovementAxisY;
        ControllerActionAxis movementAxisX2 = this.MovementAxisX;
        ControllerActionAxis movementAxisY2 = this.MovementAxisY;
        ControllerActionVector controllerActionVector;
        this.MovementAxis = controllerActionVector;
        ControllerActionVector movementAxis = this.MovementAxis;
        ControllerActionVector controllerActionVector2;
        controllerActionVector2.LinkedAction = movementAxis;
        ControllerActionButton controllerActionButton = this.CreateButtonMapping("KeyboardGrappleFire");
        this.GrappleFire = controllerActionButton;
        ControllerActionButton controllerActionButton2 = this.CreateButtonMapping("KeyboardJump");
        this.Jump = controllerActionButton2;
        ControllerActionButton controllerActionButton3;
        this.Fire = controllerActionButton3;
        ControllerActionButton controllerActionButton4 = this.CreateButtonMapping("KeyboardInteract");
        this.Interact = controllerActionButton4;
        ControllerActionButton controllerActionButton5 = this.CreateButtonMapping("KeyboardTargetLockOn");
        this.TargetLockOn = controllerActionButton5;
        ControllerActionButton controllerActionButton6 = this.CreateButtonMapping("KeyboardInventoryToggle");
        this.InventoryToggle = controllerActionButton6;
        ControllerActionButton controllerActionButton7 = this.CreateButtonMapping("KeyboardAutoSelect");
        this.AutoSelect = controllerActionButton7;
        ControllerActionButton controllerActionButton8 = this.CreateButtonMapping("KeyboardSmartCursor");
        this.SmartCursor = controllerActionButton8;
        ControllerActionButton controllerActionButton9 = this.CreateButtonMapping("KeyboardZoomIn");
        this.ZoomIn = controllerActionButton9;
        ControllerActionButton controllerActionButton10 = this.CreateButtonMapping("KeyboardZoomOut");
        this.ZoomOut = controllerActionButton10;
        ControllerActionButton controllerActionButton11 = this.CreateButtonMapping("KeyboardMapZoomIn");
        this.MapZoomIn = controllerActionButton11;
        ControllerActionButton controllerActionButton12 = this.CreateButtonMapping("KeyboardMapZoomOut");
        this.MapZoomOut = controllerActionButton12;
        ControllerActionButton controllerActionButton13 = this.CreateButtonMapping("KeyboardMapZoomDefault");
        this.MapZoomDefault = controllerActionButton13;
        ControllerActionButton controllerActionButton14 = this.CreateButtonMapping("KeyboardQuickHeal");
        this.QuickHeal = controllerActionButton14;
        ControllerActionButton controllerActionButton15 = this.CreateButtonMapping("KeyboardQuickMana");
        this.QuickMana = controllerActionButton15;
        ControllerActionButton controllerActionButton16 = this.CreateButtonMapping("KeyboardQuickBuff");
        this.QuickBuff = controllerActionButton16;
        ControllerActionButton controllerActionButton17 = this.CreateButtonMapping("KeyboardQuickMount");
        this.QuickMount = controllerActionButton17;
        ControllerActionButton controllerActionButton18 = this.CreateButtonMapping("KeyboardMapToggle");
        this.MapToggle = controllerActionButton18;
        ControllerActionButton controllerActionButton19 = this.CreateButtonMapping("KeyboardMiniMapToggle");
        this.MiniMapToggle = controllerActionButton19;
        ControllerActionButton controllerActionButton20 = this.CreateButtonMapping("KeyboardChatToggle");
        this.ChatToggle = controllerActionButton20;
        ControllerActionButton controllerActionButton21 = this.CreateButtonMapping("KeyboardUISettings");
        this.Settings = controllerActionButton21;
        ControllerActionButton controllerActionButton22 = this.CreateButtonMapping("KeyboardHotbar1");
        this.Hotbar1 = controllerActionButton22;
        ControllerActionButton controllerActionButton23 = this.CreateButtonMapping("KeyboardHotbar2");
        this.Hotbar2 = controllerActionButton23;
        ControllerActionButton controllerActionButton24 = this.CreateButtonMapping("KeyboardHotbar3");
        this.Hotbar3 = controllerActionButton24;
        ControllerActionButton controllerActionButton25 = this.CreateButtonMapping("KeyboardHotbar4");
        this.Hotbar4 = controllerActionButton25;
        ControllerActionButton controllerActionButton26 = this.CreateButtonMapping("KeyboardHotbar5");
        this.Hotbar5 = controllerActionButton26;
        ControllerActionButton controllerActionButton27 = this.CreateButtonMapping("KeyboardHotbar6");
        this.Hotbar6 = controllerActionButton27;
        ControllerActionButton controllerActionButton28 = this.CreateButtonMapping("KeyboardHotbar7");
        this.Hotbar7 = controllerActionButton28;
        ControllerActionButton controllerActionButton29 = this.CreateButtonMapping("KeyboardHotbar8");
        this.Hotbar8 = controllerActionButton29;
        ControllerActionButton controllerActionButton30 = this.CreateButtonMapping("KeyboardHotbar9");
        this.Hotbar9 = controllerActionButton30;
        ControllerActionButton controllerActionButton31 = this.CreateButtonMapping("KeyboardHotbar10");
        this.Hotbar10 = controllerActionButton31;
        ControllerActionButton controllerActionButton32 = this.CreateButtonMapping("KeyboardHotbarNext");
        this.HotbarNext = controllerActionButton32;
        ControllerActionButton controllerActionButton33 = this.CreateButtonMapping("KeyboardHotbarPrevious");
        this.HotbarPrevious = controllerActionButton33;
        ControllerActionButton controllerActionButton34;
        this.LeftPageCycle = controllerActionButton34;
        ControllerActionButton controllerActionButton35 = this.CreateButtonMapping("Weapons - Ammo");
        this.RightPageCycle = controllerActionButton35;
        ControllerActionButton controllerActionButton36 = this.CreateButtonMapping("KeyboardLoadout1");
        this.Loadout1 = controllerActionButton36;
        ControllerActionButton controllerActionButton37 = this.CreateButtonMapping("KeyboardLoadout2");
        this.Loadout2 = controllerActionButton37;
        ControllerActionButton controllerActionButton38 = this.CreateButtonMapping("KeyboardLoadout3");
        this.Loadout3 = controllerActionButton38;
        ControllerActionButton controllerActionButton39 = this.CreateButtonMapping("KeyboardLoadoutCycle");
        this.LoadoutCycle = controllerActionButton39;
        this.LoadDefaults();
        this.SetupEscapeKeySetting();
    }
References CreateButtonMapping(), j__TPar, LoadDefaults(), MovementAxis, MovementAxisX, MovementAxisY, and SetupEscapeKeySetting().