terraria-cpp2il-methodrecon: System.Threading.Monitor.Exit
Exit()
static void System.Threading.Monitor.Exit (object obj) inline static
Definition at line 47 of file Monitor.cs.
        {
        }
Referenced by System.Text.InternalDecoderBestFitFallbackBuffer.InternalDecoderBestFitFallbackBuffer(), System.Text.InternalEncoderBestFitFallbackBuffer.InternalEncoderBestFitFallbackBuffer(), System.Net.Semaphore.Semaphore(), System.Net.CommandStream.Abort(), System.Runtime.InteropServices.HandleCollector.Add(), System.ComponentModel.Container.Add(), System.Collections.Hashtable.SyncHashtable.Add(), System.Collections.SortedList.SyncSortedList.Add(), System.Xml.Linq.XHashtable< TValue >.Add(), System.Net.CookieContainer.AddRemoveDomain(), Newtonsoft.Json.Utilities.ThreadSafeStore< TKey, TValue >.AddValue(), System.LocalDataStoreMgr.AllocateDataSlot(), System.LocalDataStoreMgr.AllocateNamedDataSlot(), System.Resources.ResourceReader.AllocateStringForNameIndex(), SaveSynchronisationManager.AttemptClientConnection(), System.Net.FtpWebRequest.AttemptedRecovery(), SaveSynchronisationManager.AttemptHostConnection(), System.Net.HttpListener.BeginGetContext(), System.Net.FileWebRequest.BeginGetRequestStream(), System.Net.FtpWebRequest.BeginGetRequestStream(), System.Net.FileWebRequest.BeginGetResponse(), System.Net.FtpWebRequest.BeginGetResponse(), System.Net.TimerThread.TimerNode.Cancel(), Terraria.WorldBuilding.StructureMap.CanPlace(), System.Net.WebConnection.CanReuseConnection(), Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns(), System.Collections.Hashtable.SyncHashtable.Clear(), System.Collections.SortedList.SyncSortedList.Clear(), Telepathy.SafeQueue< T >.Clear(), System.Collections.Hashtable.SyncHashtable.Clone(), System.Collections.SortedList.SyncSortedList.Clone(), System.Net.WebConnection.Close(), System.Net.ServicePoint.CloseConnectionGroup(), System.Net.FtpDataStream.CloseEx(), System.Net.WebConnection.CloseSocket(), Mono.Net.Security.MonoTlsStream.CloseSslStream(), System.Net.HttpStreamAsyncResult.Complete(), System.Net.ListenerAsyncResult.Complete(), System.Net.ListenerAsyncResult.Complete(), SaveSynchronisationManager.Connect(), Microsoft.Xna.Framework.Content.ThreadContentRequest.ConstructFromMainThread(), System.Collections.SortedList.SyncSortedList.Contains(), Terraria.IO.Preferences.Contains(), System.Collections.SortedList.SyncSortedList.ContainsValue(), System.Net.WebConnection.Continue(), System.Net.CommandStream.ContinueCommandPipeline(), System.Collections.Hashtable.SyncHashtable.CopyTo(), System.Collections.SortedList.SyncSortedList.CopyTo(), System.TimeZoneInfo.CachedData.CreateLocal(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(), System.Net.HttpListener.CreateSslStream(), System.Net.TimerThread.TimerQueue.CreateTimer(), System.LocalDataStoreMgr.DeleteLocalDataStore(), InControl.Internal.RingBuffer< T >.Dequeue(), InControl.ThreadSafeQueue< T >.Dequeue(), InControl.ThreadSafeQueue< T >.Dequeue(), InControl.ThreadSafeQueue< T >.Dequeue(), System.Runtime.Remoting.RemotingServices.DeserializeCallData(), Terraria.GameContent.CoinLossRevengeSystem.DestroyMarker(), System.ComponentModel.Component.Dispose(), System.ComponentModel.MarshalByValueComponent.Dispose(), System.Diagnostics.AsyncStreamReader.Dispose(), Mono.Net.Security.MobileAuthenticatedStream.Dispose(), System.Runtime.Remoting.Contexts.Context.DoCallBack(), Terraria.GameContent.CoinLossRevengeSystem.DrawMapIcons(), System.Net.HttpListener.EndGetContext(), System.Runtime.Remoting.Messaging.AsyncResult.EndInvoke(), InControl.ThreadSafeQueue< T >.Enqueue(), Telepathy.SafeQueue< T >.Enqueue(), InControl.Internal.RingBuffer< T >.Enqueue(), System.Net.FtpWebRequest.EnsureFtpWebResponse(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Diagnostics.Process.EnsureWatchingForExit(), MainThreadExecution.Execute(), System.Net.CookieContainer.ExpireCollection(), System.ComponentModel.PropertyDescriptorCollection.Find(), System.Threading.Tasks.Task< TResult >.Finish(), System.Net.WebOperation.Finish(), System.Net.TimerThread.TimerNode.Fire(), System.Net.TimerThread.TimerQueue.Fire(), System.LocalDataStoreMgr.FreeNamedDataSlot(), Terraria.ID.SetFactory.GetBoolBuffer(), Terraria.WorldBuilding.StructureMap.GetBoundingBox(), System.Collections.SortedList.SyncSortedList.GetByIndex(), System.CurrentSystemTimeZone.GetCachedDaylightChanges(), System.Net.Sockets.Socket.TaskSocketAsyncEventArgs< TResult >.GetCompletionResponsibility(), System.Net.ServicePointScheduler.GetConnectionGroup(), System.Net.PathList.GetCookiesCount(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditor(), System.Collections.SortedList.SyncSortedList.GetEnumerator(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.GetEnumerator(), Terraria.ID.SetFactory.GetFloatBuffer(), System.Net.ResponseStream.GetHeaders(), Terraria.ID.SetFactory.GetIntBuffer(), System.Collections.SortedList.SyncSortedList.GetKey(), System.Collections.SortedList.SyncSortedList.GetKeyList(), System.LocalDataStoreMgr.GetNamedDataSlot(), System.Resources.ResourceManager.GetResourceSet(), System.Net.Configuration.DefaultProxySectionInternal.GetSection(), System.Runtime.Remoting.SingletonIdentity.GetServerObject(), System.Net.HttpWebRequest.GetServicePoint(), Terraria.ID.SetFactory.GetUshortBuffer(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.GetValue(), System.Collections.SortedList.SyncSortedList.GetValueList(), System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(), System.Collections.SortedList.SyncSortedList.IndexOfKey(), System.Collections.SortedList.SyncSortedList.IndexOfValue(), System.TermInfoDriver.Init(), System.Uri.InitializeUriConfig(), System.Resources.ResourceManager.InternalGetResourceSet(), ReLogic.OS.Windows.STATaskInvoker.InvokeAndWait(), Terraria.IO.Preferences.Load(), System.Net.HttpListener.LoadCertificateAndKey(), Microsoft.Xna.Framework.Content.ThreadContentRequest.LoadFromMainThread(), Terraria.Map.WorldMapChunk.LoadTiles(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator.MoveNext(), System.Net.HttpWebRequest.d__244.MoveNext(), System.Net.HttpWebRequest.MyGetRequestStreamAsync(), Ionic.Zip.ZipFile.OnZipErrorSaving(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Place(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Place(), Terraria.GameContent.Tile_Entities.TEHatRack.Place(), Terraria.GameContent.Tile_Entities.TEItemFrame.Place(), Terraria.GameContent.Tile_Entities.TELogicSensor.Place(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Place(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Place(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Place(), System.LocalDataStore.PopulateElement(), Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(), Mono.Net.Security.MobileAuthenticatedStream.ProcessRead(), Mono.Net.Security.MobileAuthenticatedStream.ProcessWrite(), Terraria.Social.Steam.CoreSocialModule.PulseSteamCallback(), Terraria.Social.Steam.CoreSocialModule.PulseSteamTick(), Terraria.IO.Preferences.Put(), System.Diagnostics.Process.RaiseOnExited(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.RegisterChatStartWith(), System.Net.HttpListener.RegisterContext(), System.Runtime.Remoting.Contexts.DynamicPropertyCollection.RegisterDynamicProperty(), Terraria.GameContent.Bestiary.NPCKillsTracker.RegisterKill(), System.Net.WebRequest.RegisterPrefix(), System.Net.WebOperation.RegisterRequest(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby(), System.Net.Sockets.SafeSocketHandle.ReleaseHandle(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks(), System.Runtime.InteropServices.HandleCollector.Remove(), System.ComponentModel.Container.Remove(), System.Collections.Hashtable.SyncHashtable.Remove(), System.Collections.SortedList.SyncSortedList.Remove(), System.Xml.XmlDownloadManager.Remove(), System.Threading.Timer.Scheduler.Remove(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Remove(), System.Collections.SortedList.SyncSortedList.RemoveAt(), System.Net.EndPointListener.RemoveConnection(), System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasksNonInlined(), ReLogic.Content.AssetRepository.Request< T >(), Mono.Net.Security.AsyncProtocolRequest.RequestRead(), System.Net.WebConnection.Reset(), Terraria.Map.WorldMapChunk.Reset(), Terraria.WorldBuilding.StructureMap.Reset(), Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(), System.Threading.Timer.Scheduler.SchedulerThread(), System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(), System.Net.HttpWebRequest.SendRequest(), System.Net.ServicePoint.SendRequest(), System.Net.ServicePointScheduler.SendRequest(), Terraria.GameContent.Bestiary.NPCKillsTracker.SetKillCountDirectly(), System.Runtime.Remoting.Lifetime.LeaseManager.SetPollTime(), System.Net.WebOperation.SetPriorityRequest(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.SetWasChatWithDirectly(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.SetWasSeenDirectly(), System.Collections.Concurrent.ConcurrentQueue< T >.SnapForObservation(), System.Net.WebConnection.StartOperation(), Terraria.Social.Steam.CoreSocialModule.SteamTickLoop(), System.Diagnostics.Process.StopWatchingForExit(), System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(), ReLogic.OS.Windows.STATaskInvoker.TaskThreadStart(), Ionic.Zip.ZipEntry.TraceWriteLine(), System.Runtime.Remoting.Lifetime.LeaseManager.TrackLifetime(), ReLogic.Content.AssetRepository.TransferCompletedAssets(), Telepathy.SafeQueue< T >.TryDequeue(), Telepathy.SafeQueue< T >.TryDequeueAll(), System.Collections.Concurrent.ConcurrentQueue< T >.TryDequeueSlow(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.TryGetValue(), System.Net.FileWebRequest.UnblockReader(), System.Runtime.Remoting.Lifetime.Lease.Unregister(), System.Threading.RegisteredWaitHandle.Unregister(), System.Net.HttpListener.UnregisterContext(), System.Runtime.Remoting.Contexts.DynamicPropertyCollection.UnregisterDynamicProperty(), System.Net.Sockets.SafeSocketHandle.UnRegisterForBlockingSyscall(), System.Net.WebProxy.Update(), Microsoft.Xna.Framework.Content.ThreadContentRequest.UpdateLoad(), System.Runtime.Remoting.Lifetime.Lease.UpdateState(), System.Threading.RegisteredWaitHandle.Wait(), Terraria.WorldGen.WaitForThreadTime(), and MainThreadExecution.WaitOnMainThreadComplete().