terraria-cpp2il-methodrecon: Terraria.Netplay.ResetNetDiag
ResetNetDiag()
static void Terraria.Netplay.ResetNetDiag () inline static
Definition at line 77 of file Netplay.cs.
        {
            if (!true)
            {
            }
            INetDiagnosticsUI activeNetDiagnosticsUI = Main.ActiveNetDiagnosticsUI;
        }
References Terraria.Main.ActiveNetDiagnosticsUI, and j__TPar.
Referenced by Terraria.Netplay.ClientLoopSetup(), Terraria.Netplay.ClientServerLoopSetup(), and Terraria.Netplay.ServerLoop().