terraria-cpp2il-methodrecon: Terraria.Netplay.ServerLoop
ServerLoop()
static void Terraria.Netplay.ServerLoop (object threadContext) inline static
Definition at line 417 of file Netplay.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            Netplay.ResetNetDiag();
            if (num == 0)
            {
            }
            long ticks = DateTime.Now.Ticks;
            if (3 == 0)
            {
            }
            bool flag = Netplay.StartListening();
            Main.menuMode = 14;
            string textValue = Language.GetTextValue("Mobile.FailedToCreateSession");
            int num2 = 1;
            Debug.LogError("   Exception normal: Tried to run two servers on the same PC");
            PlatformUser currentUser = PlatformUser.CurrentUser;
            if (num2 != 0)
            {
            }
        }
References PlatformUser.CurrentUser, Terraria.Localization.Language.GetTextValue(), j__TPar, UnityEngine.Debug.LogError(), System.DateTime.Now, Terraria.Netplay.ResetNetDiag(), Terraria.Netplay.StartListening(), and System.DateTime.Ticks.