terraria-cpp2il-methodrecon: Terraria.Netplay.ServerUpdateFrame
ServerUpdateFrame()
static void Terraria.Netplay.ServerUpdateFrame () inline static
Definition at line 250 of file Netplay.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            while (num != 0)
            {
            }
            if (num == 0)
            {
            }
            string text;
            bool flag = TcpAddress.IsLocalHost(text);
            NetworkText networkText;
            NetMessage.BootPlayer(43143168, networkText);
        }
References Terraria.NetMessage.BootPlayer(), Terraria.Net.TcpAddress.IsLocalHost(), j__TPar, and System.text.
Referenced by Microsoft.Xna.Framework.Game.UnityServerUpdate(), and Microsoft.Xna.Framework.Game.UnityUpdate().