terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.DeactivateInputField
DeactivateInputField()
void UnityEngine.UI.InputField.DeactivateInputField () inline
Definition at line 2114 of file InputField.cs.
        {
            bool allowInput = this.m_AllowInput;
            if (allowInput)
            {
                Graphic placeholder = this.m_Placeholder;
                if (!allowInput)
                {
                }
                string text = this.m_Text;
                Graphic placeholder2 = this.m_Placeholder;
                long num = 0L;
                bool flag = string.IsNullOrEmpty(text);
                placeholder2.enabled = num != 0L;
                Text textComponent = this.m_TextComponent;
                if (!allowInput)
                {
                }
                if (this.m_WasCanceled)
                {
                    string originalText = this.m_OriginalText;
                    this.SetText(originalText, true);
                }
                this.SendOnEndEdit();
                TouchScreenKeyboard keyboard = this.m_Keyboard;
                if (keyboard != null)
                {
                    long num2 = 0L;
                    keyboard.active = num2 != 0L;
                }
                this.MarkGeometryAsDirty();
                return;
            }
        }
References j__TPar, UnityEngine.L, UnityEngine.UI.InputField.m_AllowInput, UnityEngine.UI.InputField.m_Keyboard, UnityEngine.UI.InputField.m_OriginalText, UnityEngine.UI.InputField.m_Placeholder, UnityEngine.UI.InputField.m_Text, UnityEngine.UI.InputField.m_TextComponent, UnityEngine.UI.InputField.m_WasCanceled, UnityEngine.UI.InputField.MarkGeometryAsDirty(), UnityEngine.UI.InputField.placeholder, UnityEngine.UI.InputField.SendOnEndEdit(), UnityEngine.UI.InputField.SetText(), UnityEngine.UI.InputField.text, and UnityEngine.UI.InputField.textComponent.
Referenced by UnityEngine.UI.InputField.OnDeselect(), UnityEngine.UI.InputField.OnDisable(), and UnityEngine.UI.InputField.OnUpdateSelected().