terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.OnPointerDown
OnPointerDown()
override void UnityEngine.UI.InputField.OnPointerDown (PointerEventData eventData) inline virtual
Reimplemented from UnityEngine.UI.Selectable.
Definition at line 1211 of file InputField.cs.
        {
            bool flag = this.MayDrag(eventData);
            EventSystem current = EventSystem.current;
            GameObject gameObject = base.gameObject;
            current.SetSelectedGameObject(gameObject, eventData);
            bool allowInput = this.m_AllowInput;
            base.OnPointerDown(eventData);
            bool isSupported = TouchScreenKeyboard.isSupported;
            if (!this.m_TouchKeyboardAllowsInPlaceEditing)
            {
                TouchScreenKeyboard keyboard = this.m_Keyboard;
                if (keyboard != null)
                {
                    bool active = keyboard.active;
                }
                throw new MissingMethodException();
            }
            if (allowInput)
            {
                RectTransform rectTransform = this.m_TextComponent.rectTransform;
                float x = eventData.<pointerPressRaycast>k__BackingField.screenPosition.x;
                float y = eventData.<pointerPressRaycast>k__BackingField.screenPosition.y;
                Camera pressEventCamera = eventData.pressEventCamera;
                int drawStart = this.m_DrawStart;
                this.m_CaretPosition = drawStart;
                string text = this.m_Text;
                int stringLength = text._stringLength;
                int stringLength2 = text._stringLength;
                this.m_CaretSelectPosition = drawStart;
                return;
            }
            this.UpdateLabel();
        }
References UnityEngine.TouchScreenKeyboard.active, UnityEngine.EventSystems.EventSystem.current, UnityEngine.Component.gameObject, UnityEngine.GameObject.gameObject, UnityEngine.TouchScreenKeyboard.isSupported, j__TPar, UnityEngine.UI.Selectable.k__BackingField, UnityEngine.UI.InputField.m_AllowInput, UnityEngine.UI.InputField.m_DrawStart, UnityEngine.UI.InputField.m_Keyboard, UnityEngine.UI.InputField.m_Text, UnityEngine.UI.InputField.m_TextComponent, UnityEngine.UI.InputField.m_TouchKeyboardAllowsInPlaceEditing, UnityEngine.UI.InputField.MayDrag(), UnityEngine.EventSystems.PointerEventData.pressEventCamera, UnityEngine.UI.Graphic.rectTransform, UnityEngine.EventSystems.EventSystem.SetSelectedGameObject(), UnityEngine.UI.InputField.text, and UnityEngine.UI.InputField.UpdateLabel().