terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.Backspace
Backspace()
void UnityEngine.UI.InputField.Backspace () inline private
Definition at line 1542 of file InputField.cs.
        {
            if (this.m_ReadOnly)
            {
                return;
            }
            bool hasSelection = this.hasSelection;
            this.Delete();
            this.UpdateTouchKeyboardFromEditChanges();
            this.SendOnValueChanged();
            this.UpdateLabel();
        }
References UnityEngine.UI.InputField.Delete(), UnityEngine.UI.InputField.hasSelection, UnityEngine.UI.InputField.m_ReadOnly, UnityEngine.UI.InputField.SendOnValueChanged(), UnityEngine.UI.InputField.UpdateLabel(), and UnityEngine.UI.InputField.UpdateTouchKeyboardFromEditChanges().
Referenced by UnityEngine.UI.InputField.KeyPressed().