terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.LateUpdate
LateUpdate()
virtual void UnityEngine.UI.InputField.LateUpdate () inline protected virtual
Definition at line 1090 of file InputField.cs.
        {
            if (this.m_ShouldActivateNextUpdate && !this.m_AllowInput)
            {
                this.ActivateInputFieldInternal();
                return;
            }
            this.AssignPositioningIfNeeded();
            if (this.m_AllowInput)
            {
                bool flag = this.InPlaceEditingChanged();
                CanvasRenderer cachedInputRenderer = this.m_CachedInputRenderer;
                Mesh mesh = this.mesh;
                return;
            }
        }
References UnityEngine.UI.InputField.ActivateInputFieldInternal(), UnityEngine.UI.InputField.AssignPositioningIfNeeded(), UnityEngine.UI.InputField.InPlaceEditingChanged(), j__TPar, UnityEngine.UI.InputField.m_AllowInput, UnityEngine.UI.InputField.m_CachedInputRenderer, UnityEngine.UI.InputField.m_ShouldActivateNextUpdate, and UnityEngine.UI.InputField.mesh.