terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.SetText
SetText()
void UnityEngine.UI.InputField.SetText (string value, bool sendCallback = true) inline private
Definition at line 165 of file InputField.cs.
        {
            bool flag = this.m_Text == value;
            string text;
            if (this.m_LineType == InputField.LineType.SingleLine)
            {
                string text2;
                text = text2.Replace("\n", "").Replace("\t", "");
            }
            if (this.m_OnValidateInput != null)
            {
                this.m_Text = "";
                return;
            }
            if (this.m_CharacterValidation != InputField.CharacterValidation.None)
            {
                this.m_Text = "";
                int characterLimit = this.m_CharacterLimit;
                int stringLength = text._stringLength;
                this.m_CaretSelectPosition = stringLength;
                this.m_CaretPosition = stringLength;
                int num = Math.Min(characterLimit, stringLength);
                long num2 = 0L;
                int stringLength2 = this.m_Text._stringLength;
                char c = text[(int)num2];
                string text4;
                string text3 = this.m_Text + text4;
                this.m_Text = text3;
                return;
            }
            int characterLimit2 = this.m_CharacterLimit;
            int stringLength3 = text._stringLength;
            long num3 = 0L;
            string text5 = text.Substring((int)num3, characterLimit2);
            this.m_Text = text5;
            TouchScreenKeyboard keyboard = this.m_Keyboard;
            if (keyboard != null)
            {
                string text6 = this.m_Text;
                keyboard.text = text6;
            }
            string text7 = this.m_Text;
            int caretPosition = this.m_CaretPosition;
            int stringLength4 = text7._stringLength;
            this.m_CaretSelectPosition = stringLength4;
            this.m_CaretPosition = stringLength4;
        }
References UnityEngine.UI.InputField.caretPosition, UnityEngine.UI.InputField.characterLimit, j__TPar, UnityEngine.L, UnityEngine.UI.InputField.m_CaretPosition, UnityEngine.UI.InputField.m_CharacterLimit, UnityEngine.UI.InputField.m_CharacterValidation, UnityEngine.UI.InputField.m_Keyboard, UnityEngine.UI.InputField.m_LineType, UnityEngine.UI.InputField.m_OnValidateInput, UnityEngine.UI.InputField.m_Text, System.Math.Min(), UnityEngine.UI.InputField.text, and System.value.
Referenced by UnityEngine.UI.InputField.DeactivateInputField(), and UnityEngine.UI.InputField.SetTextWithoutNotify().