terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.UpdateGeometry
UpdateGeometry()
void UnityEngine.UI.InputField.UpdateGeometry () inline private
Definition at line 1836 of file InputField.cs.
        {
            bool isSupported = TouchScreenKeyboard.isSupported;
            bool hideMobileInput;
            if (!this.m_TouchKeyboardAllowsInPlaceEditing)
            {
                RuntimePlatform platform = Application.platform;
                hideMobileInput = this.m_HideMobileInput;
                if (!hideMobileInput)
                {
                    return;
                }
            }
            CanvasRenderer cachedInputRenderer = this.m_CachedInputRenderer;
            if (!hideMobileInput)
            {
            }
            Text textComponent = this.m_TextComponent;
            if (!hideMobileInput)
            {
            }
            string text = base.transform.name + " Input Caret";
            if (2304 == 0)
            {
            }
            Type type;
            Type type2;
            if ((type != null && type == null) || (type2 != null && type2 == null))
            {
                throw new ArrayTypeMismatchException();
            }
            Text textComponent2 = this.m_TextComponent;
            Transform parent = textComponent2.transform.parent;
            Transform transform;
            transform.SetParent(parent);
            Transform transform2;
            transform2.SetAsFirstSibling();
            int layer = base.gameObject.layer;
            RectTransform rectTransform;
            this.caretRectTrans = rectTransform;
            CanvasRenderer canvasRenderer;
            this.m_CachedInputRenderer = canvasRenderer;
            Text textComponent3 = this.m_TextComponent;
            if (textComponent2 == null)
            {
            }
            Material defaultGraphicMaterial = Graphic.defaultGraphicMaterial;
            Texture2D whiteTexture = Texture2D.whiteTexture;
            this.AssignPositioningIfNeeded();
            CanvasRenderer cachedInputRenderer2 = this.m_CachedInputRenderer;
        }
References UnityEngine.UI.InputField.AssignPositioningIfNeeded(), UnityEngine.UI.Graphic.defaultGraphicMaterial, UnityEngine.TouchScreenKeyboard.isSupported, j__TPar, UnityEngine.UI.InputField.m_CachedInputRenderer, UnityEngine.UI.InputField.m_HideMobileInput, UnityEngine.UI.InputField.m_TextComponent, UnityEngine.UI.InputField.m_TouchKeyboardAllowsInPlaceEditing, UnityEngine.Transform.parent, UnityEngine.Application.platform, UnityEngine.Transform.SetAsFirstSibling(), UnityEngine.Transform.SetParent(), UnityEngine.UI.InputField.text, UnityEngine.UI.InputField.textComponent, UnityEngine.Component.transform, UnityEngine.UI.ICanvasElement.transform, and UnityEngine.Texture2D.whiteTexture.
Referenced by UnityEngine.UI.InputField.Rebuild().