terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.KeyPressed
KeyPressed()
InputField.EditState UnityEngine.UI.InputField.KeyPressed (Event evt) inline protected
Definition at line 1247 of file InputField.cs.
        {
            EventModifiers modifiers = evt.modifiers;
            OperatingSystemFamily operatingSystemFamily = SystemInfo.operatingSystemFamily;
            long num = 0L;
            KeyCode keyCode = evt.keyCode;
            int num2 = 1;
            this.MoveUp(num != 0L, num2 != 0);
            string text = this.m_Text;
            int stringLength = text._stringLength;
            this.m_CaretPosition = stringLength;
            int stringLength2 = text._stringLength;
            this.m_CaretSelectPosition = stringLength2;
            if (stringLength2 == 0)
            {
            }
            string systemCopyBuffer = GUIUtility.systemCopyBuffer;
            InputField.LineType lineType = this.m_LineType;
            int num3 = 1;
            this.m_WasCanceled = num3 != 0;
            this.Backspace();
            this.ForwardSpace();
            if (this.m_InputType == InputField.InputType.Standard)
            {
            }
            return "";
        }
References UnityEngine.UI.InputField.Backspace(), UnityEngine.UI.InputField.ForwardSpace(), j__TPar, UnityEngine.L, UnityEngine.UI.InputField.lineType, UnityEngine.UI.InputField.m_InputType, UnityEngine.UI.InputField.m_LineType, UnityEngine.UI.InputField.m_Text, UnityEngine.UI.InputField.MoveUp(), UnityEngine.SystemInfo.operatingSystemFamily, UnityEngine.GUIUtility.systemCopyBuffer, and UnityEngine.UI.InputField.text.
Referenced by UnityEngine.UI.InputField.OnUpdateSelected(), and UnityEngine.UI.InputField.ProcessEvent().