terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.UpdateLabel
UpdateLabel()
void UnityEngine.UI.InputField.UpdateLabel () inline protected
Definition at line 1705 of file InputField.cs.
        {
            int num = 1;
            Text textComponent = this.m_TextComponent;
            if (num == 0)
            {
            }
            Font font = this.m_TextComponent.font;
            if (!this.m_PreventFontCallback)
            {
                int num2 = 1;
                this.m_PreventFontCallback = num2 != 0;
                if (num2 == 0)
                {
                }
                EventSystem current = EventSystem.current;
                GameObject gameObject = base.gameObject;
                GameObject currentSelected = EventSystem.current.m_CurrentSelected;
                bool flag = gameObject == currentSelected;
                string text;
                int stringLength = text._stringLength;
                string text2 = this.m_Text;
                int caretPosition = this.m_CaretPosition;
                int num3 = 1;
                long num4 = 0L;
                this.m_IsCompositionActive = num3 != 0;
                string text3 = text2.Substring((int)num4, caretPosition);
                string text4 = this.m_Text;
                int caretPosition2 = this.m_CaretPosition;
                string text5 = text4.Substring(caretPosition2);
                string text7;
                string text6 = text3 + text7 + text5;
                return;
            }
        }
References UnityEngine.UI.InputField.caretPosition, UnityEngine.EventSystems.EventSystem.current, UnityEngine.UI.Text.font, UnityEngine.Component.gameObject, UnityEngine.GameObject.gameObject, j__TPar, UnityEngine.L, UnityEngine.UI.InputField.m_CaretPosition, UnityEngine.EventSystems.EventSystem.m_CurrentSelected, UnityEngine.UI.InputField.m_PreventFontCallback, UnityEngine.UI.InputField.m_Text, UnityEngine.UI.InputField.m_TextComponent, UnityEngine.UI.InputField.text, and UnityEngine.UI.InputField.textComponent.
Referenced by UnityEngine.UI.InputField.Backspace(), UnityEngine.UI.InputField.ForceLabelUpdate(), UnityEngine.UI.InputField.OnEnable(), UnityEngine.UI.InputField.OnPointerDown(), UnityEngine.UI.InputField.OnUpdateSelected(), and UnityEngine.UI.InputField.SendOnValueChangedAndUpdateLabel().