terraria-cpp2il-methodrecon: UnityEngine.UI.InputField.OnUpdateSelected
OnUpdateSelected()
virtual void UnityEngine.UI.InputField.OnUpdateSelected (BaseEventData eventData) inline virtual
Implements UnityEngine.EventSystems.IUpdateSelectedHandler.
Definition at line 1288 of file InputField.cs.
        {
            bool allowInput = this.m_AllowInput;
            if (allowInput)
            {
                bool flag = Event.PopEvent(this.m_ProcessingEvent);
                EventType rawType = this.m_ProcessingEvent.rawType;
                string text;
                if (allowInput && text._stringLength == 0)
                {
                    char character = this.m_ProcessingEvent.character;
                    if (this.m_ProcessingEvent.modifiers == EventModifiers.None)
                    {
                        bool flag2 = Event.PopEvent(this.m_ProcessingEvent);
                        this.UpdateLabel();
                        return;
                    }
                }
                Event processingEvent = this.m_ProcessingEvent;
                InputField.EditState editState = this.KeyPressed(processingEvent);
                if (!this.m_WasCanceled)
                {
                    this.SendOnSubmit();
                }
                this.DeactivateInputField();
                return;
            }
        }
References UnityEngine.Event.character, UnityEngine.UI.InputField.DeactivateInputField(), j__TPar, UnityEngine.UI.InputField.KeyPressed(), UnityEngine.UI.InputField.m_AllowInput, UnityEngine.UI.InputField.m_ProcessingEvent, UnityEngine.UI.InputField.m_WasCanceled, UnityEngine.Event.modifiers, UnityEngine.Event.PopEvent(), UnityEngine.Event.rawType, UnityEngine.UI.InputField.SendOnSubmit(), UnityEngine.UI.InputField.text, and UnityEngine.UI.InputField.UpdateLabel().