terraria-cpp2il-methodrecon: GUIPageIconGrouping.PageOver
PageOver()
void GUIPageIconGrouping.PageOver (int index) inline private
Definition at line 433 of file GUIPageIconGrouping.cs.
    {
        List<GUIPageIcons.Category> options = this._options;
        this.HoverCategory = options;
        if (!true)
        {
        }
        bool mouseLeft = Main.mouseLeft;
        if (!true)
        {
        }
        bool mouseLeftRelease = Main.mouseLeftRelease;
        GUIPageIcons.Category selectedCategory = this.SelectedCategory;
        List<GUIPageIcons.Category> options2 = this._options;
        bool controllerModeLocked = XNAUnityRunner.ControllerModeLocked;
        GUIPageIcons.Category selectedCategory2 = this.SelectedCategory;
        InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
        GUIPageIcons.Category selectedCategory3 = this.SelectedCategory;
        bool flag = GUIPageIconGrouping.CanCollapse(this.SelectedCategory);
        GUIPageIcons.Category selectedCategory4 = this.SelectedCategory;
        bool flag2 = active.IsCollapsed(selectedCategory4);
        GUIPageIcons.Category selectedCategory5 = this.SelectedCategory;
        active.SetCollapsed(selectedCategory5, true);
    }
References _options, InterfaceStyles_Layout.Active, CanCollapse(), XNAUnityRunner.ControllerModeLocked, InterfaceProfile_Layout.IsCollapsed(), j__TPar, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, System.options, SelectedCategory, and InterfaceProfile_Layout.SetCollapsed().