terraria-cpp2il-methodrecon: GUIPageIconGrouping.LoadPageAnchor
LoadPageAnchor()
void GUIPageIconGrouping.LoadPageAnchor () inline
Definition at line 15 of file GUIPageIconGrouping.cs.
    {
        RightSideHUDAnchorUpdator.Update();
        ControlAnchor.ControlId anchorControl = this.AnchorControl;
        Vector2 location = this.Location;
        float x = this.Location.X;
        float y = this.Location.Y;
        if (!true)
        {
        }
        LayoutCalculator.AnchorType anchor = this.Anchor;
        this.LoadPageRegion();
    }
References Anchor, AnchorControl, j__TPar, LoadPageRegion(), Location, RightSideHUDAnchorUpdator.Update(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by GUIBuffs.Draw(), GUIHotbar.Draw(), Draw(), DrawEditOptions(), DrawOptions(), GUIHotbar.GetRegion(), GUIBuilderAccToggles.IsOverBuilderTools(), GUIVirtualInputController.IsOverGroupRegion(), GUIPageContentController.LoadPageAnchor(), and LoadSettingAnchor().