terraria-cpp2il-methodrecon: GUIPageIconGrouping.Draw
Draw()
void GUIPageIconGrouping.Draw () inline
Definition at line 382 of file GUIPageIconGrouping.cs.
    {
        this.LoadPageAnchor();
        Rectangle rectangle;
        Vector2 vector = rectangle.Size();
        long num = 0L;
        this.LoadColourState(num != 0L);
        this.DrawPageIcons();
        this.LoadPageAnchor();
        this.LoadColourState(true);
        this.DrawPageContent();
        bool controllerModeLocked = XNAUnityRunner.ControllerModeLocked;
    }
References XNAUnityRunner.ControllerModeLocked, DrawPageContent(), DrawPageIcons(), j__TPar, System.L, LoadColourState(), and LoadPageAnchor().