terraria-cpp2il-methodrecon: System.Xml.XmlAutoDetectWriter.CreateWrappedWriter
CreateWrappedWriter()
void System.Xml.XmlAutoDetectWriter.CreateWrappedWriter (XmlOutputMethod outMethod) inline private
Definition at line 324 of file XmlAutoDetectWriter.cs.
        {
            XmlWriterSettings xmlWriterSettings = this.writerSettings;
            xmlWriterSettings.outputMethod = outMethod;
            TriState indent = xmlWriterSettings.indent;
            int num = 1;
            xmlWriterSettings.Indent = num != 0;
            XmlWriterSettings xmlWriterSettings2 = this.writerSettings;
            int num2 = 1;
            xmlWriterSettings2.isReadOnly = num2 != 0;
            TextWriter textWriter = this.textWriter;
            if (textWriter != null)
            {
                if (XmlWriter.Create(textWriter, xmlWriterSettings2) == null)
                {
                    return;
                }
            }
            else if (XmlWriter.Create(this.strm, xmlWriterSettings2) != null)
            {
            }
            XmlEventCache xmlEventCache = this.eventCache;
            XmlEventCache xmlEventCache2;
            XmlRawWriter xmlRawWriter;
            if (xmlEventCache.singleText.idxStr == 0)
            {
                int num3 = xmlEventCache.NewEvent();
                XmlEventCache.XmlEvent[] pageCurr = xmlEventCache.pageCurr;
                xmlEventCache2 = this.eventCache;
                xmlRawWriter = this.wrapped;
            }
            xmlEventCache2.EventsToWriter(xmlRawWriter);
            OnRemoveWriter onRemoveWriter = this.onRemove;
            if (onRemoveWriter != null)
            {
                XmlRawWriter xmlRawWriter2 = this.wrapped;
                IntPtr invoke_impl = onRemoveWriter.invoke_impl;
                IntPtr method_code = onRemoveWriter.method_code;
                IntPtr method = onRemoveWriter.method;
                return;
            }
        }
References System.Xml.XmlWriter.Create(), System.Xml.XmlAutoDetectWriter.eventCache, System.Xml.XmlEventCache.EventsToWriter(), System.Xml.XmlWriterSettings.indent, j__TPar, System.Xml.XmlAutoDetectWriter.onRemove, System.Xml.XmlAutoDetectWriter.textWriter, System.Xml.XmlAutoDetectWriter.wrapped, and System.Xml.XmlAutoDetectWriter.writerSettings.
Referenced by System.Xml.XmlAutoDetectWriter.EnsureWrappedWriter().