terraria-cpp2il-methodrecon: Terraria.GameContent.TilePaintSystemV2.InitShader
InitShader()
Effect Terraria.GameContent.TilePaintSystemV2.InitShader (TreePaintingSettings settings) inline private
Definition at line 93 of file TilePaintSystemV2.cs.
        {
            TileShader[] array = this.specialShaders;
            TileShader tileShader = Microsoft.Xna.Framework.Graphics.TileShader.CreateNew();
            if (tileShader == null || tileShader != null)
            {
                EffectParameter effectParameter = tileShader.<Parameters>k__BackingField["leafHueTestOffset"];
                float hueTestOffset = settings.HueTestOffset;
                EffectParameter effectParameter2 = tileShader.<Parameters>k__BackingField["leafMinHue"];
                float specialGroupMinimalHueValue = settings.SpecialGroupMinimalHueValue;
                EffectParameter effectParameter3 = tileShader.<Parameters>k__BackingField["leafMaxHue"];
                float specialGroupMaximumHueValue = settings.SpecialGroupMaximumHueValue;
                EffectParameter effectParameter4 = tileShader.<Parameters>k__BackingField["leafMinSat"];
                float specialGroupMinimumSaturationValue = settings.SpecialGroupMinimumSaturationValue;
                EffectParameter effectParameter5 = tileShader.<Parameters>k__BackingField["leafMaxSat"];
                float specialGroupMaximumSaturationValue = settings.SpecialGroupMaximumSaturationValue;
                EffectParameter effectParameter6 = tileShader.<Parameters>k__BackingField["invertSpecialGroupResult"];
                bool invertSpecialGroupResult = settings.InvertSpecialGroupResult;
                effectParameter6.SetValue(invertSpecialGroupResult);
                int num = 1;
                EffectPass[] tileShaders = this.TileShaders;
                TreePaintingSettings.TreePaintingSettingsId id = settings.Id;
                EffectPass realShader = this.GetRealShader(num, settings);
                if (realShader == null || realShader != null)
                {
                }
            }
            throw new ArrayTypeMismatchException();
        }
References System.array, Microsoft.Xna.Framework.Graphics.TileShader.CreateNew(), Terraria.GameContent.TilePaintSystemV2.GetRealShader(), Terraria.GameContent.TreePaintingSettings.HueTestOffset, Terraria.GameContent.TreePaintingSettings.Id, Terraria.GameContent.TreePaintingSettings.InvertSpecialGroupResult, j__TPar, Terraria.GameContent.TreePaintingSettings.SpecialGroupMaximumHueValue, Terraria.GameContent.TreePaintingSettings.SpecialGroupMaximumSaturationValue, Terraria.GameContent.TreePaintingSettings.SpecialGroupMinimalHueValue, Terraria.GameContent.TreePaintingSettings.SpecialGroupMinimumSaturationValue, Terraria.GameContent.TilePaintSystemV2.specialShaders, and Terraria.GameContent.TilePaintSystemV2.TileShaders.
Referenced by Terraria.GameContent.TilePaintSystemV2.CreateTileShaders(), and Terraria.GameContent.TilePaintSystemV2.GetRealShader().