terraria-cpp2il-methodrecon: Terraria.GameContent.TilePaintSystemV2.GetRealShader
GetRealShader()
EffectPass Terraria.GameContent.TilePaintSystemV2.GetRealShader (int paintColor, TreePaintingSettings settings) inline
Definition at line 170 of file TilePaintSystemV2.cs.
        {
            int num2;
            do
            {
                int num = 1;
                bool useSpecialGroups = settings.UseSpecialGroups;
                bool useWallShaderHacks = settings.UseWallShaderHacks;
                if (num == 0)
                {
                }
                if (num2 != 0)
                {
                    Effect tileShader = this.TileShader;
                }
            }
            while (this.specialShaders.<Name>k__BackingField != null);
            return this.InitShader(settings).<CurrentTechnique>k__BackingField.<Passes>k__BackingField[num2];
        }
References Terraria.GameContent.TilePaintSystemV2.InitShader(), j__TPar, System.Name, Terraria.GameContent.TilePaintSystemV2.specialShaders, Terraria.GameContent.TilePaintSystemV2.TileShader, Terraria.GameContent.TreePaintingSettings.UseSpecialGroups, and Terraria.GameContent.TreePaintingSettings.UseWallShaderHacks.
Referenced by Terraria.GameContent.TilePaintSystemV2.GetWallEffect(), and Terraria.GameContent.TilePaintSystemV2.InitShader().