terraria-cpp2il-methodrecon: UnityEngine.UI.HorizontalOrVerticalLayoutGroup.GetChildSizes
GetChildSizes()
void UnityEngine.UI.HorizontalOrVerticalLayoutGroup.GetChildSizes (RectTransform child, int axis, bool controlSize, bool childForceExpand, [Out] float min, [Out] float preferred, [Out] float flexible) inline private inherited
Definition at line 189 of file HorizontalOrVerticalLayoutGroup.cs.
        {
            if (axis != 0)
            {
                float minHeight = LayoutUtility.GetMinHeight(child);
                float preferredHeight = LayoutUtility.GetPreferredHeight(child);
                float flexibleHeight = LayoutUtility.GetFlexibleHeight(child);
                return;
            }
            float preferredWidth = LayoutUtility.GetPreferredWidth(child);
            float flexibleWidth = LayoutUtility.GetFlexibleWidth(child);
        }
References UnityEngine.UI.LayoutGroup.flexibleHeight, UnityEngine.UI.LayoutGroup.flexibleWidth, UnityEngine.UI.LayoutUtility.GetFlexibleHeight(), UnityEngine.UI.LayoutUtility.GetFlexibleWidth(), UnityEngine.UI.LayoutUtility.GetMinHeight(), UnityEngine.UI.LayoutUtility.GetPreferredHeight(), UnityEngine.UI.LayoutUtility.GetPreferredWidth(), UnityEngine.UI.LayoutGroup.minHeight, UnityEngine.UI.LayoutGroup.preferredHeight, and UnityEngine.UI.LayoutGroup.preferredWidth.