terraria-cpp2il-methodrecon: Terraria.Lang.GetNPCNameValue
GetNPCNameValue()
static string Terraria.Lang.GetNPCNameValue (int netID) inline static
Definition at line 93 of file Lang.cs.
        {
            if (!true)
            {
            }
            return Lang.GetNPCName(42178960).<Value>k__BackingField;
        }
References Terraria.Lang.GetNPCName().
Referenced by GUIAccessoryInfo.BuildInfoAccs(), Terraria.NPC.GetFullnameByID(), and Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.GetHoverText().