terraria-cpp2il-methodrecon: Ionic.Zip.ZipEntry._SetTimes
_SetTimes()
void Ionic.Zip.ZipEntry._SetTimes (string fileOrDirectory, bool isFile) inline package
Definition at line 1425 of file ZipEntry.cs.
        {
            if (this._ntfsTimesAreSet)
            {
                DateTime atime = this._Atime;
                DateTime ctime = this._Ctime;
                DateTime mtime = this._Mtime;
                if (NetCfFile.SetTimes(fileOrDirectory, ctime, atime, mtime) != 0)
                {
                    string fileNameInArchive = this._FileNameInArchive;
                    if (fileNameInArchive != null && fileNameInArchive == null)
                    {
                        throw new ArrayTypeMismatchException();
                    }
                    if (fileOrDirectory != null && fileOrDirectory == null)
                    {
                        throw new ArrayTypeMismatchException();
                    }
                    ZipFile zf = this._container._zf;
                    if (zf != null && zf._StatusMessageTextWriter != null)
                    {
                        return;
                    }
                }
            }
            else
            {
                DateTime dateTime2;
                DateTime dateTime = SharedUtilities.AdjustTime_Reverse(dateTime2);
                if (NetCfFile.SetLastWriteTime(fileOrDirectory, dateTime) != 0)
                {
                    string fileNameInArchive2 = this._FileNameInArchive;
                    if (fileNameInArchive2 != null && fileNameInArchive2 == null)
                    {
                        throw new ArrayTypeMismatchException();
                    }
                    if (fileOrDirectory != null && fileOrDirectory == null)
                    {
                        throw new ArrayTypeMismatchException();
                    }
                    ZipFile zf2 = this._container._zf;
                    if (zf2 == null || zf2._StatusMessageTextWriter != null)
                    {
                    }
                }
            }
        }
References Ionic.Zip.ZipEntry._Atime, Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._Ctime, Ionic.Zip.ZipEntry._FileNameInArchive, Ionic.Zip.ZipEntry._Mtime, Ionic.Zip.ZipEntry._ntfsTimesAreSet, Ionic.Zip.ZipFile._StatusMessageTextWriter, Ionic.Zip.ZipContainer._zf, Ionic.Zip.SharedUtilities.AdjustTime_Reverse(), j__TPar, Ionic.Zip.NetCfFile.SetLastWriteTime(), and Ionic.Zip.NetCfFile.SetTimes().