terraria-cpp2il-methodrecon: Ionic.Zip.ZipEntry.ValidateOutput
ValidateOutput()
bool Ionic.Zip.ZipEntry.ValidateOutput (string basedir, Stream outstream, [Out] string outFileName) inline private
Definition at line 1528 of file ZipEntry.cs.
        {
            string fileName;
            while (basedir == null)
            {
                if (fileName != null)
                {
                    return this._IsDirectory || this._FileNameInArchive.EndsWith("/");
                }
            }
            string text = this._FileNameInArchive.Replace("\\", "/").Substring(2);
            bool flag = text.StartsWith("/");
            string text2 = text.Substring(1);
            bool <FlattenFoldersOnExtract>k__BackingField = this._container._zf.<FlattenFoldersOnExtract>k__BackingField;
            if (<FlattenFoldersOnExtract>k__BackingField)
            {
                if (!<FlattenFoldersOnExtract>k__BackingField)
                {
                }
                fileName = Path.GetFileName(text2);
            }
            if (!<FlattenFoldersOnExtract>k__BackingField)
            {
            }
            string text3 = Path.Combine(basedir, fileName).Replace("/", "\\");
            if (!this._IsDirectory)
            {
                bool flag2 = this._FileNameInArchive.EndsWith("/");
            }
            ExtractExistingFileAction extractExistingFileAction = this.<ExtractExistingFile>k__BackingField;
            bool flag3;
            return flag3;
        }
References Ionic.Zip.ZipEntry._container, Ionic.Zip.ZipEntry._FileNameInArchive, Ionic.Zip.ZipEntry._IsDirectory, Ionic.Zip.ZipContainer._zf, System.IO.Path.Combine(), Ionic.Zip.ZipEntry.ExtractExistingFile, System.IO.Path.GetFileName(), j__TPar, Ionic.Zip.ZipEntry.k__BackingField, and System.text.
Referenced by Ionic.Zip.ZipEntry.InternalExtract().