terraria-cpp2il-methodrecon: Mono.Security.X509.PKCS12.GetAttributes
GetAttributes() [1/2]
IDictionary Mono.Security.X509.PKCS12.GetAttributes (AsymmetricAlgorithm aa) inline
Definition at line 963 of file PKCS12.cs.
        {
            ASN1 asn;
            byte[] value = asn.Value;
            byte[] array;
            RSA rsa = PKCS8.PrivateKeyInfo.DecodeRSA(array);
            byte[] array2;
            RSA rsa2 = PKCS8.PrivateKeyInfo.DecodeRSA(array2);
            long num = 0L;
            long num2 = 0L;
            byte[] array3;
            Array.Clear(array3, (int)num2, (int)num);
            long num3 = 0L;
            long num4 = 0L;
            long num5 = 0L;
            Array.Clear(array2, (int)num5, (int)num3);
            long num6 = 0L;
            Array.Clear(array3, (int)num6, (int)num3);
            while (num4 == 0L)
            {
            }
            bool flag;
            while (!flag)
            {
            }
            long num7 = 0L;
            ASN1 asn2;
            if (asn2.elist != null)
            {
            }
            ASN1 asn3 = asn2[(int)num7];
            long num8 = 0L;
            string text = ASN1Convert.ToOid(asn3[(int)num8]);
            int num9 = 1;
            ASN1 asn4 = asn3[num9];
            long num10 = 0L;
            if (asn4.elist != null)
            {
            }
            byte[] value2 = asn4[(int)num10].Value;
            if (!false)
            {
                throw new InvalidCastException();
            }
            throw new OutOfMemoryException();
        }
References System.array, System.Array.Clear(), Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.DecodeRSA(), j__TPar, System.L, System.text, Mono.Security.ASN1Convert.ToOid(), Mono.Security.ASN1.Value, and System.value.