terraria-cpp2il-methodrecon: Mono.Security.X509.PKCS12.Decode
Decode()
void Mono.Security.X509.PKCS12.Decode (byte[] data) inline private
Definition at line 40 of file PKCS12.cs.
        {
            ASN1 asn;
            byte nTag = asn.m_nTag;
            bool flag;
            if (flag)
            {
                ASN1 asn2;
                byte nTag2 = asn2.m_nTag;
                long num = 0L;
                byte nTag3 = asn2[(int)num].m_nTag;
                long num2 = 0L;
                ASN1 asn3;
                bool flag2 = ASN1Convert.ToOid(asn3[(int)num2]) != "1.3.14.3.2.26";
                int num3 = 1;
                ASN1 asn4;
                byte[] value = asn4.Value;
                int num4 = 1;
                ASN1 asn5 = asn2[num4];
                byte nTag4 = asn5.m_nTag;
                this._iterations = num3;
                if (asn2.elist != null)
                {
                    int num5 = 2;
                    ASN1 asn6 = asn2[num5];
                    byte nTag5 = asn6.m_nTag;
                    int num6 = ASN1Convert.ToInt32(asn6);
                    this._iterations = num6;
                }
                ASN1 asn7;
                byte[] value2 = asn7.Value;
                byte[] password = this._password;
                byte[] value3 = asn5.Value;
                int iterations = this._iterations;
                return;
            }
            ASN1 asn8;
            byte[] value4 = asn8.Value;
            ASN1 asn9;
            byte[] value5 = asn9.Value;
        }
References Mono.Security.X509.PKCS12._iterations, Mono.Security.X509.PKCS12._password, j__TPar, System.L, Mono.Security.ASN1.m_nTag, Mono.Security.ASN1Convert.ToInt32(), Mono.Security.ASN1Convert.ToOid(), Mono.Security.ASN1.Value, and System.value.
Referenced by Mono.Security.X509.PKCS12.PKCS12(), Mono.Security.X509.PKCS12.PKCS12(), and Mono.Security.X509.PKCS12.PKCS12().