terraria-cpp2il-methodrecon: Mono.Security.X509.PKCS12.GetAsymmetricAlgorithm
GetAsymmetricAlgorithm()
AsymmetricAlgorithm Mono.Security.X509.PKCS12.GetAsymmetricAlgorithm (IDictionary attrs) inline
Definition at line 813 of file PKCS12.cs.
        {
            ArrayList safeBags = this._safeBags;
            if (safeBags != null)
            {
            }
            object[] items = safeBags._items;
            long num = 0L;
            ASN1 asn;
            if (asn.elist != null)
            {
            }
            ASN1 asn2 = asn[(int)num];
            long num2 = 0L;
            string text = ASN1Convert.ToOid(asn2[(int)num2]);
            if (attrs != null)
            {
                int num3 = 1;
                ASN1 asn3 = asn2[num3];
                if (asn3.elist != null)
                {
                }
                long num4 = 0L;
                if (asn3.elist != null)
                {
                }
                ASN1 asn4 = asn3[(int)num4];
                if (attrs == null || attrs == null)
                {
                }
                byte[] value = asn4.Value;
                if (asn3.elist != null)
                {
                }
            }
            if (asn.elist != null)
            {
            }
            ASN1 asn5;
            byte[] value2 = asn5.Value;
            byte[] array;
            RSA rsa = PKCS8.PrivateKeyInfo.DecodeRSA(array);
            long num5 = 0L;
            if (rsa != null)
            {
            }
            if (num5 == 0L)
            {
                int keySizeValue = rsa.KeySizeValue;
                byte[] array2;
                RSA rsa2 = PKCS8.PrivateKeyInfo.DecodeRSA(array2);
                long num6 = 0L;
                long num7 = 0L;
                Array.Clear(array2, (int)num7, (int)num6);
                throw new InvalidCastException();
            }
            throw new OutOfMemoryException();
        }
References System.Collections.ArrayList._items, Mono.Security.X509.PKCS12._safeBags, System.array, System.Array.Clear(), Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.DecodeRSA(), j__TPar, System.Security.Cryptography.AsymmetricAlgorithm.KeySizeValue, System.L, System.text, Mono.Security.ASN1Convert.ToOid(), Mono.Security.ASN1.Value, and System.value.