terraria-cpp2il-methodrecon: Mono.Security.X509.PKCS12.GetBytes
GetBytes()
byte[] Mono.Security.X509.PKCS12.GetBytes () inline
Definition at line 428 of file PKCS12.cs.
        {
            ASN1 asn;
            byte[] value = asn.Value;
            ASN1 asn2;
            byte[] value2 = asn2.Value;
            if (!false)
            {
                X509CertificateCollection x509CertificateCollection;
                X509CertificateCollection.X509CertificateEnumerator enumerator = x509CertificateCollection.GetEnumerator();
                long num = 0L;
                if (num != 0L)
                {
                }
                if (num != 0L)
                {
                }
                X509Certificate x509Certificate;
                byte[] encodedcert = x509Certificate.m_encodedcert;
                long num2 = 0L;
                int num3 = 9;
                if (num != 0L)
                {
                }
                if (num2 != 0L)
                {
                    throw new OutOfMemoryException();
                }
                if (num3 == 0)
                {
                    throw new InvalidCastException();
                }
                long num4 = 0L;
                if (num != 0L)
                {
                }
                if (num4 == 0L)
                {
                    int num5;
                    if (num5 == 0)
                    {
                        if (num != 0L)
{
                        }
                        if (num != 0L)
{
                        }
                        X509CertificateCollection x509CertificateCollection2;
                        X509CertificateCollection.X509CertificateEnumerator enumerator2 = x509CertificateCollection2.GetEnumerator();
                        long num6 = 0L;
                        bool flag = enumerator2.MoveNext();
                        byte[] encodedcert2 = enumerator2.Current.m_encodedcert;
                        long num7 = 0L;
                        int num8 = 15;
                        if (enumerator2 == null || num6 != 0L)
{
                        }
                        if (num7 != 0L)
{
                            throw new OutOfMemoryException();
                        }
                        if (num8 == 0)
{
                        }
                        long num9 = 0L;
                        if (num6 != 0L)
{
                        }
                        if (num9 == 0L)
{
                            if (num6 != 0L)
{
                            }
                            if (num6 != 0L)
{
                            }
                            long num10 = 0L;
                            int num11 = 19;
                            if (num10 == 0L)
{
                                if (num11 != 0)
{
                                    goto IL_019F;
                                }
                                long num12 = 0L;
                                int num13 = 22;
                                if (num12 != 0L)
{
                                    goto IL_020B;
                                }
                                if (num13 != 0)
{
                                    goto IL_019F;
                                }
                                long num14 = 0L;
                                int num15 = 26;
                                if (num14 == 0L)
{
                                    if (num15 != 0)
{
                                        goto IL_019F;
                                    }
                                    if ("UI.SpawnPoint" != null)
{
                                        PKCS7.ContentInfo contentInfo;
                                        ASN1 asn3 = contentInfo.GetASN1();
                                        ASN1 asn4 = asn3.Add(asn3);
                                    }
                                    long num16 = 0L;
                                    int num17 = 31;
                                    if (num16 == 0L)
{
                                        if (num17 != 0)
{
                                            goto IL_019F;
                                        }
                                        ASN1 asn6;
                                        ASN1 asn5 = asn6.Add(asn6);
                                        long num18 = 0L;
                                        int num19 = 35;
                                        if (num18 == 0L)
{
                                            if (num19 != 0)
{
                                                goto IL_019F;
                                            }
                                            PKCS7.ContentInfo contentInfo2;
                                            ASN1 asn7 = contentInfo2.GetASN1();
                                            ASN1 asn8 = asn7.Add(asn7);
                                            if ("1.2.840.113549.1.7.1" != null)
{
                                                RandomNumberGenerator randomNumberGenerator = RandomNumberGenerator.Create();
                                                ASN1 asn9;
                                                byte[] value3 = asn9.Value;
                                                ASN1 asn10 = ASN1Convert.FromOid("1.3.14.3.2.26");
                                            }
                                            ASN1 asn11;
                                            if (asn11 != null)
{
                                                goto IL_019F;
                                            }
                                            goto IL_019F;
                                        }
                                    }
                                }
                            }
                            throw new OutOfMemoryException();
                        }
                        throw new OutOfMemoryException();
                    }
                    IL_019F:
                    long num20 = 0L;
                    long num21 = 0L;
                    if (num20 != 0L)
                    {
                        long value4 = num20.m_value;
                        if (num20 != 0L)
{
                            throw new OutOfMemoryException();
                        }
                        long num22 = 0L;
                        long num23;
                        if (num23 != 0L)
{
                            long value5 = num23.m_value;
                        }
                        if (num22 != 0L)
{
                            throw new OutOfMemoryException();
                        }
                    }
                    else
                    {
                        if (num21 != 0L)
{
                            throw new OutOfMemoryException();
                        }
                        long num23 = 0L;
                        long num24;
                        if (num24 != 0L)
{
                            long value6 = num24.m_value;
                        }
                        if (num23 != 0L)
{
                            throw new OutOfMemoryException();
                        }
                    }
                    throw new OutOfMemoryException();
                }
                throw new OutOfMemoryException();
            }
            IL_020B:
            throw new OutOfMemoryException();
        }
References Mono.Security.ASN1.Add(), System.Security.Cryptography.RandomNumberGenerator.Create(), Mono.Security.ASN1Convert.FromOid(), Mono.Security.PKCS7.ContentInfo.GetASN1(), j__TPar, System.L, Mono.Security.X509.X509CertificateCollection.X509CertificateEnumerator.MoveNext(), Mono.Security.ASN1.Value, System.value, and Mono.Security.X509.PKCS12.x509Certificate.
Referenced by Mono.Security.X509.PKCS12.SaveToFile().