terraria-cpp2il-methodrecon: System.Net.MonoChunkParser.InternalWrite
InternalWrite()
void System.Net.MonoChunkParser.InternalWrite (byte[] buffer, int offset, int size) inline private
Definition at line 55 of file MonoChunkParser.cs.
        {
            MonoChunkParser.State state = this.state;
            MonoChunkParser.State state2 = this.GetChunkSize(buffer, offset, size);
            this.state = state2;
            StringBuilder stringBuilder = this.saved;
            long num = 0L;
            stringBuilder.Length = (int)num;
            MonoChunkParser.State state3 = this.state;
            MonoChunkParser.State state4 = this.ReadBody(buffer, offset, size);
            this.state = state4;
            MonoChunkParser.State state5 = this.ReadCRLF(buffer, offset, size);
            this.state = state5;
            MonoChunkParser.State state6 = this.ReadTrailer(buffer, offset, size);
            this.state = state6;
            StringBuilder stringBuilder2 = this.saved;
            long num2 = 0L;
            stringBuilder2.Length = (int)num2;
        }
References System.Net.MonoChunkParser.GetChunkSize(), j__TPar, System.L, System.offset, System.Net.MonoChunkParser.ReadBody(), System.Net.MonoChunkParser.ReadCRLF(), System.Net.MonoChunkParser.ReadTrailer(), System.Net.MonoChunkParser.saved, and System.Net.MonoChunkParser.state.
Referenced by System.Net.MonoChunkParser.Write(), and System.Net.MonoChunkParser.WriteAndReadBack().