terraria-cpp2il-methodrecon: GUIControllerHairStylist.Activate
Activate()
void GUIControllerHairStylist.Activate () inline
Implements GUIControllerItem.
Definition at line 14 of file GUIControllerHairStylist.cs.
    {
        int myPlayer = Main.myPlayer;
        int myPlayer2 = Main.myPlayer;
        this.UpdateScroll();
        int num = 2;
        this.itemSlider = num;
    }
References j__TPar, Terraria.Main.myPlayer, and UpdateScroll().
Referenced by GUIHairWindow.Draw(), and GUIHairWindow.DrawCategoryButtons().