terraria-cpp2il-methodrecon: InControl.InputManager.UpdateInternal
UpdateInternal()
static void InControl.InputManager.UpdateInternal () inline static package
Definition at line 543 of file InputManager.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            InputManager.AssertIsSetup();
            if (num != 0)
            {
            }
            int num2 = 1;
            if (num2 == 0)
            {
            }
            if (num2 != 0)
            {
                if (num2 == 0)
                {
                }
                InputManager.UpdateCurrentTime();
                int num3 = 1;
                if (num3 == 0)
                {
                }
                InputDevice inputDevice = InputManager.ActiveDevice;
                InputManager.UpdateActiveDevice();
                InputDevice inputDevice2 = InputManager.ActiveDevice;
                if (num3 == 0)
                {
                }
                ulong <LastInputTick>k__BackingField;
                if (inputDevice != null)
                {
                    if (num3 == 0)
                    {
                    }
                    InputDevice inputDevice3 = InputManager.ActiveDevice;
                    <LastInputTick>k__BackingField = inputDevice.<LastInputTick>k__BackingField;
                    string <Meta>k__BackingField = inputDevice.<Meta>k__BackingField;
                    InputDeviceStyle <DeviceStyle>k__BackingField = inputDevice.<DeviceStyle>k__BackingField;
                }
                if (<LastInputTick>k__BackingField == 0UL)
                {
                }
                if (<LastInputTick>k__BackingField != 0UL)
                {
                }
            }
        }
References InControl.InputManager.ActiveDevice, InControl.InputManager.AssertIsSetup(), j__TPar, InControl.InputManager.k__BackingField, InControl.InputManager.UpdateActiveDevice(), and InControl.InputManager.UpdateCurrentTime().
Referenced by InControl.InControlManager.FixedUpdate(), InControl.InputManager.OnLevelWasLoaded(), InControl.InControlManager.Update(), and InControl.InputManager.Update().