terraria-cpp2il-methodrecon: InControl.InputManager.AddDeviceManager
AddDeviceManager()
static void InControl.InputManager.AddDeviceManager (InputDeviceManager deviceManager) inline static
Definition at line 692 of file InputManager.cs.
        {
            if (!true)
            {
            }
            InputManager.AssertIsSetup();
            Type type = deviceManager.GetType();
            string text;
            Logger.LogError(text);
        }
References InControl.InputManager.AssertIsSetup(), System.Type.GetType(), j__TPar, InControl.Logger.LogError(), and System.text.
Referenced by InControl.NativeInputDeviceManager.Enable().