terraria-cpp2il-methodrecon: System.CurrentSystemTimeZone.GetCachedDaylightChanges
GetCachedDaylightChanges()
DaylightTime System.CurrentSystemTimeZone.GetCachedDaylightChanges (int year) inline private
Definition at line 79 of file CurrentSystemTimeZone.cs.
        {
            Hashtable cachedDaylightChanges = this.m_CachedDaylightChanges;
            DaylightTime daylightTime = CurrentSystemTimeZone.CreateDaylightChanges(year);
            Hashtable cachedDaylightChanges2 = this.m_CachedDaylightChanges;
            Monitor.Enter(cachedDaylightChanges2, true);
            Hashtable cachedDaylightChanges3 = this.m_CachedDaylightChanges;
            Hashtable cachedDaylightChanges4 = this.m_CachedDaylightChanges;
            long num = 0L;
            Monitor.Exit(cachedDaylightChanges2);
            if (num == 0L)
            {
                if (this.m_CachedDaylightChanges != null)
                {
                }
                throw new InvalidCastException();
            }
            throw new OutOfMemoryException();
        }
References System.CurrentSystemTimeZone.CreateDaylightChanges(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), j__TPar, System.L, and System.CurrentSystemTimeZone.m_CachedDaylightChanges.
Referenced by System.CurrentSystemTimeZone.GetDaylightChanges().