terraria-cpp2il-methodrecon: UnityEngine.UI.Toggle.SetToggleGroup
SetToggleGroup()
void UnityEngine.UI.Toggle.SetToggleGroup (ToggleGroup newGroup, bool setMemberValue) inline private
Definition at line 95 of file Toggle.cs.
        {
            ToggleGroup group = this.m_Group;
            if (!true)
            {
            }
            this.m_Group.UnregisterToggle(this);
            this.m_Group = newGroup;
            if (!true)
            {
            }
            newGroup.RegisterToggle(this);
            if (this.m_IsOn)
            {
                newGroup.NotifyToggleOn(this, true);
                return;
            }
        }
References UnityEngine.UI.Toggle.group, j__TPar, UnityEngine.UI.Toggle.m_Group, UnityEngine.UI.Toggle.m_IsOn, UnityEngine.UI.ToggleGroup.NotifyToggleOn(), UnityEngine.UI.ToggleGroup.RegisterToggle(), and UnityEngine.UI.ToggleGroup.UnregisterToggle().
Referenced by UnityEngine.UI.Toggle.OnEnable().