terraria-cpp2il-methodrecon: UnityEngine.UI.Toggle.Set
Set()
void UnityEngine.UI.Toggle.Set (bool value, bool sendCallback = true) inline private
Definition at line 137 of file Toggle.cs.
        {
            long num;
            ToggleGroup group2;
            for (;;)
            {
                bool isOn = this.m_IsOn;
                ToggleGroup group = this.m_Group;
                num = 0L;
                bool isActiveAndEnabled = this.m_Group.isActiveAndEnabled;
                bool isOn2 = this.m_IsOn;
                group2 = this.m_Group;
                if (isOn2)
                {
                    break;
                }
                bool flag = group2.AnyTogglesOn();
                if (this.m_Group.m_AllowSwitchOff)
                {
                    goto Block_1;
                }
            }
            this.m_IsOn = true;
            group2.NotifyToggleOn(this, num != 0L);
            return;
            Block_1:
            Toggle.ToggleTransition toggleTransition = this.toggleTransition;
            UISystemProfilerApi.AddMarker("Toggle.value", this);
            Toggle.ToggleEvent toggleEvent = this.onValueChanged;
            bool isOn3 = this.m_IsOn;
        }
References UnityEngine.UISystemProfilerApi.AddMarker(), UnityEngine.UI.ToggleGroup.AnyTogglesOn(), UnityEngine.UI.Toggle.group, UnityEngine.Behaviour.isActiveAndEnabled, UnityEngine.UI.Toggle.isOn, j__TPar, UnityEngine.L, UnityEngine.UI.ToggleGroup.m_AllowSwitchOff, UnityEngine.UI.Toggle.m_Group, UnityEngine.UI.Toggle.m_IsOn, UnityEngine.UI.ToggleGroup.NotifyToggleOn(), UnityEngine.UI.Toggle.onValueChanged, and UnityEngine.UI.Toggle.toggleTransition.
Referenced by UnityEngine.UI.Toggle.OnDidApplyAnimationProperties(), and UnityEngine.UI.Toggle.SetIsOnWithoutNotify().