terraria-cpp2il-methodrecon: DefaultFileAPI.WriteFile
WriteFile()
void DefaultFileAPI.WriteFile (string filename, byte[] fileData) inline
Implements FileAPI.
Definition at line 61 of file DefaultFileAPI.cs.
    {
        if (!true)
        {
        }
        string directoryName = Path.GetDirectoryName(filename);
        bool flag = Directory.Exists(directoryName);
        DirectoryInfo directoryInfo = Directory.CreateDirectory(directoryName);
        File.WriteAllBytes(filename, fileData);
    }
References System.IO.Directory.CreateDirectory(), System.IO.Directory.Exists(), System.IO.Path.GetDirectoryName(), j__TPar, and System.IO.File.WriteAllBytes().