terraria-cpp2il-methodrecon: GUIControllerStaticGridNavigator.NavigateHorizontal
NavigateHorizontal()
GUIControllerItem GUIControllerStaticGridNavigator.NavigateHorizontal (Vector2 navigationVector) inline private
Definition at line 447 of file GUIControllerStaticGridNavigator.cs.
    {
        int num = this.itemColumn;
        GUIControllerStaticGridNavigator.GetGrid grid = this._grid;
        IntPtr invoke_impl = grid.invoke_impl;
        IntPtr method_code = grid.method_code;
        IntPtr method = grid.method;
        int num2 = this.menuRow;
        this.itemRow = num2;
        int num3 = this.itemColumn;
        GUIControllerStaticGridNavigator.GetGrid grid2 = this._grid;
        int num4 = this.itemColumn;
        IntPtr invoke_impl2 = grid2.invoke_impl;
        IntPtr method_code2 = grid2.method_code;
        IntPtr method2 = grid2.method;
        GUIControllerStaticGridNavigator.GetGrid grid3 = this._grid;
        int num5 = this.itemColumn;
        IntPtr invoke_impl3 = grid3.invoke_impl;
        IntPtr method_code3 = grid3.method_code;
        IntPtr method3 = grid3.method;
        int num6 = this.menuRow;
        this.itemRow = num6;
        int num7 = this.itemColumn;
        this.itemColumn = num7;
        GUIControllerStaticGridNavigator.GetGrid grid4 = this._grid;
        int num8 = this.itemColumn;
        IntPtr invoke_impl4 = grid4.invoke_impl;
        IntPtr method_code4 = grid4.method_code;
        IntPtr method4 = grid4.method;
        int num9 = this.menuRow;
        GUIControllerStaticGridNavigator.GetGrid grid5 = this._grid;
        int num10 = this.itemColumn;
        IntPtr invoke_impl5 = grid5.invoke_impl;
        IntPtr method_code5 = grid5.method_code;
        IntPtr method5 = grid5.method;
        GUIControllerStaticGridNavigator.GetCollectionCount menuItemCount = this._menuItemCount;
        IntPtr invoke_impl6 = menuItemCount.invoke_impl;
        IntPtr method_code6 = menuItemCount.method_code;
        IntPtr method6 = menuItemCount.method;
        GUIControllerStaticGridNavigator.GetCollectionCount displayItemCount = this._displayItemCount;
        IntPtr method_code7 = displayItemCount.method_code;
        IntPtr invoke_impl7 = displayItemCount.invoke_impl;
        IntPtr method7 = displayItemCount.method;
        int num11 = this.menuRow;
        long num12 = 0L;
        this.menuRow = num11;
        this.ClampMenu(num12 != 0L);
        int num13 = this.itemRow;
        GUIControllerItem guicontrollerItem = this.NavigateUpOutOfGrid();
        if (guicontrollerItem == null)
        {
            return guicontrollerItem;
        }
        GUIPageContentController controller = this._controller;
        GUIControllerItem guicontrollerItem2;
        return guicontrollerItem2;
    }
References _controller, _displayItemCount, _grid, _menuItemCount, ClampMenu(), itemColumn, itemRow, j__TPar, System.L, menuRow, and NavigateUpOutOfGrid().
Referenced by Navigate().