terraria-cpp2il-methodrecon: GUIControllerStaticGridNavigator.NavigateInto
NavigateInto()
void GUIControllerStaticGridNavigator.NavigateInto (int column, int row) inline
Definition at line 560 of file GUIControllerStaticGridNavigator.cs.
    {
        GUIControllerStaticGridNavigator.GetGrid grid = this._grid;
        IntPtr invoke_impl = grid.invoke_impl;
        IntPtr method_code = grid.method_code;
        IntPtr method = grid.method;
        GUIControllerStaticGridNavigator.GetCollectionCount menuItemCount = this._menuItemCount;
        IntPtr invoke_impl2 = menuItemCount.invoke_impl;
        IntPtr method_code2 = menuItemCount.method_code;
        IntPtr method2 = menuItemCount.method;
        GUIControllerStaticGridNavigator.GetCollectionCount displayItemCount = this._displayItemCount;
        IntPtr invoke_impl3 = displayItemCount.invoke_impl;
        IntPtr method_code3 = displayItemCount.method_code;
        IntPtr method3 = displayItemCount.method;
        GUIControllerStaticGridNavigator.GetGrid grid2 = this._grid;
        IntPtr invoke_impl4 = grid2.invoke_impl;
        IntPtr method_code4 = grid2.method_code;
        IntPtr method4 = grid2.method;
        this.menuRow = grid2;
        this.ClampPosition();
    }
References _displayItemCount, _grid, _menuItemCount, ClampPosition(), and j__TPar.
Referenced by GUIControllerChest4Page.NavigateInto(), and GUIControllerShop4Page.NavigateInto().