terraria-cpp2il-methodrecon: Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain
ParseMain()
void Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain () inline private
Definition at line 41 of file JPath.cs.
        {
            int currentIndex = this._currentIndex;
            this.EatWhitespace();
            string expression = this._expression;
            int currentIndex2 = this._currentIndex;
            int stringLength = expression._stringLength;
            char c = expression[currentIndex2];
            string expression2 = this._expression;
            int stringLength2 = expression2._stringLength;
            int currentIndex3 = this._currentIndex;
            char c2 = expression2[currentIndex2];
            int currentIndex4 = this._currentIndex;
            this._currentIndex = currentIndex;
            List<PathFilter> list = this.<Filters>k__BackingField;
            long num = 0L;
            bool flag = this.ParsePath(list, currentIndex, num != 0L);
            int currentIndex5 = this._currentIndex;
            this.EatWhitespace();
            string expression3 = this._expression;
            int currentIndex6 = this._currentIndex;
            int stringLength3 = expression3._stringLength;
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, Newtonsoft.Json.Linq.JsonPath.JPath.EatWhitespace(), Newtonsoft.Json.Linq.JsonPath.JPath.Filters, j__TPar, Newtonsoft.Json.Linq.JsonPath.JPath.k__BackingField, System.L, System.list, and Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath().
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.JPath().