terraria-cpp2il-methodrecon: UnityEngine.Sprites.DataUtility.GetPadding
GetPadding()
static Vector4 UnityEngine.Sprites.DataUtility.GetPadding (Sprite sprite) inline static
Definition at line 25 of file DataUtility.cs.
        {
            Vector4 padding = sprite.GetPadding();
            Vector4 vector;
            return vector;
        }
References UnityEngine.Sprite.GetPadding().
Referenced by UnityEngine.UI.Image.GenerateSlicedSprite(), and UnityEngine.UI.Image.GetDrawingDimensions().