terraria-cpp2il-methodrecon: UnityEngine.Sprites.DataUtility.GetOuterUV
GetOuterUV()
static Vector4 UnityEngine.Sprites.DataUtility.GetOuterUV (Sprite sprite) inline static
Definition at line 17 of file DataUtility.cs.
        {
            Vector4 outerUVs = sprite.GetOuterUVs();
            Vector4 vector;
            return vector;
        }
References UnityEngine.Sprite.GetOuterUVs(), and j__TPar.
Referenced by UnityEngine.UI.Image.GenerateFilledSprite(), UnityEngine.UI.Image.GenerateSimpleSprite(), UnityEngine.UI.Image.GenerateSlicedSprite(), and UnityEngine.UI.Image.GenerateTiledSprite().