terraria-cpp2il-methodrecon: GUINPCDialogue.Option1Clicked
Option1Clicked()
void GUINPCDialogue.Option1Clicked (int healCost) inline
Definition at line 132 of file GUINPCDialogue.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        int myPlayer = Main.myPlayer;
        bool editSign = Main.editSign;
        if (num != 0)
        {
            int myPlayer2 = Main.myPlayer;
            string npcChatText = Main.npcChatText;
            Sign.TextSign(editSign ? 1 : 0, npcChatText);
            Main.editSign = false;
            bool netClient = Main.NetClient;
            Main.clrInput();
            Main.CloseKeyboard();
            return;
        }
        Main.editSign = true;
        Main.clrInput();
    }
References Terraria.Main.CloseKeyboard(), Terraria.Main.clrInput(), Terraria.Main.editSign, j__TPar, Terraria.Main.myPlayer, Terraria.Main.NetClient, Terraria.Main.npcChatText, and Terraria.Sign.TextSign().