terraria-cpp2il-methodrecon: GUINPCDialogue.Draw
Draw()
void GUINPCDialogue.Draw () inline
Definition at line 263 of file GUINPCDialogue.cs.
    {
        int myPlayer = Main.myPlayer;
        int myPlayer2 = Main.myPlayer;
        string displayString = this.DisplayString;
        this.UpdateText(displayString);
        float y = this.CachedTextSize.Y;
        Rectangle rectangle;
        ControlAnchor.SetGridItemRegion(rectangle);
        GUIControllerNPCDialogue controller = this._controller;
        this._controller.Activate();
        this.DrawNPC();
        float y2 = this.CachedTextSize.Y;
        int myPlayer3 = Main.myPlayer;
        bool editSign = Main.editSign;
    }
References _controller, GUIControllerNPCDialogue.Activate(), CachedTextSize, DisplayString, DrawNPC(), Terraria.Main.editSign, j__TPar, Terraria.Main.myPlayer, ControlAnchor.SetGridItemRegion(), UpdateText(), and Microsoft.Xna.Framework.Vector2.Y.