terraria-cpp2il-methodrecon: GUIBuffs.UpdateBuffNavigation
UpdateBuffNavigation()
void GUIBuffs.UpdateBuffNavigation () inline
Definition at line 74 of file GUIBuffs.cs.
    {
        int num = this.numActiveBuffs;
        int num2 = this.numActiveBuffs;
        if (this.buffActive && this.numActiveBuffs != 0)
        {
            bool flag = this.CanRemoveBuff();
            return;
        }
        int num3 = this.numActiveBuffs;
        float uitextAlpha = XNAUIInputLayer.UITextAlpha;
        if (!this.buffTogglePressed)
        {
            this.NextItem();
            return;
        }
        if (this.buffActive)
        {
            GUIControllerBuff guicontrollerBuff = this.buffController;
            int num4 = this.numActiveBuffs;
            int[] array = this.activeBuffs;
            return;
        }
        int num5 = 1;
        this.buffActive = num5 != 0;
        float uitextAlpha2 = XNAUIInputLayer.UITextAlpha;
        this.buffController.Activate();
        if (num5 == 0)
        {
        }
        DateTime now = DateTime.Now;
        this.NavigationTick = now;
        GUIControllerBuff guicontrollerBuff2 = this.buffController;
        Mouse.UpdateUICursorPoint();
    }
References GUIControllerBuff.Activate(), activeBuffs, System.array, buffActive, buffController, buffTogglePressed, CanRemoveBuff(), j__TPar, NextItem(), System.DateTime.Now, numActiveBuffs, XNAUIInputLayer.UITextAlpha, and Microsoft.Xna.Framework.Input.Mouse.UpdateUICursorPoint().
Referenced by Draw().