terraria-cpp2il-methodrecon: System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark
ChangeTextContentMark()
void System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark (bool value) inline protected inherited
Definition at line 839 of file XmlEncodedRawTextWriter.cs.
        {
            int[] array = this.textContentMarks;
            int num = this.lastMarkPos;
            this.GrowTextContentMarks();
            int num2 = this.lastMarkPos;
            int[] array2 = this.textContentMarks;
            int num3 = this.bufPos;
            this.lastMarkPos = num2;
        }
References System.array, System.Xml.XmlEncodedRawTextWriter.bufPos, System.Xml.XmlEncodedRawTextWriter.GrowTextContentMarks(), j__TPar, System.Xml.XmlEncodedRawTextWriter.lastMarkPos, and System.Xml.XmlEncodedRawTextWriter.textContentMarks.
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteCData(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteChars(), System.Xml.XmlEncodedRawTextWriter.WriteComment(), System.Xml.XmlEncodedRawTextWriter.WriteDocType(), System.Xml.XmlEncodedRawTextWriter.WriteEndAttribute(), System.Xml.XmlEncodedRawTextWriter.WriteEndElement(), System.Xml.XmlEncodedRawTextWriter.WriteEndNamespaceDeclaration(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRef(), System.Xml.XmlEncodedRawTextWriter.WriteFullEndElement(), System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstruction(), System.Xml.XmlEncodedRawTextWriter.WriteRaw(), System.Xml.XmlEncodedRawTextWriter.WriteRaw(), System.Xml.XmlEncodedRawTextWriter.WriteStartAttribute(), System.Xml.XmlEncodedRawTextWriter.WriteStartElement(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclaration(), System.Xml.XmlEncodedRawTextWriter.WriteString(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteWhitespace(), and System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration().