terraria-cpp2il-methodrecon: System.Xml.XmlEncodedRawTextWriter.RawText
RawText() [2/2]
void System.Xml.XmlEncodedRawTextWriter.RawText (string s) inline protected inherited
Definition at line 713 of file XmlEncodedRawTextWriter.cs.
        {
            if (s != null)
            {
                int offsetToStringData = RuntimeHelpers.OffsetToStringData;
                return;
            }
        }
References j__TPar, and System.Runtime.CompilerServices.RuntimeHelpers.OffsetToStringData.
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteDocType(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRef(), System.Xml.XmlEncodedRawTextWriter.WriteFullEndElement(), System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstruction(), System.Xml.XmlEncodedRawTextWriter.WriteStartAttribute(), System.Xml.XmlEncodedRawTextWriter.WriteStartElement(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclaration(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntity(), and System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration().