terraria-cpp2il-methodrecon: System.Security.SecurityElement.ToXml
ToXml()
void System.Security.SecurityElement.ToXml (StringBuilder s, int level) inline private
Definition at line 259 of file SecurityElement.cs.
        {
            string text = this.tag;
            if (this.attributes != null)
            {
                ArrayList arrayList = this.attributes;
                ArrayList arrayList2 = this.attributes;
                if (arrayList2 != null)
                {
                }
                object[] items = arrayList2._items;
                StringBuilder stringBuilder2;
                StringBuilder stringBuilder = stringBuilder2.Append("=\"");
                int size = arrayList2._size;
                string text2;
                StringBuilder stringBuilder3 = stringBuilder.Append(text2).Append("\"");
                ArrayList arrayList3 = this.attributes;
                string newLine = Environment.NewLine;
                ArrayList arrayList4 = this.attributes;
            }
            if (this.text != null)
            {
            }
            ArrayList arrayList5 = this.children;
            if (arrayList5 == null || arrayList5 == null)
            {
                return;
            }
            string text3 = SecurityElement.Escape(this.text);
            StringBuilder stringBuilder5;
            StringBuilder stringBuilder4 = stringBuilder5.Append(text3);
            if (this.children != null)
            {
                string newLine2 = Environment.NewLine;
                ArrayList arrayList6 = this.children;
                return;
            }
            string text4 = this.tag;
            StringBuilder stringBuilder7;
            StringBuilder stringBuilder6 = stringBuilder7.Append(text4).Append(">");
            string newLine3 = Environment.NewLine;
            StringBuilder stringBuilder8 = stringBuilder6.Append(newLine3);
        }
References System.Collections.ArrayList._items, System.Text.StringBuilder.Append(), System.Security.SecurityElement.attributes, System.Security.SecurityElement.children, System.Security.SecurityElement.Escape(), j__TPar, System.Environment.NewLine, System.Security.SecurityElement.tag, and System.Security.SecurityElement.text.
Referenced by System.Security.NamedPermissionSet.ToXml().