terraria-cpp2il-methodrecon: iOS_UserManager.Update
Update()
static void iOS_UserManager.Update () inline static
Definition at line 133 of file iOS_UserManager.cs.
    {
        if (!true)
        {
        }
        if (true)
        {
            if (!true)
            {
            }
            iOS_UserManager.AttemptSignIn();
        }
        bool isEditor = Application.isEditor;
        if (!true)
        {
        }
        if (true)
        {
            DateTime now = DateTime.Now;
            TimeSpan timeSpan;
            double totalSeconds = timeSpan.TotalSeconds;
            float editorSignInProcessTimeout = iOS_UserManager.EditorSignInProcessTimeout;
            bool editorSignedIn = iOS_UserManager.EditorSignedIn;
            iOS_UserManager.PlayerAuthenticated(false);
        }
        iOS_UserManager.UpdateUser();
    }
References AttemptSignIn(), EditorSignedIn, EditorSignInProcessTimeout, UnityEngine.Application.isEditor, j__TPar, System.DateTime.Now, PlayerAuthenticated(), System.TimeSpan.TotalSeconds, and UpdateUser().
Referenced by DrPlatform.IOS.Update().