terraria-cpp2il-methodrecon: GUIItemFilter.DrawSearch
DrawSearch()
void GUIItemFilter.DrawSearch () inline private
Definition at line 125 of file GUIItemFilter.cs.
    {
        !0 instance = PageControllerLayoutDefinition.Instance;
        int num = 320;
        string textValue = Language.GetTextValue("Mobile.Search");
        if (num == 0)
        {
        }
        bool flag = this.editingSearch;
        GUITransactionButton.InputState inputState;
        int num2;
        bool flag2;
        if (inputState != GUITransactionButton.InputState.Clicked)
        {
            if (!this.editingSearch)
            {
                string searchTerm = this.SearchTerm;
                this.editDisplaySearch = searchTerm;
                return;
            }
        }
        else
        {
            num2 = 1;
            int num3 = 1;
            flag2 = this.editingSearch;
            if (!flag2)
            {
                this.editingSearch = num3 != 0;
                if (!flag2)
                {
                }
                Main.clrInput();
                string text = this.editSearch;
                this.editSearchStart = text;
                return;
            }
        }
        if (!flag2)
        {
        }
        if (num != 0)
        {
            return;
        }
        string text2 = this.editSearch;
        int num4 = 312;
        int num5 = 320;
        long num6 = 0L;
        if (num4 == 0)
        {
        }
        int num7 = 1;
        long num8 = 0L;
        long num9 = 0L;
        Rectangle rectangle;
        string inputText = Main.GetInputText(text2, rectangle, (int)num6, num2 != 0, num8 != 0L, num7 != 0, num9 != 0L);
        this.editSearch = inputText;
        if (num5 != 0)
        {
            string text3 = this.editSearchStart;
            this.editSearch = text3;
            if (text3 == null)
            {
            }
            Main.CloseKeyboard();
            return;
        }
        if (num5 == 0)
        {
        }
        Main.CloseKeyboard();
        string text4 = this.editSearch;
        this.SetSearchTerm(text4);
        string text5 = this.editSearch;
        this.editDisplaySearch = text5;
        string text6 = this.editDisplaySearch;
        SpriteFont spriteFont;
        Vector2 vector = spriteFont.MeasureString(text6);
        SpriteFont spriteFont2;
        Vector2 vector2 = spriteFont2.MeasureString("|");
        string text7 = this.editDisplaySearch;
        int num10 = 1;
        string text8 = text7.Substring(num10);
        this.editDisplaySearch = text8;
        string text9 = this.editDisplaySearch;
        SpriteFont spriteFont3;
        Vector2 vector3 = spriteFont3.MeasureString(text9);
        string text10 = this.editDisplaySearch;
    }
References Terraria.Main.CloseKeyboard(), Terraria.Main.clrInput(), editDisplaySearch, editingSearch, editSearch, editSearchStart, Terraria.Main.GetInputText(), Terraria.Localization.Language.GetTextValue(), PageControllerLayoutDefinition< T >.Instance, j__TPar, System.L, SearchTerm, SetSearchTerm(), and System.text.
Referenced by DrawFilter().