terraria-cpp2il-methodrecon: XNAUnityRunner.ExecuteFrame
ExecuteFrame()
void XNAUnityRunner.ExecuteFrame (float timeDelta) inline private
Definition at line 486 of file XNAUnityRunner.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        if (num == 0)
        {
        }
        KeyboardInput.Update();
        if (num == 0)
        {
        }
        ThreadContentRequest.UpdatingLoading();
        UserManagement.LookForNewUsers();
        long num2 = 0L;
        this.WorldCameraSettings.ApplyCamera();
        this.UICameraSettings.ApplyCamera();
        if (num2 != 0L)
        {
            DrPlatform.DrPlatformType currentPlatform = DrPlatform.CurrentPlatform;
        }
        DrPlatform.PS4.UpdateMouse();
        DrPlatform.IOS.UpdateMouse();
        XNAUnityRunner.MobileControllerLocked = false;
        int num3 = 1;
        if (num3 == 0)
        {
        }
        if (num3 != 0)
        {
            XNAUnityRunner.MobileKeyboardLocked = false;
        }
        bool keyboardOpen = this.KeyboardOpen;
        bool hasKeyboard = Main.HasKeyboard;
        if (keyboardOpen)
        {
            global::UnityEngine.Vector3 mousePosition = XNAUnityRunner.MousePosition;
            return;
        }
        int num4 = 1;
        this.KeyboardOpen = num4 != 0;
    }
References XNAUICameraSettings.ApplyCamera(), XNAWorldCameraSettings.ApplyCamera(), DrPlatform.CurrentPlatform, Terraria.Main.HasKeyboard, j__TPar, KeyboardOpen, Microsoft.Xna.Framework.Input.L, UserManagement.LookForNewUsers(), MousePosition, UICameraSettings, KeyboardInput.Update(), DrPlatform.IOS.UpdateMouse(), DrPlatform.PS4.UpdateMouse(), Microsoft.Xna.Framework.Content.ThreadContentRequest.UpdatingLoading(), and WorldCameraSettings.
Referenced by Update().