terraria-cpp2il-methodrecon: XNAUnityRunner.Awake
Awake()
void XNAUnityRunner.Awake () inline private
Definition at line 34 of file XNAUnityRunner.cs.
    {
        DrPlatform.Setup();
        if (!true)
        {
        }
        LayoutDefinition.LoadReleaseLayout();
        Application.targetFrameRate = 60;
        if (!true)
        {
        }
        if (!true)
        {
        }
        long num = 0L;
        UserManagement.SetupPrimary();
        Screen.sleepTimeout = (int)num;
        this.WorldCameraSettings.ApplyCamera();
        this.UICameraSettings.ApplyCamera();
        Singleton.Create();
    }
References XNAUICameraSettings.ApplyCamera(), XNAWorldCameraSettings.ApplyCamera(), Singleton< T >.Create(), j__TPar, Microsoft.Xna.Framework.Input.L, LayoutDefinition.LoadReleaseLayout(), DrPlatform.Setup(), UserManagement.SetupPrimary(), UICameraSettings, and WorldCameraSettings.