terraria-cpp2il-methodrecon: System.Type.GetType
GetType() [1/5]
new Type System.Type.GetType () inline inherited
Definition at line 287 of file Type.cs.
        {
            return base.GetType();
        }
References System.Type.GetType(), and j__TPar.
Referenced by System.Collections.ArrayList.ArrayListEnumeratorSimple.ArrayListEnumeratorSimple(), System.Globalization.CultureInfo.CultureInfo(), System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument(), System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument(), System.Diagnostics.Tracing.EventSource.EventSource(), System.ComponentModel.RefreshEventArgs.RefreshEventArgs(), System.Net.WebClient.WebClient(), InControl.InputManager.AddDeviceManager(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.IO.Compression.DeflateStream.BeginRead(), System.Net.Sockets.NetworkStream.BeginRead(), System.IO.Compression.DeflateStream.BeginWrite(), System.Net.Sockets.NetworkStream.BeginWrite(), System.DefaultBinder.BindToField(), Newtonsoft.Json.Serialization.DefaultContractResolver.CanConvertToString(), System.Xml.Schema.XmlListConverter.ChangeListType(), System.Xml.Schema.XmlUntypedConverter.ChangeListType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyListConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), System.ComponentModel.MaskedTextProvider.Clone(), System.Enum.CompareTo(), System.Runtime.Serialization.SafeSerializationManager.CompleteSerialization(), System.Net.Sockets.TcpClient.Connect(), System.Net.Sockets.TcpClient.Connect(), System.ComponentModel.NullableConverter.ConvertFrom(), System.Array.Copy(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), System.IO.MemoryStream.CopyTo(), System.RuntimeType.CreateInstanceDefaultCtor(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), InControl.InputDeviceProfile.Define(), System.Net.ResponseStream.EndWrite(), System.Net.Sockets.NetworkStream.EndWrite(), UnityEngine.AnimationCurve.Equals(), UnityEngine.Gradient.Equals(), Microsoft.Xna.Framework.Graphics.PackedVector.HalfSingle.Equals(), Mono.RuntimeClassHandle.Equals(), Mono.RuntimeEventHandle.Equals(), Mono.RuntimePropertyHandle.Equals(), System.Attribute.Equals(), System.Security.CodeAccessPermission.Equals(), System.ComponentModel.MemberDescriptor.Equals(), UnityEngine.Event.Equals(), UnityEngine.Events.UnityEventBase.FindMethod(), System.Security.Cryptography.CryptoStream.FlushAsync(), System.Net.NetEventSource.Format(), System.Enum.Format(), System.Net.WebPermission.FromXml(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetAssociateMetadataTypeFromAttribute(), Newtonsoft.Json.Converters.BinaryConverter.GetByteArray(), System.ComponentModel.TypeConverter.GetConvertFromException(), System.ComponentModel.TypeConverter.GetConvertToException(), System.Attribute.GetHashCode(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberType(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetMemberType(), UnityEngine.Events.PersistentCall.GetObjectCall(), System.Runtime.Remoting.ObjRef.GetObjectData(), System.ComponentModel.ArrayConverter.GetProperties(), System.ComponentModel.TypeDescriptionProvider.GetRuntimeType(), System.Exception.GetType(), System.Type.GetType(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetType(), System.Enum.HasFlag(), System.Uri.InternalIsWellFormedOriginalString(), UnityEngine.AndroidJavaProxy.Invoke(), UnityEngine.SetupCoroutine.InvokeMember(), System.RuntimeType.IsEnumDefined(), System.Net.WebPermission.isMatchedURI(), LayoutDefinition.Load(), LayoutDefinition.LoadReleaseLayout(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(), System.IO.Compression.DeflateStream.Read(), System.Net.Sockets.NetworkStream.Read(), System.IO.MemoryStream.Read(), System.IO.UnmanagedMemoryStream.Read(), System.IO.Compression.GZipStream.Read(), System.Net.Sockets.NetworkStream.Read(), System.Net.Sockets.NetworkStream.ReadAsync(), System.Runtime.Serialization.ObjectManager.RecordFixup(), LayoutDefinition.RefreshStyles(), System.Runtime.Serialization.ObjectManager.RegisterObject(), Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(), LayoutDefinition.Save(), System.Security.Claims.ClaimsPrincipal.SerializeIdentities(), System.Threading.Tasks.Task< TResult >.SetContinuationForAwait(), System.Net.Sockets.Socket.SetSocketOption(), System.Array.SetValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteDynamicProperty(), System.Xml.Schema.XmlAnyConverter.ToBoolean(), System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.Xml.Schema.XmlUntypedConverter.ToBoolean(), System.Xml.Schema.XmlAnyConverter.ToDateTime(), System.Xml.Schema.XmlDateTimeConverter.ToDateTime(), System.Xml.Schema.XmlUntypedConverter.ToDateTime(), System.Xml.Schema.XmlAnyConverter.ToDateTimeOffset(), System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.Xml.Schema.XmlUntypedConverter.ToDateTimeOffset(), System.Xml.Schema.XmlAnyConverter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlUntypedConverter.ToDecimal(), System.Xml.Schema.XmlAnyConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.Schema.XmlAnyConverter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlUntypedConverter.ToInt32(), System.Xml.Schema.XmlAnyConverter.ToInt64(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.Xml.Schema.XmlUntypedConverter.ToInt64(), System.Xml.Schema.XmlAnyConverter.ToSingle(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlUntypedConverter.ToSingle(), System.BadImageFormatException.ToString(), System.Enum.ToString(), System.IO.FileLoadException.ToString(), System.IO.FileNotFoundException.ToString(), System.Runtime.InteropServices.COMException.ToString(), System.Runtime.InteropServices.ExternalException.ToString(), System.ComponentModel.Component.ToString(), System.ComponentModel.MarshalByValueComponent.ToString(), Mono.Net.Security.AsyncProtocolRequest.ToString(), UnityEngine.Events.UnityEventBase.ToString(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlDateTimeConverter.ToString(), System.Xml.Schema.XmlMiscConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), System.Xml.Schema.XmlStringConverter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Security.PermissionSet.ToXml(), System.Net.WebPermission.ToXml(), Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.TryConvertToString(), UnityEngine.EventSystems.ExecuteEvents.ValidateEventData< T >(), Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals(), System.IO.Compression.DeflateStream.Write(), System.Net.Sockets.NetworkStream.Write(), System.IO.MemoryStream.Write(), System.IO.UnmanagedMemoryStream.Write(), System.IO.Compression.GZipStream.Write(), System.Net.Sockets.NetworkStream.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), System.Net.Sockets.NetworkStream.WriteAsync(), Newtonsoft.Json.Converters.KeyValuePairConverter.WriteJson(), Newtonsoft.Json.Converters.VectorConverter.WriteJson(), and Newtonsoft.Json.Linq.JValue.WriteTo().