terraria-cpp2il-methodrecon: System.Runtime.Remoting.Messaging.ClientContextTerminatorSink.SyncProcessMessage
SyncProcessMessage()
IMessage System.Runtime.Remoting.Messaging.ClientContextTerminatorSink.SyncProcessMessage (IMessage msg) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 16 of file ClientContextTerminatorSink.cs.
        {
            if (!true)
            {
            }
            int num = 1;
            int num2 = 1;
            long num3 = 0L;
            Context.NotifyGlobalDynamicSinks(num != 0, msg, num2 != 0, num3 != 0L);
            Context context = this._context;
            int num4 = 1;
            int num5 = 1;
            long num6 = 0L;
            context.NotifyDynamicSinks(num4 != 0, msg, num5 != 0, num6 != 0L);
            if (msg != null)
            {
                if (msg != null)
                {
                    if (msg == null)
                    {
                        throw new InvalidCastException();
                    }
                }
            }
            else
            {
                IMessageSink channelSink = RemotingServices.GetMessageTargetIdentity(msg)._channelSink;
            }
            IMessage message;
            return message;
        }
References System.Runtime.Remoting.Identity._channelSink, System.Runtime.Remoting.Messaging.ClientContextTerminatorSink._context, System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity(), j__TPar, System.L, System.Runtime.Remoting.Contexts.Context.NotifyDynamicSinks(), and System.Runtime.Remoting.Contexts.Context.NotifyGlobalDynamicSinks().