terraria-cpp2il-methodrecon: Terraria.Audio.LegacySoundPlayer.LoadAll
LoadAll()
void Terraria.Audio.LegacySoundPlayer.LoadAll () inline private
Definition at line 32 of file LegacySoundPlayer.cs.
        {
            Asset<SoundEffect>[] soundMech = this.SoundMech;
            Asset<SoundEffect> asset = this.Load("Sounds/Mech_0");
            if (asset == null || asset != null)
            {
                Asset<SoundEffect> asset2 = this.Load("Sounds/Grab");
                this.SoundGrab = asset2;
                Asset<SoundEffect> asset3 = this.Load("Sounds/Pixie");
                this.SoundPixie = asset3;
                Asset<SoundEffect>[] soundDig = this.SoundDig;
                Asset<SoundEffect> asset4 = this.Load("Sounds/Dig_0");
                if (asset4 == null || asset4 != null)
                {
                    Asset<SoundEffect>[] soundDig2 = this.SoundDig;
                    Asset<SoundEffect> asset5 = this.Load("Sounds/Dig_1");
                    if (asset5 == null || asset5 != null)
                    {
                        Asset<SoundEffect>[] soundDig3 = this.SoundDig;
                        Asset<SoundEffect> asset6 = this.Load("Sounds/Dig_2");
                        if (asset6 == null || asset6 != null)
{
                            Asset<SoundEffect>[] soundThunder = this.SoundThunder;
                            Asset<SoundEffect> asset7 = this.Load("Sounds/Thunder_0");
                            if (asset7 == null || asset7 != null)
{
                                Asset<SoundEffect>[] soundThunder2 = this.SoundThunder;
                                Asset<SoundEffect> asset8 = this.Load("Sounds/Thunder_1");
                                if (asset8 == null || asset8 != null)
{
                                    Asset<SoundEffect>[] soundThunder3 = this.SoundThunder;
                                    Asset<SoundEffect> asset9 = this.Load("Sounds/Thunder_2");
                                    if (asset9 == null || asset9 != null)
{
                                        Asset<SoundEffect>[] soundThunder4 = this.SoundThunder;
                                        Asset<SoundEffect> asset10 = this.Load("Sounds/Thunder_3");
                                        if (asset10 == null || asset10 != null)
{
                                            Asset<SoundEffect>[] soundThunder5 = this.SoundThunder;
                                            Asset<SoundEffect> asset11 = this.Load("Sounds/Thunder_4");
                                            if (asset11 == null || asset11 != null)
{
                                                Asset<SoundEffect>[] soundThunder6 = this.SoundThunder;
                                                Asset<SoundEffect> asset12 = this.Load("Sounds/Thunder_5");
                                                if (asset12 == null || asset12 != null)
{
                                                    Asset<SoundEffect>[] soundThunder7 = this.SoundThunder;
                                                    Asset<SoundEffect> asset13 = this.Load("Sounds/Thunder_6");
                                                    if (asset13 == null || asset13 != null)
{
                                                        Asset<SoundEffect>[] soundResearch = this.SoundResearch;
                                                        Asset<SoundEffect> asset14 = this.Load("Sounds/Research_0");
                                                        if (asset14 == null || asset14 != null)
{
                                                            Asset<SoundEffect>[] soundResearch2 = this.SoundResearch;
                                                            Asset<SoundEffect> asset15 = this.Load("Sounds/Research_1");
                                                            if (asset15 == null || asset15 != null)
{
                                                                Asset<SoundEffect>[] soundResearch3 = this.SoundResearch;
                                                                Asset<SoundEffect> asset16 = this.Load("Sounds/Research_2");
                                                                if (asset16 == null || asset16 != null)
{
                                                                    Asset<SoundEffect>[] soundResearch4 = this.SoundResearch;
                                                                    Asset<SoundEffect> asset17 = this.Load("Sounds/Research_3");
                                                                    if (asset17 == null || asset17 != null)
{
                                                                        Asset<SoundEffect>[] soundTink = this.SoundTink;
                                                                        Asset<SoundEffect> asset18 = this.Load("Sounds/Tink_0");
                                                                        if (asset18 == null || asset18 != null)
{
                                                                            Asset<SoundEffect>[] soundTink2 = this.SoundTink;
                                                                            Asset<SoundEffect> asset19 = this.Load("Sounds/Tink_1");
                                                                            if (asset19 == null || asset19 != null)
{
                                                                                Asset<SoundEffect>[] soundTink3 = this.SoundTink;
                                                                                Asset<SoundEffect> asset20 = this.Load("Sounds/Tink_2");
                                                                                if (asset20 == null || asset20 != null)
{
                                                                                    Asset<SoundEffect>[] soundPlayerHit = this.SoundPlayerHit;
                                                                                    Asset<SoundEffect> asset21 = this.Load("Sounds/Player_Hit_0");
                                                                                    if (asset21 == null || asset21 != null)
{
                                                                                        Asset<SoundEffect>[] soundPlayerHit2 = this.SoundPlayerHit;
                                                                                        Asset<SoundEffect> asset22 = this.Load("Sounds/Player_Hit_1");
                                                                                        if (asset22 == null || asset22 != null)
{
                                                                                            Asset<SoundEffect>[] soundPlayerHit3 = this.SoundPlayerHit;
                                                                                            Asset<SoundEffect> asset23 = this.Load("Sounds/Player_Hit_2");
                                                                                            if (asset23 == null || asset23 != null)
{
                                                                                                Asset<SoundEffect>[] soundFemaleHit = this.SoundFemaleHit;
                                                                                                Asset<SoundEffect> asset24 = this.Load("Sounds/Female_Hit_0");
                                                                                                if (asset24 == null || asset24 != null)
{
                                                                                                    Asset<SoundEffect>[] soundFemaleHit2 = this.SoundFemaleHit;
                                                                                                    Asset<SoundEffect> asset25 = this.Load("Sounds/Female_Hit_1");
                                                                                                    if (asset25 == null || asset25 != null)
{
                                                                                                        Asset<SoundEffect>[] soundFemaleHit3 = this.SoundFemaleHit;
                                                                                                        Asset<SoundEffect> asset26 = this.Load("Sounds/Female_Hit_2");
                                                                                                        if (asset26 == null || asset26 != null)
{
                                                                                                            Asset<SoundEffect> asset27 = this.Load("Sounds/Player_Killed");
                                                                                                            this.SoundPlayerKilled = asset27;
                                                                                                            Asset<SoundEffect> asset28 = this.Load("Sounds/Chat");
                                                                                                            this.SoundChat = asset28;
                                                                                                            Asset<SoundEffect> asset29 = this.Load("Sounds/Grass");
                                                                                                            this.SoundGrass = asset29;
                                                                                                            Asset<SoundEffect> asset30 = this.Load("Sounds/Door_Opened");
                                                                                                            this.SoundDoorOpen = asset30;
                                                                                                            Asset<SoundEffect> asset31 = this.Load("Sounds/Door_Closed");
                                                                                                            this.SoundDoorClosed = asset31;
                                                                                                            Asset<SoundEffect> asset32 = this.Load("Sounds/Menu_Tick");
                                                                                                            this.SoundMenuTick = asset32;
                                                                                                            Asset<SoundEffect> asset33 = this.Load("Sounds/Menu_Open");
                                                                                                            this.SoundMenuOpen = asset33;
                                                                                                            Asset<SoundEffect> asset34 = this.Load("Sounds/Menu_Close");
                                                                                                            this.SoundMenuClose = asset34;
                                                                                                            Asset<SoundEffect> asset35 = this.Load("Sounds/Shatter");
                                                                                                            this.SoundShatter = asset35;
                                                                                                            Asset<SoundEffect> asset36 = this.Load("Sounds/Camera");
                                                                                                            this.SoundCamera = asset36;
                                                                                                            Asset<SoundEffect>[] soundCoin = this.SoundCoin;
                                                                                                            string text2;
                                                                                                            string text = "Sounds/Coin_" + text2;
                                                                                                            Asset<SoundEffect> asset37 = this.Load(text);
                                                                                                            if (asset37 == null || asset37 != null)
{
                                                                                                                Asset<SoundEffect>[] soundCoin2 = this.SoundCoin;
                                                                                                                Asset<SoundEffect>[] soundDrip = this.SoundDrip;
                                                                                                                string text4;
                                                                                                                string text3 = "Sounds/Drip_" + text4;
                                                                                                                Asset<SoundEffect> asset38 = this.Load(text3);
                                                                                                                if (asset38 == null || asset38 != null)
{
                                                                                                                    Asset<SoundEffect>[] soundDrip2 = this.SoundDrip;
                                                                                                                    Asset<SoundEffect>[] soundZombie = this.SoundZombie;
                                                                                                                    string text6;
                                                                                                                    string text5 = "Sounds/Zombie_" + text6;
                                                                                                                    Asset<SoundEffect> asset39 = this.Load(text5);
                                                                                                                    if (asset39 == null || asset39 != null)
{
                                                                                                                        Asset<SoundEffect>[] soundZombie2 = this.SoundZombie;
                                                                                                                        Asset<SoundEffect>[] soundLiquid = this.SoundLiquid;
                                                                                                                        string text8;
                                                                                                                        string text7 = "Sounds/Liquid_" + text8;
                                                                                                                        Asset<SoundEffect> asset40 = this.Load(text7);
                                                                                                                        if (asset40 == null || asset40 != null)
{
                                                                                                                            Asset<SoundEffect>[] soundLiquid2 = this.SoundLiquid;
                                                                                                                            Asset<SoundEffect>[] soundRoar = this.SoundRoar;
                                                                                                                            string text10;
                                                                                                                            string text9 = "Sounds/Roar_" + text10;
                                                                                                                            Asset<SoundEffect> asset41 = this.Load(text9);
                                                                                                                            if (asset41 == null || asset41 != null)
{
                                                                                                                                Asset<SoundEffect>[] soundRoar2 = this.SoundRoar;
                                                                                                                                string text12;
                                                                                                                                string text11 = "Sounds/Splash_" + text12;
                                                                                                                                Asset<SoundEffect> asset42 = this.Load(text11);
                                                                                                                                if (asset42 == null || asset42 != null)
{
                                                                                                                                    Asset<SoundEffect>[] soundSplash = this.SoundSplash;
                                                                                                                                    Asset<SoundEffect> asset43 = this.Load("Sounds/Double_Jump");
                                                                                                                                    this.SoundDoubleJump = asset43;
                                                                                                                                    Asset<SoundEffect> asset44 = this.Load("Sounds/Run");
                                                                                                                                    this.SoundRun = asset44;
                                                                                                                                    Asset<SoundEffect> asset45 = this.Load("Sounds/Coins");
                                                                                                                                    this.SoundCoins = asset45;
                                                                                                                                    Asset<SoundEffect> asset46 = this.Load("Sounds/Unlock");
                                                                                                                                    this.SoundUnlock = asset46;
                                                                                                                                    Asset<SoundEffect> asset47 = this.Load("Sounds/MaxMana");
                                                                                                                                    this.SoundMaxMana = asset47;
                                                                                                                                    Asset<SoundEffect> asset48 = this.Load("Sounds/Drown");
                                                                                                                                    this.SoundDrown = asset48;
                                                                                                                                    Asset<SoundEffect>[] soundItem = this.SoundItem;
                                                                                                                                    string text14;
                                                                                                                                    string text13 = "Sounds/Item_" + text14;
                                                                                                                                    Asset<SoundEffect> asset49 = this.Load(text13);
                                                                                                                                    if (asset49 == null || asset49 != null)
{
                                                                                                                                        Asset<SoundEffect>[] soundItem2 = this.SoundItem;
                                                                                                                                        Asset<SoundEffect>[] soundNpcHit = this.SoundNpcHit;
                                                                                                                                        string text16;
                                                                                                                                        string text15 = "Sounds/NPC_Hit_" + text16;
                                                                                                                                        Asset<SoundEffect> asset50 = this.Load(text15);
                                                                                                                                        if (asset50 == null || asset50 != null)
{
                                                                                                                                            Asset<SoundEffect>[] soundNpcHit2 = this.SoundNpcHit;
                                                                                                                                            Asset<SoundEffect>[] soundNpcKilled = this.SoundNpcKilled;
                                                                                                                                            string text18;
                                                                                                                                            string text17 = "Sounds/NPC_Killed_" + text18;
                                                                                                                                            Asset<SoundEffect> asset51 = this.Load(text17);
                                                                                                                                            if (asset51 == null || asset51 != null)
{
                                                                                                                                                Asset<SoundEffect>[] soundNpcKilled2 = this.SoundNpcKilled;
                                                                                                                                                int trackableLegacySoundCount = SoundID.TrackableLegacySoundCount;
                                                                                                                                                Asset<SoundEffect>[] trackableSounds = this.TrackableSounds;
                                                                                                                                                string trackableLegacySoundPath = SoundID.GetTrackableLegacySoundPath(0);
                                                                                                                                                string text20;
                                                                                                                                                string text19 = "Sounds/Custom" + text20 + trackableLegacySoundPath;
                                                                                                                                                Asset<SoundEffect> asset52 = this.Load(text19);
                                                                                                                                                if (asset52 == null || asset52 != null)
{
                                                                                                                                                    Asset<SoundEffect>[] trackableSounds2 = this.TrackableSounds;
                                                                                                                                                    return;
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            throw new ArrayTypeMismatchException();
        }
References Terraria.ID.SoundID.GetTrackableLegacySoundPath(), j__TPar, Terraria.Audio.LegacySoundPlayer.Load(), Terraria.Audio.LegacySoundPlayer.SoundCoin, Terraria.Audio.LegacySoundPlayer.SoundDig, Terraria.Audio.LegacySoundPlayer.SoundDrip, Terraria.Audio.LegacySoundPlayer.SoundFemaleHit, Terraria.Audio.LegacySoundPlayer.SoundItem, Terraria.Audio.LegacySoundPlayer.SoundLiquid, Terraria.Audio.LegacySoundPlayer.SoundMech, Terraria.Audio.LegacySoundPlayer.SoundNpcHit, Terraria.Audio.LegacySoundPlayer.SoundNpcKilled, Terraria.Audio.LegacySoundPlayer.SoundPlayerHit, Terraria.Audio.LegacySoundPlayer.SoundResearch, Terraria.Audio.LegacySoundPlayer.SoundRoar, Terraria.Audio.LegacySoundPlayer.SoundSplash, Terraria.Audio.LegacySoundPlayer.SoundThunder, Terraria.Audio.LegacySoundPlayer.SoundTink, Terraria.Audio.LegacySoundPlayer.SoundZombie, System.text, Terraria.ID.SoundID.TrackableLegacySoundCount, and Terraria.Audio.LegacySoundPlayer.TrackableSounds.
Referenced by Terraria.Audio.LegacySoundPlayer.LegacySoundPlayer().