terraria-cpp2il-methodrecon: Newtonsoft.Json.JsonWriter.InternalWriteStart
InternalWriteStart()
void Newtonsoft.Json.JsonWriter.InternalWriteStart (JsonToken token, JsonContainerType container) inline package inherited
Definition at line 905 of file JsonWriter.cs.
        {
            if (this._currentPosition.HasIndex)
            {
                int position = this._currentPosition.Position;
                this._currentPosition.Position = position;
            }
            this.AutoComplete(token);
            this.Push(container);
        }
References Newtonsoft.Json.JsonWriter._currentPosition, Newtonsoft.Json.JsonWriter.AutoComplete(), Newtonsoft.Json.JsonPosition.HasIndex, j__TPar, Newtonsoft.Json.JsonPosition.Position, and Newtonsoft.Json.JsonWriter.Push().
Referenced by Newtonsoft.Json.JsonWriter.WriteStartArray(), Newtonsoft.Json.Serialization.TraceJsonWriter.WriteStartArray(), Newtonsoft.Json.JsonWriter.WriteStartConstructor(), Newtonsoft.Json.Serialization.TraceJsonWriter.WriteStartConstructor(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.Serialization.TraceJsonWriter.WriteStartObject().