terraria-cpp2il-methodrecon: System.Threading.Tasks.Task.InternalCancel
InternalCancel() [2/2]
bool System.Threading.Tasks.Task< TResult >.InternalCancel (bool bCancelNonExecutingOnly) inline package inherited
Definition at line 1328 of file Task.2.cs.
        {
            int stateFlags = this.m_stateFlags;
            if (this.m_taskScheduler != null)
            {
            }
            if (false)
            {
                int num = 64;
                int num2 = 66;
                return this.AtomicStateUpdate(num, num2);
            }
            this.RecordInternalCancellationRequest();
            int num3 = 64;
            int num4 = 66;
            return this.AtomicStateUpdate(num3, num4);
        }
References System.Threading.Tasks.Task< TResult >.AtomicStateUpdate(), j__TPar, System.Threading.Tasks.Task< TResult >.m_stateFlags, System.Threading.Tasks.Task< TResult >.m_taskScheduler, and System.Threading.Tasks.Task< TResult >.RecordInternalCancellationRequest().
Referenced by System.Threading.Tasks.Task< TResult >.AssignCancellationToken().