terraria-cpp2il-methodrecon: System.ValueTuple.CombineHashCodes
CombineHashCodes() [1/7]
static int System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes (int h1, int h2) inline static package
Definition at line 92 of file ValueTuple.cs.
        {
            if (!true)
            {
            }
            return global::System.Numerics.Hashing.HashHelpers.Combine(global::System.Numerics.Hashing.HashHelpers.Combine(1, h1), h1);
        }
References j__TPar.
Referenced by System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), and System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.GetHashCode().