terraria-cpp2il-methodrecon: Terraria.GameContent.UI.Elements.UISearchBar.ToggleTakingText
ToggleTakingText()
void Terraria.GameContent.UI.Elements.UISearchBar.ToggleTakingText () inline
Definition at line 263 of file UISearchBar.cs.
        {
            for (;;)
            {
                bool flag = this.isWritingText;
                UITextBox text = this._text;
                this.isWritingText = flag;
                text.ShowInputTicker = flag;
                if (!flag)
                {
                }
                Main.clrInput();
                if (this.isWritingText)
                {
                    break;
                }
                if (this.OnEndTakingInput == null)
                {
                    return;
                }
            }
            Action onStartTakingInput = this.OnStartTakingInput;
            if (onStartTakingInput != null)
            {
                IntPtr invoke_impl = onStartTakingInput.invoke_impl;
                IntPtr method_code = onStartTakingInput.method_code;
                IntPtr method = onStartTakingInput.method;
                return;
            }
        }
References Terraria.GameContent.UI.Elements.UISearchBar._text, Terraria.Main.clrInput(), Terraria.GameContent.UI.Elements.UISearchBar.isWritingText, j__TPar, Terraria.GameContent.UI.Elements.UISearchBar.OnEndTakingInput, Terraria.GameContent.UI.Elements.UISearchBar.OnStartTakingInput, and System.text.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Click_SearchArea(), Terraria.GameContent.UI.States.UIBestiaryTest.Click_SearchArea(), Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GoBackHere(), Terraria.GameContent.UI.States.UIBestiaryTest.GoBackHere(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Update(), and Terraria.GameContent.UI.States.UIBestiaryTest.Update().