terraria-cpp2il-methodrecon: Mono.Security.X509.X509Store.RemoveNewFormat
RemoveNewFormat()
void Mono.Security.X509.X509Store.RemoveNewFormat (X509Certificate certificate) inline private
Definition at line 203 of file X509Store.cs.
        {
            string text2;
            string text = Path.Combine(this._storePath, text2);
            bool flag = File.Exists(text);
            File.Delete(text);
            X509CertificateCollection certificates = this._certificates;
            if (certificates != null)
            {
                certificates.Clear();
            }
        }
References Mono.Security.X509.X509Store._certificates, Mono.Security.X509.X509Store._storePath, System.Collections.CollectionBase.Clear(), System.IO.Path.Combine(), System.IO.File.Delete(), System.IO.File.Exists(), and System.text.
Referenced by Mono.Security.X509.X509Store.Remove().