terraria-cpp2il-methodrecon: Mono.Security.X509.X509Store.Import
Import() [1/2]
void Mono.Security.X509.X509Store.Import (X509Certificate certificate) inline
Definition at line 108 of file X509Store.cs.
        {
            string storePath = this._storePath;
            if (this._newFormat)
            {
                this.ImportNewFormat(certificate);
                return;
            }
            string text2;
            string text = Path.Combine(this._storePath, text2);
            bool flag = File.Exists(text);
            string text4;
            string text3 = Path.Combine(this._storePath, text4);
            X509Certificate x509Certificate = this.LoadCertificate(text);
            string text5;
            string text6;
            bool flag2 = text5 != text6;
            FileStream fileStream = File.Create(text3);
            byte[] encodedcert = certificate.m_encodedcert;
        }
References Mono.Security.X509.X509Store._newFormat, Mono.Security.X509.X509Store._storePath, System.IO.Path.Combine(), System.IO.File.Create(), System.IO.File.Exists(), Mono.Security.X509.X509Store.ImportNewFormat(), j__TPar, Mono.Security.X509.X509Store.LoadCertificate(), Mono.Security.X509.X509Certificate.m_encodedcert, and System.text.