terraria-cpp2il-methodrecon: Mono.Security.X509.X509Store.Remove
Remove() [1/2]
void Mono.Security.X509.X509Store.Remove (X509Certificate certificate) inline
Definition at line 147 of file X509Store.cs.
        {
            if (this._newFormat)
            {
                this.RemoveNewFormat(certificate);
                return;
            }
            string text;
            bool flag = File.Exists(Path.Combine(this._storePath, text));
        }
References Mono.Security.X509.X509Store._newFormat, System.IO.Path.Combine(), System.IO.File.Exists(), Mono.Security.X509.X509Store.RemoveNewFormat(), and System.text.