terraria-cpp2il-methodrecon: Mono.Security.X509.X509Store.ImportNewFormat
ImportNewFormat()
void Mono.Security.X509.X509Store.ImportNewFormat (X509Certificate certificate) inline private
Definition at line 175 of file X509Store.cs.
        {
            string text2;
            string text = Path.Combine(this._storePath, text2);
            bool flag = File.Exists(text);
            FileStream fileStream = File.Create(text);
            long num = 0L;
            int num2 = 3;
            if (fileStream != null)
            {
                return;
            }
            if (num != 0L)
            {
                throw new OutOfMemoryException();
            }
            if (num2 == 0)
            {
                X509CertificateCollection certificates = this._certificates;
                if (certificates != null)
                {
                    certificates.Clear();
                }
                return;
            }
        }
References Mono.Security.X509.X509Store._certificates, Mono.Security.X509.X509Store._storePath, System.Collections.CollectionBase.Clear(), System.IO.Path.Combine(), System.IO.File.Create(), System.IO.File.Exists(), j__TPar, System.L, and System.text.
Referenced by Mono.Security.X509.X509Store.Import().