terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexFCD.RegexFCFromRegexTree
RegexFCFromRegexTree()
RegexFC System.Text.RegularExpressions.RegexFCD.RegexFCFromRegexTree (RegexTree tree) inline private
Definition at line 162 of file RegexFCD.cs.
        {
            RegexNode root;
            long num;
            do
            {
                root = tree.Root;
                num = 0L;
                List<RegexNode> children = root.Children;
                if (children == null)
                {
                    break;
                }
                int size = children._size;
                if (this._skipAllChildren)
                {
                    goto IL_0050;
                }
                int ntype = root.NType;
                if (!this._skipchild)
                {
                    goto IL_007C;
                }
            }
            while (root.Children != null);
            int ntype2 = root.NType;
            long num2 = 0L;
            this.CalculateFC(ntype2, root, (int)num2);
            IL_0050:
            RegexNode next = root.Next;
            global::System.Collections.Generic.ValueListBuilder<int> intStack = this._intStack;
            int ntype3 = next.NType;
            this.CalculateFC(ntype2, next, (int)num);
            if (!this._failed)
            {
            }
            IL_007C:
            List<RegexNode> children2 = next.Children;
            this.PushInt((int)num);
            return this.PopFC();
        }
References System.Text.RegularExpressions.RegexFCD._failed, System.Text.RegularExpressions.RegexFCD._intStack, System.Collections.Generic.List< T >._size, System.Text.RegularExpressions.RegexFCD._skipAllChildren, System.Text.RegularExpressions.RegexFCD._skipchild, System.Text.RegularExpressions.RegexFCD.CalculateFC(), System.Text.RegularExpressions.RegexNode.Children, j__TPar, System.L, System.Text.RegularExpressions.RegexNode.Next, System.Text.RegularExpressions.RegexNode.NType, System.Text.RegularExpressions.RegexFCD.PopFC(), System.Text.RegularExpressions.RegexFCD.PushInt(), and System.Text.RegularExpressions.RegexTree.Root.