terraria-cpp2il-methodrecon: GUIMap.DrawToMap
DrawToMap()
void GUIMap.DrawToMap () inline
Definition at line 172 of file GUIMap.cs.
    {
        WorldMap map = Main.Map;
        if (map != null)
        {
            map.UpdateChunks();
        }
        bool mapEnabled = Main.mapEnabled;
        int num = this.activeY;
        this.activeY = num;
        this.InitialiseTargets();
        bool clearMap = Main.clearMap;
        this.ClearMap();
        int mapMinX = Main.mapMinX;
        int mapMaxX = Main.mapMaxX;
        int mapMinY = Main.mapMinY;
        int mapMaxY = Main.mapMaxY;
    }
References activeY, ClearMap(), Terraria.Main.clearMap, InitialiseTargets(), j__TPar, Terraria.Main.Map, Terraria.Main.mapEnabled, Terraria.Main.mapMaxX, Terraria.Main.mapMaxY, Terraria.Main.mapMinX, Terraria.Main.mapMinY, and Terraria.Map.WorldMap.UpdateChunks().