terraria-cpp2il-methodrecon: System.Runtime.Remoting.Identity.NotifyServerDynamicSinks
NotifyServerDynamicSinks()
void System.Runtime.Remoting.Identity.NotifyServerDynamicSinks (bool start, IMessage req_msg, bool client_site, bool async) inline inherited
Definition at line 163 of file Identity.cs.
        {
            DynamicPropertyCollection serverDynamicProperties = this._serverDynamicProperties;
            if (serverDynamicProperties != null)
            {
                long num = 0L;
                bool hasProperties = serverDynamicProperties.HasProperties;
                this._serverDynamicProperties.NotifyMessage(num != 0L, req_msg, client_site, async);
                return;
            }
        }
References System.Runtime.Remoting.Identity._serverDynamicProperties, System.Runtime.Remoting.Contexts.DynamicPropertyCollection.HasProperties, j__TPar, System.L, and System.Runtime.Remoting.Contexts.DynamicPropertyCollection.NotifyMessage().
Referenced by System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.AsyncProcessMessage(), and System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage().
html>