terraria-cpp2il-methodrecon: System.Globalization.JapaneseCalendar.GetEraInfo
GetEraInfo()
static EraInfo[] System.Globalization.JapaneseCalendar.GetEraInfo () inline static package
Definition at line 40 of file JapaneseCalendar.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
            throw new ArrayTypeMismatchException();
        }
Referenced by System.Globalization.JapaneseCalendar.JapaneseCalendar(), System.Globalization.JapaneseCalendar.EnglishEraNames(), and System.Globalization.JapaneseCalendar.EraNames().