terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509ChainImplMono.Process
Process()
void System.Security.Cryptography.X509Certificates.X509ChainImplMono.Process (int n) inline private
Definition at line 335 of file X509ChainImplMono.cs.
        {
            X509ChainElement x509ChainElement = this.elements[n];
            X509Certificate2 certificate = x509ChainElement.certificate;
            X509Certificate monoCertificate = X509Helper2.GetMonoCertificate(certificate);
            ArrayList list = this.elements._list;
            if (monoCertificate == null)
            {
                X509ChainElementCollection x509ChainElementCollection = this.elements;
                X509ChainElement x509ChainElement2;
                X509Certificate monoCertificate2 = X509Helper2.GetMonoCertificate(x509ChainElement2.certificate);
            }
            AsymmetricAlgorithm asymmetricAlgorithm = this.working_public_key;
            if (asymmetricAlgorithm != null)
            {
                return;
            }
            AsymmetricAlgorithm key = certificate.PublicKey.Key;
            if (key != null)
            {
                bool flag = X509Helper2.GetMonoCertificate(certificate).VerifySignature(key);
            }
            if (asymmetricAlgorithm != null)
            {
                ArrayList list2 = this.elements._list;
            }
            X509ChainStatusFlags compressed_status_flags = x509ChainElement.compressed_status_flags;
            x509ChainElement.compressed_status_flags = compressed_status_flags;
            X509ChainElement x509ChainElement3 = this.bce_restriction;
            DateTime notBefore = certificate.GetNotBefore();
            X509ChainElement x509ChainElement4 = this.bce_restriction;
            DateTime notAfter = certificate.GetNotAfter();
            X509ChainStatusFlags compressed_status_flags2 = x509ChainElement.compressed_status_flags;
            x509ChainElement.compressed_status_flags = compressed_status_flags2;
            if (asymmetricAlgorithm != null)
            {
                X500DistinguishedName issuerName = certificate.IssuerName;
                X500DistinguishedName x500DistinguishedName = this.working_issuer_name;
                bool flag2 = X500DistinguishedName.AreEqual(issuerName, x500DistinguishedName);
                X509ChainStatusFlags compressed_status_flags3 = x509ChainElement.compressed_status_flags;
                x509ChainElement.compressed_status_flags = compressed_status_flags3;
                return;
            }
        }
References System.Security.Cryptography.X509Certificates.X509ChainElementCollection._list, System.Security.Cryptography.X509Certificates.X500DistinguishedName.AreEqual(), System.Security.Cryptography.X509Certificates.X509ChainImplMono.bce_restriction, System.Security.Cryptography.X509Certificates.X509ChainImplMono.elements, System.Security.Cryptography.X509Certificates.X509Helper2.GetMonoCertificate(), System.Security.Cryptography.X509Certificates.X509Certificate.GetNotAfter(), System.Security.Cryptography.X509Certificates.X509Certificate.GetNotBefore(), System.Security.Cryptography.X509Certificates.X509Certificate2.IssuerName, j__TPar, System.key, System.Security.Cryptography.X509Certificates.PublicKey.Key, System.list, System.Security.Cryptography.X509Certificates.X509Certificate2.PublicKey, System.Security.Cryptography.X509Certificates.X509ChainImplMono.working_issuer_name, and System.Security.Cryptography.X509Certificates.X509ChainImplMono.working_public_key.