terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509ChainImplMono.ValidateChain
ValidateChain()
void System.Security.Cryptography.X509Certificates.X509ChainImplMono.ValidateChain (X509ChainStatusFlags flag) inline private
Definition at line 318 of file X509ChainImplMono.cs.
        {
            ArrayList list = this.elements._list;
            X509ChainElementCollection x509ChainElementCollection = this.elements;
            X509ChainElement x509ChainElement;
            X509Certificate2 certificate = x509ChainElement.certificate;
            AsymmetricAlgorithm key = certificate.PublicKey.Key;
            this.working_public_key = key;
            X500DistinguishedName issuerName = certificate.IssuerName;
            this.working_issuer_name = issuerName;
            long num = 0L;
            this.Process((int)num);
            this.CheckRevocationOnChain(flag);
            this.WrapUp();
        }
References System.Security.Cryptography.X509Certificates.X509ChainElementCollection._list, System.Security.Cryptography.X509Certificates.X509ChainImplMono.CheckRevocationOnChain(), System.Security.Cryptography.X509Certificates.X509ChainImplMono.elements, System.Security.Cryptography.X509Certificates.X509Certificate2.IssuerName, j__TPar, System.key, System.Security.Cryptography.X509Certificates.PublicKey.Key, System.L, System.list, System.Process, System.Security.Cryptography.X509Certificates.X509Certificate2.PublicKey, and System.Security.Cryptography.X509Certificates.X509ChainImplMono.WrapUp().
Referenced by System.Security.Cryptography.X509Certificates.X509ChainImplMono.Build().