terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509ChainImplMono.FindParent
FindParent()
X509Certificate2 System.Security.Cryptography.X509Certificates.X509ChainImplMono.FindParent (X509Certificate2 certificate) inline private
Definition at line 279 of file X509ChainImplMono.cs.
        {
            X509Certificate2Collection certificateCollection = this.CertificateCollection;
            string issuer = certificate.Issuer;
            long num = 0L;
            X509Certificate2Collection x509Certificate2Collection = certificateCollection.Find(X509FindType.FindBySubjectDistinguishedName, issuer, num != 0L);
            string authorityKeyIdentifier = X509ChainImplMono.GetAuthorityKeyIdentifier(certificate);
            if (authorityKeyIdentifier != null)
            {
                int stringLength = authorityKeyIdentifier._stringLength;
                X509Certificate2Collection certificateCollection2 = this.CertificateCollection;
                long num2 = 0L;
                X509Certificate2Collection x509Certificate2Collection2 = certificateCollection2.Find(X509FindType.FindBySubjectKeyIdentifier, authorityKeyIdentifier, num2 != 0L);
                x509Certificate2Collection.AddRange(x509Certificate2Collection2);
            }
            X509Certificate2 x509Certificate = this.SelectBestFromCollection(certificate, x509Certificate2Collection);
            return certificate;
        }
References System.Security.Cryptography.X509Certificates.X509Certificate2Collection.AddRange(), System.Security.Cryptography.X509Certificates.X509ChainImplMono.CertificateCollection, System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Find(), System.Security.Cryptography.X509Certificates.X509ChainImplMono.GetAuthorityKeyIdentifier(), System.Security.Cryptography.X509Certificates.X509Certificate.Issuer, j__TPar, System.L, and System.Security.Cryptography.X509Certificates.X509ChainImplMono.SelectBestFromCollection().
Referenced by System.Security.Cryptography.X509Certificates.X509ChainImplMono.BuildChainFrom().