terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509ChainImplMono.GetAuthorityKeyIdentifier
GetAuthorityKeyIdentifier() [1/3]
static string System.Security.Cryptography.X509Certificates.X509ChainImplMono.GetAuthorityKeyIdentifier (X509Certificate2 certificate) inline static private
Definition at line 444 of file X509ChainImplMono.cs.
        {
            X509Certificate x509Certificate;
            return X509ChainImplMono.GetAuthorityKeyIdentifier(x509Certificate.extensions["2.5.29.35"]);
        }
References System.Security.Cryptography.X509Certificates.X509ChainImplMono.GetAuthorityKeyIdentifier().
Referenced by System.Security.Cryptography.X509Certificates.X509ChainImplMono.FindParent(), System.Security.Cryptography.X509Certificates.X509ChainImplMono.GetAuthorityKeyIdentifier(), System.Security.Cryptography.X509Certificates.X509ChainImplMono.GetAuthorityKeyIdentifier(), and System.Security.Cryptography.X509Certificates.X509ChainImplMono.IsChainComplete().