terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509ChainImplMono.CheckRevocation
CheckRevocation() [2/2]
X509ChainStatusFlags System.Security.Cryptography.X509Certificates.X509ChainImplMono.CheckRevocation (X509Certificate2 certificate, X509Certificate2 ca_cert, bool online) inline private
Definition at line 482 of file X509ChainImplMono.cs.
        {
            if (ca_cert.Extensions["2.5.29.15"] != null)
            {
            }
            X509Crl x509Crl = this.FindCrl(ca_cert);
            if (x509Crl == null)
            {
                return X509ChainStatusFlags.RevocationStatusUnknown;
            }
            AsymmetricAlgorithm key = ca_cert.PublicKey.Key;
            bool flag = x509Crl.VerifySignature(key);
            X509Certificate monoCertificate = X509Helper2.GetMonoCertificate(certificate);
            X509Crl.X509CrlEntry crlEntry = x509Crl.GetCrlEntry(monoCertificate);
            if (crlEntry != null)
            {
                DateTime revocationDate = crlEntry.revocationDate;
                X509ChainElement x509ChainElement = this.bce_restriction;
                return X509ChainStatusFlags.Revoked;
            }
            DateTime nextUpdate = x509Crl.nextUpdate;
            X509ChainElement x509ChainElement2 = this.bce_restriction;
            return X509ChainStatusFlags.RevocationStatusUnknown;
        }
References System.Security.Cryptography.X509Certificates.X509ChainImplMono.bce_restriction, System.Security.Cryptography.X509Certificates.X509ChainImplMono.FindCrl(), Mono.Security.X509.X509Crl.GetCrlEntry(), System.Security.Cryptography.X509Certificates.X509Helper2.GetMonoCertificate(), j__TPar, System.key, Mono.Security.X509.X509Crl.nextUpdate, and Mono.Security.X509.X509Crl.VerifySignature().