terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509ChainImplMono.Build
Build()
override bool System.Security.Cryptography.X509Certificates.X509ChainImplMono.Build (X509Certificate2 certificate) inline
Definition at line 53 of file X509ChainImplMono.cs.
        {
            if (certificate != null)
            {
                X509ChainStatusFlags x509ChainStatusFlags = this.BuildChainFrom(certificate);
                this.ValidateChain(x509ChainStatusFlags);
                X509ChainElementEnumerator enumerator = this.elements.GetEnumerator();
                bool flag = enumerator.MoveNext();
                X509ChainStatus[] array = enumerator.Current.status;
                bool flag2 = enumerator.MoveNext();
                if (x509ChainStatusFlags != X509ChainStatusFlags.NoError)
                {
                    string information = X509ChainStatus.GetInformation(x509ChainStatusFlags);
                }
                if (this.status != null)
                {
                    AsymmetricAlgorithm asymmetricAlgorithm = this.working_public_key;
                    X509ChainStatus[] array2 = this.status;
                    AsymmetricAlgorithm asymmetricAlgorithm2 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm3 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm4 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm5 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm6 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm7 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm8 = this.working_public_key;
                    AsymmetricAlgorithm asymmetricAlgorithm9 = this.working_public_key;
                }
                throw new InvalidCastException();
            }
        }
References System.array, System.Security.Cryptography.X509Certificates.X509ChainImplMono.BuildChainFrom(), System.Security.Cryptography.X509Certificates.X509ChainElementEnumerator.Current, System.Security.Cryptography.X509Certificates.X509ChainImplMono.elements, System.Security.Cryptography.X509Certificates.X509ChainElementCollection.GetEnumerator(), System.Security.Cryptography.X509Certificates.X509ChainStatus.GetInformation(), j__TPar, System.Security.Cryptography.X509Certificates.X509ChainElementEnumerator.MoveNext(), System.Security.Cryptography.X509Certificates.X509ChainElement.status, System.Security.Cryptography.X509Certificates.X509ChainImplMono.status, System.Security.Cryptography.X509Certificates.X509ChainImplMono.ValidateChain(), and System.Security.Cryptography.X509Certificates.X509ChainImplMono.working_public_key.