terraria-cpp2il-methodrecon: System.Net.Sockets.TcpListener.Start
Start() [2/2]
void System.Net.Sockets.TcpListener.Start (int backlog) inline
Definition at line 60 of file TcpListener.cs.
        {
            bool on = Logging.On;
            Socket serverSocket = this.m_ServerSocket;
            if (serverSocket != null)
            {
                if (!this.m_Active)
                {
                    IPEndPoint serverSocketEP = this.m_ServerSocketEP;
                    serverSocket.Bind(serverSocketEP);
                    this.m_ServerSocket.Listen(backlog);
                    int num = 1;
                    this.m_Active = num != 0;
                }
                bool on2 = Logging.On;
                return;
            }
            string @string = SR.GetString("The socket handle is not valid.");
            throw new OutOfMemoryException();
        }
References System.Net.Sockets.Socket.Bind(), SR.GetString(), j__TPar, System.Net.Sockets.Socket.Listen(), System.Net.Sockets.TcpListener.m_Active, System.Net.Sockets.TcpListener.m_ServerSocket, System.Net.Sockets.TcpListener.m_ServerSocketEP, and System.Net.Logging.On.