terraria-cpp2il-methodrecon: System.Security.Cryptography.MACTripleDES.Dispose
Dispose() [2/2]
override void System.Security.Cryptography.MACTripleDES.Dispose (bool disposing) inline protected virtual
Reimplemented from System.Security.Cryptography.KeyedHashAlgorithm.
Definition at line 139 of file MACTripleDES.cs.
        {
            TripleDES tripleDES = this.des;
            if (tripleDES != null)
            {
                tripleDES.Clear();
            }
            long num;
            if (this.m_encryptor != null)
            {
                num = 0L;
                return;
            }
            CryptoStream cs = this._cs;
            if (cs != null)
            {
                cs.Clear();
            }
            if (this._ts != null)
            {
            }
            byte[] keyValue = this.KeyValue;
            if (keyValue != null)
            {
                long num2 = 0L;
                Array.Clear(keyValue, (int)num2, (int)num);
            }
            int num3 = 1;
            this._disposed = num3 != 0;
        }
References System.Security.Cryptography.MACTripleDES._cs, System.Security.Cryptography.MACTripleDES._ts, System.Array.Clear(), System.Security.Cryptography.CryptoStream.Clear(), System.Security.Cryptography.SymmetricAlgorithm.Clear(), System.Security.Cryptography.MACTripleDES.des, j__TPar, System.Security.Cryptography.KeyedHashAlgorithm.KeyValue, System.L, and System.Security.Cryptography.MACTripleDES.m_encryptor.