terraria-cpp2il-methodrecon: InControl.TouchSprite.Delete
Delete()
void InControl.TouchSprite.Delete () inline
Definition at line 76 of file TouchSprite.cs.
        {
            GameObject gameObject = this.spriteGameObject;
            if (!true)
            {
            }
            global::UnityEngine.Object.Destroy(gameObject);
        }
References UnityEngine.Object.Object(), and InControl.TouchSprite.spriteGameObject.
Referenced by InControl.TouchButtonControl.DestroyControl(), and InControl.TouchStickControl.DestroyControl().