terraria-cpp2il-methodrecon: Terraria.GameContent.Skies.SlimeSky.GenerateSlimes
GenerateSlimes()
void Terraria.GameContent.Skies.SlimeSky.GenerateSlimes () inline private
Definition at line 25 of file SlimeSky.cs.
        {
            if (!true)
            {
            }
            this._slimes = -1073741824;
            int num = 1;
            Vector2 screenPosition = Main.screenPosition;
            int screenHeight = Main.screenHeight;
            SlimeSky.Slime[] slimes = this._slimes;
            long num2 = 0L;
            int num3 = this._random.Next((int)num2, -1073741824);
            SlimeSky.Slime[] slimes2 = this._slimes;
            double num4 = this._random.NextDouble();
            SlimeSky.Slime[] slimes3 = this._slimes;
            int num5 = 2;
            int frameWidth = slimes3.FrameWidth;
            UnifiedRandom random = this._random;
            Asset<Texture2D>[] textures = this._textures;
            int num6 = random.Next(num5);
            bool active = slimes3.Active;
            int num7 = 60;
            if (this._random.Next(num7) != 0)
            {
                UnifiedRandom random2 = this._random;
                int num8 = 30;
                if (random2.Next(num8) == 0)
                {
                    Asset<Texture2D>[] textures2 = this._textures;
                    SlimeSky.Slime[] slimes4 = this._slimes;
                    double num9 = this._random.NextDouble();
                    return;
                }
            }
            else
            {
                Asset<Texture2D>[] textures3 = this._textures;
                SlimeSky.Slime[] slimes5 = this._slimes;
                double num10 = this._random.NextDouble();
                SlimeSky.Slime[] slimes6 = this._slimes;
            }
            SlimeSky.Slime[] slimes7 = this._slimes;
            slimes7._texture = num;
            int frameWidth2 = slimes7.FrameWidth;
            this._slimesRemaining = frameWidth2;
        }
References Terraria.GameContent.Skies.SlimeSky._random, Terraria.GameContent.Skies.SlimeSky._slimes, Terraria.GameContent.Skies.SlimeSky._textures, j__TPar, System.L, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Main.screenHeight, and Terraria.Main.screenPosition.
Referenced by Terraria.GameContent.Skies.SlimeSky.Activate().