terraria-cpp2il-methodrecon: Ionic.Zip.ZipSegmentedStream._SetWriteStream
_SetWriteStream()
void Ionic.Zip.ZipSegmentedStream._SetWriteStream (uint increment) inline private
Definition at line 254 of file ZipSegmentedStream.cs.
        {
            if (this._innerStream != null)
            {
                string text;
                if (this._currentName == null)
                {
                    uint currentDiskNumber = this._currentDiskNumber;
                    text = this._NameForSegment(currentDiskNumber);
                    this._currentName = text;
                }
                bool flag = File.Exists(text);
                string text2;
                if (this._currentName == null)
                {
                    uint currentDiskNumber2 = this._currentDiskNumber;
                    text2 = this._NameForSegment(currentDiskNumber2);
                    this._currentName = text2;
                }
                File.Delete(text2);
                string currentName = this._currentName;
                string currentTempName = this._currentTempName;
                string text3;
                if (currentName == null)
                {
                    uint currentDiskNumber3 = this._currentDiskNumber;
                    text3 = this._NameForSegment(currentDiskNumber3);
                    this._currentName = text3;
                }
                File.Move(currentTempName, text3);
            }
            if (increment != 0U)
            {
                uint currentDiskNumber4 = this._currentDiskNumber;
                this._currentDiskNumber = currentDiskNumber4;
            }
            string baseDir = this._baseDir;
            if (this._currentDiskNumber != 0U)
            {
                return;
            }
            byte[] bytes = BitConverter.GetBytes(19280);
        }
References Ionic.Zip.ZipSegmentedStream._baseDir, Ionic.Zip.ZipSegmentedStream._currentDiskNumber, Ionic.Zip.ZipSegmentedStream._currentName, Ionic.Zip.ZipSegmentedStream._currentTempName, Ionic.Zip.ZipSegmentedStream._innerStream, Ionic.Zip.ZipSegmentedStream._NameForSegment(), System.IO.File.Delete(), System.IO.File.Exists(), System.BitConverter.GetBytes(), j__TPar, System.IO.File.Move(), System.text, and System.U.
Referenced by Ionic.Zip.ZipSegmentedStream.Write().