terraria-cpp2il-methodrecon: Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw
Draw()
override void Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw (SpriteBatch sb) inline
Definition at line 675 of file CaptureInterface.cs.
            {
                bool selected = this.Selected;
                if (selected)
                {
                    sb.End();
                    if (!selected)
                    {
                    }
                    if (!true)
                    {
                    }
                    if (!true)
                    {
                    }
                    PlayerInput.SetZoom_Context();
                    this.DrawMarkedArea(sb);
                    sb.End();
                    if (!true)
                    {
                    }
                    PlayerInput.SetZoom_UI();
                }
            }
References Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), j__TPar, Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.Selected, Terraria.GameInput.PlayerInput.SetZoom_Context(), and Terraria.GameInput.PlayerInput.SetZoom_UI().