terraria-cpp2il-methodrecon: System.Uri.Uri
Uri() [1/7]
System.Uri.Uri (string uriString) inline
Definition at line 279 of file Uri.cs.
        {
            do
            {
                base..ctor();
            }
            while (uriString == null);
            long num = 0L;
            this.CreateThis(uriString, num != 0L, global::System.UriKind.Absolute);
        }
References System.Uri.CreateThis(), j__TPar, and System.L.
Referenced by System.Uri.Uri(), System.Uri.EnsureUriInfo(), System.Uri.GetEscapedParts(), System.Uri.GetHashCode(), System.Uri.GetHostViaCustomSyntax(), System.Uri.GetLocalPath(), System.Net.HttpListenerRequestUriBuilder.GetRequestUri(), System.Uri.GetUnescapedParts(), System.Net.WebClient.GetUri(), System.Uri.InternalIsWellFormedOriginalString(), System.Uri.ParseMinimal(), System.Uri.ParseRemaining(), and System.Uri.ReCreateParts().