terraria-cpp2il-methodrecon: System.Uri.GetHashCode
GetHashCode()
override int System.Uri.GetHashCode () inline
Definition at line 1306 of file Uri.cs.
        {
            if (this.m_Syntax != null)
            {
                global::System.Uri.Flags flags = this.m_Flags;
                this.CreateUriInfo(flags);
                global::System.Uri.UriInfo info = this.m_Info;
                if (info.MoreInfo == null)
                {
                }
                int num = global::System.Uri.CalculateCaseInsensitiveHashCode(this.GetComponents(global::System.UriComponents.HttpRequestUrl, global::System.UriFormat.SafeUnescaped));
                info.MoreInfo.Hash = num;
                return num;
            }
            bool originalStringSwitched = this.OriginalStringSwitched;
            if (24 == 0)
            {
            }
            int num2;
            return num2;
        }
References System.Uri.Uri(), System.Uri.CreateUriInfo(), System.Uri.GetComponents(), System.info, j__TPar, System.Uri.m_Flags, System.Uri.m_Info, System.Uri.m_Syntax, and System.Uri.OriginalStringSwitched.