terraria-cpp2il-methodrecon: System.Uri.GetComponents
GetComponents()
string System.Uri.GetComponents (global::System::UriComponents components, global::System::UriFormat format) inline
Definition at line 2154 of file Uri.cs.
        {
            global::System.UriParser syntax = this.m_Syntax;
            if (syntax != null)
            {
                bool isSimple = syntax.IsSimple;
                return this.GetComponentsHelper(components, format);
            }
            return this.GetRelativeSerializationString(format);
        }
References System.format, System.Uri.GetComponentsHelper(), System.Uri.GetRelativeSerializationString(), System.UriParser.IsSimple, j__TPar, and System.Uri.m_Syntax.
Referenced by System.Uri.GetHashCode(), System.Uri.GetObjectData(), and System.Uri.GetParts().