terraria-cpp2il-methodrecon: System.Uri.CreateUri
CreateUri()
void System.Uri.CreateUri (global::System::Uri baseUri, string relativeUri, bool dontEscape) inline private
Definition at line 319 of file Uri.cs.
        {
            do
            {
                bool isSimple = baseUri.m_Syntax.IsSimple;
                if (!true)
                {
                }
            }
            while (relativeUri != null);
            if (true)
            {
                global::System.Uri uri;
                if (uri != null)
                {
                    this.CreateThisFromUri(uri);
                    return;
                }
            }
            else
            {
                global::System.Uri uri;
                while (uri != null)
                {
                }
            }
            string text;
            long num;
            this.CreateThis(text, num != 0L, global::System.UriKind.Absolute);
        }
References System.Uri.CreateThis(), System.Uri.CreateThisFromUri(), j__TPar, System.L, and System.text.
Referenced by System.Uri.Uri().