terraria-cpp2il-methodrecon: System.Uri.GetLocalPath
GetLocalPath()
string System.Uri.GetLocalPath () inline private
Definition at line 906 of file Uri.cs.
        {
            int num;
            do
            {
                global::System.Uri.Flags flags = this.m_Flags;
                this.ParseRemaining();
                global::System.Uri.UriInfo info = this.m_Info;
                ushort host = info.Offset.Host;
                ushort path = info.Offset.Path;
                bool isFile = this.IsFile;
                bool originalStringSwitched = this.OriginalStringSwitched;
                num = 24;
                bool isLoopback = this.IsLoopback;
                global::System.Uri.UriInfo info2 = this.m_Info;
                ushort host2 = info2.Offset.Host;
                ushort path2 = info2.Offset.Path;
                bool originalStringSwitched2 = this.OriginalStringSwitched;
                ushort path3 = this.m_Info.Offset.Path;
                long num2 = 0L;
                global::System.Uri.Flags flags2 = this.m_Flags;
                if (path3 == 0)
                {
                }
            }
            while (num != 0);
            global::System.Uri.Flags flags3 = this.m_Flags;
            if (false)
            {
                long num3 = 0L;
                this.EnsureHostString(num3 != 0L);
                global::System.Uri.Flags flags4 = this.m_Flags;
                if (8212 == 0)
                {
                    global::System.Uri.UriInfo info3 = this.m_Info;
                    ushort path4 = info3.Offset.Path;
                }
                else
                {
                    global::System.Uri.UriInfo info4 = this.m_Info;
                    string host3 = info4.Host;
                    ushort path5 = info4.Offset.Path;
                    int stringLength = host3._stringLength;
                    ushort fragment = info4.Offset.Fragment;
                    long num2;
                    global::System.Uri.UriInfo info3;
                    ushort end;
                    if (num2 != 0L)
                    {
                        int num4 = 2;
                        int stringLength2 = host3._stringLength;
                        global::System.UriParser syntax = this.m_Syntax;
                        if (num4 == 0)
{
                        }
                        ushort host4 = info3.Offset.Host;
                        ushort host5 = info3.Offset.Host;
                        ushort query = info3.Offset.Query;
                        end = info3.Offset.End;
                        string @string = this.m_String;
                        string string2 = this.m_String;
                        string string3 = this.m_String;
                        global::System.Uri.UriInfo info5 = this.m_Info;
                        string string4 = this.m_String;
                        ushort query2 = info5.Offset.Query;
                        return string4;
                    }
                    char c = this.m_String[(int)path5];
                    char c2 = this.m_String[(int)path5];
                    global::System.Uri.Flags flags5 = this.m_Flags;
                    global::System.Uri.UriInfo info6 = this.m_Info;
                    string string5 = this.m_String;
                    global::System.UriParser syntax2 = this.m_Syntax;
                    ushort query3 = info6.Offset.Query;
                    if (info6 == null)
                    {
                    }
                    global::System.Uri.Flags flags6 = this.m_Flags;
                    global::System.UriParser syntax3 = this.m_Syntax;
                    if (info3 == null)
                    {
                    }
                    int num5 = 92;
                    end.m_value = (ushort)num5;
                    string text;
                    return text;
                }
            }
            string text2;
            return text2;
        }
References System.Uri.Uri(), System.Uri.EnsureHostString(), System.UriParser.Flags, System.Uri.Host, System.Uri.Offset.Host, System.info, System.Uri.IsFile, System.Uri.IsLoopback, j__TPar, System.L, System.Uri.m_Flags, System.Uri.m_Info, System.Uri.m_String, System.Uri.m_Syntax, System.Uri.OriginalStringSwitched, System.Uri.ParseRemaining(), System.Uri.Offset.Path, and System.text.