terraria-cpp2il-methodrecon: System.Uri.CreateThis
CreateThis()
void System.Uri.CreateThis (string uri, bool dontEscape, global::System::UriKind uriKind) inline private
Definition at line 1977 of file Uri.cs.
        {
            do
            {
                if (uri == null)
                {
                }
                global::System.Uri.Flags flags = this.m_Flags;
                this.m_Flags = flags;
            }
            while (uriKind != global::System.UriKind.RelativeOrAbsolute);
        }
References j__TPar, and System.Uri.m_Flags.
Referenced by System.Uri.Uri(), System.Uri.Uri(), System.Uri.Uri(), System.Uri.Uri(), and System.Uri.CreateUri().