terraria-cpp2il-methodrecon: System.Uri.InternalIsWellFormedOriginalString
InternalIsWellFormedOriginalString()
bool System.Uri.InternalIsWellFormedOriginalString () inline package
Definition at line 2187 of file Uri.cs.
        {
            if (this.m_String != null)
            {
                int offsetToStringData = RuntimeHelpers.OffsetToStringData;
            }
            if (this.m_Syntax != null)
            {
                global::System.Uri.Flags flags = this.m_Flags;
                this.ParseRemaining();
                global::System.Uri.Flags flags2 = this.m_Flags;
                if (!this.m_iriParsing)
                {
                    goto IL_017A;
                }
                global::System.Uri.UriInfo info = this.m_Info;
                ushort query = info.Offset.Query;
                ushort path = info.Offset.Path;
                global::System.Uri.UriInfo info2 = this.m_Info;
                string @string = this.m_String;
                ushort path2 = info2.Offset.Path;
                ushort securedPathIndex = this.SecuredPathIndex;
                global::System.Uri.Flags flags3 = this.m_Flags;
                global::System.Uri.UriInfo info3 = this.m_Info;
                ushort user = info3.Offset.User;
                ushort path3 = info3.Offset.Path;
                if (!this.m_iriParsing)
                {
                    goto IL_017D;
                }
                global::System.Uri.Flags flags4 = this.m_Flags;
                int stringLength = this.m_Syntax.m_Scheme._stringLength;
                int stringLength2 = this.m_String._stringLength;
            }
            bool shouldUseLegacyV2Quirks = global::System.UriParser.ShouldUseLegacyV2Quirks;
            bool flag = global::System.Uri.CheckForColonInFirstPathSegment(this.m_String);
            int stringLength3 = this.m_String._stringLength;
            global::System.UriParser syntax = this.m_Syntax;
            global::System.Uri.UriInfo info4 = this.m_Info;
            string scheme = syntax.m_Scheme;
            global::System.Uri.Offset offset = info4.Offset;
            int stringLength4 = scheme._stringLength;
            ushort user2 = info4.Offset.User;
            string string2 = this.m_String;
            string string3 = this.m_String;
            IL_017A:
            IL_017D:
            global::System.Uri.Flags flags5 = this.m_Flags;
            ushort user3 = this.m_Info.Offset.User;
            string string4 = this.m_String;
            string string5 = this.m_String;
            global::System.Uri.Flags flags6 = this.m_Flags;
            Type type = base.GetType();
            throw new ArrayTypeMismatchException();
        }
References System.Uri.Uri(), System.Type.GetType(), System.info, j__TPar, System.Uri.m_Flags, System.Uri.m_Info, System.Uri.m_iriParsing, System.UriParser.m_Scheme, System.Uri.m_String, System.Uri.m_Syntax, System.offset, System.Runtime.CompilerServices.RuntimeHelpers.OffsetToStringData, System.Uri.ParseRemaining(), System.Uri.Offset.Query, System.Uri.SecuredPathIndex, and System.Uri.Offset.User.
Referenced by System.Uri.IsWellFormedOriginalString().