terraria-cpp2il-methodrecon: System.Uri.CreateUriInfo
CreateUriInfo()
void System.Uri.CreateUriInfo (global::System::Uri::Flags cF) inline private
Definition at line 1540 of file Uri.cs.
        {
            int stringLength = this.m_String._stringLength;
            int stringLength2 = this.m_Syntax.m_Scheme._stringLength;
        }
References j__TPar, System.UriParser.m_Scheme, System.Uri.m_String, and System.Uri.m_Syntax.
Referenced by System.Uri.EnsureHostString(), System.Uri.EnsureUriInfo(), System.Uri.GetHashCode(), and System.Uri.ParseRemaining().