terraria-cpp2il-methodrecon: System.Uri.ParseRemaining
ParseRemaining()
void System.Uri.ParseRemaining () inline private
Definition at line 1673 of file Uri.cs.
        {
            global::System.Uri.Flags flags = this.m_Flags;
            this.CreateUriInfo(flags);
            global::System.Uri.Flags flags2 = this.m_Flags;
            if (this.m_iriParsing)
            {
            }
            global::System.Uri.Offset offset = this.m_Info.Offset;
            string @string = this.m_String;
            global::System.UriParser syntax = this.m_Syntax;
            int stringLength = @string._stringLength;
            global::System.UriSyntaxFlags flags3 = syntax.m_Flags;
            if (@string != null)
            {
                int offsetToStringData = RuntimeHelpers.OffsetToStringData;
            }
            if (syntax == null)
            {
            }
        }
References System.Uri.Uri(), System.Uri.CreateUriInfo(), j__TPar, System.Uri.m_Flags, System.UriParser.m_Flags, System.Uri.m_Info, System.Uri.m_iriParsing, System.Uri.m_String, System.Uri.m_Syntax, System.offset, and System.Runtime.CompilerServices.RuntimeHelpers.OffsetToStringData.
Referenced by System.Uri.EnsureParseRemaining(), System.Uri.GetLocalPath(), and System.Uri.InternalIsWellFormedOriginalString().