terraria-cpp2il-methodrecon: System.Uri.EnsureHostString
EnsureHostString()
void System.Uri.EnsureHostString (bool allowDnsOptimization) inline private
Definition at line 267 of file Uri.cs.
        {
            global::System.Uri.Flags flags = this.m_Flags;
            this.CreateUriInfo(flags);
            if (this.m_Info.Host != null)
            {
                return;
            }
            this.CreateHostString();
        }
References System.Uri.CreateHostString(), System.Uri.CreateUriInfo(), System.Uri.Host, System.Uri.m_Flags, and System.Uri.m_Info.
Referenced by System.Uri.GetLocalPath(), and System.Uri.ReCreateParts().