terraria-cpp2il-methodrecon: System.Net.NTAuthentication.GetOutgoingBlob
GetOutgoingBlob() [2/3]
byte[] System.Net.NTAuthentication.GetOutgoingBlob (byte[] incomingBlob, bool throwOnError, [Out] SecurityStatusPal statusCode) inline package
Definition at line 260 of file NTAuthentication.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            bool isEnabled = NetEventSource.IsEnabled;
            if (num == 0)
            {
            }
            NetEventSource.Enter(this, incomingBlob, "GetOutgoingBlob");
            global::System.Security.Authentication.ExtendedProtection.ChannelBinding channelBinding = this._channelBinding;
            if (incomingBlob != null)
            {
                if (channelBinding == null)
                {
                    goto IL_003C;
                }
                global::System.Security.Authentication.ExtendedProtection.ChannelBinding channelBinding2 = this._channelBinding;
            }
            global::System.Security.Authentication.ExtendedProtection.ChannelBinding channelBinding3 = this._channelBinding;
            IL_003C:
            int tokenSize = this._tokenSize;
            global::System.Net.Security.SafeDeleteContext securityContext = this._securityContext;
            ContextFlagsPal requestedContextFlags = this._requestedContextFlags;
            SecurityStatusPal securityStatusPal;
            statusCode.ErrorCode = securityStatusPal;
            statusCode.Exception = this;
            bool isEnabled2 = NetEventSource.IsEnabled;
            if ("SSPIWrapper.AcceptSecurityContext() returns statusCode:0x{0:x8} ({1})" == null)
            {
            }
            FormattableString formattableString;
            NetEventSource.Info(this, formattableString, "GetOutgoingBlob");
            string spn = this._spn;
            ContextFlagsPal requestedContextFlags2 = this._requestedContextFlags;
            SecurityStatusPal securityStatusPal2;
            statusCode.ErrorCode = securityStatusPal2;
            statusCode.Exception = this;
            if ("SSPIWrapper.AcceptSecurityContext() returns statusCode:0x{0:x8} ({1})" == null)
            {
            }
            bool isEnabled3 = NetEventSource.IsEnabled;
            if ("SSPIWrapper.InitializeSecurityContext() returns statusCode:0x{0:x8} ({1})" == null)
            {
            }
            FormattableString formattableString2;
            NetEventSource.Info(this, formattableString2, "GetOutgoingBlob");
            SecurityStatusPal securityStatusPal3;
            statusCode.ErrorCode = securityStatusPal3;
            statusCode.Exception = "GetOutgoingBlob";
            if ("GetOutgoingBlob" == null)
            {
            }
            bool isEnabled4 = NetEventSource.IsEnabled;
            if ("SSPIWrapper.CompleteAuthToken() returns statusCode:0x{0:x8} ({1})" == null)
            {
            }
            FormattableString formattableString3;
            NetEventSource.Info(this, formattableString3, "GetOutgoingBlob");
            long num2 = 0L;
            long num3;
            int num4;
            if (securityContext == null)
            {
                global::System.Net.Security.SafeFreeCredentials credentialsHandle = this._credentialsHandle;
                if (credentialsHandle != null)
                {
                    credentialsHandle.Dispose();
                    if (num2 == 0L)
                    {
                        goto IL_0133;
                    }
                    num3 = 0L;
                    num4 = 10;
                    while (securityContext == null)
                    {
                    }
                }
            }
            if (num3 != 0L)
            {
                throw new OutOfMemoryException();
            }
            IL_0133:
            if (num4 == 0)
            {
                if (securityContext == null)
                {
                    global::System.Net.Security.SafeFreeCredentials credentialsHandle2 = this._credentialsHandle;
                    if (credentialsHandle2 != null)
                    {
                        global::System.Net.Security.SSPIHandleCache.CacheCredential(credentialsHandle2);
                    }
                }
                this.CloseContext();
                int num5 = 1;
                this._isCompleted = num5 != 0;
                if (num5 == 0)
                {
                }
                bool isEnabled5 = NetEventSource.IsEnabled;
                FormattableString formattableString4;
                NetEventSource.Exit(this, formattableString4, "GetOutgoingBlob");
                bool isEnabled6 = NetEventSource.IsEnabled;
                bool isEnabled7 = NetEventSource.IsEnabled;
                FormattableString formattableString5;
                NetEventSource.Info(this, formattableString5, "GetOutgoingBlob");
                bool isEnabled8 = NetEventSource.IsEnabled;
                bool isEnabled9 = NetEventSource.IsEnabled;
                bool isCompleted = this._isCompleted;
                FormattableString formattableString6;
                NetEventSource.Exit(this, formattableString6, "GetOutgoingBlob");
            }
            throw new ArrayTypeMismatchException();
        }
References System.Net.NTAuthentication._channelBinding, System.Net.NTAuthentication._credentialsHandle, System.Net.NTAuthentication._isCompleted, System.Net.NTAuthentication._requestedContextFlags, System.Net.NTAuthentication._securityContext, System.Net.NTAuthentication._spn, System.Net.NTAuthentication._tokenSize, System.Net.NTAuthentication.CloseContext(), System.Net.NetEventSource.Enter(), System.Net.NetEventSource.Exit(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.IsEnabled, j__TPar, and System.L.