terraria-cpp2il-methodrecon: System.Threading.RegisteredWaitHandle.Wait
Wait()
void System.Threading.RegisteredWaitHandle.Wait (object state) inline package
Definition at line 21 of file RegisteredWaitHandle.cs.
        {
            SafeWaitHandle safeWaitHandle = this._waitObject.SafeWaitHandle;
            WaitHandle waitObject = this._waitObject;
            if (waitObject != null && waitObject == null)
            {
                throw new ArrayTypeMismatchException();
            }
            ManualResetEvent cancelEvent = this._cancelEvent;
            if (cancelEvent != null && cancelEvent == null)
            {
                throw new ArrayTypeMismatchException();
            }
            TimeSpan timeout = this._timeout;
            if (!this._unregistered)
            {
                int callsInProcess = this._callsInProcess;
                long num = 0L;
                this._callsInProcess = callsInProcess;
                if (callsInProcess != 0)
                {
                    Monitor.Exit(this);
                }
                if (num != 0L)
                {
                    throw new OutOfMemoryException();
                }
                if (!this._unregistered)
                {
                    bool executeOnlyOnce = this._executeOnlyOnce;
                    while (!executeOnlyOnce)
                    {
                    }
                    return;
                }
            }
            int callsInProcess2 = this._callsInProcess;
            int num2 = 1;
            this._unregistered = num2 != 0;
            if (callsInProcess2 != 0)
            {
                return;
            }
            WaitHandle finalEvent = this._finalEvent;
            while (finalEvent == null)
            {
            }
            bool flag = NativeEventCalls.SetEvent(finalEvent.SafeWaitHandle);
            long num3 = 0L;
            if (callsInProcess2 != 0)
            {
                Monitor.Exit(this);
            }
            if (num3 != 0L)
            {
                throw new OutOfMemoryException();
            }
            long num4 = 0L;
            if (callsInProcess2 != 0)
            {
                this._waitObject.SafeWaitHandle.DangerousRelease();
            }
            if (num4 == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.Threading.RegisteredWaitHandle._callsInProcess, System.Threading.RegisteredWaitHandle._cancelEvent, System.Threading.RegisteredWaitHandle._executeOnlyOnce, System.Threading.RegisteredWaitHandle._finalEvent, System.Threading.RegisteredWaitHandle._timeout, System.Threading.RegisteredWaitHandle._unregistered, System.Threading.RegisteredWaitHandle._waitObject, System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Threading.Monitor.Exit(), j__TPar, System.L, System.Threading.WaitHandle.SafeWaitHandle, and System.Threading.NativeEventCalls.SetEvent().