terraria-cpp2il-methodrecon: Terraria.NPC.CanBeChasedBy
CanBeChasedBy()
bool Terraria.NPC.CanBeChasedBy ([Optional] object attacker, bool ignoreDontTakeDamage = false) inline
Definition at line 7266 of file NPC.cs.
        {
            while (this.active && this.chaseable)
            {
                int num = this.lifeMax;
                if (!this.dontTakeDamage || this.friendly)
                {
                    return;
                }
            }
        }
References Terraria.Entity.active, Terraria.NPC.chaseable, Terraria.NPC.dontTakeDamage, Terraria.NPC.friendly, and Terraria.NPC.lifeMax.
Referenced by Terraria.Projectile.AI_053(), Terraria.Player.BloodButcherer_TryButchering(), Terraria.Projectile.Minion_FindTargetInRange(), and Terraria.Player.TentacleSpike_TrySpiking().