terraria-cpp2il-methodrecon: System.Security.Cryptography.RNGCryptoServiceProvider.Check
Check()
void System.Security.Cryptography.RNGCryptoServiceProvider.Check () inline private
Definition at line 62 of file RNGCryptoServiceProvider.cs.
        {
            IntPtr handle = this._handle;
        }
References System.Security.Cryptography.RNGCryptoServiceProvider._handle.
Referenced by System.Security.Cryptography.RNGCryptoServiceProvider.RNGCryptoServiceProvider(), System.Security.Cryptography.RNGCryptoServiceProvider.RNGCryptoServiceProvider(), System.Security.Cryptography.RNGCryptoServiceProvider.RNGCryptoServiceProvider(), System.Security.Cryptography.RNGCryptoServiceProvider.RNGCryptoServiceProvider(), System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(), System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(), and System.Security.Cryptography.RNGCryptoServiceProvider.GetNonZeroBytes().