terraria-cpp2il-methodrecon: Terraria.NPC.AI_123_Deerclops_TryMakingSpike
AI_123_Deerclops_TryMakingSpike()
void Terraria.NPC.AI_123_Deerclops_TryMakingSpike (Point sourceTileCoords, int dir, int howMany, int whichOne, int xOffset) inline private
Definition at line 1993 of file NPC.cs.
        {
            int num = this.AI_123_Deerclops_TryMakingSpike_FindBestY(sourceTileCoords, 43143168);
            bool flag = WorldGen.ActiveAndWalkableTile(43143168, num);
            if (8 == 0)
            {
            }
            IEntitySource spawnSource_ForProjectile = this.GetSpawnSource_ForProjectile();
            int myPlayer = Main.myPlayer;
        }
References Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.NPC.GetSpawnSource_ForProjectile(), j__TPar, and Terraria.Main.myPlayer.