terraria-cpp2il-methodrecon: Terraria.NPC.NPCLoot_DropCommonLifeAndMana
NPCLoot_DropCommonLifeAndMana()
void Terraria.NPC.NPCLoot_DropCommonLifeAndMana (Player closestPlayer) inline private
Definition at line 5423 of file NPC.cs.
        {
            int num = this.type;
            if (closestPlayer.RollLuck(6) == 0)
            {
                int num2 = this.lifeMax;
                if (this.damage == 0)
                {
                }
                int num3;
                if (num3 == 0)
                {
                    int statMana = closestPlayer.statMana;
                    int statManaMax = closestPlayer.statManaMax2;
                    IEntitySource itemSource_Loot = this.GetItemSource_Loot();
                    float x = this.position.X;
                    float y = this.position.Y;
                    int width = this.width;
                    bool wet = this.wet;
                    if (statManaMax == 0)
                    {
                    }
                    return;
                }
                int num4;
                if (num4 == 0)
                {
                    int statLife = closestPlayer.statLife;
                    int statLifeMax = closestPlayer.statLifeMax2;
                    IEntitySource itemSource_Loot2 = this.GetItemSource_Loot();
                    float x2 = this.position.X;
                    float y2 = this.position.Y;
                    int width2 = this.width;
                    bool wet2 = this.wet;
                    if (statLifeMax == 0)
                    {
                    }
                }
            }
            int num5 = this.type;
            if (closestPlayer.RollLuck(2) == 0)
            {
                int num6 = this.lifeMax;
                int num7 = this.damage;
                int statMana2 = closestPlayer.statMana;
                int statManaMax2 = closestPlayer.statManaMax2;
                IEntitySource itemSource_Loot3 = this.GetItemSource_Loot();
                float x3 = this.position.X;
                float y3 = this.position.Y;
                int width3 = this.width;
                bool wet3 = this.wet;
                if (statManaMax2 == 0)
                {
                }
            }
        }
References Terraria.NPC.damage, Terraria.NPC.GetItemSource_Loot(), j__TPar, Terraria.NPC.lifeMax, Terraria.Entity.position, Terraria.Player.RollLuck(), Terraria.Player.statMana, Terraria.NPC.type, Terraria.Entity.wet, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.NPCLoot_DropHeals().