terraria-cpp2il-methodrecon: Terraria.NPC.HitEffect
HitEffect()
void Terraria.NPC.HitEffect (int hitDirection = 0, double dmg = 10::0) inline
Definition at line 6931 of file NPC.cs.
        {
            if (!this.active)
            {
                return;
            }
            if (this.townNPC)
            {
                int num = this.life;
                bool flag = this.UsesPartyHat();
                bool isShimmerVariant = this.IsShimmerVariant;
                int num2 = this.type;
                float x = this.position.X;
                float x2 = this.velocity.X;
                bool isShimmerVariant2 = this.IsShimmerVariant;
                return;
            }
            if (this.daybreak)
            {
                int num3 = this.life;
                Rectangle hitbox = base.Hitbox;
                if (20 != 0)
                {
                    Vector2 vector = hitbox.TopLeft();
                    int width = this.width;
                    bool wet = this.wet;
                    return;
                }
                bool logicHost = Main.LogicHost;
                int num4;
                if (num4 == 0)
                {
                }
                if (num4 == 0 || num4 != 0 || num4 != 0 || num4 != 0 || num4 == 0)
                {
                }
            }
            int num5 = this.type;
            int num6 = this.life;
            Vector2 bottom = base.Bottom;
            if (!true)
            {
            }
            float num7 = this.rotation;
            Gore gore;
            float y = gore.velocity.Y;
            float x3 = gore.velocity.X;
            float num8;
            gore.velocity.Y = num8;
            gore.velocity.Y = num8;
            Vector2 bottom2 = base.Bottom;
            if (!true)
            {
            }
            float num9 = this.rotation;
            Gore gore2;
            float y2 = gore2.velocity.Y;
            float x4 = gore2.velocity.X;
            gore2.velocity.Y = num8;
            gore2.velocity.Y = num8;
            Vector2 bottom3 = base.Bottom;
            Vector2 velocity = this.velocity;
            int num10 = 680;
            this.Transform(num10);
            int num11 = 1;
            this.position.X = y2;
            this.velocity = velocity;
            this.netUpdate = num11 != 0;
            if (num11 == 0)
            {
            }
            bool netHost = Main.NetHost;
            int num12 = this.life;
            float[] array = this.ai;
            Vector2 bottom4 = base.Bottom;
            if (!true)
            {
            }
            float num13 = this.rotation;
            Gore gore3;
            float y3 = gore3.velocity.Y;
            float x5 = gore3.velocity.X;
            gore3.velocity.Y = num8;
            gore3.velocity.Y = num8;
            Vector2 bottom5 = base.Bottom;
            if (!true)
            {
            }
            float num14 = this.rotation;
            Gore gore4;
            float y4 = gore4.velocity.Y;
            float x6 = gore4.velocity.X;
            gore4.velocity.Y = num8;
            gore4.velocity.Y = num8;
            NPC npc = this.AI_113_WindyBalloon_GetSlaveNPC();
            if (npc != null)
            {
                float[] array2 = npc.ai;
                float y5 = npc.position.Y;
                int num15 = 1;
                npc.netUpdate = num15 != 0;
                npc.position.Y = y5;
            }
            int num16 = this.life;
            int num17 = this.lifeMax;
            int num18;
            if (num18 == 0)
            {
                int num19 = 255;
                float num20;
                Color color = Main.hslToRgb(num20, num8, num20, (byte)num19);
                float x7 = this.position.X;
                float y6 = this.position.Y;
                int width2 = this.width;
                bool wet2 = this.wet;
                Vector2 center = base.Center;
                int width3 = this.width;
                bool wet3 = this.wet;
                Vector2 center2 = base.Center;
                return;
            }
            int num21 = this.lifeMax;
        }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.AI_113_WindyBalloon_GetSlaveNPC(), System.array, Terraria.NPC.color, Terraria.NPC.daybreak, Terraria.Main.hslToRgb(), Terraria.NPC.IsShimmerVariant, j__TPar, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.LogicHost, Terraria.Main.NetHost, Terraria.Entity.position, Terraria.NPC.rotation, Terraria.NPC.townNPC, Terraria.NPC.Transform(), Terraria.NPC.type, Terraria.NPC.UsesPartyHat(), Terraria.Entity.velocity, Terraria.Gore.velocity, Terraria.Entity.wet, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI_037_Destroyer().