terraria-cpp2il-methodrecon: Terraria.NPC.UpdateCollision
UpdateCollision()
void Terraria.NPC.UpdateCollision () inline private
Definition at line 9169 of file NPC.cs.
        {
            this.Collision_WalkDownSlopes();
            bool flag = this.Collision_LavaCollision();
            if (!this.wet)
            {
            }
            byte wetCount = this.wetCount;
            if (wetCount != 0)
            {
                this.wetCount = wetCount;
            }
            bool flag2 = this.Collision_DecideFallThroughPlatforms();
            Vector2 velocity = this.velocity;
            this.oldVelocity = velocity;
            this.FishTransformationDuringRain();
            float x = this.velocity.X;
            float y = this.velocity.Y;
            if (!this.wet)
            {
                this.Collision_MoveWhileDry();
                return;
            }
            if (this.shimmerWet)
            {
                float num = this.shimmerMovementSpeed;
                return;
            }
            if (this.honeyWet)
            {
                float num2 = this.honeyMovementSpeed;
                return;
            }
            if (this.lavaWet)
            {
                float num3 = this.lavaMovementSpeed;
                return;
            }
            float num4 = this.waterMovementSpeed;
            int num5 = this.aiStyle;
            this.Collision_MoveSnailOnSlopes();
        }
References Terraria.NPC.aiStyle, Terraria.NPC.Collision_DecideFallThroughPlatforms(), Terraria.NPC.Collision_LavaCollision(), Terraria.NPC.Collision_MoveSnailOnSlopes(), Terraria.NPC.Collision_MoveWhileDry(), Terraria.NPC.Collision_WalkDownSlopes(), Terraria.NPC.FishTransformationDuringRain(), Terraria.NPC.honeyMovementSpeed, Terraria.Entity.honeyWet, j__TPar, Terraria.NPC.lavaMovementSpeed, Terraria.Entity.lavaWet, Terraria.NPC.shimmerMovementSpeed, Terraria.Entity.shimmerWet, Terraria.Entity.velocity, Terraria.NPC.waterMovementSpeed, Terraria.Entity.wet, Terraria.Entity.wetCount, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.