terraria-cpp2il-methodrecon: Terraria.NPC.CountKillForBannersAndDropThem
CountKillForBannersAndDropThem()
void Terraria.NPC.CountKillForBannersAndDropThem () inline private
Definition at line 5631 of file NPC.cs.
        {
            int num = this.netID;
            int num2 = 340;
            int num3 = 528;
            if (num2 == 0)
            {
            }
            int num4 = Item.NPCtoBanner(43143168);
            bool flag = this.ExcludedFromDeathTally();
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            bool netHost = Main.NetHost;
            if (num3 == 0)
            {
            }
            int num5 = Item.BannerToItem(num4);
            if (num2 == 0)
            {
            }
            if (num5 == 0)
            {
                if (num5 == 0)
                {
                }
                int num6 = Item.BannerToNPC(num4);
                int num7 = this.lastInteraction;
                if (num5 == 0)
                {
                }
                if (num2 == 0 || num2 == 0)
                {
                }
                if (num2 == 0)
                {
                }
                LocalizedText npcname = Lang.GetNPCName(num6);
                string key = npcname.Key;
                if (npcname == null)
                {
                }
                if (num3 == 0)
                {
                }
                NetworkText networkText;
                if (networkText == null || networkText != null)
                {
                    if (num2 == 0)
                    {
                    }
                    if (networkText == null || networkText != null)
                    {
                        LocalizedText npcname2 = Lang.GetNPCName(42178960);
                        string key2 = npcname2.Key;
                        if (npcname2 == null)
{
                        }
                        if (num3 == 0)
{
                        }
                        NetworkText networkText2;
                        if (networkText2 == null || networkText2 != null)
{
                            if ("Game.EnemiesDefeatedByAnnouncement" == null)
{
                            }
                            if ("Game.EnemiesDefeatedByAnnouncement" != null)
{
                                if ("Game.EnemiesDefeatedByAnnouncement" == null)
{
                                }
                                bool netHost2 = Main.NetHost;
                                if ("Game.EnemiesDefeatedByAnnouncement" == null)
{
                                }
                                return;
                            }
                            int num8 = Item.BannerToItem(num4);
                            return;
                        }
                    }
                }
                throw new ArrayTypeMismatchException();
            }
        }
References Terraria.Item.BannerToItem(), Terraria.Item.BannerToNPC(), Terraria.NPC.ExcludedFromDeathTally(), Terraria.Lang.GetNPCName(), j__TPar, System.key, Terraria.Localization.LocalizedText.Key, Terraria.NPC.lastInteraction, Terraria.Main.NetHost, Terraria.NPC.netID, and Terraria.Item.NPCtoBanner().
Referenced by Terraria.NPC.AI_003_Fighters(), and Terraria.NPC.NPCLoot().