terraria-cpp2il-methodrecon: System.Collections.CollectionBase.Clear
Clear()
void System.Collections.CollectionBase.Clear () inline inherited
Implements System.Collections.IList.
Definition at line 64 of file CollectionBase.cs.
        {
            ArrayList list = this._list;
        }
References System.Collections.CollectionBase._list, and System.list.
Referenced by Mono.Security.X509.X509Store.Clear(), Mono.Security.X509.X509Store.ClearCertificates(), System.Security.Cryptography.X509Certificates.X509Store.Close(), System.Security.Cryptography.X509Certificates.X509Store.Dispose(), Mono.Security.X509.X509Store.ImportNewFormat(), Mono.Security.X509.X509Store.RemoveNewFormat(), and Mono.Security.X509.X509Chain.Reset().