terraria-cpp2il-methodrecon: System.Net.ListenerAsyncResult.Complete
Complete() [3/3]
void System.Net.ListenerAsyncResult.Complete (HttpListenerContext context, bool synch) inline package
Definition at line 76 of file ListenerAsyncResult.cs.
        {
            int num = 1;
            ListenerAsyncResult listenerAsyncResult = this.forward;
            if (listenerAsyncResult != null)
            {
                listenerAsyncResult.Complete(context, synch);
                return;
            }
            object obj = this.locker;
            this.synch = num != 0;
            this.context = context;
            AuthenticationSchemes authenticationSchemes = context.Listener.SelectAuthenticationScheme(context);
            AuthenticationSchemes auth_schemes = context.Listener.auth_schemes;
            if (context.request.headers["Authorization"] == null)
            {
                HttpListenerResponse response = context.response;
                int num2 = 401;
                response.StatusCode = num2;
                WebHeaderCollection headers = context.response.headers;
                string realm = context.Listener.realm;
                string text2;
                string text = text2 + " realm=\"" + realm + "\"";
                headers["WWW-Authenticate"] = text;
                Stream outputStream = context.response.OutputStream;
                HttpListener listener = context.Listener;
                Monitor.Enter(headers, true);
                return;
            }
            ManualResetEvent manualResetEvent = this.handle;
            int num3 = 256;
            this.synch = num3 != 0;
            if (manualResetEvent != null)
            {
                bool flag = manualResetEvent.Set();
            }
            AsyncCallback asyncCallback = this.cb;
            if (asyncCallback != null)
            {
                if (asyncCallback == null)
                {
                }
                return;
            }
            long num4 = 0L;
            Monitor.Exit(obj);
            if (num4 == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.Net.HttpListener.auth_schemes, System.Net.ListenerAsyncResult.cb, System.Net.ListenerAsyncResult.Complete(), System.Net.ListenerAsyncResult.context, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Net.ListenerAsyncResult.forward, System.Net.ListenerAsyncResult.handle, System.Net.HttpListenerRequest.headers, System.Net.HttpListenerResponse.headers, j__TPar, System.L, System.Net.HttpListenerContext.Listener, System.Net.ListenerAsyncResult.locker, System.obj, System.Net.HttpListenerResponse.OutputStream, System.Net.HttpListener.realm, System.Net.HttpListenerContext.request, System.Net.HttpListenerContext.response, System.Net.HttpListener.SelectAuthenticationScheme(), System.Net.ListenerAsyncResult.synch, and System.text.