terraria-cpp2il-methodrecon: System.Net.ListenerAsyncResult.Complete
Complete() [1/3]
void System.Net.ListenerAsyncResult.Complete (Exception exc) inline package
Definition at line 16 of file ListenerAsyncResult.cs.
        {
            ListenerAsyncResult listenerAsyncResult = this.forward;
            if (listenerAsyncResult != null)
            {
                listenerAsyncResult.Complete(exc);
                return;
            }
            bool inGet = this.InGet;
            this.exception = exc;
            int num;
            if (inGet && exc != null)
            {
                num = 500;
            }
            object obj = this.locker;
            Monitor.Enter(obj, num != 0);
            ManualResetEvent manualResetEvent = this.handle;
            int num2 = 1;
            this.completed = num2 != 0;
            if (manualResetEvent != null)
            {
                bool flag = manualResetEvent.Set();
            }
            AsyncCallback asyncCallback = this.cb;
            if (asyncCallback != null)
            {
                if (asyncCallback == null)
                {
                }
                return;
            }
            long num3 = 0L;
            if (asyncCallback != null)
            {
                Monitor.Exit(obj);
            }
            if (num3 == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.Net.ListenerAsyncResult.cb, System.Net.ListenerAsyncResult.Complete(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Net.ListenerAsyncResult.forward, System.Net.ListenerAsyncResult.handle, System.Net.ListenerAsyncResult.InGet, j__TPar, System.L, System.Net.ListenerAsyncResult.locker, and System.obj.
Referenced by System.Net.ListenerAsyncResult.Complete(), System.Net.ListenerAsyncResult.Complete(), and System.Net.ListenerAsyncResult.Complete().