terraria-cpp2il-methodrecon: GUIInventory.ItemOver
ItemOver()
void GUIInventory.ItemOver (int index) inline
Definition at line 95 of file GUIInventory.cs.
    {
        int num = this.itemOffset;
        int myPlayer = Main.myPlayer;
        int myPlayer2 = Main.myPlayer;
        int myPlayer3 = Main.myPlayer;
        int myPlayer4 = Main.myPlayer;
        int myPlayer5 = Main.myPlayer;
        int myPlayer6 = Main.myPlayer;
        bool isAir = Main.mouseItem.IsAir;
        int myPlayer7 = Main.myPlayer;
        int myPlayer8 = Main.myPlayer;
        int myPlayer9 = Main.myPlayer;
        int myPlayer10 = Main.myPlayer;
        int myPlayer11 = Main.myPlayer;
        int myPlayer12 = Main.myPlayer;
        global::Cursor cursor;
        if (cursor != null)
        {
            return;
        }
        global::Cursor cursor2;
        if (cursor2 != null)
        {
            return;
        }
        int myPlayer13 = Main.myPlayer;
        long num2 = 0L;
        this.cursorOver = index;
        int myPlayer14 = Main.myPlayer;
        int myPlayer15 = Main.myPlayer;
        int cursorOverride = Main.cursorOverride;
        int num3 = 49024;
        this.doubleClickTimer = (float)num3;
        if (num2 != 0L)
        {
            if (num3 == 0)
            {
            }
            int myPlayer16 = Main.myPlayer;
            if (num3 == 0)
            {
            }
            Recipe.FindRecipes(false);
            this.itemDragStart = num3;
            this.itemOver = num3;
        }
        string textValue = Language.GetTextValue("ControllerMappings.TakeOne");
        int myPlayer17 = Main.myPlayer;
        Recipe.FindRecipes(false);
    }
References Terraria.Main.cursorOverride, Terraria.Recipe.FindRecipes(), Terraria.Localization.Language.GetTextValue(), System.index, Terraria.Item.IsAir, itemOffset, j__TPar, Microsoft.Xna.Framework.Input.L, Terraria.Main.mouseItem, and Terraria.Main.myPlayer.
Referenced by ItemDraw().