terraria-cpp2il-methodrecon: GUIPageOptions.DrawChestRestock
DrawChestRestock()
void GUIPageOptions.DrawChestRestock () inline
Definition at line 428 of file GUIPageOptions.cs.
    {
        this.LoadRightItemRegion();
        !0 instance = PageControllerLayoutDefinition.Instance;
        int num = 104;
        string[] array = this.options;
        if (num != 0)
        {
            return;
        }
        bool splitKeyPressed = this.SplitKeyPressed;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            bool splitKeyPressed2 = this.SplitKeyPressed;
            if (!splitKeyPressed2)
            {
                if (!splitKeyPressed2)
                {
                }
                Main.mouseLeftRelease = false;
                if (!splitKeyPressed2)
                {
                }
                ChestUI.Restock();
                if (!splitKeyPressed2)
                {
                }
                Recipe.FindRecipes(false);
                return;
            }
        }
    }
References System.array, Terraria.Recipe.FindRecipes(), PageControllerLayoutDefinition< T >.Instance, j__TPar, LoadRightItemRegion(), options, Terraria.UI.ChestUI.Restock(), and SplitKeyPressed.