terraria-cpp2il-methodrecon: Ionic.BZip2.BZip2OutputStream.EmitTrailer
EmitTrailer()
void Ionic.BZip2.BZip2OutputStream.EmitTrailer () inline private
Definition at line 85 of file BZip2OutputStream.cs.
        {
            this.bw.WriteBits(8, (uint)23);
            this.bw.WriteBits(8, (uint)114);
            this.bw.WriteBits(8, (uint)69);
            this.bw.WriteBits(8, (uint)56);
            this.bw.WriteBits(8, (uint)80);
            this.bw.WriteBits(8, (uint)144);
            BitWriter bitWriter = this.bw;
            uint num = this.combinedCRC;
            bitWriter.WriteInt(num);
            this.bw.FinishAndPad();
        }
References Ionic.BZip2.BZip2OutputStream.bw, Ionic.BZip2.BZip2OutputStream.combinedCRC, Ionic.BZip2.BitWriter.FinishAndPad(), j__TPar, Ionic.BZip2.BitWriter.WriteBits(), and Ionic.BZip2.BitWriter.WriteInt().
Referenced by Ionic.BZip2.BZip2OutputStream.Finish().