terraria-cpp2il-methodrecon: Ionic.Zip.NetCfFile.SetTimes
SetTimes()
static int Ionic.Zip.NetCfFile.SetTimes (string filename, DateTime ctime, DateTime atime, DateTime mtime) inline static
Definition at line 10 of file NetCfFile.cs.
        {
            int num;
            IntPtr intPtr = (IntPtr)num;
            int num2 = (int)intPtr;
            long num3;
            byte[] bytes = BitConverter.GetBytes(num3);
            long num4;
            byte[] bytes2 = BitConverter.GetBytes(num4);
            long num5;
            byte[] bytes3 = BitConverter.GetBytes(num5);
            bool flag = NetCfFile.SetFileTime(intPtr, bytes, bytes2, bytes3);
            bool flag2 = NetCfFile.CloseHandle(intPtr);
            return Marshal.GetLastWin32Error();
        }
References Ionic.Zip.NetCfFile.CloseHandle(), System.BitConverter.GetBytes(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), j__TPar, and Ionic.Zip.NetCfFile.SetFileTime().
Referenced by Ionic.Zip.ZipEntry._SetTimes().