terraria-cpp2il-methodrecon: System.Net.Mime.WriteStateInfoBase.Append
Append() [1/2]
void System.Net.Mime.WriteStateInfoBase.Append (byte aByte) inline package inherited
Definition at line 109 of file WriteStateInfoBase.cs.
        {
            int num = 1;
            this.EnsureSpaceInBuffer(num);
            byte[] buffer = this._buffer;
            int currentLineLength = this._currentLineLength;
            this._currentLineLength = currentLineLength;
        }
References System.Net.Mime.WriteStateInfoBase._buffer, System.Net.Mime.WriteStateInfoBase._currentLineLength, System.Net.Mime.WriteStateInfoBase.EnsureSpaceInBuffer(), and j__TPar.
Referenced by System.Net.Mime.WriteStateInfoBase.AppendCRLF(), System.Net.Mime.WriteStateInfoBase.AppendFooter(), and System.Net.Mime.WriteStateInfoBase.AppendHeader().