terraria-cpp2il-methodrecon: GUIAccessoryInfoToggles.DrawToggles
DrawToggles()
void GUIAccessoryInfoToggles.DrawToggles () inline
Definition at line 29 of file GUIAccessoryInfoToggles.cs.
    {
        if (this.Expanded)
        {
            Rectangle region = this.GetRegion();
            !0 instance = PageControllerLayoutDefinition.Instance;
            TransactionButton_Layout transactionButton_Layout;
            Rectangle region2 = GUITransactionButton.GetRegion(transactionButton_Layout);
            if (!this.Expanded)
            {
                !0 instance2 = PageControllerLayoutDefinition.Instance;
                TransactionButton_Layout transactionButton_Layout2;
                Rectangle region3 = GUITransactionButton.GetRegion(transactionButton_Layout2);
            }
            this.CloseExpandedFilter();
            return;
        }
        !0 instance3 = PageControllerLayoutDefinition.Instance;
        string textValue = Language.GetTextValue("Mobile.InfoAccessoriesToggleButton");
        if (this.Expanded)
        {
            bool controllerModeLocked = XNAUnityRunner.ControllerModeLocked;
            if (this.pickingInterceptor == null)
            {
                GUIInputRegionExclusive guiinputRegionExclusive;
                this.pickingInterceptor = guiinputRegionExclusive;
                if (guiinputRegionExclusive != null)
                {
                }
            }
            int num = 1;
            GUIControllerEquipment guicontrollerEquipment;
            guicontrollerEquipment.inAccessories = num != 0;
            return;
        }
    }
References CloseExpandedFilter(), XNAUnityRunner.ControllerModeLocked, Expanded, GetRegion(), GUITransactionButton.GetRegion(), Terraria.Localization.Language.GetTextValue(), PageControllerLayoutDefinition< T >.Instance, j__TPar, and pickingInterceptor.