terraria-cpp2il-methodrecon: UnityEngine.Mesh.GetListForChannel< T >
GetListForChannel< T >() [2/2]
void UnityEngine.Mesh.GetListForChannel< T > (List< T > buffer, int capacity, VertexAttribute channel, int dim, VertexAttributeFormat channelType) inline private
Definition at line 275 of file Mesh.cs.
        {
            bool canAccess = this.canAccess;
            bool flag = this.HasVertexAttribute(channel);
            Array array = NoAllocHelpers.ExtractArrayFromList(buffer);
            this.GetArrayFromChannelImpl(channel, channelType, dim, array);
        }
References System.array, UnityEngine.Mesh.canAccess, UnityEngine.NoAllocHelpers.ExtractArrayFromList(), UnityEngine.Mesh.GetArrayFromChannelImpl(), UnityEngine.Mesh.HasVertexAttribute(), and j__TPar.