terraria-cpp2il-methodrecon: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_MountTransformation
DrawPlayer_MountTransformation()
static void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_MountTransformation (PlayerDrawSet drawInfo) inline static private
Definition at line 115 of file LegacyPlayerRenderer.cs.
        {
            if (!true)
            {
            }
            PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(drawInfo);
            PlayerDrawLayers.DrawPlayer_23_MountFront(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_MountPlus(drawInfo);
            PlayerDrawLayers.DrawPlayer_26_SolarShield(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_MountMinus(drawInfo);
        }
References Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_23_MountFront(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_26_SolarShield(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_MountMinus(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_MountPlus(), and j__TPar.