terraria-cpp2il-methodrecon: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers
DrawPlayer_UseNormalLayers()
static void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers (PlayerDrawSet drawInfo) inline static private
Definition at line 128 of file LegacyPlayerRenderer.cs.
        {
            if (!true)
            {
            }
            PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(drawInfo);
            PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(drawInfo);
            PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(drawInfo);
            PlayerDrawLayers.DrawPlayer_03_Carpet(drawInfo);
            PlayerDrawLayers.DrawPlayer_03_PortableStool(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(drawInfo);
            PlayerDrawLayers.DrawPlayer_04_ElectrifiedDebuffBack(drawInfo);
            PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(drawInfo);
            PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(drawInfo);
            PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(drawInfo);
            PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(drawInfo);
            PlayerDrawLayers.DrawPlayer_08_Backpacks(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(drawInfo);
            PlayerDrawLayers.DrawPlayer_08_1_Tails(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(drawInfo);
            PlayerDrawLayers.DrawPlayer_09_Wings(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(drawInfo);
            PlayerDrawLayers.DrawPlayer_01_BackHair(drawInfo);
            PlayerDrawLayers.DrawPlayer_10_BackAcc(drawInfo);
            PlayerDrawLayers.DrawPlayer_01_3_BackHead(drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(drawInfo);
            PlayerDrawLayers.DrawPlayer_11_Balloons(drawInfo);
            WeaponDrawOrder weaponDrawOrder = drawInfo.weaponDrawOrder;
            if (weaponDrawOrder == WeaponDrawOrder.BehindBackArm)
            {
                if (weaponDrawOrder == WeaponDrawOrder.BehindBackArm)
                {
                }
                PlayerDrawLayers.DrawPlayer_27_HeldItem(drawInfo);
            }
            if (weaponDrawOrder == WeaponDrawOrder.BehindBackArm)
            {
            }
            PlayerDrawLayers.DrawPlayer_12_Skin(drawInfo);
            Player drawPlayer = drawInfo.drawPlayer;
            int body;
            if (drawPlayer.wearsRobe)
            {
                body = drawPlayer.body;
            }
            if (body == 0)
            {
            }
            PlayerDrawLayers.DrawPlayer_13_Leggings(drawInfo);
            PlayerDrawLayers.DrawPlayer_14_Shoes(drawInfo);
        }
References Terraria.Player.body, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_3_BackHead(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_BackHair(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_03_Carpet(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_03_PortableStool(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_04_ElectrifiedDebuffBack(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_1_Tails(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_Backpacks(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_10_BackAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_11_Balloons(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_13_Leggings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(), j__TPar, and Terraria.Player.wearsRobe.