terraria-cpp2il-methodrecon: UnityEngine.UI.LayoutRebuilder.MarkLayoutForRebuild
MarkLayoutForRebuild()
static void UnityEngine.UI.LayoutRebuilder.MarkLayoutForRebuild (RectTransform rect) inline static
Definition at line 130 of file LayoutRebuilder.cs.
        {
            if (!true)
            {
            }
            GameObject gameObject = rect.gameObject;
        }
References UnityEngine.Component.gameObject.
Referenced by UnityEngine.UI.Graphic.OnBeforeTransformParentChanged(), UnityEngine.UI.AspectRatioFitter.OnDisable(), UnityEngine.UI.ContentSizeFitter.OnDisable(), UnityEngine.UI.Graphic.OnDisable(), UnityEngine.UI.LayoutGroup.OnDisable(), UnityEngine.UI.ScrollRect.OnDisable(), UnityEngine.UI.LayoutRebuilder.ReapplyDrivenProperties(), UnityEngine.UI.ContentSizeFitter.SetDirty(), UnityEngine.UI.ScrollRect.SetDirty(), UnityEngine.UI.ScrollRect.SetDirtyCaching(), and UnityEngine.UI.Graphic.SetLayoutDirty().