terraria-cpp2il-methodrecon: Ionic.Zip.ZipOutputStream.PutNextEntry
PutNextEntry()
ZipEntry Ionic.Zip.ZipOutputStream.PutNextEntry (string entryName) inline
Definition at line 501 of file ZipOutputStream.cs.
        {
            bool disposed;
            do
            {
                bool flag = string.IsNullOrEmpty(entryName);
                disposed = this._disposed;
            }
            while (disposed);
            this._FinishCurrentEntry();
            if (!disposed)
            {
            }
            ZipEntry zipEntry = ZipEntry.CreateForZipOutputStream(entryName);
            this._currentEntry = zipEntry;
            ZipEntry currentEntry = this._currentEntry;
            short bitField = currentEntry._BitField;
            currentEntry._BitField = bitField;
            if (bitField == 0)
            {
            }
            DateTime now = DateTime.Now;
            DateTime now2 = DateTime.Now;
            DateTime now3 = DateTime.Now;
            currentEntry.SetEntryTimes(now, now2, now3);
            ZipEntry currentEntry2 = this._currentEntry;
            CompressionLevel compressionLevel = this.<CompressionLevel>k__BackingField;
            currentEntry2.CompressionLevel = compressionLevel;
            ZipEntry currentEntry3 = this._currentEntry;
            CompressionMethod compressionMethod = this.<CompressionMethod>k__BackingField;
            currentEntry3.CompressionMethod = compressionMethod;
            ZipEntry currentEntry4 = this._currentEntry;
            string password = this._password;
            currentEntry4.Password = password;
            ZipEntry currentEntry5 = this._currentEntry;
            EncryptionAlgorithm encryption = this._encryption;
            currentEntry5.Encryption = encryption;
            ZipEntry currentEntry6 = this._currentEntry;
            Encoding alternateEncoding = this._alternateEncoding;
            currentEntry6.<AlternateEncoding>k__BackingField = alternateEncoding;
            ZipOption alternateEncodingUsage = this._alternateEncodingUsage;
            currentEntry6.<AlternateEncodingUsage>k__BackingField = alternateEncodingUsage;
            bool flag2 = entryName.EndsWith("/");
            ZipEntry currentEntry7 = this._currentEntry;
            long num = 0L;
            currentEntry7.MarkAsDirectory();
            ZipEntryTimestamp timestamp = this._timestamp;
            this._currentEntry.EmitTimesInWindowsFormatWhenSaving = num != 0L;
            ZipEntryTimestamp timestamp2 = this._timestamp;
            this._currentEntry.EmitTimesInUnixFormatWhenSaving = num != 0L;
            ZipEntry currentEntry8 = this._currentEntry;
            this.InsureUniqueEntry(currentEntry8);
            this._needToWriteEntryHeader = true;
            return this._currentEntry;
        }
References Ionic.Zip.ZipOutputStream._alternateEncoding, Ionic.Zip.ZipOutputStream._alternateEncodingUsage, Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipOutputStream._currentEntry, Ionic.Zip.ZipOutputStream._disposed, Ionic.Zip.ZipOutputStream._encryption, Ionic.Zip.ZipOutputStream._FinishCurrentEntry(), Ionic.Zip.ZipOutputStream._password, Ionic.Zip.ZipOutputStream._timestamp, Ionic.Zip.ZipOutputStream.AlternateEncoding, Ionic.Zip.ZipOutputStream.AlternateEncodingUsage, Ionic.Zip.ZipEntry.CreateForZipOutputStream(), Ionic.Zip.ZipOutputStream.InsureUniqueEntry(), j__TPar, Ionic.Zip.ZipOutputStream.k__BackingField, System.L, Ionic.Zip.ZipEntry.MarkAsDirectory(), and System.DateTime.Now.