terraria-cpp2il-methodrecon: System.Net.EndpointPermission.IsSubsetOf
IsSubsetOf() [1/2]
bool System.Net.EndpointPermission.IsSubsetOf (EndpointPermission perm) inline package
Definition at line 90 of file EndpointPermission.cs.
        {
            if (perm == null)
            {
                return;
            }
            int num = perm.port;
            int num2 = this.port;
            TransportType transportType = perm.transport;
            TransportType transportType2 = this.transport;
            this.Resolve();
            perm.Resolve();
            if (this.hasWildcard)
            {
                if (perm.hasWildcard)
                {
                    string text = this.hostname;
                    string text2 = perm.hostname;
                    return this.IsSubsetOf(text, text2);
                }
                return;
            }
            else
            {
                IPAddress[] array = this.addresses;
                if (array == null)
                {
                    return;
                }
                if (perm.hasWildcard)
                {
                    ushort[] numbers = array._numbers;
                    string text3 = perm.hostname;
                }
                IPAddress[] array2 = perm.addresses;
                if (array2 != null)
                {
                    ushort[] numbers2 = array2._numbers;
                    string text4 = this.hostname;
                    return;
                }
                return;
            }
        }
References System.Net.IPAddress._numbers, System.Net.EndpointPermission.addresses, System.array, System.Net.EndpointPermission.hasWildcard, System.Net.EndpointPermission.hostname, System.Net.EndpointPermission.IsSubsetOf(), j__TPar, System.Net.EndpointPermission.port, System.Net.EndpointPermission.Resolve(), System.text, and System.Net.EndpointPermission.transport.
Referenced by System.Net.EndpointPermission.IsSubsetOf().