terraria-cpp2il-methodrecon: Terraria.Tile.CopyPaintAndCoating
CopyPaintAndCoating()
void Terraria.Tile.CopyPaintAndCoating (Tile other) inline
Definition at line 1355 of file Tile.cs.
        {
            short sTileHeader = this.sTileHeader;
            short sTileHeader2 = this.sTileHeader;
            this.SetSTileHeader(sTileHeader2);
            byte bTileHeader = this.bTileHeader3;
            this.invisibleBlock(sTileHeader2 != 0);
            byte bTileHeader2 = this.bTileHeader3;
            this.fullbrightBlock(sTileHeader2 != 0);
        }
References Terraria.Tile.bTileHeader, Terraria.Tile.bTileHeader2, Terraria.Tile.bTileHeader3, Terraria.Tile.fullbrightBlock(), Terraria.Tile.invisibleBlock(), j__TPar, Terraria.Tile.SetSTileHeader(), and Terraria.Tile.sTileHeader.