terraria-cpp2il-methodrecon: Terraria.Tile.halfBrick
halfBrick() [1/2]
bool Terraria.Tile.halfBrick () inline
Definition at line 1127 of file Tile.cs.
        {
            /*
An exception occurred when decompiling this method (06002A9F)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean Terraria.Tile::halfBrick()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:int16(var_0_06, callgetter:int16(Tile::get_sTileHeader, ldloc:valuetype Terraria.Tile&(this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceExplosive(), Terraria.WorldBuilding.Actions.HalfBlock.Apply(), Terraria.WorldBuilding.Actions.SetHalfTile.Apply(), Terraria.Collision.CanHitWithCheck(), Terraria.WorldGen.CheckAlch(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.Collision.HitTiles(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceChestDirect(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PoundPlatform(), Terraria.WorldGen.PoundTile(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTileNoAttach(), and Terraria.Collision.StickyTiles().