terraria-cpp2il-methodrecon: Terraria.Tile.ResetToType
ResetToType()
void Terraria.Tile.ResetToType (ushort type) inline
Definition at line 1298 of file Tile.cs.
        {
            long num = 0L;
            this.SetLiquid((byte)num);
            long num2 = 0L;
            this.SetBTileHeader((byte)num2);
            long num3 = 0L;
            this.SetBTileHeader2((byte)num3);
            long num4 = 0L;
            this.SetBTileHeader3((byte)num4);
            long num5 = 0L;
            this.SetFrameX((short)num5);
            long num6 = 0L;
            this.SetFrameY((short)num6);
            this.SetType(type);
        }
References j__TPar, System.L, Terraria.Tile.SetBTileHeader(), Terraria.Tile.SetBTileHeader2(), Terraria.Tile.SetBTileHeader3(), Terraria.Tile.SetFrameX(), Terraria.Tile.SetFrameY(), Terraria.Tile.SetLiquid(), and Terraria.Tile.SetType().
Referenced by Terraria.WorldBuilding.TileFont.DrawChar(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), and Terraria.GameContent.Generation.TrackGenerator.PlacePath().