terraria-cpp2il-methodrecon: Terraria.Tile.active
active() [1/2]
bool Terraria.Tile.active () inline
Definition at line 1241 of file Tile.cs.
        {
            /*
An exception occurred when decompiling this method (06002AA6)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean Terraria.Tile::active()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:int16(var_0_06, callgetter:int16(Tile::get_sTileHeader, ldloc:valuetype Terraria.Tile&(this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.AddShadowOrb(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.Player.AdjTiles(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_022(), Terraria.NPC.AI_045_Golem(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_RemoveRope(), Terraria.GameContent.MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack(), Terraria.GameContent.Generation.ActionGrass.Apply(), Terraria.GameContent.Generation.ActionVines.Apply(), Terraria.WorldBuilding.Actions.TileScanner.Apply(), Terraria.WorldBuilding.Actions.SetTile.Apply(), Terraria.WorldBuilding.Modifiers.OnlyTiles.Apply(), Terraria.WorldBuilding.Modifiers.IsTouching.Apply(), Terraria.WorldBuilding.Modifiers.NotTouching.Apply(), Terraria.WorldBuilding.Modifiers.IsTouchingAir.Apply(), Terraria.WorldBuilding.Modifiers.SkipTiles.Apply(), Terraria.WorldBuilding.Modifiers.IsEmpty.Apply(), Terraria.WorldBuilding.Modifiers.IsSolid.Apply(), Terraria.WorldBuilding.Modifiers.IsNotSolid.Apply(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.GameContent.Biomes.HiveBiome.BadSpotForHoneyFall(), GUIAccessoryInfo.BuildInfoAccs(), Terraria.WorldGen.CactusFrame(), Terraria.Collision.CanHitWithCheck(), Terraria.Player.CanMoveForwardOnRope(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldGen.CanPoundTile(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.DelegateMethods.CastLightOpenFunc(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChest(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldGen.CheckLogicTiles(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckPalmTree(), Terraria.Player.CheckPulley(), Terraria.Player.CheckSpawn_Internal(), Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot(), Terraria.WorldGen.CheckTileFrames(), Terraria.WorldGen.CheckTree(), Terraria.WorldGen.CheckTreeWithSettings(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections(), Terraria.WorldGen.CountTileTypesInArea(), Terraria.GameContent.Biomes.HiveBiome.CreateBlockedHoneyCube(), Terraria.NPC.CreateBrickBoxForWallOfFlesh(), Terraria.Projectile.CreateImpactExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.WorldGen.CrimEnt(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.CrimVein(), Terraria.Wiring.DeActive(), Terraria.WorldGen.DestroyHeart(), Terraria.WorldGen.DontStarveTryWateringTile(), GUIClothesWindow.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.WorldGen.dropMeteor(), Terraria.WorldGen.DungeonPitTrap(), Terraria.WorldGen.DungeonRoom(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.Collision.EmptyTile(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.EveryTileFrame(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpot(), Terraria.Player.FindPulley(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FixChand(), Terraria.WorldGen.FixChands(), Terraria.IO.ChestInfo_OldMobile.FixDresserChests(), Terraria.IO.WorldFile.FixDresserChests(), WorldFile_OldConsole.FixDresserChests(), WorldFile_OldSwitch.FixDresserChests(), Terraria.WorldGen.FixHeart(), Terraria.WorldGen.FixHearts(), Terraria.WorldGen.FixSunflowers(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.WorldGen.GERunner(), Terraria.Player.GetHurtTile(), Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetTreeVariant(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.WorldGen.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.hardUpdateWorld(), Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), Terraria.WorldGen.HellHouse(), Terraria.WorldGen.HellRoom(), Terraria.GameContent.Golf.GolfHelper.HitGolfBall(), Terraria.Collision.HitTiles(), Terraria.Player.InterruptItemUsageIfOverTile(), Terraria.WorldGen.IsBelowANonHammeredPlatform(), Terraria.Player.IsBottomOfTreeTrunkNoRoots(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsGoodSpotsForExplosive(), Terraria.WorldGen.IslandHouse(), Terraria.WorldGen.IsTileALeafyTreeTop(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryHittingWall(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_GetTreeDrops(), Terraria.IO.SignInfo_OldMobile.Load(), Terraria.IO.WorldFile.LoadSigns(), WorldFile_OldConsole.LoadSigns(), WorldFile_OldSwitch.LoadSigns(), Terraria.WorldGen.MakeDungeon_GroundFurniture(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.GameContent.MinecartDiggerHelper.MineTheTileIfNecessary(), Terraria.Chest.NearOtherChests(), Terraria.DelegateMethods.NotDoorStand(), Terraria.NPC.NPCCanStickToWalls(), Terraria.WorldGen.oceanCave(), Terraria.WorldGen.OpenDoor(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.outerTempled(), Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheSand(), Terraria.WorldGen.PaintTheTemple(), Terraria.WorldGen.PaintTheTrees(), Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.GraniteBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.WorldGen.Place1x2(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place1xX(), Terraria.WorldGen.Place2x1(), Terraria.WorldGen.Place2x3Wall(), Terraria.WorldGen.Place3x1(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x2Wall(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.Place3x3Wall(), Terraria.WorldGen.Place3x4(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.Place4x3Wall(), Terraria.WorldGen.Place5x4(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.Place6x4Wall(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceBanner(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot(), Terraria.WorldGen.PlaceCannon(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChand(), Terraria.WorldGen.PlaceChestDirect(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceDresserDirect(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLogicTiles(), Terraria.WorldGen.PlaceMan(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlacePumpkin(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceStatueTrap(), Terraria.WorldGen.PlaceSunflower(), Terraria.Player.PlaceThing_CannonBall(), Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.PlaceThing_LockChest(), Terraria.Player.PlaceThing_Paintbrush(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.Player.PlaceThing_Walls(), Terraria.Player.PlaceThing_XMasTreeTops(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.placeTNTBarrel(), Terraria.WorldGen.PlaceUncheckedStalactite(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.Player.PlaceWeapon(), Terraria.IO.TilInfo_OldMobile.PlaceWeapon(), WorldFile_OldConsole.PlaceWeapon(), WorldFile_OldSwitch.PlaceWeapon(), Terraria.WorldGen.PlaceWoman(), Terraria.WorldGen.PlaceXmasTree(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.Pyramid(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickMinecart(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), Terraria.WorldGen.ReplaceTile_EliminateNaturalExtras(), Terraria.GameContent.Biomes.TerrainPass.RetargetColumn(), Terraria.GameContent.Tile_Entities.TELogicSensor.SanityCheck(), Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.WorldGen.ScoreRoom_CanBeHomeSpot(), Terraria.Framing.SelfFrame8Way(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.Collision.SolidTiles(), Terraria.NPC.Spawning_SandstoneCheck(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.Projectile.SpawnWebs(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), Terraria.GameContent.SmartCursorHelper.Step_LawnMower(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.GameContent.SmartCursorHelper.Step_PlanterBox(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.Player.StickyMovement(), Terraria.Collision.StickyTiles(), Terraria.GameContent.Events.DD2Event.SummonCrystalDirect(), Terraria.WorldGen.SwitchFountain(), Terraria.WorldGen.SwitchMB(), Terraria.WorldGen.SwitchMonolith(), Terraria.WorldGen.templeCleaner(), Terraria.WorldGen.templePart2(), Terraria.WorldGen.tileCountAndDestroy(), Terraria.WorldGen.tileCounterKill(), Terraria.WorldGen.TileEmpty(), Terraria.Player.TileInteractionsCheck(), Terraria.Player.TileInteractionsCheckLongDistance(), Terraria.WorldGen.TileIsExposedToAir(), Terraria.WorldGen.ToggleGemLock(), Terraria.Minecart.TrackColors(), Terraria.WorldGen.TreeGrowFXCheck(), Terraria.Player.TryBouncingBlocks(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.Player.TryLandingOnDetonator(), Terraria.WorldGen.TryToggleLight(), Terraria.Player.TryUsingDiggerCart(), Terraria.Wiring.UpdateMech(), Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.WorldGen.WillWaterPlacedHereStayPut(), and Terraria.WorldGen.WouldTileReplacementWork().