terraria-cpp2il-methodrecon: Terraria.Tile.ClearEverything
ClearEverything()
void Terraria.Tile.ClearEverything () inline
Definition at line 355 of file Tile.cs.
        {
        }
Referenced by Terraria.WorldBuilding.Actions.Clear.Apply(), Terraria.WorldBuilding.Passes.Clear.ApplyPass(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), and Terraria.GameContent.Generation.TrackGenerator.PlacePath().