terraria-cpp2il-methodrecon: Terraria.Tile.nactive
nactive()
bool Terraria.Tile.nactive () inline
Definition at line 1187 of file Tile.cs.
        {
            /*
An exception occurred when decompiling this method (06002AA3)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean Terraria.Tile::nactive()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:int16(var_0_06, callgetter:int16(Tile::get_sTileHeader, ldloc:valuetype Terraria.Tile&(this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.CheckAlch(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.Physics.BallCollision.CheckForPassThrough(), Terraria.Player.CheckIceBreak(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckSunflower(), Terraria.Liquid.DelWater(), Terraria.Mount.DrillSmartCursor_BlocksPlot(), Terraria.Physics.BallCollision.GetCollisionPointForTile(), Terraria.Player.GetFloorTile(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.mayanTrap(), Terraria.Player.MinionRestTargetAim(), Terraria.WorldGen.Place1x1(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBanner(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.WorldGen.PlantCheck(), Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.Player.Spawn_IsAreaAValidWorldSpawn(), Terraria.WorldGen.SpawnTownNPC(), and Terraria.GameContent.SmartCursorHelper.Step_Boulders().