terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawImmediateBatch
DrawImmediateBatch()
void Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawImmediateBatch (Effect effect) inline
Definition at line 69 of file SpriteBatcher.cs.
        {
            int batchItemCount = this._batchItemCount;
            if (batchItemCount != 0)
            {
                if (batchItemCount == 0)
                {
                }
                int num = 1;
                if (num == 0)
                {
                }
                int value = num.m_value;
                if (!true)
                {
                }
                int num2 = 1;
                if (num2 == 0)
                {
                }
                if (num2 == 0)
                {
                    if (num2 == 0)
                    {
                    }
                    bool gameMenu = Main.gameMenu;
                    if (num2 == 0)
                    {
                    }
                    int myPlayer = Main.myPlayer;
                    if (num2 == 0)
                    {
                    }
                    int screenHeight = Main.screenHeight;
                }
                EffectPass overloadedEffectPass = this._batchItemList.OverloadedEffectPass;
                SpriteBatcher.VertexData[] array = this.vertexData;
                string name = overloadedEffectPass.Name;
                if (array != null)
                {
                    return;
                }
                int vertexOffset = this._vertexOffset;
                int indexOffset = this._indexOffset;
                int vertexOffset2 = this._vertexOffset;
                int batchIndex = overloadedEffectPass.BatchIndex;
                this._vertexOffset.m_value = batchIndex;
                this._vertexOffset.m_value = batchIndex;
                this._vertexOffset.m_value = batchIndex;
                int vertexOffset3 = this._vertexOffset;
                GraphicsDevice device = this._device;
                this._vertexOffset = vertexOffset3;
                Texture2D[] textures = device.Textures;
                if (name != null && name == null)
                {
                    throw new ArrayTypeMismatchException();
                }
                textures.<Name>k__BackingField = name;
                Effect effect2 = overloadedEffectPass._effect;
                if (this._vertexOffset == 0)
                {
                }
                int num3 = 1;
                if (num3 == 0)
                {
                }
                int value2 = num3.m_value;
                if (!true)
                {
                }
                int num4 = 1;
                if (num4 == 0)
                {
                }
                if (num4 == 0)
                {
                    if (num4 == 0)
                    {
                    }
                    bool gameMenu2 = Main.gameMenu;
                    if (num4 == 0)
                    {
                    }
                    int myPlayer2 = Main.myPlayer;
                    if (num4 == 0)
                    {
                    }
                    int screenHeight2 = Main.screenHeight;
                }
                int vertexOffset4 = this._vertexOffset;
                int materialOffset = this._materialOffset;
                Dictionary<int, SpriteBatchItemList> activeBatchLists = this._activeBatchLists;
                this._lastBatchListId = num4;
            }
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatcher._activeBatchLists, Microsoft.Xna.Framework.Graphics.SpriteBatcher._batchItemCount, Microsoft.Xna.Framework.Graphics.SpriteBatcher._batchItemList, Microsoft.Xna.Framework.Graphics.SpriteBatcher._device, Microsoft.Xna.Framework.Graphics.SpriteBatcher._indexOffset, Microsoft.Xna.Framework.Graphics.SpriteBatcher._materialOffset, Microsoft.Xna.Framework.Graphics.SpriteBatcher._vertexOffset, System.array, Microsoft.Xna.Framework.Graphics.EffectPass.BatchIndex, Terraria.Main.gameMenu, j__TPar, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Graphics.EffectPass.Name, System.name, System.Name, Microsoft.Xna.Framework.Graphics.SpriteBatchItem.OverloadedEffectPass, Terraria.Main.screenHeight, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, System.value, and Microsoft.Xna.Framework.Graphics.SpriteBatcher.vertexData.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushIfNeeded().