terraria-cpp2il-methodrecon: System.Net.HttpListenerRequest.FinishInitialization
FinishInitialization()
bool System.Net.HttpListenerRequest.FinishInitialization () inline package
Definition at line 75 of file HttpListenerRequest.cs.
        {
            string userHostName = this.UserHostName;
            Version version = this.version;
            if (userHostName != null && userHostName._stringLength != 0)
            {
                bool flag = HttpListenerRequest.MaybeUri(this.raw_url.ToLowerInvariant());
                string text = this.raw_url;
                if (userHostName == null)
                {
                    string text2 = this.raw_url;
                    if (userHostName == null)
                    {
                        goto IL_004E;
                    }
                }
                if (userHostName._stringLength != 0)
                {
                    goto IL_0060;
                }
                IL_004E:
                IPEndPoint localEndPoint = this.context.cnc.LocalEndPoint;
                IL_0060:
                int num = 58;
                string text3;
                int num2 = text3.IndexOf((char)num);
                long num3 = 0L;
                string text4 = text3.Substring((int)num3, num2);
                HttpConnection cnc = this.context.cnc;
                bool secure = cnc.secure;
                if (cnc.LocalEndPoint._port == 0)
                {
                }
                string query = this.url.Query;
                this.CreateQueryString(query);
                string text5 = this.raw_url;
                string scheme = this.url.Scheme;
                string authority = this.url.Authority;
                string localPath = this.url.LocalPath;
                string query2 = this.url.Query;
                global::System.Uri requestUri = HttpListenerRequestUriBuilder.GetRequestUri(text5, scheme, authority, localPath, query2);
                this.url = requestUri;
                Version version2 = this.version;
                if (this.headers["Transfer-Encoding"] == null)
                {
                    goto IL_0152;
                }
                this.is_chunked = "chunked" != null;
                int num4;
                if (num4 == 0)
                {
                    goto IL_0159;
                }
                HttpListenerContext httpListenerContext = this.context;
                string text6;
                this.context.error = text6;
            }
            if ("Invalid host name" != null)
            {
                goto IL_0159;
            }
            IL_0152:
            if ("Invalid host name" == null)
            {
                goto IL_0160;
            }
            IL_0159:
            int num5;
            if (num5 == 0)
            {
            }
            IL_0160:
            int num6;
            if (num6 != 0)
            {
                int num7;
                while (num7 != 0)
                {
                }
                return;
            }
        }
References System.Net.IPEndPoint._port, System.Uri.Authority, System.Net.HttpListenerContext.cnc, System.Net.HttpListenerRequest.context, System.Net.HttpListenerRequest.CreateQueryString(), System.Net.HttpListenerRequestUriBuilder.GetRequestUri(), System.Net.HttpListenerRequest.headers, j__TPar, System.L, System.Net.HttpConnection.LocalEndPoint, System.Uri.LocalPath, System.Net.HttpListenerRequest.MaybeUri(), System.Uri.Query, System.Net.HttpListenerRequest.raw_url, System.Uri.Scheme, System.Net.HttpConnection.secure, System.text, System.Net.HttpListenerRequest.url, System.Net.HttpListenerRequest.UserHostName, and System.Net.HttpListenerRequest.version.