terraria-cpp2il-methodrecon: UnityEngine.UI.Scrollbar.UpdateVisuals
UpdateVisuals()
void UnityEngine.UI.Scrollbar.UpdateVisuals () inline private
Definition at line 316 of file Scrollbar.cs.
        {
            int num = 1;
            RectTransform containerRect = this.m_ContainerRect;
            if (num == 0)
            {
            }
            RectTransform handleRect = this.m_HandleRect;
            float value = this.value;
            float size = this.m_Size;
            Scrollbar.Direction direction = this.m_Direction;
            RectTransform handleRect2 = this.m_HandleRect;
            RectTransform handleRect3 = this.m_HandleRect;
        }
References UnityEngine.UI.Scrollbar.direction, UnityEngine.UI.Scrollbar.handleRect, j__TPar, UnityEngine.UI.Scrollbar.m_ContainerRect, UnityEngine.UI.Scrollbar.m_Direction, UnityEngine.UI.Scrollbar.m_HandleRect, UnityEngine.UI.Scrollbar.m_Size, UnityEngine.UI.Scrollbar.size, and UnityEngine.UI.Scrollbar.value.
Referenced by UnityEngine.UI.Scrollbar.OnEnable(), UnityEngine.UI.Scrollbar.OnRectTransformDimensionsChange(), UnityEngine.UI.Scrollbar.Set(), and UnityEngine.UI.Scrollbar.Update().