terraria-cpp2il-methodrecon: UnityEngine.UI.Scrollbar.Set
Set()
void UnityEngine.UI.Scrollbar.Set (float input, bool sendCallback = true) inline private
Definition at line 242 of file Scrollbar.cs.
        {
            float value = this.m_Value;
            float value2 = this.value;
            this.UpdateVisuals();
            UISystemProfilerApi.AddMarker("Scrollbar.value", this);
            Scrollbar.ScrollEvent onValueChanged = this.m_OnValueChanged;
            float value3 = this.value;
        }
References UnityEngine.UISystemProfilerApi.AddMarker(), j__TPar, UnityEngine.UI.Scrollbar.m_OnValueChanged, UnityEngine.UI.Scrollbar.m_Value, UnityEngine.UI.Scrollbar.onValueChanged, UnityEngine.UI.Scrollbar.UpdateVisuals(), and UnityEngine.UI.Scrollbar.value.
Referenced by UnityEngine.UI.Scrollbar.SetValueWithoutNotify().