terraria-cpp2il-methodrecon: System.IO.PathInternal.GetIsCaseSensitive
GetIsCaseSensitive()
static bool System.IO.PathInternal.GetIsCaseSensitive () inline static private
Definition at line 108 of file PathInternal.cs.
        {
            if (!true)
            {
            }
            string tempPath = Path.GetTempPath();
            string text = Guid.NewGuid().ToString("N");
            string text2 = "CASESENSITIVETEST" + "N";
            bool flag = File.Exists(Path.Combine(tempPath, text2).ToLowerInvariant());
            long num = 0L;
            int num2 = 2;
            if (num != 0L || num2 == 0)
            {
            }
            throw new OutOfMemoryException();
        }
References System.IO.Path.Combine(), System.IO.File.Exists(), System.IO.Path.GetTempPath(), j__TPar, System.L, System.Guid.NewGuid(), System.text, and System.Guid.ToString().
Referenced by System.IO.PathInternal.PathInternal().