terraria-cpp2il-methodrecon: GUIKeyboardMappingEntry.Draw
Draw()
void GUIKeyboardMappingEntry.Draw () inline
Definition at line 137 of file GUIKeyboardMappingEntry.cs.
    {
        bool flag = this.displayOptions;
        if (flag && !this.drawingOverlay)
        {
            Rectangle gridItemRegion = ControlAnchor._gridItemRegion;
            return;
        }
        if (this._optionsBlocker != null)
        {
        }
        bool flag2;
        if (flag)
        {
            flag2 = this.displayOptions;
        }
        GUITransactionButton.InputState inputState;
        if (inputState != GUITransactionButton.InputState.Clicked || !flag2)
        {
        }
        string <Value>k__BackingField = Language.GetText(this.localisationId).<Value>k__BackingField;
        if (this.displayOptions)
        {
            int num = 1;
            GUITransactionButton.InputState inputState2;
            if (inputState2 == GUITransactionButton.InputState.Clicked)
            {
                if (num == 0)
                {
                }
                GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
            }
            GUITransactionButton.InputState inputState3;
            if (inputState3 == GUITransactionButton.InputState.Clicked)
            {
                Main.mouseLeftRelease = false;
                this.RemoveBinding();
            }
            bool flag3 = this.displayOptions;
            if (flag3)
            {
                if (!flag3)
                {
                }
                if (!false)
                {
                }
                GUIInputRegionExclusive optionsBlocker2 = this._optionsBlocker;
                return;
            }
        }
        if (this.Binding != KeyCode.None)
        {
            string text = this.Binding.ToString();
            string textValue = Language.GetTextValue("KeyboardBindings." + text);
            return;
        }
        LocalizedText text2 = Language.GetText("Mobile.UnboundControl");
        string <Value>k__BackingField2 = text2.<Value>k__BackingField;
        if (text2 == null)
        {
        }
        bool mouseLeftRelease = Main.mouseLeftRelease;
        if (text2 == null)
        {
        }
        bool mouseLeft = Main.mouseLeft;
        if (text2 == null)
        {
        }
        GUIInputRegionExclusive optionsBlocker3 = this._optionsBlocker;
        if (optionsBlocker3 != null)
        {
            int num2 = 1;
            optionsBlocker3.Active = num2 != 0;
            GUIInputRegionExclusive optionsBlocker4 = this._optionsBlocker;
        }
    }
References ControlAnchor._gridItemRegion, _optionsBlocker, Binding, displayOptions, drawingOverlay, Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), j__TPar, localisationId, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, RemoveBinding(), and System.text.
Referenced by DrawOverlay().