terraria-cpp2il-methodrecon: System.Xml.XmlUtf8RawTextWriter.RawText
RawText() [2/2]
void System.Xml.XmlUtf8RawTextWriter.RawText (string s) inline protected
Definition at line 476 of file XmlUtf8RawTextWriter.cs.
        {
            if (s != null)
            {
                int offsetToStringData = RuntimeHelpers.OffsetToStringData;
                return;
            }
        }
References j__TPar, and System.Runtime.CompilerServices.RuntimeHelpers.OffsetToStringData.
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteCharEntity(), System.Xml.XmlUtf8RawTextWriter.WriteDocType(), System.Xml.XmlUtf8RawTextWriter.WriteEntityRef(), System.Xml.XmlUtf8RawTextWriter.WriteFullEndElement(), System.Xml.XmlUtf8RawTextWriter.WriteProcessingInstruction(), System.Xml.XmlUtf8RawTextWriter.WriteStartAttribute(), System.Xml.XmlUtf8RawTextWriter.WriteStartElement(), System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclaration(), System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntity(), and System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclaration().