terraria-cpp2il-methodrecon: VirtualControlsHardwareConfiguration_Layout.Copy
Copy()
void VirtualControlsHardwareConfiguration_Layout.Copy (VirtualControlsHardwareConfiguration_Layout other) inline
Definition at line 10 of file VirtualControlsHardwareConfiguration_Layout.cs.
    {
        string editedName = other.EditedName;
        this.EditedName = editedName;
        GUIPageIcons.PageControlsType pageControls = other.PageControls;
        this.PageControls = pageControls;
        Vector2 leftPagePosition = other.LeftPagePosition;
        this.LeftPagePosition = leftPagePosition;
        Vector2 leftControlsPosition = other.LeftControlsPosition;
        this.LeftControlsPosition = leftControlsPosition;
        Vector2 rightPagePosition = other.RightPagePosition;
        this.RightPagePosition = rightPagePosition;
        Vector2 rightControlsPosition = other.RightControlsPosition;
        this.RightControlsPosition = rightControlsPosition;
        Vector2 settingsPosition = other.SettingsPosition;
        this.SettingsPosition = settingsPosition;
        Vector2 menuPosition = other.MenuPosition;
        this.MenuPosition = menuPosition;
        VirtualControlsSlotTypeMapping_Layout style = other.Slots.Style;
        VirtualControlsHardwareConfigurationMapping_Layout[] slots = this.Slots;
        VirtualControlsHardwareConfigurationMapping_Layout[] slots2 = other.Slots;
        VirtualControlsHardwareConfigurationMapping_Layout[] slots3 = this.Slots;
    }
References j__TPar, and Slots.
Referenced by GUIInterfaceEdit.Backup(), GUIInterfaceEdit.RestoreBackup(), and GUIInterfaceEdit.RestoreDefaults().