terraria-cpp2il-methodrecon: VirtualControlsHardwareConfiguration_Layout.LoadControlPositions
LoadControlPositions()
void VirtualControlsHardwareConfiguration_Layout.LoadControlPositions () inline
Definition at line 66 of file VirtualControlsHardwareConfiguration_Layout.cs.
    {
        GUIPageIcons.PageControlsType pageControls = this.PageControls;
    }
References j__TPar, and PageControls.
Referenced by GUIInterfaceEdit.RestoreBackup(), GUIInterfaceEdit.RestoreDefaults(), and VirtualControlsStyles_Layout.SetActiveProfile().