terraria-cpp2il-methodrecon: UnityEngine.UI.MaskableGraphic.OnDisable
OnDisable()
override void UnityEngine.UI.MaskableGraphic.OnDisable () inline protected virtual inherited
Reimplemented from UnityEngine.UI.Graphic.
Reimplemented in UnityEngine.UI.Text.
Definition at line 117 of file MaskableGraphic.cs.
        {
            base.OnDisable();
            this.UpdateClipParent();
            StencilMaterial.Remove(this.m_MaskMaterial);
            if (this.m_IsMaskingGraphic)
            {
                MaskUtilities.NotifyStencilStateChanged(this);
                return;
            }
        }
References j__TPar, UnityEngine.UI.MaskableGraphic.m_IsMaskingGraphic, UnityEngine.UI.MaskableGraphic.m_MaskMaterial, UnityEngine.UI.MaskUtilities.NotifyStencilStateChanged(), UnityEngine.UI.StencilMaterial.Remove(), and UnityEngine.UI.MaskableGraphic.UpdateClipParent().