terraria-cpp2il-methodrecon: UnityEngine.UI.MaskableGraphic.GetModifiedMaterial
GetModifiedMaterial()
virtual Material UnityEngine.UI.MaskableGraphic.GetModifiedMaterial (Material baseMaterial) inline virtual inherited
Implements UnityEngine.UI.IMaterialModifier.
Definition at line 56 of file MaskableGraphic.cs.
        {
            if (this.m_ShouldRecalculateStencil && this.m_Maskable)
            {
                Transform transform = MaskUtilities.FindRootSortOverrideCanvas(base.transform);
                int stencilDepth = MaskUtilities.GetStencilDepth(base.transform, transform);
            }
            long num = 0L;
            this.m_StencilValue = (int)num;
            Material maskMaterial;
            if (!this.m_IsMaskingGraphic)
            {
                maskMaterial = this.m_MaskMaterial;
                StencilMaterial.Remove(maskMaterial);
                Material material;
                this.m_MaskMaterial = material;
            }
            return maskMaterial;
        }
References UnityEngine.UI.MaskUtilities.FindRootSortOverrideCanvas(), UnityEngine.UI.MaskUtilities.GetStencilDepth(), j__TPar, UnityEngine.L, UnityEngine.UI.MaskableGraphic.m_IsMaskingGraphic, UnityEngine.UI.MaskableGraphic.m_Maskable, UnityEngine.UI.MaskableGraphic.m_MaskMaterial, UnityEngine.UI.MaskableGraphic.m_ShouldRecalculateStencil, UnityEngine.UI.Graphic.material, UnityEngine.UI.StencilMaterial.Remove(), and UnityEngine.UI.ICanvasElement.transform.