terraria-cpp2il-methodrecon: Terraria.UI.UserInterface.RefreshState
RefreshState()
void Terraria.UI.UserInterface.RefreshState () inline package
Definition at line 314 of file UserInterface.cs.
        {
            UIState currentState = this._currentState;
            if (currentState != null)
            {
                currentState.Deactivate();
            }
            this.ResetState();
            this._currentState.Activate();
            UIState currentState2 = this._currentState;
        }
References Terraria.UI.UserInterface._currentState, Terraria.UI.UIElement.Activate(), Terraria.UI.UIElement.Deactivate(), j__TPar, and Terraria.UI.UserInterface.ResetState().