terraria-cpp2il-methodrecon: System.Security.Cryptography.AsymmetricAlgorithm.Clear
Clear()
void System.Security.Cryptography.AsymmetricAlgorithm.Clear () inline inherited
Definition at line 23 of file AsymmetricAlgorithm.cs.
        {
            GC.SuppressFinalize(this);
        }
References System.GC.SuppressFinalize().
Referenced by System.Security.Cryptography.AsymmetricAlgorithm.Dispose(), System.Security.Cryptography.DSACryptoServiceProvider.Dispose(), and System.Security.Cryptography.RSACryptoServiceProvider.Dispose().