terraria-cpp2il-methodrecon: InControl.OneAxisInputControl.PrepareForUpdate
PrepareForUpdate()
void InControl.OneAxisInputControl.PrepareForUpdate (ulong updateTick) inline private inherited
Definition at line 28 of file OneAxisInputControl.cs.
        {
            while (!this.isNullControl)
            {
                ulong num = this.pendingTick;
                if (!this.pendingCommit)
                {
                    float rawValue = this.thisState.RawValue;
                    this.pendingTick = updateTick;
                    this.lastState.RawValue = rawValue;
                    this.pendingCommit = true;
                    break;
                }
            }
        }
References InControl.OneAxisInputControl.isNullControl, j__TPar, InControl.OneAxisInputControl.pendingCommit, InControl.OneAxisInputControl.pendingTick, InControl.InputControlState.RawValue, and InControl.OneAxisInputControl.thisState.
Referenced by InControl.OneAxisInputControl.CommitWithState(), InControl.OneAxisInputControl.UpdateWithRawValue(), InControl.InputDevice.UpdateWithState(), and InControl.OneAxisInputControl.UpdateWithValue().