terraria-cpp2il-methodrecon: GUIVirtualInputController.IsOverGroupRegion
IsOverGroupRegion()
bool GUIVirtualInputController.IsOverGroupRegion (GUIPageIconGrouping group, Point mousePoint) inline private
Definition at line 581 of file GUIVirtualInputController.cs.
    {
        GUIPageIcons.Category selectedCategory = group.SelectedCategory;
        group.LoadPageAnchor();
        float x = group.pageButtonRegionSize.X;
        float y = group.pageButtonRegionSize.Y;
        int size = group._options._size;
        int size2 = group.SettingEntries._size;
        RightSideHUDAnchorUpdator.Update();
        bool flag = group.GetRegion().Contains(mousePoint);
        group.LoadPageAnchor();
        float x2 = group.pageButtonRegionSize.X;
        float y2 = group.pageButtonRegionSize.Y;
        int size3 = group._options._size;
        int size4 = group.SettingEntries._size;
        group.LoadPageAnchor();
        GUIPageIcons.Category selectedCategory2 = group.SelectedCategory;
        !0 instance = PageControllerLayoutDefinition.Instance;
        Rectangle rectangle;
        bool flag2 = rectangle.Contains(mousePoint);
        !0 instance2 = PageControllerLayoutDefinition.Instance;
        Rectangle rectangle2;
        bool flag3 = rectangle2.Contains(mousePoint);
        !0 instance3 = PageControllerLayoutDefinition.Instance;
        Rectangle rectangle3;
        bool flag4 = rectangle3.Contains(mousePoint);
        !0 instance4 = PageControllerLayoutDefinition.Instance;
        Rectangle rectangle4;
        bool flag5 = rectangle4.Contains(mousePoint);
        int gameMode = Main.GameMode;
        InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
        InterfaceProfile_Layout active2 = InterfaceStyles_Layout.Active;
        GUIPageIconGrouping guipageIconGrouping;
        if (guipageIconGrouping != null)
        {
            GUIPageIconGrouping guipageIconGrouping2;
            while (guipageIconGrouping2 != null)
            {
            }
        }
        if (group.SelectedCategory == GUIPageIcons.Category.Crafting)
        {
            bool flag6;
            return flag6;
        }
        GUIPageIcons.Category category;
        return category.Collapsed;
    }
References GUIPageIconGrouping._options, System.Collections.Generic.List< T >._size, InterfaceStyles_Layout.Active, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Main.GameMode, GUIPageIconGrouping.GetRegion(), PageControllerLayoutDefinition< T >.Instance, j__TPar, GUIPageIconGrouping.LoadPageAnchor(), GUIPageIconGrouping.pageButtonRegionSize, GUIPageIconGrouping.SelectedCategory, GUIPageIconGrouping.SettingEntries, RightSideHUDAnchorUpdator.Update(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.