terraria-cpp2il-methodrecon: UnityEngine.UI.Slider.UpdateVisuals
UpdateVisuals()
void UnityEngine.UI.Slider.UpdateVisuals () inline private
Definition at line 460 of file Slider.cs.
        {
            int num = 1;
            RectTransform fillContainerRect = this.m_FillContainerRect;
            if (num == 0)
            {
            }
            RectTransform fillRect = this.m_FillRect;
            Image fillImage = this.m_FillImage;
            Image fillImage2 = this.m_FillImage;
            Image.Type type = fillImage2.m_Type;
            float normalizedValue = this.normalizedValue;
            fillImage2.fillAmount = normalizedValue;
        }
References UnityEngine.UI.Slider.fillRect, j__TPar, UnityEngine.UI.Slider.m_FillContainerRect, UnityEngine.UI.Slider.m_FillImage, UnityEngine.UI.Slider.m_FillRect, UnityEngine.UI.Image.m_Type, and UnityEngine.UI.Slider.normalizedValue.
Referenced by UnityEngine.UI.Slider.OnEnable(), UnityEngine.UI.Slider.OnRectTransformDimensionsChange(), UnityEngine.UI.Slider.Set(), and UnityEngine.UI.Slider.Update().