terraria-cpp2il-methodrecon: System.Security.Cryptography.DESTransform.DESTransform
DESTransform() [1/2]
System.Security.Cryptography.DESTransform.DESTransform (SymmetricAlgorithm symmAlgo, bool encryption, byte[] key, byte[] iv) inline package
Definition at line 10 of file DESTransform.cs.
        {
            int num = 1;
            base..ctor(symmAlgo, encryption, iv);
            byte[] strongKey;
            if (key == null)
            {
                if (num == 0)
                {
                }
                strongKey = DESTransform.GetStrongKey();
            }
            bool flag = DES.IsWeakKey(strongKey);
            if (num == 0)
            {
            }
            bool flag2 = DES.IsSemiWeakKey(strongKey);
            object obj;
            if (strongKey == null && obj != null && obj == null)
            {
                throw new InvalidCastException();
            }
            if (num == 0)
            {
            }
        }
References System.Security.Cryptography.DESTransform.GetStrongKey(), System.Security.Cryptography.DES.IsSemiWeakKey(), System.Security.Cryptography.DES.IsWeakKey(), j__TPar, System.key, and System.obj.