terraria-cpp2il-methodrecon: Telepathy.Server.Stop
Stop()
void Telepathy.Server.Stop () inline
Definition at line 96 of file Server.cs.
        {
            Thread thread = this.listenerThread;
            if (thread != null)
            {
                bool isAlive = thread.IsAlive;
                if (!true)
                {
                }
                TcpListener tcpListener = this.listener;
                if (tcpListener != null)
                {
                    tcpListener.Stop();
                }
                Thread thread2 = this.listenerThread;
                if (thread2 != null)
                {
                    thread2.Interrupt();
                }
                if (!true)
                {
                }
                Thread.Sleep(10);
                TcpListener tcpListener2 = this.listener;
                if (tcpListener2 != null)
                {
                    tcpListener2.Stop();
                }
            }
            this.Cleanup();
        }
References Telepathy.Server.Cleanup(), System.Threading.Thread.Interrupt(), System.Threading.Thread.IsAlive, j__TPar, Telepathy.Server.listener, Telepathy.Server.listenerThread, System.Threading.Thread.Sleep(), and System.Net.Sockets.TcpListener.Stop().
Referenced by SaveSynchronisationHost.Close(), and SaveSynchronisationManager.Shutdown().