terraria-cpp2il-methodrecon: Terraria.GameContent.Animations.Segments.PlayerSegment.Draw
Draw()
override void Terraria.GameContent.Animations.Segments.PlayerSegment.Draw (GameAnimationSegment info) inline
Definition at line 200 of file Segments.cs.
            {
                int timeInAnimation = info.TimeInAnimation;
                float dedicatedTimeNeeded = base.DedicatedTimeNeeded;
                int timeInAnimation2 = info.TimeInAnimation;
                this.ResetPlayerAnimation(info);
                int timeInAnimation3 = info.TimeInAnimation;
                Player player = this._player;
                float displayOpacity = info.DisplayOpacity;
                this._player.ResetEffects();
                this._player.ResetVisibleAccessories();
                this._player.UpdateMiscCounter();
                this._player.UpdateDyes();
                this._player.PlayerFrame();
                Player player2 = this._player;
                int num = 1;
                player2.socialIgnoreLight = num != 0;
                float x = player2.position.X;
                float y = player2.position.Y;
                if (num == 0)
                {
                }
                Vector2 screenPosition = Main.screenPosition;
                if (num == 0)
                {
                }
                player2.position.X = displayOpacity;
                Player player3 = this._player;
                int width = player3.width;
                int height = player3.height;
                float x2 = player3.position.X;
                float y2 = player3.position.Y;
                player3.position.X = displayOpacity;
                player3.position.Y = (float)height;
                Player player4 = this._player;
                float displayOpacity2 = info.DisplayOpacity;
                float opacityForAnimation = player4.opacityForAnimation;
                Item[] inventory = player4.inventory;
                player4.opacityForAnimation = displayOpacity2;
                Vector2 position = player2.position;
                if (player4 == null)
                {
                }
                if (this._shaderEffect != null)
                {
                    return;
                }
                Camera camera = Main.Camera;
                Player player5 = this._player;
                float x3 = player5.position.X;
                float y3 = player5.position.Y;
                float x4 = player5.fullRotationOrigin.X;
                float y4 = player5.fullRotationOrigin.Y;
            }
References Terraria.GameContent.Animations.Segments.PlayerSegment._player, Terraria.GameContent.Animations.Segments.PlayerSegment._shaderEffect, Terraria.Main.Camera, Terraria.GameContent.Animations.GameAnimationSegment.DisplayOpacity, System.info, j__TPar, Terraria.Player.PlayerFrame(), Terraria.Entity.position, Terraria.Player.ResetEffects(), Terraria.GameContent.Animations.Segments.PlayerSegment.ResetPlayerAnimation(), Terraria.Player.ResetVisibleAccessories(), Terraria.Main.screenPosition, Terraria.Player.UpdateDyes(), Terraria.Player.UpdateMiscCounter(), Terraria.Entity.width, and Microsoft.Xna.Framework.Vector2.X.