terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Content.ContentManager.Load< T1 >
Load< T1 >()
T1 Microsoft.Xna.Framework.Content.ContentManager.Load< T1 > (string A_1) inline package
Type Constraints
T1 : class
Definition at line 38 of file ContentManager.cs.
                                                  : class
        {
            SpriteEffect effect4;
            do
            {
                string text = Path.Combine("Content", A_1).Replace("\\", "/");
                Type type;
                Type type2;
                bool flag = type == type2;
                object obj = Convert.ChangeType(this.LoadTexture2D(text), type);
                Type type3;
                bool flag2 = type == type3;
                bool flag3 = text == "Content/TileShader";
                TileShader effect = TileShader.Effect;
                Type type4;
                bool flag4 = type == type4;
                PixelShader effect2 = PixelShader.Effect;
                Type type5;
                bool flag5 = type == type5;
                bool flag6 = text == "Content/ScreenShader";
                ScreenShader effect3 = ScreenShader.Effect;
                effect4 = SpriteEffect.Effect;
                if (effect4 == null)
                {
                    return;
                }
            }
            while (effect4 != null);
            throw new InvalidCastException();
        }
References System.Convert.ChangeType(), System.IO.Path.Combine(), Microsoft.Xna.Framework.Graphics.PixelShader.Effect, Microsoft.Xna.Framework.Graphics.ScreenShader.Effect, Microsoft.Xna.Framework.Graphics.SpriteEffect.Effect, Microsoft.Xna.Framework.Graphics.TileShader.Effect, j__TPar, Microsoft.Xna.Framework.Content.ContentManager.LoadTexture2D(), System.obj, and System.text.