terraria-cpp2il-methodrecon: Mono.Security.Cryptography.KeyPairPersistence.Save
Save()
void Mono.Security.Cryptography.KeyPairPersistence.Save () inline
Definition at line 102 of file KeyPairPersistence.cs.
        {
            string filename = this.Filename;
            Encoding utf = Encoding.UTF8;
            string text = this.ToXml();
            long num = 0L;
            FileStream fileStream;
            if (fileStream != null)
            {
                return;
            }
            if (num == 0L)
            {
                int flags = this._params.m_flags;
                string filename2 = this.Filename;
                bool flag = KeyPairPersistence.ProtectUser(filename2);
                return;
            }
            throw new OutOfMemoryException();
        }
References Mono.Security.Cryptography.KeyPairPersistence._params, Mono.Security.Cryptography.KeyPairPersistence.Filename, j__TPar, System.L, System.Security.Cryptography.CspParameters.m_flags, Mono.Security.Cryptography.KeyPairPersistence.ProtectUser(), System.text, Mono.Security.Cryptography.KeyPairPersistence.ToXml(), and System.Text.Encoding.UTF8.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.OnKeyGenerated(), and System.Security.Cryptography.RSACryptoServiceProvider.OnKeyGenerated().