terraria-cpp2il-methodrecon: Terraria.GameContent.ShopHelper.AddHappinessReportText
AddHappinessReportText()
void Terraria.GameContent.ShopHelper.AddHappinessReportText (string textKeyInCategory, [Optional] object substitutes) inline private
Definition at line 151 of file ShopHelper.cs.
        {
            if (!true)
            {
            }
            string text;
            string textValueWith = Language.GetTextValueWith("TownNPCMood_" + text + "Transformed" + "." + textKeyInCategory, substitutes);
            string text2 = textValueWith + textValueWith + " ";
        }
References Terraria.Localization.Language.GetTextValueWith(), j__TPar, and System.text.
Referenced by Terraria.GameContent.ShopHelper.IsFarFromHome(), and Terraria.GameContent.ShopHelper.RuinMoodIfHomeless().