terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop
MasterModeCommonDrop()
static IItemDropRule Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop (int itemId) inline static
Definition at line 89 of file ItemDropRule.cs.
        {
            IItemDropRule itemDropRule;
            return itemDropRule;
        }
References j__TPar.
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_AncientCultist(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Betsy(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_BOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Deerclops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_DukeFishron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOW(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_FrostMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_MoonLord(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_PumpkinMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenBee(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_SkeletronPrime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_TheDestroyer(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Twins(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_WOF(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterDD2EventDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMartianDrops(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPirateDrops().