terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag
BossBag()
static IItemDropRule Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag (int itemId) inline static
Definition at line 16 of file ItemDropRule.cs.
        {
            /*
An exception occurred when decompiling this method (060043C1)
ICSharpCode.Decompiler.DecompilerException: Error decompiling Terraria.GameContent.ItemDropRules.IItemDropRule Terraria.GameContent.ItemDropRules.ItemDropRule::BossBag(System.Int32)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:IItemDropRule(var_0_05, call:IItemDropRule(ItemDropRule::DropNothing))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Betsy(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_BOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Deerclops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_DukeFishron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_MoonLord(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenBee(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_SkeletronPrime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_TheDestroyer(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Twins(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_WOF().