terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropRule.Common
Common()
static IItemDropRule Terraria.GameContent.ItemDropRules.ItemDropRule.Common (int itemId, int chanceDenominator = 1, int minimumDropped = 1, int maximumDropped = 1) inline static
Definition at line 10 of file ItemDropRule.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBloodMoonFishing(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_AncientCultist(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOW(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_FrostMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_PumpkinMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Twins(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossTrophies(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterDD2EventDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterEclipse(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterGlobalRules(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeDungeonDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeFeathers(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMartianDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMimic(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMiscDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPirateDrops(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterTownNPCDrops().