terraria-cpp2il-methodrecon: Terraria.UI.Chat.ChatManager.DrawColorCodedString
DrawColorCodedString() [2/5]
static Vector2 Terraria.UI.Chat.ChatManager.DrawColorCodedString (SpriteBatch spriteBatch, SpriteFont font, StringBuilder text, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, float maxWidth = -1f, bool ignoreColors = false) inline static
Definition at line 292 of file ChatManager.cs.
        {
            Vector2 vector = font.MeasureString(" ");
            int length = text.Length;
            long num = 0L;
            long num2 = 0L;
            char c = text[(int)num2];
            char c2 = text[(int)num2];
            int <LineSpacing>k__BackingField = font.<LineSpacing>k__BackingField;
            if (num2 == 0L)
            {
            }
            float num3 = Math.Max(maxWidth, maxWidth);
            if (num2 == 0L)
            {
            }
            Vector2 vector2 = font.MeasureString(text, (int)num, (int)num);
            if (num2 == 0L)
            {
            }
            float num4 = Math.Max(rotation, rotation);
            char c3 = text[(int)num2];
            int <LineSpacing>k__BackingField2 = font.<LineSpacing>k__BackingField;
            if (num2 == 0L)
            {
            }
            float num5 = Math.Max(num3, maxWidth);
            Vector2 vector3 = font.MeasureString(text, (int)num2, (int)num);
            int <LineSpacing>k__BackingField3 = font.<LineSpacing>k__BackingField;
            if (num2 == 0L)
            {
            }
            float num6 = Math.Max(num5, maxWidth);
            if (num2 == 0L)
            {
            }
            Vector2 vector4 = font.MeasureString(text, (int)num2, (int)num2);
            if (num2 == 0L)
            {
            }
            float num7 = Math.Max(num4, rotation);
            if (num2 == 0L)
            {
                return;
            }
        }
References j__TPar, System.L, Microsoft.Xna.Framework.Vector2.Length(), System.length, System.Math.Max(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), and System.text.