terraria-cpp2il-methodrecon: ReLogic.Threading.AsyncActionDispatcher.Dispose
Dispose() [2/2]
virtual void ReLogic.Threading.AsyncActionDispatcher.Dispose (bool disposing) inline protected virtual
Definition at line 88 of file AsyncActionDispatcher.cs.
        {
            if (!this.<IsDisposed>k__BackingField)
            {
                if (this._isRunning)
                {
                    this.Stop();
                }
                this._actionQueue.Dispose();
                this._threadCancellation.Dispose();
                this.<IsDisposed>k__BackingField = true;
            }
        }
References ReLogic.Threading.AsyncActionDispatcher._actionQueue, ReLogic.Threading.AsyncActionDispatcher._isRunning, ReLogic.Threading.AsyncActionDispatcher._threadCancellation, System.Threading.CancellationTokenSource.Dispose(), System.Collections.Concurrent.BlockingCollection< T >.Dispose(), ReLogic.Threading.AsyncActionDispatcher.IsDisposed, ReLogic.Threading.AsyncActionDispatcher.k__BackingField, and ReLogic.Threading.AsyncActionDispatcher.Stop().