terraria-cpp2il-methodrecon: UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingLayout
IsRebuildingLayout()
static bool UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingLayout () inline static
Definition at line 214 of file CanvasUpdateRegistry.cs.
        {
            if (!true)
            {
            }
            return CanvasUpdateRegistry.instance.m_PerformingLayoutUpdate;
        }
References UnityEngine.UI.CanvasUpdateRegistry.instance, and UnityEngine.UI.CanvasUpdateRegistry.m_PerformingLayoutUpdate.
Referenced by UnityEngine.UI.ScrollRect.EnsureLayoutHasRebuilt(), UnityEngine.UI.Text.FontTextureChanged(), UnityEngine.UI.Graphic.OnRectTransformDimensionsChange(), and UnityEngine.UI.LayoutGroup.SetDirty().