terraria-cpp2il-methodrecon: System.Runtime.Serialization.ObjectIDGenerator.GetId
GetId()
virtual long System.Runtime.Serialization.ObjectIDGenerator.GetId (object obj, [Out] bool firstTime) inline virtual
Definition at line 33 of file ObjectIDGenerator.cs.
        {
            if (obj != null)
            {
                int num = this.FindElement(obj, firstTime);
                long[] ids = this.m_ids;
                object[] objs = this.m_objs;
                if (obj == null)
                {
                    goto IL_0046;
                }
                long[] ids2 = this.m_ids;
                int currentSize = this.m_currentSize;
                this.Rehash();
                firstTime.m_value = currentSize != 0;
            }
            string resourceString = Environment.GetResourceString("Object cannot be null.");
            IL_0046:
            throw new ArrayTypeMismatchException();
        }
References System.Runtime.Serialization.ObjectIDGenerator.FindElement(), System.Environment.GetResourceString(), j__TPar, System.Runtime.Serialization.ObjectIDGenerator.m_currentSize, System.Runtime.Serialization.ObjectIDGenerator.m_ids, System.Runtime.Serialization.ObjectIDGenerator.m_objs, System.obj, and System.Runtime.Serialization.ObjectIDGenerator.Rehash().