terraria-cpp2il-methodrecon: UnityEngine.RenderTexture.ValidateRenderTextureDesc
ValidateRenderTextureDesc()
static void UnityEngine.RenderTexture.ValidateRenderTextureDesc (RenderTextureDescriptor desc) inline static private
Definition at line 259 of file RenderTexture.cs.
        {
            if (desc._graphicsFormat != GraphicsFormat.None)
            {
                throw new MissingMethodException();
            }
            GraphicsFormat <depthStencilFormat>k__BackingField = desc.<depthStencilFormat>k__BackingField;
            if (<depthStencilFormat>k__BackingField != GraphicsFormat.None)
            {
                bool flag = GraphicsFormatUtility.IsDepthFormat(<depthStencilFormat>k__BackingField);
                bool flag2 = GraphicsFormatUtility.IsStencilFormat(desc.<depthStencilFormat>k__BackingField);
                int <height>k__BackingField = desc.<height>k__BackingField;
                int <volumeDepth>k__BackingField = desc.<volumeDepth>k__BackingField;
                int <msaaSamples>k__BackingField = desc.<msaaSamples>k__BackingField;
                TextureDimension <dimension>k__BackingField = desc.<dimension>k__BackingField;
                GraphicsFormat graphicsFormat = desc._graphicsFormat;
                if (<dimension>k__BackingField == TextureDimension.None)
                {
                }
                bool flag3 = GraphicsFormatUtility.IsDepthFormat(graphicsFormat);
                GraphicsFormat graphicsFormat2 = desc._graphicsFormat;
                if (<dimension>k__BackingField == TextureDimension.None)
                {
                }
                bool flag4 = GraphicsFormatUtility.IsStencilFormat(graphicsFormat2);
                return;
            }
        }
References UnityEngine.RenderTexture.depthStencilFormat, UnityEngine.RenderTexture.graphicsFormat, UnityEngine.RenderTexture.height, UnityEngine.Experimental.Rendering.GraphicsFormatUtility.IsDepthFormat(), UnityEngine.Experimental.Rendering.GraphicsFormatUtility.IsStencilFormat(), and j__TPar.
Referenced by UnityEngine.RenderTexture.RenderTexture().