terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.PackedVector.HalfTypeHelper.Convert
Convert() [1/3]
static ushort Microsoft.Xna.Framework.Graphics.PackedVector.HalfTypeHelper.Convert (float f) inline static package
Definition at line 11 of file HalfTypeHelper.cs.
        {
            ushort num;
            return num;
        }
Referenced by Microsoft.Xna.Framework.Graphics.PackedVector.HalfVector2.HalfVector2(), Microsoft.Xna.Framework.Graphics.PackedVector.HalfVector2.HalfVector2(), and Microsoft.Xna.Framework.Graphics.PackedVector.HalfVector2.PackFromVector4().