terraria-cpp2il-methodrecon: GUIBestiary.NPCOver
NPCOver()
void GUIBestiary.NPCOver (int index) inline private
Definition at line 48 of file GUIBestiary.cs.
    {
        this.EntryOver = index;
        if (!true)
        {
        }
        bool mouseLeft = Main.mouseLeft;
        if (!true)
        {
        }
        bool mouseLeftRelease = Main.mouseLeftRelease;
        if (this.editingSearch)
        {
            this.CloseSearchInput();
        }
        List<BestiaryEntry> sortedEntries = this.SortedEntries;
        this.SelectedEntry = sortedEntries;
        this.RefreshSelectedStats();
        this._controllerInput.SelectNPCEntry(index);
    }
References _controllerInput, CloseSearchInput(), editingSearch, System.index, j__TPar, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, RefreshSelectedStats(), GUIControllerBestiary.SelectNPCEntry(), and SortedEntries.