terraria-cpp2il-methodrecon: GUIBestiary.DrawFilters
DrawFilters()
void GUIBestiary.DrawFilters () inline private
Definition at line 358 of file GUIBestiary.cs.
    {
        bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
        int activeFilterCount = this.ActiveFilterCount;
        if (!this.drawLootDrops && !this.displayOrders)
        {
            bool anyControllerConnected2 = ControllerActionManager.AnyControllerConnected;
            return;
        }
        bool anyControllerConnected3 = ControllerActionManager.AnyControllerConnected;
        bool flag = this.displayFilters;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            bool flag2 = this.displayFilters;
            bool flag3 = this.displayOrders;
            this.displayFilters = flag2;
            if (flag3)
            {
                this.CloseSortOrder();
            }
            if (this.drawLootDrops)
            {
                this.CloseLootDrops();
            }
        }
        if (this.displayFilters)
        {
            if (this._filterBlocker == null)
            {
                GUIInputRegionExclusive guiinputRegionExclusive;
                this._filterBlocker = guiinputRegionExclusive;
                if (guiinputRegionExclusive != null)
                {
                }
            }
            int num = 1;
            bool anyControllerConnected4 = ControllerActionManager.AnyControllerConnected;
            this._controllerInput.ActivateFilters();
            List<bool> list = this.filterEnabled;
            GUIItemGrid.CursorOver cursorOver = this.filterItemOver;
            GUIItemGrid.GetItemScaleHandler getItemScaleHandler = this.filterScale;
            GUIItemGrid.DrawItemHandler drawItemHandler = this.filterDraw;
            int size = list._size;
            if (num == 0)
            {
            }
            this.DrawFilterSearch();
            GUIInputRegionExclusive filterBlocker = this._filterBlocker;
            if (filterBlocker != null)
            {
                int num2 = 1;
                filterBlocker.Active = num2 != 0;
            }
            return;
        }
        this.CloseFilters();
    }
References _controllerInput, _filterBlocker, GUIControllerBestiary.ActivateFilters(), ActiveFilterCount, Controller.ControllerActionManager.AnyControllerConnected, CloseFilters(), CloseLootDrops(), CloseSortOrder(), displayFilters, displayOrders, DrawFilterSearch(), drawLootDrops, filterDraw, filterEnabled, filterItemOver, filterScale, j__TPar, and System.list.