terraria-cpp2il-methodrecon: GUIBestiary.DrawFilterSearch
DrawFilterSearch()
void GUIBestiary.DrawFilterSearch () inline private
Definition at line 127 of file GUIBestiary.cs.
    {
        bool flag = this.editingSearch;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            int num = 1;
            this.editingSearch = num != 0;
            if (-2147483648 == 0)
            {
            }
            Main.clrInput();
        }
        bool flag2 = this.editingSearch;
        if (flag2)
        {
            if (!flag2)
            {
            }
            return;
        }
        bool flag3 = string.IsNullOrWhiteSpace(this.searchTerm);
        string textValue = Language.GetTextValue("UI.PlayerNameSlot");
    }
References Terraria.Main.clrInput(), editingSearch, Terraria.Localization.Language.GetTextValue(), j__TPar, and searchTerm.
Referenced by DrawFilters().