terraria-cpp2il-methodrecon: Mono.Security.X509.X509Chain.Build
Build()
bool Mono.Security.X509.X509Chain.Build (X509Certificate leaf) inline
Definition at line 96 of file X509Chain.cs.
        {
            X509CertificateCollection chain = this._chain;
            if (chain != null)
            {
                int count = chain.Count;
                X509CertificateCollection chain2 = this._chain;
                long num = 0L;
                X509Certificate x509Certificate = chain2[(int)num];
                bool flag = this.IsParent(leaf, x509Certificate);
                int num2 = 1;
                X509CertificateCollection chain3 = this._chain;
                X509Certificate x509Certificate2 = this._chain[num2];
                X509Certificate x509Certificate3;
                return this.IsParent(x509Certificate3, x509Certificate2);
            }
            if (leaf != null)
            {
                bool isSelfSigned = leaf.IsSelfSigned;
                int num3 = this._chain.Add(leaf);
                X509Certificate x509Certificate4 = this.FindCertificateParent(leaf);
                if (x509Certificate4 != null)
                {
                    return x509Certificate4.IsSelfSigned;
                }
            }
            X509Certificate x509Certificate5;
            this._root = x509Certificate5;
            X509CertificateCollection chain4 = this._chain;
            if (chain4 == null || this._status != X509ChainStatusFlags.NoError)
            {
                X509ChainStatusFlags status = this._status;
            }
            X509CertificateCollection.X509CertificateEnumerator enumerator = chain4.GetEnumerator();
            bool flag2 = enumerator.MoveNext();
            X509Certificate x509Certificate6 = enumerator.Current;
            return this.IsValid(x509Certificate6);
        }
References Mono.Security.X509.X509Chain._chain, Mono.Security.X509.X509Chain._status, Mono.Security.X509.X509CertificateCollection.Add(), System.Collections.CollectionBase.Count, System.count, Mono.Security.X509.X509CertificateCollection.X509CertificateEnumerator.Current, Mono.Security.X509.X509Chain.FindCertificateParent(), Mono.Security.X509.X509Chain.IsParent(), Mono.Security.X509.X509Chain.IsValid(), j__TPar, System.L, and Mono.Security.X509.X509CertificateCollection.X509CertificateEnumerator.MoveNext().