terraria-cpp2il-methodrecon: System.IO.FileStream.ReadInternal
ReadInternal()
int System.IO.FileStream.ReadInternal (byte[] dest, int offset, int count) inline private inherited
Definition at line 329 of file FileStream.cs.
        {
            int num = this.ReadSegment(dest, offset, count);
            int num2 = this.buf_size;
            this.FlushBuffer();
            SafeFileHandle safeFileHandle = this.safeHandle;
            int num3 = this.ReadData(safeFileHandle, dest, count, count);
            long num4 = this.buf_start;
            this.buf_start = num4;
            return num3;
        }
References System.IO.FileStream.buf_size, System.IO.FileStream.buf_start, System.count, System.IO.FileStream.FlushBuffer(), j__TPar, System.offset, System.IO.FileStream.ReadData(), System.IO.FileStream.ReadSegment(), and System.IO.FileStream.safeHandle.
Referenced by System.IO.FileStream.Read().