terraria-cpp2il-methodrecon: System.IO.StreamWriter.Flush
Flush() [1/2]
override void System.IO.StreamWriter.Flush () inline virtual
Reimplemented from System.IO.TextWriter.
Reimplemented in System.IO.UnexceptionalStreamWriter.
Definition at line 160 of file StreamWriter.cs.
        {
            this.CheckAsyncTaskInProgress();
            this.Flush(true, true);
        }
References System.IO.StreamWriter.CheckAsyncTaskInProgress(), and System.IO.StreamWriter.Flush().
Referenced by System.IO.StreamWriter.Dispose(), System.IO.StreamWriter.Flush(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.WriteLine(), and System.IO.StreamWriter.WriteSpan().