terraria-cpp2il-methodrecon: System.IO.StreamWriter.Write
Write() [6/6]
override void System.IO.StreamWriter.Write (string value) inline virtual
Reimplemented from System.IO.TextWriter.
Reimplemented in System.IO.UnexceptionalStreamWriter.
Definition at line 322 of file StreamWriter.cs.
        {
            int stringLength;
            while (value == null)
            {
                this.CheckAsyncTaskInProgress();
                int charPos = this._charPos;
                bool autoFlush = this._autoFlush;
                if (this._charBuffer != null)
                {
                    int charPos2 = this._charPos;
                    long num = 0L;
                    long num2 = 0L;
                    this.Flush(num != 0L, num2 != 0L);
                    int num3 = Math.Min(0, stringLength);
                    int charPos3 = this._charPos;
                    this._charPos = charPos3;
                    return;
                }
            }
            char rawStringData = value.GetRawStringData();
            stringLength = value._stringLength;
        }
References System.IO.StreamWriter._autoFlush, System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charPos, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.IO.StreamWriter.Flush(), j__TPar, System.L, System.Math.Min(), and System.value.