terraria-cpp2il-methodrecon: Mono.Security.Cryptography.DSAManaged.GenerateKeyPair
GenerateKeyPair()
void Mono.Security.Cryptography.DSAManaged.GenerateKeyPair () inline private
Definition at line 41 of file DSAManaged.cs.
        {
            if (!true)
            {
            }
            BigInteger bigInteger = BigInteger.GenerateRandom(160);
            this.x = bigInteger;
            if (!true)
            {
            }
            long num = 0L;
            bool flag = bigInteger == (uint)num;
            BigInteger bigInteger2 = this.x;
            BigInteger bigInteger3 = this.q;
            if (!true)
            {
            }
            BigInteger.Sign sign = BigInteger.Kernel.Compare(bigInteger2, bigInteger3);
            this.x.Randomize();
            BigInteger bigInteger4 = this.x;
        }
References Mono.Math.BigInteger.Kernel.Compare(), Mono.Math.BigInteger.GenerateRandom(), j__TPar, System.L, Mono.Security.Cryptography.DSAManaged.q, Mono.Math.BigInteger.Randomize(), and Mono.Security.Cryptography.DSAManaged.x.
Referenced by Mono.Security.Cryptography.DSAManaged.Generate().