terraria-cpp2il-methodrecon: System.Net.WebOperation.SetError
SetError()
void System.Net.WebOperation.SetError (Exception error) inline private
Definition at line 157 of file WebOperation.cs.
        {
            WebCompletionSource<WebRequestStream> webCompletionSource = this.requestTask;
            WebCompletionSource<WebRequestStream> webCompletionSource2 = this.requestWrittenTask;
            WebCompletionSource<WebResponseStream> webCompletionSource3 = this.responseTask;
            long num = 0L;
            this.Finish(num != 0L, error);
        }
References System.Net.WebOperation.Finish(), j__TPar, System.L, System.Net.WebOperation.requestTask, System.Net.WebOperation.requestWrittenTask, and System.Net.WebOperation.responseTask.
Referenced by System.Net.WebOperation.CompleteRequestWritten(), and System.Net.WebOperation.Finish().