terraria-cpp2il-methodrecon: System.Net.WebOperation.RegisterRequest
RegisterRequest()
void System.Net.WebOperation.RegisterRequest (ServicePoint servicePoint, WebConnection connection) inline package
Definition at line 258 of file WebOperation.cs.
        {
            int num = 1;
            if (servicePoint != null)
            {
                if (connection != null)
                {
                    int num2;
                    if (num2 != 0)
                    {
                        return;
                    }
                    long num3 = 0L;
                    this.<Connection>k__BackingField = connection;
                    this.<ServicePoint>k__BackingField = servicePoint;
                    int num4 = 11;
                    if (num != 0)
                    {
                        Monitor.Exit(this);
                    }
                    if (num3 == 0L)
                    {
                        if (num4 == 0)
{
                            CancellationToken token = this.cts.Token;
                        }
                        return;
                    }
                }
                throw new OutOfMemoryException();
            }
        }
References System.Net.WebOperation.Connection, System.Net.WebOperation.cts, System.Threading.Monitor.Exit(), j__TPar, System.Net.WebOperation.k__BackingField, System.L, and System.Threading.CancellationTokenSource.Token.
Referenced by System.Net.WebConnection.Continue(), and System.Net.WebConnection.StartOperation().