terraria-cpp2il-methodrecon: System.Net.WebOperation.Finish
Finish()
void System.Net.WebOperation.Finish (bool ok, [Optional] Exception error) inline package
Definition at line 456 of file WebOperation.cs.
        {
            int num = 1;
            long num2 = 0L;
            if (Interlocked.CompareExchange(0, num, (int)num2) != 0)
            {
                return;
            }
            Monitor.Enter(this, num != 0);
            HttpWebRequest httpWebRequest = this.<Request>k__BackingField;
            long num3 = 0L;
            int num4 = 3;
            if (httpWebRequest != null)
            {
                Monitor.Exit(this);
            }
            if (num3 != 0L)
            {
                throw new OutOfMemoryException();
            }
            while (num4 != 0)
            {
            }
            if (error != null)
            {
                if (this != null)
                {
                    this.SetError(error);
                }
                bool flag = this.finishedTask.TrySetException(error);
                return;
            }
            bool aborted = this.Aborted;
            if (this != null)
            {
            }
            if (this != null)
            {
                bool aborted2 = this.Aborted;
                return;
            }
            WebCompletionSource<ValueTuple<bool, WebOperation>> webCompletionSource = this.finishedTask;
        }
References System.Net.WebOperation.Aborted, System.Threading.Interlocked.CompareExchange(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Net.WebOperation.finishedTask, j__TPar, System.Net.WebOperation.k__BackingField, System.L, System.Net.WebOperation.Request, and System.Net.WebOperation.SetError().
Referenced by System.Net.WebOperation.SetError().