terraria-cpp2il-methodrecon: System.Net.ContextAwareResult.CaptureOrComplete
CaptureOrComplete()
bool System.Net.ContextAwareResult.CaptureOrComplete (ExecutionContext cachedContext, bool returnContext) inline private
Definition at line 155 of file ContextAwareResult.cs.
        {
            if (this._flags == ContextAwareResult.StateFlags.None)
            {
            }
            NetEventSource.Fail(this, "Called without calling StartPostingAsyncOp.", "CaptureOrComplete");
            AsyncCallback asyncCallback = this.m_AsyncCallback;
            ContextAwareResult.StateFlags flags = this._flags;
            if (asyncCallback != null)
            {
            }
            bool internalPeekCompleted = base.InternalPeekCompleted;
            if (!true)
            {
                if (flags == ContextAwareResult.StateFlags.None)
                {
                }
                bool isEnabled = NetEventSource.IsEnabled;
                if (flags == ContextAwareResult.StateFlags.None)
                {
                }
                NetEventSource.Info(this, "starting identity capture", "CaptureOrComplete");
            }
            if (true)
            {
                bool internalPeekCompleted2 = base.InternalPeekCompleted;
            }
            if (flags == ContextAwareResult.StateFlags.None)
            {
            }
            bool isEnabled2 = NetEventSource.IsEnabled;
            if (flags == ContextAwareResult.StateFlags.None)
            {
            }
            NetEventSource.Info(this, "Skipping capture", "CaptureOrComplete");
            AsyncCallback asyncCallback2 = this.m_AsyncCallback;
            if (asyncCallback2 != null)
            {
                bool completedSynchronously = base.CompletedSynchronously;
                if (asyncCallback2 == null)
                {
                }
                NetEventSource.Fail(this, "Didn't capture context, but didn't complete synchronously!", "CaptureOrComplete");
                if (asyncCallback2 == null)
                {
                }
                bool isEnabled3 = NetEventSource.IsEnabled;
                if (asyncCallback2 == null)
                {
                }
                NetEventSource.Info(this, "starting capture", "CaptureOrComplete");
                ExecutionContext executionContext;
                if ("Didn't capture context, but didn't complete synchronously!" == null)
                {
                    executionContext = ExecutionContext.Capture();
                    if (executionContext == null)
                    {
                        goto IL_00DE;
                    }
                }
                this._context = executionContext;
                IL_00DE:
                bool isEnabled4 = NetEventSource.IsEnabled;
                ExecutionContext context = this._context;
                if (context != null && context == null)
                {
                    throw new ArrayTypeMismatchException();
                }
                if (asyncCallback == null)
                {
                }
                FormattableString formattableString;
                NetEventSource.Info(this, formattableString, "CaptureOrComplete");
            }
            bool completedSynchronously2 = base.CompletedSynchronously;
            bool isEnabled5 = NetEventSource.IsEnabled;
            NetEventSource.Info(this, "Completing synchronously", "CaptureOrComplete");
            return true;
        }
References System.Net.ContextAwareResult._context, System.Net.ContextAwareResult._flags, System.Threading.ExecutionContext.Capture(), System.Net.NetEventSource.Fail(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalPeekCompleted, System.Net.NetEventSource.IsEnabled, j__TPar, and System.Net.LazyAsyncResult.m_AsyncCallback.