terraria-cpp2il-methodrecon: XNAUICameraSettings.ApplyCamera
ApplyCamera()
void XNAUICameraSettings.ApplyCamera () inline
Definition at line 193 of file XNAUICameraSettings.cs.
    {
        Rect viewportSafeRegion = this.GetViewportSafeRegion();
        bool screenResolutionSettingsDirty = this.ScreenResolutionSettingsDirty;
        int num = 16256;
        this._zoomScale = (float)num;
        this.RecalculateVirtualScreen();
        Rect viewportSafeRegion2 = this.GetViewportSafeRegion();
        float height = viewportSafeRegion2.height;
        float pixelScale = this.PixelScale;
        float width = viewportSafeRegion2.width;
        float height2 = viewportSafeRegion2.height;
        if (num == 0)
        {
        }
        this.RecalculateVirtualScreen();
        float pixelScale2 = this.PixelScale;
        if (32640 == 0)
        {
        }
        int cameraWidth = this._cameraWidth;
        int cameraHeight = this._cameraHeight;
        float xmin = this._cameraSafeRegion.m_XMin;
        float ymin = this._cameraSafeRegion.m_YMin;
        float width2 = this._cameraSafeRegion.m_Width;
        float height3 = this._cameraSafeRegion.m_Height;
        this._cameraSafeRegion = 43139072;
        int nativeHeight = this.NativeHeight;
        float pixelScale3 = this.PixelScale;
        int num2 = 32640;
        this.realVirtualScreenHeight = num2;
        int nativeWidth = this.NativeWidth;
        int nativeHeight2 = this.NativeHeight;
        int num3 = this.realVirtualScreenHeight;
        if (cameraWidth == 0)
        {
        }
        int num4 = 32640;
        this.realVirtualScreenWidth = num4;
        int nativeWidth2 = this.NativeWidth;
        int num5 = this.realVirtualScreenWidth;
        int num6 = 65408;
        this.realVirtualScreenOffsetX = num6;
        int nativeHeight3 = this.NativeHeight;
        int num7 = this.realVirtualScreenHeight;
        Camera camera = this.Camera;
        this.realVirtualScreenOffsetY = num6;
        if (num6 == 0)
        {
        }
        Transform transform = this.Camera.transform;
        int num8 = this.realVirtualScreenWidth;
        int nativeWidth3 = this.NativeWidth;
        int num9 = this.realVirtualScreenWidth;
        int num10 = this.realVirtualScreenOffsetX;
        if (num6 == 0)
        {
        }
        int height4 = Screen.height;
        int num11 = this.realVirtualScreenHeight;
        int num12 = this.realVirtualScreenWidth;
        int num13 = this.realVirtualScreenOffsetX;
        Camera camera2 = this.Camera;
    }
References _cameraHeight, _cameraSafeRegion, _cameraWidth, Camera, GetViewportSafeRegion(), UnityEngine.Screen.height, j__TPar, UnityEngine.Rect.m_Height, UnityEngine.Rect.m_Width, UnityEngine.Rect.m_XMin, UnityEngine.Rect.m_YMin, NativeHeight, NativeWidth, DeviceVPPICalculator.PixelScale, realVirtualScreenHeight, realVirtualScreenOffsetX, realVirtualScreenWidth, RecalculateVirtualScreen(), ScreenResolutionSettingsDirty, and UnityEngine.Component.transform.
Referenced by XNAUnityRunner.Awake(), and XNAUnityRunner.ExecuteFrame().