terraria-cpp2il-methodrecon: Terraria.Projectile.GetFishingPondState
GetFishingPondState()
static void Terraria.Projectile.GetFishingPondState (int x, int y, [Out] bool lava, [Out] bool honey, [Out] int numWaters, [Out] int chumCount) inline static private
Definition at line 1482 of file Projectile.cs.
        {
            int num = 1;
            long num2 = 0L;
            long num3 = 0L;
            long num4 = 0L;
            if (num == 0)
            {
            }
            Projectile.GetFishingPondWidth(x, (int)num2, (int)num3, (int)num4);
            int num5 = 1;
            if (num == 0)
            {
            }
            Tile tile;
            byte liquid = tile.liquid;
            long num6 = 0L;
            bool flag = WorldGen.SolidTile(x, 0, num6 != 0L);
            Tile tile2;
            bool flag2 = tile2.lava();
            if (!lava)
            {
            }
            Tile tile3;
            bool flag3 = tile3.honey();
            honey.m_value = num5 != 0;
            if (!honey)
            {
            }
            chumCount.m_value = (honey ? 1 : 0);
        }
References Terraria.Projectile.GetFishingPondWidth(), Terraria.Tile.honey(), j__TPar, System.L, Terraria.Tile.lava(), Terraria.Tile.liquid, and Terraria.WorldGen.SolidTile().