terraria-cpp2il-methodrecon: Terraria.Projectile.GetProjectileSource_FromThis
GetProjectileSource_FromThis()
IEntitySource Terraria.Projectile.GetProjectileSource_FromThis () inline
Definition at line 1750 of file Projectile.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_038(), Terraria.Projectile.AI_046(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.BetsySharpnel(), Terraria.Projectile.BoulderExplosion(), and Terraria.Projectile.SummonSuperStarSlash().