terraria-cpp2il-methodrecon: Mono.Security.X509.X509Certificate.Parse
Parse()
void Mono.Security.X509.X509Certificate.Parse (byte[] data) inline private
Definition at line 13 of file X509Certificate.cs.
        {
            ASN1 asn;
            byte nTag = asn.m_nTag;
            ASN1 asn2 = this.decoder;
            long num = 0L;
            ASN1 asn3 = asn2[(int)num];
            ASN1 asn4 = this.decoder;
            long num2 = 0L;
            ASN1 asn5 = asn4[(int)num2];
            long num3 = 0L;
            ASN1 asn6 = asn5[(int)num3];
            int num4 = 1;
            this.version = num4;
            byte nTag2 = asn6.m_nTag;
            int num5;
            if (asn6.elist != null)
            {
                num5 = this.version;
                long num6 = 0L;
                byte[] value = asn6[(int)num6].Value;
                return;
            }
            long num7 = 0L;
            ASN1 asn7 = this.decoder;
            long num8 = 0L;
            ASN1 asn8 = asn7[(int)num8][(int)num7];
            byte nTag3 = asn8.m_nTag;
            byte[] value2 = asn8.Value;
            this.serialnumber = value2;
            int num9 = 48;
            ASN1 asn9 = asn3.Element(num5, (byte)num9);
            this.issuer = asn9;
            string text = X501.ToString(asn9);
            this.m_issuername = text;
            int num10 = 48;
            ASN1 asn10 = asn3.Element(num5, (byte)num10);
            long num11 = 0L;
            DateTime dateTime = ASN1Convert.ToDateTime(asn10[(int)num11]);
            this.m_from = dateTime;
            int num12 = 1;
            DateTime dateTime2 = ASN1Convert.ToDateTime(asn10[num12]);
            this.m_until = dateTime2;
            int num13 = 48;
            ASN1 asn11 = asn3.Element(num12, (byte)num13);
            this.subject = asn11;
            string text2 = X501.ToString(asn11);
            this.m_subject = text2;
            int num14 = 48;
            ASN1 asn12 = asn3.Element(num12, (byte)num14);
            int num15 = 48;
            long num16 = 0L;
            ASN1 asn13 = asn12.Element((int)num16, (byte)num15);
            int num17 = 6;
            long num18 = 0L;
            string text3 = ASN1Convert.ToOid(asn13.Element((int)num18, (byte)num17));
            this.m_keyalgo = text3;
            int num19 = 1;
            ASN1 asn14 = asn13[num19];
            if (asn13.elist != null)
            {
                return;
            }
            long num20;
            this.m_keyalgoparams = num20;
            int num21 = 1;
            int num22 = 3;
            ASN1 asn15 = asn12.Element(num21, (byte)num22);
            if (asn15.m_aValue != null)
            {
            }
            byte[] value3 = asn15.Value;
            byte[] publickey = this.m_publickey;
            ASN1 asn16 = this.decoder;
            int num23 = 2;
            byte[] value4 = asn16[num23].Value;
            ASN1 asn17 = this.decoder;
            int num24 = 1;
            ASN1 asn18 = asn17[num24];
            int num25 = 6;
            long num26 = 0L;
            string text4 = ASN1Convert.ToOid(asn18.Element((int)num26, (byte)num25));
            this.m_signaturealgo = text4;
            int num27 = 1;
            ASN1 asn19 = asn18[num27];
            if (asn19 != null)
            {
            }
            this.m_signaturealgoparams = asn19;
            int num28 = 129;
            ASN1 asn20 = asn3.Element((int)num7, (byte)num28);
            if (asn20 != null)
            {
                byte[] value5 = asn20.Value;
                this.issuerUniqueID = value5;
            }
            int num29 = 130;
            ASN1 asn21 = asn3.Element((int)num7, (byte)num29);
            if (asn21 != null)
            {
                byte[] value6 = asn21.Value;
                this.subjectUniqueID = value6;
            }
            int num30 = 163;
            ASN1 asn22 = asn3.Element((int)num7, (byte)num30);
            if (asn22 != null && asn22.elist != null)
            {
                long num31 = 0L;
                ASN1 asn23 = asn22[(int)num31];
                return;
            }
            object obj;
            if (obj != null)
            {
                if (obj == null)
                {
                    throw new InvalidCastException();
                }
                this.m_encodedcert = obj;
                if (obj == null)
                {
                    throw new InvalidCastException();
                }
            }
        }
References Mono.Security.X509.X509Certificate.decoder, Mono.Security.ASN1.Element(), j__TPar, System.L, Mono.Security.ASN1.m_nTag, Mono.Security.X509.X509Certificate.m_publickey, System.obj, System.text, Mono.Security.ASN1Convert.ToDateTime(), Mono.Security.ASN1Convert.ToOid(), Mono.Security.X509.X501.ToString(), Mono.Security.ASN1.Value, System.value, and Mono.Security.X509.X509Certificate.version.
Referenced by Mono.Security.X509.X509Certificate.X509Certificate().