terraria-cpp2il-methodrecon: System.IO.File.WriteAllBytes
WriteAllBytes()
static void System.IO.File.WriteAllBytes (string path, byte[] bytes) inline static
Definition at line 200 of file File.cs.
        {
            while (path != null)
            {
                if (path._stringLength == 0)
                {
                    return;
                }
                if (bytes != null)
                {
                    File.InternalWriteAllBytes(path, bytes);
                    return;
                }
            }
        }
References System.IO.File.InternalWriteAllBytes().
Referenced by CSVWriter.CloseStreams(), and DefaultFileAPI.WriteFile().