terraria-cpp2il-methodrecon: UnityEngine.UI.AspectRatioFitter.IsComponentValidOnObject
IsComponentValidOnObject()
bool UnityEngine.UI.AspectRatioFitter.IsComponentValidOnObject () inline
Definition at line 212 of file AspectRatioFitter.cs.
        {
            Canvas component = base.gameObject.GetComponent<Canvas>();
            bool flag = component;
            bool isRootCanvas = component.isRootCanvas;
            RenderMode renderMode = component.renderMode;
            return true;
        }
References UnityEngine.Component.gameObject, UnityEngine.GameObject.GetComponent(), UnityEngine.Canvas.isRootCanvas, j__TPar, and UnityEngine.Canvas.renderMode.
Referenced by UnityEngine.UI.AspectRatioFitter.Start(), and UnityEngine.UI.AspectRatioFitter.UpdateRect().