terraria-cpp2il-methodrecon: UnityEngine.UI.AspectRatioFitter.UpdateRect
UpdateRect()
void UnityEngine.UI.AspectRatioFitter.UpdateRect () inline private
Definition at line 136 of file AspectRatioFitter.cs.
        {
            bool flag = this.IsComponentValidOnObject();
            AspectRatioFitter.AspectMode aspectMode = this.m_AspectMode;
            RectTransform rectTransform = this.rectTransform;
            RectTransform rectTransform2 = this.rectTransform;
            float height = this.rectTransform.rect.height;
            float aspectRatio = this.m_AspectRatio;
        }
References UnityEngine.UI.AspectRatioFitter.aspectMode, UnityEngine.UI.AspectRatioFitter.aspectRatio, UnityEngine.Rect.height, UnityEngine.UI.AspectRatioFitter.IsComponentValidOnObject(), j__TPar, UnityEngine.UI.AspectRatioFitter.m_AspectMode, UnityEngine.UI.AspectRatioFitter.m_AspectRatio, UnityEngine.RectTransform.rect, and UnityEngine.UI.AspectRatioFitter.rectTransform.
Referenced by UnityEngine.UI.AspectRatioFitter.OnEnable(), UnityEngine.UI.AspectRatioFitter.OnRectTransformDimensionsChange(), UnityEngine.UI.AspectRatioFitter.OnTransformParentChanged(), UnityEngine.UI.AspectRatioFitter.SetDirty(), and UnityEngine.UI.AspectRatioFitter.Update().