terraria-cpp2il-methodrecon: Terraria.Player.PlaceThing_Walls
PlaceThing_Walls()
void Terraria.Player.PlaceThing_Walls () inline private
Definition at line 11554 of file Player.cs.
        {
            for (;;)
            {
                Microsoft.Xna.Framework.Vector2 position = this.inventory.position;
                float x = this.position.X;
                if (position == null)
                {
                }
                int tileRangeX = Player.tileRangeX;
                Item[] array = this.inventory;
                int num = this.blockRange;
                Microsoft.Xna.Framework.Vector2 position2 = array.position;
                int tileTargetX = Player.tileTargetX;
                int num2 = 15744;
                float x2 = this.position.X;
                int width = this.width;
                if (num2 == 0)
                {
                }
                int tileRangeX2 = Player.tileRangeX;
                Item[] array2 = this.inventory;
                int num3 = this.blockRange;
                Microsoft.Xna.Framework.Vector2 position3 = array2.position;
                int tileTargetX2 = Player.tileTargetX;
                int num4 = 15744;
                float y = this.position.Y;
                if (num4 == 0)
                {
                }
                int tileRangeY = Player.tileRangeY;
                Item[] array3 = this.inventory;
                int num5 = this.blockRange;
                Microsoft.Xna.Framework.Vector2 position4 = array3.position;
                int tileTargetY = Player.tileTargetY;
                int num6 = 15744;
                float y2 = this.position.Y;
                int height = this.height;
                if (num6 == 0)
                {
                }
                int tileRangeY2 = Player.tileRangeY;
                Item[] array4 = this.inventory;
                int num7 = this.blockRange;
                Microsoft.Xna.Framework.Vector2 position5 = array4.position;
                int tileTargetY2 = Player.tileTargetY;
                int num8 = this.itemTime;
                int num9 = 1;
                this.cursorItemIconEnabled = num9 != 0;
                if (num8 != 0)
                {
                    break;
                }
                int num10 = this.itemAnimation;
                bool flag = this.controlUseItem;
                while (!flag)
                {
                }
                if (!flag)
                {
                }
                int tileTargetX3 = Player.tileTargetX;
                int tileTargetY3 = Player.tileTargetY;
                Tile tile;
                bool flag2 = tile.active();
                int tileTargetX4 = Player.tileTargetX;
                int tileTargetY4 = Player.tileTargetY;
                Tile tile2;
                ushort wall = tile2.wall;
                int tileTargetX5 = Player.tileTargetX;
                int tileTargetY5 = Player.tileTargetY;
                Tile tile3;
                bool flag3 = tile3.active();
                int tileTargetX6 = Player.tileTargetX;
                int tileTargetY6 = Player.tileTargetY;
                Tile tile4;
                ushort wall2 = tile4.wall;
                int tileTargetX7 = Player.tileTargetX;
                int tileTargetY7 = Player.tileTargetY;
                Tile tile5;
                bool flag4 = tile5.active();
                int tileTargetX8 = Player.tileTargetX;
                int tileTargetY8 = Player.tileTargetY;
                Tile tile6;
                ushort wall3 = tile6.wall;
                int tileTargetX9 = Player.tileTargetX;
                int tileTargetY9 = Player.tileTargetY;
                Tile tile7;
                bool flag5 = tile7.active();
                int tileTargetX10 = Player.tileTargetX;
                int tileTargetY10 = Player.tileTargetY;
                Tile tile8;
                ushort wall4 = tile8.wall;
                int tileTargetX11 = Player.tileTargetX;
                int tileTargetY11 = Player.tileTargetY;
                Tile tile9;
                ushort wall5 = tile9.wall;
                Microsoft.Xna.Framework.Vector2 position6 = this.inventory.position;
                int[] array5 = this.builderAccStatus;
                if (array5 == null)
                {
                    int num11 = 1;
                    bool flag6 = this.PlaceThing_TryReplacingWalls(num11 != 0);
                }
                if (array5 == null)
                {
                }
                int tileTargetX12 = Player.tileTargetX;
                int tileTargetY12 = Player.tileTargetY;
                Item[] array6 = this.inventory;
                long num12 = 0L;
                WorldGen.PlaceWall(tileTargetX12, tileTargetY12, 0, num12 != 0L);
                if (!false)
                {
                }
                int tileTargetX13 = Player.tileTargetX;
                int tileTargetY13 = Player.tileTargetY;
                Tile tile10;
                ushort wall6 = tile10.wall;
                Microsoft.Xna.Framework.Vector2 position7 = this.inventory.position;
                float num13 = this.wallSpeed;
                int num14 = 32640;
                this.itemTime = num14;
                this.itemTimeMax = num14;
                if (num14 == 0)
                {
                }
                bool netClient = Main.NetClient;
                if (num14 == 0)
                {
                }
                int tileTargetX14 = Player.tileTargetX;
                int tileTargetY14 = Player.tileTargetY;
                Item[] array7 = this.inventory;
                this.PlaceThing_Walls_FillEmptySpace();
                if (this.autoPaint)
                {
                    goto Block_3;
                }
            }
            return;
            Block_3:
            int[] array8 = this.builderAccStatus;
            while (array8 != null)
            {
            }
            if (array8 == null)
            {
            }
            int tileTargetX15 = Player.tileTargetX;
            int tileTargetY15 = Player.tileTargetY;
            int num15 = 1;
            long num16 = 0L;
            this.TryPainting(tileTargetX15, tileTargetY15, num15 != 0, num16 != 0L);
        }
References Terraria.Tile.active(), System.array, Terraria.Player.autoPaint, Terraria.Player.blockRange, Terraria.Player.builderAccStatus, Terraria.Player.controlUseItem, Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.itemTime, j__TPar, System.L, Terraria.Main.NetClient, Terraria.Player.PlaceThing_TryReplacingWalls(), Terraria.Player.PlaceThing_Walls_FillEmptySpace(), Terraria.WorldGen.PlaceWall(), Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.TryPainting(), Terraria.Tile.wall, Terraria.Player.wallSpeed, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.PlaceThing().