terraria-cpp2il-methodrecon: Terraria.Player.PlaceThing
PlaceThing()
void Terraria.Player.PlaceThing (Player::ItemCheckContext context) inline
Definition at line 11533 of file Player.cs.
        {
            if (this.itemTime == 0)
            {
            }
            this.PlaceThing_Paintbrush();
            this.PlaceThing_PaintRoller();
            this.PlaceThing_PaintScrapper();
            this.PlaceThing_CannonBall();
            this.PlaceThing_XMasTreeTops();
            this.PlaceThing_ItemInExtractinator(context);
            this.PlaceThing_LockChest();
            if (this.noBuilding)
            {
                return;
            }
            this.PlaceThing_Tiles();
            this.PlaceThing_Walls();
        }
References Terraria.Player.itemTime, Terraria.Player.noBuilding, Terraria.Player.PlaceThing_CannonBall(), Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.PlaceThing_LockChest(), Terraria.Player.PlaceThing_Paintbrush(), Terraria.Player.PlaceThing_PaintRoller(), Terraria.Player.PlaceThing_PaintScrapper(), Terraria.Player.PlaceThing_Tiles(), Terraria.Player.PlaceThing_Walls(), and Terraria.Player.PlaceThing_XMasTreeTops().