terraria-cpp2il-methodrecon: Terraria.Player.PlaceThing_ItemInExtractinator
PlaceThing_ItemInExtractinator()
void Terraria.Player.PlaceThing_ItemInExtractinator (Player::ItemCheckContext context) inline private
Definition at line 12956 of file Player.cs.
        {
            for (;;)
            {
                if (!true)
                {
                }
                int tileTargetX = Player.tileTargetX;
                int tileTargetY = Player.tileTargetY;
                Item[] array = this.inventory;
                Microsoft.Xna.Framework.Vector2 position = array.position;
                Tile tile;
                bool flag = tile.active();
                float x = this.position.X;
                if (array == null)
                {
                }
                int tileRangeX = Player.tileRangeX;
                int num = this.blockRange;
                int tileTargetX2 = Player.tileTargetX;
                int num2 = 15744;
                float x2 = this.position.X;
                int width = this.width;
                if (num2 == 0)
                {
                }
                int tileRangeX2 = Player.tileRangeX;
                int num3 = this.blockRange;
                int tileTargetX3 = Player.tileTargetX;
                int num4 = 15744;
                float y = this.position.Y;
                if (num4 == 0)
                {
                }
                int tileRangeY = Player.tileRangeY;
                int num5 = this.blockRange;
                int tileTargetY2 = Player.tileTargetY;
                int num6 = 15744;
                float y2 = this.position.Y;
                int height = this.height;
                if (num6 == 0)
                {
                }
                int tileRangeY2 = Player.tileRangeY;
                int num7 = this.blockRange;
                int tileTargetY3 = Player.tileTargetY;
                if (this.itemTime != 0)
                {
                    break;
                }
                int num8 = this.itemAnimation;
                if (this.controlUseItem)
                {
                    goto Block_1;
                }
            }
            return;
            Block_1:
            ItemTrader itemTrader;
            int num10;
            if (itemTrader != null)
            {
                int num9 = 1;
                num10 = 32640;
                this.itemTime = num10;
                this.itemTimeMax = num10;
                context.SkipItemConsumption = num9 != 0;
                long num11 = 0L;
                long num12 = 0L;
                this.DropItemFromExtractinator((int)num11, (int)num12);
                return;
            }
            if (num10 == 0)
            {
            }
            int num13 = 32640;
            this.itemTime = num13;
            this.itemTimeMax = num13;
            if (num13 == 0)
            {
            }
            int num14 = 219;
            PlatformAwardNotifierUtility.NoteCraftingStationUsed(this, num14);
            if (num13 == 0)
            {
            }
        }
References Terraria.Tile.active(), System.array, Terraria.Player.blockRange, Terraria.Player.controlUseItem, Terraria.Player.DropItemFromExtractinator(), Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.itemTime, j__TPar, System.L, PlatformAwardNotifierUtility.NoteCraftingStationUsed(), Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.PlaceThing().