terraria-cpp2il-methodrecon: Terraria.Player.ItemCheck_CatchCritters
ItemCheck_CatchCritters()
Rectangle Terraria.Player.ItemCheck_CatchCritters (Item sItem, Rectangle itemRectangle) inline private
Definition at line 15047 of file Player.cs.
        {
            int num = 1;
            int type = sItem.type;
            if (num == 0)
            {
            }
            int myPlayer = Main.myPlayer;
            int whoAmI = this.whoAmI;
            PlayerDeathReason playerDeathReason = PlayerDeathReason.ByNPC(myPlayer);
            Microsoft.Xna.Framework.Vector2 center = base.Center;
            bool flag = this.dead;
            if (!flag)
            {
                int num2 = 24;
                int num3 = 300;
                long num4 = 0L;
                long num5 = 0L;
                this.AddBuff(num2, num3, num4 != 0L, num5 != 0L);
                if (!flag)
                {
                }
                if (!flag)
                {
                }
                int whoAmI2 = this.whoAmI;
                if (!flag)
                {
                }
                NPC.CatchNPC(int.MinValue, whoAmI2);
            }
            return int.MinValue;
        }
References Terraria.Player.AddBuff(), Terraria.DataStructures.PlayerDeathReason.ByNPC(), Terraria.NPC.CatchNPC(), Terraria.Player.dead, j__TPar, System.L, Terraria.Main.myPlayer, and Terraria.Entity.whoAmI.