terraria-cpp2il-methodrecon: Terraria.Player.InternalSavePlayerFile
InternalSavePlayerFile()
static void Terraria.Player.InternalSavePlayerFile (PlayerFileData playerFile) inline static private
Definition at line 18692 of file Player.cs.
        {
            int num = 1;
            string path = playerFile._path;
            Player player = playerFile._player;
            bool isCloudSave = playerFile._isCloudSave;
            if (num == 0)
            {
            }
            Debug.Log(DateTime.Now.ToString() + " Saving the player");
            if (path == null)
            {
                return;
            }
            bool flag = path == "";
            if ("" == null)
            {
            }
            if ("" != null)
            {
                if ("" == null)
                {
                }
                long num2 = 0L;
                string text = path + ".bak";
                int num3 = 1;
                FileUtilities.Copy(path, text, num2 != 0L, num3 != 0);
            }
            FileMetadata metadata = playerFile.Metadata;
            long num4 = 0L;
            string text2 = player.name;
            byte b = player.difficulty;
            TimeSpan playTime = playerFile.GetPlayTime();
            int num5 = player.hair;
            byte b2 = player.hairDye;
            BitsByte bitsByte = 0;
            long num6 = 0L;
            bool[] array = player.hideVisibleAccessory;
            bitsByte[(int)num6] = num4 != 0L;
            BitsByte bitsByte2 = 0;
            long num7 = 0L;
            bool[] array2 = player.hideVisibleAccessory;
            bitsByte2[(int)num7] = num4 != 0L;
            BitsByte bitsByte3 = player.hideMisc;
            int num8 = player.skinVariant;
            int num9 = player.statLife;
            int num10 = player.statLifeMax;
            int num11 = player.statMana;
            int num12 = player.statManaMax;
            bool flag2 = player.extraAccessory;
            bool flag3 = player.unlockedBiomeTorches;
            if (player.unlockedBiomeTorches)
            {
                int[] array3 = player.builderAccStatus;
                return;
            }
            bool flag4 = player.ateArtisanBread;
            bool flag5 = player.usedAegisCrystal;
            bool flag6 = player.usedAegisFruit;
            bool flag7 = player.usedArcaneCrystal;
            bool flag8 = player.usedGalaxyPearl;
            bool flag9 = player.usedGummyWorm;
            bool flag10 = player.usedAmbrosia;
            bool flag11 = player.downedDD2EventAnyDifficulty;
            int num13 = player.taxMoney;
            int num14 = player.numberOfDeathsPVE;
            int num15 = player.numberOfDeathsPVP;
            byte r = player.hairColor.R;
            byte g = player.hairColor.G;
            byte b3 = player.hairColor.B;
            byte r2 = player.skinColor.R;
            byte g2 = player.skinColor.G;
            byte b4 = player.skinColor.B;
            byte r3 = player.eyeColor.R;
            byte g3 = player.eyeColor.G;
            byte b5 = player.eyeColor.B;
            byte r4 = player.shirtColor.R;
            byte g4 = player.shirtColor.G;
            byte b6 = player.shirtColor.B;
            byte r5 = player.underShirtColor.R;
            byte g5 = player.underShirtColor.G;
            byte b7 = player.underShirtColor.B;
            byte r6 = player.pantsColor.R;
            byte g6 = player.pantsColor.G;
            byte b8 = player.pantsColor.B;
            byte r7 = player.shoeColor.R;
            byte g7 = player.shoeColor.G;
            byte b9 = player.shoeColor.B;
            Item[] array4 = player.armor;
            long entityId = array4.entityId;
            int netID = array4.netID;
            byte prefix = player.armor.prefix;
            Item[] array5 = player.armor;
            Item[] array6 = player.dye;
            long entityId2 = array6.entityId;
            int netID2 = array6.netID;
            byte prefix2 = player.dye.prefix;
            Item[] array7 = player.dye;
            int netID3 = player.inventory.netID;
            int stack = player.inventory.stack;
            byte prefix3 = player.inventory.prefix;
            bool favorited = player.inventory.favorited;
            Item[] array8 = player.miscEquips;
            long entityId3 = array8.entityId;
            int netID4 = array8.netID;
            byte prefix4 = player.miscEquips.prefix;
            int netID5 = player.miscDyes.netID;
            byte prefix5 = player.miscDyes.prefix;
            Item[] array9 = player.miscEquips;
            int netID6 = player.bank.item.netID;
            int stack2 = player.bank.item.stack;
            byte prefix6 = player.bank.item.prefix;
            int netID7 = player.bank2.item.netID;
            int stack3 = player.bank2.item.stack;
            byte prefix7 = player.bank2.item.prefix;
            int netID8 = player.bank3.item.netID;
            int stack4 = player.bank3.item.stack;
            byte prefix8 = player.bank3.item.prefix;
            int netID9 = player.bank4.item.netID;
            int stack5 = player.bank4.item.stack;
            byte prefix9 = player.bank4.item.prefix;
            bool favorited2 = player.bank4.item.favorited;
            BitsByte bitsByte4 = player.voidVaultInfo;
            int[] array10 = player.buffType;
        }
References Terraria.Player.armor, System.array, Terraria.Player.ateArtisanBread, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Player.buffType, Terraria.Player.builderAccStatus, Terraria.Utilities.FileUtilities.Copy(), Terraria.Player.difficulty, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.Player.dye, Terraria.Entity.entityId, Terraria.Player.extraAccessory, Terraria.Player.eyeColor, Terraria.Item.favorited, Terraria.Player.hair, Terraria.Player.hairColor, Terraria.Player.hairDye, Terraria.Player.hideMisc, Terraria.Player.hideVisibleAccessory, Terraria.Player.inventory, Terraria.Chest.item, j__TPar, System.L, UnityEngine.Debug.Log(), Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Player.name, Terraria.Item.netID, System.DateTime.Now, Terraria.Player.numberOfDeathsPVE, Terraria.Player.numberOfDeathsPVP, Terraria.Player.pantsColor, Terraria.Item.prefix, Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, System.stack, Terraria.Item.stack, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.Player.taxMoney, System.text, System.DateTime.ToString(), Terraria.Player.underShirtColor, Terraria.Player.unlockedBiomeTorches, Terraria.Player.usedAegisCrystal, Terraria.Player.usedAegisFruit, Terraria.Player.usedAmbrosia, Terraria.Player.usedArcaneCrystal, Terraria.Player.usedGalaxyPearl, Terraria.Player.usedGummyWorm, and Terraria.Player.voidVaultInfo.