terraria-cpp2il-methodrecon: Terraria.Player.InterruptItemUsageIfOverTile
InterruptItemUsageIfOverTile()
void Terraria.Player.InterruptItemUsageIfOverTile (int tileTypeToBeOver) inline
Definition at line 1854 of file Player.cs.
        {
            if (!true)
            {
            }
            int tileTargetX = Player.tileTargetX;
            int tileTargetY = Player.tileTargetY;
            Tile tile;
            bool flag = tile.active();
        }
References Terraria.Tile.active(), Terraria.Player.tileTargetX, and Terraria.Player.tileTargetY.
Referenced by Terraria.WorldGen.CheckFoodPlatter(), Terraria.WorldGen.CheckWeaponsRack(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile().