terraria-cpp2il-methodrecon: Terraria.Player.FloorVisuals
FloorVisuals()
void Terraria.Player.FloorVisuals (bool Falling) inline
Definition at line 7707 of file Player.cs.
        {
            int width = this.width;
            int height = this.height;
            float x = this.position.X;
            float y = this.position.Y;
            float num = this.gravDir;
            int num2 = 32640;
            int num3 = 63488;
            Tile floorTile = Player.GetFloorTile(43143168, Falling ? 1 : 0);
            if (num2 == 0)
            {
            }
            this.slippy2 = num2 != 0;
            this.powerrun = num3 != 0;
            if (num2 == 0)
            {
                if (num2 == 0)
                {
                }
                if (num2 == 0)
                {
                    if (this.name == null)
                    {
                    }
                    return;
                }
            }
            int num4 = 1;
            this.runningOnSand = num4 != 0;
            int whoAmI = this.whoAmI;
            if (num4 == 0)
            {
            }
            int myPlayer = Main.myPlayer;
            int num5 = 120;
            int num6 = 180;
            int num7 = 1;
            long num8 = 0L;
            this.AddBuff(num5, num6, num7 != 0, num8 != 0L);
            if (num4 == 0)
            {
            }
            Tile tile;
            byte b = tile.slope();
            if (num4 == 0)
            {
            }
            Tile tile2;
            byte b2 = tile2.slope();
            if (num4 == 0)
            {
            }
            Tile tile3;
            byte b3 = tile3.slope();
            if (!this.wet)
            {
                bool cart = this.mount.Cart;
                return;
            }
        }
References Terraria.Player.AddBuff(), Terraria.Mount.Cart, Terraria.Player.GetFloorTile(), Terraria.Player.gravDir, Terraria.Entity.height, j__TPar, System.L, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.name, Terraria.Entity.position, Terraria.Tile.slope(), Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.