terraria-cpp2il-methodrecon: Terraria.Player.ItemCheck_UseEventItems
ItemCheck_UseEventItems()
void Terraria.Player.ItemCheck_UseEventItems (Item sItem) inline private
Definition at line 14201 of file Player.cs.
        {
            if (this.itemTime == 0)
            {
                int num = this.itemAnimation;
                if (sItem.type == 0)
                {
                }
                bool flag = Main.CanStartInvasion(1, 16777216 != 0);
                int useTime = sItem.useTime;
                float x = this.position.X;
                float y = this.position.Y;
                this.itemTime = useTime;
                this.itemTimeMax = useTime;
                if (useTime == 0)
                {
                }
                if (32640 != 0)
                {
                    int whoAmI = this.whoAmI;
                    if (useTime == 0)
                    {
                    }
                    return;
                }
                if (32640 == 0)
                {
                }
                if (32640 == 0)
                {
                    if (32640 == 0)
                    {
                    }
                    Main.StartInvasion(1);
                }
                if (this.itemTime == 0)
                {
                    int num2 = this.itemAnimation;
                    if (sItem.type == 0)
                    {
                    }
                    bool flag2 = Main.CanStartInvasion(2, 16777216 != 0);
                    int useTime2 = sItem.useTime;
                    float x2 = this.position.X;
                    float y2 = this.position.Y;
                    this.itemTime = useTime2;
                    this.itemTimeMax = useTime2;
                    if (useTime2 == 0)
                    {
                    }
                    if (32640 != 0)
                    {
                        int whoAmI2 = this.whoAmI;
                        if (useTime2 == 0)
{
                        }
                        return;
                    }
                    if (32640 == 0)
                    {
                    }
                    if (32640 == 0)
                    {
                        if (32640 == 0)
{
                        }
                        Main.StartInvasion(2);
                    }
                    if (this.itemTime == 0)
                    {
                        int num3 = this.itemAnimation;
                        if (sItem.type == 0)
{
                        }
                        bool flag3 = Main.CanStartInvasion(3, 16777216 != 0);
                        int useTime3 = sItem.useTime;
                        float x3 = this.position.X;
                        float y3 = this.position.Y;
                        this.itemTime = useTime3;
                        this.itemTimeMax = useTime3;
                        if (useTime3 == 0)
{
                        }
                        if (32640 != 0)
{
                            int whoAmI3 = this.whoAmI;
                            if (useTime3 == 0)
{
                            }
                            return;
                        }
                        if (32640 == 0)
{
                        }
                        if (32640 == 0)
{
                            if (32640 == 0)
{
                            }
                            Main.StartInvasion(3);
                        }
                        if (this.itemTime == 0)
{
                            int num4 = this.itemAnimation;
                            if (sItem.type == 0)
{
                            }
                            if (32640 == 0)
{
                                if (32640 == 0)
{
                                }
                                if (32640 == 0)
{
                                    if (32640 == 0)
{
                                    }
                                    int useTime4 = sItem.useTime;
                                    float x4 = this.position.X;
                                    float y4 = this.position.Y;
                                    this.itemTime = useTime4;
                                    this.itemTimeMax = useTime4;
                                    if (useTime4 == 0)
{
                                    }
                                    if (useTime4 != 0)
{
                                        int whoAmI4 = this.whoAmI;
                                        if (useTime4 == 0)
{
                                        }
                                        return;
                                    }
                                    if (32640 == 0)
{
                                    }
                                    if (32640 == 0)
{
                                    }
                                    Main.startPumpkinMoon();
                                }
                            }
                            if (this.itemTime == 0)
{
                                int num5 = this.itemAnimation;
                                if (sItem.type == 0)
{
                                }
                                if (32640 != 0)
{
                                    if (32640 == 0)
{
                                    }
                                    float x5 = this.position.X;
                                    float y5 = this.position.Y;
                                    int useTime5 = sItem.useTime;
                                    this.itemTime = useTime5;
                                    this.itemTimeMax = useTime5;
                                    if (useTime5 == 0)
{
                                    }
                                    int whoAmI5;
                                    if (32768 != 0)
{
                                        whoAmI5 = this.whoAmI;
                                        if (useTime5 == 0)
{
                                        }
                                        return;
                                    }
                                    if (32768 == 0)
{
                                    }
                                    if (!true)
{
                                    }
                                    if (whoAmI5 != 0)
{
                                        return;
                                    }
                                    if (!true)
{
                                    }
                                }
                                if (this.itemTime == 0)
{
                                    int num6 = this.itemAnimation;
                                    if (sItem.type == 0)
{
                                    }
                                    if (4271 == 0)
{
                                        if (4271 == 0)
{
                                        }
                                        float x6 = this.position.X;
                                        float y6 = this.position.Y;
                                        int useTime6 = sItem.useTime;
                                        this.itemTime = useTime6;
                                        this.itemTimeMax = useTime6;
                                        if (useTime6 == 0)
{
                                        }
                                        if (useTime6 != 0)
{
                                            int whoAmI6 = this.whoAmI;
                                            if (useTime6 == 0)
{
                                            }
                                            return;
                                        }
                                        AchievementsHelper.NotifyProgressionEvent(4);
                                        if (useTime6 == 0)
{
                                        }
                                        if (32768 == 0)
{
                                        }
                                        if (5 == 0)
{
                                        }
                                        if (5 == 0)
{
                                        }
                                    }
                                    if (this.itemTime == 0)
{
                                        int num7 = this.itemAnimation;
                                        int type = sItem.type;
                                        if (type == 0)
{
                                        }
                                        if (type != 0)
{
                                            if (type == 0)
{
                                            }
                                            if (type != 0)
{
                                                if (type == 0)
{
                                                }
                                                long num8 = 0L;
                                                long num9 = 0L;
                                                bool flag4 = NPC.AnyDanger(num8 != 0L, num9 != 0L);
                                                if (type == 0)
{
                                                }
                                                bool flag5 = NPC.AnyoneNearCultists();
                                                float x7 = this.position.X;
                                                float y7 = this.position.Y;
                                                int useTime7 = sItem.useTime;
                                                this.itemTime = useTime7;
                                                this.itemTimeMax = useTime7;
                                                if (useTime7 == 0)
{
                                                }
                                                if (useTime7 != 0)
{
                                                    int whoAmI7 = this.whoAmI;
                                                    if (useTime7 == 0)
{
                                                    }
                                                    return;
                                                }
                                                WorldGen.StartImpendingDoom(720);
                                            }
                                        }
                                        if (this.itemTime == 0)
{
                                            int num10 = this.itemAnimation;
                                            if (sItem.type == 0)
{
                                            }
                                            while (32768 != 0)
{
                                            }
                                            if (32768 == 0)
{
                                            }
                                            while (32768 != 0)
{
                                            }
                                            if (32768 == 0)
{
                                            }
                                            int useTime8 = sItem.useTime;
                                            float x8 = this.position.X;
                                            float y8 = this.position.Y;
                                            this.itemTime = useTime8;
                                            this.itemTimeMax = useTime8;
                                            if (useTime8 == 0)
{
                                            }
                                            if (useTime8 != 0)
{
                                                int whoAmI8 = this.whoAmI;
                                                if (useTime8 == 0)
{
                                                }
                                                return;
                                            }
                                            if (32640 == 0)
{
                                            }
                                            if (32640 == 0)
{
                                            }
                                            Main.startSnowMoon();
                                            return;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.NPC.AnyDanger(), Terraria.NPC.AnyoneNearCultists(), Terraria.Main.CanStartInvasion(), Terraria.Player.itemAnimation, Terraria.Player.itemTime, j__TPar, System.L, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Entity.position, Terraria.WorldGen.StartImpendingDoom(), Terraria.Main.StartInvasion(), Terraria.Main.startPumpkinMoon(), Terraria.Main.startSnowMoon(), Terraria.Item.type, Terraria.Item.useTime, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.