terraria-cpp2il-methodrecon: Terraria.Player.RecalculateLuck
RecalculateLuck()
void Terraria.Player.RecalculateLuck () inline
Definition at line 8363 of file Player.cs.
        {
            float ladyBugLuck = this.GetLadyBugLuck();
            float num = this.torchLuck;
            byte b = this.luckPotion;
            if (this.usedGalaxyPearl)
            {
            }
            bool lanternsUp = LanternNight.LanternsUp;
            float num2 = this.luck;
            this.luck = num2;
            bool hasGardenGnomeNearby = this.HasGardenGnomeNearby;
            float num3 = this.luck;
            if (hasGardenGnomeNearby)
            {
                this.luck = num3;
            }
            float num4 = this.equipmentBasedLuckBonus;
            float num5 = this.CalculateCoinLuck();
            this.luck = num3;
        }
References Terraria.Player.CalculateCoinLuck(), Terraria.Player.equipmentBasedLuckBonus, Terraria.Player.GetLadyBugLuck(), Terraria.Player.HasGardenGnomeNearby, j__TPar, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Player.luck, Terraria.Player.luckPotion, Terraria.Player.torchLuck, and Terraria.Player.usedGalaxyPearl.
Referenced by Terraria.Player.UpdateLuck().