terraria-cpp2il-methodrecon: Terraria.Player.PlaceThing_LockChest
PlaceThing_LockChest()
void Terraria.Player.PlaceThing_LockChest () inline private
Definition at line 12887 of file Player.cs.
        {
            if (!true)
            {
            }
            int tileTargetX = Player.tileTargetX;
            int tileTargetY = Player.tileTargetY;
            Item[] array = this.inventory;
            Microsoft.Xna.Framework.Vector2 position = array.position;
            Tile tile;
            bool flag = tile.active();
            if (array == null)
            {
            }
            Microsoft.Xna.Framework.Vector2 position2 = array.position;
            if (position2 != null)
            {
                float x = this.position.X;
                if (position2 == null)
                {
                }
                int tileRangeX = Player.tileRangeX;
                int num = this.blockRange;
                int tileTargetX2 = Player.tileTargetX;
                int num2 = 15744;
                float x2 = this.position.X;
                int width = this.width;
                if (num2 == 0)
                {
                }
                int tileRangeX2 = Player.tileRangeX;
                int num3 = this.blockRange;
                int tileTargetX3 = Player.tileTargetX;
                int num4 = 15744;
                float y = this.position.Y;
                if (num4 == 0)
                {
                }
                int tileRangeY = Player.tileRangeY;
                int num5 = this.blockRange;
                int tileTargetY2 = Player.tileTargetY;
                int num6 = 15744;
                float y2 = this.position.Y;
                int height = this.height;
                if (num6 == 0)
                {
                }
                int tileRangeY2 = Player.tileRangeY;
                int num7 = this.blockRange;
                int tileTargetY3 = Player.tileTargetY;
                if (this.itemTime == 0)
                {
                    int num8 = this.itemAnimation;
                    bool flag2 = this.controlUseItem;
                    while (!flag2)
                    {
                    }
                    if (!flag2)
                    {
                    }
                    int tileTargetX4 = Player.tileTargetX;
                    int tileTargetY4 = Player.tileTargetY;
                    ushort type = Framing.GetTileSafely(tileTargetX4, tileTargetY4).type;
                    return;
                }
            }
        }
References Terraria.Tile.active(), System.array, Terraria.Player.blockRange, Terraria.Player.controlUseItem, Terraria.Framing.GetTileSafely(), Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.itemTime, j__TPar, Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.PlaceThing().