terraria-cpp2il-methodrecon: Terraria.Player.PlaceThing_Paintbrush
PlaceThing_Paintbrush()
void Terraria.Player.PlaceThing_Paintbrush () inline private
Definition at line 13383 of file Player.cs.
        {
            Microsoft.Xna.Framework.Vector2 position = this.inventory.position;
            float x = this.position.X;
            if (position == null)
            {
            }
            int tileRangeX = Player.tileRangeX;
            Item[] array = this.inventory;
            int num = this.blockRange;
            Microsoft.Xna.Framework.Vector2 position2 = array.position;
            int tileTargetX = Player.tileTargetX;
            int num2 = 15744;
            float x2 = this.position.X;
            int width = this.width;
            if (num2 == 0)
            {
            }
            int tileRangeX2 = Player.tileRangeX;
            Item[] array2 = this.inventory;
            int num3 = this.blockRange;
            Microsoft.Xna.Framework.Vector2 position3 = array2.position;
            int tileTargetX2 = Player.tileTargetX;
            int num4 = 15744;
            float y = this.position.Y;
            if (num4 == 0)
            {
            }
            int tileRangeY = Player.tileRangeY;
            Item[] array3 = this.inventory;
            int num5 = this.blockRange;
            Microsoft.Xna.Framework.Vector2 position4 = array3.position;
            int tileTargetY = Player.tileTargetY;
            int num6 = 15744;
            float y2 = this.position.Y;
            int height = this.height;
            if (num6 == 0)
            {
            }
            int tileRangeY2 = Player.tileRangeY;
            Item[] array4 = this.inventory;
            int num7 = this.blockRange;
            Microsoft.Xna.Framework.Vector2 position5 = array4.position;
            int tileTargetY2 = Player.tileTargetY;
            if (15744 == 0)
            {
            }
            int tileTargetX3 = Player.tileTargetX;
            int tileTargetY3 = Player.tileTargetY;
            Tile tile;
            bool flag = tile.active();
            int num8 = this.itemTime;
            int num9 = 1;
            this.cursorItemIconEnabled = num9 != 0;
            if (num8 == 0)
            {
                int num10 = this.itemAnimation;
                if (this.controlUseItem)
                {
                    int num11 = 1;
                    long num12 = 0L;
                    this.TryPainting(tileTargetX3, tileTargetY3, num12 != 0L, num11 != 0);
                }
            }
        }
References Terraria.Tile.active(), System.array, Terraria.Player.blockRange, Terraria.Player.controlUseItem, Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.itemTime, j__TPar, System.L, Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.TryPainting(), Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.PlaceThing().