terraria-cpp2il-methodrecon: Terraria.Player.PetAnimal
PetAnimal()
void Terraria.Player.PetAnimal (int animalNpcIndex) inline
Definition at line 9770 of file Player.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            long num2 = 0L;
            Microsoft.Xna.Framework.Vector2 bottom = base.Bottom;
            if (num == 0)
            {
            }
            bool flag = WorldGen.SolidTileAllowBottomSlope(0, (int)num2);
            bool flag2 = this.isPettingAnimal;
            if (flag2)
            {
                Microsoft.Xna.Framework.Vector2 bottom2 = base.Bottom;
                if (!flag2)
                {
                }
                return;
            }
            int num3 = 1;
            this.RemoveAllGrapplingHooks();
            Mount mount = this.mount;
            bool active = mount._active;
            if (active)
            {
                mount.Dismount(this);
            }
            long num4 = 0L;
            this.ChangeDir((int)num4);
            this.isPettingAnimal = num3 != 0;
            this.isTheAnimalBeingPetSmall = active;
            if (!active)
            {
            }
            if (!true)
            {
            }
            int num5 = 16256;
            this.gravDir = (float)num5;
            int whoAmI = this.whoAmI;
            int myPlayer = Main.myPlayer;
            int num6 = 21;
            AchievementsHelper.HandleSpecialEvent(this, num6);
        }
References Terraria.Mount._active, Terraria.Entity.active, Terraria.Player.ChangeDir(), Terraria.Mount.Dismount(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Player.isPettingAnimal, j__TPar, System.L, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.RemoveAllGrapplingHooks(), Terraria.WorldGen.SolidTileAllowBottomSlope(), and Terraria.Entity.whoAmI.