terraria-cpp2il-methodrecon: Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool
ItemCheck_UseMiningTools_ActuallyUseMiningTool()
void Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool (Item sItem, [Out] bool canHitWalls, int x, int y) inline private
Definition at line 15866 of file Player.cs.
        {
            int num = 1;
            canHitWalls.m_value = num != 0;
            if (num == 0)
            {
            }
            Tile tile;
            bool flag = tile.active();
            int pick = sItem.pick;
            if (pick == 0)
            {
            }
            if (pick == 0)
            {
                if (pick == 0)
                {
                }
                if (pick == 0)
                {
                    goto IL_0046;
                }
            }
            int axe = sItem.axe;
            if (axe == 0)
            {
            }
            if (axe == 0)
            {
                int hammer = sItem.hammer;
                if (hammer == 0)
                {
                }
                if (hammer != 0)
                {
                }
            }
            IL_0046:
            HitTile hitTile = this.hitTile;
            int num2 = 1;
            int num3 = hitTile.HitObject(x, y, num2);
            if (100 != 0)
            {
                int hammer2 = sItem.hammer;
                bool flag2 = WorldGen.CanKillTile(x, y);
                int hammer3 = sItem.hammer;
                if (hammer3 == 0)
                {
                }
                long num5;
                if (hammer3 == 0)
                {
                    PlayerDeathReason playerDeathReason = PlayerDeathReason.ByOther(4);
                    int num4 = this.statLife;
                    int direction = this.direction;
                    num5 = 0L;
                }
                int num6 = 1;
                int num7 = this.hitTile.AddDamage(num3, (int)num5, num6 != 0);
                HitTile hitTile2 = this.hitReplace;
                int num8 = 1;
                hitTile2.TryClearingAndPruning(x, y, num8);
                HitTile hitTile3 = this.hitTile;
                int num9 = 1;
                hitTile3.TryClearingAndPruning(x, y, num9);
                long num10 = 0L;
                long num11 = 0L;
                long num12 = 0L;
                WorldGen.KillTile(x, y, num10 != 0L, num11 != 0L, num12 != 0L);
                bool netClient = Main.NetClient;
                return;
            }
        }
References Terraria.Tile.active(), Terraria.HitTile.AddDamage(), Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.WorldGen.CanKillTile(), Terraria.Entity.direction, Terraria.HitTile.HitObject(), Terraria.Player.hitReplace, Terraria.Player.hitTile, j__TPar, Terraria.WorldGen.KillTile(), System.L, Terraria.Main.NetClient, Terraria.Player.statLife, and Terraria.HitTile.TryClearingAndPruning().