terraria-cpp2il-methodrecon: Terraria.Player.SavePlayer
SavePlayer()
static void Terraria.Player.SavePlayer (PlayerFileData playerFile, bool skipMapSave = false, bool forceSave = false) inline static
Definition at line 18657 of file Player.cs.
        {
            Player player = playerFile._player;
            LocalUser localUser = player.LocalUser;
            if (localUser != null)
            {
                localUser.SavePersistantData();
            }
            if (player == null)
            {
            }
            Player.UpdateOldMobilePath(playerFile);
            if (player == null)
            {
            }
            AchievementManager achievements = Main.Achievements;
            long num = 0L;
            achievements.Save();
            bool isCloudSave = playerFile._isCloudSave;
            if (player == null)
            {
            }
            Player.InternalSaveMap(true, num != 0L);
            if (player == null)
            {
            }
            if (player.DpadRadial != null)
            {
                string text = DateTime.Now.ToString() + " Serverside characters enabled, saving disabled.";
                Debug.Log(text);
                return;
            }
        }
References Terraria.Main.Achievements, Terraria.Player.DpadRadial, Terraria.Player.InternalSaveMap(), j__TPar, System.L, Terraria.Player.LocalUser, UnityEngine.Debug.Log(), System.DateTime.Now, Terraria.Achievements.AchievementManager.Save(), LocalUser.SavePersistantData(), System.text, System.DateTime.ToString(), and Terraria.Player.UpdateOldMobilePath().
Referenced by Terraria.IO.PlayerFileData.Rename(), and Terraria.WorldGen.saveToonWhilePlayingCallBack().