terraria-cpp2il-methodrecon: Terraria.Player.PlaceWeapon
PlaceWeapon()
void Terraria.Player.PlaceWeapon (int x, int y) inline
Definition at line 17901 of file Player.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Tile tile;
            bool flag = tile.active();
            if (num == 0)
            {
            }
            Tile tile2;
            ushort type = tile2.type;
            if (num == 0)
            {
            }
            Tile tile3;
            short frameY = tile3.frameY;
            if (num == 0)
            {
            }
            Tile tile4;
            short frameY2 = tile4.frameY;
            if (num == 0)
            {
            }
            Tile tile5;
            short frameY3 = tile5.frameY;
            if (num == 0)
            {
            }
            Tile tile6;
            short frameX = tile6.frameX;
            int num2 = 5000;
            if (36409 == 0)
            {
            }
            Tile tile7;
            short frameX2 = tile7.frameX;
            if (num2 == 0)
            {
            }
            int num3 = 1;
            long num4 = 0L;
            long num5 = 0L;
            WorldGen.KillTile(x, y, num3 != 0, num4 != 0L, num5 != 0L);
            bool netClient = Main.NetClient;
            if (num2 == 0)
            {
            }
            if (num2 == 0)
            {
            }
            bool netClient2 = Main.NetClient;
            if (num2 == 0)
            {
            }
            if (num2 == 0)
            {
            }
            if (num2 == 0)
            {
            }
            Microsoft.Xna.Framework.Vector2 position = this.inventory.position;
            Tile tile8;
            tile8.frameX = 0;
            Microsoft.Xna.Framework.Vector2 position2 = this.inventory.position;
            tile8.frameX = 0;
            bool netClientOnly = Main.NetClientOnly;
            if (position2 == null)
            {
            }
            if (position2 == null)
            {
            }
            bool netClientOnly2 = Main.NetClientOnly;
            if (position2 == null)
            {
            }
            Item[] array = this.inventory;
            Microsoft.Xna.Framework.Vector2 position3 = array.position;
            if (position2 == null)
            {
            }
            Item mouseItem = Main.mouseItem;
            long num6 = 0L;
            mouseItem.SetDefaults((int)num6);
            int num7 = this.selectedItem;
            Item[] array2 = this.inventory;
            Item item = mouseItem.Clone();
            if (array == null)
            {
            }
            Main.mouseItem = item;
            int num8 = 1;
            this.mouseInterface = num8 != 0;
        }
References Terraria.Tile.active(), System.array, Terraria.Item.Clone(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Player.inventory, System.item, j__TPar, Terraria.WorldGen.KillTile(), System.L, Terraria.Main.mouseItem, Terraria.Main.NetClient, Terraria.Main.NetClientOnly, Terraria.Entity.position, Terraria.Player.selectedItem, Terraria.Item.SetDefaults(), and Terraria.Tile.type.