terraria-cpp2il-methodrecon: Terraria.Player.InternalSaveMap
InternalSaveMap()
static void Terraria.Player.InternalSaveMap (bool isCloudSave, bool forceSave = false) inline static
Definition at line 18913 of file Player.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            bool flag = string.IsNullOrEmpty(Main.playerPathName);
            if (num == 0)
            {
            }
            string text = DateTime.Now.ToString() + " Saving the map";
            long num2 = 0L;
            Debug.Log(text);
            bool mapEnabled = Main.mapEnabled;
            Main.Map.Save(num2 != 0L);
            FileUtilities.CreateDirectory(Main.PlayerPath);
            string text2 = DateTime.Now.ToString() + " Map saved!";
            Debug.Log(text2);
        }
References Terraria.Utilities.FileUtilities.CreateDirectory(), j__TPar, System.L, UnityEngine.Debug.Log(), Terraria.Main.Map, Terraria.Main.mapEnabled, System.DateTime.Now, Terraria.Main.PlayerPath, Terraria.Main.playerPathName, System.text, and System.DateTime.ToString().
Referenced by Terraria.Player.SavePlayer().