terraria-cpp2il-methodrecon: Terraria.Player.PlaceThing_TryReplacingWalls
PlaceThing_TryReplacingWalls()
bool Terraria.Player.PlaceThing_TryReplacingWalls (bool canUse) inline private
Definition at line 11749 of file Player.cs.
        {
            int num = this.itemAnimation;
            if (this.itemTime != 0)
            {
            }
            bool flag = this.controlUseItem;
            while (!flag)
            {
            }
            if (!flag)
            {
            }
            int tileTargetX = Player.tileTargetX;
            int tileTargetY = Player.tileTargetY;
            bool flag2 = WorldGen.NearFriendlyWall(tileTargetX, tileTargetY);
            int tileTargetX2 = Player.tileTargetX;
            int tileTargetY2 = Player.tileTargetY;
            Item[] array = this.inventory;
            bool flag3 = WorldGen.ReplaceWall(tileTargetX2, tileTargetY2, (ushort)tileTargetY);
            Item[] array2 = this.inventory;
            float num2 = this.wallSpeed;
            Microsoft.Xna.Framework.Vector2 position = array2.position;
            int num3 = 32640;
            this.itemTime = num3;
            this.itemTimeMax = num3;
            if (num3 == 0)
            {
            }
            int tileTargetX3 = Player.tileTargetX;
            int tileTargetY3 = Player.tileTargetY;
            Item[] array3 = this.inventory;
            if (!this.autoPaint)
            {
                return;
            }
            int[] array4 = this.builderAccStatus;
            if (array4 == null)
            {
                if (array4 == null)
                {
                }
                int tileTargetX4 = Player.tileTargetX;
                int tileTargetY4 = Player.tileTargetY;
                int num4 = 1;
                long num5 = 0L;
                this.TryPainting(tileTargetX4, tileTargetY4, num4 != 0, num5 != 0L);
                return;
            }
        }
References System.array, Terraria.Player.autoPaint, Terraria.Player.builderAccStatus, Terraria.Player.controlUseItem, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.itemTime, j__TPar, System.L, Terraria.WorldGen.NearFriendlyWall(), Terraria.Entity.position, Terraria.WorldGen.ReplaceWall(), Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.TryPainting(), and Terraria.Player.wallSpeed.
Referenced by Terraria.Player.PlaceThing_Walls().