terraria-cpp2il-methodrecon: Terraria.Player.ItemCheck_UseMiningTools_TryHittingWall
ItemCheck_UseMiningTools_TryHittingWall()
void Terraria.Player.ItemCheck_UseMiningTools_TryHittingWall (Item sItem, int wX, int wY) inline private
Definition at line 16012 of file Player.cs.
        {
            long num2;
            for (;;)
            {
                int num = 1;
                if (num == 0)
                {
                }
                Tile tile;
                ushort wall = tile.wall;
                if (num == 0)
                {
                }
                Tile tile2;
                bool flag = tile2.active();
                if (num == 0)
                {
                }
                int tileTargetX = Player.tileTargetX;
                if (num == 0)
                {
                }
                int tileTargetY = Player.tileTargetY;
                if (num == 0)
                {
                }
                num2 = 0L;
                Tile tile3;
                ushort type = tile3.type;
                if (num != 0 || this.poundRelease || this.toolTime != 0)
                {
                    break;
                }
                int num3 = this.itemAnimation;
                if (this.controlUseItem)
                {
                    goto Block_2;
                }
            }
            return;
            Block_2:
            if (sItem.hammer == 0)
            {
            }
            bool flag2 = Player.CanPlayerSmashWall(wX, wY);
            int hammer = sItem.hammer;
            this.PickWall(wX, wY, (int)num2);
            int useTime = sItem.useTime;
            this.itemTime = useTime;
        }
References Terraria.Tile.active(), Terraria.Player.CanPlayerSmashWall(), Terraria.Player.controlUseItem, Terraria.Item.hammer, Terraria.Player.itemAnimation, j__TPar, System.L, Terraria.Player.PickWall(), Terraria.Player.poundRelease, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.toolTime, Terraria.Tile.type, and Terraria.Tile.wall.