terraria-cpp2il-methodrecon: UnityEngine.Experimental.Rendering.GraphicsFormatUtility.IsCrunchFormat
IsCrunchFormat()
static bool UnityEngine.Experimental.Rendering.GraphicsFormatUtility.IsCrunchFormat (TextureFormat format) inline static
Definition at line 139 of file GraphicsFormatUtility.cs.
        {
            return true;
        }
Referenced by UnityEngine.Cubemap.Cubemap(), UnityEngine.CubemapArray.CubemapArray(), UnityEngine.Texture2D.Texture2D(), UnityEngine.Texture2DArray.Texture2DArray(), UnityEngine.Texture3D.Texture3D(), and UnityEngine.Texture3D.Texture3D().