terraria-cpp2il-methodrecon: Mono.Security.Cryptography.RSAManaged.GenerateKeyPair
GenerateKeyPair() [2/2]
void Mono.Security.Cryptography.RSAManaged.GenerateKeyPair () inline private
Definition at line 25 of file RSAManaged.cs.
        {
            BigInteger bigInteger = 65537U;
            this.e = bigInteger;
            BigInteger bigInteger2 = BigInteger.GeneratePseudoPrime(-1073741824);
            this.p = bigInteger2;
            uint length = bigInteger2.length;
            if (length != 0U)
            {
                uint[] data = bigInteger2.data;
                return;
            }
            BigInteger bigInteger3;
            if (bigInteger3 == null)
            {
            }
            BigInteger bigInteger4 = BigInteger.GeneratePseudoPrime(0);
            this.q = bigInteger4;
            uint length2 = bigInteger4.length;
            if (length2 != 0U)
            {
                uint[] data2 = bigInteger4.data;
            }
            BigInteger bigInteger5 = this.p;
            if (length2 == 0U)
            {
            }
            bool flag = bigInteger5 != bigInteger4;
            BigInteger bigInteger6 = this.p;
            BigInteger bigInteger7 = this.q;
            if (length2 == 0U)
            {
            }
            BigInteger bigInteger8 = bigInteger6 * bigInteger7;
            this.n = bigInteger8;
            int num = bigInteger8.BitCount();
            BigInteger bigInteger9 = this.p;
            BigInteger bigInteger10 = 1;
            BigInteger bigInteger11 = bigInteger9 - bigInteger10;
            BigInteger bigInteger12 = this.q;
            BigInteger bigInteger13 = 1;
            BigInteger bigInteger14 = bigInteger12 - bigInteger13;
            BigInteger bigInteger15 = bigInteger11 * bigInteger14;
            BigInteger bigInteger16 = this.e;
            BigInteger bigInteger17 = BigInteger.Kernel.modInverse(bigInteger16, bigInteger15);
            this.d = bigInteger17;
            BigInteger[] array = BigInteger.Kernel.multiByteDivide(bigInteger17, bigInteger11);
            BigInteger bigInteger18 = this.d;
            this.dp = bigInteger16;
            BigInteger[] array2 = BigInteger.Kernel.multiByteDivide(bigInteger18, bigInteger14);
            BigInteger bigInteger19 = this.p;
            BigInteger bigInteger20 = this.q;
            this.dq = bigInteger16;
            BigInteger bigInteger21 = BigInteger.Kernel.modInverse(bigInteger20, bigInteger19);
            RSAManaged.KeyGeneratedEventHandler keyGenerated = this.KeyGenerated;
            this.qInv = bigInteger21;
            if (keyGenerated != null)
            {
                IntPtr invoke_impl = keyGenerated.invoke_impl;
                IntPtr method_code = keyGenerated.method_code;
                IntPtr method = keyGenerated.method;
                return;
            }
        }
References System.array, Mono.Math.BigInteger.BitCount(), Mono.Security.Cryptography.RSAManaged.d, Mono.Security.Cryptography.RSAManaged.e, Mono.Math.BigInteger.GeneratePseudoPrime(), j__TPar, Mono.Security.Cryptography.RSAManaged.KeyGenerated, Mono.Math.BigInteger.length, System.length, Mono.Math.BigInteger.Kernel.modInverse(), Mono.Math.BigInteger.Kernel.multiByteDivide(), Mono.Security.Cryptography.RSAManaged.p, Mono.Security.Cryptography.RSAManaged.q, and System.U.