terraria-cpp2il-methodrecon: GUIPageIcons.Close
Close()
void GUIPageIcons.Close (bool hideChat = true) inline
Definition at line 198 of file GUIPageIcons.cs.
    {
        GUIPageIcons.Category selectedLeft = this._selectedLeft;
        GUIPageIcons.Category selectedRight = this._selectedRight;
        if (this.UseConsoleStyle)
        {
            InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
            long num = 0L;
            active.Close(num != 0L);
        }
        Main.playerInventory = false;
        Main.InReforgeMenu = false;
        Main.InGuideCraftMenu = false;
        Main.CancelHairWindow();
        Main.CancelClothesWindow(false);
        Main.npcShop = 0;
        int myPlayer = Main.myPlayer;
        int myPlayer2 = Main.myPlayer;
        int myPlayer3 = Main.myPlayer;
        this.RefreshRightItems();
    }
References _selectedLeft, _selectedRight, InterfaceStyles_Layout.Active, Terraria.Main.CancelClothesWindow(), Terraria.Main.CancelHairWindow(), InterfaceProfile_Layout.Close(), j__TPar, System.L, Terraria.Main.myPlayer, RefreshRightItems(), selectedLeft, selectedRight, and UseConsoleStyle.
Referenced by UpdatePageStates().