terraria-cpp2il-methodrecon: GUIPageIcons.DrawLeftMenuButton
DrawLeftMenuButton()
void GUIPageIcons.DrawLeftMenuButton () inline
Definition at line 650 of file GUIPageIcons.cs.
    {
        if (64 == 0)
        {
        }
        int myPlayer = Main.myPlayer;
        int num = 1;
        bool editChest = Main.editChest;
        long num2;
        int num3;
        if (num != 0)
        {
            if (true)
            {
                num2 = 0L;
                return;
            }
            num3 = 17096;
        }
        bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
        if ((num3 != 0 && num3 == 0 && num3 == 0) || num3 == 0)
        {
        }
        XNAUnityRunner.ForcedInputMode primaryInputMode = XNAUnityRunner.PrimaryInputMode;
        if (num2 != 0L)
        {
            return;
        }
        bool flag = InterfaceStyles_Layout.Active.AnyOpen();
        InterfaceStyles_Layout.Active.LeftRightPageController();
        InterfaceStyles_Layout.Active.Draw();
    }
References InterfaceStyles_Layout.Active, Controller.ControllerActionManager.AnyControllerConnected, InterfaceProfile_Layout.AnyOpen(), InterfaceProfile_Layout.Draw(), Terraria.Main.editChest, j__TPar, System.L, InterfaceProfile_Layout.LeftRightPageController(), Terraria.Main.myPlayer, and XNAUnityRunner.PrimaryInputMode.