terraria-cpp2il-methodrecon: GUIPageIcons.UpdatePageStates
UpdatePageStates()
void GUIPageIcons.UpdatePageStates () inline private
Definition at line 273 of file GUIPageIcons.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        int myPlayer = Main.myPlayer;
        if (num != 0)
        {
            if (num == 0)
            {
            }
            bool flag = InterfaceStyles_Layout.Active.AnyOpen();
            long num2 = 0L;
            this.Close(num2 != 0L);
        }
        this.RefreshAvailableItems();
        bool useConsoleStyle = this.UseConsoleStyle;
        if (useConsoleStyle)
        {
            if (!useConsoleStyle)
            {
            }
            InterfaceStyles_Layout.Active.RefreshAllItems();
            return;
        }
        this.RefreshLeftItems();
        this.RefreshRightItems();
    }
References InterfaceStyles_Layout.Active, InterfaceProfile_Layout.AnyOpen(), Close(), j__TPar, System.L, Terraria.Main.myPlayer, InterfaceProfile_Layout.RefreshAllItems(), RefreshAvailableItems(), RefreshLeftItems(), RefreshRightItems(), and UseConsoleStyle.