terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Content.ThreadContentRequest.LoadFromMainThread
LoadFromMainThread()
global.UnityEngine.Object Microsoft.Xna.Framework.Content.ThreadContentRequest.LoadFromMainThread () inline
Definition at line 214 of file ThreadContentRequest.cs.
        {
            long num = 0L;
            long num2 = 0L;
            Thread.Sleep((int)num);
            object lockObject = this._lockObject;
            Monitor.Enter(lockObject, num2 != 0L);
            bool loaded = this._loaded;
            long num3 = 0L;
            if (loaded)
            {
                Monitor.Exit(lockObject);
            }
            if (num3 == 0L)
            {
                throw new OutOfMemoryException();
            }
            throw new OutOfMemoryException();
        }
References Microsoft.Xna.Framework.Content.ThreadContentRequest._loaded, Microsoft.Xna.Framework.Content.ThreadContentRequest._lockObject, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), j__TPar, System.L, and System.Threading.Thread.Sleep().