terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Content.ThreadContentRequest.UpdateLoad
UpdateLoad()
bool Microsoft.Xna.Framework.Content.ThreadContentRequest.UpdateLoad () inline private
Definition at line 138 of file ThreadContentRequest.cs.
        {
            bool isDone = this._loadRequest.isDone;
            ResourceRequest loadRequest = this._loadRequest2;
            if (loadRequest != null)
            {
                bool isDone2 = loadRequest.isDone;
            }
            ResourceRequest loadRequest2 = this._loadRequest3;
            long num;
            if (loadRequest2 != null)
            {
                num = 0L;
                bool isDone3 = loadRequest2.isDone;
            }
            object lockObject = this._lockObject;
            Monitor.Enter(lockObject, num != 0L);
            ResourceRequest loadRequest3 = this._loadRequest;
            this._loaded = true;
            global::UnityEngine.Object asset = loadRequest3.asset;
            ResourceRequest loadRequest4 = this._loadRequest2;
            this._resource = asset;
            if (loadRequest4 != null)
            {
                global::UnityEngine.Object asset2 = loadRequest4.asset;
                this._resource2 = asset2;
            }
            ResourceRequest loadRequest5 = this._loadRequest3;
            if (loadRequest5 != null)
            {
                global::UnityEngine.Object asset3 = loadRequest5.asset;
                this._resource3 = asset3;
            }
            ThreadContentRequest.ObjectCreate createFunction = this._createFunction;
            if (createFunction != null)
            {
                global::UnityEngine.Object resource = this._resource;
                IntPtr method_code = createFunction.method_code;
                IntPtr invoke_impl = createFunction.invoke_impl;
                IntPtr method = createFunction.method;
                this._constructedObject = method_code;
            }
            ThreadContentRequest.ObjectCreate2 createFunction2 = this._createFunction2;
            if (createFunction2 != null)
            {
                global::UnityEngine.Object resource2 = this._resource;
                global::UnityEngine.Object resource3 = this._resource2;
                IntPtr method_code2 = createFunction2.method_code;
                IntPtr invoke_impl2 = createFunction2.invoke_impl;
                IntPtr method2 = createFunction2.method;
                this._constructedObject = method_code2;
            }
            ThreadContentRequest.ObjectCreate3 createFunction3 = this._createFunction3;
            if (createFunction3 != null)
            {
                global::UnityEngine.Object resource4 = this._resource;
                global::UnityEngine.Object resource5 = this._resource2;
                IntPtr method_code3 = createFunction3.method_code;
                global::UnityEngine.Object resource6 = this._resource3;
                IntPtr invoke_impl3 = createFunction3.invoke_impl;
                IntPtr method3 = createFunction3.method;
                this._constructedObject = method_code3;
            }
            long num2 = 0L;
            if (createFunction3 != null)
            {
                Monitor.Exit(lockObject);
            }
            if (num2 == 0L)
            {
                return true;
            }
            throw new OutOfMemoryException();
        }
References System.Object.Object(), Microsoft.Xna.Framework.Content.ThreadContentRequest._createFunction, Microsoft.Xna.Framework.Content.ThreadContentRequest._createFunction2, Microsoft.Xna.Framework.Content.ThreadContentRequest._createFunction3, Microsoft.Xna.Framework.Content.ThreadContentRequest._loadRequest, Microsoft.Xna.Framework.Content.ThreadContentRequest._loadRequest2, Microsoft.Xna.Framework.Content.ThreadContentRequest._loadRequest3, Microsoft.Xna.Framework.Content.ThreadContentRequest._lockObject, Microsoft.Xna.Framework.Content.ThreadContentRequest._resource, Microsoft.Xna.Framework.Content.ThreadContentRequest._resource2, Microsoft.Xna.Framework.Content.ThreadContentRequest._resource3, UnityEngine.ResourceRequest.asset, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), UnityEngine.AsyncOperation.isDone, j__TPar, and System.L.