terraria-cpp2il-methodrecon: GUIString.Draw
Draw() [5/5]
static void GUIString.Draw (String_Layout layout, TextSnippet[] textSnippets, [Out] int snippetSelected, float maxWidth = -1f, int maxLines = 100) inline static
Definition at line 12 of file GUIString.cs.
    {
        ControlAnchor.ControlId anchorControl = layout.AnchorControl;
        Vector2 location = layout.Location;
        float x = layout.Location.X;
        float y = layout.Location.Y;
        SpriteFont font = layout.GetFont();
        float scale = layout.Scale;
        LayoutCalculator.AnchorType alignment = layout.Alignment;
        SpriteFont font2 = layout.GetFont();
        if (!true)
        {
        }
        if (!true)
        {
        }
        float scale2 = layout.Scale;
        if (!true)
        {
        }
    }
References j__TPar.
Referenced by GUIReturnToTouch.Draw(), Draw(), Draw(), and GUIResearch.DrawItemProgress().