terraria-cpp2il-methodrecon: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
Throw() [1/2]
void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () inline
Definition at line 65 of file ExceptionDispatchInfo.cs.
        {
            /*
An exception occurred when decompiling this method (060021EB)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void System.Runtime.ExceptionServices.ExceptionDispatchInfo::Throw()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    call:void(Exception::RestoreExceptionDispatchInfo, ldfld:Exception(ExceptionDispatchInfo::m_Exception, ldloc:ExceptionDispatchInfo(this)), ldloc:ExceptionDispatchInfo(this))
    stloc:Exception(var_0_12, ldfld:Exception(ExceptionDispatchInfo::m_Exception, ldloc:ExceptionDispatchInfo(this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by System.Net.FtpWebRequest.BeginGetRequestStream(), System.Net.FtpWebRequest.BeginGetResponse(), System.Net.FtpWebRequest.CheckError(), Mono.Net.Security.MobileAuthenticatedStream.CheckThrow(), System.Net.FtpWebRequest.DataStreamClosed(), System.Net.FtpWebRequest.EndGetRequestStream(), System.Net.FtpWebRequest.EndGetResponse(), System.Runtime.InteropServices.Marshal.GetCustomMarshalerInstance(), System.Net.FtpWebRequest.GetRequestStream(), System.Threading.Tasks.RendezvousAwaitable< TResult >.GetResult(), Mono.Net.Security.MobileAuthenticatedStream.ProcessRead(), Mono.Net.Security.MobileAuthenticatedStream.ProcessWrite(), Internal.Runtime.Augments.RuntimeAugments.ReportUnhandledException(), and System.IO.Stream.SynchronousAsyncResult.ThrowIfError().