terraria-cpp2il-methodrecon: GUITransactionButton.GetRegion
GetRegion()
static Rectangle GUITransactionButton.GetRegion (TransactionButton_Layout layout) inline static
Definition at line 13 of file GUITransactionButton.cs.
    {
        if (true)
        {
            Rectangle rectangle;
            return rectangle;
        }
        Microsoft.Xna.Framework.Graphics.Texture2D texture2D;
        RenderTexture unityRenderTexture = texture2D._unityRenderTexture;
        Rectangle rectangle2;
        return rectangle2;
    }
References j__TPar.
Referenced by GUIWiresUI.CalculateRegion(), GUIBuilderAccToggles.Draw(), GUIPVPIcons.DrawTeamGrid(), GUIAccessoryInfoToggles.DrawToggles(), GUIEquipmentLoadout.DrawToggles(), GUIControllerChat.GetSelectedItemRegion(), GUIControllerJourneyModeSettings.GetSelectedItemRegion(), GUIControllerMappingOverlay.GetSelectedItemRegion(), GUIControllerSettingsOverlay.GetSelectedItemRegion(), GUIResearch.IsOver(), and GUIWiresUI.ItemDraw().