terraria-cpp2il-methodrecon: InControl.InputDeviceProfile.LeftStickRightMapping
LeftStickRightMapping()
static InputControlMapping InControl.InputDeviceProfile.LeftStickRightMapping (int analog) inline static protected inherited
Definition at line 549 of file InputDeviceProfile.cs.
        {
            /*
An exception occurred when decompiling this method (06000293)
ICSharpCode.Decompiler.DecompilerException: Error decompiling InControl.InputControlMapping InControl.InputDeviceProfile::LeftStickRightMapping(System.Int32)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    IL_0000:
    brtrue(IL_0000, ldstr:string[exp:bool]("Left Stick Right"))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1846
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by InControl.NativeDeviceProfiles.AppleMFiExtendedGamepadNativeProfile.Define(), InControl.NativeDeviceProfiles.DualShock4MFiNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF310ModeDMacNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF510ModeDMacNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF710ModeDMacNativeProfile.Define(), InControl.NativeDeviceProfiles.PlayStation3MacNativeProfile.Define(), InControl.NativeDeviceProfiles.PlayStation4MacNativeProfile.Define(), InControl.NativeDeviceProfiles.Xbox360DriverMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneDriverMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneMFiNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneSMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XInputWindowsNativeProfile.Define(), InControl.UnityDeviceProfiles.AirFloWiredPS3MacUnityProfile.Define(), InControl.UnityDeviceProfiles.AmazonFireTVUnityProfile.Define(), InControl.UnityDeviceProfiles.AndroidTVAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.AndroidTVUnityProfile.Define(), InControl.UnityDeviceProfiles.AppleMFiUnityProfile.Define(), InControl.UnityDeviceProfiles.AppleTVRemoteUnityProfile.Define(), InControl.UnityDeviceProfiles.AppleTVWirelessControllerUnityProfile.Define(), InControl.UnityDeviceProfiles.BeboncoolDA015CAAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BetopBTP2175sWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.BetopBTPAX1TAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BetopBTPGenericAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BTC938AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.DroidBoxPS3AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.DroidBoxXboxAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EasySmxEsm9101AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoFC30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoGenericAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoN30Pro2AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoNES30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSF30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSN30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.ExecutionerXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.ExecutionerXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.FixXBG301AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.FlareAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.FlarePlayAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameCubeWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.GameSirG3sAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameSirG3wAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameSirG4sAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameStickLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.GameStickUnityProfile.Define(), InControl.UnityDeviceProfiles.GenericAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GenericBlackBerryUnityProfile.Define(), InControl.UnityDeviceProfiles.GenericLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.GoogleStadiaUnityProfile.Define(), InControl.UnityDeviceProfiles.GreenThrottleAtlasAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.HamaBlackForceWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.HavitHVG95WLinuxProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9021AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9023AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9025AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9055AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9068AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.LevelUpBlackHawkWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeDMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeDMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710MacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechModeDAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechModeXAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechWingManWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.MadCatzCTRLRAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.MadCatzCTRLRAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MadCatzMicroCTRLRAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.MaxFireBlaze5WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaHeroPowerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProMacUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProPowerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NatecGenesisP44WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerMacUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShield2016AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShield2017AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindows10UnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindows81UnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NykoPlayPadProAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.OuyaAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.OuyaLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.OuyaWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation2LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation2WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3BWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3MacUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3ShenghicWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4AmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4AndroidXperiaZ5UnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacBluetoothUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacUSBUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4SteamLinkMacUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4TouchpadAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStationVitaPSMUnityProfile.Define(), InControl.UnityDeviceProfiles.RazerServalForgeTVUnityProfile.Define(), InControl.UnityDeviceProfiles.RazerServalMacUnityProfile.Define(), InControl.UnityDeviceProfiles.RedSamuraiAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SaitekAviatorWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.SamsungGP20AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SpeedlinkStrikeMacUnityProfile.Define(), InControl.UnityDeviceProfiles.SpeedlinkStrikeWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeMacUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesStratusXLAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesStratusXLWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.ValveStreamingWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360AmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360MacUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360RockCandyAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneBluetoothAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneMacUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.XiamoiWindowsUnityProfile.Define(), and InControl.UnityDeviceProfiles.XiaomiMacUnityProfile.Define().