terraria-cpp2il-methodrecon: InControl.InputDeviceProfile.Button
Button()
static InputControlSource InControl.InputDeviceProfile.Button (int index) inline static protected inherited
Definition at line 510 of file InputDeviceProfile.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by InControl.NativeDeviceProfiles.AfterglowXbox360WindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.AirFloPS3WindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.AppleMFiExtendedGamepadNativeProfile.Define(), InControl.NativeDeviceProfiles.AppleMFiMicroGamepadNativeProfile.Define(), InControl.NativeDeviceProfiles.BuffaloClassicMacNativeProfile.Define(), InControl.NativeDeviceProfiles.BuffaloClassicWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.DualShock4MFiNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoNES30ProBTMacNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoNES30ProUSBMacNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoNES30ProWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoSF30ProWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoSFC30MacNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoSFC30WindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.EightBitdoSNES30WindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.GameCubeMayflashWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.GameCubeWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.GoogleStadiaMacNativeProfile.Define(), InControl.NativeDeviceProfiles.GoogleStadiaWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.KiwitataNESWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF310ModeDMacNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF310ModeDWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF310ModeXWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF510ModeDMacNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF510ModeDWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF510ModeXWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF710ModeDMacNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF710ModeDWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.LogitechF710ModeXWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.NintendoSwitchProMacNativeProfile.Define(), InControl.NativeDeviceProfiles.NintendoSwitchProWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.NVidiaShieldWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.OUYAWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.PCTWINSHOCKWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.PlayStation3MacNativeProfile.Define(), InControl.NativeDeviceProfiles.PlayStation4MacNativeProfile.Define(), InControl.NativeDeviceProfiles.PlayStation4WindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.PowerANintendoSwitchMacNativeProfile.Define(), InControl.NativeDeviceProfiles.RazerServalWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.SteamWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.SteelseriesNimbusMacNativeProfile.Define(), InControl.NativeDeviceProfiles.Xbox360DriverMacNativeProfile.Define(), InControl.NativeDeviceProfiles.Xbox360WiredWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.Xbox360WirelessWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneDriverMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneEliteWindows10AENativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneEliteWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneMFiNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneSMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneWindows10AENativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneWindows10NativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneWirelessAdapterWindowsNativeProfile.Define(), InControl.NativeDeviceProfiles.XInputWindowsNativeProfile.Define(), InControl.UnityDeviceProfiles.AirFloWiredPS3MacUnityProfile.Define(), InControl.UnityDeviceProfiles.AmazonFireTVRemoteUnityProfile.Define(), InControl.UnityDeviceProfiles.AmazonFireTVUnityProfile.Define(), InControl.UnityDeviceProfiles.AndroidTVAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.AndroidTVMiBoxRemoteUnityProfile.Define(), InControl.UnityDeviceProfiles.AndroidTVRemoteUnityProfile.Define(), InControl.UnityDeviceProfiles.AndroidTVUnityProfile.Define(), InControl.UnityDeviceProfiles.AppleMFiUnityProfile.Define(), InControl.UnityDeviceProfiles.AppleTVRemoteUnityProfile.Define(), InControl.UnityDeviceProfiles.AppleTVWirelessControllerUnityProfile.Define(), InControl.UnityDeviceProfiles.BeboncoolDA015CAAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BetopBTP2175sWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.BetopBTPAX1TAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BetopBTPGenericAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BTC938AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.BuffaloClassicAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.BuffaloClassicMacUnityProfile.Define(), InControl.UnityDeviceProfiles.BuffaloClassicWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.DroidBoxPS3AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.DroidBoxXboxAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EasySmxEsm9101AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoFC30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoGenericAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoN30Pro2AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoNES30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoNES30ProMacUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoNES30ProWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSF30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSFC30AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSFC30MacUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSFC30WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSN30ProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSNES30AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSNES30MacUnityProfile.Define(), InControl.UnityDeviceProfiles.EightBitdoSNES30WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.ExecutionerXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.ExecutionerXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.FixXBG301AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.FlareAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.FlarePlayAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameCubeMayflashWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.GameCubeWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.GameSirG3sAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameSirG3wAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameSirG4sAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GameStickLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.GameStickUnityProfile.Define(), InControl.UnityDeviceProfiles.GenericAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.GenericBlackBerryUnityProfile.Define(), InControl.UnityDeviceProfiles.GenericLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.GoogleStadiaMacUnityProfile.Define(), InControl.UnityDeviceProfiles.GoogleStadiaUnityProfile.Define(), InControl.UnityDeviceProfiles.GoogleStadiaWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.GreenThrottleAtlasAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.HamaBlackForceWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.HavitHVG95WLinuxProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9021AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9023AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9025AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9055AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.IpegaPG9068AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.LevelUpBlackHawkWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeDMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeDMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710MacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechModeDAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechModeXAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechWingManWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.MadCatzCTRLRAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.MadCatzCTRLRAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MadCatzMicroCTRLRAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.MaxFireBlaze5WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaHeroPowerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProMacUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProPowerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NatecGenesisP44WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerMacUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerRemoteAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NintendoSwitchProAndroidProfile.Define(), InControl.UnityDeviceProfiles.NintendoSwitchProMacChromeUnityProfile.Define(), InControl.UnityDeviceProfiles.NintendoSwitchProWindowsChromeUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShield2016AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShield2017AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NvidiaShieldRemoteAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindows10UnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindows81UnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NykoPlayPadProAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.OuyaAmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.OuyaLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.OuyaWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation2LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation2WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3BWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3MacUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3ShenghicWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4AmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4AndroidXperiaZ5UnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacBluetoothUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacChromeUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacFirefoxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacUSBUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4SteamLinkMacUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4TouchpadAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4UnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4WindowsChromeUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4WindowsFirefoxUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStationVitaPSMUnityProfile.Define(), InControl.UnityDeviceProfiles.RazerServalForgeTVUnityProfile.Define(), InControl.UnityDeviceProfiles.RazerServalMacUnityProfile.Define(), InControl.UnityDeviceProfiles.RedSamuraiAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SaitekAviatorWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.SamsungGP20AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SpeedlinkStrikeMacUnityProfile.Define(), InControl.UnityDeviceProfiles.SpeedlinkStrikeWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeLinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeMacUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesFreeWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesStratusXLAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesStratusXLWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.ValveStreamingWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360AmazonUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360LinuxUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360MacChromeUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360MacFirefoxUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360MacSafariUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360MacUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360RockCandyAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneBluetoothAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneMacChromeUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneMacFirefoxUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneMacSafariUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneMacUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneWindows10AEUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.XiamoiWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.XiaomiMacUnityProfile.Define(), InControl.UnityDeviceProfiles.XInputWindowsChromeUnityProfile.Define(), and InControl.UnityDeviceProfiles.XInputWindowsFirefoxUnityProfile.Define().