terraria-cpp2il-methodrecon: InControl.InputDeviceProfile.RightTriggerMapping
RightTriggerMapping()
static InputControlMapping InControl.InputDeviceProfile.RightTriggerMapping (int analog) inline static protected inherited
Definition at line 873 of file InputDeviceProfile.cs.
        {
            /*
An exception occurred when decompiling this method (0600029F)
ICSharpCode.Decompiler.DecompilerException: Error decompiling InControl.InputControlMapping InControl.InputDeviceProfile::RightTriggerMapping(System.Int32)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    IL_0000:
    brtrue(IL_0000, ldstr:string[exp:bool]("Right Trigger"))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1846
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by InControl.NativeDeviceProfiles.PlayStation4MacNativeProfile.Define(), InControl.NativeDeviceProfiles.Xbox360DriverMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneDriverMacNativeProfile.Define(), InControl.NativeDeviceProfiles.XboxOneSMacNativeProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeXMacUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaHeroPowerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.MogaProPowerAndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacBluetoothUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4MacUSBUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4SteamLinkMacUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360MacUnityProfile.Define(), and InControl.UnityDeviceProfiles.XboxOneMacUnityProfile.Define().