terraria-cpp2il-methodrecon: InControl.InputDeviceProfile.DPadUpMapping2
DPadUpMapping2()
static InputControlMapping InControl.InputDeviceProfile.DPadUpMapping2 (int analog) inline static protected inherited
Definition at line 990 of file InputDeviceProfile.cs.
        {
            /*
An exception occurred when decompiling this method (060002A4)
ICSharpCode.Decompiler.DecompilerException: Error decompiling InControl.InputControlMapping InControl.InputDeviceProfile::DPadUpMapping2(System.Int32)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    IL_0000:
    brtrue(IL_0000, ldstr:string[exp:bool]("DPad Up"))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1846
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by InControl.UnityDeviceProfiles.BetopBTP2175sWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF310ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF510ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710ModeDWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.LogitechF710ModeXWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.MaxFireBlaze5WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NexusPlayerWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindows10UnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindows81UnityProfile.Define(), InControl.UnityDeviceProfiles.NVidiaShieldWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation3WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStationVitaPSMUnityProfile.Define(), InControl.UnityDeviceProfiles.SteelSeriesStratusXLWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.ValveStreamingWindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.Xbox360WindowsUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneUnityProfile.Define(), InControl.UnityDeviceProfiles.XboxOneWindowsUnityProfile.Define(), and InControl.UnityDeviceProfiles.XiamoiWindowsUnityProfile.Define().