terraria-cpp2il-methodrecon: System.Net.WebClient.DownloadFile
DownloadFile() [1/2]
void System.Net.WebClient.DownloadFile (global::System::Uri address, string fileName) inline
Definition at line 844 of file WebClient.cs.
        {
            if (!true)
            {
            }
            WebClient.ThrowIfNull(address, "address");
            WebClient.ThrowIfNull(fileName, "fileName");
            this.StartOperation();
            global::System.Uri uri = this.GetUri(address);
            this._webRequest = this;
            long num = 0L;
            if (!true)
            {
                File.Delete(fileName);
            }
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.IO.File.Delete(), System.Net.WebClient.GetUri(), j__TPar, System.L, System.Net.WebClient.StartOperation(), and System.Net.WebClient.ThrowIfNull().