terraria-cpp2il-methodrecon: System.Net.WebClient.UploadFile
UploadFile() [2/4]
byte[] System.Net.WebClient.UploadFile (global::System::Uri address, string method, string fileName) inline
Definition at line 1029 of file WebClient.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            WebClient.ThrowIfNull(address, "address");
            WebClient.ThrowIfNull(fileName, "fileName");
            string text;
            if (method == null)
            {
                text = this.MapToDefaultMethod(address);
            }
            this.StartOperation();
            this._method = text;
            string scheme = this.GetUri(address).Scheme;
            if (num == 0)
            {
            }
            this._webRequest = this;
            byte[] array;
            return array;
        }
References System.array, System.Net.WebClient.GetUri(), j__TPar, System.Net.WebClient.MapToDefaultMethod(), System.Uri.Scheme, System.Net.WebClient.StartOperation(), System.text, and System.Net.WebClient.ThrowIfNull().