terraria-cpp2il-methodrecon: System.Net.WebClient.GetUri
GetUri() [2/2]
global.System.Uri System.Net.WebClient.GetUri (string address) inline private
Definition at line 1218 of file WebClient.cs.
        {
            if (!true)
            {
            }
            WebClient.ThrowIfNull(address, "address");
            global::System.Uri baseAddress = this._baseAddress;
            if (!true)
            {
            }
            global::System.Uri baseAddress2 = this._baseAddress;
            if (!true)
            {
            }
            if (!true)
            {
            }
            string fullPath = Path.GetFullPath(address);
            global::System.Uri uri;
            return uri;
        }
References System.Uri.Uri(), System.Net.WebClient._baseAddress, System.IO.Path.GetFullPath(), j__TPar, and System.Net.WebClient.ThrowIfNull().
Referenced by System.Net.WebClient.DownloadData(), System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadDataInternal(), System.Net.WebClient.DownloadDataTaskAsync(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadFileTaskAsync(), System.Net.WebClient.DownloadString(), System.Net.WebClient.DownloadStringAsync(), System.Net.WebClient.DownloadStringTaskAsync(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenReadTaskAsync(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.OpenWriteTaskAsync(), System.Net.WebClient.OpenWriteTaskAsync(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadDataInternal(), System.Net.WebClient.UploadDataTaskAsync(), System.Net.WebClient.UploadDataTaskAsync(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadFileTaskAsync(), System.Net.WebClient.UploadFileTaskAsync(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadStringAsync(), System.Net.WebClient.UploadStringTaskAsync(), System.Net.WebClient.UploadStringTaskAsync(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValuesAsync(), System.Net.WebClient.UploadValuesTaskAsync(), and System.Net.WebClient.UploadValuesTaskAsync().