terraria-cpp2il-methodrecon: System.Net.WebClient.StartAsyncOperation
StartAsyncOperation()
global.System.ComponentModel.AsyncOperation System.Net.WebClient.StartAsyncOperation (object userToken) inline private
Definition at line 419 of file WebClient.cs.
        {
            if (!this._initWebClientAsync)
            {
                this._initWebClientAsync = true;
            }
            global::System.ComponentModel.AsyncOperation asyncOperation = global::System.ComponentModel.AsyncOperationManager.CreateOperation(userToken);
            this.StartOperation();
            this._asyncOp = asyncOperation;
            return asyncOperation;
        }
References System.Net.WebClient._initWebClientAsync, j__TPar, and System.Net.WebClient.StartOperation().
Referenced by System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadStringAsync(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadStringAsync(), and System.Net.WebClient.UploadValuesAsync().