terraria-cpp2il-methodrecon: System.Net.WebClient.ThrowIfNull
ThrowIfNull()
static void System.Net.WebClient.ThrowIfNull (object argument, string parameterName) inline static private
Definition at line 2026 of file WebClient.cs.
        {
            while (argument == null)
            {
            }
        }
Referenced by System.Net.WebClient.DownloadData(), System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadString(), System.Net.WebClient.DownloadStringAsync(), System.Net.WebClient.GetUri(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadStringAsync(), System.Net.WebClient.UploadValues(), and System.Net.WebClient.UploadValuesAsync().