terraria-cpp2il-methodrecon: InControl.TestInputManager.DrawUnityInputDebugger
DrawUnityInputDebugger()
void InControl.TestInputManager.DrawUnityInputDebugger () inline private
Definition at line 109 of file TestInputManager.cs.
        {
            int width = Screen.width;
            string[] joystickNames = Input.GetJoystickNames();
            string text;
            if (("Joystick " == null || "Joystick " != null) && (text == null || text != null) && (": \"" == null || ": \"" != null) && ": \"" != null)
            {
                string text2;
                string text3;
                bool key = Input.GetKey("joystick " + text2 + " button " + text3);
                string text5;
                string text4 = "Buttons: " + "B" + text5 + "  ";
                string text6;
                string text7;
                float axisRaw = Input.GetAxisRaw("joystick " + text6 + " analog " + text7);
                if ("joystick " == null)
                {
                }
                string text8;
                string text9;
                if (("Analogs: " == null || "Analogs: " != null) && ("A" == null || "A" != null) && (text8 == null || text8 != null) && (": " == null || ": " != null) && (text9 == null || text9 != null) && ("  " == null || "  " != null))
                {
                    return;
                }
            }
            throw new ArrayTypeMismatchException();
        }
References UnityEngine.Input.GetAxisRaw(), UnityEngine.Input.GetJoystickNames(), UnityEngine.Input.GetKey(), j__TPar, System.key, System.text, and UnityEngine.Screen.width.