terraria-cpp2il-methodrecon: System.Net.HttpWebRequest.SetSpecialHeaders
SetSpecialHeaders()
void System.Net.HttpWebRequest.SetSpecialHeaders (string HeaderName, string value) inline private
Definition at line 99 of file HttpWebRequest.cs.
        {
            if (!true)
            {
            }
            string text = WebHeaderCollection.CheckBadChars(value, true);
            this.webHeaders.RemoveInternal(HeaderName);
            if (text._stringLength != 0)
            {
                this.webHeaders.AddInternal(HeaderName, text);
                return;
            }
        }
References System.Net.WebHeaderCollection.AddInternal(), System.Net.WebHeaderCollection.CheckBadChars(), System.Net.WebHeaderCollection.RemoveInternal(), System.text, System.value, and System.Net.HttpWebRequest.webHeaders.
Referenced by System.Net.HttpWebRequest.SetDateHeaderHelper().