terraria-cpp2il-methodrecon: System.Net.HttpWebRequest.MyGetRequestStreamAsync
MyGetRequestStreamAsync()
Task< Stream > System.Net.HttpWebRequest.MyGetRequestStreamAsync (CancellationToken cancellationToken) inline private
Definition at line 1222 of file HttpWebRequest.cs.
        {
            int num4;
            do
            {
                bool flag = this.method == "GET";
                bool flag2 = this.method == "CONNECT";
                bool flag3 = this.method == "HEAD";
                bool flag4 = this.method == "TRACE";
                if (this.method == null)
                {
                    goto IL_00F2;
                }
                long num = this.contentLength;
                if (!this.sendChunked && !this.allowBuffering && this.keepAlive)
                {
                    goto IL_00FF;
                }
                string transferEncoding = this.TransferEncoding;
                if (transferEncoding != null && !this.sendChunked)
                {
                    bool flag5 = transferEncoding.Trim() != "";
                }
                object obj = this.locker;
                if (this.getResponseCalled)
                {
                    goto IL_00FF;
                }
                string text;
                if (this.currentOperation == null)
                {
                    text = this.method;
                    int num2 = 1;
                    this.gotRequestStream = num2 != 0;
                    this.initialMethod = text;
                }
                long num3 = 0L;
                num4 = 21;
                if (text != null)
                {
                    Monitor.Exit(obj);
                }
                if (num3 != 0L)
                {
                    goto IL_00F9;
                }
            }
            while (num4 != 0);
            WebOperation webOperation;
            return webOperation.GetRequestStream();
            IL_00F2:
            WebException ex = HttpWebRequest.CreateRequestAbortedException();
            IL_00F9:
            throw new OutOfMemoryException();
            IL_00FF:
            return "Content-Length not set";
        }
References System.Net.HttpWebRequest.allowBuffering, System.Net.HttpWebRequest.contentLength, System.Net.HttpWebRequest.CreateRequestAbortedException(), System.Net.HttpWebRequest.currentOperation, System.Threading.Monitor.Exit(), System.Net.WebOperation.GetRequestStream(), System.Net.HttpWebRequest.getResponseCalled, j__TPar, System.Net.HttpWebRequest.keepAlive, System.L, System.Net.HttpWebRequest.locker, System.Net.HttpWebRequest.method, System.obj, System.Net.HttpWebRequest.sendChunked, System.text, and System.Net.HttpWebRequest.TransferEncoding.