terraria-cpp2il-methodrecon: CSVWriter.CloseStreams
CloseStreams()
void CSVWriter.CloseStreams () inline private
Definition at line 50 of file CSVWriter.cs.
    {
        if (this._open)
        {
            StreamWriter writer = this._writer;
            MemoryStream memoryStream = this._memoryStream;
            StreamWriter writer2 = this._writer;
            this.SaveData = memoryStream;
            string outputFile = this._outputFile;
            if (outputFile != null)
            {
                byte[] saveData = this.SaveData;
                File.WriteAllBytes(outputFile, saveData);
                return;
            }
        }
    }
References _memoryStream, _open, _outputFile, _writer, j__TPar, SaveData, and System.IO.File.WriteAllBytes().
Referenced by Close(), and Finalize().