terraria-cpp2il-methodrecon: UnityEngine.AndroidReflection.AndroidReflection
AndroidReflection()
static UnityEngine.AndroidReflection.AndroidReflection () inline static private
Definition at line 134 of file AndroidReflection.cs.
        {
            IntPtr intPtr = AndroidJNISafe.FindClass("com/unity3d/player/ReflectionHelper");
            IntPtr staticMethodID = AndroidReflection.GetStaticMethodID("com/unity3d/player/ReflectionHelper", "getConstructorID", "(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Constructor;");
            IntPtr staticMethodID2 = AndroidReflection.GetStaticMethodID("com/unity3d/player/ReflectionHelper", "getMethodID", "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/reflect/Method;");
            IntPtr staticMethodID3 = AndroidReflection.GetStaticMethodID("com/unity3d/player/ReflectionHelper", "getFieldID", "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/reflect/Field;");
            IntPtr staticMethodID4 = AndroidReflection.GetStaticMethodID("com/unity3d/player/ReflectionHelper", "getFieldSignature", "(Ljava/lang/reflect/Field;)Ljava/lang/String;");
            IntPtr staticMethodID5 = AndroidReflection.GetStaticMethodID("com/unity3d/player/ReflectionHelper", "newProxyInstance", "(JLjava/lang/Class;)Ljava/lang/Object;");
            IntPtr staticMethodID6 = AndroidReflection.GetStaticMethodID("com/unity3d/player/ReflectionHelper", "setNativeExceptionOnProxy", "(Ljava/lang/Object;JZ)V");
            IntPtr methodID = AndroidReflection.GetMethodID("java/lang/reflect/Field", "getDeclaringClass", "()Ljava/lang/Class;");
        }
References UnityEngine.AndroidJNISafe.FindClass(), UnityEngine.AndroidReflection.GetMethodID(), UnityEngine.AndroidReflection.GetStaticMethodID(), and j__TPar.