terraria-cpp2il-methodrecon: System.Exception.ToString
ToString() [2/2]
string System.Exception.ToString (bool needFileLineInfo, bool needMessage) inline private inherited
Definition at line 221 of file Exception.cs.
        {
            if (this != null)
            {
                string className = this._className;
                string className2 = this.GetClassName();
                string text;
                return text;
            }
            string className3 = this.GetClassName();
            long num;
            if (this._innerException != null)
            {
                if ((className3 == null || className3 != null) && (" ---> " == null || " ---> " != null))
                {
                    Exception innerException = this._innerException;
                    string text2;
                    if (text2 == null || text2 != null)
                    {
                        string newLine = Environment.NewLine;
                        if ((newLine == null || newLine != null) && ("   " == null || "   " != null))
{
                            string resourceString = Environment.GetResourceString("--- End of inner exception stack trace ---");
                            if (resourceString == null || resourceString != null)
{
                                num = 0L;
                                goto IL_0083;
                            }
                        }
                    }
                }
                throw new ArrayTypeMismatchException();
            }
            IL_0083:
            string stackTrace = this.GetStackTrace(num != 0L);
            string text3;
            if (stackTrace != null)
            {
                string newLine2 = Environment.NewLine;
                return text3 + newLine2 + stackTrace;
            }
            return text3;
        }
References System.Exception._className, System.Exception._innerException, System.Exception.GetClassName(), System.Environment.GetResourceString(), System.Exception.GetStackTrace(), j__TPar, System.L, System.Environment.NewLine, and System.text.