terraria-cpp2il-methodrecon: System.Exception.GetObjectData
GetObjectData()
virtual void System.Exception.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual inherited
Implements System.Runtime.Serialization.ISerializable.
Reimplemented in System.AggregateException, System.ArgumentException, System.ArgumentOutOfRangeException, System.BadImageFormatException, System.Globalization.CultureNotFoundException, System.IO.FileLoadException, System.IO.FileNotFoundException, System.MissingMemberException, System.ObjectDisposedException, System.Reflection.ReflectionTypeLoadException, System.Runtime.CompilerServices.RuntimeWrappedException, System.Security.SecurityException, System.TypeInitializationException, System.TypeLoadException, System.Xml.Schema.XmlSchemaException, System.Xml.XmlException, System.ComponentModel.LicenseException, System.ComponentModel.WarningException, System.ComponentModel.Win32Exception, System.Text.RegularExpressions.RegexMatchTimeoutException, System.Net.CookieException, System.Net.CookieException, System.Net.ProtocolViolationException, System.Net.ProtocolViolationException, System.Net.WebException, System.Net.WebException, and System.UriFormatException.
Definition at line 266 of file Exception.cs.
        {
            while (info == null)
            {
            }
            string stackTrace;
            if (this._stackTraceString == null && this._stackTrace != null)
            {
                stackTrace = Environment.GetStackTrace(this, true);
            }
            if (this._source == null)
            {
                this._source = this;
            }
            string className = this.GetClassName();
            Type type;
            info.AddValue("ClassName", className, type);
            string message = this._message;
            Type type2;
            info.AddValue("Message", message, type2);
            IDictionary data = this._data;
            Exception innerException = this._innerException;
            Type type3;
            info.AddValue("InnerException", innerException, type3);
            string helpURL = this._helpURL;
            Type type4;
            info.AddValue("HelpURL", helpURL, type4);
            Type type5;
            info.AddValue("StackTraceString", stackTrace, type5);
            string remoteStackTraceString = this._remoteStackTraceString;
            Type type6;
            info.AddValue("RemoteStackTraceString", remoteStackTraceString, type6);
            int remoteStackIndex = this._remoteStackIndex;
            long num = 0L;
            info.AddValue("ExceptionMethod", num);
            int hresult = this._HResult;
            info.AddValue("HResult", hresult);
            string source = this._source;
            Type type7;
            info.AddValue("Source", source, type7);
            SafeSerializationManager safeSerializationManager = this._safeSerializationManager;
            if (safeSerializationManager != null)
            {
                bool isActive = safeSerializationManager.IsActive;
                SafeSerializationManager safeSerializationManager2 = this._safeSerializationManager;
                Type type8;
                info.AddValue("SafeSerializationManager", safeSerializationManager2, type8);
                SafeSerializationManager safeSerializationManager3 = this._safeSerializationManager;
            }
        }
References System.Exception._data, System.Exception._helpURL, System.Exception._HResult, System.Exception._innerException, System.Exception._message, System.Exception._remoteStackIndex, System.Exception._remoteStackTraceString, System.Exception._safeSerializationManager, System.Exception._source, System.Exception._stackTrace, System.Exception._stackTraceString, System.Runtime.Serialization.SerializationInfo.AddValue(), System.Exception.GetClassName(), System.Environment.GetStackTrace(), System.info, System.Runtime.Serialization.SafeSerializationManager.IsActive, j__TPar, System.L, and System.source.