terraria-cpp2il-methodrecon: System.Threading.Interlocked.CompareExchange
CompareExchange() [3/8]
static int System.Threading.Interlocked.CompareExchange (int location1, int value, int comparand) inline static
Definition at line 14 of file Interlocked.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by System.Net.HttpWebRequest.Abort(), Mono.SystemCertificateProvider.EnsureInitialized(), System.Net.WebOperation.Finish(), System.Net.HttpWebRequest.GetWebException(), Mono.Net.Security.AsyncProtocolRequest.d__23.MoveNext(), System.Net.WebResponseStream.d__40.MoveNext(), System.Net.TimerThread.Prod(), System.Net.ServicePointScheduler.Run(), and System.Net.TimerThread.ThreadProc().