terraria-cpp2il-methodrecon: System.Threading.Tasks.TaskToApm.End
End()
static void System.Threading.Tasks.TaskToApm.End (IAsyncResult asyncResult) inline static
Definition at line 38 of file TaskToApm.cs.
        {
            while (asyncResult == null || asyncResult == null)
            {
            }
        }
Referenced by System.Net.Security.SslStream.EndAuthenticateAsClient(), System.Security.Cryptography.CryptoStream.EndRead(), System.IO.Compression.GZipStream.EndRead(), System.Net.Security.SslStream.EndRead(), System.Net.WebConnectionStream.EndRead(), System.Net.WebReadStream.EndRead(), System.Security.Cryptography.CryptoStream.EndWrite(), System.IO.Compression.GZipStream.EndWrite(), System.Net.Security.SslStream.EndWrite(), and System.Net.WebConnectionStream.EndWrite().