terraria-cpp2il-methodrecon: System.Security.Cryptography.TripleDES.IsWeakKey
IsWeakKey()
static bool System.Security.Cryptography.TripleDES.IsWeakKey (byte[] rgbKey) inline static
Definition at line 82 of file TripleDES.cs.
        {
            if (!true)
            {
            }
            long num = 0L;
            byte[] array;
            bool flag = TripleDES.EqualBytes(array, (int)num, 8, 8);
            return true;
        }
References System.array, System.Security.Cryptography.TripleDES.EqualBytes(), and System.L.
Referenced by System.Security.Cryptography.TripleDESTransform.TripleDESTransform(), System.Security.Cryptography.TripleDESCryptoServiceProvider.GenerateKey(), and System.Security.Cryptography.TripleDESTransform.GetStrongKey().