terraria-cpp2il-methodrecon: Terraria.GameContent.UI.Chat.MobileChatMonitor.NewTextInternal
NewTextInternal()
void Terraria.GameContent.UI.Chat.MobileChatMonitor.NewTextInternal (string newText, byte R = 255, byte G = 255, byte B = 255, bool force = false) inline
Definition at line 84 of file MobileChatMonitor.cs.
        {
            int num = this.numChatLines;
            ChatLine[] array = this.chatLine;
            ChatLine[] array2 = this.chatLine;
            array2.parsedText.Text = array2;
            ChatLine[] array3 = this.chatLine;
            array3.parsedText.TextOriginal = newText;
            TextSnippet[] parsedText = array3.parsedText;
            string textOriginal = parsedText.TextOriginal;
            string text = parsedText.Text;
            TextSnippet[] array4;
            parsedText.Color = array4;
            TextSnippet[] parsedText2 = this.chatLine.parsedText;
            string textOriginal2 = parsedText2.TextOriginal;
            string text2 = parsedText2.Text;
            TextSnippet[] array5;
            parsedText2.CheckForHover = array5 != null;
            TextSnippet[] parsedText3 = this.chatLine.parsedText;
            string textOriginal3 = parsedText3.TextOriginal;
            string text3 = parsedText3.Text;
            ChatLine[] array6 = this.chatLine;
            int num2 = this.chatLength;
            Color color = array6.parsedText.Color;
            TextSnippet[] parsedText4 = this.chatLine.parsedText;
            Color color2 = this.chatLine.parsedText.Color;
            Color color3 = this.chatLine.parsedText.Color;
            TextSnippet[] parsedText5 = this.chatLine.parsedText;
            int num3 = this.numChatItems;
            int num4 = this.numChatLines;
            this.numChatItems = num3;
            this.numChatItems = num4;
        }
References Microsoft.Xna.Framework.Graphics.Color.Color(), System.array, Terraria.GameContent.UI.Chat.MobileChatMonitor.chatLength, Terraria.GameContent.UI.Chat.MobileChatMonitor.chatLine, Terraria.UI.Chat.TextSnippet.Color, j__TPar, Terraria.GameContent.UI.Chat.MobileChatMonitor.numChatItems, Terraria.GameContent.UI.Chat.MobileChatMonitor.numChatLines, Terraria.UI.Chat.ChatLine.parsedText, System.text, Terraria.UI.Chat.TextSnippet.Text, and Terraria.UI.Chat.TextSnippet.TextOriginal.
Referenced by Terraria.GameContent.UI.Chat.MobileChatMonitor.NewText(), and Terraria.GameContent.UI.Chat.MobileChatMonitor.TrimIntoMultipleLines().