terraria-cpp2il-methodrecon: System.Xml.DtdParser.HandleEntityReference
HandleEntityReference() [2/2]
bool System.Xml.DtdParser.HandleEntityReference (XmlQualifiedName entityName, bool paramEntity, bool inLiteral, bool inAttribute) inline private
Definition at line 1622 of file DtdParser.cs.
        {
            SchemaEntity schemaEntity;
            do
            {
                int num = this.curPos;
                this.SaveParsingBuffer(num);
                if (this.externalEntitiesDepth == 0 && this.scanningFunction != DtdParser.ScanningFunction.SubsetContent && this.savedScanningFunction != DtdParser.ScanningFunction.SubsetContent)
                {
                    string name = entityName.name;
                    int num2 = this.curPos;
                    int stringLength = name._stringLength;
                    this.Throw(num, "A parameter entity reference is not allowed in internal markup.");
                }
            }
            while (schemaEntity == null);
            if (schemaEntity.parsingInProgress)
            {
                int stringLength2 = entityName.name._stringLength;
                int num3 = this.curPos;
            }
            if (schemaEntity.isExternal)
            {
                IDtdParserAdapter dtdParserAdapter = this.readerAdapter;
                if ("General entity '{0}' references itself." != null)
                {
                }
            }
            if (schemaEntity.text._stringLength != 0)
            {
                IDtdParserAdapter dtdParserAdapter2 = this.readerAdapter;
                if ("General entity '{0}' references itself." != null)
                {
                }
                int num4 = this.externalEntitiesDepth;
                this.externalEntitiesDepth = num4;
                this.currentEntityId = num4;
                DtdParser.ScanningFunction scanningFunction = this.scanningFunction;
                this.savedScanningFunction = scanningFunction;
                int num5 = 32;
                this.scanningFunction = (DtdParser.ScanningFunction)num5;
                this.LoadParsingBuffer();
                return;
            }
        }
References System.Xml.DtdParser.curPos, System.Xml.DtdParser.externalEntitiesDepth, System.Xml.Schema.SchemaEntity.isExternal, j__TPar, System.Xml.DtdParser.LoadParsingBuffer(), System.name, System.Xml.DtdParser.readerAdapter, System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.scanningFunction, System.Xml.Schema.SchemaEntity.text, and System.Xml.DtdParser.Throw().