terraria-cpp2il-methodrecon: System.Xml.DtdParser.GetToken
GetToken()
DtdParser.Token System.Xml.DtdParser.GetToken (bool needWhiteSpace) inline private
Definition at line 538 of file DtdParser.cs.
        {
            for (;;)
            {
                int num = 1;
                int num2 = 1;
                char[] array = this.chars;
                int num3 = this.curPos;
                if (num != 0)
                {
                    break;
                }
                int num4 = this.charsUsed;
                IDtdParserAdapter dtdParserAdapter = this.readerAdapter;
                this.whitespaceSeen = num2 != 0;
                DtdParser.ScanningFunction scanningFunction;
                if (scanningFunction != DtdParser.ScanningFunction.SubsetContent)
                {
                    int num5 = this.charsUsed;
                    IDtdParserAdapter dtdParserAdapter2 = this.readerAdapter;
                    if (scanningFunction != DtdParser.ScanningFunction.SubsetContent)
                    {
                    }
                    if (scanningFunction != DtdParser.ScanningFunction.SubsetContent)
                    {
                    }
                    int num6 = this.curPos;
                    char[] array2 = this.chars;
                    IDtdParserAdapter dtdParserAdapter3 = this.readerAdapter;
                    this.curPos = dtdParserAdapter2;
                    if (scanningFunction != DtdParser.ScanningFunction.SubsetContent)
                    {
                    }
                }
                IDtdParserAdapter dtdParserAdapter4 = this.readerAdapter;
                if (scanningFunction != DtdParser.ScanningFunction.SubsetContent)
                {
                }
                if (this.ReadData() == 0)
                {
                    goto Block_2;
                }
            }
            return "'{0}' is an unexpected token. Expecting white space.";
            Block_2:
            long num7 = 0L;
            bool flag = this.HandleEntityEnd(num7 != 0L);
            if (this.scanningFunction != DtdParser.ScanningFunction.SubsetContent)
            {
                int num8 = this.curPos;
                this.Throw(num8, "Incomplete DTD content.");
                if (!this.whitespaceSeen)
                {
                    DtdParser.ScanningFunction scanningFunction2 = this.scanningFunction;
                    int num9 = this.curPos;
                    string text;
                    this.Throw(num9, "'{0}' is an unexpected token. Expecting white space.", text);
                }
                int num10 = this.curPos;
                DtdParser.ScanningFunction scanningFunction3 = this.nextScaningFunction;
                int num11 = 1;
                this.tokenStartPos = num10;
                DtdParser.ScanningFunction scanningFunction4 = this.savedScanningFunction;
                this.whitespaceSeen = num11 != 0;
                this.scanningFunction = scanningFunction4;
                return this.ScanSubsetContent();
            }
            long num12 = 0L;
            this.ScanQName(num12 != 0L);
            DtdParser.ScanningFunction scanningFunction5 = this.nextScaningFunction;
            bool flag2 = this.supportNamespaces;
            this.ScanQName(flag2);
            DtdParser.ScanningFunction scanningFunction6 = this.nextScaningFunction;
            this.ScanNmtoken();
            DtdParser.ScanningFunction scanningFunction7 = this.nextScaningFunction;
            this.scanningFunction = scanningFunction7;
            return this.ScanDoctype1();
        }
References System.array, System.Xml.DtdParser.chars, System.Xml.DtdParser.charsUsed, System.Xml.DtdParser.curPos, System.Xml.DtdParser.HandleEntityEnd(), j__TPar, System.L, System.Xml.DtdParser.nextScaningFunction, System.Xml.DtdParser.ReadData(), System.Xml.DtdParser.readerAdapter, System.Xml.DtdParser.savedScanningFunction, System.Xml.DtdParser.ScanDoctype1(), System.Xml.DtdParser.scanningFunction, System.Xml.DtdParser.ScanNmtoken(), System.Xml.DtdParser.ScanQName(), System.Xml.DtdParser.ScanSubsetContent(), System.Xml.DtdParser.supportNamespaces, System.text, System.Xml.DtdParser.Throw(), and System.Xml.DtdParser.whitespaceSeen.
Referenced by System.Xml.DtdParser.ParseAttlistDecl(), System.Xml.DtdParser.ParseAttlistDefault(), System.Xml.DtdParser.ParseAttlistType(), System.Xml.DtdParser.ParseCondSection(), System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseExternalId(), System.Xml.DtdParser.ParseHowMany(), System.Xml.DtdParser.ParseInDocumentDtd(), and System.Xml.DtdParser.ParseNotationDecl().