terraria-cpp2il-methodrecon: System.Xml.DtdParser.Parse
Parse()
void System.Xml.DtdParser.Parse (bool saveInternalSubset) inline private
Definition at line 226 of file DtdParser.cs.
        {
            if (this.freeFloatingDtd)
            {
                this.ParseFreeFloatingDtd();
                return;
            }
            this.ParseInDocumentDtd(saveInternalSubset);
            this.schemaInfo.Finish();
            if (this.validate && this.undeclaredNotations != null)
            {
                string baseUriStr = this.BaseUriStr;
                return;
            }
        }
References System.Xml.DtdParser.BaseUriStr, System.Xml.Schema.SchemaInfo.Finish(), System.Xml.DtdParser.freeFloatingDtd, System.Xml.DtdParser.ParseFreeFloatingDtd(), System.Xml.DtdParser.ParseInDocumentDtd(), System.Xml.DtdParser.schemaInfo, System.Xml.DtdParser.undeclaredNotations, and System.Xml.DtdParser.validate.