terraria-cpp2il-methodrecon: System.Xml.DtdParser.ParseExternalId
ParseExternalId()
void System.Xml.DtdParser.ParseExternalId (DtdParser::Token idTokenType, DtdParser::Token declType, [Out] string publicId, [Out] string systemId) inline private
Definition at line 511 of file DtdParser.cs.
        {
            int lineNo = this.LineNo;
            int linePos = this.LinePos;
            int num = 1;
            DtdParser.Token token = this.GetToken(num != 0);
            int num2 = this.curPos;
            this.ThrowUnexpectedToken(num2, "\"", "'");
            string value = this.GetValue();
            int num3 = 35;
            int num4 = value.IndexOf((char)num3);
            int num5 = this.curPos;
            string text;
            if (text != null && text == null)
            {
                throw new ArrayTypeMismatchException();
            }
            if (!this.freeFloatingDtd)
            {
                int linePos2 = this.literalLineInfo.linePos;
                IDtdParserAdapter dtdParserAdapter = this.readerAdapter;
                this.literalLineInfo.linePos = linePos2;
                return;
            }
        }
References System.Xml.DtdParser.curPos, System.Xml.DtdParser.freeFloatingDtd, System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.GetValue(), j__TPar, System.Xml.DtdParser.LineNo, System.Xml.DtdParser.LinePos, System.Xml.LineInfo.linePos, System.Xml.DtdParser.literalLineInfo, System.Xml.DtdParser.readerAdapter, System.text, System.Xml.DtdParser.ThrowUnexpectedToken(), and System.value.