terraria-cpp2il-methodrecon: System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeData
GetTypeData()
ReflectTypeDescriptionProvider.ReflectedTypeData System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeData (Type type, bool createIfNeeded) inline private
Definition at line 466 of file ReflectTypeDescriptionProvider.cs.
        {
            for (;;)
            {
                Hashtable typeData = this._typeData;
                if (typeData != null && typeData != null)
                {
                    break;
                }
                Hashtable typeData2 = this._typeData;
                if (typeData2 == null)
                {
                    goto IL_0026;
                }
                if (typeData2 != null)
                {
                    goto Block_3;
                }
            }
            throw new InvalidCastException();
            Block_3:
            throw new InvalidCastException();
            IL_0026:
            long num;
            if (!false)
            {
                if (this._typeData == null)
                {
                }
                num = 0L;
            }
            if (num == 0L)
            {
            }
            throw new OutOfMemoryException();
        }
References System.ComponentModel.ReflectTypeDescriptionProvider._typeData, j__TPar, and System.L.
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.GetAttributes(), System.ComponentModel.ReflectTypeDescriptionProvider.GetComponentName(), System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(), System.ComponentModel.ReflectTypeDescriptionProvider.GetDefaultEvent(), System.ComponentModel.ReflectTypeDescriptionProvider.GetDefaultProperty(), System.ComponentModel.ReflectTypeDescriptionProvider.GetEditor(), System.ComponentModel.ReflectTypeDescriptionProvider.GetEvents(), System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedComponentName(), System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedConverter(), System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedEditor(), System.ComponentModel.ReflectTypeDescriptionProvider.GetProperties(), and System.ComponentModel.ReflectTypeDescriptionProvider.Refresh().