terraria-cpp2il-methodrecon: Terraria.UI.ItemSorting.SortInventory
SortInventory()
static void Terraria.UI.ItemSorting.SortInventory () inline static
Definition at line 38 of file ItemSorting.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Player localPlayer = Main.LocalPlayer;
            int num2 = 905;
            bool flag = localPlayer.HasItem(num2);
            if (num == 0)
            {
            }
            ItemSorting.SortCoins();
            if (num == 0)
            {
            }
            ItemSorting.SortAmmo();
            if (num == 0)
            {
            }
            int myPlayer = Main.myPlayer;
        }
References Terraria.Player.HasItem(), j__TPar, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.UI.ItemSorting.SortAmmo(), and Terraria.UI.ItemSorting.SortCoins().