terraria-cpp2il-methodrecon: System.Xml.DtdParser.ParseFreeFloatingDtd
ParseFreeFloatingDtd() [1/2]
void System.Xml.DtdParser.ParseFreeFloatingDtd () inline private
Definition at line 263 of file DtdParser.cs.
        {
            if (this.hasFreeFloatingInternalSubset)
            {
                this.LoadParsingBuffer();
                this.ParseSubset();
                int num = this.curPos;
                this.SaveParsingBuffer(num);
            }
            string text = this.systemId;
            if (text != null)
            {
                int stringLength = text._stringLength;
                this.ParseExternalSubset();
                return;
            }
        }
References System.Xml.DtdParser.curPos, System.Xml.DtdParser.hasFreeFloatingInternalSubset, j__TPar, System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.ParseExternalSubset(), System.Xml.DtdParser.ParseSubset(), System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.systemId, and System.text.
Referenced by System.Xml.DtdParser.Parse().