terraria-cpp2il-methodrecon: Terraria.Mount.Dismount
Dismount()
void Terraria.Mount.Dismount (Player mountedPlayer) inline
Definition at line 1578 of file Mount.cs.
        {
            while (this._active)
            {
                Mount.MountData data = this._data;
                if (data == null)
                {
                    if (116 == 0)
                    {
                    }
                    if (!true)
                    {
                    }
                    long num = 0L;
                    this.DoSpawnDust(mountedPlayer, num != 0L);
                    long num2 = 0L;
                    this._idleTime = (int)num2;
                    int height = mountedPlayer.height;
                    float y = mountedPlayer.position.Y;
                    int num3 = 42;
                    mountedPlayer.height = num3;
                    mountedPlayer.position.Y = (float)height;
                    int whoAmI = mountedPlayer.whoAmI;
                    if (num3 == 0)
                    {
                    }
                    int myPlayer = Main.myPlayer;
                    int whoAmI2 = mountedPlayer.whoAmI;
                    break;
                }
                bool minecart = data.Minecart;
                int buff = data.buff;
                mountedPlayer.ClearBuff(buff);
                if (minecart)
                {
                    Mount.MountData data2 = this._data;
                    int extraBuff = data2.extraBuff;
                    mountedPlayer.ClearBuff(extraBuff);
                    if (data2 == null)
                    {
                    }
                    if (!true)
                    {
                    }
                    return;
                }
            }
        }
References Terraria.Mount._active, Terraria.Mount._data, Terraria.Mount.MountData.buff, Terraria.Mount.DoSpawnDust(), j__TPar, System.L, Terraria.Mount.MountData.Minecart, and Terraria.Main.myPlayer.
Referenced by Terraria.Player.GrappleMovement(), Terraria.Player.ItemCheck_HandleMount(), Terraria.Player.PetAnimal(), Terraria.Player.QuickGrapple(), and Terraria.Player.QuickMount().