terraria-cpp2il-methodrecon: GUIVirtualInputControllerEdit.DrawProfile
DrawProfile()
void GUIVirtualInputControllerEdit.DrawProfile () inline private
Definition at line 67 of file GUIVirtualInputControllerEdit.cs.
    {
        bool mouseLeft = Main.mouseLeft;
        bool mouseLeftRelease = Main.mouseLeftRelease;
        bool flag = this.editingName;
        if (flag)
        {
            bool mouseLeft2 = Main.mouseLeft;
            bool mouseLeftRelease2 = Main.mouseLeftRelease;
            this.CloseNameEdit();
        }
        if (this.SlotOrder == null)
        {
        }
        int selectedControl = this.SelectedControl;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            int num = 1;
            this.editingName = num != 0;
            if (num == 0)
            {
            }
            Main.clrInput();
            VirtualControlsProfile_Layout virtualControlsProfile_Layout;
            string editedName = virtualControlsProfile_Layout.EditedName;
            this.editNameValue = editedName;
        }
        bool flag2 = this.editingName;
        if (!flag2)
        {
            bool flag3 = this.displayProfileOptions;
            GUITransactionButton.InputState inputState2;
            if (inputState2 == GUITransactionButton.InputState.Clicked)
            {
                int num2 = 1;
                bool flag4 = this.displayProfileOptions;
                if (flag4)
                {
                    this.CloseProfileOptions();
                    return;
                }
                this.displayProfileOptions = num2 != 0;
                if (!flag4)
                {
                }
                Main.mouseLeftRelease = Main.mouseLeftRelease;
                GUIInputRegionExclusive guiinputRegionExclusive;
                this._optionsBlocker = guiinputRegionExclusive;
            }
            GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
            bool flag5 = this.displayProfileOptions;
            if (optionsBlocker != null)
            {
                if (flag5)
                {
                    return;
                }
            }
            else if (flag5)
            {
                if (optionsBlocker == null)
                {
                }
                Main.FlushBatches();
                if (this.displayProfileOptions)
                {
                    GUITransactionButton.InputState inputState3;
                    if (inputState3 == GUITransactionButton.InputState.Clicked)
                    {
                        GUIInputRegionExclusive optionsBlocker2 = this._optionsBlocker;
                    }
                    GUITransactionButton.InputState inputState4;
                    if (inputState4 == GUITransactionButton.InputState.Clicked)
                    {
                        GUIInputRegionExclusive optionsBlocker3 = this._optionsBlocker;
                    }
                    GUITransactionButton.InputState inputState5;
                    if (inputState5 == GUITransactionButton.InputState.Clicked)
                    {
                        GUIInputRegionExclusive optionsBlocker4 = this._optionsBlocker;
                    }
                    GUITransactionButton.InputState inputState6;
                    if (inputState6 != GUITransactionButton.InputState.Clicked)
                    {
                        GUIInputRegionExclusive optionsBlocker5 = this._optionsBlocker;
                        if (optionsBlocker5 != null)
{
                            int num3 = 1;
                            optionsBlocker5.Active = num3 != 0;
                            if (optionsBlocker5 == null)
{
                            }
                            bool mouseLeft3 = Main.mouseLeft;
                            if (optionsBlocker5 == null)
{
                            }
                            bool mouseLeftRelease3 = Main.mouseLeftRelease;
                            return;
                        }
                    }
                    else
                    {
                        GUIInputRegionExclusive optionsBlocker6 = this._optionsBlocker;
                    }
                }
            }
            return;
        }
        string text = this.editNameValue;
        long num4 = 0L;
        if (!flag2)
        {
        }
        int num5 = 20;
        long num6 = 0L;
        long num7 = 0L;
        long num8 = 0L;
        Rectangle rectangle;
        string inputText = Main.GetInputText(text, rectangle, (int)num4, num5 != 0, num6 != 0L, num7 != 0L, num8 != 0L);
        this.editNameValue = inputText;
        int stringLength = inputText._stringLength;
        int num9 = 20;
        long num10 = 0L;
        string text2 = inputText.Substring((int)num10, num9);
        this.editNameValue = text2;
        if (stringLength == 0)
        {
        }
        if (flag)
        {
            return;
        }
        if (!flag)
        {
        }
        string text3 = this.editNameValue;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout2;
        virtualControlsProfile_Layout2.EditedName = text3;
        int num11 = this.textBlinkerCount;
        this.textBlinkerCount = num11;
        int num12 = this.textBlinkerState;
        this.StlyeOptionsList = num12;
        string text4 = this.editNameValue;
        bool flag6 = string.IsNullOrEmpty(text4);
        SpriteFont spriteFont;
        Microsoft.Xna.Framework.Vector2 vector = spriteFont.MeasureString(text4);
        long num13 = 0L;
        string text5 = "..." + text4;
        SpriteFont spriteFont2;
        Microsoft.Xna.Framework.Vector2 vector2 = spriteFont2.MeasureString(text5);
        int stringLength2 = text4._stringLength;
        int num14 = 1;
        string text6 = text4.Substring(num14, (int)num13);
    }
References _optionsBlocker, CloseNameEdit(), CloseProfileOptions(), Terraria.Main.clrInput(), displayProfileOptions, VirtualControlsProfile_Layout.EditedName, editingName, editNameValue, Terraria.Main.FlushBatches(), Terraria.Main.GetInputText(), j__TPar, System.L, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, SelectedControl, SlotOrder, System.text, textBlinkerCount, and textBlinkerState.
Referenced by DrawWidgetOverlays(), and DrawWidgets().