terraria-cpp2il-methodrecon: GUIVirtualInputControllerEdit.DrawPageOptions
DrawPageOptions()
void GUIVirtualInputControllerEdit.DrawPageOptions () inline private
Definition at line 248 of file GUIVirtualInputControllerEdit.cs.
    {
        if (this.displayPageOptions)
        {
        }
        GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
        bool flag;
        if (optionsBlocker != null)
        {
            flag = this.displayPageOptions;
            if (flag)
            {
            }
        }
        if (optionsBlocker == null)
        {
        }
        bool mouseLeft = Main.mouseLeft;
        if (optionsBlocker == null)
        {
        }
        bool mouseLeftRelease = Main.mouseLeftRelease;
        if (flag)
        {
            return;
        }
        Microsoft.Xna.Framework.Graphics.Texture2D texture2D;
        int width = texture2D.Width;
        bool flag2 = this.displayPageOptions;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            int num;
            if (this.displayPageOptions)
            {
                this.ClosePageOptions();
                num = 1;
                return;
            }
            this.displayPageOptions = num != 0;
            GUIInputRegionExclusive guiinputRegionExclusive;
            this._optionsBlocker = guiinputRegionExclusive;
        }
        bool flag3 = this.displayPageOptions;
        if (flag3)
        {
            int width2 = texture2D.Width;
            if (!flag3)
            {
            }
            GUITransactionButton.InputState inputState2;
            if (inputState2 == GUITransactionButton.InputState.Clicked)
            {
                GUIInputRegionExclusive optionsBlocker2 = this._optionsBlocker;
            }
            GUITransactionButton.InputState inputState3;
            if (inputState3 == GUITransactionButton.InputState.Clicked)
            {
                GUIInputRegionExclusive optionsBlocker3 = this._optionsBlocker;
            }
            GUIInputRegionExclusive optionsBlocker4 = this._optionsBlocker;
            if (optionsBlocker4 != null)
            {
                int num2 = 1;
                optionsBlocker4.Active = num2 != 0;
                if (optionsBlocker4 == null)
                {
                }
                bool mouseLeft2 = Main.mouseLeft;
                if (optionsBlocker4 == null)
                {
                }
                bool mouseLeftRelease2 = Main.mouseLeftRelease;
                GUIInputRegionExclusive optionsBlocker5 = this._optionsBlocker;
            }
        }
    }
References _optionsBlocker, ClosePageOptions(), displayPageOptions, j__TPar, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, and Microsoft.Xna.Framework.Graphics.Texture2D.Width.
Referenced by DrawWidgetOverlays(), and DrawWidgets().