terraria-cpp2il-methodrecon: Terraria.GameContent.Creative.CreativeUI.ToggleMenu
ToggleMenu()
void Terraria.GameContent.Creative.CreativeUI.ToggleMenu () inline
Definition at line 243 of file CreativeUI.cs.
        {
            bool flag = this.<Enabled>k__BackingField;
            UserInterface powersUI = this._powersUI;
            this.<Enabled>k__BackingField = flag;
            powersUI.EscapeElements();
            UISliderBase.EscapeElements();
            if (this.<Enabled>k__BackingField)
            {
                Recipe.FindRecipes(false);
                Player localPlayer = Main.LocalPlayer;
                this.RefreshAvailableInfiniteItemsList();
                return;
            }
            Item[] itemSlotsForUI = this._itemSlotsForUI;
            if (itemSlotsForUI.position == null)
            {
            }
            Player localPlayer2 = Main.LocalPlayer;
            int myPlayer = Main.myPlayer;
            Vector2 position = this._itemSlotsForUI.position;
            Item item;
            if (item != null && item == null)
            {
                throw new ArrayTypeMismatchException();
            }
            itemSlotsForUI.position = item;
            UICreativePowersMenu uiState = this._uiState;
            if (uiState != null)
            {
                uiState.StopPlayingResearchAnimations();
                return;
            }
        }
References Terraria.GameContent.Creative.CreativeUI._itemSlotsForUI, Terraria.GameContent.Creative.CreativeUI._powersUI, Terraria.GameContent.Creative.CreativeUI._uiState, Terraria.GameContent.Creative.CreativeUI.Enabled, Terraria.GameContent.UI.Elements.UISliderBase.EscapeElements(), Terraria.Recipe.FindRecipes(), System.item, j__TPar, Terraria.GameContent.Creative.CreativeUI.k__BackingField, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Entity.position, Terraria.GameContent.Creative.CreativeUI.RefreshAvailableInfiniteItemsList(), and Terraria.GameContent.UI.States.UICreativePowersMenu.StopPlayingResearchAnimations().
Referenced by Terraria.GameContent.Creative.CreativeUI.DrawToggleButton().