terraria-cpp2il-methodrecon: System.Net.ServicePointScheduler.SendRequest
SendRequest()
void System.Net.ServicePointScheduler.SendRequest (WebOperation operation, string groupName) inline
Definition at line 233 of file ServicePointScheduler.cs.
        {
            ServicePoint servicePoint = this.<ServicePoint>k__BackingField;
            this.GetConnectionGroup(groupName).EnqueueOperation(operation);
            this.Run();
            long num = 0L;
            Monitor.Exit(servicePoint);
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.Threading.Monitor.Exit(), System.Net.ServicePointScheduler.GetConnectionGroup(), System.Net.ServicePointScheduler.k__BackingField, System.L, and System.Net.ServicePointScheduler.Run().