terraria-cpp2il-methodrecon: AndroidImmersive.GetSDKLevel
GetSDKLevel()
static int AndroidImmersive.GetSDKLevel () inline static private
Definition at line 36 of file AndroidImmersive.cs.
    {
        IntPtr intPtr = AndroidJNI.FindClass("android/os/Build$VERSION");
        IntPtr staticFieldID = AndroidJNI.GetStaticFieldID(intPtr, "SDK_INT", "I");
        string text = AndroidJNI.GetStaticIntField(intPtr, staticFieldID).ToString();
        string text2 = "AndroidImmersive: SDK level = " + text;
        Debug.Log(text2);
        Debug.Log("AndroidImmersive: Can't retrieve SDK level");
        return "AndroidImmersive: Can't retrieve SDK level";
    }
References UnityEngine.AndroidJNI.FindClass(), UnityEngine.AndroidJNI.GetStaticFieldID(), UnityEngine.AndroidJNI.GetStaticIntField(), j__TPar, UnityEngine.Debug.Log(), and System.text.
Referenced by Activate().