terraria-cpp2il-methodrecon: InControl.UnityInputDeviceManager.UnityInputDeviceManager
UnityInputDeviceManager()
InControl.UnityInputDeviceManager.UnityInputDeviceManager () inline
Definition at line 15 of file UnityInputDeviceManager.cs.
        {
            if (!true)
            {
            }
            this.AddSystemDeviceProfiles();
            bool flag = Directory.Exists(UnityInputDeviceManager.CustomProfileFolder);
            DirectoryInfo directoryInfo = Directory.CreateDirectory(UnityInputDeviceManager.CustomProfileFolder);
            string customProfileFolder = UnityInputDeviceManager.CustomProfileFolder;
            this.LoadDeviceProfilesFromPath(customProfileFolder);
            this.QueryJoystickInfo();
            this.AttachDevices();
        }
References InControl.UnityInputDeviceManager.AddSystemDeviceProfiles(), InControl.UnityInputDeviceManager.AttachDevices(), System.IO.Directory.CreateDirectory(), InControl.UnityInputDeviceManager.CustomProfileFolder, System.IO.Directory.Exists(), j__TPar, InControl.UnityInputDeviceManager.LoadDeviceProfilesFromPath(), and InControl.UnityInputDeviceManager.QueryJoystickInfo().