terraria-cpp2il-methodrecon: System.Threading.ManualResetEventSlim.Set
Set() [2/2]
void System.Threading.ManualResetEventSlim.Set (bool duringCancellation) inline private inherited
Definition at line 207 of file ManualResetEventSlim.cs.
        {
            this.UpdateStateAtomically(0, 32768);
            int waiters = this.Waiters;
            Monitor.Enter(this.m_lock, false);
            Monitor.PulseAll(this.m_lock);
            if (!false)
            {
                ManualResetEvent eventObj = this.m_eventObj;
                if (eventObj != null)
                {
                    Monitor.Enter(eventObj, false);
                    if (this.m_eventObj != null)
                    {
                        bool flag = this.m_eventObj.Set();
                    }
                    if (false)
                    {
                        throw new OutOfMemoryException();
                    }
                }
                return;
            }
            throw new OutOfMemoryException();
        }
References System.Threading.Monitor.Enter(), j__TPar, System.Threading.ManualResetEventSlim.m_eventObj, System.Threading.ManualResetEventSlim.m_lock, System.Threading.Monitor.PulseAll(), System.Threading.EventWaitHandle.Set(), System.Threading.ManualResetEventSlim.UpdateStateAtomically(), and System.Threading.ManualResetEventSlim.Waiters.