terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.SpriteBatch.InsertNewBatchItem
InsertNewBatchItem()
SpriteBatchItem Microsoft.Xna.Framework.Graphics.SpriteBatch.InsertNewBatchItem (Texture2D texture) inline inherited
Definition at line 185 of file SpriteBatch.cs.
        {
            do
            {
                Texture2D texture2 = this._batcher._batchItemList.Texture;
                SpriteBatcher batcher = this._batcher;
                SpriteBatchItem[] batchItemList = batcher._batchItemList;
                GraphicsDevice device = batcher._device;
                SpriteBatchItem[] batchItemList2 = batcher._batchItemList;
                EffectPass overloadedEffectPass = this.OverloadedEffectPass;
                if (overloadedEffectPass != null)
                {
                    int batchIndex = overloadedEffectPass.BatchIndex;
                }
                int batchTextureIndex = texture.BatchTextureIndex;
                if (this.BatchDeffered)
                {
                    int lastBatchListId = batcher._lastBatchListId;
                    SpriteBatchItemList lastBatchList = batcher._lastBatchList;
                }
                SpriteBatchItem lastBatchItem = this._lastBatchItem;
                if (lastBatchItem != null)
                {
                }
                SpriteBatchItem nextBatchItem = lastBatchItem.NextBatchItem;
                SpriteBatcher batcher2 = this._batcher;
                SpriteBatcher batcher3 = this._batcher;
                Dictionary<int, SpriteBatchItemList> activeBatchLists = batcher3._activeBatchLists;
                this._batcher._lastBatchList = batcher3;
                if (batcher3._batchItemList != null)
                {
                    int batchItemCount = batcher3._batchItemCount;
                }
                if (this.BatchDefferedHeadInsert)
                {
                    SpriteBatchItemList firstBatchList = this._firstBatchList;
                    if (firstBatchList != null)
                    {
                        SpriteBatchItem first = firstBatchList.First;
                    }
                    if (this._lastBatchList == null)
                    {
                        this._lastBatchList = batcher3;
                    }
                    this._firstBatchList = batcher3;
                }
                if (texture.SharedBatching)
                {
                    SpriteBatchItemList lastBatchList2 = this._lastBatchList;
                    if (lastBatchList2 != null)
                    {
                        SpriteBatchItem last = lastBatchList2.Last;
                    }
                    if (this._firstBatchList == null)
                    {
                        this._firstBatchList = batcher3;
                    }
                    this._lastBatchList = batcher3;
                }
            }
            while (texture.NonSharedHeadInsert);
            throw new ArrayTypeMismatchException();
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch._batcher, Microsoft.Xna.Framework.Graphics.SpriteBatcher._batchItemList, Microsoft.Xna.Framework.Graphics.SpriteBatch._firstBatchList, Microsoft.Xna.Framework.Graphics.SpriteBatch._lastBatchItem, Microsoft.Xna.Framework.Graphics.SpriteBatch._lastBatchList, Microsoft.Xna.Framework.Graphics.SpriteBatcher._lastBatchListId, Microsoft.Xna.Framework.Graphics.SpriteBatch.BatchDeffered, Microsoft.Xna.Framework.Graphics.SpriteBatch.BatchDefferedHeadInsert, Microsoft.Xna.Framework.Graphics.EffectPass.BatchIndex, Microsoft.Xna.Framework.Graphics.Texture2D.BatchTextureIndex, j__TPar, Microsoft.Xna.Framework.Graphics.SpriteBatchItem.NextBatchItem, Microsoft.Xna.Framework.Graphics.Texture2D.NonSharedHeadInsert, Microsoft.Xna.Framework.Graphics.SpriteBatch.OverloadedEffectPass, Microsoft.Xna.Framework.Graphics.Texture2D.SharedBatching, and Microsoft.Xna.Framework.Graphics.SpriteBatchItem.Texture.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), and Microsoft.Xna.Framework.Graphics.Clipper.InjectBatches().