terraria-cpp2il-methodrecon: VirtualControllerInputState.SaveDefaultCategories
SaveDefaultCategories()
void VirtualControllerInputState.SaveDefaultCategories () inline
Definition at line 62 of file VirtualControllerInputState.cs.
    {
        long num = 0L;
        string text;
        bool flag = FileUtilities.Exists(text, num != 0L);
        long num2 = 0L;
        string text2;
        FileUtilities.Delete(text2, num2 != 0L);
        VirtualControllerInputState.SetupLookups();
        string text3;
        if (("Item" == null || "Item" != null) && ("Category" == null || "Category" != null) && (text3 == null || text3 != null))
        {
            return;
        }
        throw new ArrayTypeMismatchException();
    }
References Terraria.Utilities.FileUtilities.Delete(), Terraria.Utilities.FileUtilities.Exists(), j__TPar, System.L, SetupLookups(), and System.text.