terraria-cpp2il-methodrecon: Terraria.GameContent.Golf.GolfState.GetLastHitBall
GetLastHitBall()
Projectile Terraria.GameContent.Golf.GolfState.GetLastHitBall () inline
Definition at line 181 of file GolfState.cs.
        {
            Projectile lastHitGolfBall = this._lastHitGolfBall;
            if (lastHitGolfBall == null)
            {
                return;
            }
            bool active = lastHitGolfBall.active;
            if (!active)
            {
                return;
            }
            Projectile lastHitGolfBall2;
            if (!active)
            {
                lastHitGolfBall2 = this._lastHitGolfBall;
            }
            if (active)
            {
                int owner = lastHitGolfBall2.owner;
                int myPlayer = Main.myPlayer;
                Projectile lastHitGolfBall3 = this._lastHitGolfBall;
                int lastRecordedSwingCount = this._lastRecordedSwingCount;
                return this._lastHitGolfBall;
            }
        }
References Terraria.GameContent.Golf.GolfState._lastHitGolfBall, Terraria.GameContent.Golf.GolfState._lastRecordedSwingCount, Terraria.Entity.active, j__TPar, Terraria.Main.myPlayer, and Terraria.Projectile.owner.
Referenced by Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.GameContent.Golf.GolfState.RecordBallInfo(), Terraria.GameContent.Golf.GolfState.ResetGolfBall(), and Terraria.GameContent.Golf.GolfState.Update().