terraria-cpp2il-methodrecon: LayoutDefinition.LoadReleaseLayout
LoadReleaseLayout() [1/2]
static void LayoutDefinition.LoadReleaseLayout () inline static inherited
Definition at line 36 of file LayoutDefinition.cs.
    {
        bool flag = LayoutDefinition.LoadReleaseLayout(Resources.Load<TextAsset>("Content/UILayout").bytes);
        Type type;
        MethodInfo method = type.GetMethod("Awake", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
    }
References UnityEngine.TextAsset.bytes, System.Type.GetMethod(), UnityEngine.Resources.Load(), and LayoutDefinition.LoadReleaseLayout().
Referenced by XNAUnityRunner.Awake(), and LayoutDefinition.LoadReleaseLayout().