terraria-cpp2il-methodrecon: GUIWorldCreateMenu.IsOverOptions
IsOverOptions()
bool GUIWorldCreateMenu.IsOverOptions (Vector2 cursorPosition) inline private
Definition at line 181 of file GUIWorldCreateMenu.cs.
    {
        if (!true)
        {
        }
        int menuMode = Main.menuMode;
        if (this.displayDifficultyOptions)
        {
            GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
            this._controllerInput.DeactivateDifficultyOptions();
        }
        if (this.displayWorldOptions)
        {
            GUIInputRegionExclusive optionsBlocker2 = this._optionsBlocker;
            this._controllerInput.DeactivateWorldOptions();
        }
        if (this.displayEvilTypeOptions)
        {
            GUIInputRegionExclusive optionsBlocker3 = this._optionsBlocker;
            this._controllerInput.DeactivateEvilTypeOptions();
        }
        return true;
    }
References _controllerInput, _optionsBlocker, GUIWorldCreateController.DeactivateDifficultyOptions(), GUIWorldCreateController.DeactivateEvilTypeOptions(), GUIWorldCreateController.DeactivateWorldOptions(), displayDifficultyOptions, displayEvilTypeOptions, displayWorldOptions, j__TPar, and Terraria.Main.menuMode.