terraria-cpp2il-methodrecon: GUIHousingMenu.Draw
Draw()
void GUIHousingMenu.Draw () inline
Definition at line 206 of file GUIHousingMenu.cs.
    {
        !0 instance = PageControllerLayoutDefinition.Instance;
        int myPlayer = Main.myPlayer;
        int myPlayer2 = Main.myPlayer;
        this.UpdateHotbarNavigation();
        this.RefreshNPCEntries();
        bool npcOver = this._npcOver;
        if (!npcOver)
        {
            this._lastNPCOVer = (npcOver ? 1 : 0);
        }
        this.over = (npcOver ? 1 : 0);
        !0 instance2 = PageControllerLayoutDefinition.Instance;
        !0 instance3 = PageControllerLayoutDefinition.Instance;
        DraggableItemGrid_Layout draggableItemGrid_Layout;
        int itemCount = draggableItemGrid_Layout.ItemCount;
        Rectangle rectangle;
        if (rectangle == null)
        {
        }
        int mouseX = Main.mouseX;
        int mouseY = Main.mouseY;
        !0 instance4 = PageControllerLayoutDefinition.Instance;
        List<int> activeNPCEntries = this._activeNPCEntries;
        int size = activeNPCEntries._size;
        if (activeNPCEntries == null)
        {
        }
        GUIControllerHousing guicontrollerHousing;
        if (guicontrollerHousing != null)
        {
            GUIControllerDynamicGridNavigator guicontrollerDynamicGridNavigator;
            guicontrollerDynamicGridNavigator.DisableScrollUntilChange();
        }
        bool npcOver2 = this._npcOver;
        if (npcOver2)
        {
            if (!npcOver2)
            {
            }
            bool npcOver3 = this._npcOver;
            int num;
            this._lastNPCOVer = num;
            if (npcOver3)
            {
                if (!npcOver3)
                {
                }
                string text = this.npcString;
                return;
            }
        }
        else
        {
            bool npcOver3;
            this._lastNPCOVer = (npcOver3 ? 1 : 0);
        }
    }
References _activeNPCEntries, _npcOver, System.Collections.Generic.List< T >._size, GUIControllerDynamicGridNavigator.DisableScrollUntilChange(), PageControllerLayoutDefinition< T >.Instance, ItemGrid_Layout.ItemCount, j__TPar, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, npcString, RefreshNPCEntries(), System.text, and UpdateHotbarNavigation().