terraria-cpp2il-methodrecon: System.Diagnostics.Process.StopWatchingForExit
StopWatchingForExit()
void System.Diagnostics.Process.StopWatchingForExit () inline private
Definition at line 567 of file Process.cs.
        {
            if (this.watchingForExit)
            {
                if (this.watchingForExit)
                {
                    RegisteredWaitHandle registeredWaitHandle = this.registeredWaitHandle;
                    WaitHandle waitHandle = this.waitHandle;
                    return;
                }
                long num = 0L;
                Monitor.Exit(this);
                if (num != 0L)
                {
                    throw new OutOfMemoryException();
                }
            }
        }
References System.Threading.Monitor.Exit(), System.L, System.Diagnostics.Process.registeredWaitHandle, System.Diagnostics.Process.waitHandle, and System.Diagnostics.Process.watchingForExit.
Referenced by System.Diagnostics.Process.Close(), and System.Diagnostics.Process.CompletionCallback().