terraria-cpp2il-methodrecon: System.Diagnostics.Process.WaitForExit
WaitForExit() [2/2]
bool System.Diagnostics.Process.WaitForExit (int milliseconds) inline
Definition at line 603 of file Process.cs.
        {
            long num = 0L;
            Microsoft.Win32.SafeHandles.SafeProcessHandle processHandle = this.GetProcessHandle(16, num != 0L);
            this.signaled = true;
            AsyncStreamReader asyncStreamReader = this.output;
            if (asyncStreamReader != null && asyncStreamReader.eofEvent != null)
            {
                ManualResetEvent eofEvent = asyncStreamReader.eofEvent;
            }
            AsyncStreamReader asyncStreamReader2 = this.error;
            if (asyncStreamReader2 != null && asyncStreamReader2.eofEvent != null)
            {
                ManualResetEvent eofEvent2 = asyncStreamReader2.eofEvent;
            }
            long num2 = 0L;
            if (processHandle != null)
            {
                if (this.haveProcessHandle)
                {
                    Microsoft.Win32.SafeHandles.SafeProcessHandle processHandle2 = this.m_processHandle;
                }
                processHandle.Close();
            }
            if (num2 == 0L && 7 == 0 && this.watchForExit)
            {
                this.RaiseOnExited();
            }
            throw new OutOfMemoryException();
        }
References System.Runtime.InteropServices.SafeHandle.Close(), System.Diagnostics.AsyncStreamReader.eofEvent, System.Diagnostics.Process.error, System.Diagnostics.Process.GetProcessHandle(), System.Diagnostics.Process.haveProcessHandle, j__TPar, System.L, System.Diagnostics.Process.m_processHandle, System.Diagnostics.Process.output, System.Diagnostics.Process.RaiseOnExited(), and System.Diagnostics.Process.watchForExit.