terraria-cpp2il-methodrecon: System.IO.ChunkedMemoryStream.AppendChunk
AppendChunk()
void System.IO.ChunkedMemoryStream.AppendChunk (long count) inline private
Definition at line 76 of file ChunkedMemoryStream.cs.
        {
            ChunkedMemoryStream.MemoryChunk currentChunk = this._currentChunk;
            if (currentChunk != null)
            {
                byte[] buffer = currentChunk._buffer;
                return;
            }
            int num = 16;
            long num2 = Math.Min(count, (long)num);
        }
References System.IO.ChunkedMemoryStream.MemoryChunk._buffer, System.IO.ChunkedMemoryStream._currentChunk, System.count, j__TPar, and System.Math.Min().
Referenced by System.IO.ChunkedMemoryStream.SetLength(), and System.IO.ChunkedMemoryStream.Write().