terraria-cpp2il-methodrecon: System.Net.Sockets.SafeSocketHandle.ReleaseHandle
ReleaseHandle()
override bool System.Net.Sockets.SafeSocketHandle.ReleaseHandle () inline protected
Definition at line 27 of file SafeSocketHandle.cs.
        {
            int num = 1;
            IntPtr handle = this.handle;
            if (num == 0)
            {
            }
            IntPtr handle2 = this.handle;
            int num2 = 2;
            List<Thread> list = this.blocking_threads;
            long num8;
            if (list != null)
            {
                Monitor.Enter(list, num2 != 0);
                int num3 = 1;
                int size = this.blocking_threads._size;
                Thread currentThread = Thread.CurrentThread;
                List<Thread> list2 = this.blocking_threads;
                if (size == 0)
                {
                }
                long num4 = 0L;
                int num5 = 15;
                if (num4 != 0L)
                {
                    throw new OutOfMemoryException();
                }
                if (num5 == 0)
                {
                    List<Thread> list3 = this.blocking_threads;
                    this.in_cleanup = num3 != 0;
                    int num6 = 100;
                    return Monitor.Wait(list3, num6);
                }
                long num7 = 0L;
                num8 = 0L;
                StringBuilder stringBuilder;
                Monitor.Exit(stringBuilder);
                if (num7 != 0L)
                {
                    throw new OutOfMemoryException();
                }
            }
            Socket.Close_icall(this.handle, (int)num8);
            if (false)
            {
                throw new OutOfMemoryException();
            }
            long num9 = 0L;
            long num10;
            Monitor.Exit(num10);
            if (num9 == 0L)
            {
            }
            throw new OutOfMemoryException();
        }
References System.Collections.Generic.List< T >._size, System.Net.Sockets.SafeSocketHandle.blocking_threads, System.Net.Sockets.Socket.Close_icall(), System.Threading.Thread.CurrentThread, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Runtime.InteropServices.SafeHandle.handle, j__TPar, System.L, System.list, and System.Threading.Monitor.Wait().