terraria-cpp2il-methodrecon: Terraria.GameContent.Events.DD2Event.WipeEntities
WipeEntities()
static void Terraria.GameContent.Events.DD2Event.WipeEntities () inline static
Definition at line 650 of file DD2Event.cs.
        {
            if (!true)
            {
            }
            DD2Event.ClearAllTowersInGame();
            DD2Event.ClearAllDD2HostilesInGame();
            DD2Event.ClearAllDD2EnergyCrystalsInChests();
            if (!true)
            {
            }
            bool netHost = Main.NetHost;
        }
References Terraria.GameContent.Events.DD2Event.ClearAllDD2EnergyCrystalsInChests(), Terraria.GameContent.Events.DD2Event.ClearAllDD2HostilesInGame(), Terraria.GameContent.Events.DD2Event.ClearAllTowersInGame(), j__TPar, and Terraria.Main.NetHost.
Referenced by Terraria.GameContent.Events.DD2Event.StartInvasion(), and Terraria.GameContent.Events.DD2Event.StopInvasion().