terraria-cpp2il-methodrecon: Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore
MatchesBackwardCore()
unsafe bool Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore (string s, int idx, int end, int orgStart, int ti, byte * sortkey, bool noLv4, SimpleCollator::ExtenderType ext, Contraction ct, SimpleCollator::Context ctx) inline private
Definition at line 727 of file SimpleCollator.cs.
        {
            int num;
            byte b = this.Category(num);
            long num2 = 0L;
            byte b2;
            Contraction tailContraction = this.GetTailContraction(s, (int)num2, (int)b2);
            bool flag;
            if (tailContraction != null)
            {
                char[] source = tailContraction.Source;
                idx.m_value = source;
                if (tailContraction.SortKey == null)
                {
                    goto IL_0064;
                }
                if (false)
                {
                    return flag;
                }
                int num3;
                byte b3 = this.Level1(num3);
                byte b4 = MSCompatUnicodeTable.Level3(num3);
            }
            int num4;
            byte b5 = this.Category(num4);
            byte b6 = this.Level1(num4);
            IL_0064:
            int num5 = 1;
            byte b7 = MSCompatUnicodeTable.Level3(num4);
            char c = s[num5];
            byte b8 = this.Category(num5);
            if (b2 == 0)
            {
            }
            char c2 = s[num5];
            return flag;
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.GetTailContraction(), j__TPar, System.L, Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), System.s, and System.source.