terraria-cpp2il-methodrecon: Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore
MatchesForwardCore()
unsafe bool Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore (string s, int idx, int end, int ti, byte * sortkey, bool noLv4, SimpleCollator::ExtenderType ext, Contraction ct, SimpleCollator::Context ctx) inline private
Definition at line 670 of file SimpleCollator.cs.
        {
            if (ext != SimpleCollator.ExtenderType.None)
            {
            }
            Contraction contraction;
            long num2;
            if (contraction == null)
            {
                int num;
                byte b = this.Category(num);
                byte b2 = this.Level1(num);
                num2 = 0L;
                byte b3 = this.Level2(num, ext);
                byte b4 = MSCompatUnicodeTable.Level3(num);
            }
            if (num2 == 0L)
            {
            }
            bool flag;
            return flag;
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), j__TPar, System.L, Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), and Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3().