terraria-cpp2il-methodrecon: Mono.Globalization.Unicode.SimpleCollator.IndexOf
IndexOf() [1/2]
unsafe int Mono.Globalization.Unicode.SimpleCollator.IndexOf (string s, string target, int start, int length, byte * targetSortKey, SimpleCollator::Context ctx) inline private
Definition at line 538 of file SimpleCollator.cs.
        {
            int stringLength = target._stringLength;
            long num = 0L;
            char c = target[(int)num];
            int stringLength2 = target._stringLength;
            int stringLength3 = target._stringLength;
            long num2 = 0L;
            char c2 = target[(int)num2];
            Contraction contraction = this.GetContraction(target, start, start);
            int num3;
            byte[] sortKey2;
            if (contraction != null)
            {
                string replacement = contraction.Replacement;
                if (targetSortKey == null)
                {
                    return num3;
                }
                byte[] sortKey = contraction.SortKey;
                targetSortKey->m_value = sortKey;
                sortKey2 = contraction.SortKey;
            }
            if (targetSortKey != null)
            {
                char c3 = target[start];
                char c4 = target[start];
                int num4;
                byte b = this.Category(num4);
                targetSortKey->m_value = b;
                byte b2 = this.Level1(num4);
                if (sortKey2 == null)
                {
                }
                byte b3 = MSCompatUnicodeTable.Level3(num4);
                return num3;
            }
            return num3;
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), j__TPar, System.L, Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), and System.start.