terraria-cpp2il-methodrecon: Mono.Globalization.Unicode.SimpleCollator.GetSortKey
GetSortKey() [2/3]
void Mono.Globalization.Unicode.SimpleCollator.GetSortKey (string s, int start, int end, SortKeyBuffer buf, CompareOptions opt) inline private
Definition at line 300 of file SimpleCollator.cs.
        {
            char c = s[start];
            SimpleCollator.ExtenderType extenderType;
            if (extenderType != SimpleCollator.ExtenderType.None)
            {
                int num = this.FilterExtender(43151360, extenderType, opt);
                return;
            }
            bool flag = SimpleCollator.IsIgnorable(43151360, opt);
            int num2 = this.FilterOptions(43151360, opt);
            Contraction contraction = this.GetContraction(s, start, end);
            if (contraction == null)
            {
                bool flag2 = MSCompatUnicodeTable.IsIgnorableNonSpacing(num2);
                return;
            }
            string replacement = contraction.Replacement;
            if (replacement != null)
            {
                int stringLength = replacement._stringLength;
                return;
            }
            byte b = MSCompatUnicodeTable.Level3(num2);
        }
References Mono.Globalization.Unicode.SimpleCollator.FilterExtender(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.IsIgnorable(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsIgnorableNonSpacing(), j__TPar, Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), System.s, and System.start.