terraria-cpp2il-methodrecon: System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext
MoveNext()
bool System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 18 of file SerializationInfoEnumerator.cs.
        {
            /*
An exception occurred when decompiling this method (06001ECF)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean System.Runtime.Serialization.SerializationInfoEnumerator::MoveNext()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:int32(var_0_06, ldfld:int32(SerializationInfoEnumerator::_numItems, ldloc:SerializationInfoEnumerator(this)))
    stloc:bool(var_1_0D, ldfld:bool(SerializationInfoEnumerator::_current, ldloc:SerializationInfoEnumerator(this)))
    stfld:int32(SerializationInfoEnumerator::_currItem, ldloc:SerializationInfoEnumerator(this), ldloc:bool[exp:int32](var_1_0D))
    stloc:int64(var_2_16, ldc.i4:int64(0))
    stfld:bool(SerializationInfoEnumerator::_current, ldloc:SerializationInfoEnumerator(this), ldloc:int64[exp:bool](var_2_16))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by System.DateTime.DateTime(), System.Threading.ExecutionContext.ExecutionContext(), System.Runtime.Remoting.Messaging.LogicalCallContext.LogicalCallContext(), System.Runtime.Remoting.Messaging.MethodCall.MethodCall(), System.Runtime.Remoting.Messaging.MethodResponse.MethodResponse(), System.Runtime.Remoting.ObjRef.ObjRef(), System.Security.SecurityException.SecurityException(), System.Text.StringBuilder.StringBuilder(), System.Xml.XmlException.XmlException(), System.Xml.Schema.XmlSchemaException.XmlSchemaException(), System.Security.Claims.ClaimsPrincipal.Deserialize(), System.Collections.Hashtable.OnDeserialization(), and System.Collections.Specialized.NameObjectCollectionBase.OnDeserialization().