terraria-cpp2il-methodrecon: GUIControllerDynamicGridNavigator.GetNavigationOutDirs
GetNavigationOutDirs()
int GUIControllerDynamicGridNavigator.GetNavigationOutDirs () inline
Definition at line 876 of file GUIControllerDynamicGridNavigator.cs.
    {
        if (this._controller != null)
        {
            GUIControllerDynamicGridNavigator.GetCollectionCount menuItemCount = this._menuItemCount;
            IntPtr invoke_impl = menuItemCount.invoke_impl;
            IntPtr method_code = menuItemCount.method_code;
            IntPtr method = menuItemCount.method;
            GUIControllerDynamicGridNavigator.GetCollectionCount displayItemCount = this._displayItemCount;
            IntPtr invoke_impl2 = displayItemCount.invoke_impl;
            IntPtr method_code2 = displayItemCount.method_code;
            IntPtr method2 = displayItemCount.method;
            int num = this.itemColumn;
            int menuColumn = this.MenuColumn;
            bool leftSideController = this.LeftSideController;
            GUIControllerDynamicGridNavigator.GetCollectionCount menuItemCount2 = this._menuItemCount;
            int num2 = this.menuRow;
            IntPtr invoke_impl3 = menuItemCount2.invoke_impl;
            IntPtr method_code3 = menuItemCount2.method_code;
            IntPtr method3 = menuItemCount2.method;
            GUIControllerDynamicGridNavigator.GetCollectionCount displayItemCount2 = this._displayItemCount;
            IntPtr method_code4 = displayItemCount2.method_code;
            IntPtr invoke_impl4 = displayItemCount2.invoke_impl;
            IntPtr method4 = displayItemCount2.method;
            int num3 = this.menuRow;
        }
        int num4 = this.itemRow;
        int num5 = this.itemColumn;
        int maxRowColumn_Horizontal = this.MaxRowColumn_Horizontal;
        int num6 = this.itemRow;
        int maxRow_Horizontal = this.MaxRow_Horizontal;
        int num7 = this.itemColumn;
        int maxRowColumn_Horizontal2 = this.MaxRowColumn_Horizontal;
        int num8 = this.itemRow;
        return this.MaxRow_Horizontal;
    }
References _controller, _displayItemCount, _menuItemCount, itemColumn, itemRow, j__TPar, LeftSideController, MaxRow_Horizontal, MaxRowColumn_Horizontal, MenuColumn, and menuRow.
Referenced by GUIControllerCrafting4Page.GetNavigationOutDirs(), GUIControllerCraftingGuide.GetNavigationOutDirs(), GUIControllerCraftingGuidePopup.GetNavigationOutDirs(), GUIControllerHousing4Page.GetNavigationOutDirs(), GUIControllerItemDuplication4Page.GetNavigationOutDirs(), GUIControllerPVP4Page.GetNavigationOutDirs(), GUIControllerReforge4Page.GetNavigationOutDirs(), and GUIControllerResearchPage4Page.GetNavigationOutDirs().