terraria-cpp2il-methodrecon: GUIControllerDynamicGridNavigator.RefreshScrollOffset
RefreshScrollOffset()
void GUIControllerDynamicGridNavigator.RefreshScrollOffset () inline
Definition at line 578 of file GUIControllerDynamicGridNavigator.cs.
    {
        int num = 1;
        int maxScrollOffset_Horizontal = this.MaxScrollOffset_Horizontal;
        if (num == 0)
        {
        }
        GUIControllerDynamicGridNavigator.GetItemScale itemScale = this._itemScale;
        IntPtr invoke_impl = itemScale.invoke_impl;
        IntPtr method_code = itemScale.method_code;
        IntPtr method = itemScale.method;
        if (itemScale == null)
        {
        }
        GUIControllerDynamicGridNavigator.GetGrid grid = this._grid;
        IntPtr invoke_impl2 = grid.invoke_impl;
        IntPtr method_code2 = grid.method_code;
        IntPtr method2 = grid.method;
        GUIControllerDynamicGridNavigator.GetScrollOffset getScrollOffset = this._getScrollOffset;
        IntPtr method_code3 = getScrollOffset.method_code;
        IntPtr invoke_impl3 = getScrollOffset.invoke_impl;
        IntPtr method3 = getScrollOffset.method;
        int num2 = this.scrollOffset;
        GUIControllerDynamicGridNavigator.GetScrollOffset getScrollOffset2 = this._getScrollOffset;
        this.scrollOffset = num2;
        IntPtr invoke_impl4 = getScrollOffset2.invoke_impl;
        IntPtr method_code4 = getScrollOffset2.method_code;
        IntPtr method4 = getScrollOffset2.method;
        GUIControllerDynamicGridNavigator.GetScrollOffset getScrollOffset3 = this._getScrollOffset;
        int num3 = this.scrollOffset;
        IntPtr invoke_impl5 = getScrollOffset3.invoke_impl;
        IntPtr method_code5 = getScrollOffset3.method_code;
        IntPtr method5 = getScrollOffset3.method;
        int num4 = 32640;
        this.scrollOffset = num4;
        int num5 = this.scrollOffset;
        int maxScrollOffset_Horizontal2 = this.MaxScrollOffset_Horizontal;
        int maxScrollOffset_Horizontal3 = this.MaxScrollOffset_Horizontal;
        this.scrollOffset = maxScrollOffset_Horizontal3;
    }
References _getScrollOffset, _grid, _itemScale, itemScale, j__TPar, MaxScrollOffset_Horizontal, and scrollOffset.
Referenced by GUIControllerCrafting4Page.RefreshScrollOffset(), GUIControllerCraftingGuide.RefreshScrollOffset(), GUIControllerCraftingGuidePopup.RefreshScrollOffset(), and GUIControllerItemDuplication4Page.RefreshScrollOffset().