terraria-cpp2il-methodrecon: GUIControllerDynamicGridNavigator.GetSelectedItemRegion
GetSelectedItemRegion()
Rectangle GUIControllerDynamicGridNavigator.GetSelectedItemRegion () inline
Definition at line 999 of file GUIControllerDynamicGridNavigator.cs.
    {
        int num = 1;
        this.ClampPosition();
        if (num == 0)
        {
        }
        GUIControllerDynamicGridNavigator.GetItemScale itemScale = this._itemScale;
        IntPtr invoke_impl = itemScale.invoke_impl;
        IntPtr method_code = itemScale.method_code;
        IntPtr method = itemScale.method;
        if (itemScale == null)
        {
        }
        int num2 = this.scrollOffset;
        int num3 = this.itemRow;
        bool flag = this.inMenu;
        int menuColumn = this.MenuColumn;
        int num4 = this.menuRow;
        GUIControllerDynamicGridNavigator.GetGrid grid = this._grid;
        IntPtr invoke_impl2 = grid.invoke_impl;
        IntPtr method_code2 = grid.method_code;
        IntPtr method2 = grid.method;
        GUIControllerDynamicGridNavigator.GetGrid grid2 = this._grid;
        IntPtr invoke_impl3 = grid2.invoke_impl;
        IntPtr method_code3 = grid2.method_code;
        IntPtr method3 = grid2.method;
        Debug.Log("Cursor outside visible");
        return "Cursor outside visible";
    }
References _grid, _itemScale, ClampPosition(), inMenu, itemRow, itemScale, j__TPar, UnityEngine.Debug.Log(), MenuColumn, menuRow, and scrollOffset.
Referenced by GUIControllerCrafting4Page.GetSelectedItemRegion(), GUIControllerCraftingGuide.GetSelectedItemRegion(), GUIControllerCraftingGuidePopup.GetSelectedItemRegion(), GUIControllerHousing4Page.GetSelectedItemRegion(), GUIControllerItemDuplication4Page.GetSelectedItemRegion(), GUIControllerReforge4Page.GetSelectedItemRegion(), and GUIControllerResearchPage4Page.GetSelectedItemRegion().