terraria-cpp2il-methodrecon: GUIControllerDynamicGridNavigator.ClampPosition
ClampPosition()
void GUIControllerDynamicGridNavigator.ClampPosition () inline protected
Definition at line 973 of file GUIControllerDynamicGridNavigator.cs.
    {
        GUIControllerDynamicGridNavigator.GetCollectionCount collectionCount = this._collectionCount;
        IntPtr invoke_impl = collectionCount.invoke_impl;
        IntPtr method_code = collectionCount.method_code;
        IntPtr method = collectionCount.method;
        if (method_code == 0)
        {
            GUIControllerDynamicGridNavigator.GetCollectionCount menuItemCount = this._menuItemCount;
            IntPtr invoke_impl2 = menuItemCount.invoke_impl;
            IntPtr method_code2 = menuItemCount.method_code;
            IntPtr method2 = menuItemCount.method;
            GUIControllerDynamicGridNavigator.GetCollectionCount displayItemCount = this._displayItemCount;
            IntPtr invoke_impl3 = displayItemCount.invoke_impl;
            IntPtr method_code3 = displayItemCount.method_code;
            IntPtr method3 = displayItemCount.method;
            int menuColumn = this.MenuColumn;
            this.itemColumn = menuColumn;
        }
        int num = this.itemColumn;
        int menuColumn2 = this.MenuColumn;
        int num2 = 1;
        this.ClampMenu(num2 != 0);
    }
References _collectionCount, _displayItemCount, _menuItemCount, ClampMenu(), itemColumn, j__TPar, and MenuColumn.
Referenced by GetSelectedItemRegion(), and NavigateInto().