terraria-cpp2il-methodrecon: GUIControllerDynamicGridNavigator.NavigateInto
NavigateInto()
void GUIControllerDynamicGridNavigator.NavigateInto (int column, int row) inline
Definition at line 1031 of file GUIControllerDynamicGridNavigator.cs.
    {
        GUIControllerDynamicGridNavigator.GetGrid grid = this._grid;
        IntPtr invoke_impl = grid.invoke_impl;
        IntPtr method_code = grid.method_code;
        IntPtr method = grid.method;
        GUIControllerDynamicGridNavigator.GetCollectionCount menuItemCount = this._menuItemCount;
        IntPtr invoke_impl2 = menuItemCount.invoke_impl;
        IntPtr method_code2 = menuItemCount.method_code;
        IntPtr method2 = menuItemCount.method;
        GUIControllerDynamicGridNavigator.GetCollectionCount displayItemCount = this._displayItemCount;
        IntPtr invoke_impl3 = displayItemCount.invoke_impl;
        IntPtr method_code3 = displayItemCount.method_code;
        IntPtr method3 = displayItemCount.method;
        int menuColumn = this.MenuColumn;
        int num = this.scrollOffset;
        this.itemRow = num;
        this.inMenu = invoke_impl3 != 0;
        this.ClampPosition();
    }
References _displayItemCount, _grid, _menuItemCount, ClampPosition(), j__TPar, MenuColumn, and scrollOffset.
Referenced by GUIControllerCrafting4Page.NavigateInto(), GUIControllerCraftingGuide.NavigateInto(), GUIControllerCraftingGuidePopup.NavigateInto(), GUIControllerHousing4Page.NavigateInto(), GUIControllerItemDuplication4Page.NavigateInto(), GUIControllerPVP4Page.NavigateInto(), GUIControllerReforge4Page.NavigateInto(), and GUIControllerResearchPage4Page.NavigateInto().