terraria-cpp2il-methodrecon: UnityEngine.UI.Dropdown.SetupTemplate
SetupTemplate()
void UnityEngine.UI.Dropdown.SetupTemplate (Canvas rootCanvas) inline private
Definition at line 285 of file Dropdown.cs.
        {
            int num = 1;
            RectTransform template = this.m_Template;
            if (num == 0)
            {
            }
            bool flag = template;
            GameObject gameObject = this.m_Template.gameObject;
            int num2 = 1;
            int num3 = 1;
            gameObject.SetActive(num2 != 0);
            Toggle componentInChildren = this.m_Template.GetComponentInChildren<Toggle>();
            this.validTemplate = num3 != 0;
            bool flag2 = componentInChildren;
            Transform transform = componentInChildren.transform;
            RectTransform template2 = this.m_Template;
            bool flag3 = transform == template2;
            RectTransform template3 = this.m_Template;
            Debug.LogError("The dropdown template is not valid. The template must have a child GameObject with a Toggle component serving as the item.", template3);
            if (this.validTemplate)
            {
                Dropdown.DropdownItem dropdownItem = componentInChildren.gameObject.AddComponent<Dropdown.DropdownItem>();
                Text itemText = this.m_ItemText;
                dropdownItem.m_Toggle = componentInChildren;
                Transform transform2 = componentInChildren.transform;
                if (transform2 != null)
                {
                }
                dropdownItem.m_RectTransform = transform2;
                Canvas component = this.m_Template.parent.GetComponent<Canvas>();
                Canvas canvas = gameObject.AddComponent<Canvas>();
                int num4 = 1;
                canvas.overrideSorting = num4 != 0;
                int num5 = 30000;
                canvas.sortingOrder = num5;
                int sortingLayerID = rootCanvas.sortingLayerID;
                canvas.sortingLayerID = sortingLayerID;
                BaseRaycaster rootRaycaster = component.GetComponents<BaseRaycaster>().m_RootRaycaster;
                Type type;
                Component component2 = gameObject.GetComponent(type);
                Component component3 = gameObject.AddComponent(type);
                return;
            }
        }
References UnityEngine.GameObject.AddComponent(), UnityEngine.Component.gameObject, UnityEngine.Component.GetComponent(), UnityEngine.GameObject.GetComponent(), UnityEngine.Component.GetComponentInChildren(), UnityEngine.Component.GetComponents(), UnityEngine.UI.Dropdown.itemText, j__TPar, UnityEngine.Debug.LogError(), UnityEngine.UI.Dropdown.m_ItemText, UnityEngine.UI.Dropdown.m_Template, UnityEngine.Transform.parent, UnityEngine.GameObject.SetActive(), UnityEngine.Canvas.sortingLayerID, UnityEngine.Component.transform, and UnityEngine.UI.Dropdown.validTemplate.