terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_PumpkinMoon
RegisterBoss_PumpkinMoon()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_PumpkinMoon () inline private
Definition at line 374 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule2;
            IItemDropRule itemDropRule = this.RegisterToNPC(315, itemDropRule2);
            long num = 0L;
            IItemDropRule itemDropRule4;
            IItemDropRule itemDropRule5;
            IItemDropRule itemDropRule3 = itemDropRule4.OnSuccess(itemDropRule5, num != 0L);
            IItemDropRule itemDropRule6 = ItemDropRule.Common(1835, 1, 1, 1);
            IItemDropRule itemDropRule7 = ItemDropRule.Common(1836, 1, 30, 60);
            IItemDropRule itemDropRule8 = itemDropRule6.OnSuccess(itemDropRule7, true);
            IItemDropRule itemDropRule9 = ItemDropRule.Common(1829, 1, 1, 1);
            if (itemDropRule9 == null || itemDropRule9 != null)
            {
                IItemDropRule itemDropRule10 = ItemDropRule.Common(1831, 1, 1, 1);
                if ((itemDropRule10 == null || itemDropRule10 != null) && (itemDropRule6 == null || itemDropRule6 != null))
                {
                    IItemDropRule itemDropRule11 = ItemDropRule.Common(1837, 1, 1, 1);
                    if (itemDropRule11 == null || itemDropRule11 != null)
                    {
                        IItemDropRule itemDropRule12 = ItemDropRule.Common(1845, 1, 1, 1);
                        if (itemDropRule12 == null || itemDropRule12 != null)
{
                            long num2 = 0L;
                            IItemDropRule itemDropRule14;
                            IItemDropRule itemDropRule15;
                            IItemDropRule itemDropRule13 = itemDropRule14.OnSuccess(itemDropRule15, num2 != 0L);
                            long num3 = 0L;
                            IItemDropRule itemDropRule17;
                            IItemDropRule itemDropRule16 = itemDropRule14.OnSuccess(itemDropRule17, num3 != 0L);
                            IItemDropRule itemDropRule18 = ItemDropRule.MasterModeCommonDrop(4941);
                            long num4 = 0L;
                            IItemDropRule itemDropRule19 = itemDropRule14.OnSuccess(itemDropRule18, num4 != 0L);
                            int masterModeDropRng = this._masterModeDropRng;
                            IItemDropRule itemDropRule20 = ItemDropRule.MasterModeDropOnAllPlayers(4793, masterModeDropRng);
                            long num5 = 0L;
                            IItemDropRule itemDropRule21 = itemDropRule14.OnSuccess(itemDropRule20, num5 != 0L);
                            IItemDropRule itemDropRule22 = ItemDropRule.Common(1782, 1, 1, 1);
                            IItemDropRule itemDropRule23 = ItemDropRule.Common(1783, 1, 50, 100);
                            IItemDropRule itemDropRule24 = itemDropRule22.OnSuccess(itemDropRule23, true);
                            IItemDropRule itemDropRule25 = ItemDropRule.Common(1784, 1, 1, 1);
                            IItemDropRule itemDropRule26 = ItemDropRule.Common(1785, 1, 25, 50);
                            IItemDropRule itemDropRule27 = itemDropRule25.OnSuccess(itemDropRule26, true);
                            if ((itemDropRule22 == null || itemDropRule22 != null) && (itemDropRule25 == null || itemDropRule25 != null))
{
                                IItemDropRule itemDropRule28 = ItemDropRule.Common(1811, 1, 1, 1);
                                if (itemDropRule28 == null || itemDropRule28 != null)
{
                                    IItemDropRule itemDropRule29 = ItemDropRule.Common(1826, 1, 1, 1);
                                    if (itemDropRule29 == null || itemDropRule29 != null)
{
                                        IItemDropRule itemDropRule30 = ItemDropRule.Common(1801, 1, 1, 1);
                                        if (itemDropRule30 == null || itemDropRule30 != null)
{
                                            IItemDropRule itemDropRule31 = ItemDropRule.Common(1802, 1, 1, 1);
                                            if (itemDropRule31 == null || itemDropRule31 != null)
{
                                                IItemDropRule itemDropRule32 = ItemDropRule.Common(4680, 1, 1, 1);
                                                if (itemDropRule32 == null || itemDropRule32 != null)
{
                                                    IItemDropRule itemDropRule33 = ItemDropRule.Common(1798, 1, 1, 1);
                                                    if (itemDropRule33 == null || itemDropRule33 != null)
{
                                                        long num6 = 0L;
                                                        IItemDropRule itemDropRule35;
                                                        IItemDropRule itemDropRule34 = itemDropRule35.OnSuccess(itemDropRule35, num6 != 0L);
                                                        IItemDropRule itemDropRule36 = ItemDropRule.MasterModeCommonDrop(4942);
                                                        long num7 = 0L;
                                                        IItemDropRule itemDropRule38;
                                                        IItemDropRule itemDropRule37 = itemDropRule38.OnSuccess(itemDropRule36, num7 != 0L);
                                                        int masterModeDropRng2 = this._masterModeDropRng;
                                                        IItemDropRule itemDropRule39 = ItemDropRule.MasterModeDropOnAllPlayers(4812, masterModeDropRng2);
                                                        long num8 = 0L;
                                                        IItemDropRule itemDropRule40 = itemDropRule38.OnSuccess(itemDropRule39, num8 != 0L);
                                                        return;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            throw new ArrayTypeMismatchException();
        }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), j__TPar, System.L, Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().