terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss
RegisterBoss_HallowBoss()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss () inline private
Definition at line 350 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule = ItemDropRule.BossBag(4782);
            IItemDropRule itemDropRule2 = ItemDropRule.MasterModeCommonDrop(4949);
            IItemDropRule itemDropRule3 = this.RegisterToNPC(636, itemDropRule2);
            int masterModeDropRng = this._masterModeDropRng;
            IItemDropRule itemDropRule4 = ItemDropRule.MasterModeDropOnAllPlayers(4811, masterModeDropRng);
            IItemDropRule itemDropRule5 = this.RegisterToNPC(636, itemDropRule4);
            long num = 0L;
            IItemDropRule itemDropRule7;
            IItemDropRule itemDropRule8;
            IItemDropRule itemDropRule6 = itemDropRule7.OnSuccess(itemDropRule8, num != 0L);
            IItemDropRule itemDropRule9 = ItemDropRule.Common(4823, 15, 1, 1);
            IItemDropRule itemDropRule10 = ItemDropRule.Common(4778, 4, 1, 1);
            IItemDropRule itemDropRule11 = ItemDropRule.Common(4715, 50, 1, 1);
            IItemDropRule itemDropRule12 = ItemDropRule.Common(4784, 7, 1, 1);
            IItemDropRule itemDropRule13 = ItemDropRule.Common(5075, 20, 1, 1);
            IItemDropRule itemDropRule14 = ItemDropRule.Common(5005, 1, 1, 1);
            long num2 = 0L;
            IItemDropRule itemDropRule16;
            IItemDropRule itemDropRule15 = itemDropRule16.OnSuccess(itemDropRule14, num2 != 0L);
        }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), j__TPar, System.L, Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().