terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPirateDrops
RegisterPirateDrops()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPirateDrops () inline private
Definition at line 1106 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule = ItemDropRule.Common(905, 4000, 1, 1);
            IItemDropRule itemDropRule2 = ItemDropRule.Common(855, 2000, 1, 1);
            IItemDropRule itemDropRule3 = ItemDropRule.Common(854, 1000, 1, 1);
            IItemDropRule itemDropRule4 = ItemDropRule.Common(2584, 1000, 1, 1);
            IItemDropRule itemDropRule5 = ItemDropRule.Common(3033, 500, 1, 1);
            IItemDropRule itemDropRule6 = ItemDropRule.Common(672, 200, 1, 1);
            IItemDropRule itemDropRule7 = ItemDropRule.Common(1277, 500, 1, 1);
            IItemDropRule itemDropRule8 = ItemDropRule.Common(1278, 500, 1, 1);
            IItemDropRule itemDropRule9 = ItemDropRule.Common(1279, 500, 1, 1);
            IItemDropRule itemDropRule10 = ItemDropRule.Common(1280, 500, 1, 1);
            IItemDropRule itemDropRule11 = ItemDropRule.Common(1704, 300, 1, 1);
            IItemDropRule itemDropRule12 = ItemDropRule.Common(1705, 300, 1, 1);
            IItemDropRule itemDropRule13 = ItemDropRule.Common(1710, 300, 1, 1);
            IItemDropRule itemDropRule14 = ItemDropRule.Common(1716, 300, 1, 1);
            IItemDropRule itemDropRule15 = ItemDropRule.Common(1720, 300, 1, 1);
            IItemDropRule itemDropRule16 = ItemDropRule.Common(2379, 300, 1, 1);
            IItemDropRule itemDropRule17 = ItemDropRule.Common(2389, 300, 1, 1);
            IItemDropRule itemDropRule18 = ItemDropRule.Common(2405, 300, 1, 1);
            IItemDropRule itemDropRule19 = ItemDropRule.Common(2843, 300, 1, 1);
            IItemDropRule itemDropRule20 = ItemDropRule.Common(3885, 300, 1, 1);
            IItemDropRule itemDropRule21 = ItemDropRule.Common(2663, 300, 1, 1);
            IItemDropRule itemDropRule22 = ItemDropRule.Common(3904, 150, 80, 130);
            IItemDropRule itemDropRule23 = ItemDropRule.Common(3910, 300, 1, 1);
            IItemDropRule itemDropRule24 = ItemDropRule.Common(2238, 300, 1, 1);
            IItemDropRule itemDropRule25 = ItemDropRule.Common(2133, 300, 1, 1);
            IItemDropRule itemDropRule26 = ItemDropRule.Common(2137, 300, 1, 1);
            IItemDropRule itemDropRule27 = ItemDropRule.Common(2143, 300, 1, 1);
            IItemDropRule itemDropRule28 = ItemDropRule.Common(2147, 300, 1, 1);
            IItemDropRule itemDropRule29 = ItemDropRule.Common(2151, 300, 1, 1);
            IItemDropRule itemDropRule30 = ItemDropRule.Common(2155, 300, 1, 1);
            IItemDropRule itemDropRule31 = ItemDropRule.Common(3263, 500, 1, 1);
            IItemDropRule itemDropRule32 = ItemDropRule.Common(3264, 500, 1, 1);
            IItemDropRule itemDropRule33 = ItemDropRule.Common(3265, 500, 1, 1);
            IItemDropRule itemDropRule34 = ItemDropRule.Common(905, 1000, 1, 1);
            IItemDropRule itemDropRule35 = this.RegisterToNPC(216, itemDropRule34);
            IItemDropRule itemDropRule36 = ItemDropRule.Common(855, 500, 1, 1);
            IItemDropRule itemDropRule37 = this.RegisterToNPC(216, itemDropRule36);
            IItemDropRule itemDropRule38 = ItemDropRule.Common(854, 250, 1, 1);
            IItemDropRule itemDropRule39 = ItemDropRule.Common(2584, 250, 1, 1);
            IItemDropRule itemDropRule40 = this.RegisterToNPC(216, itemDropRule39);
            IItemDropRule itemDropRule41 = ItemDropRule.Common(3033, 125, 1, 1);
            IItemDropRule itemDropRule42 = this.RegisterToNPC(216, itemDropRule41);
            IItemDropRule itemDropRule43 = ItemDropRule.Common(672, 50, 1, 1);
            IItemDropRule itemDropRule44 = this.RegisterToNPC(216, itemDropRule43);
            IItemDropRule itemDropRule45 = ItemDropRule.Common(905, 50, 1, 1);
            IItemDropRule itemDropRule46 = this.RegisterToNPC(491, itemDropRule45);
            IItemDropRule itemDropRule47 = ItemDropRule.Common(855, 15, 1, 1);
            IItemDropRule itemDropRule48 = this.RegisterToNPC(491, itemDropRule47);
            IItemDropRule itemDropRule49 = ItemDropRule.Common(854, 15, 1, 1);
            IItemDropRule itemDropRule50 = this.RegisterToNPC(491, itemDropRule49);
            IItemDropRule itemDropRule51 = ItemDropRule.Common(2584, 15, 1, 1);
            IItemDropRule itemDropRule52 = this.RegisterToNPC(491, itemDropRule51);
            IItemDropRule itemDropRule53 = ItemDropRule.Common(3033, 15, 1, 1);
            IItemDropRule itemDropRule54 = this.RegisterToNPC(491, itemDropRule53);
            IItemDropRule itemDropRule55 = ItemDropRule.Common(4471, 20, 1, 1);
            IItemDropRule itemDropRule56 = this.RegisterToNPC(491, itemDropRule55);
            IItemDropRule itemDropRule57 = ItemDropRule.Common(672, 10, 1, 1);
            IItemDropRule itemDropRule58 = this.RegisterToNPC(491, itemDropRule57);
            IItemDropRule itemDropRule59 = ItemDropRule.MasterModeCommonDrop(4940);
            IItemDropRule itemDropRule60 = this.RegisterToNPC(491, itemDropRule59);
            int masterModeDropRng = this._masterModeDropRng;
            IItemDropRule itemDropRule61 = ItemDropRule.MasterModeDropOnAllPlayers(4792, masterModeDropRng);
            IItemDropRule itemDropRule62 = this.RegisterToNPC(491, itemDropRule61);
            IItemDropRule itemDropRule64;
            IItemDropRule itemDropRule63 = this.RegisterToNPC(491, itemDropRule64);
        }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), j__TPar, Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().