terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_WOF
RegisterBoss_WOF()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_WOF () inline private
Definition at line 787 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule = ItemDropRule.BossBag(3324);
            IItemDropRule itemDropRule2 = this.RegisterToNPC(113, itemDropRule);
            IItemDropRule itemDropRule3 = ItemDropRule.MasterModeCommonDrop(4930);
            IItemDropRule itemDropRule4 = this.RegisterToNPC(113, itemDropRule3);
            int masterModeDropRng = this._masterModeDropRng;
            IItemDropRule itemDropRule5 = ItemDropRule.MasterModeDropOnAllPlayers(4795, masterModeDropRng);
            IItemDropRule itemDropRule6 = this.RegisterToNPC(113, itemDropRule5);
            IItemDropRule itemDropRule8;
            IItemDropRule itemDropRule7 = this.RegisterToNPC(113, itemDropRule8);
            IItemDropRule itemDropRule10;
            IItemDropRule itemDropRule9 = this.RegisterToNPC(113, itemDropRule10);
            long num = 0L;
            IItemDropRule itemDropRule12;
            IItemDropRule itemDropRule13;
            IItemDropRule itemDropRule11 = itemDropRule12.OnSuccess(itemDropRule13, num != 0L);
            long num2 = 0L;
            IItemDropRule itemDropRule15;
            IItemDropRule itemDropRule16;
            IItemDropRule itemDropRule14 = itemDropRule15.OnSuccess(itemDropRule16, num2 != 0L);
        }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), j__TPar, System.L, Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().