terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossTrophies
RegisterBossTrophies()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossTrophies () inline private
Definition at line 1181 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule2;
            IItemDropRule itemDropRule = this.RegisterToNPC(4, itemDropRule2);
            IItemDropRule itemDropRule4;
            IItemDropRule itemDropRule3 = this.RegisterToNPC(13, itemDropRule4);
            IItemDropRule itemDropRule6;
            IItemDropRule itemDropRule5 = this.RegisterToNPC(14, itemDropRule6);
            IItemDropRule itemDropRule8;
            IItemDropRule itemDropRule7 = this.RegisterToNPC(15, itemDropRule8);
            IItemDropRule itemDropRule10;
            IItemDropRule itemDropRule9 = this.RegisterToNPC(266, itemDropRule10);
            IItemDropRule itemDropRule12;
            IItemDropRule itemDropRule11 = this.RegisterToNPC(35, itemDropRule12);
            IItemDropRule itemDropRule14;
            IItemDropRule itemDropRule13 = this.RegisterToNPC(222, itemDropRule14);
            IItemDropRule itemDropRule16;
            IItemDropRule itemDropRule15 = this.RegisterToNPC(113, itemDropRule16);
            IItemDropRule itemDropRule18;
            IItemDropRule itemDropRule17 = this.RegisterToNPC(134, itemDropRule18);
            IItemDropRule itemDropRule20;
            IItemDropRule itemDropRule19 = this.RegisterToNPC(127, itemDropRule20);
            IItemDropRule itemDropRule22;
            IItemDropRule itemDropRule21 = this.RegisterToNPC(262, itemDropRule22);
            IItemDropRule itemDropRule24;
            IItemDropRule itemDropRule23 = this.RegisterToNPC(245, itemDropRule24);
            IItemDropRule itemDropRule26;
            IItemDropRule itemDropRule25 = this.RegisterToNPC(50, itemDropRule26);
            IItemDropRule itemDropRule28;
            IItemDropRule itemDropRule27 = this.RegisterToNPC(439, itemDropRule28);
            IItemDropRule itemDropRule30;
            IItemDropRule itemDropRule29 = this.RegisterToNPC(395, itemDropRule30);
            IItemDropRule itemDropRule32;
            IItemDropRule itemDropRule31 = this.RegisterToNPC(398, itemDropRule32);
            IItemDropRule itemDropRule34;
            IItemDropRule itemDropRule33 = this.RegisterToNPC(636, itemDropRule34);
            IItemDropRule itemDropRule36;
            IItemDropRule itemDropRule35 = this.RegisterToNPC(657, itemDropRule36);
            IItemDropRule itemDropRule38;
            IItemDropRule itemDropRule37 = this.RegisterToNPC(668, itemDropRule38);
            IItemDropRule itemDropRule39 = ItemDropRule.Common(1368, 10, 1, 1);
            IItemDropRule itemDropRule40 = this.RegisterToNPC(125, itemDropRule39);
            IItemDropRule itemDropRule41 = ItemDropRule.Common(1369, 10, 1, 1);
            IItemDropRule itemDropRule42 = this.RegisterToNPC(126, itemDropRule41);
            IItemDropRule itemDropRule43 = ItemDropRule.Common(3359, 10, 1, 1);
            IItemDropRule itemDropRule44 = this.RegisterToNPC(491, itemDropRule43);
            IItemDropRule itemDropRule45 = ItemDropRule.Common(3866, 10, 1, 1);
            IItemDropRule itemDropRule46 = this.RegisterToNPC(551, itemDropRule45);
            IItemDropRule itemDropRule47 = ItemDropRule.Common(3867, 10, 1, 1);
            IItemDropRule itemDropRule48 = this.RegisterToNPC(564, itemDropRule47);
            IItemDropRule itemDropRule49 = ItemDropRule.Common(3867, 10, 1, 1);
            IItemDropRule itemDropRule50 = this.RegisterToNPC(565, itemDropRule49);
            IItemDropRule itemDropRule51 = ItemDropRule.Common(3868, 10, 1, 1);
            IItemDropRule itemDropRule52 = this.RegisterToNPC(576, itemDropRule51);
            IItemDropRule itemDropRule53 = ItemDropRule.Common(3868, 10, 1, 1);
            IItemDropRule itemDropRule54 = this.RegisterToNPC(577, itemDropRule53);
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), j__TPar, and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().