terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterEclipse
RegisterEclipse()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterEclipse () inline private
Definition at line 169 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule = ItemDropRule.ExpertGetsRerolls(497, 50, 1);
            IItemDropRule itemDropRule2 = this.RegisterToNPC(461, itemDropRule);
            IItemDropRule itemDropRule3 = ItemDropRule.ExpertGetsRerolls(900, 35, 1);
            IItemDropRule itemDropRule4 = ItemDropRule.ExpertGetsRerolls(1311, 15, 1);
            IItemDropRule itemDropRule5 = this.RegisterToNPC(251, itemDropRule4);
            IItemDropRule itemDropRule6 = ItemDropRule.Common(5239, 15, 1, 1);
            IItemDropRule itemDropRule7 = this.RegisterToNPC(251, itemDropRule6);
            IItemDropRule itemDropRule8 = ItemDropRule.Common(5236, 15, 1, 1);
            IItemDropRule itemDropRule9 = this.RegisterToNPC(251, itemDropRule8);
            IItemDropRule itemDropRule10 = ItemDropRule.Common(5237, 15, 1, 1);
            IItemDropRule itemDropRule11 = this.RegisterToNPC(477, itemDropRule10);
            IItemDropRule itemDropRule12 = ItemDropRule.Common(5223, 60, 1, 1);
            IItemDropRule itemDropRule13 = this.RegisterToNPC(253, itemDropRule12);
            IItemDropRule itemDropRule14 = ItemDropRule.Common(5227, 60, 1, 1);
            IItemDropRule itemDropRule15 = this.RegisterToNPC(460, itemDropRule14);
            IItemDropRule itemDropRule16 = ItemDropRule.Common(5260, 60, 1, 1);
            IItemDropRule itemDropRule17 = this.RegisterToNPC(469, itemDropRule16);
            IItemDropRule itemDropRule18 = ItemDropRule.Common(5261, 450, 1, 1);
            IItemDropRule itemDropRule19 = ItemDropRule.Common(5262, 60, 1, 1);
            IItemDropRule itemDropRule20 = this.RegisterToNPC(462, itemDropRule19);
            IItemDropRule itemDropRule21 = ItemDropRule.ExpertGetsRerolls(1570, 4, 1);
            long num = 0L;
            IItemDropRule itemDropRule23;
            IItemDropRule itemDropRule22 = itemDropRule23.OnSuccess(itemDropRule21, num != 0L);
            IItemDropRule itemDropRule24 = ItemDropRule.ExpertGetsRerolls(2770, 20, 1);
            long num2 = 0L;
            IItemDropRule itemDropRule26;
            IItemDropRule itemDropRule25 = itemDropRule26.OnSuccess(itemDropRule24, num2 != 0L);
            IItemDropRule itemDropRule27 = ItemDropRule.ExpertGetsRerolls(3292, 3, 1);
            long num3 = 0L;
            IItemDropRule itemDropRule28 = itemDropRule26.OnSuccess(itemDropRule27, num3 != 0L);
            IItemDropRule itemDropRule29 = ItemDropRule.ExpertGetsRerolls(1327, 40, 1);
            long num4 = 0L;
            IItemDropRule itemDropRule31;
            IItemDropRule itemDropRule30 = itemDropRule31.OnSuccess(itemDropRule29, num4 != 0L);
            IItemDropRule itemDropRule32 = ItemDropRule.ExpertGetsRerolls(3098, 40, 1);
            long num5 = 0L;
            IItemDropRule itemDropRule33 = itemDropRule32.OnSuccess(itemDropRule32, num5 != 0L);
            IItemDropRule itemDropRule34 = ItemDropRule.ExpertGetsRerolls(4740, 50, 1);
            IItemDropRule itemDropRule35 = this.RegisterToNPC(460, itemDropRule34);
            IItemDropRule itemDropRule36 = ItemDropRule.ExpertGetsRerolls(4741, 50, 1);
            IItemDropRule itemDropRule37 = this.RegisterToNPC(460, itemDropRule36);
            IItemDropRule itemDropRule38 = ItemDropRule.ExpertGetsRerolls(4742, 50, 1);
            IItemDropRule itemDropRule39 = this.RegisterToNPC(460, itemDropRule38);
            IItemDropRule itemDropRule40 = ItemDropRule.ExpertGetsRerolls(3105, 40, 1);
            long num6 = 0L;
            IItemDropRule itemDropRule42;
            IItemDropRule itemDropRule41 = itemDropRule42.OnSuccess(itemDropRule40, num6 != 0L);
            IItemDropRule itemDropRule43 = ItemDropRule.ExpertGetsRerolls(4738, 50, 1);
            IItemDropRule itemDropRule44 = this.RegisterToNPC(468, itemDropRule43);
            IItemDropRule itemDropRule45 = ItemDropRule.ExpertGetsRerolls(4739, 50, 1);
            IItemDropRule itemDropRule46 = this.RegisterToNPC(468, itemDropRule45);
            IItemDropRule itemDropRule47 = ItemDropRule.ExpertGetsRerolls(3106, 40, 1);
            long num7 = 0L;
            IItemDropRule itemDropRule49;
            IItemDropRule itemDropRule48 = itemDropRule49.OnSuccess(itemDropRule47, num7 != 0L);
            IItemDropRule itemDropRule50 = ItemDropRule.ExpertGetsRerolls(3249, 30, 1);
            long num8 = 0L;
            IItemDropRule itemDropRule52;
            IItemDropRule itemDropRule51 = itemDropRule52.OnSuccess(itemDropRule50, num8 != 0L);
            IItemDropRule itemDropRule53 = ItemDropRule.Common(3107, 25, 1, 1);
            IItemDropRule itemDropRule54 = ItemDropRule.WithRerolls(3107, 1, 25, 1, 1);
            IItemDropRule itemDropRule55 = ItemDropRule.Common(3108, 1, 100, 200);
            IItemDropRule itemDropRule56 = itemDropRule53.OnSuccess(itemDropRule55, true);
            IItemDropRule itemDropRule57 = ItemDropRule.Common(3108, 1, 100, 200);
            IItemDropRule itemDropRule58 = itemDropRule54.OnSuccess(itemDropRule57, true);
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.ExpertGetsRerolls(), j__TPar, System.L, Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC(), and Terraria.GameContent.ItemDropRules.ItemDropRule.WithRerolls().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().