terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeDungeonDrops
RegisterHardmodeDungeonDrops()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeDungeonDrops () inline private
Definition at line 271 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule = ItemDropRule.ExpertGetsRerolls(1513, 15, 1);
            IItemDropRule itemDropRule2 = this.RegisterToNPC(290, itemDropRule);
            IItemDropRule itemDropRule3 = ItemDropRule.ExpertGetsRerolls(938, 10, 1);
            IItemDropRule itemDropRule4 = this.RegisterToNPC(290, itemDropRule3);
            IItemDropRule itemDropRule5 = ItemDropRule.ExpertGetsRerolls(977, 12, 1);
            IItemDropRule itemDropRule6 = this.RegisterToNPC(287, itemDropRule5);
            IItemDropRule itemDropRule7 = ItemDropRule.ExpertGetsRerolls(963, 12, 1);
            IItemDropRule itemDropRule8 = this.RegisterToNPC(287, itemDropRule7);
            IItemDropRule itemDropRule9 = ItemDropRule.ExpertGetsRerolls(1300, 12, 1);
            IItemDropRule itemDropRule10 = this.RegisterToNPC(291, itemDropRule9);
            IItemDropRule itemDropRule11 = ItemDropRule.ExpertGetsRerolls(1254, 12, 1);
            IItemDropRule itemDropRule12 = this.RegisterToNPC(291, itemDropRule11);
            IItemDropRule itemDropRule13 = ItemDropRule.ExpertGetsRerolls(1514, 12, 1);
            IItemDropRule itemDropRule14 = this.RegisterToNPC(292, itemDropRule13);
            IItemDropRule itemDropRule15 = ItemDropRule.ExpertGetsRerolls(679, 12, 1);
            IItemDropRule itemDropRule16 = this.RegisterToNPC(292, itemDropRule15);
            IItemDropRule itemDropRule17 = ItemDropRule.ExpertGetsRerolls(759, 18, 1);
            IItemDropRule itemDropRule18 = this.RegisterToNPC(293, itemDropRule17);
            IItemDropRule itemDropRule19 = ItemDropRule.ExpertGetsRerolls(4789, 25, 1);
            IItemDropRule itemDropRule20 = this.RegisterToNPC(289, itemDropRule19);
            IItemDropRule itemDropRule21 = ItemDropRule.ExpertGetsRerolls(1446, 20, 1);
            IItemDropRule itemDropRule22 = ItemDropRule.ExpertGetsRerolls(1444, 20, 1);
            IItemDropRule itemDropRule23 = ItemDropRule.ExpertGetsRerolls(1445, 20, 1);
            IItemDropRule itemDropRule24 = ItemDropRule.ExpertGetsRerolls(1183, 400, 1);
            IItemDropRule itemDropRule25 = ItemDropRule.ExpertGetsRerolls(1266, 300, 1);
            IItemDropRule itemDropRule26 = ItemDropRule.ExpertGetsRerolls(671, 200, 1);
            IItemDropRule itemDropRule27 = ItemDropRule.ExpertGetsRerolls(2273, 200, 1);
            IItemDropRule itemDropRule28 = ItemDropRule.ExpertGetsRerolls(4679, 200, 1);
            IItemDropRule itemDropRule29 = ItemDropRule.Common(1508, 1, 1, 2);
            IItemDropRule itemDropRule30 = this.RegisterToNPC(288, itemDropRule29);
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.ExpertGetsRerolls(), j__TPar, and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().