terraria-cpp2il-methodrecon: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMiscDrops
RegisterMiscDrops()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMiscDrops () inline private
Definition at line 1264 of file ItemDropDatabase.cs.
        {
            IItemDropRule itemDropRule = ItemDropRule.Common(1169, 1, 1, 1);
            IItemDropRule itemDropRule2 = this.RegisterToNPC(68, itemDropRule);
            IItemDropRule itemDropRule3 = ItemDropRule.Common(3086, 1, 5, 10);
            IItemDropRule itemDropRule4 = ItemDropRule.Common(723, 150, 1, 1);
            IItemDropRule itemDropRule5 = this.RegisterToNPC(77, itemDropRule4);
            IItemDropRule itemDropRule6 = ItemDropRule.NormalvsExpert(3102, 2, 1);
            IItemDropRule itemDropRule8;
            IItemDropRule itemDropRule7 = this.RegisterToNPC(471, itemDropRule8);
            IItemDropRule itemDropRule9 = ItemDropRule.Common(1328, 12, 1, 1);
            IItemDropRule itemDropRule10 = this.RegisterToNPC(153, itemDropRule9);
            IItemDropRule itemDropRule11 = ItemDropRule.Common(23, 1, 1, 2);
            long num = 0L;
            IItemDropRule itemDropRule13;
            IItemDropRule itemDropRule12 = itemDropRule13.OnSuccess(itemDropRule11, num != 0L);
            IItemDropRule itemDropRule14 = ItemDropRule.NormalvsExpert(1309, 8000, 5600);
            long num2 = 0L;
            IItemDropRule itemDropRule16;
            IItemDropRule itemDropRule15 = itemDropRule16.OnSuccess(itemDropRule14, num2 != 0L);
            IItemDropRule itemDropRule17 = ItemDropRule.Common(1326, 100, 1, 1);
            long num3 = 0L;
            IItemDropRule itemDropRule19;
            IItemDropRule itemDropRule18 = itemDropRule19.OnSuccess(itemDropRule17, num3 != 0L);
            IItemDropRule itemDropRule20 = ItemDropRule.NormalvsExpert(1326, 500, 400);
            long num4 = 0L;
            IItemDropRule itemDropRule22;
            IItemDropRule itemDropRule21 = itemDropRule22.OnSuccess(itemDropRule20, num4 != 0L);
            IItemDropRule itemDropRule23 = ItemDropRule.Common(1325, 250, 1, 1);
            long num5 = 0L;
            IItemDropRule itemDropRule25;
            IItemDropRule itemDropRule24 = itemDropRule25.OnSuccess(itemDropRule23, num5 != 0L);
            IItemDropRule itemDropRule26 = ItemDropRule.Common(1314, 250, 1, 1);
            long num6 = 0L;
            IItemDropRule itemDropRule28;
            IItemDropRule itemDropRule27 = itemDropRule28.OnSuccess(itemDropRule26, num6 != 0L);
            IItemDropRule itemDropRule29 = ItemDropRule.Common(1314, 5, 1, 1);
            long num7 = 0L;
            IItemDropRule itemDropRule31;
            IItemDropRule itemDropRule30 = itemDropRule31.OnSuccess(itemDropRule29, num7 != 0L);
            IItemDropRule itemDropRule32 = ItemDropRule.Common(1325, 5, 1, 1);
            long num8 = 0L;
            IItemDropRule itemDropRule34;
            IItemDropRule itemDropRule33 = itemDropRule34.OnSuccess(itemDropRule32, num8 != 0L);
            IItemDropRule itemDropRule35 = ItemDropRule.Common(683, 30, 1, 1);
            long num9 = 0L;
            IItemDropRule itemDropRule37;
            IItemDropRule itemDropRule36 = itemDropRule37.OnSuccess(itemDropRule35, num9 != 0L);
            IItemDropRule itemDropRule38 = ItemDropRule.Common(112, 30, 1, 1);
            long num10 = 0L;
            IItemDropRule itemDropRule40;
            IItemDropRule itemDropRule39 = itemDropRule40.OnSuccess(itemDropRule38, num10 != 0L);
            IItemDropRule itemDropRule41 = ItemDropRule.Common(4764, 40, 1, 1);
            IItemDropRule itemDropRule42 = this.RegisterToNPC(634, itemDropRule41);
            IItemDropRule itemDropRule43 = ItemDropRule.Common(951, 150, 1, 1);
            IItemDropRule itemDropRule44 = this.RegisterToNPC(185, itemDropRule43);
            IItemDropRule itemDropRule45 = ItemDropRule.Common(5070, 1, 1, 2);
            IItemDropRule itemDropRule46 = ItemDropRule.Common(1320, 20, 1, 1);
            IItemDropRule itemDropRule47 = this.RegisterToNPC(44, itemDropRule46);
            IItemDropRule itemDropRule48 = ItemDropRule.Common(88, 20, 1, 1);
            IItemDropRule itemDropRule49 = this.RegisterToNPC(44, itemDropRule48);
            IItemDropRule itemDropRule50 = ItemDropRule.Common(1322, 150, 1, 1);
            IItemDropRule itemDropRule51 = this.RegisterToNPC(60, itemDropRule50);
            IItemDropRule itemDropRule52 = ItemDropRule.Common(1322, 50, 1, 1);
            IItemDropRule itemDropRule53 = this.RegisterToNPC(151, itemDropRule52);
            IItemDropRule itemDropRule54 = ItemDropRule.Common(1323, 20, 1, 1);
            IItemDropRule itemDropRule55 = this.RegisterToNPC(24, itemDropRule54);
            IItemDropRule itemDropRule56 = ItemDropRule.Common(1324, 10, 1, 1);
            IItemDropRule itemDropRule57 = this.RegisterToNPC(109, itemDropRule56);
            IItemDropRule itemDropRule58 = ItemDropRule.Common(4271, 10, 1, 1);
            IItemDropRule itemDropRule59 = this.RegisterToNPC(109, itemDropRule58);
            IItemDropRule itemDropRule60 = ItemDropRule.Common(1308, 40, 1, 1);
            IItemDropRule itemDropRule61 = ItemDropRule.Common(2607, 2, 1, 3);
            IItemDropRule itemDropRule62 = ItemDropRule.Common(1306, 100, 1, 1);
            IItemDropRule itemDropRule63 = ItemDropRule.Common(23, 1, 1, 20);
            IItemDropRule itemDropRule64 = this.RegisterToNPC(244, itemDropRule63);
            IItemDropRule itemDropRule65 = ItemDropRule.Common(662, 1, 30, 60);
            IItemDropRule itemDropRule66 = this.RegisterToNPC(244, itemDropRule65);
            IItemDropRule itemDropRule67 = ItemDropRule.Common(1244, 15, 1, 1);
            IItemDropRule itemDropRule68 = this.RegisterToNPC(250, itemDropRule67);
            IItemDropRule itemDropRule69 = ItemDropRule.Common(754, 1, 1, 1);
            IItemDropRule itemDropRule70 = this.RegisterToNPC(172, itemDropRule69);
            IItemDropRule itemDropRule71 = ItemDropRule.Common(755, 1, 1, 1);
            IItemDropRule itemDropRule72 = this.RegisterToNPC(172, itemDropRule71);
            IItemDropRule itemDropRule73 = ItemDropRule.Common(682, 200, 1, 1);
            IItemDropRule itemDropRule74 = this.RegisterToNPC(110, itemDropRule73);
            IItemDropRule itemDropRule75 = ItemDropRule.Common(1321, 40, 1, 1);
            IItemDropRule itemDropRule76 = this.RegisterToNPC(110, itemDropRule75);
            IItemDropRule itemDropRule77 = ItemDropRule.Common(4428, 100, 1, 1);
            IItemDropRule itemDropRule78 = ItemDropRule.Common(1253, 50, 1, 1);
            IItemDropRule itemDropRule79 = this.RegisterToNPC(154, itemDropRule78);
            IItemDropRule itemDropRule80 = ItemDropRule.Common(726, 50, 1, 1);
            IItemDropRule itemDropRule81 = ItemDropRule.Common(2161, 1, 1, 1);
            IItemDropRule itemDropRule82 = this.RegisterToNPC(243, itemDropRule81);
            IItemDropRule itemDropRule83 = ItemDropRule.NormalvsExpert(5130, 30, 25);
            IItemDropRule itemDropRule84 = this.RegisterToNPC(155, itemDropRule83);
            IItemDropRule itemDropRule85 = ItemDropRule.Common(3269, 25, 1, 1);
            IItemDropRule itemDropRule86 = this.RegisterToNPC(480, itemDropRule85);
            IItemDropRule itemDropRule87 = ItemDropRule.NormalvsExpert(3781, 40, 20);
            IItemDropRule itemDropRule88 = this.RegisterToNPC(480, itemDropRule87);
            IItemDropRule itemDropRule89 = ItemDropRule.Common(1172, 1000, 1, 1);
            IItemDropRule itemDropRule90 = ItemDropRule.Common(1293, 50, 1, 1);
            IItemDropRule itemDropRule91 = ItemDropRule.Common(2766, 7, 1, 2);
            IItemDropRule itemDropRule92 = ItemDropRule.Common(870, 75, 1, 1);
            IItemDropRule itemDropRule93 = ItemDropRule.Common(871, 75, 1, 1);
            IItemDropRule itemDropRule94 = ItemDropRule.Common(872, 75, 1, 1);
            IItemDropRule itemDropRule96;
            IItemDropRule itemDropRule95 = this.RegisterToNPC(473, itemDropRule96);
            IItemDropRule itemDropRule98;
            IItemDropRule itemDropRule97 = this.RegisterToNPC(474, itemDropRule98);
            IItemDropRule itemDropRule100;
            IItemDropRule itemDropRule99 = this.RegisterToNPC(475, itemDropRule100);
            IItemDropRule itemDropRule101 = ItemDropRule.Common(52, 3, 1, 1);
            IItemDropRule itemDropRule102 = this.RegisterToNPC(476, itemDropRule101);
            IItemDropRule itemDropRule103 = ItemDropRule.Common(1724, 3, 1, 1);
            IItemDropRule itemDropRule104 = this.RegisterToNPC(476, itemDropRule103);
            IItemDropRule itemDropRule105 = ItemDropRule.Common(2353, 3, 5, 10);
            IItemDropRule itemDropRule106 = this.RegisterToNPC(476, itemDropRule105);
            IItemDropRule itemDropRule108;
            IItemDropRule itemDropRule107 = this.RegisterToNPC(476, itemDropRule108);
            IItemDropRule itemDropRule109 = ItemDropRule.Common(678, 3, 3, 5);
            IItemDropRule itemDropRule110 = this.RegisterToNPC(476, itemDropRule109);
            IItemDropRule itemDropRule111 = ItemDropRule.Common(1336, 3, 1, 1);
            IItemDropRule itemDropRule112 = this.RegisterToNPC(476, itemDropRule111);
            IItemDropRule itemDropRule113 = ItemDropRule.Common(2676, 3, 2, 4);
            IItemDropRule itemDropRule114 = this.RegisterToNPC(476, itemDropRule113);
            IItemDropRule itemDropRule115 = ItemDropRule.Common(2272, 3, 1, 1);
            IItemDropRule itemDropRule116 = this.RegisterToNPC(476, itemDropRule115);
            IItemDropRule itemDropRule117 = ItemDropRule.Common(5395, 3, 1, 1);
            IItemDropRule itemDropRule118 = this.RegisterToNPC(476, itemDropRule117);
            IItemDropRule itemDropRule119 = ItemDropRule.Common(4986, 3, 69, 69);
            IItemDropRule itemDropRule120 = this.RegisterToNPC(476, itemDropRule119);
            IItemDropRule itemDropRule121 = ItemDropRule.Common(499, 1, 5, 10);
            IItemDropRule itemDropRule122 = ItemDropRule.Common(500, 1, 5, 15);
            IItemDropRule itemDropRule123 = ItemDropRule.Common(575, 1, 5, 10);
            IItemDropRule itemDropRule124 = ItemDropRule.Common(575, 1, 10, 20);
            IItemDropRule itemDropRule125 = ItemDropRule.Common(1115, 1, 1, 1);
            IItemDropRule itemDropRule126 = this.RegisterToNPC(217, itemDropRule125);
            IItemDropRule itemDropRule127 = ItemDropRule.Common(1116, 1, 1, 1);
            IItemDropRule itemDropRule128 = this.RegisterToNPC(218, itemDropRule127);
            IItemDropRule itemDropRule129 = ItemDropRule.Common(1117, 1, 1, 1);
            IItemDropRule itemDropRule130 = this.RegisterToNPC(219, itemDropRule129);
            IItemDropRule itemDropRule131 = ItemDropRule.Common(1118, 1, 1, 1);
            IItemDropRule itemDropRule132 = this.RegisterToNPC(220, itemDropRule131);
            IItemDropRule itemDropRule133 = ItemDropRule.Common(1119, 1, 1, 1);
            IItemDropRule itemDropRule134 = this.RegisterToNPC(221, itemDropRule133);
            IItemDropRule itemDropRule135 = ItemDropRule.Common(879, 50, 1, 1);
            IItemDropRule itemDropRule136 = this.RegisterToNPC(167, itemDropRule135);
            IItemDropRule itemDropRule137 = ItemDropRule.Common(313, 2, 1, 2);
            IItemDropRule itemDropRule138 = this.RegisterToNPC(628, itemDropRule137);
            IItemDropRule itemDropRule139 = ItemDropRule.Common(593, 1, 5, 10);
            IItemDropRule itemDropRule140 = ItemDropRule.Common(527, 10, 1, 1);
            IItemDropRule itemDropRule141 = ItemDropRule.Common(528, 10, 1, 1);
            IItemDropRule itemDropRule142 = this.RegisterToNPC(80, itemDropRule141);
            IItemDropRule itemDropRule143 = ItemDropRule.Common(3794, 10, 1, 3);
            IItemDropRule itemDropRule144 = this.RegisterToNPC(524, itemDropRule143);
            IItemDropRule itemDropRule145 = ItemDropRule.Common(3794, 10, 1, 1);
            IItemDropRule itemDropRule146 = this.RegisterToNPC(525, itemDropRule145);
            IItemDropRule itemDropRule147 = ItemDropRule.Common(522, 3, 1, 3);
            IItemDropRule itemDropRule148 = this.RegisterToNPC(525, itemDropRule147);
            IItemDropRule itemDropRule149 = ItemDropRule.Common(527, 15, 1, 1);
            IItemDropRule itemDropRule150 = this.RegisterToNPC(525, itemDropRule149);
            IItemDropRule itemDropRule151 = ItemDropRule.Common(3794, 10, 1, 1);
            IItemDropRule itemDropRule152 = this.RegisterToNPC(526, itemDropRule151);
            IItemDropRule itemDropRule153 = ItemDropRule.Common(1332, 3, 1, 3);
            IItemDropRule itemDropRule154 = this.RegisterToNPC(526, itemDropRule153);
            IItemDropRule itemDropRule155 = ItemDropRule.Common(527, 15, 1, 1);
            IItemDropRule itemDropRule156 = this.RegisterToNPC(526, itemDropRule155);
            IItemDropRule itemDropRule157 = ItemDropRule.Common(3794, 10, 1, 1);
            IItemDropRule itemDropRule158 = this.RegisterToNPC(527, itemDropRule157);
            IItemDropRule itemDropRule159 = ItemDropRule.Common(528, 15, 1, 1);
            IItemDropRule itemDropRule160 = this.RegisterToNPC(527, itemDropRule159);
            IItemDropRule itemDropRule161 = ItemDropRule.Common(3380, 2, 1, 2);
            IItemDropRule itemDropRule162 = this.RegisterToNPC(513, itemDropRule161);
            IItemDropRule itemDropRule163 = ItemDropRule.Common(3380, 1, 1, 3);
            IItemDropRule itemDropRule164 = this.RegisterToNPC(532, itemDropRule163);
            IItemDropRule itemDropRule165 = ItemDropRule.Common(3771, 50, 1, 1);
            IItemDropRule itemDropRule166 = this.RegisterToNPC(532, itemDropRule165);
            IItemDropRule itemDropRule167 = ItemDropRule.Common(2802, 25, 1, 1);
            IItemDropRule itemDropRule168 = this.RegisterToNPC(528, itemDropRule167);
            IItemDropRule itemDropRule170;
            IItemDropRule itemDropRule169 = this.RegisterToNPC(528, itemDropRule170);
            IItemDropRule itemDropRule171 = ItemDropRule.Common(2801, 25, 1, 1);
            IItemDropRule itemDropRule172 = this.RegisterToNPC(529, itemDropRule171);
            IItemDropRule itemDropRule174;
            IItemDropRule itemDropRule173 = this.RegisterToNPC(529, itemDropRule174);
            IItemDropRule itemDropRule175 = ItemDropRule.Common(18, 100, 1, 1);
            IItemDropRule itemDropRule176 = ItemDropRule.Common(393, 50, 1, 1);
            IItemDropRule itemDropRule177 = ItemDropRule.Common(393, 75, 1, 1);
            IItemDropRule itemDropRule178 = this.RegisterToNPC(58, itemDropRule177);
            IItemDropRule itemDropRule179 = ItemDropRule.Common(18, 80, 1, 1);
            IItemDropRule itemDropRule180 = ItemDropRule.Common(393, 80, 1, 1);
            long num11 = 0L;
            IItemDropRule itemDropRule182;
            IItemDropRule itemDropRule181 = itemDropRule182.OnFailedRoll(itemDropRule180, num11 != 0L);
            IItemDropRule itemDropRule183 = ItemDropRule.Common(3285, 25, 1, 1);
            long num12 = 0L;
            IItemDropRule itemDropRule184 = itemDropRule181.OnFailedRoll(itemDropRule183, num12 != 0L);
            IItemDropRule itemDropRule185 = ItemDropRule.Common(954, 100, 1, 1);
            IItemDropRule itemDropRule186 = ItemDropRule.Common(955, 200, 1, 1);
            long num13 = 0L;
            IItemDropRule itemDropRule188;
            IItemDropRule itemDropRule187 = itemDropRule188.OnFailedRoll(itemDropRule186, num13 != 0L);
            IItemDropRule itemDropRule189 = ItemDropRule.Common(1166, 200, 1, 1);
            long num14 = 0L;
            IItemDropRule itemDropRule190 = itemDropRule187.OnFailedRoll(itemDropRule189, num14 != 0L);
            IItemDropRule itemDropRule191 = ItemDropRule.Common(1274, 500, 1, 1);
            long num15 = 0L;
            IItemDropRule itemDropRule192 = itemDropRule190.OnFailedRoll(itemDropRule191, num15 != 0L);
            IItemDropRule itemDropRule194;
            IItemDropRule itemDropRule193 = this.RegisterToNPC(6, itemDropRule194);
            IItemDropRule itemDropRule195 = ItemDropRule.Common(959, 450, 1, 1);
            IItemDropRule itemDropRule196 = ItemDropRule.Common(1307, 300, 1, 1);
            IItemDropRule itemDropRule197 = ItemDropRule.Common(996, 200, 1, 1);
            IItemDropRule itemDropRule198 = ItemDropRule.Common(522, 1, 2, 5);
            IItemDropRule itemDropRule200;
            IItemDropRule itemDropRule199 = this.RegisterToNPC(98, itemDropRule200);
            IItemDropRule itemDropRule201 = ItemDropRule.Common(526, 1, 1, 1);
            IItemDropRule itemDropRule202 = this.RegisterToNPC(86, itemDropRule201);
            IItemDropRule itemDropRule203 = ItemDropRule.Common(856, 100, 1, 1);
            IItemDropRule itemDropRule204 = this.RegisterToNPC(86, itemDropRule203);
            IItemDropRule itemDropRule206;
            IItemDropRule itemDropRule205 = this.RegisterToNPC(86, itemDropRule206);
            IItemDropRule itemDropRule207 = ItemDropRule.Common(4057, 100, 1, 1);
            IItemDropRule itemDropRule208 = this.RegisterToNPC(224, itemDropRule207);
            IItemDropRule itemDropRule209 = ItemDropRule.Common(40, 1, 1, 9);
            IItemDropRule itemDropRule210 = ItemDropRule.Common(1243, 45, 1, 1);
            IItemDropRule itemDropRule211 = this.RegisterToNPC(225, itemDropRule210);
            IItemDropRule itemDropRule212 = ItemDropRule.Common(23, 1, 2, 6);
            long num16 = 0L;
            IItemDropRule itemDropRule213 = itemDropRule211.OnFailedRoll(itemDropRule212, num16 != 0L);
            IItemDropRule itemDropRule214 = ItemDropRule.Common(23, 1, 2, 3);
            IItemDropRule itemDropRule215 = this.RegisterToNPC(537, itemDropRule214);
            IItemDropRule itemDropRule216 = ItemDropRule.NormalvsExpert(1309, 8000, 5600);
            IItemDropRule itemDropRule217 = this.RegisterToNPC(537, itemDropRule216);
            IItemDropRule itemDropRule218 = ItemDropRule.Common(1906, 20, 1, 1);
            IItemDropRule itemDropRule219 = ItemDropRule.Common(3111, 1, 25, 50);
            IItemDropRule itemDropRule220 = this.RegisterToNPC(1, itemDropRule219);
            IItemDropRule itemDropRule221 = ItemDropRule.NormalvsExpert(1309, 100, 70);
            IItemDropRule itemDropRule222 = this.RegisterToNPC(100, itemDropRule221);
            IItemDropRule itemDropRule223 = ItemDropRule.Common(23, 1, 1, 2);
            IItemDropRule itemDropRule224 = ItemDropRule.Common(23, 1, 2, 5);
            IItemDropRule itemDropRule225 = ItemDropRule.NormalvsExpert(1309, 10000, 7000);
            IItemDropRule itemDropRule226 = ItemDropRule.NormalvsExpert(1309, 10000, 7000);
            IItemDropRule itemDropRule227 = ItemDropRule.Common(501, 1, 1, 3);
            IItemDropRule itemDropRule228 = this.RegisterToNPC(75, itemDropRule227);
            IItemDropRule itemDropRule229 = ItemDropRule.Common(23, 1, 2, 4);
            IItemDropRule itemDropRule230 = ItemDropRule.Common(23, 1, 5, 10);
            IItemDropRule itemDropRule231 = this.RegisterToNPC(122, itemDropRule230);
            IItemDropRule itemDropRule232 = ItemDropRule.Common(327, 1, 1, 1);
            IItemDropRule itemDropRule233 = this.RegisterToNPC(71, itemDropRule232);
            IItemDropRule itemDropRule234 = ItemDropRule.Common(236, 100, 1, 1);
            IItemDropRule itemDropRule235 = ItemDropRule.Common(38, 3, 1, 1);
            long num17 = 0L;
            IItemDropRule itemDropRule237;
            IItemDropRule itemDropRule236 = itemDropRule237.OnFailedRoll(itemDropRule235, num17 != 0L);
            IItemDropRule itemDropRule239;
            IItemDropRule itemDropRule238 = this.RegisterToNPC(133, itemDropRule239);
            IItemDropRule itemDropRule240 = ItemDropRule.Common(485, 60, 1, 1);
            IItemDropRule itemDropRule241 = this.RegisterToNPC(104, itemDropRule240);
            IItemDropRule itemDropRule242 = ItemDropRule.Common(263, 250, 1, 1);
            IItemDropRule itemDropRule243 = this.RegisterToNPC(58, itemDropRule242);
            IItemDropRule itemDropRule244 = ItemDropRule.Common(118, 30, 1, 1);
            long num18 = 0L;
            IItemDropRule itemDropRule245 = itemDropRule243.OnFailedRoll(itemDropRule244, num18 != 0L);
            IItemDropRule itemDropRule246 = ItemDropRule.Common(263, 250, 1, 1);
            IItemDropRule itemDropRule247 = this.RegisterToNPC(102, itemDropRule246);
            IItemDropRule itemDropRule248 = ItemDropRule.Common(216, 50, 1, 1);
            IItemDropRule itemDropRule249 = ItemDropRule.Common(1304, 250, 1, 1);
            IItemDropRule itemDropRule250 = ItemDropRule.Common(5332, 1500, 1, 1);
            IItemDropRule itemDropRule251 = ItemDropRule.NormalvsExpert(3212, 150, 75);
            IItemDropRule itemDropRule252 = ItemDropRule.NormalvsExpert(3213, 200, 100);
            IItemDropRule itemDropRule254;
            IItemDropRule itemDropRule253 = this.RegisterToNPC(223, itemDropRule254);
            IItemDropRule itemDropRule255 = ItemDropRule.Common(267, 1, 1, 1);
            IItemDropRule itemDropRule256 = this.RegisterToNPC(66, itemDropRule255);
            IItemDropRule itemDropRule257 = ItemDropRule.Common(272, 35, 1, 1);
            IItemDropRule itemDropRule258 = ItemDropRule.Common(251, 1, 1, 1);
            IItemDropRule itemDropRule259 = this.RegisterToNPC(52, itemDropRule258);
            IItemDropRule itemDropRule260 = ItemDropRule.Common(239, 1, 1, 1);
            IItemDropRule itemDropRule261 = this.RegisterToNPC(53, itemDropRule260);
            IItemDropRule itemDropRule262 = ItemDropRule.Common(3478, 1, 1, 1);
            IItemDropRule itemDropRule263 = this.RegisterToNPC(536, itemDropRule262);
            IItemDropRule itemDropRule264 = ItemDropRule.Common(3479, 1, 1, 1);
            IItemDropRule itemDropRule265 = this.RegisterToNPC(536, itemDropRule264);
            IItemDropRule itemDropRule266 = ItemDropRule.Common(323, 3, 1, 2);
            IItemDropRule itemDropRule268;
            IItemDropRule itemDropRule267 = this.RegisterToNPC(582, itemDropRule268);
            IItemDropRule itemDropRule269 = ItemDropRule.Common(3772, 50, 1, 1);
            IItemDropRule itemDropRule270 = ItemDropRule.Common(362, 1, 1, 2);
            IItemDropRule itemDropRule271 = this.RegisterToNPC(73, itemDropRule270);
            IItemDropRule itemDropRule272 = ItemDropRule.Common(3109, 30, 1, 1);
            IItemDropRule itemDropRule273 = ItemDropRule.Common(4400, 20, 1, 1);
            IItemDropRule itemDropRule274 = ItemDropRule.Common(68, 3, 1, 1);
            IItemDropRule itemDropRule275 = ItemDropRule.Common(1330, 3, 1, 1);
            IItemDropRule itemDropRule276 = ItemDropRule.Common(68, 3, 1, 2);
            IItemDropRule itemDropRule277 = ItemDropRule.Common(69, 1, 3, 8);
            IItemDropRule itemDropRule278 = ItemDropRule.Common(215, 50, 1, 1);
            IItemDropRule itemDropRule279 = ItemDropRule.WithRerolls(215, 1, 50, 1, 1);
            IItemDropRule itemDropRule280 = ItemDropRule.Common(243, 75, 1, 1);
            IItemDropRule itemDropRule281 = ItemDropRule.Common(3795, 40, 1, 1);
            IItemDropRule itemDropRule282 = this.RegisterToNPC(533, itemDropRule281);
            IItemDropRule itemDropRule283 = ItemDropRule.Common(3770, 30, 1, 1);
            long num19 = 0L;
            IItemDropRule itemDropRule284 = itemDropRule282.OnFailedRoll(itemDropRule283, num19 != 0L);
            IItemDropRule itemDropRule285 = ItemDropRule.Common(1303, 100, 1, 1);
            IItemDropRule itemDropRule286 = ItemDropRule.Common(282, 1, 1, 4);
            IItemDropRule itemDropRule287 = ItemDropRule.Common(282, 1, 1, 4);
            IItemDropRule itemDropRule288 = ItemDropRule.Common(282, 1, 1, 4);
            IItemDropRule itemDropRule290;
            IItemDropRule itemDropRule289 = this.RegisterToNPC(63, itemDropRule290);
            IItemDropRule itemDropRule292;
            IItemDropRule itemDropRule291 = this.RegisterToNPC(64, itemDropRule292);
            IItemDropRule itemDropRule293 = ItemDropRule.Common(3094, 2, 40, 80);
            IItemDropRule itemDropRule294 = this.RegisterToNPC(481, itemDropRule293);
            IItemDropRule itemDropRule296;
            IItemDropRule itemDropRule295 = this.RegisterToNPC(481, itemDropRule296);
            IItemDropRule itemDropRule297 = ItemDropRule.Common(4463, 20, 1, 1);
            IItemDropRule itemDropRule298 = this.RegisterToNPC(481, itemDropRule297);
            IItemDropRule itemDropRule299 = ItemDropRule.Common(118, 25, 1, 1);
            IItemDropRule itemDropRule300 = ItemDropRule.Common(118, 25, 1, 1);
            IItemDropRule itemDropRule301 = this.RegisterToNPC(44, itemDropRule300);
            long num20 = 0L;
            IItemDropRule itemDropRule303;
            IItemDropRule itemDropRule302 = itemDropRule301.OnFailedRoll(itemDropRule303, num20 != 0L);
            IItemDropRule itemDropRule304 = ItemDropRule.Common(166, 1, 1, 3);
            long num21 = 0L;
            IItemDropRule itemDropRule305 = itemDropRule302.OnFailedRoll(itemDropRule304, num21 != 0L);
            IItemDropRule itemDropRule306 = ItemDropRule.Common(238, 1, 1, 1);
            IItemDropRule itemDropRule307 = this.RegisterToNPC(45, itemDropRule306);
            IItemDropRule itemDropRule308 = ItemDropRule.Common(116, 50, 1, 1);
            IItemDropRule itemDropRule309 = this.RegisterToNPC(23, itemDropRule308);
            IItemDropRule itemDropRule310 = ItemDropRule.Common(244, 250, 1, 1);
            IItemDropRule itemDropRule311 = this.RegisterToNPC(24, itemDropRule310);
            IItemDropRule itemDropRule312 = ItemDropRule.Common(932, 250, 1, 1);
            IItemDropRule itemDropRule313 = ItemDropRule.Common(3095, 100, 1, 1);
            long num22 = 0L;
            IItemDropRule itemDropRule315;
            IItemDropRule itemDropRule314 = itemDropRule315.OnFailedRoll(itemDropRule313, num22 != 0L);
            IItemDropRule itemDropRule316 = ItemDropRule.Common(327, 65, 1, 1);
            long num23 = 0L;
            IItemDropRule itemDropRule317 = itemDropRule314.OnFailedRoll(itemDropRule316, num23 != 0L);
            long num24 = 0L;
            IItemDropRule itemDropRule319;
            IItemDropRule itemDropRule318 = itemDropRule317.OnFailedRoll(itemDropRule319, num24 != 0L);
            IItemDropRule itemDropRule320 = ItemDropRule.Common(160, 200, 1, 1);
            IItemDropRule itemDropRule321 = ItemDropRule.Common(161, 2, 1, 5);
            long num25 = 0L;
            IItemDropRule itemDropRule323;
            IItemDropRule itemDropRule322 = itemDropRule323.OnFailedRoll(itemDropRule321, num25 != 0L);
            IItemDropRule itemDropRule324 = ItemDropRule.Common(1265, 100, 1, 1);
            IItemDropRule itemDropRule326;
            IItemDropRule itemDropRule325 = this.RegisterToNPC(175, itemDropRule326);
            IItemDropRule itemDropRule327 = ItemDropRule.Common(209, 1, 1, 1);
            IItemDropRule itemDropRule328 = ItemDropRule.Common(209, 6, 1, 1);
            IItemDropRule itemDropRule329 = this.RegisterToNPC(176, itemDropRule328);
            IItemDropRule itemDropRule330 = ItemDropRule.NormalvsExpert(209, 2, 1);
            IItemDropRule itemDropRule331 = this.RegisterToNPC(204, itemDropRule330);
            IItemDropRule itemDropRule332 = ItemDropRule.NormalvsExpert(210, 2, 1);
            IItemDropRule itemDropRule333 = this.RegisterToNPC(43, itemDropRule332);
            IItemDropRule itemDropRule335;
            IItemDropRule itemDropRule334 = this.RegisterToNPC(43, itemDropRule335);
            IItemDropRule itemDropRule337;
            IItemDropRule itemDropRule336 = this.RegisterToNPC(39, itemDropRule337);
            IItemDropRule itemDropRule339;
            IItemDropRule itemDropRule338 = this.RegisterToNPC(65, itemDropRule339);
            IItemDropRule itemDropRule340 = ItemDropRule.Common(268, 20, 1, 1);
            IItemDropRule itemDropRule341 = this.RegisterToNPC(65, itemDropRule340);
            IItemDropRule itemDropRule342 = ItemDropRule.Common(319, 1, 1, 1);
            long num26 = 0L;
            IItemDropRule itemDropRule343 = itemDropRule342.OnFailedRoll(itemDropRule342, num26 != 0L);
            IItemDropRule itemDropRule344 = ItemDropRule.NotScalingWithLuck(320, 2, 1, 1);
            IItemDropRule itemDropRule345 = this.RegisterToNPC(48, itemDropRule344);
            IItemDropRule itemDropRule346 = ItemDropRule.Common(3783, 1, 1, 1);
            IItemDropRule itemDropRule347 = this.RegisterToNPC(541, itemDropRule346);
            IItemDropRule itemDropRule348 = ItemDropRule.Common(319, 8, 1, 1);
            IItemDropRule itemDropRule349 = ItemDropRule.Common(527, 25, 1, 1);
            IItemDropRule itemDropRule350 = this.RegisterToNPC(543, itemDropRule349);
            IItemDropRule itemDropRule351 = ItemDropRule.Common(527, 25, 1, 1);
            IItemDropRule itemDropRule352 = this.RegisterToNPC(544, itemDropRule351);
            IItemDropRule itemDropRule353 = ItemDropRule.Common(528, 25, 1, 1);
            IItemDropRule itemDropRule354 = this.RegisterToNPC(545, itemDropRule353);
            IItemDropRule itemDropRule356;
            IItemDropRule itemDropRule355 = this.RegisterToNPC(47, itemDropRule356);
            IItemDropRule itemDropRule358;
            IItemDropRule itemDropRule357 = this.RegisterToNPC(464, itemDropRule358);
            IItemDropRule itemDropRule359 = ItemDropRule.Common(1332, 1, 2, 5);
            IItemDropRule itemDropRule360 = this.RegisterToNPC(268, itemDropRule359);
            IItemDropRule itemDropRule361 = ItemDropRule.Common(3, 1, 10, 20);
            IItemDropRule itemDropRule362 = this.RegisterToNPC(631, itemDropRule361);
            IItemDropRule itemDropRule363 = ItemDropRule.Common(4761, 10, 1, 1);
            IItemDropRule itemDropRule364 = this.RegisterToNPC(631, itemDropRule363);
        }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), j__TPar, System.L, Terraria.GameContent.ItemDropRules.ItemDropRule.NormalvsExpert(), Terraria.GameContent.ItemDropRules.ItemDropRule.NotScalingWithLuck(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC(), and Terraria.GameContent.ItemDropRules.ItemDropRule.WithRerolls().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().