terraria-cpp2il-methodrecon: Terraria.Item.CanRollPrefix
CanRollPrefix()
bool Terraria.Item.CanRollPrefix (int prefix) inline
Definition at line 285 of file Item.cs.
        {
            if (this.type == 0)
            {
                return;
            }
            int num = this.maxStack;
            int num2 = this.damage;
            if (!this.accessory || this.GetRollablePrefixes() != null)
            {
                return;
            }
        }
References Terraria.Item.accessory, Terraria.Item.damage, Terraria.Item.GetRollablePrefixes(), j__TPar, Terraria.Item.maxStack, and Terraria.Item.type.
Referenced by Terraria.Item.CanApplyPrefix(), and Terraria.Item.FixAgainstExploit().