terraria-cpp2il-methodrecon: Terraria.Item.Refresh
Refresh()
void Terraria.Item.Refresh (bool onlyIfVariantChanged = true) inline
Definition at line 1897 of file Item.cs.
        {
            int num = this.type;
            int num2 = this.stack;
            ItemVariant itemVariant = ItemVariants.SelectVariant(num);
            ItemVariant itemVariant2 = this.<Variant>k__BackingField;
            int num3 = this.stack;
            int num4 = this.netID;
            bool flag = this.favorited;
            byte b = this.prefix;
            this.netDefaults(num4);
            bool flag2 = this.Prefix((int)b);
            this.stack = num3;
            this.favorited = flag;
        }
References Terraria.Item.favorited, j__TPar, Terraria.Item.k__BackingField, Terraria.Item.netDefaults(), Terraria.Item.netID, Terraria.Item.Prefix(), Terraria.Item.prefix, Terraria.GameContent.Items.ItemVariants.SelectVariant(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.Item.FixAgainstExploit(), and Terraria.Item.ResetPrefix().