terraria-cpp2il-methodrecon: Newtonsoft.Json.Converters.HashSetConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.HashSetConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 16 of file HashSetConverter.cs.
        {
            if (existingValue != null)
            {
            }
            object obj = Activator.CreateInstance(objectType);
            MethodInfo method = objectType.GetMethod("Add");
            JArray jarray = JArray.Load(reader);
            int count = jarray.Count;
            long num = 0L;
            JsonReader jsonReader = jarray[(int)num].CreateReader();
            object obj2;
            if (obj2 == null || obj2 != null)
            {
                int count2 = jarray.Count;
                return obj;
            }
            throw new ArrayTypeMismatchException();
        }
References System.count, Newtonsoft.Json.Linq.JContainer.Count, System.Activator.CreateInstance(), System.Type.GetMethod(), j__TPar, System.L, Newtonsoft.Json.Linq.JArray.Load(), and System.obj.