terraria-cpp2il-methodrecon: GUIMultiplayerLobby.DrawLocal
DrawLocal()
void GUIMultiplayerLobby.DrawLocal () inline private
Definition at line 100 of file GUIMultiplayerLobby.cs.
    {
        this.RefreshLocalServers();
        if (this.NoPlatformFriends)
        {
            string textValue = Language.GetTextValue("Mobile.StadiaNoFriends");
            return;
        }
        string textValue2 = Language.GetTextValue("Mobile.StadiaSearchingFriendGames");
        if ("Mobile.StadiaSearchingFriendGames" == null)
        {
        }
        if ("Mobile.StadiaSearchingFriendGames" == null)
        {
        }
        if (6899 == 0)
        {
        }
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
        }
        SpriteBatchItem.DisabledClipping();
        GUITransactionButton.InputState inputState2;
        if (inputState2 == GUITransactionButton.InputState.Clicked)
        {
        }
    }
References Microsoft.Xna.Framework.Graphics.SpriteBatchItem.DisabledClipping(), Terraria.Localization.Language.GetTextValue(), j__TPar, NoPlatformFriends, and RefreshLocalServers().