terraria-cpp2il-methodrecon: Mono.Security.X509.X509CertificateCollection.AddRange
AddRange() [1/2]
void Mono.Security.X509.X509CertificateCollection.AddRange (X509Certificate[] value) inline
Definition at line 69 of file X509CertificateCollection.cs.
        {
            while (value == null)
            {
            }
            byte[] encodedcert = value.m_encodedcert;
            ArrayList list = this._list;
        }
References System.Collections.CollectionBase._list, j__TPar, System.list, and System.value.
Referenced by Mono.Security.X509.X509CertificateCollection.X509CertificateCollection(), Mono.Security.X509.X509CertificateCollection.X509CertificateCollection(), and Mono.Security.X509.X509Chain.LoadCertificates().