terraria-cpp2il-methodrecon: Terraria.Initializers.PlayerDataInitializer.CopyVariant
CopyVariant()
static void Terraria.Initializers.PlayerDataInitializer.CopyVariant (int to, int from) inline static private
Definition at line 41 of file PlayerDataInitializer.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
        }
Referenced by Terraria.Initializers.PlayerDataInitializer.LoadCoatFemale(), Terraria.Initializers.PlayerDataInitializer.LoadCoatMale(), Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollFemale(), Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollMale(), Terraria.Initializers.PlayerDataInitializer.LoadDressFemale(), Terraria.Initializers.PlayerDataInitializer.LoadDressMale(), Terraria.Initializers.PlayerDataInitializer.LoadGangsterFemale(), Terraria.Initializers.PlayerDataInitializer.LoadGangsterMale(), Terraria.Initializers.PlayerDataInitializer.LoadStarterFemale(), Terraria.Initializers.PlayerDataInitializer.LoadStickerFemale(), and Terraria.Initializers.PlayerDataInitializer.LoadStickerMale().