terraria-cpp2il-methodrecon: Terraria.Initializers.PlayerDataInitializer.Load
Load()
static void Terraria.Initializers.PlayerDataInitializer.Load () inline static
Definition at line 9 of file PlayerDataInitializer.cs.
        {
            if (!true)
            {
            }
            PlayerDataInitializer.LoadStarterMale();
            PlayerDataInitializer.LoadStarterFemale();
            PlayerDataInitializer.LoadStickerMale();
            PlayerDataInitializer.LoadStickerFemale();
            PlayerDataInitializer.LoadGangsterMale();
            PlayerDataInitializer.LoadGangsterFemale();
            PlayerDataInitializer.LoadCoatMale();
            PlayerDataInitializer.LoadDressFemale();
            PlayerDataInitializer.LoadDressMale();
            PlayerDataInitializer.LoadCoatFemale();
            PlayerDataInitializer.LoadDisplayDollMale();
            PlayerDataInitializer.LoadDisplayDollFemale();
        }
References Terraria.Initializers.PlayerDataInitializer.LoadCoatFemale(), Terraria.Initializers.PlayerDataInitializer.LoadCoatMale(), Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollFemale(), Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollMale(), Terraria.Initializers.PlayerDataInitializer.LoadDressFemale(), Terraria.Initializers.PlayerDataInitializer.LoadDressMale(), Terraria.Initializers.PlayerDataInitializer.LoadGangsterFemale(), Terraria.Initializers.PlayerDataInitializer.LoadGangsterMale(), Terraria.Initializers.PlayerDataInitializer.LoadStarterFemale(), Terraria.Initializers.PlayerDataInitializer.LoadStarterMale(), Terraria.Initializers.PlayerDataInitializer.LoadStickerFemale(), and Terraria.Initializers.PlayerDataInitializer.LoadStickerMale().