terraria-cpp2il-methodrecon: Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby
RegisterWasNearby()
void Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby (NPC npc) inline
Definition at line 26 of file NPCWasNearPlayerTracker.cs.
        {
            string bestiaryCreditId = npc.GetBestiaryCreditId();
            HashSet<string> wasNearPlayer = this._wasNearPlayer;
            object entryCreationLock = this._entryCreationLock;
            HashSet<string> wasNearPlayer2 = this._wasNearPlayer;
            long num = 0L;
            Monitor.Exit(entryCreationLock);
            if (num == 0L)
            {
                bool netHost = Main.NetHost;
                int netID = npc.netID;
                NetPacket netPacket = NetBestiaryModule.SerializeSight(netID);
                return;
            }
            throw new OutOfMemoryException();
        }
References Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker._entryCreationLock, Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker._wasNearPlayer, System.Threading.Monitor.Exit(), Terraria.NPC.GetBestiaryCreditId(), j__TPar, System.L, Terraria.Main.NetHost, Terraria.NPC.netID, and Terraria.GameContent.NetModules.NetBestiaryModule.SerializeSight().