terraria-cpp2il-methodrecon: Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal
TryConvertInternal()
static ConvertUtils.ConvertResult Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal (object initialValue, CultureInfo culture, Type targetType, [Out] object value) inline static private
Definition at line 158 of file ConvertUtils.cs.
        {
            if (!true)
            {
            }
            Type type2;
            Type type = type2.GetType();
            long num = 0L;
            bool flag = ConvertUtils.IsConvertible(type.GetType());
            bool flag2 = ConvertUtils.IsConvertible(type2);
            object obj = Enum.ToObject(type2, num);
            Type type3;
            if (type3 != null)
            {
            }
            object obj2;
            if (ConvertUtils.GetConverter(type) == null || obj2 != null)
            {
                TypeConverter typeConverter;
                if (typeConverter != null)
                {
                    bool flag3 = typeConverter.CanConvertFrom(type);
                }
                return ConvertUtils.ConvertResult.NotInstantiableType;
            }
            throw new InvalidCastException();
        }
References System.ComponentModel.TypeConverter.CanConvertFrom(), Newtonsoft.Json.Utilities.ConvertUtils.GetConverter(), System.Type.GetType(), Newtonsoft.Json.Utilities.ConvertUtils.IsConvertible(), j__TPar, System.L, System.obj, and System.Enum.ToObject().