terraria-cpp2il-methodrecon: System.Net.FtpWebRequest.BeginGetResponse
BeginGetResponse()
override IAsyncResult System.Net.FtpWebRequest.BeginGetResponse (AsyncCallback callback, object state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 384 of file FtpWebRequest.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            bool isEnabled = NetEventSource.IsEnabled;
            if (num == 0)
            {
            }
            string method = this._methodInfo.Method;
            if (method == null || method != null)
            {
                FormattableString formattableString;
                NetEventSource.Info(this, formattableString, "BeginGetResponse");
                if (this._ftpWebResponse != null)
                {
                    FtpWebResponse ftpWebResponse = this._ftpWebResponse;
                }
                if (!this._getResponseStarted)
                {
                    Exception exception = this._exception;
                    int num2 = 1;
                    this._getResponseStarted = num2 != 0;
                    if (exception != null)
                    {
                        ExceptionDispatchInfo.Throw(exception);
                    }
                    long num3 = 0L;
                    object syncObject = this._syncObject;
                    Monitor.Enter(syncObject, num3 != 0L);
                    FtpWebRequest.RequestStage requestStage = this._requestStage;
                    long num4 = 0L;
                    int num5 = 10;
                    if (requestStage != FtpWebRequest.RequestStage.CheckForError)
                    {
                        Monitor.Exit(syncObject);
                    }
                    if (num4 == 0L)
                    {
                        int num10;
                        if (num5 == 0)
{
                            LazyAsyncResult readAsyncResult = this._readAsyncResult;
                            if (readAsyncResult != null)
{
                            }
                            bool internalPeekCompleted = readAsyncResult.InternalPeekCompleted;
                            readAsyncResult.InvokeCallback();
                            long num6 = 0L;
                            object obj;
                            Monitor.Enter(obj, num6 != 0L);
                            int num7 = 1;
                            this.SubmitRequest(num7 != 0);
                            long num8 = 0L;
                            int num9 = 13;
                            Monitor.Exit(syncObject);
                            if (num8 != 0L)
{
                                throw new OutOfMemoryException();
                            }
                            if (num9 == 0)
{
                                num10 = 14;
                            }
                        }
                        long num11 = 0L;
                        bool isEnabled2 = NetEventSource.IsEnabled;
                        if (num11 != 0L || num10 == 0)
{
                        }
                        throw new OutOfMemoryException();
                    }
                    throw new OutOfMemoryException();
                }
            }
            throw new ArrayTypeMismatchException();
        }
References System.Net.FtpWebRequest._exception, System.Net.FtpWebRequest._ftpWebResponse, System.Net.FtpWebRequest._getResponseStarted, System.Net.FtpWebRequest._methodInfo, System.Net.FtpWebRequest._readAsyncResult, System.Net.FtpWebRequest._requestStage, System.Net.FtpWebRequest._syncObject, System.Threading.Monitor.Enter(), System.exception, System.Threading.Monitor.Exit(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalPeekCompleted, System.Net.NetEventSource.IsEnabled, j__TPar, System.L, System.Net.FtpMethodInfo.Method, System.obj, System.Net.FtpWebRequest.SubmitRequest(), and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().