terraria-cpp2il-methodrecon: System.Net.FtpWebRequest.GetRequestStream
GetRequestStream()
override Stream System.Net.FtpWebRequest.GetRequestStream () inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 506 of file FtpWebRequest.cs.
        {
            int num6;
            do
            {
                int num = 1;
                if (num == 0)
                {
                }
                bool isEnabled = NetEventSource.IsEnabled;
                if (num == 0)
                {
                }
                string method = this._methodInfo.Method;
                if (method != null && method == null)
                {
                    goto IL_0138;
                }
                FormattableString formattableString;
                NetEventSource.Info(this, formattableString, "GetRequestStream");
                if (this._getRequestStreamStarted)
                {
                    goto IL_0128;
                }
                FtpMethodInfo methodInfo = this._methodInfo;
                int num2 = 1;
                this._getRequestStreamStarted = num2 != 0;
                FtpMethodFlags flags = methodInfo.Flags;
                Exception exception = this._exception;
                if (exception != null)
                {
                    ExceptionDispatchInfo.Throw(exception);
                }
                if (flags == FtpMethodFlags.None)
                {
                }
                DateTime utcNow = DateTime.UtcNow;
                this._startTime = utcNow;
                this._remainingTimeout = this;
                DateTime utcNow2 = DateTime.UtcNow;
                DateTime startTime = this._startTime;
                double totalMilliseconds = (utcNow2 - startTime).TotalMilliseconds;
                int num3 = 32768;
                this._remainingTimeout = num3;
                long num4 = 0L;
                this.SubmitRequest(num4 != 0L);
                Exception exception2 = this._exception;
                if (exception2 != null)
                {
                    ExceptionDispatchInfo.Throw(exception2);
                }
                Stream stream = this._stream;
                Stream stream2 = this._stream;
                int readWriteTimeout = this._readWriteTimeout;
                Stream stream3 = this._stream;
                int readWriteTimeout2 = this._readWriteTimeout;
                long num5 = 0L;
                num6 = 13;
                bool isEnabled2 = NetEventSource.IsEnabled;
                if (num5 != 0L)
                {
                    goto IL_0128;
                }
            }
            while (num6 != 0);
            return this._stream;
            IL_0128:
            throw new OutOfMemoryException();
            IL_0138:
            throw new ArrayTypeMismatchException();
        }
References System.Net.FtpWebRequest._exception, System.Net.FtpWebRequest._getRequestStreamStarted, System.Net.FtpWebRequest._methodInfo, System.Net.FtpWebRequest._readWriteTimeout, System.Net.FtpWebRequest._startTime, System.Net.FtpWebRequest._stream, System.exception, System.Net.NetEventSource.Info(), System.Net.NetEventSource.IsEnabled, j__TPar, System.L, System.Net.FtpMethodInfo.Method, System.Net.FtpWebRequest.SubmitRequest(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(), and System.DateTime.UtcNow.