terraria-cpp2il-methodrecon: System.Net.HttpConnection.SendError
SendError() [1/2]
void System.Net.HttpConnection.SendError () inline
Definition at line 414 of file HttpConnection.cs.
        {
            HttpListenerContext httpListenerContext = this.context;
            string error = httpListenerContext.error;
            int err_status = httpListenerContext.err_status;
            this.SendError(error, err_status);
        }
References System.Net.HttpConnection.context, System.Net.HttpListenerContext.error, j__TPar, and System.Net.HttpConnection.SendError().
Referenced by System.Net.HttpConnection.OnReadInternal(), and System.Net.HttpConnection.SendError().