terraria-cpp2il-methodrecon: System.Net.HttpConnection.OnReadInternal
OnReadInternal()
void System.Net.HttpConnection.OnReadInternal (IAsyncResult ares) inline private
Definition at line 253 of file HttpConnection.cs.
        {
            HttpListenerContext httpListenerContext;
            string error;
            HttpListenerContext httpListenerContext2;
            for (;;)
            {
                Timer timer = this.timer;
                Stream stream = this.stream;
                MemoryStream memoryStream = this.ms;
                byte[] array = this.buffer;
                MemoryStream memoryStream2 = this.ms;
                if (stream == null)
                {
                    goto IL_0154;
                }
                MemoryStream memoryStream3 = this.ms;
                bool flag = this.ProcessInput(memoryStream3);
                httpListenerContext = this.context;
                error = httpListenerContext.error;
                if (error != null)
                {
                    break;
                }
                httpListenerContext2 = this.context;
                if (httpListenerContext2.error == null)
                {
                    goto Block_2;
                }
            }
            int err_status = httpListenerContext.err_status;
            this.SendError(error, err_status);
            int num = 1;
            this.Close(num != 0);
            return;
            Block_2:
            bool flag2 = this.epl.BindContext(httpListenerContext2);
            HttpListenerContext httpListenerContext3 = this.context;
            HttpListener httpListener = this.last_listener;
            HttpListener listener = httpListenerContext3.Listener;
            this.RemoveConnection();
            Hashtable connections = listener.connections;
            HttpListenerContext httpListenerContext4 = this.context;
            this.last_listener = listener;
            int num2 = 1;
            this.context_bound = num2 != 0;
            listener.RegisterContext(httpListenerContext4);
            return;
            IL_0154:
            this.CloseSocket();
            this.Unbind();
        }
References System.array, System.Net.EndPointListener.BindContext(), System.Net.HttpConnection.buffer, System.Net.HttpConnection.Close(), System.Net.HttpConnection.CloseSocket(), System.Net.HttpListener.connections, System.Net.HttpConnection.context, System.Net.HttpConnection.epl, System.Net.HttpListenerContext.err_status, System.Net.HttpListenerContext.error, j__TPar, System.Net.HttpConnection.last_listener, System.Net.HttpConnection.ms, System.Net.HttpConnection.ProcessInput(), System.Net.HttpListener.RegisterContext(), System.Net.HttpConnection.RemoveConnection(), System.Net.HttpConnection.SendError(), System.Net.HttpConnection.stream, System.Net.HttpConnection.timer, and System.Net.HttpConnection.Unbind().