terraria-cpp2il-methodrecon: System.Net.HttpConnection.Unbind
Unbind()
void System.Net.HttpConnection.Unbind () inline private
Definition at line 423 of file HttpConnection.cs.
        {
            if (this.context_bound)
            {
                HttpListenerContext httpListenerContext = this.context;
                if (httpListenerContext != null && httpListenerContext.request != null)
                {
                    httpListenerContext.Listener.UnregisterContext(httpListenerContext);
                }
            }
        }
References System.Net.HttpConnection.context, System.Net.HttpConnection.context_bound, j__TPar, System.Net.HttpListenerContext.Listener, System.Net.HttpListenerContext.request, and System.Net.HttpListener.UnregisterContext().
Referenced by System.Net.HttpConnection.Close(), System.Net.HttpConnection.OnReadInternal(), and System.Net.HttpConnection.OnTimeout().