terraria-cpp2il-methodrecon: System.Net.HttpConnection.Close
Close() [2/2]
void System.Net.HttpConnection.Close (bool force_close) inline package
Definition at line 455 of file HttpConnection.cs.
        {
            if (this.sock != null)
            {
                if (this.GetResponseStream() != null)
                {
                }
                if (this.sock != null)
                {
                    bool keepAlive = this.context.request.KeepAlive;
                    bool flag = this.context.response.headers["connection"] == "close";
                    bool flag2 = this.context.request.FlushInput();
                    if (this.chunked)
                    {
                        bool force_close_chunked = this.context.response.force_close_chunked;
                    }
                    int num = this.reuses;
                    this.reuses = num;
                    this.Unbind();
                    this.Init();
                    this.BeginReadRequest();
                    return;
                }
            }
        }
References System.Net.HttpConnection.BeginReadRequest(), System.Net.HttpConnection.chunked, System.Net.HttpConnection.context, System.Net.HttpListenerRequest.FlushInput(), System.Net.HttpListenerResponse.force_close_chunked, System.Net.HttpConnection.GetResponseStream(), System.Net.HttpListenerResponse.headers, System.Net.HttpConnection.Init(), j__TPar, System.Net.HttpListenerRequest.KeepAlive, System.Net.HttpListenerContext.request, System.Net.HttpListenerContext.response, System.Net.HttpConnection.reuses, System.Net.HttpConnection.sock, and System.Net.HttpConnection.Unbind().