terraria-cpp2il-methodrecon: Terraria.GameContent.Drawing.TileDrawing.Update
Update()
void Terraria.GameContent.Drawing.TileDrawing.Update () inline
Definition at line 404 of file TileDrawing.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num != 0)
            {
                return;
            }
            if (num == 0)
            {
            }
            if (!true)
            {
            }
            this.UpdateLeafFrequency();
            WindGrid windGrid;
            windGrid.Update();
            bool flag = Main.ShouldShowInvisibleWalls();
            Main.sectionManager.SetAllFramedSectionsAsNeedingRefresh();
        }
References j__TPar, Terraria.Main.sectionManager, Terraria.WorldSections.SetAllFramedSectionsAsNeedingRefresh(), Terraria.Main.ShouldShowInvisibleWalls(), Terraria.GameContent.Drawing.WindGrid.Update(), and Terraria.GameContent.Drawing.TileDrawing.UpdateLeafFrequency().