terraria-cpp2il-methodrecon: UnityEngine.Texture2DArray.ValidateFormat
ValidateFormat() [4/4]
bool UnityEngine.Texture2DArray.ValidateFormat (TextureFormat format, int width, int height) inline package
Definition at line 37 of file Texture2DArray.cs.
        {
            bool flag = base.ValidateFormat(format);
            return Mathf.IsPowerOfTwo(width);
        }
References System.format, UnityEngine.Mathf.IsPowerOfTwo(), j__TPar, and UnityEngine.Texture.width.
Referenced by UnityEngine.Texture2DArray.Texture2DArray(), and UnityEngine.Texture2DArray.Texture2DArray().