terraria-cpp2il-methodrecon: UnityEngine.Texture2DArray.Texture2DArray
Texture2DArray() [3/6]
UnityEngine.Texture2DArray.Texture2DArray (int width, int height, int depth, GraphicsFormat format, TextureCreationFlags flags, int mipCount) inline
Definition at line 69 of file Texture2DArray.cs.
        {
            if (!true)
            {
            }
            base..ctor();
            bool flag = this.ValidateFormat(format, width, height);
            Texture2DArray.ValidateIsNotCrunched(flags);
            Texture2DArray.Internal_Create(this, width, height, depth, mipCount, format, flags);
        }
References System.format, UnityEngine.Texture.height, UnityEngine.Texture2DArray.Internal_Create(), j__TPar, UnityEngine.Texture2DArray.ValidateFormat(), UnityEngine.Texture2DArray.ValidateIsNotCrunched(), and UnityEngine.Texture.width.