terraria-cpp2il-methodrecon: Terraria.GameContent.UI.States.UIBestiaryTest.FillBestiarySpaceWithEntries
FillBestiarySpaceWithEntries()
void Terraria.GameContent.UI.States.UIBestiaryTest.FillBestiarySpaceWithEntries () inline private
Definition at line 255 of file UIBestiaryTest.cs.
        {
            UIBestiaryEntryGrid entryGrid = this._entryGrid;
            if (entryGrid != null && entryGrid.<Parent>k__BackingField != null)
            {
                UIBestiaryEntryInfoPage infoSpace = this._infoSpace;
                BestiaryUnlockProgressReport unlockProgress = this.GetUnlockProgress();
                UIBestiaryEntryGrid entryGrid2 = this._entryGrid;
                this._progressReport = unlockProgress;
                entryGrid2.FillBestiarySpaceWithEntries();
                return;
            }
        }
References Terraria.GameContent.UI.States.UIBestiaryTest._entryGrid, Terraria.GameContent.UI.States.UIBestiaryTest._infoSpace, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.States.UIBestiaryTest.GetUnlockProgress(), j__TPar, Terraria.UI.UIElement.k__BackingField, and Terraria.UI.UIElement.Parent.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.Recalculate(), and Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents().