terraria-cpp2il-methodrecon: Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents
UpdateBestiaryContents()
void Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents () inline private
Definition at line 372 of file UIBestiaryTest.cs.
        {
            this._filteringGrid.UpdateAvailability();
            EntrySorter<BestiaryEntry, IBestiarySortStep> sorter = this._sorter;
            UIText sortingText = this._sortingText;
            EntryFilterer<BestiaryEntry, IBestiaryEntryFilter> filterer = this._filterer;
            UIText filteringText = this._filteringText;
            string displayName = filterer.GetDisplayName();
            filteringText.SetText(displayName);
            this.FilterEntries();
            this.SortEntries();
            this.FillBestiarySpaceWithEntries();
            BestiaryUnlockProgressReport unlockProgress = this.GetUnlockProgress();
            this._progressReport = unlockProgress;
            string completionPercentText = this.GetCompletionPercentText();
            this._progressPercentText.SetText(completionPercentText);
            UIColoredSliderSimple unlocksProgressBar = this._unlocksProgressBar;
        }
References Terraria.GameContent.UI.States.UIBestiaryTest._filterer, Terraria.GameContent.UI.States.UIBestiaryTest._filteringGrid, Terraria.GameContent.UI.States.UIBestiaryTest._filteringText, Terraria.GameContent.UI.States.UIBestiaryTest._progressPercentText, Terraria.GameContent.UI.States.UIBestiaryTest._sorter, Terraria.GameContent.UI.States.UIBestiaryTest._sortingText, Terraria.GameContent.UI.States.UIBestiaryTest._unlocksProgressBar, Terraria.GameContent.UI.States.UIBestiaryTest.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.States.UIBestiaryTest.FilterEntries(), Terraria.GameContent.UI.States.UIBestiaryTest.GetCompletionPercentText(), Terraria.GameContent.UI.States.UIBestiaryTest.GetUnlockProgress(), j__TPar, Terraria.GameContent.UI.Elements.UIText.SetText(), Terraria.GameContent.UI.States.UIBestiaryTest.SortEntries(), and Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), Terraria.GameContent.UI.States.UIBestiaryTest.CloseFilteringGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.CloseSortingGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.OnOpenPage(), Terraria.GameContent.UI.States.UIBestiaryTest.OnSearchContentsChanged(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseFilteringGrid(), and Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseSortingOptions().