terraria-cpp2il-methodrecon: Terraria.Audio.ActiveSound.Play
Play()
void Terraria.Audio.ActiveSound.Play () inline private
Definition at line 111 of file ActiveSound.cs.
        {
            SoundStyle soundStyle = this.<Style>k__BackingField;
            SoundEffectInstance soundEffectInstance;
            float pitch = soundEffectInstance._pitch;
            float randomPitch = this.<Style>k__BackingField.GetRandomPitch();
            soundEffectInstance.Pitch = randomPitch;
            float pitch2 = soundEffectInstance._pitch;
            this.Pitch = pitch2;
            SoundInstanceGarbageCollector.Track(soundEffectInstance);
            this.<Sound>k__BackingField = soundEffectInstance;
            this.Update();
        }
References Microsoft.Xna.Framework.Audio.SoundEffectInstance._pitch, Terraria.Audio.SoundStyle.GetRandomPitch(), j__TPar, Terraria.Audio.ActiveSound.k__BackingField, Terraria.Audio.ActiveSound.Sound, Terraria.Audio.ActiveSound.Style, Terraria.Audio.SoundInstanceGarbageCollector.Track(), and Terraria.Audio.ActiveSound.Update().
Referenced by Terraria.Audio.ActiveSound.ActiveSound(), and Terraria.Audio.ActiveSound.ActiveSound().