terraria-cpp2il-methodrecon: Mono.Security.ASN1Convert.FromOid
FromOid()
static ASN1 Mono.Security.ASN1Convert.FromOid (string oid) inline static
Definition at line 45 of file ASN1Convert.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by Mono.Security.X509.PKCS12.CertificateSafeBag(), Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.GetBytes(), Mono.Security.X509.PKCS12.GetBytes(), Mono.Security.X509.PKCS12.KeyBagSafeBag(), Mono.Security.X509.PKCS12.Pkcs8ShroudedKeyBagSafeBag(), and Mono.Security.X509.PKCS12.SecretBagSafeBag().