terraria-cpp2il-methodrecon: Mono.Security.ASN1Convert.ToOid
ToOid()
static string Mono.Security.ASN1Convert.ToOid (ASN1 asn1) inline static
Definition at line 62 of file ASN1Convert.cs.
        {
            /*
An exception occurred when decompiling this method (06000019)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.String Mono.Security.ASN1Convert::ToOid(Mono.Security.ASN1)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    IL_001C:
    stloc:CultureInfo(var_14_24, callgetter:CultureInfo(CultureInfo::get_InvariantCulture))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Mono.Security.PKCS7.ContentInfo.ContentInfo(), Mono.Security.PKCS7.EncryptedData.EncryptedData(), Mono.Security.X509.X509Extension.X509Extension(), Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.Decode(), Mono.Security.Cryptography.PKCS8.EncryptedPrivateKeyInfo.Decode(), Mono.Security.X509.PKCS12.Decode(), System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension.Decode(), Mono.Security.X509.PKCS12.GetAsymmetricAlgorithm(), Mono.Security.X509.PKCS12.GetAttributes(), Mono.Security.X509.PKCS12.GetAttributes(), Mono.Security.X509.PKCS12.GetCertificate(), Mono.Security.X509.PKCS12.GetSecret(), Mono.Security.X509.X509Certificate.Parse(), Mono.Security.X509.PKCS12.ReadSafeBag(), Mono.Security.X509.PKCS12.RemoveCertificate(), Mono.Security.Authenticode.AuthenticodeDeformatter.VerifyCounterSignature(), and Mono.Security.Authenticode.AuthenticodeDeformatter.VerifySignature().