terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension.Decode
Decode()
AsnDecodeStatus System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension.Decode (byte[] extension) inline package
Definition at line 57 of file X509EnhancedKeyUsageExtension.cs.
        {
            int num = 1;
            if (extension != null && num != 0)
            {
                if (this._enhKeyUsage == null)
                {
                }
                OidCollection enhKeyUsage = this._enhKeyUsage;
                ASN1 asn;
                string text = ASN1Convert.ToOid(asn);
                string text2 = Locale.GetText("Invalid ASN.1 Tag");
                return;
            }
        }
References System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension._enhKeyUsage, Locale.GetText(), j__TPar, System.text, and Mono.Security.ASN1Convert.ToOid().
Referenced by System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension.X509EnhancedKeyUsageExtension(), and System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension.CopyFrom().