terraria-cpp2il-methodrecon: Terraria.Lighting.Initialize
Initialize()
static void Terraria.Lighting.Initialize (bool resized = false) inline static
Definition at line 214 of file Lighting.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
            Lighting.NewEngine.Rebuild();
            Lighting.LegacyEngine.Rebuild();
            if (Lighting._activeEngine != null)
            {
                return;
            }
            if (!true)
            {
            }
            Lighting.Mode = LightMode.Color;
        }
References Terraria.Lighting._activeEngine, j__TPar, Terraria.Lighting.LegacyEngine, Terraria.Lighting.NewEngine, Terraria.Graphics.Light.LegacyLighting.Rebuild(), and Terraria.Graphics.Light.LightingEngine.Rebuild().
Referenced by Terraria.Main.SetDisplayMode().