terraria-cpp2il-methodrecon: Terraria.IO.ResourcePack.HasFile
HasFile()
bool Terraria.IO.ResourcePack.HasFile (string fileName) inline private
Definition at line 204 of file ResourcePack.cs.
        {
            if (this._isCompressed)
            {
                return this._zipFile.ContainsEntry(fileName);
            }
            return File.Exists(Path.Combine(this.FullPath, fileName));
        }
References Terraria.IO.ResourcePack._isCompressed, Terraria.IO.ResourcePack._zipFile, System.IO.Path.Combine(), Ionic.Zip.ZipFile.ContainsEntry(), and System.IO.File.Exists().
Referenced by Terraria.IO.ResourcePack.CreateIcon(), and Terraria.IO.ResourcePack.LoadManifest().