terraria-cpp2il-methodrecon: UnityEngine.AndroidJNISafe.DeleteLocalRef
DeleteLocalRef()
static void UnityEngine.AndroidJNISafe.DeleteLocalRef (IntPtr localref) inline static
Definition at line 27 of file AndroidJNISafe.cs.
        {
            throw new MissingMethodException();
        }
Referenced by UnityEngine.AndroidJavaObject.AndroidJavaObject(), UnityEngine.AndroidJavaClass._AndroidJavaClass(), UnityEngine.AndroidJavaObject._AndroidJavaObject(), UnityEngine._AndroidJNIHelper.ConvertToJNIArray(), UnityEngine.AndroidJavaObject.FromJavaArrayDeleteLocalRef< ReturnType >(), UnityEngine._AndroidJNIHelper.GetConstructorID(), UnityEngine.AndroidReflection.GetConstructorMember(), UnityEngine.AndroidReflection.GetFieldMember(), UnityEngine.AndroidReflection.GetMethodID(), UnityEngine.AndroidReflection.GetMethodMember(), and UnityEngine.AndroidReflection.GetStaticMethodID().