terraria-cpp2il-methodrecon: GUIClothesWindow.Draw
Draw()
void GUIClothesWindow.Draw () inline
Definition at line 104 of file GUIClothesWindow.cs.
    {
        int num = 1;
        bool flag = Main.npcChatText != "";
        if (num == 0)
        {
        }
        int myPlayer = Main.myPlayer;
        if (num == 0)
        {
        }
        if (Main.npcShop != 0)
        {
            Main.CancelClothesWindow(false);
            return;
        }
        if (num == 0)
        {
        }
        int myPlayer2 = Main.myPlayer;
        if (num == 0)
        {
        }
        bool inGuideCraftMenu = Main.InGuideCraftMenu;
        if (num == 0)
        {
        }
        int interactedDresserTopLeftX = Main.interactedDresserTopLeftX;
        int interactedDresserTopLeftY = Main.interactedDresserTopLeftY;
        Tile tile;
        ushort type = tile.type;
        GUIControllerDresser controller = this._controller;
        GUIControllerDresser controller2 = this._controller;
        Player localPlayer = Main.LocalPlayer;
        int interactedDresserTopLeftX2 = Main.interactedDresserTopLeftX;
        int interactedDresserTopLeftY2 = Main.interactedDresserTopLeftY;
        bool flag2 = localPlayer.IsInInteractionRangeToMultiTileHitbox(interactedDresserTopLeftX2, interactedDresserTopLeftY2);
        int interactedDresserTopLeftX3 = Main.interactedDresserTopLeftX;
        int interactedDresserTopLeftY3 = Main.interactedDresserTopLeftY;
        Tile tile2;
        bool flag3 = tile2.active();
        Rectangle rectangle;
        ControlAnchor.SetGridItemRegion(rectangle);
        this.ClonePlayer();
        if (Main.selClothes != 0)
        {
            this.DrawHSLSlider();
            return;
        }
        this.DrawStyles();
        this.DrawCategoryButtons();
        this.DrawChangeButton();
        this.DrawCancelButton();
        this.DrawPlayer();
    }
References _controller, Terraria.Tile.active(), Terraria.Main.CancelClothesWindow(), ClonePlayer(), DrawCancelButton(), DrawCategoryButtons(), DrawChangeButton(), DrawHSLSlider(), DrawPlayer(), DrawStyles(), Terraria.Main.InGuideCraftMenu, Terraria.Main.interactedDresserTopLeftX, Terraria.Main.interactedDresserTopLeftY, j__TPar, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.npcShop, Terraria.Main.selClothes, ControlAnchor.SetGridItemRegion(), and Terraria.Tile.type.