terraria-cpp2il-methodrecon: GUIRubbleMaker.DrawOverlay
DrawOverlay()
void GUIRubbleMaker.DrawOverlay () inline
Definition at line 288 of file GUIRubbleMaker.cs.
    {
        Cursor cursor;
        if (this.DisplayOptions && cursor != null)
        {
            bool displayMaterials;
            if (this.DisplayMaterials)
            {
                Rectangle rectangle = this.CalculateMaterialRegion();
                TransactionButton_Layout materialToggle = RubbleMakerUI_Layout.Instance.MaterialToggle;
                Rectangle pickRegion = GUITransactionButton.GetPickRegion(materialToggle);
                displayMaterials = this.DisplayMaterials;
                if (displayMaterials)
                {
                }
            }
            Panel_Layout backing = RubbleMakerUI_Layout.Instance.Backing;
            Rectangle rectangle2 = GUIPanel.Region(backing);
            float x = cursor.Position.x;
            float y = cursor.Position.y;
            if (!displayMaterials)
            {
            }
            this.Close();
        }
        bool drawRubbleModeUI = GUIRubbleMaker.DrawRubbleModeUI;
        bool displayOptions = this.DisplayOptions;
        if (displayOptions)
        {
            this.RefreshOptions();
            if (!displayOptions)
            {
            }
            Main.FlushBatches();
            string textValue = Language.GetTextValue("Mobile.FilterItemsClose");
            bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
            if (this.DisplayMaterials)
            {
                GUIInputRegionExclusive pickingInterceptor = this.PickingInterceptor;
                Panel_Layout backing2 = RubbleMakerUI_Layout.Instance.Backing;
                Rectangle rectangle3 = GUIPanel.Region(backing2);
                Panel_Layout backing3 = RubbleMakerUI_Layout.Instance.Backing;
                ControlAnchor.SetMainMenuPageRegion(rectangle3);
                Panel_Layout menuDivider = RubbleMakerUI_Layout.Instance.MenuDivider;
                Cursor cursor2;
                if (cursor2 != null)
                {
                }
                int myPlayer = Main.myPlayer;
                int myPlayer2 = Main.myPlayer;
                int num = 5329;
                TransactionButton_Layout sizeToggle = RubbleMakerUI_Layout.Instance.SizeToggle;
                GUITransactionButton.InputState inputState;
                if (inputState == GUITransactionButton.InputState.Clicked)
                {
                    if (num == 0)
                    {
                    }
                    return;
                }
                FlexibleTileWand.OptionBucket selectedMaterial;
                if (this.SelectedMaterial != null)
                {
                    int itemTypeToConsume = this.SelectedMaterial.ItemTypeToConsume;
                    selectedMaterial = this.SelectedMaterial;
                    if (selectedMaterial != null)
                    {
                        return;
                    }
                }
                else
                {
                    Item item = this.EmptyItem;
                }
                if (selectedMaterial == null)
                {
                }
                List<FlexibleTileWand.PlacementOption> options = selectedMaterial.Options;
                RubbleMakerUI_Layout instance = RubbleMakerUI_Layout.Instance;
                List<FlexibleTileWand.OptionBucket> materialOptions = this.MaterialOptions;
                TransactionButton_Layout materialToggle2 = instance.MaterialToggle;
                int size = materialOptions._size;
                GUITransactionButton.InputState inputState2;
                if (inputState2 == GUITransactionButton.InputState.Clicked)
                {
                    bool displayMaterials2 = this.DisplayMaterials;
                    this.DisplayMaterials = displayMaterials2;
                }
                FlexibleTileWand.OptionBucket selectedMaterial2 = this.SelectedMaterial;
                if (selectedMaterial2 != null)
                {
                    int size2 = selectedMaterial2.Options._size;
                    return;
                }
                ItemGrid_Layout rubbleOptions = RubbleMakerUI_Layout.Instance.RubbleOptions;
                Rectangle rectangle4;
                if (rectangle4 == null)
                {
                }
                int mouseX = Main.mouseX;
                int mouseY = Main.mouseY;
                Vector2 smallRubblePreviewScaleOffset = RubbleMakerUI_Layout.Instance.SmallRubblePreviewScaleOffset;
                this.rubbleScaleOffset = smallRubblePreviewScaleOffset;
                RubbleMakerUI_Layout instance2 = RubbleMakerUI_Layout.Instance;
                return;
            }
            else
            {
                this.Close();
            }
        }
    }
References Controller.ControllerActionManager.AnyControllerConnected, RubbleMakerUI_Layout.Backing, CalculateMaterialRegion(), Close(), DisplayMaterials, DisplayOptions, DrawRubbleModeUI, EmptyItem, Terraria.Main.FlushBatches(), GUITransactionButton.GetPickRegion(), Terraria.Localization.Language.GetTextValue(), RubbleMakerUI_Layout.Instance, System.item, j__TPar, MaterialOptions, RubbleMakerUI_Layout.MaterialToggle, RubbleMakerUI_Layout.MenuDivider, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, System.options, PickingInterceptor, RefreshOptions(), GUIPanel.Region(), RubbleMakerUI_Layout.RubbleOptions, SelectedMaterial, ControlAnchor.SetMainMenuPageRegion(), RubbleMakerUI_Layout.SizeToggle, and RubbleMakerUI_Layout.SmallRubblePreviewScaleOffset.