terraria-cpp2il-methodrecon: GUIRubbleMaker.CalculateMaterialRegion
CalculateMaterialRegion()
Rectangle GUIRubbleMaker.CalculateMaterialRegion () inline
Definition at line 442 of file GUIRubbleMaker.cs.
    {
        ControlAnchor.SetMainMenuPageRegion(GUIPanel.Region(RubbleMakerUI_Layout.Instance.Backing));
        RubbleMakerUI_Layout instance = RubbleMakerUI_Layout.Instance;
        ItemGrid_Layout materialOptions = instance.MaterialOptions;
        bool useCollpasedCoinsAmmo = RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo;
        float x = materialOptions.FirstItemLocation.X;
        materialOptions.FirstItemLocation.X = x;
        int size = this.MaterialOptions._size;
        float x2 = instance.MaterialBackingTLOffset.X;
        float y = instance.MaterialBackingTLOffset.Y;
        float x3 = instance.MaterialBackingBROffset.X;
        float y2 = instance.MaterialBackingBROffset.Y;
        Rectangle rectangle;
        return rectangle;
    }
References RubbleMakerUI_Layout.Backing, RubbleMakerUI_Layout.Instance, j__TPar, RubbleMakerUI_Layout.MaterialBackingBROffset, RubbleMakerUI_Layout.MaterialBackingTLOffset, MaterialOptions, RubbleMakerUI_Layout.MaterialOptions, GUIPanel.Region(), ControlAnchor.SetMainMenuPageRegion(), RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by DrawOverlay(), and IsOverMaterial().