terraria-cpp2il-methodrecon: System.Resources.ResourceReader.FindType
FindType()
RuntimeType System.Resources.ResourceReader.FindType (int typeIndex) inline private
Definition at line 420 of file ResourceReader.cs.
        {
            RuntimeType[] typeTable = this._typeTable;
            MonoTypeInfo type_info = typeTable.type_info;
            object genericCache = typeTable.GenericCache;
            if (type_info == null)
            {
            }
            BinaryReader store = this._store;
            BinaryReader store2 = this._store;
            int[] typeNamePositions = this._typeNamePositions;
            BinaryReader store3 = this._store;
            RuntimeType[] typeTable2 = this._typeTable;
            if (store3 != null && store3 == null)
            {
                throw new ArrayTypeMismatchException();
            }
            long num = 0L;
            int num2 = 6;
            BinaryReader store4 = this._store;
            if (num == 0L)
            {
                if (num2 == 0)
                {
                    object genericCache2 = this._typeTable.GenericCache;
                }
                string resourceString = Environment.GetResourceString("Corrupt .resources file.  The specified type doesn't exist.");
                throw new InvalidCastException();
            }
            throw new OutOfMemoryException();
        }
References System.Resources.ResourceReader._store, System.Resources.ResourceReader._typeNamePositions, System.Resources.ResourceReader._typeTable, System.RuntimeType.GenericCache, System.Environment.GetResourceString(), j__TPar, and System.L.
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader.DeserializeObject(), and System.Resources.ResourceReader.LoadString().