terraria-cpp2il-methodrecon: System.Resources.ResourceReader.SkipString
SkipString()
void System.Resources.ResourceReader.SkipString () inline private
Definition at line 58 of file ResourceReader.cs.
        {
            int num = this._store.Read7BitEncodedInt();
            BinaryReader store = this._store;
        }
References System.Resources.ResourceReader._store, and System.IO.BinaryReader.Read7BitEncodedInt().
Referenced by System.Resources.ResourceReader._ReadResources(), and System.Resources.ResourceReader.GetValueForNameIndex().