terraria-cpp2il-methodrecon: System.Resources.ResourceReader.AllocateStringForNameIndex
AllocateStringForNameIndex()
unsafe string System.Resources.ResourceReader.AllocateStringForNameIndex (int index, [Out] int dataOffset) inline private
Definition at line 190 of file ResourceReader.cs.
        {
            int namePosition = this.GetNamePosition(index);
            Monitor.Enter(this, index != 0);
            BinaryReader store = this._store;
            long nameSectionOffset = this._nameSectionOffset;
            int num = this._store.Read7BitEncodedInt();
            if (this._ums != null)
            {
                UnmanagedMemoryStream ums = this._ums;
                byte* positionPointer = this._ums.PositionPointer;
                string text;
                return text;
            }
            if (this._store != null)
            {
                BinaryReader store2 = this._store;
                dataOffset.m_value = store2;
                BinaryReader store3 = this._store;
                long dataSectionOffset = this._dataSectionOffset;
                long num2 = 0L;
                UnmanagedMemoryStream ums2 = this._ums;
                BinaryReader store4 = this._store;
                num2.m_value = store4;
                BinaryReader store5 = this._store;
                long dataSectionOffset2 = this._dataSectionOffset;
                long num3 = 0L;
                int num4 = 20;
                if (dataSectionOffset2 != 0L)
                {
                    Monitor.Exit(this);
                }
                if (num3 != 0L)
                {
                    throw new OutOfMemoryException();
                }
                if (num4 == 0)
                {
                    Encoding unicode = Encoding.Unicode;
                }
            }
            throw new ArrayTypeMismatchException();
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._nameSectionOffset, System.Resources.ResourceReader._store, System.Resources.ResourceReader._ums, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Resources.ResourceReader.GetNamePosition(), System.index, j__TPar, System.L, System.IO.UnmanagedMemoryStream.PositionPointer, System.IO.BinaryReader.Read7BitEncodedInt(), System.text, and System.Text.Encoding.Unicode.