terraria-cpp2il-methodrecon: System.Net.Sockets.Socket.Send
Send() [2/5]
int System.Net.Sockets.Socket.Send (byte[] buffer, int offset, int size, SocketFlags socketFlags, [Out] SocketError errorCode) inline
Definition at line 1392 of file Socket.cs.
        {
            this.ThrowIfDisposedAndClosed();
            this.ThrowIfBufferNull(buffer);
            this.ThrowIfBufferOutOfRange(buffer, offset, size);
            int num2;
            if (size != 0)
            {
                if (buffer != null)
                {
                }
                SafeSocketHandle handle = this.m_Handle;
                bool flag = this.is_blocking;
                int num = 1;
                this.is_connected = num != 0;
                return num2;
            }
            return num2;
        }
References System.Net.Sockets.Socket.is_blocking, j__TPar, System.Net.Sockets.Socket.m_Handle, System.offset, System.Net.Sockets.Socket.ThrowIfBufferNull(), System.Net.Sockets.Socket.ThrowIfBufferOutOfRange(), and System.Net.Sockets.Socket.ThrowIfDisposedAndClosed().