terraria-cpp2il-methodrecon: System.Net.Sockets.Socket.ThrowIfDisposedAndClosed
ThrowIfDisposedAndClosed()
void System.Net.Sockets.Socket.ThrowIfDisposedAndClosed () inline private
Definition at line 1797 of file Socket.cs.
        {
            /*
An exception occurred when decompiling this method (060013B2)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void System.Net.Sockets.Socket::ThrowIfDisposedAndClosed()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    IL_0010:
    stloc:Type(var_1_16, call:Type(object::GetType, ldloc:Socket[exp:object](this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1846
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.Bind(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Disconnect(), System.Net.Sockets.Socket.EndConnect(), System.Net.Sockets.Socket.EndDisconnect(), System.Net.Sockets.Socket.EndReceive(), System.Net.Sockets.Socket.EndReceiveFrom(), System.Net.Sockets.Socket.EndReceiveFrom_internal(), System.Net.Sockets.Socket.EndSend(), System.Net.Sockets.Socket.EndSendTo(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.Listen(), System.Net.Sockets.Socket.Poll(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SetSocketOption(), and System.Net.Sockets.Socket.Shutdown().