terraria-cpp2il-methodrecon: System.Net.Sockets.Socket.BeginSend
BeginSend() [1/2]
IAsyncResult System.Net.Sockets.Socket.BeginSend (byte[] buffer, int offset, int size, SocketFlags socketFlags, [Out] SocketError errorCode, AsyncCallback callback, object state) inline
Definition at line 1471 of file Socket.cs.
        {
            this.ThrowIfDisposedAndClosed();
            this.ThrowIfBufferNull(buffer);
            this.ThrowIfBufferOutOfRange(buffer, offset, size);
            if (!this.is_connected)
            {
                return;
            }
            SemaphoreSlim writeSem = this.WriteSem;
            if (offset == 0)
            {
                return;
            }
        }
References System.Net.Sockets.Socket.is_connected, j__TPar, System.offset, System.Net.Sockets.Socket.ThrowIfBufferNull(), System.Net.Sockets.Socket.ThrowIfBufferOutOfRange(), System.Net.Sockets.Socket.ThrowIfDisposedAndClosed(), and System.Net.Sockets.Socket.WriteSem.