terraria-cpp2il-methodrecon: Terraria.DataStructures.DrawData.DrawData
DrawData() [1/5]
Terraria.DataStructures.DrawData.DrawData (Texture2D texture, Vector2 position, Color color) inline
Definition at line 11 of file DrawData.cs.
        {
            this.texture = texture;
            this.color = position;
            if (!true)
            {
            }
            long num = 0L;
            long num2 = 0L;
            long num3 = 0L;
            long num4 = 0L;
            Rectangle rectangle = texture.Frame(1, 1, (int)num, (int)num2, (int)num3, (int)num4);
            this.sourceRect = rectangle;
            this.sourceRect.Width = 1;
            if (!true)
            {
            }
            if (!true)
            {
            }
            this.origin = 1;
            if (!true)
            {
            }
            this.scale = 1;
        }
References j__TPar, System.L, Terraria.DataStructures.DrawData.position, and Terraria.DataStructures.DrawData.texture.
Referenced by Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_CapricornMask(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_05_TallHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_07_JustHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_DrawSelectionRect(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), and Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD().