terraria-cpp2il-methodrecon: DeviceVPPICalculator.GetViewportSafeRegion
GetViewportSafeRegion()
Rect DeviceVPPICalculator.GetViewportSafeRegion () inline inherited
Definition at line 212 of file DeviceVPPICalculator.cs.
    {
        if (!true)
        {
        }
        int width = Screen.width;
        int height = Screen.height;
        int width2 = Screen.width;
        int height2 = Screen.height;
        Rect safeArea = this.GetSafeArea();
        float xMin = safeArea.xMin;
        float xMin2 = safeArea.xMin;
        float xMax = safeArea.xMax;
        float xMax2 = safeArea.xMax;
        float yMin = safeArea.yMin;
        float yMin2 = safeArea.yMin;
        float yMax = safeArea.yMax;
        float yMax2 = safeArea.yMax;
        return safeArea;
    }
References DeviceVPPICalculator.GetSafeArea(), UnityEngine.Screen.height, j__TPar, UnityEngine.Screen.width, UnityEngine.Rect.xMax, UnityEngine.Rect.xMin, UnityEngine.Rect.yMax, and UnityEngine.Rect.yMin.
Referenced by DeviceVPPICalculator.GetDefaultVerticalResolution(), and DeviceVPPICalculator.UpdatePixelScale().