terraria-cpp2il-methodrecon: DeviceVPPICalculator.UpdatePixelScale
UpdatePixelScale()
void DeviceVPPICalculator.UpdatePixelScale (bool safeRegion = false) inline protected inherited
Definition at line 121 of file DeviceVPPICalculator.cs.
    {
        bool isEditor = Application.isEditor;
        this.UpdateForcedEmulation();
        float deviceDPI = this.GetDeviceDPI();
        DeviceVPPICalculator.EditorMobileEmuEntry forceEMUEntry = this._forceEMUEntry;
        int height;
        if (forceEMUEntry != null)
        {
            float dpi = forceEMUEntry.DPI;
            this.DPI = dpi;
            height = forceEMUEntry.Height;
            return;
        }
        this.DPI = (float)height;
        float height2 = this.GetViewportSafeRegion().height;
        float dpi2 = this.DPI;
        this.PhysicalHeight = (float)height;
        if (forceEMUEntry == null)
        {
        }
        bool vppioverridden = this.VPPIOverridden;
        if (vppioverridden)
        {
            float vppi = this.VPPI;
            return;
        }
        AnimationCurve physicalToResolution = this.PhysicalToResolution;
        float physicalHeight = this.PhysicalHeight;
        float num = physicalToResolution.Evaluate(height2);
        float physicalHeight2 = this.PhysicalHeight;
        this.VPPI = physicalHeight;
        float zoomScale = this._zoomScale;
        float dpi3 = this.DPI;
        this.PixelScale = physicalHeight;
    }
References DeviceVPPICalculator._forceEMUEntry, DeviceVPPICalculator._zoomScale, DeviceVPPICalculator.DPI, DeviceVPPICalculator.GetDeviceDPI(), DeviceVPPICalculator.GetViewportSafeRegion(), UnityEngine.Rect.height, UnityEngine.Application.isEditor, j__TPar, DeviceVPPICalculator.PhysicalHeight, DeviceVPPICalculator.PhysicalToResolution, DeviceVPPICalculator.UpdateForcedEmulation(), DeviceVPPICalculator.VPPI, and DeviceVPPICalculator.VPPIOverridden.