terraria-cpp2il-methodrecon: DeviceVPPICalculator.GetDefaultVerticalResolution
GetDefaultVerticalResolution()
float DeviceVPPICalculator.GetDefaultVerticalResolution (bool safeRegion = false) inline inherited
Definition at line 85 of file DeviceVPPICalculator.cs.
    {
        if (!true)
        {
        }
        float deviceDPI = this.GetDeviceDPI();
        float deviceDPI2 = this.GetDeviceDPI();
        DeviceVPPICalculator.EditorMobileEmuEntry forceEMUEntry = this._forceEMUEntry;
        if (forceEMUEntry != null)
        {
            int height = forceEMUEntry.Height;
            Rect viewportSafeRegion = this.GetViewportSafeRegion();
            float height2 = viewportSafeRegion.height;
            float dpi = this.DPI;
            float height3 = viewportSafeRegion.height;
            float num = this.PhysicalToResolution.Evaluate(height3);
            if (forceEMUEntry == null)
            {
            }
            if (forceEMUEntry == null)
            {
            }
        }
        int height4 = Screen.height;
        DeviceVPPICalculator.EditorMobileEmuEntry forceEMUEntry2 = this._forceEMUEntry;
        while (forceEMUEntry2 != null)
        {
        }
        float height5 = this.GetViewportSafeRegion().height;
        while (forceEMUEntry2 != null)
        {
        }
        throw new MissingMethodException();
    }
References DeviceVPPICalculator._forceEMUEntry, DeviceVPPICalculator.DPI, UnityEngine.AnimationCurve.Evaluate(), DeviceVPPICalculator.GetDeviceDPI(), DeviceVPPICalculator.GetViewportSafeRegion(), UnityEngine.Rect.height, UnityEngine.Screen.height, j__TPar, and DeviceVPPICalculator.PhysicalToResolution.
html>