terraria-cpp2il-methodrecon: System.Array.SorterObjectArray.PickPivotAndPartition
PickPivotAndPartition()
int System.Array.SorterObjectArray.PickPivotAndPartition (int lo, int hi) inline private
Definition at line 1630 of file Array.cs.
            {
                this.SwapIfGreaterWithItems(lo, hi);
                this.SwapIfGreaterWithItems(lo, hi);
                this.SwapIfGreaterWithItems(lo, hi);
                this.Swap(lo, hi);
                IComparer comparer = this.comparer;
                IComparer comparer2 = this.comparer;
                this.Swap(lo, hi);
                this.Swap(lo, hi);
                return lo;
            }
References System.Array.SorterObjectArray.comparer, j__TPar, System.Array.SorterObjectArray.Swap(), and System.Array.SorterObjectArray.SwapIfGreaterWithItems().
Referenced by System.Array.SorterObjectArray.IntroSort().