terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexParser.AddAlternate
AddAlternate()
void System.Text.RegularExpressions.RegexParser.AddAlternate () inline private
Definition at line 1019 of file RegexParser.cs.
        {
            int ntype = this._group.NType;
            RegexNode alternation = this._alternation;
            RegexNode concatenation = this._concatenation;
            RegexNode regexNode = concatenation.ReverseLeft();
            alternation.AddChild(concatenation);
            RegexOptions options = this._options;
        }
References System.Text.RegularExpressions.RegexParser._alternation, System.Text.RegularExpressions.RegexParser._concatenation, System.Text.RegularExpressions.RegexParser._group, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexNode.AddChild(), j__TPar, System.Text.RegularExpressions.RegexNode.NType, System.options, and System.Text.RegularExpressions.RegexNode.ReverseLeft().
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().