terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexParser.ScanGroupOpen
ScanGroupOpen()
RegexNode System.Text.RegularExpressions.RegexParser.ScanGroupOpen () inline private
Definition at line 273 of file RegexParser.cs.
        {
            string pattern = this._pattern;
            int currentPos = this._currentPos;
            int stringLength = pattern._stringLength;
            char c = pattern[currentPos];
            string pattern2 = this._pattern;
            int currentPos2 = this._currentPos;
            char c2 = pattern2[currentPos2];
            string pattern3 = this._pattern;
            int currentPos3 = this._currentPos;
            int stringLength2 = pattern3._stringLength;
            char c3 = pattern3[currentPos2];
            RegexOptions options = this._options;
            int currentPos4;
            if (this._ignoreNextParen)
            {
                long num = 0L;
                currentPos4 = this._currentPos;
                string pattern4 = this._pattern;
                this._currentPos = (int)num;
                int stringLength3 = pattern4._stringLength;
                this._currentPos = currentPos4;
                char c4 = pattern4[(int)num];
            }
            int autocap = this._autocap;
            this._autocap = currentPos4;
            string pattern5 = this._pattern;
            int currentPos5 = this._currentPos;
            int stringLength4 = pattern5._stringLength;
            this._currentPos = stringLength4;
            char c5 = pattern5[currentPos5];
            RegexOptions options2 = this._options;
            RegexOptions options3 = this._options;
            string pattern6 = this._pattern;
            int currentPos6 = this._currentPos;
            int stringLength5 = pattern6._stringLength;
            char c6 = pattern6[currentPos6];
            if (stringLength5 == 0)
            {
            }
            bool flag = RegexCharClass.IsWordChar(c6);
            string text = this.ScanCapname();
            if (this._capnames != null)
            {
                string pattern7 = this._pattern;
                int currentPos7 = this._currentPos;
                int stringLength6 = pattern7._stringLength;
                this._currentPos = stringLength6;
                char c7 = pattern7[currentPos7];
                RegexOptions options4 = this._options;
                int num2 = this.CaptureSlotFromName(text);
                int num3 = 33;
                if (num3 == 0)
                {
                }
                if (num3 == 0)
                {
                    goto IL_01B1;
                }
            }
            int num4;
            if (num4 == 0)
            {
                return "Capture number cannot be zero.";
            }
            int num5 = 1;
            bool flag2;
            if (!flag2)
            {
            }
            char c8;
            bool flag3 = RegexCharClass.IsWordChar(c8);
            if (!flag2)
            {
                return "Reference to undefined group name {0}.";
            }
            if (num5 != 0)
            {
            }
            IL_01B1:
            return "Invalid group name: Group names must begin with a word character.";
        }
References System.Text.RegularExpressions.RegexParser._autocap, System.Text.RegularExpressions.RegexParser._capnames, System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._ignoreNextParen, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser._pattern, System.Text.RegularExpressions.RegexParser.CaptureSlotFromName(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), j__TPar, System.L, System.options, System.Text.RegularExpressions.RegexParser.ScanCapname(), and System.text.