terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexParser.ScanCharClass
ScanCharClass()
RegexCharClass System.Text.RegularExpressions.RegexParser.ScanCharClass (bool caseInsensitive, bool scanOnly) inline private
Definition at line 193 of file RegexParser.cs.
        {
            string pattern = this._pattern;
            int currentPos = this._currentPos;
            int stringLength = pattern._stringLength;
            char c = pattern[currentPos];
            int currentPos2 = this._currentPos;
            this._currentPos = currentPos2;
            string pattern2 = this._pattern;
            int stringLength2 = pattern2._stringLength;
            long num = 0L;
            this._currentPos = stringLength2;
            char c2 = pattern2[currentPos2];
            string pattern3 = this._pattern;
            int currentPos3 = this._currentPos;
            int stringLength3 = pattern3._stringLength;
            this._currentPos = stringLength3;
            char c3 = pattern3[currentPos3];
            RegexOptions options = this._options;
            string pattern4 = this._pattern;
            string pattern5 = this._pattern;
            int currentPos4 = this._currentPos;
            int stringLength4 = pattern5._stringLength;
            char c4 = pattern5[currentPos4];
            long num2 = 0L;
            RegexCharClass regexCharClass = this.ScanCharClass(num != 0L, num2 != 0L);
            string pattern6 = this._pattern;
            int currentPos5 = this._currentPos;
            int stringLength5 = pattern6._stringLength;
            char c5 = pattern6[currentPos5];
            int currentPos6 = this._currentPos;
            this._currentPos = stringLength5;
            string text = this.ScanCapname();
            string pattern7 = this._pattern;
            int currentPos7 = this._currentPos;
            int stringLength6 = pattern7._stringLength;
            this._currentPos = stringLength6;
            char c6 = pattern7[currentPos7];
            int currentPos8 = this._currentPos;
            string pattern8 = this._pattern;
            this._currentPos = stringLength6;
            char c7 = pattern8[currentPos8];
            this._currentPos = currentPos6;
            int num3 = 91;
            string pattern9 = this._pattern;
            int currentPos9 = this._currentPos;
            int stringLength7 = pattern9._stringLength;
            char c8 = pattern9[currentPos9];
            int currentPos10 = this._currentPos;
            char c9 = this._pattern[currentPos9];
            string pattern10 = this._pattern;
            int currentPos11 = this._currentPos;
            int stringLength8 = pattern10._stringLength;
            char c10 = pattern10[currentPos11];
            string pattern11 = this._pattern;
            int currentPos12 = this._currentPos;
            int stringLength9 = pattern11._stringLength;
            int currentPos13 = this._currentPos;
            this._currentPos = currentPos13;
            RegexCharClass regexCharClass2 = this.ScanCharClass(currentPos12 != 0, num3 != 0);
            string pattern12 = this._pattern;
            int currentPos14 = this._currentPos;
            int stringLength10 = pattern12._stringLength;
            char c11 = pattern12[currentPos14];
            int currentPos15 = this._currentPos;
            this._currentPos = currentPos15;
            RegexOptions options2 = this._options;
            int currentPos16 = this._currentPos;
            this._currentPos = currentPos16;
            char c12 = this.ScanCharEscape();
            RegexOptions options3 = this._options;
            string text2 = this.ParseProperty();
            string text3 = this.ParseProperty();
            string pattern13 = this._pattern;
            CultureInfo culture = this._culture;
            ArgumentException ex = this.MakeException("Unterminated [] set.");
            return "[x-y] range in reverse order.";
        }
References System.Text.RegularExpressions.RegexParser._culture, System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser._pattern, System.culture, j__TPar, System.L, System.Text.RegularExpressions.RegexParser.MakeException(), System.options, System.Text.RegularExpressions.RegexParser.ParseProperty(), System.Text.RegularExpressions.RegexParser.ScanCapname(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), System.Text.RegularExpressions.RegexParser.ScanCharEscape(), and System.text.
Referenced by System.Text.RegularExpressions.RegexParser.ScanCharClass(), and System.Text.RegularExpressions.RegexParser.ScanRegex().