terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexParser.ScanRegex
ScanRegex()
RegexNode System.Text.RegularExpressions.RegexParser.ScanRegex () inline private
Definition at line 101 of file RegexParser.cs.
        {
            RegexOptions options = this._options;
            string pattern = this._pattern;
            int currentPos = this._currentPos;
            int stringLength = pattern._stringLength;
            this.ScanBlank();
            string pattern2 = this._pattern;
            int currentPos2 = this._currentPos;
            RegexOptions options2 = this._options;
            int stringLength2 = pattern2._stringLength;
            char c = pattern2[currentPos2];
            if (options2 == RegexOptions.None)
            {
            }
            bool flag = RegexParser.IsSpecial(c);
            bool flag2 = this.IsTrueQuantifier();
            int currentPos3 = this._currentPos;
            string pattern3 = this._pattern;
            this._currentPos = currentPos2;
            int stringLength3 = pattern3._stringLength;
            char c2 = pattern3[currentPos2];
            if (options2 == RegexOptions.None)
            {
            }
            bool flag3 = RegexParser.IsStopperX(c2);
            bool flag4 = this.IsTrueQuantifier();
            int currentPos4 = this._currentPos;
            string pattern4 = this._pattern;
            this._currentPos = currentPos2;
            int stringLength4 = pattern4._stringLength;
            int currentPos5 = this._currentPos;
            this.ScanBlank();
            string pattern5 = this._pattern;
            int currentPos6 = this._currentPos;
            int stringLength5 = pattern5._stringLength;
            long num = 0L;
            char c3 = pattern5[currentPos6];
            if (options2 == RegexOptions.None)
            {
            }
            bool flag5 = RegexParser.IsSpecial(c3);
            bool flag6 = RegexParser.IsQuantifier(c3);
            int currentPos7 = this._currentPos;
            this._currentPos = currentPos7;
            long num2 = 0L;
            long num3 = 0L;
            this.AddConcatenate(currentPos2, (int)num, num3 != 0L);
            char c4;
            if (num2 != 0L)
            {
                c4 = this._pattern[currentPos2];
                this.AddUnitOne(c4);
            }
            RegexOptions options3 = this._options;
            this.AddAlternate();
            RegexOptions options4 = this._options;
            long num4 = 0L;
            string text = this.ScanCharClass(c4 != '\0', num4 != 0L).ToStringClass();
            RegexOptions options5 = this._options;
            long num5 = 0L;
            RegexNode regexNode = this.ScanBackslash(num5 != 0L);
            this._unit = regexNode;
            return regexNode;
        }
References System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser._pattern, System.Text.RegularExpressions.RegexParser.AddAlternate(), System.Text.RegularExpressions.RegexParser.AddConcatenate(), System.Text.RegularExpressions.RegexParser.AddUnitOne(), System.Text.RegularExpressions.RegexParser.IsQuantifier(), System.Text.RegularExpressions.RegexParser.IsSpecial(), System.Text.RegularExpressions.RegexParser.IsStopperX(), System.Text.RegularExpressions.RegexParser.IsTrueQuantifier(), j__TPar, System.L, System.options, System.Text.RegularExpressions.RegexParser.ScanBackslash(), System.Text.RegularExpressions.RegexParser.ScanBlank(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), System.text, and System.Text.RegularExpressions.RegexCharClass.ToStringClass().