terraria-cpp2il-methodrecon: System.Threading.CancellationTokenSource.NotifyCancellation
NotifyCancellation()
void System.Threading.CancellationTokenSource.NotifyCancellation (bool throwOnFirstException) inline private inherited
Definition at line 257 of file CancellationTokenSource.cs.
        {
            int state = this._state;
            Timer timer = this._timer;
            long num;
            if (timer != null)
            {
                num = 0L;
                timer.Dispose();
            }
            int currentManagedThreadId = Environment.CurrentManagedThreadId;
            ManualResetEvent kernelEvent = this._kernelEvent;
            this._threadIDExecutingCallbacks = currentManagedThreadId;
            if (kernelEvent != null)
            {
                bool flag = kernelEvent.Set();
            }
            this.ExecuteCallbackHandlers(num != 0L);
        }
References System.Threading.CancellationTokenSource._kernelEvent, System.Threading.CancellationTokenSource._state, System.Threading.CancellationTokenSource._timer, System.Environment.CurrentManagedThreadId, System.Threading.Timer.Dispose(), System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(), j__TPar, System.L, System.Threading.EventWaitHandle.Set(), and System.state.
Referenced by System.Threading.CancellationTokenSource.Cancel(), and System.Threading.CancellationTokenSource.Cancel().