terraria-cpp2il-methodrecon: Ionic.BZip2.BZip2Compressor.moveToFrontCodeAndSend
moveToFrontCodeAndSend()
void Ionic.BZip2.BZip2Compressor.moveToFrontCodeAndSend () inline private
Definition at line 528 of file BZip2Compressor.cs.
        {
            BitWriter bitWriter = this.bw;
            int num = this.origPtr;
            bitWriter.WriteBits(24, (uint)num);
            this.generateMTFValues();
            this.sendMTFValues();
        }
References Ionic.BZip2.BZip2Compressor.bw, Ionic.BZip2.BZip2Compressor.generateMTFValues(), j__TPar, Ionic.BZip2.BZip2Compressor.origPtr, Ionic.BZip2.BZip2Compressor.sendMTFValues(), and Ionic.BZip2.BitWriter.WriteBits().
Referenced by Ionic.BZip2.BZip2Compressor.CompressAndWrite().