terraria-cpp2il-methodrecon: Ionic.BZip2.BZip2Compressor.CompressAndWrite
CompressAndWrite()
void Ionic.BZip2.BZip2Compressor.CompressAndWrite () inline
Definition at line 183 of file BZip2Compressor.cs.
        {
            int num = this.runLength;
            int num2 = 1;
            bool flag = this.AddRunToOutputBlock(num2 != 0);
            int num3 = this.last;
            this.blockSort();
            BitWriter bitWriter = this.bw;
            int num4 = 8;
            int num5 = 49;
            bitWriter.WriteBits(num4, (uint)num5);
            BitWriter bitWriter2 = this.bw;
            int num6 = 8;
            int num7 = 65;
            bitWriter2.WriteBits(num6, (uint)num7);
            BitWriter bitWriter3 = this.bw;
            int num8 = 8;
            int num9 = 89;
            bitWriter3.WriteBits(num8, (uint)num9);
            BitWriter bitWriter4 = this.bw;
            int num10 = 8;
            int num11 = 38;
            bitWriter4.WriteBits(num10, (uint)num11);
            BitWriter bitWriter5 = this.bw;
            int num12 = 8;
            int num13 = 83;
            bitWriter5.WriteBits(num12, (uint)num13);
            BitWriter bitWriter6 = this.bw;
            int num14 = 8;
            int num15 = 89;
            bitWriter6.WriteBits(num14, (uint)num15);
            int crc32Result = this.crc.Crc32Result;
            BitWriter bitWriter7 = this.bw;
            this.<Crc32>k__BackingField = (uint)crc32Result;
            bitWriter7.WriteInt((uint)crc32Result);
            BitWriter bitWriter8 = this.bw;
            bool flag2 = this.blockRandomised;
            int num16 = 1;
            bitWriter8.WriteBits(num16, flag2 ? 1U : 0U);
            this.moveToFrontCodeAndSend();
            this.crc.Reset();
            bool[] inUse = this.cstate.inUse;
        }
References Ionic.BZip2.BZip2Compressor.AddRunToOutputBlock(), Ionic.BZip2.BZip2Compressor.blockRandomised, Ionic.BZip2.BZip2Compressor.blockSort(), Ionic.BZip2.BZip2Compressor.bw, Ionic.BZip2.BZip2Compressor.crc, Ionic.BZip2.BZip2Compressor.Crc32, Ionic.Crc.CRC32.Crc32Result, Ionic.BZip2.BZip2Compressor.cstate, j__TPar, Ionic.BZip2.BZip2Compressor.k__BackingField, Ionic.BZip2.BZip2Compressor.last, Ionic.BZip2.BZip2Compressor.moveToFrontCodeAndSend(), Ionic.Crc.CRC32.Reset(), Ionic.BZip2.BZip2Compressor.runLength, System.U, and Ionic.BZip2.BitWriter.WriteBits().
Referenced by Ionic.BZip2.BZip2OutputStream.Finish(), and Ionic.BZip2.BZip2OutputStream.Write().