terraria-cpp2il-methodrecon: System.Math.Sign
Sign() [1/4]
static int System.Math.Sign (double value) inline static
Definition at line 252 of file Math.cs.
        {
            return 1;
        }
Referenced by Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_134_Ballista(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_194_HorsemanPumpkin(), Terraria.Player.CanParryAgainst(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ChasePlayerTop(), Terraria.Wiring.MassWireOperationInner(), Terraria.Main.snowing(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Collision.TupleHitLine(), and Terraria.Player.Yoraiz0rEye().