terraria-cpp2il-methodrecon: System.Linq.Error.ArgumentNull
ArgumentNull()
static Exception System.Linq.Error.ArgumentNull (string s) inline static package
Definition at line 10 of file Error.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by System.Linq.Enumerable.All< TSource >(), System.Linq.Enumerable.Any< TSource >(), System.Linq.Enumerable.Any< TSource >(), System.Linq.Enumerable.Contains< TSource >(), System.Linq.Enumerable.Count< TSource >(), System.Linq.Lookup< TKey, TElement >.Create< TSource >(), System.Linq.Enumerable.ElementAt< TSource >(), System.Linq.Enumerable.First< TSource >(), System.Linq.Enumerable.FirstOrDefault< TSource >(), System.Linq.Enumerable.FirstOrDefault< TSource >(), System.Linq.Enumerable.Last< TSource >(), System.Linq.Enumerable.LastOrDefault< TSource >(), System.Linq.Enumerable.Max(), System.Linq.Enumerable.Min(), System.Linq.Enumerable.Select< TResult, TSource >(), System.Linq.Enumerable.SequenceEqual< TSource >(), System.Linq.Enumerable.Single< TSource >(), System.Linq.Enumerable.SingleOrDefault< TSource >(), System.Linq.Enumerable.SingleOrDefault< TSource >(), System.Linq.Enumerable.ToDictionary< TKey, TElement, TSource >(), and System.Linq.Enumerable.Where< TSource >().