terraria-cpp2il-methodrecon: System.Runtime.InteropServices.SafeHandle.DangerousAddRef
DangerousAddRef()
void System.Runtime.InteropServices.SafeHandle.DangerousAddRef (bool success) inline inherited
Definition at line 112 of file SafeHandle.cs.
        {
            if (this._fullyInitialized)
            {
                int state = this._state;
                return;
            }
        }
References System.Runtime.InteropServices.SafeHandle._fullyInitialized, System.Runtime.InteropServices.SafeHandle._state, and System.state.
Referenced by System.Net.Security.SafeCredentialReference.SafeCredentialReference(), System.Net.Sockets.Socket.Blocking_internal(), System.Net.Sockets.Socket.Disconnect_internal(), and System.Net.Sockets.Socket.Listen_internal().