terraria-cpp2il-methodrecon: System.Runtime.InteropServices.SafeHandle.InternalDispose
InternalDispose()
void System.Runtime.InteropServices.SafeHandle.InternalDispose () inline private inherited
Definition at line 130 of file SafeHandle.cs.
        {
            bool fullyInitialized;
            do
            {
                fullyInitialized = this._fullyInitialized;
            }
            while (!fullyInitialized);
            this.DangerousReleaseInternal(true);
            if (!fullyInitialized)
            {
            }
            GC.SuppressFinalize(this);
        }
References System.Runtime.InteropServices.SafeHandle._fullyInitialized, System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal(), j__TPar, and System.GC.SuppressFinalize().
Referenced by System.Runtime.InteropServices.SafeHandle.Dispose().