terraria-cpp2il-methodrecon: GUICoins.ItemDraw
ItemDraw()
void GUICoins.ItemDraw (ItemGrid_Layout gridLayout, int index, Microsoft::Xna::Framework::Vector2 position, float scale) inline
Definition at line 152 of file GUICoins.cs.
    {
        this.ItemOver(index);
        GUIControllerCoins guicontrollerCoins;
        guicontrollerCoins.itemRow = index;
        Mouse.UpdateUICursorPoint();
        int num = this.cursorOver;
        if (!true)
        {
        }
        if (this.itemOver == 0)
        {
        }
        bool useCollpasedCoinsAmmo = RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo;
        !0 instance = PageControllerLayoutDefinition.Instance;
        if (60 == 0)
        {
        }
        ItemSlot.SetSelectHighlight(true, scale);
        if (instance == null)
        {
        }
        Main.inventoryScale = scale;
        int myPlayer = Main.myPlayer;
        int num2 = 16256;
        int myPlayer2 = Main.myPlayer;
        if (num2 == 0)
        {
        }
    }
References cursorOver, System.index, PageControllerLayoutDefinition< T >.Instance, ItemOver(), itemOver, j__TPar, Terraria.Main.myPlayer, Terraria.UI.ItemSlot.SetSelectHighlight(), Microsoft.Xna.Framework.Input.Mouse.UpdateUICursorPoint(), and RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo.