terraria-cpp2il-methodrecon: System.DateTimeParse.Lex
Lex()
static bool System.DateTimeParse.Lex (DateTimeParse::DS dps, __DTString str, DateTimeToken dtok, DateTimeRawInfo raw, DateTimeResult result, DateTimeFormatInfo dtfi, DateTimeStyles styles) inline static private
Definition at line 186 of file DateTimeParse.cs.
        {
            int num = 18;
            str.Value = num;
            int num2 = dtok.num;
            if (3 == 0)
            {
            }
            if (!true)
            {
            }
            Calendar taiwanCalendarDefaultInstance = DateTimeParse.GetTaiwanCalendarDefaultInstance();
            DateTimeFormatInfo taiwanCalendarDTFI = DateTimeFormatInfo.GetTaiwanCalendarDTFI();
            if (!true)
            {
            }
            Calendar japaneseCalendarDefaultInstance = DateTimeParse.GetJapaneseCalendarDefaultInstance();
            DateTimeFormatInfo japaneseCalendarDTFI = DateTimeFormatInfo.GetJapaneseCalendarDTFI();
            result.Year = japaneseCalendarDTFI;
            double fraction = raw.fraction;
            int num3 = 16;
            raw.fraction = fraction;
            str.Value = num3;
            int num4 = 15;
            str.Value = num4;
            bool flag;
            return flag;
        }
References System.DateTimeRawInfo.fraction, System.DateTimeParse.GetJapaneseCalendarDefaultInstance(), System.Globalization.DateTimeFormatInfo.GetJapaneseCalendarDTFI(), System.DateTimeParse.GetTaiwanCalendarDefaultInstance(), System.Globalization.DateTimeFormatInfo.GetTaiwanCalendarDTFI(), and j__TPar.