terraria-cpp2il-methodrecon: UnityEngine.UI.DefaultControls.CreateInputField
CreateInputField()
static GameObject UnityEngine.UI.DefaultControls.CreateInputField (DefaultControls::Resources resources) inline static
Definition at line 276 of file DefaultControls.cs.
        {
            if (!true)
            {
            }
            Type type;
            Type type2;
            Type type3;
            Type type4;
            if ((type == null || type != null) && (type2 == null || type2 != null) && (type3 == null || type3 != null) && (type4 == null || type4 != null))
            {
                GameObject gameObject;
                gameObject.GetComponent<Image>().type = Image.Type.Sliced;
                InputField component = gameObject.GetComponent<InputField>();
                GameObject gameObject2;
                Text component2 = gameObject2.GetComponent<Text>();
                DefaultControls.SetDefaultTextValues(component2);
                GameObject gameObject3;
                Text component3 = gameObject3.GetComponent<Text>();
                component3.fontStyle = FontStyle.Italic;
                RectTransform component4 = gameObject2.GetComponent<RectTransform>();
                RectTransform component5 = gameObject3.GetComponent<RectTransform>();
                component.textComponent = component2;
                component.placeholder = component3;
                return gameObject;
            }
            throw new ArrayTypeMismatchException();
        }
References UnityEngine.Component.GetComponent(), UnityEngine.GameObject.GetComponent(), j__TPar, and UnityEngine.UI.DefaultControls.SetDefaultTextValues().