terraria-cpp2il-methodrecon: UnityEngine.UI.DefaultControls.CreateScrollView
CreateScrollView()
static GameObject UnityEngine.UI.DefaultControls.CreateScrollView (DefaultControls::Resources resources) inline static
Definition at line 312 of file DefaultControls.cs.
        {
            Type type;
            Type type2;
            Type type3;
            Type type4;
            Type type5;
            if ((type == null || type != null) && (type2 == null || type2 != null) && (type3 == null || type3 != null) && (type4 == null || type4 != null) && (type5 == null || type5 != null))
            {
                GameObject gameObject;
                gameObject.name = "Scrollbar Horizontal";
                GameObject gameObject2;
                DefaultControls.SetParentAndAlign(gameObject, gameObject2);
                Vector2 sizeDelta = gameObject.GetComponent<RectTransform>().sizeDelta;
                GameObject gameObject3;
                gameObject3.name = "Scrollbar Vertical";
                DefaultControls.SetParentAndAlign(gameObject3, gameObject2);
                gameObject3.GetComponent<Scrollbar>().SetDirection(Scrollbar.Direction.BottomToTop, true);
                Vector2 sizeDelta2 = gameObject3.GetComponent<RectTransform>().sizeDelta;
                GameObject gameObject4;
                RectTransform component = gameObject4.GetComponent<RectTransform>();
                ScrollRect component2 = gameObject2.GetComponent<ScrollRect>();
                RectTransform rectTransform;
                component2.m_Content = rectTransform;
                component2.viewport = component;
                Scrollbar component3 = gameObject.GetComponent<Scrollbar>();
                component2.horizontalScrollbar = component3;
                Scrollbar component4 = gameObject3.GetComponent<Scrollbar>();
                component2.verticalScrollbar = component4;
                component2.horizontalScrollbarVisibility = ScrollRect.ScrollbarVisibility.AutoHideAndExpandViewport;
                component2.verticalScrollbarVisibility = ScrollRect.ScrollbarVisibility.AutoHideAndExpandViewport;
                component2.horizontalScrollbarSpacing = float.Epsilon;
                component2.verticalScrollbarSpacing = float.Epsilon;
                Image image;
                image.type = Image.Type.Sliced;
                Mask component5 = gameObject4.GetComponent<Mask>();
                long num = 0L;
                component5.showMaskGraphic = num != 0L;
                Image image2;
                image2.type = Image.Type.Sliced;
                return gameObject2;
            }
            throw new ArrayTypeMismatchException();
        }
References UnityEngine.Component.GetComponent(), UnityEngine.GameObject.GetComponent(), j__TPar, UnityEngine.L, and UnityEngine.UI.DefaultControls.SetParentAndAlign().