terraria-cpp2il-methodrecon: BindingsExample.BindingsExample.LoadBindings
LoadBindings()
void BindingsExample.BindingsExample.LoadBindings () inline private
Definition at line 55 of file BindingsExample.cs.
        {
            bool flag = PlayerPrefs.HasKey("Bindings");
            string @string = PlayerPrefs.GetString("Bindings");
            PlayerActions playerActions = this.playerActions;
            this.saveData = @string;
            playerActions.Load(@string);
        }
References UnityEngine.PlayerPrefs.GetString(), UnityEngine.PlayerPrefs.HasKey(), j__TPar, and InControl.PlayerActionSet.Load().