terraria-cpp2il-methodrecon: Terraria.GameContent.UI.States.UIVirtualKeyboard.TryEscapingMenu
TryEscapingMenu()
bool Terraria.GameContent.UI.States.UIVirtualKeyboard.TryEscapingMenu () inline private
Definition at line 233 of file UIVirtualKeyboard.cs.
        {
            if (this.CustomEscapeAttempt != null)
            {
            }
            bool edittingSign = this._edittingSign;
            if (edittingSign)
            {
                if (!edittingSign)
                {
                }
                Main.InputTextSignCancel();
            }
            if (this._edittingChest)
            {
                ChestUI.RenameChestCancel();
            }
            bool gameMenu = Main.gameMenu;
            if (this._cancelAction != null)
            {
                UIVirtualKeyboard.Cancel();
                return false;
            }
            IngameFancyUI.Close();
            return true;
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._cancelAction, Terraria.GameContent.UI.States.UIVirtualKeyboard._edittingChest, Terraria.GameContent.UI.States.UIVirtualKeyboard._edittingSign, Terraria.GameContent.UI.States.UIVirtualKeyboard.Cancel(), Terraria.UI.IngameFancyUI.Close(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CustomEscapeAttempt, Terraria.Main.gameMenu, Terraria.Main.InputTextSignCancel(), j__TPar, and Terraria.UI.ChestUI.RenameChestCancel().