terraria-cpp2il-methodrecon: Terraria.GameContent.UI.States.UIVirtualKeyboard.TextIsValidForSubmit
TextIsValidForSubmit()
bool Terraria.GameContent.UI.States.UIVirtualKeyboard.TextIsValidForSubmit () inline private
Definition at line 171 of file UIVirtualKeyboard.cs.
        {
            Func<string, bool> customTextValidationForUpdate = this.CustomTextValidationForUpdate;
            string text = this.Text;
            if (customTextValidationForUpdate != null)
            {
            }
            int stringLength = text.Trim()._stringLength;
            if (this._edittingSign || this._edittingChest)
            {
                return true;
            }
            bool allowEmpty = this._allowEmpty;
            return true;
        }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._allowEmpty, Terraria.GameContent.UI.States.UIVirtualKeyboard._edittingChest, Terraria.GameContent.UI.States.UIVirtualKeyboard._edittingSign, Terraria.GameContent.UI.States.UIVirtualKeyboard.CustomTextValidationForUpdate, j__TPar, System.text, and Terraria.GameContent.UI.States.UIVirtualKeyboard.Text.
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.b__50_14(), Terraria.GameContent.UI.States.UIVirtualKeyboard.InternalSubmit(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText().