terraria-cpp2il-methodrecon: GUICrafting.Draw
Draw()
void GUICrafting.Draw () inline
Definition at line 211 of file GUICrafting.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        Recipe.GetThroughDelayedFindRecipes();
        this.UpdateMaterialNavigation();
        if (num == 0)
        {
        }
        if (num == 0)
        {
        }
        long num2 = 0L;
        this.UpdateFilter(num2 != 0L);
        List<int> filteredItems = this.FilteredItems;
        int focusRecipe = Main.focusRecipe;
        int size = this.FilteredItems._size;
        !0 instance = PageControllerLayoutDefinition.Instance;
        !0 instance2 = PageControllerLayoutDefinition.Instance;
        !0 instance3 = PageControllerLayoutDefinition.Instance;
        Rectangle rectangle;
        if (rectangle == null)
        {
        }
        int mouseX = Main.mouseX;
        int mouseY = Main.mouseY;
    }
References System.Collections.Generic.List< T >._size, FilteredItems, Terraria.Main.focusRecipe, Terraria.Recipe.GetThroughDelayedFindRecipes(), PageControllerLayoutDefinition< T >.Instance, j__TPar, System.L, Terraria.Main.mouseX, Terraria.Main.mouseY, UpdateFilter(), and UpdateMaterialNavigation().