terraria-cpp2il-methodrecon: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin
DrawPlayer_12_Skin()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin (PlayerDrawSet drawinfo) inline static
Definition at line 934 of file PlayerDrawLayers.cs.
        {
            bool usesCompositeTorso = drawinfo.usesCompositeTorso;
            if (usesCompositeTorso)
            {
                if (!usesCompositeTorso)
                {
                }
                PlayerDrawLayers.DrawPlayer_12_Skin_Composite(drawinfo);
                return;
            }
            if (drawinfo.isSitting)
            {
                int num = 1;
                drawinfo.hidesBottomSkin = num != 0;
            }
            bool hidesTopSkin = drawinfo.hidesTopSkin;
            if (!hidesTopSkin)
            {
                float y = drawinfo.Position.Y;
                float torsoOffset = drawinfo.torsoOffset;
                drawinfo.Position.Y = y;
                if (!hidesTopSkin)
                {
                }
                float x = drawinfo.Position.X;
                Vector2 screenPosition = Main.screenPosition;
                Player drawPlayer = drawinfo.drawPlayer;
                float y2 = drawinfo.Position.Y;
                int width = drawPlayer.bodyFrame.Width;
                int width2 = drawPlayer.width;
                Vector2 screenPosition2 = Main.screenPosition;
                Player drawPlayer2 = drawinfo.drawPlayer;
                int num2 = 52992;
                int height = drawPlayer2.height;
                int height2 = drawPlayer2.bodyFrame.Height;
                Player drawPlayer3 = drawinfo.drawPlayer;
                float x2 = drawPlayer3.bodyPosition.X;
                float y3 = drawPlayer3.bodyPosition.Y;
                if (num2 == 0)
                {
                }
                Player drawPlayer4 = drawinfo.drawPlayer;
                int width3 = drawPlayer4.bodyFrame.Width;
                int height3 = drawPlayer4.bodyFrame.Height;
                Player drawPlayer5 = drawinfo.drawPlayer;
                Color colorBodySkin = drawinfo.colorBodySkin;
                float x3 = drawinfo.bodyVect.X;
                float y4 = drawinfo.bodyVect.Y;
                float bodyRotation = drawPlayer5.bodyRotation;
                int value = width3.m_value;
                SpriteEffects playerEffect = drawinfo.playerEffect;
                int skinDyePacked = drawinfo.skinDyePacked;
                float y5 = drawinfo.Position.Y;
                float torsoOffset2 = drawinfo.torsoOffset;
                drawinfo.Position.Y = y5;
            }
            bool hidesBottomSkin = drawinfo.hidesBottomSkin;
            if (!hidesBottomSkin)
            {
                if (!hidesBottomSkin)
                {
                }
                bool flag = PlayerDrawLayers.IsBottomOverridden(drawinfo);
                bool isSitting = drawinfo.isSitting;
                if (!hidesBottomSkin)
                {
                }
                if (isSitting)
                {
                    Color colorLegs = drawinfo.colorLegs;
                    if (!hidesBottomSkin)
                    {
                    }
                    return;
                }
                float x4 = drawinfo.Position.X;
                if (!hidesBottomSkin)
                {
                }
                Vector2 screenPosition3 = Main.screenPosition;
                Player drawPlayer6 = drawinfo.drawPlayer;
                float y6 = drawinfo.Position.Y;
                int width4 = drawPlayer6.width;
                Vector2 screenPosition4 = Main.screenPosition;
                Player drawPlayer7 = drawinfo.drawPlayer;
                int num3 = 52992;
                int height4 = drawPlayer7.height;
                int height5 = drawPlayer7.bodyFrame.Height;
                Player drawPlayer8 = drawinfo.drawPlayer;
                float x5 = drawPlayer8.bodyPosition.X;
                float y7 = drawPlayer8.bodyPosition.Y;
                if (num3 == 0)
                {
                }
                Player drawPlayer9 = drawinfo.drawPlayer;
                int width5 = drawPlayer9.bodyFrame.Width;
                int height6 = drawPlayer9.bodyFrame.Height;
                Player drawPlayer10 = drawinfo.drawPlayer;
                Color colorLegs2 = drawinfo.colorLegs;
                float x6 = drawinfo.bodyVect.X;
                float y8 = drawinfo.bodyVect.Y;
                float legRotation = drawPlayer10.legRotation;
                int value2 = width5.m_value;
                SpriteEffects playerEffect2 = drawinfo.playerEffect;
            }
        }
References Terraria.Player.bodyFrame, Terraria.Player.bodyPosition, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite(), Terraria.Entity.height, Terraria.DataStructures.PlayerDrawLayers.IsBottomOverridden(), j__TPar, Terraria.Main.screenPosition, System.value, Microsoft.Xna.Framework.Rectangle.Width, and Terraria.Entity.width.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().