terraria-cpp2il-methodrecon: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite
DrawPlayer_12_Skin_Composite()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite (PlayerDrawSet drawinfo) inline static
Definition at line 1063 of file PlayerDrawLayers.cs.
        {
            bool invis2;
            for (;;)
            {
                if (!drawinfo.hidesTopSkin)
                {
                    bool invis = drawinfo.drawPlayer.invis;
                    if (!invis)
                    {
                        float x = drawinfo.Position.X;
                        if (!invis)
{
                        }
                        Vector2 screenPosition = Main.screenPosition;
                        Player drawPlayer = drawinfo.drawPlayer;
                        float y = drawinfo.Position.Y;
                        int width = drawPlayer.bodyFrame.Width;
                        int width2 = drawPlayer.width;
                        Vector2 screenPosition2 = Main.screenPosition;
                        Player drawPlayer2 = drawinfo.drawPlayer;
                        int num = 52992;
                        int height = drawPlayer2.height;
                        int height2 = drawPlayer2.bodyFrame.Height;
                        Player drawPlayer3 = drawinfo.drawPlayer;
                        float x2 = drawPlayer3.bodyPosition.X;
                        float y2 = drawPlayer3.bodyPosition.Y;
                        if (num == 0)
{
                        }
                        Player drawPlayer4 = drawinfo.drawPlayer;
                        int width3 = drawPlayer4.bodyFrame.Width;
                        int height3 = drawPlayer4.bodyFrame.Height;
                        Player drawPlayer5 = drawinfo.drawPlayer;
                        int y3 = drawPlayer5.bodyFrame.Y;
                        int height4 = drawPlayer5.bodyFrame.Height;
                        float torsoOffset = drawinfo.torsoOffset;
                        SpriteEffects playerEffect = drawinfo.playerEffect;
                        int num2 = true.ToDirectionInt();
                        Player drawPlayer6 = drawinfo.drawPlayer;
                        float x3 = drawinfo.bodyVect.X;
                        float y4 = drawinfo.bodyVect.Y;
                        float bodyRotation = drawPlayer6.bodyRotation;
                        if (drawPlayer6 == null)
{
                        }
                        Vector2 compositeOffset_BackArm = PlayerDrawLayers.GetCompositeOffset_BackArm(drawinfo);
                        SpriteEffects playerEffect2 = drawinfo.playerEffect;
                        bool drawFloatingTube = drawinfo.drawFloatingTube;
                        if (!drawFloatingTube)
{
                            continue;
                        }
                        if (!drawFloatingTube)
{
                        }
                        float x4 = drawinfo.bodyVect.X;
                        float y5 = drawinfo.bodyVect.Y;
                        SpriteEffects playerEffect3 = drawinfo.playerEffect;
                        if (drawinfo.cFloatingTube == 0)
{
                        }
                        Color colorBodySkin = drawinfo.colorBodySkin;
                        float x5 = drawinfo.bodyVect.X;
                        float y6 = drawinfo.bodyVect.Y;
                        SpriteEffects playerEffect4 = drawinfo.playerEffect;
                        int skinDyePacked = drawinfo.skinDyePacked;
                    }
                }
                if (!drawinfo.hidesBottomSkin)
                {
                    invis2 = drawinfo.drawPlayer.invis;
                    if (!invis2)
                    {
                        break;
                    }
                }
            }
            if (!invis2)
            {
            }
            bool flag = PlayerDrawLayers.IsBottomOverridden(drawinfo);
            bool isSitting = drawinfo.isSitting;
            if (!invis2)
            {
            }
            if (isSitting)
            {
                Color colorLegs = drawinfo.colorLegs;
                int skinDyePacked2 = drawinfo.skinDyePacked;
                if (!invis2)
                {
                }
                return;
            }
            float x6 = drawinfo.Position.X;
            if (!invis2)
            {
            }
            Vector2 screenPosition3 = Main.screenPosition;
            Player drawPlayer7 = drawinfo.drawPlayer;
            float y7 = drawinfo.Position.Y;
            int width4 = drawPlayer7.bodyFrame.Width;
            int width5 = drawPlayer7.width;
            Vector2 screenPosition4 = Main.screenPosition;
            Player drawPlayer8 = drawinfo.drawPlayer;
            int num3 = 52992;
            int height5 = drawPlayer8.height;
            int height6 = drawPlayer8.bodyFrame.Height;
            Player drawPlayer9 = drawinfo.drawPlayer;
            float x7 = drawPlayer9.bodyPosition.X;
            float y8 = drawPlayer9.bodyPosition.Y;
            if (num3 == 0)
            {
            }
            Player drawPlayer10 = drawinfo.drawPlayer;
            int width6 = drawPlayer10.bodyFrame.Width;
            int height7 = drawPlayer10.bodyFrame.Height;
            Player drawPlayer11 = drawinfo.drawPlayer;
            Color colorLegs2 = drawinfo.colorLegs;
            float x8 = drawinfo.bodyVect.X;
            float y9 = drawinfo.bodyVect.Y;
            float legRotation = drawPlayer11.legRotation;
            int value = width6.m_value;
            SpriteEffects playerEffect5 = drawinfo.playerEffect;
            if (drawinfo.skinDyePacked == 0)
            {
            }
            PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(drawinfo);
        }
References Terraria.Player.bodyFrame, Terraria.Player.bodyPosition, Terraria.Player.bodyRotation, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(), Terraria.DataStructures.PlayerDrawLayers.GetCompositeOffset_BackArm(), Terraria.Entity.height, Terraria.DataStructures.PlayerDrawLayers.IsBottomOverridden(), j__TPar, Terraria.Main.screenPosition, System.value, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin().