terraria-cpp2il-methodrecon: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt
DrawPlayer_12_SkinComposite_BackArmShirt()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt (PlayerDrawSet drawinfo) inline static
Definition at line 1195 of file PlayerDrawLayers.cs.
        {
            int num = 1;
            float x = drawinfo.Position.X;
            if (num == 0)
            {
            }
            Vector2 screenPosition = Main.screenPosition;
            Player drawPlayer = drawinfo.drawPlayer;
            float y = drawinfo.Position.Y;
            int width = drawPlayer.bodyFrame.Width;
            int width2 = drawPlayer.width;
            Vector2 screenPosition2 = Main.screenPosition;
            Player drawPlayer2 = drawinfo.drawPlayer;
            int height = drawPlayer2.height;
            int height2 = drawPlayer2.bodyFrame.Height;
            Player drawPlayer3 = drawinfo.drawPlayer;
            float x2 = drawPlayer3.bodyPosition.X;
            float y2 = drawPlayer3.bodyPosition.Y;
            Player drawPlayer4 = drawinfo.drawPlayer;
            int width3 = drawPlayer4.bodyFrame.Width;
            int height3 = drawPlayer4.bodyFrame.Height;
            Player drawPlayer5 = drawinfo.drawPlayer;
            int y3 = drawPlayer5.bodyFrame.Y;
            int height4 = drawPlayer5.bodyFrame.Height;
            SpriteEffects playerEffect = drawinfo.playerEffect;
            int num2 = true.ToDirectionInt();
            Player drawPlayer6 = drawinfo.drawPlayer;
            float torsoOffset = drawinfo.torsoOffset;
            float x3 = drawinfo.bodyVect.X;
            float bodyRotation = drawPlayer6.bodyRotation;
            float y4 = drawinfo.bodyVect.Y;
            if (drawPlayer6 == null)
            {
            }
            Vector2 compositeOffset_BackArm = PlayerDrawLayers.GetCompositeOffset_BackArm(drawinfo);
            float x4 = drawinfo.backShoulderOffset.X;
            Player drawPlayer7 = drawinfo.drawPlayer;
            float compositeBackArmRotation = drawinfo.compositeBackArmRotation;
            int body = drawPlayer7.body;
            bool invis = drawPlayer7.invis;
            if (drawPlayer7 != null)
            {
                return;
            }
            bool hidesTopSkin = drawinfo.hidesTopSkin;
            bool missingHand = drawinfo.missingHand;
            if (invis)
            {
                return;
            }
            bool missingArm = drawinfo.missingArm;
            int num3;
            if (missingArm && !hidesTopSkin)
            {
                if (!missingArm)
                {
                }
                Color colorBodySkin = drawinfo.colorBodySkin;
                SpriteEffects playerEffect2 = drawinfo.playerEffect;
                if (drawinfo.skinDyePacked == 0)
                {
                }
                Color colorBodySkin2 = drawinfo.colorBodySkin;
                SpriteEffects playerEffect3 = drawinfo.playerEffect;
                int skinDyePacked = drawinfo.skinDyePacked;
                num3 = 1;
            }
            Player drawPlayer8 = drawinfo.drawPlayer;
            bool invis2 = drawPlayer8.invis;
            if (invis2)
            {
                int body2 = drawPlayer8.body;
                if (!invis2)
                {
                }
            }
            if (drawPlayer8 == null)
            {
            }
            Player drawPlayer9 = drawinfo.drawPlayer;
            int teleportStyle = drawPlayer8.teleportStyle;
            int cBody;
            if (!drawinfo.hideCompositeShoulders)
            {
                Color colorArmorBody = drawinfo.colorArmorBody;
                float x5 = drawinfo.bodyVect.X;
                float y5 = drawinfo.bodyVect.Y;
                SpriteEffects playerEffect4 = drawinfo.playerEffect;
                cBody = drawinfo.cBody;
                if (cBody == 0)
                {
                }
            }
            if (cBody == 0)
            {
            }
            PlayerDrawLayers.DrawPlayer_12_1_BalloonFronts(drawinfo);
            Color colorArmorBody2 = drawinfo.colorArmorBody;
            SpriteEffects playerEffect5 = drawinfo.playerEffect;
            int cBody2 = drawinfo.cBody;
            if (num3 == 0)
            {
                return;
            }
            if (cBody2 == 0)
            {
            }
            Color colorBodySkin3 = drawinfo.colorBodySkin;
            SpriteEffects playerEffect6 = drawinfo.playerEffect;
            if (drawinfo.skinDyePacked == 0)
            {
            }
            Color colorBodySkin4 = drawinfo.colorBodySkin;
            SpriteEffects playerEffect7 = drawinfo.playerEffect;
            int skinDyePacked2 = drawinfo.skinDyePacked;
            if (skinDyePacked2 == 0)
            {
            }
            Color colorUnderShirt = drawinfo.colorUnderShirt;
            SpriteEffects playerEffect8 = drawinfo.playerEffect;
            if (skinDyePacked2 == 0)
            {
            }
            PlayerDrawLayers.DrawPlayer_12_1_BalloonFronts(drawinfo);
            Color colorShirt = drawinfo.colorShirt;
            SpriteEffects playerEffect9 = drawinfo.playerEffect;
            if (drawinfo.drawPlayer == null)
            {
            }
            Player drawPlayer10 = drawinfo.drawPlayer;
            Color colorArmorBody3 = drawinfo.colorArmorBody;
            SpriteEffects playerEffect10 = drawinfo.playerEffect;
            if (drawinfo.cHandOff == 0)
            {
            }
            bool drawingFootball = drawinfo.drawPlayer.drawingFootball;
            if (drawingFootball)
            {
                if (!drawingFootball)
                {
                }
                if (!drawingFootball)
                {
                }
                if (drawPlayer10 == null)
                {
                }
                Rectangle rectangle;
                Vector2 vector = rectangle.Size();
                if (!drawingFootball)
                {
                }
                Player drawPlayer11 = drawinfo.drawPlayer;
                int direction = drawPlayer11.direction;
                float gravDir = drawPlayer11.gravDir;
                Player drawPlayer12 = drawinfo.drawPlayer;
                Color colorArmorBody4 = drawinfo.colorArmorBody;
                SpriteEffects playerEffect11 = drawinfo.playerEffect;
                int direction2 = drawPlayer12.direction;
            }
        }
References Terraria.Player.body, Terraria.Player.bodyFrame, Terraria.Player.bodyPosition, Terraria.Player.bodyRotation, Terraria.Entity.direction, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_1_BalloonFronts(), Terraria.DataStructures.PlayerDrawLayers.GetCompositeOffset_BackArm(), Terraria.Entity.height, Terraria.Player.invis, j__TPar, Terraria.Main.screenPosition, Terraria.Player.teleportStyle, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite().