terraria-cpp2il-methodrecon: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes
DrawPlayer_14_Shoes()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes (PlayerDrawSet drawinfo) inline static
Definition at line 1497 of file PlayerDrawLayers.cs.
        {
            if (drawinfo.drawPlayer == null)
            {
            }
            bool flag = PlayerDrawLayers.ShouldOverrideLegs_CheckPants(drawinfo);
            sbyte shoe = drawinfo.drawPlayer.shoe;
            bool isSitting = drawinfo.isSitting;
            sbyte shoe2 = drawinfo.drawPlayer.shoe;
            if (isSitting)
            {
                Color colorArmorLegs = drawinfo.colorArmorLegs;
                if (shoe2 == 0)
                {
                }
                return;
            }
            float x = drawinfo.Position.X;
            Vector2 screenPosition = Main.screenPosition;
            Player drawPlayer = drawinfo.drawPlayer;
            float y = drawinfo.Position.Y;
            int width = drawPlayer.legFrame.Width;
            int width2 = drawPlayer.width;
            Vector2 screenPosition2 = Main.screenPosition;
            int num = 52992;
            int height = drawinfo.drawPlayer.height;
            Player drawPlayer2 = drawinfo.drawPlayer;
            float x2 = drawPlayer2.legPosition.X;
            float y2 = drawPlayer2.legPosition.Y;
            if (num == 0)
            {
            }
            float x3 = drawinfo.legVect.X;
            float y3 = drawinfo.legVect.Y;
            Player drawPlayer3 = drawinfo.drawPlayer;
            Color colorArmorLegs2 = drawinfo.colorArmorLegs;
            float x4 = drawinfo.legVect.X;
            float y4 = drawinfo.legVect.Y;
            float legRotation = drawPlayer3.legRotation;
            int value = num.m_value;
            SpriteEffects playerEffect = drawinfo.playerEffect;
            if (drawinfo.drawPlayer.shoe == 0)
            {
            }
            PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(drawinfo);
        }
References Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), j__TPar, Terraria.Player.legFrame, Terraria.Player.legPosition, Terraria.Main.screenPosition, Terraria.DataStructures.PlayerDrawLayers.ShouldOverrideLegs_CheckPants(), System.value, Microsoft.Xna.Framework.Rectangle.Width, and Terraria.Entity.width.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().