terraria-cpp2il-methodrecon: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer
DrawPlayer_02_MountBehindPlayer()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer (PlayerDrawSet drawinfo) inline static
Definition at line 175 of file PlayerDrawLayers.cs.
        {
            if (drawinfo.drawPlayer.mount._active)
            {
                PlayerDrawLayers.DrawMeowcartTrail(drawinfo);
                PlayerDrawLayers.DrawTiedBalloons(drawinfo);
                Player drawPlayer = drawinfo.drawPlayer;
                float shadow = drawinfo.shadow;
                float x = drawinfo.Position.X;
                float y = drawinfo.Position.Y;
                Color colorMount = drawinfo.colorMount;
                Mount mount = drawPlayer.mount;
                SpriteEffects playerEffect = drawinfo.playerEffect;
                Player drawPlayer2 = drawinfo.drawPlayer;
                float shadow2 = drawinfo.shadow;
                float x2 = drawinfo.Position.X;
                float y2 = drawinfo.Position.Y;
                Color colorMount2 = drawinfo.colorMount;
                Mount mount2 = drawPlayer2.mount;
                SpriteEffects playerEffect2 = drawinfo.playerEffect;
                return;
            }
        }
References Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail(), Terraria.DataStructures.PlayerDrawLayers.DrawTiedBalloons(), j__TPar, and Terraria.Player.mount.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_MountTransformation(), and Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().