terraria-cpp2il-methodrecon: UserManagement.LocalUserQuit
LocalUserQuit()
static void UserManagement.LocalUserQuit (LocalUser user) inline static
Definition at line 77 of file UserManagement.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        int userIndex = user.UserIndex;
        if (num == 0)
        {
        }
        Player.Hooks.PlayerDisconnect(userIndex);
        if (num == 0)
        {
        }
        ThreadManager.TerminateUserThreads(user);
        user.GameState._achievements.Shutdown();
        user.fileManager.Shutdown();
        GameObject gameObject = user.UICameraSettings.Camera.gameObject;
        long num2 = 0L;
        gameObject.SetActive(num2 != 0L);
        GameObject gameObject2 = user.WorldCameraSettings.Camera.gameObject;
        long num3 = 0L;
        gameObject2.SetActive(num3 != 0L);
        GUIInstance guiinstance = user.GUIInstance;
        guiinstance.GUIMap.CleanupMapTargets();
        if (guiinstance == null)
        {
        }
        InterfaceProfile_Layout active = guiinstance._active;
    }
References LocalUserGameState._achievements, XNAUICameraSettings.Camera, XNAWorldCameraSettings.Camera, GUIMap.CleanupMapTargets(), LocalUser.fileManager, UnityEngine.Component.gameObject, LocalUser.GameState, LocalUser.GUIInstance, GUIInstance.GUIMap, j__TPar, System.L, Terraria.Player.Hooks.PlayerDisconnect(), UnityEngine.GameObject.SetActive(), FileManager.Shutdown(), Terraria.Achievements.AchievementManager.Shutdown(), ThreadManager.TerminateUserThreads(), LocalUser.UICameraSettings, LocalUser.UserIndex, and LocalUser.WorldCameraSettings.