terraria-cpp2il-methodrecon: UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.ExtractIndirect
ExtractIndirect()
static LinearColor UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.ExtractIndirect (Light l) inline static
Definition at line 16 of file LightmapperUtils.cs.
        {
            Color color;
            float num;
            return LinearColor.Convert(color, num);
        }
References UnityEngine.Experimental.GlobalIllumination.LinearColor.Convert().
Referenced by UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract(), UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract(), UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract(), UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract(), and UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract().