terraria-cpp2il-methodrecon: UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract
Extract() [5/7]
static void UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.Extract (Light l, RectangleLight rect) inline static
Definition at line 94 of file LightmapperUtils.cs.
        {
            int instanceID = l.GetInstanceID();
            rect.instanceID = instanceID;
            LightBakingOutput bakingOutput = l.bakingOutput;
            LightShadows shadows = l.shadows;
            Vector3 position = l.transform.position;
            Quaternion rotation = l.transform.rotation;
            Color color = LightmapperUtils.ExtractColorTemperature(l);
            Color color2 = l.color;
            float intensity = l.intensity;
            LinearColor linearColor = LightmapperUtils.ExtractIndirect(l);
            float range = l.range;
            rect.falloff = FalloffType.Legacy;
        }
References UnityEngine.Light.bakingOutput, UnityEngine.Light.color, UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.ExtractColorTemperature(), UnityEngine.Experimental.GlobalIllumination.LightmapperUtils.ExtractIndirect(), UnityEngine.Object.GetInstanceID(), UnityEngine.Light.intensity, j__TPar, UnityEngine.Transform.position, UnityEngine.Light.range, UnityEngine.Transform.rotation, UnityEngine.Light.shadows, and UnityEngine.Component.transform.