terraria-cpp2il-methodrecon: InControl.TouchManager.TouchCameraIsValid
TouchCameraIsValid()
bool InControl.TouchManager.TouchCameraIsValid () inline private
Definition at line 232 of file TouchManager.cs.
        {
            Camera camera = this.touchCamera;
            if (!true)
            {
            }
            float orthographicSize = this.touchCamera.orthographicSize;
            if (!true)
            {
            }
            bool flag = Utility.IsZero(orthographicSize);
            float width = this.touchCamera.rect.width;
            if (!true)
            {
            }
            bool flag2 = Utility.IsZero(width);
            float height = this.touchCamera.rect.height;
            if (!true)
            {
            }
            bool flag3 = Utility.IsZero(height);
            float width2 = this.touchCamera.pixelRect.width;
            if (!true)
            {
            }
            bool flag4 = Utility.IsZero(width2);
            float height2 = this.touchCamera.pixelRect.height;
            if (!true)
            {
            }
            bool flag5 = Utility.IsZero(height2);
            return true;
        }
References UnityEngine.Rect.height, InControl.Utility.IsZero(), j__TPar, UnityEngine.Camera.orthographicSize, UnityEngine.Camera.pixelRect, UnityEngine.Camera.rect, InControl.TouchManager.touchCamera, and UnityEngine.Rect.width.
Referenced by InControl.TouchManager.ConvertScreenToViewPoint(), InControl.TouchManager.ConvertScreenToWorldPoint(), and InControl.TouchManager.ConvertViewToWorldPoint().