terraria-cpp2il-methodrecon: Terraria.GameInput.TriggersPack.Reset
Reset()
void Terraria.GameInput.TriggersPack.Reset () inline
Definition at line 18 of file TriggersPack.cs.
        {
            TriggersSet current = this.Current;
            TriggersSet old = this.Old;
            current.Clone(old);
            bool[] keyStatus = this.Current.KeyStatus;
        }
References Terraria.GameInput.TriggersSet.Clone(), Terraria.GameInput.TriggersPack.Current, j__TPar, Terraria.GameInput.TriggersSet.KeyStatus, and Terraria.GameInput.TriggersPack.Old.
Referenced by Terraria.GameInput.PlayerInput.ResetInputsOnActiveStateChange(), and Terraria.GameInput.PlayerInput.UpdateInput().