terraria-cpp2il-methodrecon: GUIResearch.ActionResearch
ActionResearch()
void GUIResearch.ActionResearch () inline private
Definition at line 230 of file GUIResearch.cs.
    {
        int num = 1;
        Item researchItem = this.GetResearchItem();
        bool isAir = researchItem.IsAir;
        if (num == 0)
        {
        }
        int type = researchItem.type;
        if (num == 0)
        {
        }
        ItemsSacrificedUnlocksTracker itemSacrifices = Main.LocalPlayerCreativeTracker.ItemSacrifices;
        int type2 = researchItem.type;
        int sacrificeCount = itemSacrifices.GetSacrificeCount(type2);
        int stack = researchItem.stack;
        int type3 = researchItem.type;
        if (stack == 0)
        {
        }
        if (stack != 0)
        {
            NetPacket netPacket = NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(researchItem.type, 1073741824);
            if (stack == 0)
            {
            }
            return;
        }
        if (stack == 0)
        {
        }
        ItemsSacrificedUnlocksTracker itemSacrifices2 = Main.LocalPlayerCreativeTracker.ItemSacrifices;
        int type4 = researchItem.type;
        itemSacrifices2.RegisterItemSacrifice(type4, 1073741824);
        int stack2 = researchItem.stack;
        researchItem.stack = stack2;
        long num2 = 0L;
        researchItem.TurnToAir(num2 != 0L);
        if (stack2 == 0)
        {
        }
        Recipe.FindRecipes(false);
    }
References Terraria.Recipe.FindRecipes(), GetResearchItem(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.GetSacrificeCount(), Terraria.Item.IsAir, Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, j__TPar, System.L, Terraria.Main.LocalPlayerCreativeTracker, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.RegisterItemSacrifice(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), and System.stack.
Referenced by DrawMainButtons().