terraria-cpp2il-methodrecon: GUIResearch.DrawItemProgress
DrawItemProgress()
void GUIResearch.DrawItemProgress () inline private
Definition at line 386 of file GUIResearch.cs.
    {
        Research_Layout instance = Research_Layout.Instance;
        Item researchItem = this.GetResearchItem();
        int stack = researchItem.stack;
        String_Layout itemName = instance.ItemName;
        string name = researchItem.Name;
        GUIString.Draw(itemName, name);
        String_Layout description = instance.Description;
        string textValue = Language.GetTextValue("Mobile.ResearchDescription");
        GUIString.Draw(description, textValue);
        Panel_Layout barBacking = instance.BarBacking;
        Rectangle rectangle = GUIPanel.Region(instance.BarBacking);
        bool isAir = researchItem.IsAir;
        int type = researchItem.type;
        int researchItemStart;
        if (this.ResearchAnimationInProgress)
        {
            int researchFrame = this.ResearchFrame;
            researchItemStart = this.ResearchItemStart;
            int researchFrame2 = this.ResearchFrame;
            return;
        }
        ItemsSacrificedUnlocksTracker itemSacrifices = Main.LocalPlayerCreativeTracker.ItemSacrifices;
        int type2 = researchItem.type;
        int sacrificeCount = itemSacrifices.GetSacrificeCount(type2);
        if (researchItemStart == 0)
        {
        }
        int stack2 = researchItem.stack;
    }
References Research_Layout.BarBacking, Research_Layout.Description, GUIString.Draw(), GetResearchItem(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.GetSacrificeCount(), Terraria.Localization.Language.GetTextValue(), Research_Layout.Instance, Research_Layout.ItemName, Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, j__TPar, Terraria.Main.LocalPlayerCreativeTracker, System.name, GUIPanel.Region(), ResearchAnimationInProgress, ResearchFrame, ResearchItemStart, System.stack, and Terraria.Item.stack.
Referenced by Draw().