terraria-cpp2il-methodrecon: GUIResearch.DrawResearchBacking
DrawResearchBacking()
void GUIResearch.DrawResearchBacking () inline private
Definition at line 287 of file GUIResearch.cs.
    {
        Research_Layout instance = Research_Layout.Instance;
        Panel_Layout imageBacking = instance.ImageBacking;
        Rectangle rectangle = GUIPanel.Region(instance.ResearchItemBacking);
        int num = this.UpdateResearchAnimation();
        this.DrawResearchItem();
        if (!true)
        {
        }
        Vector2 vector = rectangle.TopLeft();
        Vector2 vector2 = rectangle.Size();
        Color backingColor = instance.ResearchItemBacking.BackingColor;
    }
References Panel_Layout.BackingColor, DrawResearchItem(), Research_Layout.ImageBacking, Research_Layout.Instance, j__TPar, GUIPanel.Region(), Research_Layout.ResearchItemBacking, and UpdateResearchAnimation().
Referenced by Draw().