terraria-cpp2il-methodrecon: GUIResearch.DrawInventoryResearchButton
DrawInventoryResearchButton()
void GUIResearch.DrawInventoryResearchButton () inline
Definition at line 72 of file GUIResearch.cs.
    {
        int gameMode = Main.GameMode;
        bool useCollpasedCoinsAmmo = RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo;
        Research_Layout instance = Research_Layout.Instance;
        string textValue = Language.GetTextValue("Mobile.Research");
        string textValue2 = Language.GetTextValue("Mobile.Research");
        bool drawToolModeUI = WiresUI.Settings.DrawToolModeUI;
        TransactionButton_Layout inventoryResearchController = instance.InventoryResearchController;
        float x = instance.InventoryResearchControllerWiringOffset.X;
        float y = instance.InventoryResearchControllerWiringOffset.Y;
        float x2 = inventoryResearchController.Location.X;
        float y2 = inventoryResearchController.Location.Y;
        TransactionButton_Layout inventoryResearch = instance.InventoryResearch;
        int num = 18;
        int myPlayer = Main.myPlayer;
        this.Open(num);
        bool drawToolModeUI2 = WiresUI.Settings.DrawToolModeUI;
        TransactionButton_Layout inventoryResearchController2 = instance.InventoryResearchController;
        float x3 = instance.InventoryResearchControllerWiringOffset.X;
        float y3 = instance.InventoryResearchControllerWiringOffset.Y;
        float x4 = inventoryResearchController2.Location.X;
        float y4 = inventoryResearchController2.Location.Y;
    }
References Terraria.GameContent.UI.WiresUI.Settings.DrawToolModeUI, Terraria.Main.GameMode, Terraria.Localization.Language.GetTextValue(), Research_Layout.Instance, Research_Layout.InventoryResearch, Research_Layout.InventoryResearchController, Research_Layout.InventoryResearchControllerWiringOffset, j__TPar, Terraria.Main.myPlayer, Open(), RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by DrawInventoryResearchBinding().