terraria-cpp2il-methodrecon: GUIResearch.Draw
Draw()
void GUIResearch.Draw () inline
Definition at line 149 of file GUIResearch.cs.
    {
        if (!true)
        {
        }
        GUIPageIconGrouping categoryGrouping = InterfaceStyles_Layout.Active.GetCategoryGrouping(GUIPageIcons.Category.Research, true);
        GUIInputRegionExclusive pickingInterceptor = this.PickingInterceptor;
        if (pickingInterceptor != null)
        {
        }
        if (pickingInterceptor == null)
        {
        }
        if (!true)
        {
        }
        Main.FlushBatches();
        this.DrawResearchBacking();
        this.DrawResearchCogs();
        this.DrawItemProgress();
        this.DrawResearchParticles();
        Panel_Layout divider = Research_Layout.Instance.Divider;
        Panel_Layout divider2 = Research_Layout.Instance.Divider2;
        this.DrawMainButtons();
        GUIInputRegionExclusive pickingInterceptor2 = this.PickingInterceptor;
        if (pickingInterceptor2 != null)
        {
            pickingInterceptor2.Active = true;
        }
    }
References InterfaceStyles_Layout.Active, Research_Layout.Divider, Research_Layout.Divider2, DrawItemProgress(), DrawMainButtons(), DrawResearchBacking(), DrawResearchCogs(), DrawResearchParticles(), Terraria.Main.FlushBatches(), InterfaceProfile_Layout.GetCategoryGrouping(), Research_Layout.Instance, j__TPar, and PickingInterceptor.