terraria-cpp2il-methodrecon: GUIResearch.DrawMainButtons
DrawMainButtons()
void GUIResearch.DrawMainButtons () inline private
Definition at line 191 of file GUIResearch.cs.
    {
        int num = 1;
        int openedFrame = this.OpenedFrame;
        if (num == 0)
        {
        }
        Research_Layout instance = Research_Layout.Instance;
        TransactionButton_Layout close = instance.Close;
        GUITransactionButton.InputState inputState2;
        if (!this.ResearchAnimationInProgress)
        {
            TransactionButton_Layout actionResearch = instance.ActionResearch;
            string textValue = Language.GetTextValue("Mobile.Research");
            GUITransactionButton.InputState inputState;
            if (inputState == GUITransactionButton.InputState.Clicked)
            {
                this.ActionResearch();
                while (inputState2 != GUITransactionButton.InputState.Clicked)
                {
                }
                goto IL_004B;
            }
        }
        if (inputState2 != GUITransactionButton.InputState.Clicked)
        {
            return;
        }
        IL_004B:
        this.Close();
    }
References ActionResearch(), Research_Layout.ActionResearch, Close(), Research_Layout.Close, Terraria.Localization.Language.GetTextValue(), Research_Layout.Instance, j__TPar, OpenedFrame, and ResearchAnimationInProgress.
Referenced by Draw().