terraria-cpp2il-methodrecon: GUIResearch.IsOver
IsOver()
bool GUIResearch.IsOver (Vector2 cursorPosition) inline
Definition at line 98 of file GUIResearch.cs.
    {
        if (!true)
        {
        }
        if (InterfaceStyles_Layout.Active.GetCategoryGrouping(GUIPageIcons.Category.Research, true) != null)
        {
        }
        if (this.Displaying)
        {
            Research_Layout instance = Research_Layout.Instance;
            Rectangle rectangle = GUIPanel.Region(Research_Layout.Instance.Backing);
            Rectangle controlRegion = ControlAnchor.GetControlRegion(ControlAnchor.ControlId.GridItem);
            ControlAnchor.SetGridItemRegion(rectangle);
            TransactionButton_Layout close = instance.Close;
            Rectangle region = GUITransactionButton.GetRegion(close);
            ControlAnchor.SetGridItemRegion(controlRegion);
        }
        return true;
    }
References InterfaceStyles_Layout.Active, Research_Layout.Backing, Research_Layout.Close, Displaying, InterfaceProfile_Layout.GetCategoryGrouping(), ControlAnchor.GetControlRegion(), GUITransactionButton.GetRegion(), Research_Layout.Instance, j__TPar, GUIPanel.Region(), and ControlAnchor.SetGridItemRegion().