terraria-cpp2il-methodrecon: WorldFile_OldSwitch.CheckWeaponsRack
CheckWeaponsRack()
static void WorldFile_OldSwitch.CheckWeaponsRack (int i, int j) inline static private
Definition at line 114 of file WorldFile_OldSwitch.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        Tile tile;
        short frameY = tile.frameY;
        if (num == 0)
        {
        }
        Tile tile2;
        short frameY2 = tile2.frameY;
        if (num == 0)
        {
        }
        Tile tile3;
        short frameY3 = tile3.frameY;
        if (num == 0)
        {
        }
        Tile tile4;
        short frameX = tile4.frameX;
        int num2 = 36409;
        if (num2 == 0)
        {
        }
        Tile tile5;
        short frameX2 = tile5.frameX;
        if (num2 == 0)
        {
        }
        Tile tile6;
        short frameX3 = tile6.frameX;
        long num3 = 0L;
        Tile tile7;
        tile7.SetFrameX((short)num3);
        int num4 = 18;
        Tile tile8;
        tile8.SetFrameY((short)num4);
    }
References Terraria.Tile.frameX, Terraria.Tile.frameY, j__TPar, System.L, Terraria.Tile.SetFrameX(), and Terraria.Tile.SetFrameY().
Referenced by CleanItemsStoredInTiles().