terraria-cpp2il-methodrecon: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup
WriteMemberSetup()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup (WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, string memberName, Type memberType, object memberData, WriteObjectInfo memberObjectInfo) inline private
Definition at line 112 of file ObjectWriter.cs.
        {
            NameInfo nameInfo = this.GetNameInfo();
            nameInfo.NIFullName = memberName;
            if (memberObjectInfo != null)
            {
                long assemId = memberObjectInfo.assemId;
                nameInfo.NItype = memberType;
                nameInfo.NIassemId = assemId;
                Type objectType = memberObjectInfo.objectType;
                InternalPrimitiveTypeE internalPrimitiveTypeE = this.ToCode(objectType);
                return;
            }
            nameInfo.NItype = memberType;
            InternalPrimitiveTypeE internalPrimitiveTypeE2 = this.ToCode(memberType);
            NameInfo nameInfo2 = this.GetNameInfo();
            nameInfo2.NIprimitiveTypeEnum = internalPrimitiveTypeE2;
            nameInfo2.NItype = memberType;
            bool nitransmitTypeOnObject = memberNameInfo.NItransmitTypeOnObject;
            nameInfo.NItransmitTypeOnObject = nitransmitTypeOnObject;
            bool niisParentTypeOnObject = memberNameInfo.NIisParentTypeOnObject;
            nameInfo.NIisParentTypeOnObject = niisParentTypeOnObject;
            this.niPool.Push(nameInfo);
            this.niPool.Push(nameInfo2);
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNameInfo(), j__TPar, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.niPool, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.ToCode().