terraria-cpp2il-methodrecon: UnityEngine.EventSystems.StandaloneInputModule.Process
Process()
override void UnityEngine.EventSystems.StandaloneInputModule.Process () inline
Definition at line 325 of file StandaloneInputModule.cs.
        {
            if (this.m_EventSystem.m_HasFocus)
            {
                bool flag = this.SendUpdateEventToSelectedObject();
                bool flag2 = this.ProcessTouchEvents();
                BaseInput input = base.input;
                long num = 0L;
                this.ProcessMouseEvent((int)num);
                bool sendNavigationEvents = this.m_EventSystem.m_sendNavigationEvents;
                bool flag3 = this.SendMoveEventToSelectedObject();
            }
        }
References UnityEngine.EventSystems.BaseInputModule.input, j__TPar, UnityEngine.L, UnityEngine.EventSystems.BaseInputModule.m_EventSystem, UnityEngine.EventSystems.EventSystem.m_HasFocus, UnityEngine.EventSystems.EventSystem.m_sendNavigationEvents, UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent(), UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents(), UnityEngine.EventSystems.StandaloneInputModule.SendMoveEventToSelectedObject(), and UnityEngine.EventSystems.StandaloneInputModule.SendUpdateEventToSelectedObject().