terraria-cpp2il-methodrecon: GUIShop.PurchasePressedAndHeld
PurchasePressedAndHeld()
void GUIShop.PurchasePressedAndHeld (bool delayedPurchase = false) inline private
Definition at line 52 of file GUIShop.cs.
    {
        if (!true)
        {
        }
        int stackSplit = Main.stackSplit;
        Item item;
        int type = item.type;
        if (type == 0)
        {
        }
        Item item2;
        bool flag = Main.mouseItem.IsTheSameAs(item2);
        if (type == 0)
        {
        }
        if (Main.mouseItem.type == 0)
        {
            int num = 20;
            if (num == 0)
            {
            }
            int num2 = 1;
            Main.preventStackSplitReset = num2 != 0;
            int superFastStack = Main.superFastStack;
            if (num == 0)
            {
            }
            int stack = Main.mouseItem.stack;
            if (Main.mouseItem.maxStack == 0)
            {
            }
            if (Main.mouseItem.type == 0)
            {
                return;
            }
        }
    }
References Terraria.Item.IsTheSameAs(), System.item, j__TPar, Terraria.Item.maxStack, Terraria.Main.mouseItem, System.stack, Terraria.Item.stack, Terraria.Main.stackSplit, Terraria.Main.superFastStack, and Terraria.Item.type.
Referenced by DrawSlots(), and ItemOver().