terraria-cpp2il-methodrecon: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Create
Create() [1/2]
static AsyncTaskMethodBuilder< TResult > System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.Create () inline static
Definition at line 12 of file AsyncTaskMethodBuilder.2.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by System.Net.WebConnection.Connect(), System.Net.MonoChunkStream.FinishReading(), System.IO.Stream.FinishWriteAsync(), System.Net.WebRequestStream.FinishWriting(), System.Net.WebRequestStream.Initialize(), System.Net.WebConnectionTunnel.Initialize(), System.Net.WebResponseStream.InitReadAsync(), Mono.Net.Security.AsyncProtocolRequest.InnerRead(), Mono.Net.Security.MobileAuthenticatedStream.InnerWrite(), Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication(), Mono.Net.Security.AsyncProtocolRequest.ProcessOperation(), System.Net.WebRequestStream.ProcessWrite(), System.Net.WebResponseStream.ReadAllAsync(), System.Net.ServicePointScheduler.RunScheduler(), System.Net.WebRequestStream.SetHeadersAsync(), Microsoft.Xna.Framework.Input.MessageBox.Show(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), System.Net.WebRequestStream.WriteAsyncInner(), System.Security.Cryptography.CryptoStream.WriteAsyncInternal(), System.Net.WebRequestStream.WriteChunkTrailer(), System.Net.WebRequestStream.WriteChunkTrailer_inner(), and System.Net.WebRequestStream.WriteRequestAsync().