terraria-cpp2il-methodrecon: UnityEngine.UI.ScrollRect.GetBounds
GetBounds()
Bounds UnityEngine.UI.ScrollRect.GetBounds () inline private
Definition at line 1165 of file ScrollRect.cs.
        {
            RectTransform content = this.m_Content;
            if (!true)
            {
            }
            RectTransform content2 = this.m_Content;
            Vector3[] corners = this.m_Corners;
            content2.GetWorldCorners(corners);
            Matrix4x4 worldToLocalMatrix = this.viewRect.worldToLocalMatrix;
            Vector3[] corners2 = this.m_Corners;
            Bounds bounds;
            return bounds;
        }
References UnityEngine.UI.ScrollRect.content, UnityEngine.RectTransform.GetWorldCorners(), j__TPar, UnityEngine.UI.ScrollRect.m_Content, UnityEngine.UI.ScrollRect.m_Corners, UnityEngine.UI.ScrollRect.viewRect, and UnityEngine.Transform.worldToLocalMatrix.
Referenced by UnityEngine.UI.ScrollRect.SetLayoutHorizontal(), UnityEngine.UI.ScrollRect.SetLayoutVertical(), and UnityEngine.UI.ScrollRect.UpdateBounds().