terraria-cpp2il-methodrecon: UnityEngine.UI.ScrollRect.UpdateBounds
UpdateBounds()
void UnityEngine.UI.ScrollRect.UpdateBounds () inline protected
Definition at line 1134 of file ScrollRect.cs.
        {
            int num = 1;
            Vector2 center = this.viewRect.rect.center;
            Vector2 size = this.viewRect.rect.size;
            this.m_ViewBounds.m_Extents.y = (float)num;
            Bounds bounds = this.GetBounds();
            this.m_ContentBounds.m_Extents.y = (float)num;
            RectTransform content = this.m_Content;
            if (num == 0)
            {
            }
            Vector2 pivot = this.m_Content.pivot;
            ScrollRect.MovementType movementType = this.m_MovementType;
        }
References UnityEngine.Rect.center, UnityEngine.UI.ScrollRect.content, UnityEngine.UI.ScrollRect.GetBounds(), j__TPar, UnityEngine.UI.ScrollRect.m_Content, UnityEngine.UI.ScrollRect.m_MovementType, UnityEngine.UI.ScrollRect.movementType, UnityEngine.RectTransform.pivot, UnityEngine.RectTransform.rect, UnityEngine.Rect.size, and UnityEngine.UI.ScrollRect.viewRect.
Referenced by UnityEngine.UI.ScrollRect.LateUpdate(), UnityEngine.UI.ScrollRect.OnBeginDrag(), UnityEngine.UI.ScrollRect.OnDrag(), UnityEngine.UI.ScrollRect.OnScroll(), UnityEngine.UI.ScrollRect.SetContentAnchoredPosition(), and UnityEngine.UI.ScrollRect.SetNormalizedPosition().