terraria-cpp2il-methodrecon: UnityEngine.UI.ScrollRect.OnScroll
OnScroll()
virtual void UnityEngine.UI.ScrollRect.OnScroll (PointerEventData data) inline virtual
Implements UnityEngine.EventSystems.IScrollHandler.
Definition at line 555 of file ScrollRect.cs.
        {
            this.EnsureLayoutHasRebuilt();
            this.UpdateBounds();
            float y = data.<scrollDelta>k__BackingField.y;
            float x = data.<scrollDelta>k__BackingField.x;
            bool vertical = this.m_Vertical;
            bool horizontal = this.m_Horizontal;
            if (vertical)
            {
                if (horizontal)
                {
                    return;
                }
                return;
            }
            else
            {
                if (!vertical && horizontal)
                {
                    return;
                }
                bool flag = data.IsScrolling();
                int num = 1;
                this.m_Scrolling = num != 0;
                Vector2 anchoredPosition = this.m_Content.anchoredPosition;
                float scrollSensitivity = this.m_ScrollSensitivity;
                ScrollRect.MovementType movementType = this.m_MovementType;
                Vector2 anchoredPosition2 = this.m_Content.anchoredPosition;
                bool horizontal2 = this.m_Horizontal;
                bool vertical2 = this.m_Vertical;
                ScrollRect.MovementType movementType2 = this.m_MovementType;
                this.UpdateBounds();
                return;
            }
        }
References UnityEngine.RectTransform.anchoredPosition, UnityEngine.UI.ScrollRect.EnsureLayoutHasRebuilt(), UnityEngine.UI.ScrollRect.horizontal, UnityEngine.EventSystems.PointerEventData.IsScrolling(), j__TPar, UnityEngine.UI.ScrollRect.m_Content, UnityEngine.UI.ScrollRect.m_Horizontal, UnityEngine.UI.ScrollRect.m_MovementType, UnityEngine.UI.ScrollRect.m_ScrollSensitivity, UnityEngine.UI.ScrollRect.m_Vertical, UnityEngine.UI.ScrollRect.movementType, UnityEngine.UI.ScrollRect.scrollSensitivity, UnityEngine.UI.ScrollRect.UpdateBounds(), and UnityEngine.UI.ScrollRect.vertical.