terraria-cpp2il-methodrecon: UnityEngine.UI.ScrollRect.SetLayoutHorizontal
SetLayoutHorizontal()
virtual void UnityEngine.UI.ScrollRect.SetLayoutHorizontal () inline virtual
Implements UnityEngine.UI.ILayoutController.
Definition at line 992 of file ScrollRect.cs.
        {
            this.UpdateCachedData();
            if (this.m_HSliderExpand || this.m_VSliderExpand)
            {
                RectTransform viewRect = this.viewRect;
                RectTransform viewRect2 = this.viewRect;
                RectTransform viewRect3 = this.viewRect;
                RectTransform viewRect4 = this.viewRect;
                RectTransform viewRect5 = this.viewRect;
                LayoutRebuilder.ForceRebuildLayoutImmediate(this.m_Content);
                Vector2 center = this.viewRect.rect.center;
                Vector2 size = this.viewRect.rect.size;
                Bounds bounds = this.GetBounds();
                bool vsliderExpand = this.m_VSliderExpand;
                if (vsliderExpand)
                {
                    bool vScrollingNeeded = this.vScrollingNeeded;
                    RectTransform viewRect6 = this.viewRect;
                    float vsliderWidth = this.m_VSliderWidth;
                    float verticalScrollbarSpacing = this.m_VerticalScrollbarSpacing;
                    Vector2 sizeDelta = this.viewRect.sizeDelta;
                    RectTransform content = this.m_Content;
                    if (!vsliderExpand)
                    {
                    }
                    LayoutRebuilder.ForceRebuildLayoutImmediate(content);
                    Vector2 center2 = this.viewRect.rect.center;
                    Vector2 size2 = this.viewRect.rect.size;
                    this.m_ViewBounds.m_Extents.y = vsliderExpand;
                    Bounds bounds2 = this.GetBounds();
                    this.m_ContentBounds.m_Extents.y = vsliderExpand;
                    return;
                }
            }
            bool hsliderExpand = this.m_HSliderExpand;
            if (hsliderExpand)
            {
                bool hScrollingNeeded = this.hScrollingNeeded;
                RectTransform viewRect7 = this.viewRect;
                Vector2 sizeDelta2 = this.viewRect.sizeDelta;
                float hsliderHeight = this.m_HSliderHeight;
                float horizontalScrollbarSpacing = this.m_HorizontalScrollbarSpacing;
                Vector2 center3 = this.viewRect.rect.center;
                Vector2 size3 = this.viewRect.rect.size;
                this.m_ViewBounds.m_Extents.y = hsliderExpand;
                Bounds bounds3 = this.GetBounds();
                this.m_ContentBounds.m_Extents.y = hsliderExpand;
            }
            bool vScrollingNeeded2 = this.vScrollingNeeded;
            Vector2 sizeDelta3 = this.viewRect.sizeDelta;
            Vector2 sizeDelta4 = this.viewRect.sizeDelta;
            RectTransform viewRect8 = this.viewRect;
            float vsliderWidth2 = this.m_VSliderWidth;
            float verticalScrollbarSpacing2 = this.m_VerticalScrollbarSpacing;
            Vector2 sizeDelta5 = this.viewRect.sizeDelta;
        }
References UnityEngine.Rect.center, UnityEngine.UI.ScrollRect.content, UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(), UnityEngine.UI.ScrollRect.GetBounds(), UnityEngine.UI.ScrollRect.horizontalScrollbarSpacing, UnityEngine.UI.ScrollRect.hScrollingNeeded, j__TPar, UnityEngine.UI.ScrollRect.m_Content, UnityEngine.UI.ScrollRect.m_HorizontalScrollbarSpacing, UnityEngine.UI.ScrollRect.m_HSliderExpand, UnityEngine.UI.ScrollRect.m_HSliderHeight, UnityEngine.UI.ScrollRect.m_VerticalScrollbarSpacing, UnityEngine.UI.ScrollRect.m_VSliderExpand, UnityEngine.UI.ScrollRect.m_VSliderWidth, UnityEngine.RectTransform.rect, UnityEngine.Rect.size, UnityEngine.RectTransform.sizeDelta, UnityEngine.UI.ScrollRect.UpdateCachedData(), UnityEngine.UI.ScrollRect.verticalScrollbarSpacing, UnityEngine.UI.ScrollRect.viewRect, and UnityEngine.UI.ScrollRect.vScrollingNeeded.