terraria-cpp2il-methodrecon: UnityEngine.UI.ScrollRect.LateUpdate
LateUpdate()
virtual void UnityEngine.UI.ScrollRect.LateUpdate () inline protected virtual
Definition at line 661 of file ScrollRect.cs.
        {
            int num = 1;
            RectTransform content = this.m_Content;
            if (num == 0)
            {
            }
            bool flag = content;
            this.EnsureLayoutHasRebuilt();
            this.UpdateBounds();
            float unscaledDeltaTime = Time.unscaledDeltaTime;
            bool horizontal = this.m_Horizontal;
            bool vertical = this.m_Vertical;
            ScrollRect.MovementType movementType = this.m_MovementType;
            if (this.m_Dragging)
            {
                if (this.m_Inertia)
                {
                    Vector2 anchoredPosition = this.m_Content.anchoredPosition;
                    float x = this.m_Velocity.x;
                    float num2;
                    this.m_Velocity.x = num2;
                }
                IntPtr cachedPtr = content.m_CachedPtr;
                Vector2 anchoredPosition2 = this.m_Content.anchoredPosition;
                float x2 = this.m_PrevPosition.x;
                float y = this.m_PrevPosition.y;
                UISystemProfilerApi.AddMarker("ScrollRect.value", this);
                ScrollRect.ScrollRectEvent onValueChanged = this.m_OnValueChanged;
                float horizontalNormalizedPosition = this.horizontalNormalizedPosition;
                float verticalNormalizedPosition = this.verticalNormalizedPosition;
                this.UpdatePrevData();
                this.UpdateScrollbarVisibility();
                return;
            }
            float x3 = this.m_Velocity.x;
            float y2 = this.m_Velocity.y;
            Vector2 anchoredPosition3 = this.m_Content.anchoredPosition;
            ScrollRect.MovementType movementType2 = this.m_MovementType;
            if (!this.m_Inertia)
            {
                return;
            }
            float decelerationRate = this.m_DecelerationRate;
            float x4 = this.m_Velocity.x;
            this.m_Velocity.x = decelerationRate;
        }
References UnityEngine.UISystemProfilerApi.AddMarker(), UnityEngine.RectTransform.anchoredPosition, UnityEngine.UI.ScrollRect.content, UnityEngine.UI.ScrollRect.decelerationRate, UnityEngine.UI.ScrollRect.EnsureLayoutHasRebuilt(), UnityEngine.UI.ScrollRect.horizontal, UnityEngine.UI.ScrollRect.horizontalNormalizedPosition, j__TPar, UnityEngine.Object.m_CachedPtr, UnityEngine.UI.ScrollRect.m_Content, UnityEngine.UI.ScrollRect.m_DecelerationRate, UnityEngine.UI.ScrollRect.m_Dragging, UnityEngine.UI.ScrollRect.m_Horizontal, UnityEngine.UI.ScrollRect.m_Inertia, UnityEngine.UI.ScrollRect.m_MovementType, UnityEngine.UI.ScrollRect.m_OnValueChanged, UnityEngine.UI.ScrollRect.m_PrevPosition, UnityEngine.UI.ScrollRect.m_Velocity, UnityEngine.UI.ScrollRect.m_Vertical, UnityEngine.UI.ScrollRect.movementType, UnityEngine.UI.ScrollRect.onValueChanged, UnityEngine.Time.unscaledDeltaTime, UnityEngine.UI.ScrollRect.UpdateBounds(), UnityEngine.UI.ScrollRect.UpdatePrevData(), UnityEngine.UI.ScrollRect.UpdateScrollbarVisibility(), UnityEngine.UI.ScrollRect.vertical, UnityEngine.UI.ScrollRect.verticalNormalizedPosition, UnityEngine.Vector2.x, and UnityEngine.Vector2.y.