terraria-cpp2il-methodrecon: GUIPlayerAndGameModeMismatch.Draw
Draw()
void GUIPlayerAndGameModeMismatch.Draw () inline
Definition at line 15 of file GUIPlayerAndGameModeMismatch.cs.
    {
        GUIControllerPlayerAndGameModeMistmatch inputController = this._inputController;
        this._inputController.Activate();
        string textValue = Language.GetTextValue("UI.Back");
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            this.Back();
        }
        this.Back();
        string text = this.messageText;
    }
References _inputController, GUIControllerPlayerAndGameModeMistmatch.Activate(), Back(), Terraria.Localization.Language.GetTextValue(), j__TPar, messageText, and System.text.