terraria-cpp2il-methodrecon: Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench
Step_MulticolorWrench()
static void Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench (SmartCursorHelper::SmartCursorUsageInfo providedInfo, int focusedX, int focusedY) inline static private
Definition at line 559 of file SmartCursorHelper.cs.
        {
            int type = providedInfo.item.type;
            WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
            int screenTargetX = providedInfo.screenTargetX;
            int reachableStartX = providedInfo.reachableStartX;
            Tile tile;
            bool flag = tile.wire();
            int screenTargetX2 = providedInfo.screenTargetX;
            int reachableStartX2 = providedInfo.reachableStartX;
            Tile tile2;
            bool flag2 = tile2.wire2();
            int screenTargetX3 = providedInfo.screenTargetX;
            int reachableStartX3 = providedInfo.reachableStartX;
            Tile tile3;
            bool flag3 = tile3.wire3();
            int screenTargetX4 = providedInfo.screenTargetX;
            int reachableStartX4 = providedInfo.reachableStartX;
            Tile tile4;
            bool flag4 = tile4.wire4();
            WiresUI.Settings.MultiToolMode toolMode2 = WiresUI.Settings.ToolMode;
            int reachableStartX5 = providedInfo.reachableStartX;
            int reachableStartY = providedInfo.reachableStartY;
            int reachableEndY = providedInfo.reachableEndY;
            int reachableStartY2 = providedInfo.reachableStartY;
        }
References j__TPar, Terraria.GameContent.SmartCursorHelper.providedInfo, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().