terraria-cpp2il-methodrecon: Mono.Security.Protocol.Ntlm.ChallengeResponse2.Compute_NTLMv2_Session
Compute_NTLMv2_Session()
static void Mono.Security.Protocol.Ntlm.ChallengeResponse2.Compute_NTLMv2_Session (string password, byte[] challenge, [Out] byte[] lm, [Out] byte[] ntlm) inline static private
Definition at line 43 of file ChallengeResponse2.cs.
        {
            RandomNumberGenerator randomNumberGenerator = RandomNumberGenerator.Create();
            MD5 md = MD5.Create();
            int num = 8;
            byte[] array;
            ntlm.m_value = array;
            long num2 = 0L;
            byte[] array2;
            Array.Clear(array2, (int)num2, num);
        }
References System.array, System.Array.Clear(), System.Security.Cryptography.MD5.Create(), System.Security.Cryptography.RandomNumberGenerator.Create(), j__TPar, and System.L.