terraria-cpp2il-methodrecon: GUIReforgePopup.SetupBackingSize
SetupBackingSize()
void GUIReforgePopup.SetupBackingSize () inline private
Definition at line 11 of file GUIReforgePopup.cs.
    {
        float y = this.CachedTextSize.Y;
        bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
        int num = 32768;
        int num2 = 28;
        if (num == 0)
        {
        }
        if (num2 == 0)
        {
        }
        int num3 = 32768;
        Item item;
        int stack = item.stack;
        int type = item.type;
        string hoverName = item.HoverName;
        if (num3 == 0)
        {
        }
    }
References Controller.ControllerActionManager.AnyControllerConnected, CachedTextSize, System.item, j__TPar, System.stack, Terraria.Item.stack, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Draw(), GetRegion(), LoadPanelRegion(), and LoadRegion().