terraria-cpp2il-methodrecon: UnityEngine.Shader.PropertyToID
PropertyToID()
static int UnityEngine.Shader.PropertyToID (string name) inline static
Definition at line 50 of file Shader.cs.
        {
            throw new MissingMethodException();
        }
Referenced by Microsoft.Xna.Framework.Graphics.MaterialBuffer.MaterialBuffer(), Microsoft.Xna.Framework.Graphics.PixelShader.PixelShader(), ScreenPostProcessor.ScreenPostProcessor(), Microsoft.Xna.Framework.Graphics.ScreenShader.ScreenShader(), and Microsoft.Xna.Framework.Graphics.TileShader.TileShader().