terraria-cpp2il-methodrecon: RightSideHUDAnchorUpdator.Update
Update()
static void RightSideHUDAnchorUpdator.Update () inline static
Definition at line 98 of file RightSideHUDAnchorUpdator.cs.
    {
        List<GUIPageIconGrouping> rightGroupings = InterfaceStyles_Layout.Active.RightGroupings;
        List<GUIPageIconGrouping> leftGroupings = InterfaceStyles_Layout.Active.LeftGroupings;
        int size = rightGroupings._size;
        int size2 = rightGroupings._size;
        int size3 = leftGroupings._size;
        int size4 = leftGroupings._size;
        Rectangle rectangle;
        int right = rectangle.Right;
    }
References System.Collections.Generic.List< T >._size, InterfaceStyles_Layout.Active, j__TPar, InterfaceProfile_Layout.LeftGroupings, Microsoft.Xna.Framework.Rectangle.Right, and InterfaceProfile_Layout.RightGroupings.
Referenced by GUIPageIcons.DrawRightPageHUD(), GUIHearts.GetHeartsRegion(), GUIMana.GetManaRegion(), GUIVirtualInputController.IsOverGroupRegion(), and GUIPageIconGrouping.LoadPageAnchor().