terraria-cpp2il-methodrecon: System.Platform.CheckOS
CheckOS()
static void System.Platform.CheckOS () inline static private
Definition at line 13 of file Platform.cs.
        {
            PlatformID platform = Environment.OSVersion._platform;
            if (platform == PlatformID.Win32S)
            {
            }
            IntPtr intPtr = Marshal.AllocHGlobal(8192);
            if (global::System.Platform.uname(intPtr) == 0)
            {
                if (platform == PlatformID.Win32S)
                {
                }
                string text = Marshal.PtrToStringAnsi(intPtr);
                bool flag = text == "Darwin";
                return;
            }
            Marshal.FreeHGlobal(intPtr);
        }
References System.OperatingSystem._platform, System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), j__TPar, System.Environment.OSVersion, System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), System.text, and System.Platform.uname().