terraria-cpp2il-methodrecon: System.Xml.XmlUtf8RawTextWriterIndent.WriteIndent
WriteIndent()
void System.Xml.XmlUtf8RawTextWriterIndent.WriteIndent () inline private
Definition at line 227 of file XmlUtf8RawTextWriterIndent.cs.
        {
            string newLineChars = this.newLineChars;
            base.RawText(newLineChars);
            int num = this.indentLevel;
            string text = this.indentChars;
            base.RawText(text);
        }
References System.Xml.XmlUtf8RawTextWriterIndent.indentChars, System.Xml.XmlUtf8RawTextWriterIndent.indentLevel, j__TPar, System.Xml.XmlUtf8RawTextWriter.newLineChars, and System.text.
Referenced by System.Xml.XmlUtf8RawTextWriterIndent.WriteComment(), System.Xml.XmlUtf8RawTextWriterIndent.WriteDocType(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEndElement(), System.Xml.XmlUtf8RawTextWriterIndent.WriteFullEndElement(), System.Xml.XmlUtf8RawTextWriterIndent.WriteProcessingInstruction(), and System.Xml.XmlUtf8RawTextWriterIndent.WriteStartAttribute().