terraria-cpp2il-methodrecon: SaveSynchronisationManager.Startup
Startup()
void SaveSynchronisationManager.Startup () inline
Definition at line 77 of file SaveSynchronisationManager.cs.
    {
        this.LocalState.RefreshFromFileSystem();
        this.RemoteState.Clear();
        SaveSynchronisationHost saveSynchronisationHost = this.server;
        bool flag = saveSynchronisationHost.Server.Start(5555);
        SaveSynchronisationBroadcast.StartBroadCasting();
        if (saveSynchronisationHost == null)
        {
        }
        SaveSynchronisationFinder.StartSearching();
    }
References SaveSynchronisationState.Clear(), j__TPar, LocalState, SaveSynchronisationState.RefreshFromFileSystem(), RemoteState, SaveSynchronisationHost.Server, server, Telepathy.Server.Start(), SaveSynchronisationBroadcast.StartBroadCasting(), and SaveSynchronisationFinder.StartSearching().
Referenced by Restart().