terraria-cpp2il-methodrecon: TutorialStep_03_CraftWorkbench.GetGuideString
GetGuideString()
override string TutorialStep_03_CraftWorkbench.GetGuideString () inline virtual
Reimplemented from TutorialStep.
Definition at line 17 of file TutorialStep_03_CraftWorkbench.cs.
    {
        do
        {
            LocalizedText text = Language.GetText("Tutorial.NeedMoreWood");
            if (this.craftedWorkbench)
            {
            }
        }
        while (!this.got10Wood);
        string <Value>k__BackingField = Language.GetText("Tutorial.HaveWood").<Value>k__BackingField;
        XNAUnityRunner.ForcedInputMode primaryInputMode = XNAUnityRunner.PrimaryInputMode;
        if (this.craftedWorkbench)
        {
            string controlTag = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.Aim);
            string text2 = <Value>k__BackingField.Replace("[cm:1]", controlTag);
            string controlTag2 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.Fire);
            string text3 = text2.Replace("[cm:2]", controlTag2);
            string controlTag3 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.InventoryToggle);
            string text4 = text3.Replace("[cm:5]", controlTag3);
            ControllerActionButton.Entry entry;
            ControllerActionButton.Entry entry2;
            if (entry.InputKey == KeyCode.None && entry2.InputKey == KeyCode.None)
            {
                return 9;
            }
            string controlTag4 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.CycleLeftPage);
            string text5 = text4.Replace("[cm:7]", controlTag4);
            string controlTag5 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.CycleRightPage);
            string text6 = text5.Replace("[cm:8]", controlTag5);
            ControllerActionButton.Entry entry3;
            ControllerActionButton.Entry entry4;
            if (entry3.InputKey != KeyCode.None || entry4.InputKey != KeyCode.None)
            {
                string controlTag6 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.CyclePreviousHotbarItem);
                string text7 = text6.Replace("[cm:9]", controlTag6);
                string controlTag7 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.CycleNextHotbarItem);
                string text8 = text7.Replace("[cm:10]", controlTag7);
                string controlTag8 = GUIKeyboardMappings.GetControlTag(ControlsKeyboardTagHandler.MappingType.CraftItem);
                return text8.Replace("[cm:12]", controlTag8);
            }
            return 22;
        }
        else
        {
            string text8;
            if (text8._stringLength != 0)
            {
                return "[cm:12]";
            }
            return Language.GetTextValue("TutorialTouch.NeedMoreWood");
        }
    }
References craftedWorkbench, GUIKeyboardMappings.GetControlTag(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), got10Wood, Controller.ControllerActionButton.Entry.InputKey, j__TPar, XNAUnityRunner.PrimaryInputMode, and System.text.