terraria-cpp2il-methodrecon: SaveSynchronisationManager.Shutdown
Shutdown()
void SaveSynchronisationManager.Shutdown () inline
Definition at line 91 of file SaveSynchronisationManager.cs.
    {
        if (!true)
        {
        }
        SaveSynchronisationFinder.StopSearching();
        SaveSynchronisationBroadcast.StopBroadCasting();
        this.server.Server.Stop();
        this.client.Client.Disconnect();
    }
References SaveSynchronisationClient.Client, client, Telepathy.Client.Disconnect(), SaveSynchronisationHost.Server, server, Telepathy.Server.Stop(), SaveSynchronisationBroadcast.StopBroadCasting(), and SaveSynchronisationFinder.StopSearching().
Referenced by Restart().