terraria-cpp2il-methodrecon: Terraria.WorldGen.PlaceAlch
PlaceAlch()
static bool Terraria.WorldGen.PlaceAlch (int x, int y, int style) inline static
Definition at line 8594 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Tile tile;
            bool flag = tile.active();
            if (num == 0)
            {
            }
            Tile tile2;
            bool flag2 = tile2.nactive();
            if (num == 0)
            {
            }
            Tile tile3;
            bool flag3 = tile3.halfBrick();
            if (num == 0)
            {
            }
            Tile tile4;
            byte b = tile4.slope();
            if (y == 0)
            {
            }
            Tile tile5;
            ushort type = tile5.type;
            if (y == 0)
            {
            }
            Tile tile6;
            ushort type2 = tile6.type;
            if (y == 0)
            {
            }
            Tile tile7;
            ushort type3 = tile7.type;
            if (y == 0)
            {
            }
            Tile tile8;
            ushort type4 = tile8.type;
            if (y == 0)
            {
            }
            Tile tile9;
            ushort type5 = tile9.type;
            if (y == 0)
            {
            }
            Tile tile10;
            ushort type6 = tile10.type;
            if (y == 0)
            {
            }
            Tile tile11;
            ushort type7 = tile11.type;
            if (y == 0)
            {
            }
            Tile tile12;
            ushort type8 = tile12.type;
            if (y == 0)
            {
            }
            Tile tile13;
            ushort type9 = tile13.type;
            if (y == 0)
            {
            }
            Tile tile14;
            ushort type10 = tile14.type;
            if (y == 0)
            {
            }
            Tile tile15;
            ushort type11 = tile15.type;
            if (y == 0)
            {
            }
            Tile tile16;
            ushort type12 = tile16.type;
            if (y == 0)
            {
            }
            Tile tile17;
            ushort type13 = tile17.type;
            if (y == 0)
            {
            }
            Tile tile18;
            ushort type14 = tile18.type;
            if (y == 0)
            {
            }
            Tile tile19;
            ushort type15 = tile19.type;
            if (y == 0)
            {
            }
            Tile tile20;
            ushort type16 = tile20.type;
            if (y == 0)
            {
            }
            Tile tile21;
            ushort type17 = tile21.type;
            if (y == 0)
            {
            }
            Tile tile22;
            byte liquid = tile22.liquid;
            if (y == 0)
            {
            }
            int num2 = 1;
            Tile tile23;
            tile23.active(num2 != 0);
            int num3 = 82;
            tile23.type = (ushort)num3;
            tile23.frameX = (short)num3;
            long num4 = 0L;
            tile23.frameY = (short)num4;
            if (y == 0)
            {
            }
            Tile tile24;
            ushort type18 = tile24.type;
            if (y == 0)
            {
            }
            Tile tile25;
            ushort type19 = tile25.type;
            if (y == 0)
            {
            }
            Tile tile26;
            ushort type20 = tile26.type;
            if (y == 0)
            {
            }
            Tile tile27;
            ushort type21 = tile27.type;
            if (y == 0)
            {
            }
            Tile tile28;
            ushort type22 = tile28.type;
            if (y == 0)
            {
            }
            Tile tile29;
            ushort type23 = tile29.type;
            if (y == 0)
            {
            }
            Tile tile30;
            ushort type24 = tile30.type;
            long num5 = 0L;
            if (y == 0)
            {
            }
            Tile tile31;
            byte liquid2 = tile31.liquid;
            if (y == 0)
            {
            }
            Tile tile32;
            bool flag4 = tile32.lava();
            while (num5 != 0L)
            {
            }
            return flag4;
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), j__TPar, System.L, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Tile.slope(), and Terraria.Tile.type.