terraria-cpp2il-methodrecon: Terraria.WorldGen.GrowTreeWithSettings
GrowTreeWithSettings()
static bool Terraria.WorldGen.GrowTreeWithSettings (int checkedX, int checkedY, WorldGen::GrowTreeSettings settings) inline static
Definition at line 5257 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Tile tile;
            ushort type = tile.type;
            if (num == 0)
            {
            }
            Tile tile2;
            byte liquid = tile2.liquid;
            if (num == 0)
            {
            }
            Tile tile3;
            byte liquid2 = tile3.liquid;
            if (num == 0)
            {
            }
            Tile tile4;
            byte liquid3 = tile4.liquid;
            if (num == 0)
            {
            }
            Tile tile5;
            bool flag = tile5.nactive();
            if (num == 0)
            {
            }
            Tile tile6;
            ushort wall = tile6.wall;
            if (num == 0)
            {
            }
            Tile tile7;
            bool flag2 = tile7.active();
            if (num == 0)
            {
            }
            Tile tile8;
            ushort type2 = tile8.type;
            if (num == 0)
            {
            }
            Tile tile9;
            bool flag3 = tile9.active();
            if (num == 0)
            {
            }
            Tile tile10;
            ushort type3 = tile10.type;
            if (num == 0)
            {
            }
            long num2 = 0L;
            Tile tile11;
            TileColorCache tileColorCache = tile11.BlockColorAndCoating();
            int num4;
            if (num != 0)
            {
                UnifiedRandom genRand = WorldGen.genRand;
                long num3 = 0L;
                num4 = genRand.Next((int)num2, checkedX);
                int num5 = 20;
                bool flag4 = WorldGen.EmptyTileCheck(num4, (int)num2, checkedX, (int)num3, num5);
                if (num4 == 0)
                {
                }
                UnifiedRandom genRand2 = WorldGen.genRand;
                int num6 = 3;
                int num7 = genRand2.Next(num6);
                UnifiedRandom genRand3 = WorldGen.genRand;
                int num8 = 3;
                int num9 = genRand3.Next(num8);
                UnifiedRandom genRand4 = WorldGen.genRand;
                int num10 = 10;
                int num11 = genRand4.Next(num10);
                UnifiedRandom genRand5 = WorldGen.genRand;
                int num12 = 10;
                int num13 = genRand5.Next(num12);
                int num14 = 1;
                Tile tile12;
                tile12.active(num14 != 0);
                UnifiedRandom genRand6 = WorldGen.genRand;
                int num15 = 3;
                int num16 = genRand6.Next(num15);
                UnifiedRandom genRand7 = WorldGen.genRand;
                int num17 = 3;
                int num18 = genRand7.Next(num17);
                if (num16 == 0 || num16 != 0)
                {
                }
                int num19 = 1;
                Tile tile13;
                tile13.active(num19 != 0);
                UnifiedRandom genRand8 = WorldGen.genRand;
                int num20 = 3;
                int num21 = genRand8.Next(num20);
                UnifiedRandom genRand9 = WorldGen.genRand;
                int num22 = 3;
                int num23 = genRand9.Next(num22);
                if (num21 == 0 || num21 != 0)
                {
                }
                Tile tile14;
                bool flag5 = tile14.nactive();
                Tile tile15;
                bool flag6 = tile15.halfBrick();
                Tile tile16;
                byte b = tile16.slope();
                Tile tile17;
                ushort type4 = tile17.type;
                if (num4 == 0)
                {
                }
                return WorldGen.IsTileTypeFitForTree(type4);
            }
            UnifiedRandom genRand10 = WorldGen.genRand;
            int num24 = 1;
            int num25 = 13;
            int num26 = genRand10.Next(num24, num25);
            if (num26 != 0)
            {
                int num27 = 1;
                Tile tile18;
                tile18.active(num27 != 0);
                UnifiedRandom genRand11 = WorldGen.genRand;
                int num28 = 3;
                if (genRand11.Next(num28) == 0)
                {
                }
            }
            UnifiedRandom genRand12 = WorldGen.genRand;
            int num29 = 3;
            int num30 = genRand12.Next(num29);
            if (num30 == 0)
            {
                int num31 = 88;
                Tile tile19;
                tile19.frameX = (short)num31;
                if (num26 != 0)
                {
                    if (num30 != 0)
                    {
                        goto IL_03ED;
                    }
                    long num32 = 0L;
                    Tile tile20;
                    tile20.frameX = (short)num32;
                }
                long num33;
                if (num33 != 0L && num30 == 0)
                {
                    int num34 = 66;
                    Tile tile21;
                    tile21.frameX = (short)num34;
                    int num35 = 88;
                    tile21.frameX = (short)num35;
                    int num36 = 88;
                    tile21.frameX = (short)num36;
                    Tile tile22;
                    ushort type5 = tile22.type;
                    if (num4 == 0)
                    {
                    }
                    return WorldGen.IsTileTypeFitForTree(type5);
                }
            }
            IL_03ED:
            UnifiedRandom genRand13 = WorldGen.genRand;
            int num37 = 13;
            int num38 = genRand13.Next(num37);
            if (num4 == 0)
            {
            }
            long num39 = 0L;
            if (num38 != 0)
            {
                if (num4 == 0)
                {
                }
                UnifiedRandom genRand14 = WorldGen.genRand;
                int num40 = 3;
                if (genRand14.Next(num40) != 0)
                {
                    goto IL_0462;
                }
            }
            if (num4 == 0)
            {
            }
            UnifiedRandom genRand15 = WorldGen.genRand;
            int num41 = 3;
            int num42;
            long num43;
            if (genRand15.Next(num41) == 0)
            {
                num42 = 220;
                num43 = 0L;
            }
            IL_0462:
            WorldGen.RangeFrame(0, num42, (int)num43, (int)num39);
            if (!false)
            {
            }
            bool netHost = Main.NetHost;
            if (!false)
            {
                goto IL_047E;
            }
            goto IL_047E;
            IL_047E:;
        }
References Terraria.Tile.active(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.IsTileTypeFitForTree(), j__TPar, System.L, Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.NetHost, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RangeFrame(), Terraria.Tile.slope(), Terraria.Tile.type, and Terraria.Tile.wall.