terraria-cpp2il-methodrecon: Terraria.WorldGen.RangeFrame
RangeFrame()
static void Terraria.WorldGen.RangeFrame (int startX, int startY, int endX, int endY) inline static
Definition at line 17035 of file WorldGen.cs.
        {
            if (!true)
            {
            }
            long num = 0L;
            long num2 = 0L;
            WorldGen.TileFrame(startX, endY, num != 0L, num2 != 0L);
            long num3 = 0L;
            Framing.WallFrame(startX, endY, num3 != 0L);
        }
References j__TPar, System.L, Terraria.WorldGen.TileFrame(), and Terraria.Framing.WallFrame().
Referenced by Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.NetMessage.SendTileSquare(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing().