terraria-cpp2il-methodrecon: Terraria.WorldGen.GrowUndergroundTree
GrowUndergroundTree()
static void Terraria.WorldGen.GrowUndergroundTree (int i, int y) inline static
Definition at line 5474 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Tile tile;
            ushort type = tile.type;
            if (num == 0)
            {
            }
            Tile tile2;
            bool flag = tile2.nactive();
            if (num == 0)
            {
            }
            Tile tile3;
            bool flag2 = tile3.halfBrick();
            if (num == 0)
            {
            }
            Tile tile4;
            byte b = tile4.slope();
            if (num == 0)
            {
            }
            Tile tile5;
            ushort type2 = tile5.type;
            if (num == 0)
            {
            }
            Tile tile6;
            bool flag3 = tile6.active();
            if (num == 0)
            {
            }
            Tile tile7;
            ushort type3 = tile7.type;
            if (num == 0)
            {
            }
            Tile tile8;
            bool flag4 = tile8.active();
            if (num == 0)
            {
            }
            Tile tile9;
            ushort type4 = tile9.type;
            if (num == 0)
            {
            }
            UnifiedRandom genRand = WorldGen.genRand;
            int num2 = 5;
            int num3 = 15;
            int num4 = genRand.Next(num2, num3);
            long num5 = 0L;
            long num6 = 0L;
            Tile tile10;
            ushort type5 = tile10.type;
            int num7 = 20;
            bool flag5 = WorldGen.EmptyTileCheck(43143168, (int)num6, y, (int)num5, num7);
            UnifiedRandom genRand2 = WorldGen.genRand;
            int num8 = 3;
            int num9 = genRand2.Next(num8);
            UnifiedRandom genRand3 = WorldGen.genRand;
            int num10 = 3;
            int num11 = genRand3.Next(num10);
            UnifiedRandom genRand4 = WorldGen.genRand;
            int num12 = 10;
            int num13 = genRand4.Next(num12);
            UnifiedRandom genRand5 = WorldGen.genRand;
            int num14 = 10;
            int num15 = genRand5.Next(num14);
        }
References Terraria.Tile.active(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), j__TPar, System.L, Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Tile.slope(), and Terraria.Tile.type.