terraria-cpp2il-methodrecon: Terraria.WorldGen.paintCoatEffect
paintCoatEffect()
static void Terraria.WorldGen.paintCoatEffect (int x, int y, byte paintCoatId, List< Color > oldColors) inline static
Definition at line 8159 of file WorldGen.cs.
        {
            if (!true)
            {
            }
            Color color = WorldGen.coatingColor(0);
            if (oldColors._size == 0)
            {
            }
            int size = oldColors._size;
            UnifiedRandom genRand = WorldGen.genRand;
            int num = 2;
            if (genRand.Next(num) == 0)
            {
            }
        }
References Terraria.WorldGen.coatingColor(), Terraria.WorldGen.genRand, j__TPar, and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.WorldGen.paintCoatTile().