terraria-cpp2il-methodrecon: Terraria.WorldGen.RandomizeMoonState
RandomizeMoonState()
static void Terraria.WorldGen.RandomizeMoonState (UnifiedRandom random, bool garenteeNewStyle = false) inline static
Definition at line 1501 of file WorldGen.cs.
        {
            if (!true)
            {
            }
            int num = random.Next(9);
        }
References Terraria.Utilities.UnifiedRandom.Next().
Referenced by WorldFile_OldConsole.LoadWorld_Version1(), WorldFile_OldSwitch.LoadWorld_Version1(), and Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88().