terraria-cpp2il-methodrecon: Terraria.WorldGen.SolidTile2
SolidTile2() [1/2]
static bool Terraria.WorldGen.SolidTile2 (int i, int j) inline static
Definition at line 14913 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Tile tile;
            bool isLoaded = tile.IsLoaded;
            if (num == 0)
            {
            }
            Tile tile2;
            bool flag = tile2.active();
            if (num == 0)
            {
            }
            Tile tile3;
            ushort type = tile3.type;
            if (num != 0)
            {
                if (num == 0)
                {
                }
                Tile tile4;
                ushort type2 = tile4.type;
                Tile tile5;
                bool flag2 = tile5.halfBrick();
                Tile tile6;
                bool flag3 = tile6.topSlope();
                Tile tile7;
                byte b = tile7.slope();
                Tile tile8;
                bool flag4 = tile8.halfBrick();
                Tile tile9;
                bool flag5 = tile9.inActive();
                return;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.IsLoaded, j__TPar, Terraria.Tile.slope(), Terraria.Tile.topSlope(), and Terraria.Tile.type.