terraria-cpp2il-methodrecon: Terraria.WorldGen.MakeDungeon_GroundFurniture
MakeDungeon_GroundFurniture()
static double Terraria.WorldGen.MakeDungeon_GroundFurniture (int wallType) inline static private
Definition at line 6494 of file WorldGen.cs.
        {
            int num14;
            int num23;
            int num25;
            long num27;
            for (;;)
            {
                if (!true)
                {
                }
                long num = 32752L;
                long num2 = -2147483647L;
                if (num == 0L)
                {
                }
                UnifiedRandom genRand = WorldGen.genRand;
                if (num2 == 0L)
                {
                }
                UnifiedRandom genRand2 = WorldGen.genRand;
                if (num2 == 0L)
                {
                }
                Tile tile;
                ushort wall = tile.wall;
                long num3 = 0L;
                Tile tile2;
                bool flag = tile2.active();
                int num5;
                int num4 = WorldGen.genRand.Next((int)num3, num5);
                UnifiedRandom genRand3 = WorldGen.genRand;
                Tile tile3;
                ushort wall2 = tile3.wall;
                long num6 = 0L;
                Tile tile4;
                bool flag2 = tile4.active();
                long num7 = 0L;
                bool flag3 = WorldGen.SolidTile(num4, (int)num6, num7 != 0L);
                int underworldLayer = Main.UnderworldLayer;
                long num8 = 0L;
                Tile tile5;
                bool flag4 = tile5.active();
                long num9 = 0L;
                bool flag5 = WorldGen.SolidTile(num4, (int)num8, num9 != 0L);
                long num10 = 0L;
                Tile tile6;
                bool flag6 = tile6.active();
                long num11 = 0L;
                bool flag7 = WorldGen.SolidTile(num4, (int)num10, num11 != 0L);
                Tile tile7;
                bool flag8 = tile7.active();
                long num12 = 0L;
                Tile tile8;
                ushort wall3 = tile8.wall;
                long num13 = 0L;
                bool flag9 = WorldGen.SolidTile(num4, (int)num12, num13 != 0L);
                Tile tile9;
                ushort type = tile9.type;
                num14 = 5;
                int num15 = 30;
                if (num15 == 0)
                {
                }
                Tile tile10;
                ushort wall4 = tile10.wall;
                if (num15 == 0)
                {
                }
                Tile tile11;
                ushort wall5 = tile11.wall;
                int num16 = 15;
                if (num16 == 0)
                {
                }
                UnifiedRandom genRand4 = WorldGen.genRand;
                int num17 = 13;
                int num18 = genRand4.Next(num17);
                if (num16 == 0)
                {
                }
                UnifiedRandom genRand5 = WorldGen.genRand;
                int num19 = 4;
                int num20 = genRand5.Next(num19);
                if (num20 != 0)
                {
                    if (num16 == 0)
                    {
                    }
                    UnifiedRandom genRand6 = WorldGen.genRand;
                    int num21 = 13;
                    int num22 = genRand6.Next(num21);
                }
                num23 = 2;
                int num24 = 1;
                if (num24 == 0)
                {
                }
                Tile tile12;
                bool flag10 = tile12.active();
                num25 = 10;
                if (num24 == 0)
                {
                }
                if (num24 == 0)
                {
                }
                Tile tile13;
                bool flag11 = tile13.active();
                if (num24 == 0)
                {
                }
                Tile tile14;
                bool flag12 = tile14.active();
                if (num24 == 0)
                {
                }
                if (num24 == 0)
                {
                }
                Tile tile15;
                bool flag13 = tile15.active();
                if (num24 == 0)
                {
                }
                Tile tile16;
                short frameX = tile16.frameX;
                Tile tile17;
                short frameX2 = tile17.frameX;
                Tile tile18;
                bool flag14 = tile18.active();
                UnifiedRandom genRand7 = WorldGen.genRand;
                int num26 = 2;
                if (genRand7.Next(num26) == 0)
                {
                    break;
                }
                Tile tile19;
                ushort type2 = tile19.type;
                num27 = 0L;
                Tile tile20;
                ushort type3 = tile20.type;
                Tile tile21;
                bool flag15 = tile21.active();
                UnifiedRandom genRand8 = WorldGen.genRand;
                int num28 = 2;
                int num29 = genRand8.Next(num28);
                if (num24 == 0)
                {
                }
                if (num29 != 0)
                {
                    goto Block_2;
                }
                Tile tile22;
                bool flag16 = tile22.active();
                if (42190112.0 == null)
                {
                }
                if (42190112.0 == null)
                {
                }
                Tile tile23;
                bool flag17 = tile23.active();
                if (42190112.0 == null)
                {
                }
                Tile tile24;
                short frameX3 = tile24.frameX;
                Tile tile25;
                short frameX4 = tile25.frameX;
                UnifiedRandom genRand9 = WorldGen.genRand;
                int num30 = 2;
                if (genRand9.Next(num30) == 0)
                {
                    goto Block_3;
                }
            }
            Tile tile26;
            bool flag18 = tile26.active();
            UnifiedRandom genRand10 = WorldGen.genRand;
            int num31 = 5;
            int num32 = genRand10.Next(num31);
            Tile tile27;
            ushort type4 = tile27.type;
            Tile tile28;
            ushort type5 = tile28.type;
            int num33 = 49;
            int num34 = 1;
            long num35 = 0L;
            long num36 = 0L;
            bool flag19 = WorldGen.PlaceTile(num14, num25, num33, num34 != 0, num35 != 0L, num23, (int)num36);
            return 42190112.0;
            Block_2:
            Tile tile29;
            bool flag20 = tile29.active();
            return 42190112.0;
            Block_3:
            Tile tile30;
            bool flag21 = tile30.active();
            UnifiedRandom genRand11 = WorldGen.genRand;
            int num37 = 5;
            int num38 = genRand11.Next(num37);
            Tile tile31;
            ushort type6 = tile31.type;
            int num39 = 33;
            int num40 = 1;
            long num41 = 0L;
            int num42;
            int num43;
            bool flag22 = WorldGen.PlaceTile(num42, num43, num39, num40 != 0, num41 != 0L, num23, (int)num27);
            Tile tile32;
            ushort type7 = tile32.type;
            int num44 = 49;
            int num45 = 1;
            long num46 = 0L;
            long num47 = 0L;
            bool flag23 = WorldGen.PlaceTile(num42, num43, num44, num45 != 0, num46 != 0L, num23, (int)num47);
            return 42190112.0;
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.WorldGen.genRand, j__TPar, System.L, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.SolidTile(), Terraria.Tile.type, Terraria.Main.UnderworldLayer, and Terraria.Tile.wall.