terraria-cpp2il-methodrecon: Terraria.WorldGen.saveToonWhilePlayingCallBack
saveToonWhilePlayingCallBack()
static void Terraria.WorldGen.saveToonWhilePlayingCallBack (object threadContext) inline static
Definition at line 1347 of file WorldGen.cs.
        {
            if (threadContext != null)
            {
                bool gameMenu = Main.gameMenu;
                bool settingsSavePending = Main.SettingsSavePending;
                bool flag = Main.SaveSettings();
                if (Main.ActivePlayerFileData != null)
                {
                    Player player = Main.ActivePlayerFileData._player;
                    if (player != null)
                    {
                        if (player == null)
{
                        }
                        int num = 1;
                        if (player == null)
{
                        }
                        PlayerFileData activePlayerFileData = Main.ActivePlayerFileData;
                        if (num == 0)
{
                        }
                        long num2 = 0L;
                        long num3 = 0L;
                        Player.SavePlayer(activePlayerFileData, num2 != 0L, num3 != 0L);
                    }
                }
            }
            Profiler.EndThreadProfiling();
        }
References Terraria.IO.PlayerFileData._player, Terraria.Main.ActivePlayerFileData, UnityEngine.Profiling.Profiler.EndThreadProfiling(), Terraria.Main.gameMenu, j__TPar, System.L, Terraria.Player.SavePlayer(), Terraria.Main.SaveSettings(), and Terraria.Main.SettingsSavePending.