terraria-cpp2il-methodrecon: Terraria.WorldGen.RefreshSections
RefreshSections()
static void Terraria.WorldGen.RefreshSections (int startX, int startY, int endX, int endY) inline static
Definition at line 16916 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            int sectionX = Netplay.GetSectionX(startX);
            int sectionY = Netplay.GetSectionY(startY);
            int sectionX2 = Netplay.GetSectionX(endX);
            int sectionY2 = Netplay.GetSectionY(endY);
            if (num == 0)
            {
            }
            bool flag = Main.sectionManager.SectionNeedsRefresh(sectionX, sectionY);
            if (num == 0)
            {
            }
            WorldGen.RefreshSection(sectionX, sectionY);
        }
References Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), j__TPar, Terraria.WorldGen.RefreshSection(), Terraria.Main.sectionManager, and Terraria.WorldSections.SectionNeedsRefresh().