terraria-cpp2il-methodrecon: Terraria.WorldGen.PlacePumpkin
PlacePumpkin()
static void Terraria.WorldGen.PlacePumpkin (int x, int superY) inline static
Definition at line 11103 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            UnifiedRandom genRand = WorldGen.genRand;
            int num2 = 6;
            int num3 = genRand.Next(num2);
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            Tile tile;
            bool flag = tile.active();
            if (num == 0)
            {
            }
            Tile tile2;
            ushort type = tile2.type;
            if (num == 0)
            {
            }
            Tile tile3;
            ushort type2 = tile3.type;
            if (num == 0)
            {
            }
            Tile tile4;
            ushort type3 = tile4.type;
            if (num == 0)
            {
            }
            Tile tile5;
            ushort type4 = tile5.type;
            if (num == 0)
            {
            }
            Tile tile6;
            ushort type5 = tile6.type;
            if (num == 0)
            {
            }
            Tile tile7;
            short frameY = tile7.frameY;
            if (num == 0)
            {
            }
            long num4 = 0L;
            Tile tile8;
            byte liquid = tile8.liquid;
            if (num == 0)
            {
            }
            long num5 = 0L;
            bool flag2 = WorldGen.SolidTile(0, (int)num4, num5 != 0L);
            if (num == 0)
            {
            }
            Tile tile9;
            ushort type6 = tile9.type;
            if (num == 0)
            {
            }
            Tile tile10;
            ushort type7 = tile10.type;
            if (num == 0)
            {
            }
            int num6 = 1;
            Tile tile11;
            tile11.active(num6 != 0);
            tile11.frameY = (short)num3;
            long num7 = 0L;
            tile11.frameX = (short)num7;
            int num8 = 254;
            tile11.type = (ushort)num8;
            int num9 = 1;
            Tile tile12;
            tile12.active(num9 != 0);
            tile12.frameY = (short)num3;
            int num10 = 18;
            tile12.frameX = (short)num10;
            int num11 = 254;
            tile12.type = (ushort)num11;
            int num12 = 1;
            Tile tile13;
            tile13.active(num12 != 0);
            long num13 = 0L;
            tile13.frameX = (short)num13;
            int num14 = 254;
            tile13.type = (ushort)num14;
            int num15 = 1;
            Tile tile14;
            tile14.active(num15 != 0);
            int num16 = 18;
            tile14.frameX = (short)num16;
            int num17 = 254;
            tile14.type = (ushort)num17;
        }
References Terraria.Tile.active(), Terraria.Tile.frameY, Terraria.WorldGen.genRand, j__TPar, System.L, Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SolidTile(), and Terraria.Tile.type.