terraria-cpp2il-methodrecon: Terraria.WorldGen.TryGrowingGlowTulip
TryGrowingGlowTulip()
static bool Terraria.WorldGen.TryGrowingGlowTulip (int i, int j) inline static private
Definition at line 15413 of file WorldGen.cs.
        {
            if (!true)
            {
            }
            UnifiedRandom genRand = WorldGen.genRand;
            int num = Math.Max(10, 43143168);
            int num2 = Math.Min(int.MinValue, 43143168);
            int num3 = genRand.Next(num, num2);
            UnifiedRandom genRand2 = WorldGen.genRand;
            int num4 = Math.Max(10, num);
            int num5 = Math.Min(num4, num);
            int num6 = genRand2.Next(num4, num5);
            bool flag = WorldGen.HasValidGroundForGlowTulipBelowSpot(num3, num6);
            if (-2147483648 == 0)
            {
            }
            bool flag2 = WorldGen.NoNearbyGlowTulips(num3, num6);
            if (-2147483648 == 0)
            {
            }
            if (-2147483648 == 0)
            {
            }
            Tile tile;
            bool flag3 = tile.active();
            if (-2147483648 == 0)
            {
            }
            if (-2147483648 == 0)
            {
                if (-2147483648 == 0)
                {
                }
                bool netHost = Main.NetHost;
                if (-2147483648 == 0)
                {
                }
                Tile tile2;
                bool flag4 = tile2.active();
                return;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), j__TPar, System.Math.Max(), System.Math.Min(), Terraria.Main.NetHost, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.WorldGen.NoNearbyGlowTulips().