terraria-cpp2il-methodrecon: Terraria.WorldGen.InWorld
InWorld()
static bool Terraria.WorldGen.InWorld (int x, int y, int fluff = 0) inline static
Definition at line 1952 of file WorldGen.cs.
        {
            /*
An exception occurred when decompiling this method (06002C93)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean Terraria.WorldGen::InWorld(System.Int32,System.Int32,System.Int32)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    IL_0000:
    brtrue(IL_0000, ldc.i4:bool(1))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1878
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1846
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.Projectile.AI_016(), Terraria.Projectile.AI_046(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.Player.CanDoWireStuffHere(), Terraria.Wiring.CheckLogicGate(), Terraria.IO.WorldFile.ConvertMannequin(), Terraria.IO.WorldFile.ConvertWeaponRack(), Terraria.DelegateMethods.CutTiles(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawTileCracks(), Terraria.WorldGen.DungeonEnt(), Terraria.Collision.ExpandVertically(), Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckType(), Terraria.WorldGen.FillWallHolesInSpot(), Terraria.NPC.FindCattailTop(), Terraria.NPC.FindTreeBranch(), Terraria.WorldGen.Spread.Gem(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowMoreVines(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.hardUpdateWorld(), Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), Terraria.Wiring.HitSwitch(), Terraria.Graphics.Light.TileLightScanner.IsTileNullOrTouchingNull(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.Spread.Moss(), Terraria.DataStructures.TileEntity.PlaceEntityNet(), Terraria.WorldGen.PlaceLiquid(), Terraria.Utils.PlotTileArea(), Terraria.WorldGen.ReplaceTile_EliminateNaturalExtras(), Terraria.Item.Shimmering(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.Main.snowing(), Terraria.WorldGen.SolidTile3(), Terraria.NPC.Spawning_FlyingAntlionCheck(), Terraria.NPC.Spawning_SandstoneCheck(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.Collision.StepDown(), Terraria.Player.TileInteractionsCheckLongDistance(), Terraria.WorldGen.TileIsExposedToAir(), Terraria.Player.TryInteractingWithMinecartTrackInNearbyArea(), Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.Wiring.UpdateMech(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.WorldGen.Spread.Wall(), Terraria.WorldGen.Spread.Wall2(), Terraria.WorldGen.Spread.WallDungeon(), and Terraria.WorldGen.WouldTileReplacementWork().