terraria-cpp2il-methodrecon: Terraria.WorldGen.KillTile_GetTreeDrops
KillTile_GetTreeDrops()
static void Terraria.WorldGen.KillTile_GetTreeDrops (int i, int j, Tile tileCache, bool bonusWood, int dropItem, int secondaryItem) inline static private
Definition at line 14059 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            bool logicHost = Main.LogicHost;
            if (num == 0)
            {
            }
            UnifiedRandom genRand = WorldGen.genRand;
            int num2 = 2;
            long num3 = 0L;
            if (genRand.Next(num2) != 0)
            {
                int num4 = 9;
                dropItem.m_value = num4;
                if (num4 == 0)
                {
                }
                WorldGen.GetTreeBottom(i, j, (int)num3, bonusWood ? 1 : 0);
                if (num4 == 0)
                {
                }
                Tile tile;
                bool flag = tile.active();
                if (num4 == 0)
                {
                }
                Tile tile2;
                ushort type = tile2.type;
                return;
            }
            int num5;
            if (num5 == 0)
            {
            }
            Tile tile3;
            bool flag2 = tile3.active();
            Tile tile4;
            ushort type2 = tile4.type;
            Tile tile5;
            ushort type3 = tile5.type;
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.GetTreeBottom(), j__TPar, System.L, Terraria.Main.LogicHost, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Tile.type.