terraria-cpp2il-methodrecon: Terraria.WorldGen.SectionTileFrameWithCheck
SectionTileFrameWithCheck()
static void Terraria.WorldGen.SectionTileFrameWithCheck (int startX, int startY, int endX, int endY) inline static
Definition at line 16887 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            int sectionX = Netplay.GetSectionX(startX);
            int sectionY = Netplay.GetSectionY(startY);
            int sectionX2 = Netplay.GetSectionX(endX);
            int sectionY2 = Netplay.GetSectionY(endY);
            if (num == 0)
            {
            }
            bool flag = Main.sectionManager.SectionLoaded(sectionX, sectionY);
            if (num == 0)
            {
            }
            bool flag2 = Main.sectionManager.SectionFramed(sectionX, sectionY);
            if (num == 0)
            {
            }
            WorldGen.SectionTileFrame(sectionX, sectionY, sectionX, sectionY);
            if (num == 0)
            {
            }
            bool anyUnfinishedSections = Main.sectionManager.AnyUnfinishedSections;
        }
References Terraria.WorldSections.AnyUnfinishedSections, Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), j__TPar, Terraria.WorldSections.SectionFramed(), Terraria.WorldSections.SectionLoaded(), Terraria.Main.sectionManager, and Terraria.WorldGen.SectionTileFrame().