terraria-cpp2il-methodrecon: Terraria.WorldGen.SolidTile
SolidTile() [3/5]
static bool Terraria.WorldGen.SolidTile (short tileSHeader, ushort tileType) inline static
Definition at line 14460 of file WorldGen.cs.
        {
            if (29792 == 0)
            {
                return;
            }
        }
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.Projectile.AI_025(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.GameContent.Biomes.GraniteBiome.BuildMagmaMap(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Biomes.GraniteBiome.CleanupTiles(), Terraria.WorldGen.CrimStart(), Terraria.Mount.EmitGolfCartWheelDust(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishNoTraps(), Terraria.Projectile.GetFishingPondState(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowWeb(), Terraria.WorldGen.MakeDungeon_GroundFurniture(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.MatureTheHerbPlants(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceDye(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.WorldGen.PlacePumpkin(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlaceUncheckedStalactite(), Terraria.WorldGen.PlaceXmasTree(), Terraria.WorldGen.Scan3By3(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.NPC.SpawnNPC_CheckToSpawnRockGolem(), Terraria.DelegateMethods.SpreadTest(), and Terraria.Player.UpdateBlacklistedTilesForGrappling().