terraria-cpp2il-methodrecon: Terraria.WorldGen.joinLocalWorldCallBack
joinLocalWorldCallBack()
static void Terraria.WorldGen.joinLocalWorldCallBack (object threadContext) inline static
Definition at line 1277 of file WorldGen.cs.
        {
            if (threadContext != null)
            {
                return;
            }
            long ticks = DateTime.Now.Ticks;
            long num = 0L;
            int num2 = 1;
            bool mapEnabled = Main.mapEnabled;
            Main.Map.Allocate((int)ticks, (int)num);
            Main.Map.Load();
            bool loadMapLock = Main.loadMapLock;
            int totalMapSections = Main.sectionManager.TotalMapSections;
            int mapSectionsLeft = Main.sectionManager.mapSectionsLeft;
            int totalMapSections2 = Main.sectionManager.TotalMapSections;
            if (num2 == 0)
            {
            }
            Thread.Sleep(0);
            bool mapEnabled2 = Main.mapEnabled;
        }
References Terraria.Map.WorldMap.Allocate(), j__TPar, System.L, Terraria.Map.WorldMap.Load(), Terraria.Main.loadMapLock, Terraria.Main.Map, Terraria.Main.mapEnabled, Terraria.WorldSections.mapSectionsLeft, System.DateTime.Now, Terraria.Main.sectionManager, System.Threading.Thread.Sleep(), System.DateTime.Ticks, and Terraria.WorldSections.TotalMapSections.