terraria-cpp2il-methodrecon: Terraria.WorldGen.PlaceUnderwaterPlant
PlaceUnderwaterPlant()
static void Terraria.WorldGen.PlaceUnderwaterPlant (ushort type, int x, int y) inline static
Definition at line 12591 of file WorldGen.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            long num2 = 0L;
            bool flag = WorldGen.CanUnderwaterPlantGrowHere(type, x, y, num2 != 0L);
            Tile tileSafely = Framing.GetTileSafely(x, x);
            long num3 = 0L;
            tileSafely.slope((byte)num3);
            long num4 = 0L;
            tileSafely.halfBrick(num4 != 0L);
            Tile tileSafely2 = Framing.GetTileSafely(x, y);
            int num5 = 1;
            tileSafely2.active(num5 != 0);
            tileSafely2.type = type;
            long num6 = 0L;
            tileSafely2.frameX = (short)num6;
            long num7 = 0L;
            tileSafely2.frameY = (short)num7;
            long num8 = 0L;
            tileSafely2.slope((byte)num8);
            long num9 = 0L;
            tileSafely2.halfBrick(num9 != 0L);
            if (num == 0)
            {
            }
            int num10 = 1;
            WorldGen.SquareTileFrame(x, y, num10 != 0);
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.Framing.GetTileSafely(), j__TPar, System.L, Terraria.Tile.slope(), and Terraria.WorldGen.SquareTileFrame().