terraria-cpp2il-methodrecon: Terraria.WorldGen.ExecuteThreadTime
ExecuteThreadTime()
static void Terraria.WorldGen.ExecuteThreadTime () inline static
Definition at line 16012 of file WorldGen.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
            if (!true)
            {
            }
            DateTime now = DateTime.Now;
            if (!false)
            {
                if (3 == 0)
                {
                    Thread.Sleep(0);
                    MainThreadExecution.ExecuteSnippetsOnly();
                    if (false)
                    {
                        goto IL_0038;
                    }
                    if (5 == 0)
                    {
                        return;
                    }
                }
                return;
            }
            IL_0038:
            throw new OutOfMemoryException();
        }
References MainThreadExecution.ExecuteSnippetsOnly(), j__TPar, System.DateTime.Now, and System.Threading.Thread.Sleep().
Referenced by MainThreadExecution.ExecuteSnippets(), and Microsoft.Xna.Framework.Game.UnityServerUpdate().