terraria-cpp2il-methodrecon: GUICraftGuidePopup.Draw
Draw()
void GUICraftGuidePopup.Draw () inline
Definition at line 162 of file GUICraftGuidePopup.cs.
    {
        if (!true)
        {
        }
        if (!true)
        {
        }
        Main.FlushBatches();
        if (this.PickingInterceptor != null)
        {
        }
        GUIControllerCraftingGuidePopup controller = this._controller;
        this._controller.Activate();
        this.FindRecipes();
        int num = this.focusGuideRecipe;
        int selectedNumMaterials = this.SelectedNumMaterials;
    }
References _controller, GUIControllerCraftingGuidePopup.Activate(), FindRecipes(), Terraria.Main.FlushBatches(), focusGuideRecipe, j__TPar, PickingInterceptor, and SelectedNumMaterials.