terraria-cpp2il-methodrecon: System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem
AddItem()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem (XmlWellFormedWriter::AttributeValueCache::ItemType type, object data) inline private
Definition at line 1448 of file XmlWellFormedWriter.cs.
            {
                int num = this.lastItem;
                XmlWellFormedWriter.AttributeValueCache.Item[] array = this.items;
                XmlWellFormedWriter.AttributeValueCache.Item[] array2;
                if (array != null)
                {
                    object data2 = array.data;
                    array2 = this.items;
                    return;
                }
                if (array2 == null)
                {
                    XmlWellFormedWriter.AttributeValueCache.Item[] array3 = this.items;
                }
            }
References System.array, System.Xml.XmlWellFormedWriter.AttributeValueCache.Item.data, System.Xml.XmlWellFormedWriter.AttributeValueCache.items, j__TPar, and System.Xml.XmlWellFormedWriter.AttributeValueCache.lastItem.
Referenced by System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteString(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteWhitespace().