terraria-cpp2il-methodrecon: System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue
StartComplexValue()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue () inline private
Definition at line 1438 of file XmlWellFormedWriter.cs.
            {
                StringBuilder stringBuilder = this.stringValue;
                string text = this.singleStringValue;
                StringBuilder stringBuilder2 = stringBuilder.Append(text);
                string text2 = this.singleStringValue;
                this.AddItem(XmlWellFormedWriter.AttributeValueCache.ItemType.String, text2);
            }
References System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem(), System.Text.StringBuilder.Append(), j__TPar, System.Xml.XmlWellFormedWriter.AttributeValueCache.singleStringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.stringValue, and System.text.
Referenced by System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteChars(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteString(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteSurrogateCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteWhitespace().