terraria-cpp2il-methodrecon: Terraria.Graphics.Light.LightMap.SetSize
SetSize()
void Terraria.Graphics.Light.LightMap.SetSize (int width, int height) inline
Definition at line 488 of file LightMap.cs.
        {
            Vector3[] colors = this._colors;
            this.<Width>k__BackingField = width;
        }
References Terraria.Graphics.Light.LightMap._colors, Terraria.Graphics.Light.LightMap.k__BackingField, and Terraria.Graphics.Light.LightMap.Width.
Referenced by Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.Graphics.Light.LightingEngine.ProcessScan(), and Terraria.Graphics.Light.LegacyLighting.Rebuild().