terraria-cpp2il-methodrecon: Terraria.Graphics.Light.LightMap.Blur1PassThreaded
Blur1PassThreaded()
void Terraria.Graphics.Light.LightMap.Blur1PassThreaded (int start, int end) inline private
Definition at line 314 of file LightMap.cs.
        {
            LightingEngine lightingEngine = this._threadManager.DrawThreads.lightingEngine;
            WallDrawing wallDrawing = this._threadManager.DrawThreads.wallDrawing;
            TileDrawing tileDrawing = this._threadManager.DrawThreads.tileDrawing;
            this.Blur1Pass(start, end);
            ThreadedRenderManager threadManager = this._threadManager;
            ThreadedRenderManager.BatchProcessCallback exportBatchFinishedCallback = this.ExportBatchFinishedCallback;
            int num = 3;
            threadManager.WaitAndProcess(exportBatchFinishedCallback, num);
        }
References Terraria.Graphics.Light.LightMap._threadManager, Terraria.Graphics.Light.LightMap.Blur1Pass(), ThreadedRenderManager.DrawThreads, Terraria.Graphics.Light.LightMap.ExportBatchFinishedCallback, j__TPar, and ThreadedRenderManager.WaitAndProcess().
Referenced by Terraria.Graphics.Light.LightMap.BlurPass().