terraria-cpp2il-methodrecon: Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction
OnPlayerInteraction()
static void Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
Definition at line 189 of file TEItemFrame.cs.
        {
            Vector2 position = player.inventory.position;
            if (position != null)
            {
                if (position == null)
                {
                }
                Tile tile;
                short frameX = tile.frameX;
                int num = 36409;
                int num2 = 36;
                if (num == 0)
                {
                }
                Tile tile2;
                short frameY = tile2.frameY;
                int num3 = TEItemFrame.Find((int)frameY, num2);
                if (position == null)
                {
                }
                player.GamepadEnableGrappleCooldown();
                int num4 = 1;
                long num5 = 0L;
                long num6 = 0L;
                WorldGen.KillTile(clickX, clickY, num4 != 0, num5 != 0L, num6 != 0L);
                bool netClient = Main.NetClient;
                return;
            }
            player.GamepadEnableGrappleCooldown();
            TEItemFrame.PlaceItemInFrame(player, clickX, clickY);
            Recipe.FindRecipes(false);
        }
References Terraria.GameContent.Tile_Entities.TEItemFrame.Find(), Terraria.Recipe.FindRecipes(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Player.inventory, j__TPar, Terraria.WorldGen.KillTile(), System.L, Terraria.Main.NetClient, Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), and Terraria.Entity.position.