terraria-cpp2il-methodrecon: System.Collections.Concurrent.BlockingCollection.Dispose
Dispose() [1/2]
void System.Collections.Concurrent.BlockingCollection< T >.Dispose () inline
Implements System.IDisposable.
Definition at line 185 of file BlockingCollection.cs.
        {
            GC.SuppressFinalize(this);
        }
References System.GC.SuppressFinalize().
Referenced by ReLogic.OS.Windows.STATaskInvoker.Dispose(), and ReLogic.Threading.AsyncActionDispatcher.Dispose().