terraria-cpp2il-methodrecon: Newtonsoft.Json.JsonTextWriter.UpdateCharEscapeFlags
UpdateCharEscapeFlags()
void Newtonsoft.Json.JsonTextWriter.UpdateCharEscapeFlags () inline private
Definition at line 214 of file JsonTextWriter.cs.
        {
            StringEscapeHandling stringEscapeHandling = this._stringEscapeHandling;
            char quoteChar = this._quoteChar;
            if (!true)
            {
            }
            bool[] charEscapeFlags = JavaScriptUtils.GetCharEscapeFlags(stringEscapeHandling, quoteChar);
            this._charEscapeFlags = charEscapeFlags;
        }
References Newtonsoft.Json.JsonTextWriter._quoteChar, Newtonsoft.Json.JsonWriter._stringEscapeHandling, Newtonsoft.Json.Utilities.JavaScriptUtils.GetCharEscapeFlags(), and j__TPar.
Referenced by Newtonsoft.Json.JsonTextWriter.JsonTextWriter(), and Newtonsoft.Json.JsonTextWriter.OnStringEscapeHandlingChanged().