terraria-cpp2il-methodrecon: System.Runtime.InteropServices.Marshal.AllocHGlobal
AllocHGlobal() [2/2]
static IntPtr System.Runtime.InteropServices.Marshal.AllocHGlobal (IntPtr cb) inline static
Definition at line 17 of file Marshal.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by System.Platform.CheckOS(), System.Net.NetworkInformation.AixNetworkInterfaceAPI.GetAllNetworkInterfaces(), and System.Runtime.InteropServices.Marshal.SecureStringGlobalAllocator().