terraria-cpp2il-methodrecon: System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage
SyncProcessMessage()
virtual IMessage System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage (IMessage msgRequest) inline virtual
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 66 of file CrossAppDomainSink.cs.
        {
            CADMethodCallMessage cadmethodCallMessage = CADMethodCallMessage.Create(msgRequest);
            if (cadmethodCallMessage != null)
            {
            }
            MemoryStream memoryStream = CADSerializer.SerializeMessage(msgRequest);
            Context currentContext = Thread.CurrentContext;
            int domainID = this._domainID;
            if (memoryStream != null && memoryStream == null)
            {
                throw new ArrayTypeMismatchException();
            }
            if (cadmethodCallMessage != null && cadmethodCallMessage == null)
            {
                throw new ArrayTypeMismatchException();
            }
            long num = 0L;
            int num2 = 3;
            Context context = AppDomain.InternalSetContext(currentContext);
            if (num == 0L && num2 == 0 && domainID != 0)
            {
                IMessage message;
                return message;
            }
            throw new OutOfMemoryException();
        }
References System.Runtime.Remoting.Channels.CrossAppDomainSink._domainID, System.Runtime.Remoting.Messaging.CADMethodCallMessage.Create(), System.Threading.Thread.CurrentContext, System.AppDomain.InternalSetContext(), j__TPar, System.L, and System.Runtime.Remoting.Channels.CADSerializer.SerializeMessage().