terraria-cpp2il-methodrecon: ThreadedRenderManager.WaitAndProcess
WaitAndProcess()
void ThreadedRenderManager.WaitAndProcess (ThreadedRenderManager::BatchProcessCallback callback, int numberOfThreads) inline
Definition at line 74 of file ThreadedRenderManager.cs.
    {
        AutoResetEvent[][] waitHandles = this.WaitHandles;
        int[][] waitThreads = this.WaitThreads;
        SafeWaitHandle safeWaitHandle = waitHandles.safeWaitHandle;
        if ("Thread wait aborted!" != null)
        {
            AutoResetEvent[][] waitHandles2 = this.WaitHandles;
            int[][] waitThreads2 = this.WaitThreads;
            return;
        }
        throw new ArrayTypeMismatchException();
    }
References j__TPar, WaitHandles, and WaitThreads.
Referenced by Terraria.Graphics.Light.LightMap.Blur1PassThreaded(), Terraria.Graphics.Light.LightMap.Blur2PassThreaded(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMapThreaded(), Terraria.Graphics.Light.TileLightScanner.ExportToThreaded(), Terraria.Main.WaitBackgroundDrawThreads(), and Terraria.GameContent.Drawing.TileDrawing.WaitDrawThreads().