terraria-cpp2il-methodrecon: Terraria.Utilities.FileUtilities.CreateDirectory
CreateDirectory()
static void Terraria.Utilities.FileUtilities.CreateDirectory (string path) inline static
Definition at line 44 of file FileUtilities.cs.
        {
            FileManager.CreateDirectory(path);
        }
References FileManager.CreateDirectory().
Referenced by Terraria.Map.MapHelper.InternalSaveMap(), Terraria.Player.InternalSaveMap(), Terraria.Map.MapHelper.InternalSaveMapCompressed(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.Main.LoadWorlds(), Terraria.Utils.OpenFolder(), and Terraria.Main.SaveRecent().