terraria-cpp2il-methodrecon: Terraria.Utilities.FileUtilities.Exists
Exists()
static bool Terraria.Utilities.FileUtilities.Exists (string path, bool cloud = false) inline static
Definition at line 50 of file FileUtilities.cs.
        {
            bool flag;
            return flag;
        }
Referenced by Terraria.IO.OldSaveSynchronise.CopyOldSaves(), Terraria.Main.GetPlayerPathFromName(), Terraria.IO.Preferences.Load(), Terraria.Main.LoadDedConfig(), Terraria.Utils.OpenFolder(), Terraria.Main.OpenLegacySettings(), Terraria.Main.OpenRecent(), Terraria.Main.ResetSettings(), Terraria.IO.Preferences.Save(), and VirtualControllerInputState.SaveDefaultCategories().