terraria-cpp2il-methodrecon: GUIPanel.Region
Region()
static Rectangle GUIPanel.Region (Panel_Layout layout) inline static
Definition at line 57 of file GUIPanel.cs.
    {
        if (!true)
        {
        }
        if (true)
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
        }
        if (!true)
        {
            return;
        }
    }
Referenced by GUIRubbleMaker.CalculateMaterialRegion(), GUIRubbleMaker.CalculateRegion(), GUIRubbleMaker.ClampPositionToScreen(), GUIResearch.DrawBacking(), GUIEvents.DrawInfiniteProgressBar(), GUIResearch.DrawItemProgress(), GUIRubbleMaker.DrawOverlay(), GUIEvents.DrawProgressBar(), GUIResearch.DrawResearchBacking(), GUIResearch.DrawTexture(), GUIResearch.GetRegion(), GUIControllerChat.GetSelectedItemRegion(), GUIControllerResearchPage4Page.GetSelectedItemRegion(), GUIResearch.IsOver(), GUIRubbleMaker.IsOver(), GUIMultiplayerChat.LoadPageRegion(), and GUIControllerChat.UpdateEmoteScroll().