terraria-cpp2il-methodrecon: Mono.Net.Security.MobileAuthenticatedStream.Dispose
Dispose() [2/2]
override void Mono.Net.Security.MobileAuthenticatedStream.Dispose (bool disposing) inline protected inherited
Definition at line 479 of file MobileAuthenticatedStream.cs.
        {
            object obj = this.ioLock;
            Monitor.Enter(obj, disposing);
            MobileTlsContext mobileTlsContext = this.xobileTlsContext;
            if (mobileTlsContext != null)
            {
                mobileTlsContext.Dispose();
                return;
            }
            long num = 0L;
            long num2;
            if ("MobileAuthenticatedStream" != null)
            {
                num2 = 0L;
                Monitor.Exit(obj);
            }
            if (num == 0L)
            {
                base.Dispose(num2 != 0L);
                return;
            }
            throw new OutOfMemoryException();
        }
References Mono.Net.Security.MobileTlsContext.Dispose(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Mono.Net.Security.MobileAuthenticatedStream.ioLock, j__TPar, System.L, System.obj, and Mono.Net.Security.MobileAuthenticatedStream.xobileTlsContext.