terraria-cpp2il-methodrecon: GUIMultiplayerHost.Draw
Draw()
void GUIMultiplayerHost.Draw () inline
Definition at line 20 of file GUIMultiplayerHost.cs.
    {
        if (!true)
        {
        }
        Rectangle selectedItemRegion = this.SelectedItemRegion;
        int width = this.SelectedItemRegion.Width;
        ControlAnchor.SetGridItemRegion(selectedItemRegion);
        GUIControllerMultiplayerHost controllerInput = this._controllerInput;
        this.DrawMaxPlayers();
        this.DrawMainButtons();
        this.DrawOpenInviteOnly();
    }
References _controllerInput, DrawMainButtons(), DrawMaxPlayers(), DrawOpenInviteOnly(), j__TPar, SelectedItemRegion, ControlAnchor.SetGridItemRegion(), and Microsoft.Xna.Framework.Rectangle.Width.