terraria-cpp2il-methodrecon: System.Runtime.Serialization.SerializationObjectManager.RegisterObject
RegisterObject()
void System.Runtime.Serialization.SerializationObjectManager.RegisterObject (object obj) inline
Definition at line 17 of file SerializationObjectManager.cs.
        {
            SerializationEvents serializationEventsForType = SerializationEventsCache.GetSerializationEventsForType(obj.GetType());
            if (serializationEventsForType._onSerializingMethods != null || serializationEventsForType._onSerializedMethods != null)
            {
                Dictionary<object, object> objectSeenTable = this._objectSeenTable;
                StreamingContext context = this._context;
                StreamingContextStates state = this._context.m_state;
                serializationEventsForType.InvokeOnSerializing(obj, context);
                this.AddOnSerialized(obj);
            }
        }
References System.Runtime.Serialization.SerializationObjectManager._context, System.Runtime.Serialization.SerializationObjectManager._objectSeenTable, System.Runtime.Serialization.SerializationObjectManager.AddOnSerialized(), System.Runtime.Serialization.SerializationEventsCache.GetSerializationEventsForType(), System.Runtime.Serialization.SerializationEvents.InvokeOnSerializing(), j__TPar, System.Runtime.Serialization.StreamingContext.m_state, System.obj, and System.state.