terraria-cpp2il-methodrecon: Terraria.Utilities.UnifiedRandom.NextDouble
NextDouble()
double Terraria.Utilities.UnifiedRandom.NextDouble () inline
Definition at line 127 of file UnifiedRandom.cs.
        {
            /*
An exception occurred when decompiling this method (06003125)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Double Terraria.Utilities.UnifiedRandom::NextDouble()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:int32(var_0_06, call:int32(UnifiedRandom::InternalSample, ldloc:UnifiedRandom(this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.WorldGen.AddTrees(), Terraria.GameContent.Skies.SlimeSky.GenerateSlimes(), Terraria.Utilities.WeightedRandom< T >.Get(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.neonMossBiome(), Terraria.Utils.NextVector2FromRectangle(), Terraria.Utils.NextVector2Square(), Terraria.Utils.NextVector2Unit(), Terraria.WorldGen.oceanCave(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests(), Terraria.Utils.RandomVector2(), Terraria.Utils.RandomVector2D(), Terraria.GameContent.Skies.PartySky.ResetBalloon(), Terraria.GameContent.Skies.LanternSky.ResetLantern(), and Terraria.WorldGen.WavyCaverer().