terraria-cpp2il-methodrecon: Terraria.IO.Preferences.Load
Load()
bool Terraria.IO.Preferences.Load () inline
Definition at line 93 of file Preferences.cs.
        {
            int num = 1;
            object @lock = this._lock;
            string path = this._path;
            if (num == 0)
            {
            }
            long num2 = 0L;
            bool flag = FileUtilities.Exists(path, num2 != 0L);
            bool useBson = this.UseBson;
            string path2 = this._path;
            int num4;
            if (useBson)
            {
                if (num == 0)
                {
                }
                long num3 = 0L;
                byte[] array = FileUtilities.ReadAllBytes(path2, num3 != 0L);
                JsonSerializer jsonSerializer = JsonSerializer.Create(this._serializerSettings);
                this._data = jsonSerializer;
                num4 = 6;
                if (useBson)
                {
                }
            }
            JsonSerializerSettings serializerSettings = this._serializerSettings;
            string text;
            this._data = text;
            if (text == null)
            {
                if (serializerSettings != null)
                {
                    throw new OutOfMemoryException();
                }
                int num5;
                if (num4 == 0)
                {
                    num5 = 5;
                    if (text != null)
                    {
                        goto IL_0089;
                    }
                }
                long num6 = 0L;
                if (text == null)
                {
                    goto IL_008D;
                }
                IL_0089:
                if (useBson)
                {
                }
                IL_008D:
                if (num6 != 0L)
                {
                    goto IL_00AB;
                }
                if (num5 != 0)
                {
                    long num7 = 0L;
                    Monitor.Exit(@lock);
                    if (num7 == 0L)
                    {
                    }
                    throw new OutOfMemoryException();
                }
                if (this._data == null)
                {
                }
            }
            if (this.OnLoad != null)
            {
            }
            IL_00AB:
            throw new OutOfMemoryException();
        }
References Terraria.IO.Preferences._data, Terraria.IO.Preferences._lock, Terraria.IO.Preferences._path, Terraria.IO.Preferences._serializerSettings, System.array, Newtonsoft.Json.JsonSerializer.Create(), Terraria.Utilities.FileUtilities.Exists(), System.Threading.Monitor.Exit(), j__TPar, System.L, Terraria.IO.Preferences.OnLoad, Terraria.Utilities.FileUtilities.ReadAllBytes(), System.text, and Terraria.IO.Preferences.UseBson.