terraria-cpp2il-methodrecon: Terraria.IO.Preferences.Put
Put()
void Terraria.IO.Preferences.Put (string name, object value) inline
Definition at line 229 of file Preferences.cs.
        {
            object @lock = this._lock;
            Dictionary<string, object> data = this._data;
            bool autoSave = this.AutoSave;
            if (autoSave)
            {
                bool flag = this.Save(true);
            }
            long num = 0L;
            if (autoSave)
            {
                Monitor.Exit(@lock);
            }
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References Terraria.IO.Preferences._data, Terraria.IO.Preferences._lock, Terraria.IO.Preferences.AutoSave, System.Threading.Monitor.Exit(), j__TPar, System.L, and Terraria.IO.Preferences.Save().
Referenced by Terraria.GameContent.UI.ResourceSets.PlayerResourceSetsManager.Configuration_OnSave(), GUIControllerMappingState.SaveConfiguration(), and Terraria.Main.SaveSettings().