terraria-cpp2il-methodrecon: System.Net.HttpListener.CreateSslStream
CreateSslStream()
global.System.Net.Security.SslStream System.Net.HttpListener.CreateSslStream (Stream innerStream, bool ownsStream, global::System::Net::Security::RemoteCertificateValidationCallback callback) inline package
Definition at line 63 of file HttpListener.cs.
        {
            object internalLock;
            do
            {
                internalLock = this._internalLock;
                if (this.tlsProvider == null)
                {
                    MonoTlsProvider provider = MonoTlsProviderFactory.GetProvider();
                    this.tlsProvider = provider;
                }
            }
            while (this.tlsSettings != null);
            MonoTlsSettings monoTlsSettings = MonoTlsSettings.DefaultSettings.Clone();
            MonoRemoteCertificateValidationCallback monoRemoteCertificateValidationCallback = Mono.Net.Security.Private.CallbackHelpers.PublicToMono(callback);
            monoTlsSettings.<RemoteCertificateValidationCallback>k__BackingField = monoRemoteCertificateValidationCallback;
            MonoTlsProvider monoTlsProvider = this.tlsProvider;
            long num = 0L;
            Monitor.Exit(internalLock);
            if (num == 0L)
            {
            }
            throw new OutOfMemoryException();
        }
References System.Net.HttpListener._internalLock, Mono.Security.Interface.MonoTlsSettings.Clone(), Mono.Security.Interface.MonoTlsSettings.DefaultSettings, System.Threading.Monitor.Exit(), Mono.Security.Interface.MonoTlsProviderFactory.GetProvider(), j__TPar, System.L, Mono.Net.Security.Private.CallbackHelpers.PublicToMono(), System.Net.HttpListener.tlsProvider, and System.Net.HttpListener.tlsSettings.