terraria-cpp2il-methodrecon: System.Net.HttpListener.LoadCertificateAndKey
LoadCertificateAndKey()
X509Certificate System.Net.HttpListener.LoadCertificateAndKey (IPAddress addr, int port) inline package
Definition at line 29 of file HttpListener.cs.
        {
            int num = 1;
            object internalLock = this._internalLock;
            if (this.certificate != null)
            {
            }
            if (num == 0)
            {
            }
            string text2;
            string text = Path.Combine(Path.Combine(text2, ".mono"), "httplistener");
            string text3;
            bool flag = File.Exists(Path.Combine(text, text3));
            if ("{0}.pvk" == null)
            {
            }
            string text5;
            string text4 = Path.Combine(text, text5);
            bool flag2 = File.Exists(text4);
            RSA rsa = PrivateKey.CreateFromFile(text4).rsa;
            global::System.Security.Cryptography.X509Certificates.X509Certificate2Impl x509Certificate2Impl;
            if (x509Certificate2Impl != null)
            {
            }
            long num2 = 0L;
            Monitor.Exit(internalLock);
            if (num2 == 0L)
            {
            }
            throw new OutOfMemoryException();
        }
References System.Net.HttpListener._internalLock, System.Net.HttpListener.certificate, System.IO.Path.Combine(), Mono.Security.Authenticode.PrivateKey.CreateFromFile(), System.IO.File.Exists(), System.Threading.Monitor.Exit(), j__TPar, System.L, Mono.Security.Authenticode.PrivateKey.rsa, and System.text.