terraria-cpp2il-methodrecon: System.Net.WebConnection.CloseSocket
CloseSocket()
void System.Net.WebConnection.CloseSocket () inline private
Definition at line 278 of file WebConnection.cs.
        {
            Stream stream = this.networkStream;
            if (stream != null)
            {
                stream.Dispose();
            }
            Mono.Net.Security.MonoTlsStream monoTlsStream = this.monoTlsStream;
            if (monoTlsStream != null)
            {
                monoTlsStream.Dispose();
            }
            global::System.Net.Sockets.Socket socket = this.socket;
            if (socket != null)
            {
                socket.Dispose();
            }
            long num = 0L;
            Monitor.Exit(this);
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.IO.Stream.Dispose(), System.Threading.Monitor.Exit(), System.L, System.Net.WebConnection.monoTlsStream, System.Net.WebConnection.networkStream, and System.Net.WebConnection.socket.
Referenced by System.Net.WebConnection.Close().