terraria-cpp2il-methodrecon: System.Net.WebConnection.Close
Close()
void System.Net.WebConnection.Close (bool reset) inline private
Definition at line 263 of file WebConnection.cs.
        {
            Monitor.Enter(this, reset);
            this.CloseSocket();
            this.Reset();
            long num = 0L;
            Monitor.Exit(this);
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.Net.WebConnection.CloseSocket(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.L, and System.Net.WebConnection.Reset().
Referenced by System.Net.WebConnection.Continue(), System.Net.WebConnection.Dispose(), and System.Net.WebConnection.StartOperation().