terraria-cpp2il-methodrecon: System.Net.WebConnection.StartOperation
StartOperation()
bool System.Net.WebConnection.StartOperation (WebOperation operation, bool reused) inline
Definition at line 373 of file WebConnection.cs.
        {
            int num = this.disposed;
            if (num != 0 || this != null)
            {
                long num2 = 0L;
                int num3 = 3;
                if (num != 0)
                {
                    Monitor.Exit(this);
                }
                if (num2 != 0L)
                {
                    goto IL_0083;
                }
                if (num3 == 0)
                {
                    operation.Run();
                }
            }
            DateTime utcNow = DateTime.UtcNow;
            TimeSpan timeSpan = TimeSpan.FromDays(3650.0);
            DateTime dateTime = utcNow + timeSpan;
            this.idleSince = dateTime;
            bool flag = this.PrepareSharingNtlm(operation);
            int num4 = 1;
            this.Close(num4 != 0);
            ServicePoint servicePoint = this.<ServicePoint>k__BackingField;
            operation.RegisterRequest(servicePoint, this);
            IL_0083:
            throw new OutOfMemoryException();
        }
References System.Net.WebConnection.Close(), System.Net.WebConnection.disposed, System.Threading.Monitor.Exit(), System.TimeSpan.FromDays(), j__TPar, System.Net.WebConnection.k__BackingField, System.L, System.Net.WebConnection.PrepareSharingNtlm(), System.Net.WebOperation.RegisterRequest(), System.Net.WebOperation.Run(), and System.DateTime.UtcNow.