terraria-cpp2il-methodrecon: System.TimeZoneInfo.TryGetLocalTzFile
TryGetLocalTzFile()
static bool System.TimeZoneInfo.TryGetLocalTzFile ([Out] byte[] rawData, [Out] string id) inline static private
Definition at line 70 of file TimeZoneInfo.cs.
        {
            if (!true)
            {
            }
            string tzEnvironmentVariable = TimeZoneInfo.GetTzEnvironmentVariable();
            if (tzEnvironmentVariable != null)
            {
                int stringLength = tzEnvironmentVariable._stringLength;
                if (stringLength == 0)
                {
                    string text = Path.Combine(TimeZoneInfo.GetTimeZoneDirectory(), "localtime");
                    bool flag;
                    return flag;
                }
                long num = 0L;
                char c = tzEnvironmentVariable[(int)num];
                rawData.m_value = tzEnvironmentVariable;
                if (stringLength == 0)
                {
                }
                string text2 = Path.Combine(TimeZoneInfo.GetTimeZoneDirectory(), tzEnvironmentVariable);
            }
            return true;
        }
References System.IO.Path.Combine(), System.TimeZoneInfo.GetTimeZoneDirectory(), System.TimeZoneInfo.GetTzEnvironmentVariable(), j__TPar, System.L, and System.text.