terraria-cpp2il-methodrecon: UnityEngine.Debug.Log
Log()
static void UnityEngine.Debug.Log (object message) inline static
Definition at line 51 of file Debug.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
        }
Referenced by DefaultFileAPI.DefaultFileAPI(), Microsoft.Xna.Framework.Graphics.MaterialBuffer.MaterialEntry.MaterialEntry(), Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Android_UserManager._authenticationFailedEvent(), Android_UserManager._authenticationSucceededEvent(), AndroidImmersive.Activate(), UnityEngine.GUISkin.Apply(), Singleton< T >.Cleanup(), GUIPageIcons.ClickedOutOfRegion(), Telepathy.Client.Connect(), InControl.InputDeviceProfile.CreateInstanceOfType(), UnityEngine.AndroidJavaObject.DebugPrint(), Terraria.Main.DedServ(), InControl.UnityDeviceProfiles.PlayStation4AndroidUnityProfile.Define(), InControl.UnityDeviceProfiles.PlayStation4TouchpadAndroidUnityProfile.Define(), GUILowDiskSpacePopup.DiskSpace(), SimpleProfiler.DumpFrameData(), Terraria.NetMessage.EnsureLocalPlayerIsPresent(), AndroidImmersive.GetSDKLevel(), GUIControllerDynamicGridNavigator.GetSelectedItemRegion(), DefaultFileAPI.GetUserSavePath(), Terraria.Player.InternalSaveMap(), Terraria.Player.InternalSavePlayerFile(), InControl.InControlManager.LogMessage(), Terraria.Netplay.OnConnectionAccepted(), InControl.InControlManager.OnEnable(), AndroidImmersive.Listener.onSystemUiVisibilityChange(), UnityEngine.MonoBehaviour.print(), SaveSynchronisationOperation_ReceiveFile.ProcessMessage(), AndroidImmersive.RunDeactivate(), Terraria.Player.SavePlayer(), Terraria.IO.WorldFile.SaveWorld(), MPSession_Dummy.SetClientInSession(), DrPlatform.Switch.SetCpuBoostMode(), Android_UserManager.Update(), TutorialStep_05_Torches.Update(), Microsoft.Xna.Framework.Content.ContentManager.UpdateAysncLoad(), and XNAUIInputLayer.UpdateCursor().