terraria-cpp2il-methodrecon: UnityEngine.Debug.LogError
LogError() [1/2]
static void UnityEngine.Debug.LogError (object message) inline static
Definition at line 62 of file Debug.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
        }
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), InControl.UnityInputDevice.UnityInputDevice(), SaveSynchronisationOperation_SendFile.Begin(), Terraria.Netplay.BroadcastThread(), GUIQuickActionButton.CanInteract(), Terraria.Map.WorldMapChunk.Compress(), FileCompressor.CompressFile(), FileCompressor.Decompress(), Terraria.Map.WorldMapChunk.Decompress(), GUIControllerDisconnected.DisplayNpadConnectionPromptAndReassignNpads(), GUIDraggableItemGrid.Draw(), Terraria.TimeLogger.DrawException(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), MainThreadExecution.ExecuteOnMainThread(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.GetBatchInstance(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.GetInstance(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.GetInstance(), UnityEngine.RectTransform.GetLocalCorners(), UnityEngine.RectTransform.GetWorldCorners(), UnityEngine.UI.CanvasUpdateRegistry.InternalDisableCanvasElementForGraphicRebuild(), UnityEngine.UI.CanvasUpdateRegistry.InternalDisableCanvasElementForLayoutRebuild(), UnityEngine.UI.CanvasUpdateRegistry.InternalRegisterCanvasElementForGraphicRebuild(), UnityEngine.UI.CanvasUpdateRegistry.InternalUnRegisterCanvasElementForGraphicRebuild(), UnityEngine.UI.CanvasUpdateRegistry.InternalUnRegisterCanvasElementForLayoutRebuild(), UnityEngine.GUILayoutUtility.LayoutFromEditorWindow(), LayoutDefinition.LoadFields(), Terraria.Audio.LegacyAudioSystem.LoadFromSources(), Microsoft.Xna.Framework.Content.ContentManager.LoadSoundEffect(), Microsoft.Xna.Framework.Content.ContentManager.LoadUnityTexturePageAsync(), InControl.TouchManager.OnEnable(), UnityEngine.Mesh.PrintErrorCantAccessIndices(), InControl.UnityInputDevice.RefreshProfile(), Terraria.Netplay.ServerLoop(), UnityEngine.EventSystems.EventSystem.SetSelectedGameObject(), UnityEngine.UI.Dropdown.SetupTemplate(), UnityEngine.Mesh.SetUvsImpl< T >(), ThreadedRenderManager.ThreadMonitor(), FileManager.WriteAllBytes(), and SaveSynchronisationOperation_ReceiveFile.WriteFile().