terraria-cpp2il-methodrecon: System.IO.Enumeration.FileSystemEntry.ToSpecifiedFullPath
ToSpecifiedFullPath()
string System.IO.Enumeration.FileSystemEntry.ToSpecifiedFullPath () inline
Definition at line 187 of file FileSystemEntry.cs.
        {
            int length = this.<Directory>k__BackingField._length;
            int length2 = this.<RootDirectory>k__BackingField._length;
            ReadOnlySpan<char> readOnlySpan = this.<Directory>k__BackingField;
            ThrowHelper.ThrowArgumentOutOfRangeException();
            ReadOnlySpan<char> readOnlySpan2 = this.<OriginalRootDirectory>k__BackingField;
            int length3 = this.<OriginalRootDirectory>k__BackingField._length;
            if (length == 0)
            {
            }
            bool flag = PathInternal.EndsInDirectorySeparator(readOnlySpan2);
            if (length == 0)
            {
            }
            bool flag2 = PathInternal.StartsWithDirectorySeparator(readOnlySpan);
            ThrowHelper.ThrowArgumentOutOfRangeException();
            ReadOnlySpan<char> readOnlySpan3 = this.<OriginalRootDirectory>k__BackingField;
            int length4 = this.<OriginalRootDirectory>k__BackingField._length;
            ReadOnlySpan<char> fileName = this.FileName;
            if (length == 0)
            {
            }
            string text;
            return text;
        }
References System.ReadOnlySpan< T >._length, System.IO.PathInternal.EndsInDirectorySeparator(), System.IO.Enumeration.FileSystemEntry.FileName, j__TPar, System.IO.Enumeration.FileSystemEntry.k__BackingField, System.length, System.IO.Enumeration.FileSystemEntry.OriginalRootDirectory, System.IO.Enumeration.FileSystemEntry.RootDirectory, System.IO.PathInternal.StartsWithDirectorySeparator(), System.text, and System.ThrowHelper.ThrowArgumentOutOfRangeException().