terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawGeometryWithSubMeshes
DrawGeometryWithSubMeshes()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawGeometryWithSubMeshes (SpriteBatcher::VertexData[] vertices, short[] indices, int vertexCount, int indexCount, Vector3 position, Vector3 scale, List< Material > subMeshMaterials, List< SubMeshDescriptor > subMeshPartitions) inline
Definition at line 751 of file GraphicsDevice.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            GeometryBufferInstance batchInstance = GeometryBufferInstance.GetBatchInstance();
            int offset = batchInstance._offset;
            if (false)
            {
                if (num == 0)
                {
                }
                GeometryBufferInstance.IncrementBufferOffset();
            }
            Material[] array;
            batchInstance._meshRenderer.materials = array;
            Mesh mesh = batchInstance.Mesh;
            int num2 = 1;
            mesh.Clear(num2 != 0);
            mesh.subMeshCount = num2;
            if (num == 0)
            {
            }
            long num3 = 0L;
            mesh.UploadMeshData(num3 != 0L);
        }
References UnityEngine.Mesh.Mesh(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance._offset, System.array, UnityEngine.Mesh.Clear(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.GetBatchInstance(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.IncrementBufferOffset(), j__TPar, System.L, System.offset, and UnityEngine.Mesh.UploadMeshData().