terraria-cpp2il-methodrecon: System.ComponentModel.AsyncOperation.OperationCompletedCore
OperationCompletedCore()
void System.ComponentModel.AsyncOperation.OperationCompletedCore () inline private
Definition at line 78 of file AsyncOperation.cs.
        {
            SynchronizationContext syncContext = this._syncContext;
            long num = 0L;
            GC.SuppressFinalize(this);
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References System.ComponentModel.AsyncOperation._syncContext, j__TPar, System.L, and System.GC.SuppressFinalize().
Referenced by System.ComponentModel.AsyncOperation.OperationCompleted(), and System.ComponentModel.AsyncOperation.PostOperationCompleted().