terraria-cpp2il-methodrecon: System.Security.Cryptography.RSACryptoServiceProvider.VerifyData
VerifyData() [1/5]
bool System.Security.Cryptography.RSACryptoServiceProvider.VerifyData (byte[] buffer, object halg, byte[] signature) inline
Definition at line 536 of file RSACryptoServiceProvider.cs.
        {
            while (buffer != null)
            {
                if (signature != null)
                {
                    HashAlgorithm hash = this.GetHash(halg);
                    byte[] array = hash.ComputeHash(buffer);
                    return PKCS1.Verify_v15(this, hash, array, signature);
                }
            }
            return "buffer" != null;
        }
References System.array, System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.RSACryptoServiceProvider.GetHash(), and Mono.Security.Cryptography.PKCS1.Verify_v15().