terraria-cpp2il-methodrecon: Terraria.UI.IngameFancyUI.OpenAchievementsAndGoto
OpenAchievementsAndGoto()
static void Terraria.UI.IngameFancyUI.OpenAchievementsAndGoto (Achievement achievement) inline static
Definition at line 37 of file IngameFancyUI.cs.
        {
            IngameFancyUI.OpenAchievements();
        }
References Terraria.UI.IngameFancyUI.OpenAchievements().
Referenced by Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.GameContent.UI.Chat.AchievementTagHandler.AchievementSnippet.OnClick(), and Terraria.UI.InGamePopups.AchievementUnlockedPopup.OnMouseOver().