terraria-cpp2il-methodrecon: GUIInterfaceEdit.DrawProfile
DrawProfile()
void GUIInterfaceEdit.DrawProfile () inline private
Definition at line 401 of file GUIInterfaceEdit.cs.
    {
        bool mouseLeft = Main.mouseLeft;
        bool mouseLeftRelease = Main.mouseLeftRelease;
        bool flag = this.editingName;
        if (flag)
        {
            bool mouseLeft2 = Main.mouseLeft;
            bool mouseLeftRelease2 = Main.mouseLeftRelease;
            this.CloseNameEdit();
        }
        InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
        bool flag2 = this.editingName;
        if (flag2)
        {
            string text = this.editNameValue;
            long num = 0L;
            if (!flag2)
            {
            }
            int num2 = 20;
            long num3 = 0L;
            long num4 = 0L;
            long num5 = 0L;
            Rectangle rectangle;
            string inputText = Main.GetInputText(text, rectangle, (int)num, num2 != 0, num3 != 0L, num4 != 0L, num5 != 0L);
            this.editNameValue = inputText;
            int stringLength = inputText._stringLength;
            int num6 = 20;
            long num7 = 0L;
            string text2 = inputText.Substring((int)num7, num6);
            this.editNameValue = text2;
            if (stringLength == 0)
            {
            }
            if (flag)
            {
                return;
            }
            if (!flag)
            {
            }
            InterfaceProfile_Layout active2 = InterfaceStyles_Layout.Active;
            string text3 = this.editNameValue;
            active2.ProfileName = text3;
            int num8 = this.textBlinkerCount;
            this.textBlinkerCount = num8;
            int num9 = this.textBlinkerState;
            this._optionsBlocker = num9;
            string text4 = this.editNameValue;
            bool flag3 = string.IsNullOrEmpty(text4);
            SpriteFont spriteFont;
            Microsoft.Xna.Framework.Vector2 vector = spriteFont.MeasureString(text4);
            long num10 = 0L;
            SpriteFont spriteFont2;
            string text5;
            Microsoft.Xna.Framework.Vector2 vector2 = spriteFont2.MeasureString(text5);
            int stringLength2 = text4._stringLength;
            int num11 = 1;
            string text6 = text4.Substring(num11, (int)num10);
            return;
        }
        else
        {
            GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
            bool flag4 = this.displayProfileOptions;
            int num12;
            if (optionsBlocker != null)
            {
                if (flag4)
                {
                    return;
                }
            }
            else if (flag4)
            {
                if (optionsBlocker == null)
                {
                }
                num12 = 1;
                string text7;
                int stringLength3 = text7._stringLength;
                return;
            }
            if (num12 == 0)
            {
            }
            InterfaceProfile_Layout active3 = InterfaceStyles_Layout.Active;
            bool flag5 = this.displayProfileOptions;
            GUITransactionButton.InputState inputState;
            if (inputState == GUITransactionButton.InputState.Clicked)
            {
                this.CloseProfileOptions();
                return;
            }
            GUIControllerInterfaceEdit guicontrollerInterfaceEdit;
            int pageRow = guicontrollerInterfaceEdit.PageRow;
            return;
        }
    }
References _optionsBlocker, InterfaceStyles_Layout.Active, CloseNameEdit(), CloseProfileOptions(), displayProfileOptions, editingName, editNameValue, Terraria.Main.GetInputText(), j__TPar, System.L, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, GUIControllerInterfaceEdit.PageRow, System.text, textBlinkerCount, and textBlinkerState.