terraria-cpp2il-methodrecon: GUIInterfaceEdit.DrawTemplate
DrawTemplate()
void GUIInterfaceEdit.DrawTemplate () inline private
Definition at line 528 of file GUIInterfaceEdit.cs.
    {
        bool mouseLeft = Main.mouseLeft;
        bool mouseLeftRelease = Main.mouseLeftRelease;
        this.RefreshTemplate();
        if (this.currentProfile != null)
        {
            return;
        }
        string textValue = Language.GetTextValue("InterfaceProfiles.Custom");
        GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
        bool flag = this.displayTemplateOptions;
        if (optionsBlocker == null || flag)
        {
        }
        GUITransactionButton.InputState inputState;
        GUIInputRegionExclusive.IsOverHandler isOver;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            if (this.displayTemplateOptions)
            {
                this.CloseTemplateOptions();
                return;
            }
            isOver = optionsBlocker.isOver;
            if (isOver == null)
            {
            }
            if (!true)
            {
            }
            Main.mouseLeftRelease = Main.mouseLeftRelease;
            GUIInputRegionExclusive guiinputRegionExclusive;
            this._optionsBlocker = guiinputRegionExclusive;
        }
        string textValue2 = Language.GetTextValue("Mobile.ProfileTemplate");
        if (isOver == null)
        {
        }
        bool flag2 = this.displayTemplateOptions;
        if (flag2)
        {
            if (!flag2)
            {
            }
            string text;
            string textValue3 = Language.GetTextValue(text);
            int stringLength = textValue2._stringLength;
            string text2;
            string textValue4 = Language.GetTextValue(text2);
            string text3;
            string textValue5 = Language.GetTextValue(text3);
            string textValue6 = Language.GetTextValue("InterfaceProfiles.Custom");
            SpriteFont spriteFont;
            Microsoft.Xna.Framework.Vector2 vector = spriteFont.MeasureString(textValue3);
            SpriteFont spriteFont2;
            Microsoft.Xna.Framework.Vector2 vector2 = spriteFont2.MeasureString(textValue4);
            SpriteFont spriteFont3;
            Microsoft.Xna.Framework.Vector2 vector3 = spriteFont3.MeasureString(textValue5);
            SpriteFont spriteFont4;
            Microsoft.Xna.Framework.Vector2 vector4 = spriteFont4.MeasureString(textValue6);
            Microsoft.Xna.Framework.Graphics.Texture2D texture2D;
            int width = texture2D.Width;
            DrPlatform.DrPlatformType currentPlatform = DrPlatform.CurrentPlatform;
            InterfaceProfile_Layout interfaceProfile_Layout = this.currentProfile;
            return;
        }
    }
References _optionsBlocker, CloseTemplateOptions(), DrPlatform.CurrentPlatform, currentProfile, displayTemplateOptions, Terraria.Localization.Language.GetTextValue(), j__TPar, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, RefreshTemplate(), System.text, and Microsoft.Xna.Framework.Graphics.Texture2D.Width.
Referenced by DrawUITweaks(), and DrawWidgetOverlays().