terraria-cpp2il-methodrecon: GUIInterfaceEdit.RestoreDefaults
RestoreDefaults()
void GUIInterfaceEdit.RestoreDefaults () inline
Definition at line 757 of file GUIInterfaceEdit.cs.
    {
        if (!true)
        {
        }
        VirtualControlsProfile_Layout virtualControlsProfile_Layout;
        VirtualControlsHardwareConfiguration_Layout virtualControlsHardwareConfiguration_Layout;
        virtualControlsProfile_Layout.HardwareConfig.Copy(virtualControlsHardwareConfiguration_Layout);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout2;
        virtualControlsProfile_Layout2.HardwareConfig.LoadControlPositions();
        VirtualControlsProfile_Layout virtualControlsProfile_Layout3;
        VirtualControlsSlotTypeMapping_Layout style = virtualControlsProfile_Layout3.HardwareConfig.Slots.Style;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout4;
        VirtualControlsHardwareConfigurationMapping_Layout.ContolType action = virtualControlsProfile_Layout4.Controls.Action;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout5;
        VirtualControlsBinding_Layout[] controls = virtualControlsProfile_Layout5.Controls;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout6;
        VirtualControlsBinding_Layout[] controls2 = virtualControlsProfile_Layout6.Controls;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout7;
        string slotId = virtualControlsProfile_Layout7.HardwareConfig.Slots.SlotId;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout8;
        VirtualControlsBinding_Layout[] controls3 = virtualControlsProfile_Layout8.Controls;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout9;
        VirtualControlsHardwareConfigurationMapping_Layout.ContolType defaultControl = virtualControlsProfile_Layout9.HardwareConfig.Slots.DefaultControl;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout10;
        VirtualControlsBinding_Layout[] controls4 = virtualControlsProfile_Layout10.Controls;
        if (controls4 == null)
        {
        }
        InterfaceStyles_Layout.Active.InvalidateMinResolution();
        InterfaceStyles_Layout.LoadUIResolution();
        if (controls4 == null)
        {
        }
        int num = 1;
        if (num == 0)
        {
        }
        int value = num.m_value;
        int num2 = 1;
        if (num2 == 0)
        {
        }
        int value2 = num2.m_value;
        this.ClearControlUndoRedo();
    }
References System.action, VirtualControlsBinding_Layout.Action, InterfaceStyles_Layout.Active, ClearControlUndoRedo(), VirtualControlsProfile_Layout.Controls, VirtualControlsHardwareConfiguration_Layout.Copy(), VirtualControlsHardwareConfigurationMapping_Layout.DefaultControl, VirtualControlsProfile_Layout.HardwareConfig, InterfaceProfile_Layout.InvalidateMinResolution(), j__TPar, VirtualControlsHardwareConfiguration_Layout.LoadControlPositions(), InterfaceStyles_Layout.LoadUIResolution(), VirtualControlsHardwareConfigurationMapping_Layout.SlotId, VirtualControlsHardwareConfiguration_Layout.Slots, and System.value.
Referenced by DrawControlsOptions(), and DrawSafeRegionOptions().