terraria-cpp2il-methodrecon: GUIInterfaceEdit.Backup
Backup()
void GUIInterfaceEdit.Backup () inline
Definition at line 640 of file GUIInterfaceEdit.cs.
    {
        VirtualControlsProfile_Layout virtualControlsProfile_Layout;
        this.BackupActiveProfile = virtualControlsProfile_Layout;
        VirtualControlsHardwareConfiguration_Layout backupHardware = this.BackupHardware1;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout2;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig = virtualControlsProfile_Layout2.HardwareConfig;
        backupHardware.Copy(hardwareConfig);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout3;
        this.BackupProfile1.Copy(virtualControlsProfile_Layout3);
        VirtualControlsHardwareConfiguration_Layout backupHardware2 = this.BackupHardware2;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout4;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig2 = virtualControlsProfile_Layout4.HardwareConfig;
        backupHardware2.Copy(hardwareConfig2);
        VirtualControlsProfile_Layout backupProfile = this.BackupProfile2;
        VirtualControlsHardwareConfiguration_Layout backupHardware3 = this.BackupHardware3;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout5;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig3 = virtualControlsProfile_Layout5.HardwareConfig;
        backupHardware3.Copy(hardwareConfig3);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout6;
        this.BackupProfile3.Copy(virtualControlsProfile_Layout6);
        VirtualControlsHardwareConfiguration_Layout backupHardware4 = this.BackupHardware4;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout7;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig4 = virtualControlsProfile_Layout7.HardwareConfig;
        backupHardware4.Copy(hardwareConfig4);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout8;
        this.BackupProfile4.Copy(virtualControlsProfile_Layout8);
        InterfaceProfile_Layout backupInterfaceProfile = this.BackupInterfaceProfile;
        InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
        long num = 0L;
        backupInterfaceProfile.Copy(active, num != 0L);
        InterfaceProfile_Layout backupInterfaceProfile2 = this.BackupInterfaceProfile;
        string profileName = InterfaceStyles_Layout.Active.ProfileName;
        backupInterfaceProfile2.ProfileName = profileName;
        this.AddControlUndo();
        Microsoft.Xna.Framework.Vector2 leftControls = ControlAnchor.LeftControls;
        Microsoft.Xna.Framework.Vector2 rightControls = ControlAnchor.RightControls;
        if (profileName == null)
        {
        }
    }
References InterfaceStyles_Layout.Active, AddControlUndo(), BackupHardware1, BackupHardware2, BackupHardware3, BackupHardware4, BackupInterfaceProfile, BackupProfile1, BackupProfile2, BackupProfile3, BackupProfile4, InterfaceProfile_Layout.Copy(), VirtualControlsHardwareConfiguration_Layout.Copy(), VirtualControlsProfile_Layout.Copy(), j__TPar, System.L, ControlAnchor.LeftControls, InterfaceProfile_Layout.ProfileName, and ControlAnchor.RightControls.