terraria-cpp2il-methodrecon: GUIInterfaceEdit.RestoreBackup
RestoreBackup()
void GUIInterfaceEdit.RestoreBackup () inline
Definition at line 805 of file GUIInterfaceEdit.cs.
    {
        VirtualControlsProfile_Layout backupProfile = this.BackupProfile1;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout;
        virtualControlsProfile_Layout.Copy(backupProfile);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout2;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig = virtualControlsProfile_Layout2.HardwareConfig;
        VirtualControlsHardwareConfiguration_Layout backupHardware = this.BackupHardware1;
        hardwareConfig.Copy(backupHardware);
        VirtualControlsProfile_Layout backupProfile2 = this.BackupProfile2;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout3;
        virtualControlsProfile_Layout3.Copy(backupProfile2);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout4;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig2 = virtualControlsProfile_Layout4.HardwareConfig;
        VirtualControlsHardwareConfiguration_Layout backupHardware2 = this.BackupHardware2;
        hardwareConfig2.Copy(backupHardware2);
        VirtualControlsProfile_Layout backupProfile3 = this.BackupProfile3;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout5;
        virtualControlsProfile_Layout5.Copy(backupProfile3);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout6;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig3 = virtualControlsProfile_Layout6.HardwareConfig;
        VirtualControlsHardwareConfiguration_Layout backupHardware3 = this.BackupHardware3;
        hardwareConfig3.Copy(backupHardware3);
        VirtualControlsProfile_Layout backupProfile4 = this.BackupProfile4;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout7;
        virtualControlsProfile_Layout7.Copy(backupProfile4);
        VirtualControlsProfile_Layout virtualControlsProfile_Layout8;
        VirtualControlsHardwareConfiguration_Layout hardwareConfig4 = virtualControlsProfile_Layout8.HardwareConfig;
        VirtualControlsHardwareConfiguration_Layout backupHardware4 = this.BackupHardware4;
        hardwareConfig4.Copy(backupHardware4);
        VirtualControlsProfile_Layout backupActiveProfile = this.BackupActiveProfile;
        VirtualControlsProfile_Layout virtualControlsProfile_Layout9;
        virtualControlsProfile_Layout9.HardwareConfig.LoadControlPositions();
        InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
        InterfaceProfile_Layout backupInterfaceProfile = this.BackupInterfaceProfile;
        long num = 0L;
        active.Copy(backupInterfaceProfile, num != 0L);
        InterfaceProfile_Layout active2 = InterfaceStyles_Layout.Active;
        string profileName = this.BackupInterfaceProfile.ProfileName;
        active2.ProfileName = profileName;
        if (profileName == null)
        {
        }
        float xmin = this.backupSafeRegion.m_XMin;
        float ymin = this.backupSafeRegion.m_YMin;
        float width = this.backupSafeRegion.m_Width;
        float height = this.backupSafeRegion.m_Height;
        bool flag = this.backupVPPIOverride;
        InterfaceStyles_Layout.Active.InvalidateMinResolution();
        InterfaceStyles_Layout.LoadUIResolution();
        if (this.backupVPPIOverride)
        {
            float num2 = this.backupVPPI;
        }
        this.ClearControlUndoRedo();
    }
References InterfaceStyles_Layout.Active, BackupActiveProfile, BackupHardware1, BackupHardware2, BackupHardware3, BackupHardware4, BackupInterfaceProfile, BackupProfile1, BackupProfile2, BackupProfile3, BackupProfile4, backupSafeRegion, backupVPPI, backupVPPIOverride, ClearControlUndoRedo(), InterfaceProfile_Layout.Copy(), VirtualControlsHardwareConfiguration_Layout.Copy(), VirtualControlsProfile_Layout.Copy(), VirtualControlsProfile_Layout.HardwareConfig, InterfaceProfile_Layout.InvalidateMinResolution(), j__TPar, System.L, VirtualControlsHardwareConfiguration_Layout.LoadControlPositions(), InterfaceStyles_Layout.LoadUIResolution(), UnityEngine.Rect.m_Height, UnityEngine.Rect.m_Width, UnityEngine.Rect.m_XMin, UnityEngine.Rect.m_YMin, and InterfaceProfile_Layout.ProfileName.
Referenced by CancelChanges().