terraria-cpp2il-methodrecon: GUIControllerRubbleMaker.GetSelectedItemRegion
GetSelectedItemRegion()
Rectangle GUIControllerRubbleMaker.GetSelectedItemRegion () inline
Implements GUIControllerItem.
Definition at line 60 of file GUIControllerRubbleMaker.cs.
    {
        bool flag;
        RubbleMakerUI_Layout instance5;
        do
        {
            Rectangle rectangle;
            ControlAnchor.SetMainMenuPageRegion(rectangle);
            if (!this.wasInFilterGrid)
            {
                this.wasInFilterGrid = true;
            }
            this.ClampMaterialGrid();
            if (this.inGrid)
            {
                this.ClampRubbleGrid();
            }
            RubbleMakerUI_Layout instance = RubbleMakerUI_Layout.Instance;
            ItemGrid_Layout materialOptions = instance.MaterialOptions;
            ItemGrid_Layout rubbleOptions = instance.RubbleOptions;
            RubbleMakerUI_Layout instance2 = RubbleMakerUI_Layout.Instance;
            float materialScale = instance2.MaterialScale;
            ControlAnchor.ControlId firstAnchorControl = materialOptions.FirstAnchorControl;
            Vector2 firstItemLocation = materialOptions.FirstItemLocation;
            float x = materialOptions.FirstItemLocation.X;
            float y = materialOptions.FirstItemLocation.Y;
            if (instance2 == null)
            {
            }
            float x2 = materialOptions.ExtraElementSpacing.X;
            int num = this.filterGridRow;
            int num2 = this.filterGridCol;
            if (this.inGrid)
            {
                RubbleMakerUI_Layout instance3 = RubbleMakerUI_Layout.Instance;
                ItemGrid_Layout rubbleOptions2 = instance3.RubbleOptions;
                ItemGrid_Layout rubbleOptions3 = instance3.RubbleOptions;
                RubbleMakerUI_Layout instance4 = RubbleMakerUI_Layout.Instance;
                float rubbleScale = instance4.RubbleScale;
                ControlAnchor.ControlId firstAnchorControl2 = rubbleOptions2.FirstAnchorControl;
                Vector2 firstItemLocation2 = rubbleOptions2.FirstItemLocation;
                float x3 = rubbleOptions2.FirstItemLocation.X;
                float y2 = rubbleOptions2.FirstItemLocation.Y;
                if (instance4 == null)
                {
                }
                float x4 = rubbleOptions2.ExtraElementSpacing.X;
                int num3 = this.gridRow;
                int num4 = this.gridCol;
                float y3 = rubbleOptions2.ExtraElementSpacing.Y;
            }
            flag = this.filterButton;
            instance5 = RubbleMakerUI_Layout.Instance;
        }
        while (!flag);
        Texture_Layout backingDisabled = instance5.MaterialToggle.BackingDisabled;
        Rectangle rectangle2;
        return rectangle2;
    }
References ClampMaterialGrid(), ClampRubbleGrid(), ItemGrid_Layout.ExtraElementSpacing, filterButton, filterGridCol, filterGridRow, gridCol, gridRow, inGrid, RubbleMakerUI_Layout.Instance, j__TPar, RubbleMakerUI_Layout.MaterialOptions, RubbleMakerUI_Layout.MaterialScale, RubbleMakerUI_Layout.RubbleOptions, RubbleMakerUI_Layout.RubbleScale, ControlAnchor.SetMainMenuPageRegion(), wasInFilterGrid, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.