terraria-cpp2il-methodrecon: GUIQuickActionButton.CanInteract
CanInteract()
static bool GUIQuickActionButton.CanInteract (Player player, Item item, Microsoft::Xna::Framework::Graphics::Texture2D iconTexture, Rectangle frame, bool useFrame) inline static private
Definition at line 213 of file GUIQuickActionButton.cs.
    {
        if (!true)
        {
        }
        bool gameMenu = Main.gameMenu;
        NPC mouseNPC = GUIQuickActionButton.GetMouseNPC();
        int myPlayer = Main.myPlayer;
        int tileTargetX = Player.tileTargetX;
        int tileTargetY = Player.tileTargetY;
        Tile tile;
        ushort type = tile.type;
        int tileTargetX2 = Player.tileTargetX;
        int tileTargetY2 = Player.tileTargetY;
        Tile tile2;
        ushort type2 = tile2.type;
        int tileTargetX3 = Player.tileTargetX;
        int tileTargetY3 = Player.tileTargetY;
        Tile tile3;
        short frameX = tile3.frameX;
        Tile tile4;
        short frameY = tile4.frameY;
        int num = 53;
        int num2 = 54;
        int num3 = TEWeaponsRack.Find(tileTargetX3, tileTargetY3);
        if (num == 0)
        {
        }
        int num7;
        if (num != 0)
        {
            if (num == 0)
            {
            }
            int signHover = Main.signHover;
            if (num == 0)
            {
            }
            int signHover2 = Main.signHover;
            if (num != 0 && num == 0)
            {
                if (num == 0)
                {
                }
                int signHover3 = Main.signHover;
                int signHover4 = Main.signHover;
                Tile tile5;
                ushort type3 = tile5.type;
            }
            int tileTargetX4 = Player.tileTargetX;
            int tileTargetY4 = Player.tileTargetY;
            bool flag = Minecart.CanSwitchTrack(tileTargetX4, tileTargetY4);
            if (num2 == 0)
            {
            }
            int tileTargetX5 = Player.tileTargetX;
            int tileTargetY5 = Player.tileTargetY;
            Tile tile6;
            ushort type4 = tile6.type;
            int tileTargetX6 = Player.tileTargetX;
            int tileTargetY6 = Player.tileTargetY;
            Tile tile7;
            short frameX2 = tile7.frameX;
            Tile tile8;
            short frameY2 = tile8.frameY;
            int num4 = 36409;
            int num5 = TEItemFrame.Find(tileTargetX6, tileTargetY6);
            if (num4 == 0)
            {
            }
            if (num5 != 0)
            {
            }
            if (num2 == 0)
            {
            }
            int tileTargetX7 = Player.tileTargetX;
            int tileTargetY7 = Player.tileTargetY;
            Tile tile9;
            ushort type5 = tile9.type;
            if (num2 == 0)
            {
            }
            int tileTargetX8 = Player.tileTargetX;
            int tileTargetY8 = Player.tileTargetY;
            Tile tile10;
            ushort type6 = tile10.type;
            int num6 = NPC.TypeToDefaultHeadIndex(num7);
        }
        int num8 = NPC.TypeToDefaultHeadIndex(num7);
        if (num2 == 0)
        {
        }
        int tileTargetX9 = Player.tileTargetX;
        int tileTargetY9 = Player.tileTargetY;
        Tile tile11;
        ushort type7 = tile11.type;
        float cursorScale = Main.cursorScale;
        string text = 1.ToString();
        Debug.LogError("Invalid icon type " + text);
        int signHover5 = Main.signHover;
        int signHover6 = Main.signHover;
        Tile tile12;
        ushort type8 = tile12.type;
        bool drawToolModeUI = WiresUI.Settings.DrawToolModeUI;
        WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
        int num9 = 56;
        int num10 = 48;
        if (num9 == 0)
        {
        }
        if (num9 == 0)
        {
        }
        if (num9 == 0)
        {
        }
        int signHover7 = Main.signHover;
        int signHover8 = Main.signHover;
        Tile tile13;
        short frameX3 = tile13.frameX;
        long num11 = 0L;
        if (num11 == 0L)
        {
        }
        if (num11 == 0L)
        {
        }
        if (num10 == 0)
        {
        }
        if (num11 == 0L || num10 == 0)
        {
        }
        int num12 = 1;
        if (num12 == 0)
        {
        }
        VirtualControllerInputState.Category itemCategory = VirtualControllerInputState.GetItemCategory(0);
        if (num12 != 0)
        {
        }
        if (num12 == 0)
        {
        }
        if (num12 == 0)
        {
        }
        if (num12 == 0)
        {
        }
        if (num12 == 0)
        {
        }
        while (num12 != 0)
        {
        }
        if (num12 == 0)
        {
        }
        throw new InvalidCastException();
    }
References Terraria.Minecart.CanSwitchTrack(), Terraria.Main.cursorScale, Terraria.GameContent.UI.WiresUI.Settings.DrawToolModeUI, Terraria.GameContent.Tile_Entities.TEItemFrame.Find(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.gameMenu, VirtualControllerInputState.GetItemCategory(), GetMouseNPC(), j__TPar, System.L, UnityEngine.Debug.LogError(), Terraria.Main.myPlayer, Terraria.Main.signHover, System.text, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Tile.type, and Terraria.NPC.TypeToDefaultHeadIndex().