terraria-cpp2il-methodrecon: InterfaceProfile_Layout.GetCategoryGrouping
GetCategoryGrouping()
GUIPageIconGrouping InterfaceProfile_Layout.GetCategoryGrouping (GUIPageIcons::Category category, bool includeOptions = true) inline
Definition at line 133 of file InterfaceProfile_Layout.cs.
    {
        /*
An exception occurred when decompiling this method (06000C1D)
ICSharpCode.Decompiler.DecompilerException: Error decompiling GUIPageIconGrouping InterfaceProfile_Layout::GetCategoryGrouping(GUIPageIcons/Category,System.Boolean)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:bool(var_0_06, call:bool(GUIPageIconGrouping::InteractionCategory, ldloc:Category(category)))
    stloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(var_1_0D, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(InterfaceProfile_Layout::LeftGroupings, ldloc:InterfaceProfile_Layout(this)))
    stloc:int32(var_2_14, ldfld:int32(List`1::_size, ldloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](var_1_0D)))
    stloc:object(var_4_1D, ldfld:object(List`1::_syncRoot, ldloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](var_1_0D)))
    stloc:int32(var_5_2A, ldfld:int32(List`1::_size, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](InterfaceProfile_Layout::LeftGroupings, ldloc:InterfaceProfile_Layout(this))))
    stloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(var_6_32, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(InterfaceProfile_Layout::RightGroupings, ldloc:InterfaceProfile_Layout(this)))
    stloc:int32(var_7_3B, ldfld:int32(List`1::_size, ldloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](var_6_32)))
    stloc:object(var_9_47, ldfld:object(List`1::_syncRoot, ldloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](var_6_32)))
    stloc:int32(var_10_54, ldfld:int32(List`1::_size, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](InterfaceProfile_Layout::RightGroupings, ldloc:InterfaceProfile_Layout(this))))
    stloc:int32(var_11_61, ldfld:int32(List`1::_size, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](InterfaceProfile_Layout::LeftGroupings, ldloc:InterfaceProfile_Layout(this))))
    stloc:int32(var_12_6E, ldfld:int32(List`1::_size, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](InterfaceProfile_Layout::LeftGroupings, ldloc:InterfaceProfile_Layout(this))))
    stloc:int32(var_13_7B, ldfld:int32(List`1::_size, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](InterfaceProfile_Layout::RightGroupings, ldloc:InterfaceProfile_Layout(this))))
    stloc:int32(var_15_8B, ldfld:int32(List`1::_size, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>[exp:List`1](InterfaceProfile_Layout::RightGroupings, ldloc:InterfaceProfile_Layout(this))))
    stloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(var_17_96, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(InterfaceProfile_Layout::LeftGroupings, ldloc:InterfaceProfile_Layout(this)))
    stloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(var_18_9E, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(InterfaceProfile_Layout::RightGroupings, ldloc:InterfaceProfile_Layout(this)))
    stloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(var_19_A6, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(InterfaceProfile_Layout::LeftGroupings, ldloc:InterfaceProfile_Layout(this)))
    stloc:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(var_20_AE, ldfld:class [mscorlib]System.Collections.Generic.List`1<class GUIPageIconGrouping>(InterfaceProfile_Layout::RightGroupings, ldloc:InterfaceProfile_Layout(this)))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
    }
Referenced by GUIResearch.Draw(), GUIResearch.IsOver(), and GUIBuilderAccToggles.IsOverBuilderTools().