terraria-cpp2il-methodrecon: nativefiledialog.NFD_SaveDialog
NFD_SaveDialog()
static unsafe nativefiledialog.nfdresult_t nativefiledialog.NFD_SaveDialog (string filterList, string defaultPath, [Out] string outPath) inline static
Definition at line 90 of file nativefiledialog.cs.
    {
        byte* ptr = nativefiledialog.Utf8EncodeNullable(filterList);
        IntPtr intPtr;
        Marshal.FreeHGlobal(intPtr);
        IntPtr intPtr2;
        Marshal.FreeHGlobal(intPtr2);
        string text = nativefiledialog.UTF8_ToManaged(intPtr2, true);
        nativefiledialog.nfdresult_t nfdresult_t;
        return nfdresult_t;
    }
References System.Runtime.InteropServices.Marshal.FreeHGlobal(), j__TPar, System.text, UTF8_ToManaged(), and Utf8EncodeNullable().