terraria-cpp2il-methodrecon: Terraria.Wiring.MassWireOperationInner
MassWireOperationInner()
static void Terraria.Wiring.MassWireOperationInner (Player user, Point ps, Point pe, Vector2 dropPoint, bool dir, int wireCount, int actuatorCount) inline static private
Definition at line 533 of file Wiring.cs.
        {
            if (!true)
            {
            }
            int num = Math.Sign(Math.Sign(0));
            WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
            Item.StartCachingType(530);
            Item.StartCachingType(849);
            bool value = Wiring.MassWireOperationStep(user, ps, toolMode, dir ? 1 : 0, wireCount).Value != null;
            bool value2 = Wiring.MassWireOperationStep(user, ps, toolMode, dir ? 1 : 0, wireCount).Value != null;
            if (!true)
            {
            }
        }
References j__TPar, Terraria.Wiring.MassWireOperationStep(), System.Math.Sign(), Terraria.Item.StartCachingType(), Terraria.GameContent.UI.WiresUI.Settings.ToolMode, and System.value.