terraria-cpp2il-methodrecon: Terraria.Wiring.ReActive
ReActive()
static void Terraria.Wiring.ReActive (int i, int j) inline static private
Definition at line 516 of file Wiring.cs.
        {
            if (!true)
            {
            }
            long num = 0L;
            Tile tile;
            tile.inActive(num != 0L);
            if (!true)
            {
            }
            long num2 = 0L;
            WorldGen.SquareTileFrame(i, j, num2 != 0L);
            bool logicHost = Main.LogicHost;
        }
References Terraria.Tile.inActive(), j__TPar, System.L, Terraria.Main.LogicHost, and Terraria.WorldGen.SquareTileFrame().
Referenced by Terraria.Wiring.Actuate(), and Terraria.Wiring.ActuateForced().