terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexNode.ReduceSet
ReduceSet()
RegexNode System.Text.RegularExpressions.RegexNode.ReduceSet () inline private
Definition at line 151 of file RegexNode.cs.
        {
            int num = 1;
            string str = this.Str;
            if (num == 0)
            {
            }
            bool flag = RegexCharClass.IsEmpty(str);
            int num2 = 22;
            this.NType = num2;
            string str2 = this.Str;
            if (num2 == 0)
            {
            }
            bool flag2 = RegexCharClass.IsSingleton(str2);
            char c = RegexCharClass.SingletonChar(this.Str);
            int ntype = this.NType;
            this.Ch = c;
            string str3 = this.Str;
            if (ntype == 0)
            {
            }
            char c2 = RegexCharClass.SingletonChar(str3);
            int ntype2 = this.NType;
            this.Ch = c2;
            this.NType = ntype2;
            return this;
        }
References System.Text.RegularExpressions.RegexCharClass.IsEmpty(), System.Text.RegularExpressions.RegexCharClass.IsSingleton(), j__TPar, System.Text.RegularExpressions.RegexNode.NType, System.Text.RegularExpressions.RegexCharClass.SingletonChar(), and System.Text.RegularExpressions.RegexNode.Str.