terraria-cpp2il-methodrecon: InControl.InputDevice.Commit
Commit()
void InControl.InputDevice.Commit (ulong updateTick, float deltaTime) inline inherited
Definition at line 1478 of file InputDevice.cs.
        {
            this.ProcessLeftStick(updateTick, deltaTime);
            this.ProcessRightStick(updateTick, deltaTime);
            this.ProcessDPad(updateTick, deltaTime);
            ReadOnlyCollection<InputControl> readOnlyCollection = this.<Controls>k__BackingField;
            if (this.<Controls>k__BackingField != null)
            {
            }
            InputControl[] array = this.<ControlsByTarget>k__BackingField;
            long num = 0L;
            InputControl inputControl = this.cachedCommand;
            if (inputControl != null)
            {
                inputControl.Passive = num != 0L;
                return;
            }
            InputControl inputControl2;
            this.cachedCommand = inputControl2;
            inputControl2.Passive = num != 0L;
            int num2;
            InputControl inputControl3;
            if (inputControl2 == null)
            {
                num2 = 300;
                this.cachedCommand = inputControl3;
            }
            inputControl3.CommitWithState(num2 != 0, updateTick, deltaTime);
            int num3 = 1;
            if (this.<Controls>k__BackingField != null && num == 0L)
            {
                this.<LastInputTick>k__BackingField = updateTick;
                this.<IsActive>k__BackingField = num3 != 0;
            }
        }
References System.array, InControl.InputDevice.cachedCommand, InControl.OneAxisInputControl.CommitWithState(), InControl.InputDevice.Controls, InControl.InputDevice.ControlsByTarget, InControl.InputDevice.IsActive, j__TPar, InControl.InputDevice.k__BackingField, InControl.L, InControl.InputDevice.LastInputTick, InControl.InputDevice.ProcessDPad(), InControl.InputDevice.ProcessLeftStick(), and InControl.InputDevice.ProcessRightStick().