terraria-cpp2il-methodrecon: InControl.InputDevice.CommitRightStick
CommitRightStick()
void InControl.InputDevice.CommitRightStick () inline inherited
Definition at line 662 of file InputDevice.cs.
        {
            InputControl control;
            if (this.cachedRightStickUp == null)
            {
                control = this.GetControl(InputControlType.RightStickUp);
                this.cachedRightStickUp = control;
            }
            control.Commit();
            InputControl control2;
            if (this.cachedRightStickDown == null)
            {
                control2 = this.GetControl(InputControlType.RightStickDown);
                this.cachedRightStickDown = control2;
            }
            control2.Commit();
            InputControl control3;
            if (this.cachedRightStickLeft == null)
            {
                control3 = this.GetControl(InputControlType.RightStickLeft);
                this.cachedRightStickLeft = control3;
            }
            control3.Commit();
            InputControl control4;
            if (this.cachedRightStickRight == null)
            {
                control4 = this.GetControl(InputControlType.RightStickRight);
                this.cachedRightStickRight = control4;
            }
            control4.Commit();
        }
References InControl.InputDevice.cachedRightStickDown, InControl.InputDevice.cachedRightStickLeft, InControl.InputDevice.cachedRightStickRight, InControl.InputDevice.cachedRightStickUp, InControl.OneAxisInputControl.Commit(), InControl.InputDevice.GetControl(), and j__TPar.
Referenced by InControl.TouchControl.CommitAnalog().