terraria-cpp2il-methodrecon: Telepathy.Client.ReceiveThreadFunction
ReceiveThreadFunction()
void Telepathy.Client.ReceiveThreadFunction (string ip, int port) inline private
Definition at line 79 of file Client.cs.
        {
            TcpClient tcpClient = this.client;
            if (tcpClient != null)
            {
                tcpClient.Connect(ip, port);
                if (this.client != null)
                {
                    TcpClient tcpClient2 = this.client;
                    bool noDelay = this.NoDelay;
                    tcpClient2.NoDelay = noDelay;
                    TcpClient tcpClient3 = this.client;
                    int sendTimeout = this.SendTimeout;
                    tcpClient3.SendTimeout = sendTimeout;
                    this.sendThread.Start();
                    TcpClient tcpClient4 = this.client;
                    ConcurrentQueue<Message> receiveQueue = this.receiveQueue;
                    int maxMessageSize = this.MaxMessageSize;
                    Common.ReceiveLoop(0, tcpClient4, receiveQueue, maxMessageSize);
                    Thread thread = this.sendThread;
                    if (thread != null)
                    {
                        thread.Interrupt();
                    }
                    TcpClient tcpClient5 = this.client;
                    if (tcpClient5 != null)
                    {
                        tcpClient5.Close();
                    }
                    return;
                }
            }
        }
References Telepathy.Client.client, System.Net.Sockets.TcpClient.Close(), System.Net.Sockets.TcpClient.Connect(), System.Threading.Thread.Interrupt(), j__TPar, Telepathy.Common.MaxMessageSize, Telepathy.Common.NoDelay, Telepathy.Common.ReceiveLoop(), Telepathy.Common.receiveQueue, Telepathy.Client.sendThread, Telepathy.Common.SendTimeout, and System.Threading.Thread.Start().