terraria-cpp2il-methodrecon: Telepathy.Client.Disconnect
Disconnect()
void Telepathy.Client.Disconnect () inline
Definition at line 180 of file Client.cs.
        {
            while (!this._Connecting)
            {
                TcpClient tcpClient = this.client;
                if (tcpClient != null)
                {
                    Socket clientSocket = tcpClient.m_ClientSocket;
                    if (clientSocket != null)
                    {
                        if (!clientSocket.is_connected)
{
                            return;
                        }
                        continue;
                    }
                }
                return;
            }
            if (this._Connecting)
            {
                Thread thread = this.receiveThread;
                if (thread != null)
                {
                    thread.Interrupt();
                }
                Thread thread2 = this.sendThread;
                if (thread2 != null)
                {
                    thread2.Interrupt();
                }
                TcpClient tcpClient2 = this.client;
                if (tcpClient2 != null)
                {
                    tcpClient2.Close();
                    return;
                }
            }
            else
            {
                TcpClient tcpClient3 = this.client;
                if (tcpClient3 != null)
                {
                    tcpClient3.Close();
                }
                Thread thread3 = this.receiveThread;
                if (thread3 != null)
                {
                    thread3.Join();
                }
                SafeQueue<byte[]> safeQueue = this.sendQueue;
                if (safeQueue != null)
                {
                    safeQueue.Clear();
                }
            }
            TcpClient tcpClient4 = this.client;
            if (tcpClient4 != null)
            {
                tcpClient4.Dispose();
                return;
            }
        }
References Telepathy.Client._Connecting, Telepathy.SafeQueue< T >.Clear(), Telepathy.Client.client, System.Net.Sockets.TcpClient.Close(), System.Net.Sockets.TcpClient.Dispose(), System.Threading.Thread.Interrupt(), j__TPar, System.Threading.Thread.Join(), Telepathy.Client.receiveThread, Telepathy.Client.sendQueue, and Telepathy.Client.sendThread.
Referenced by SaveSynchronisationClient.Close(), and SaveSynchronisationManager.Shutdown().