terraria-cpp2il-methodrecon: Telepathy.Client.Connect
Connect()
void Telepathy.Client.Connect (string ip, int port) inline
Definition at line 152 of file Client.cs.
        {
            for (;;)
            {
                Debug.Log("Connecting" + ip);
                if (this._Connecting)
                {
                    break;
                }
                TcpClient tcpClient = this.client;
                if (tcpClient == null)
                {
                    goto IL_0035;
                }
                Socket clientSocket = tcpClient.m_ClientSocket;
                if (clientSocket == null || !clientSocket.is_connected)
                {
                    goto IL_0035;
                }
            }
            return;
            IL_0035:
            this._Connecting = true;
            this.sendQueue.Clear();
            this.receiveThread.Start();
        }
References Telepathy.Client._Connecting, Telepathy.SafeQueue< T >.Clear(), Telepathy.Client.client, j__TPar, UnityEngine.Debug.Log(), Telepathy.Client.receiveThread, Telepathy.Client.sendQueue, and System.Threading.Thread.Start().
Referenced by SaveSynchronisationManager.Connect(), and SaveSynchronisationClient.Connect().