terraria-cpp2il-methodrecon: System.ThrowHelper.ThrowArgumentOutOfRangeException
ThrowArgumentOutOfRangeException() [1/3]
static void System.ThrowHelper.ThrowArgumentOutOfRangeException () inline static package
Definition at line 133 of file ThrowHelper.cs.
        {
            /*
An exception occurred when decompiling this method (06000BA7)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void System.ThrowHelper::ThrowArgumentOutOfRangeException()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:Exception(var_0_05, call:Exception(ThrowHelper::CreateArgumentOutOfRangeException))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by System.Memory< T >.Memory(), System.ReadOnlyMemory< T >.ReadOnlyMemory(), System.ReadOnlySpan< T >.ReadOnlySpan(), System.ReadOnlySpan< T >.ReadOnlySpan(), System.Span< T >.Span(), System.Span< T >.Span(), System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Append(), System.Text.StringBuilder.AppendCore(), System.Net.IPAddressParser.AppendSections(), System.Text.ValueStringBuilder.AppendSlow(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.Net.Sockets.Socket.BeginSendCallback(), System.Text.ValueUtf8Converter.ConvertAndTerminateString(), System.Guid.EatAllWhitespace(), System.DateTimeFormat.Format(), System.Numerics.BigNumber.FormatBigIntegerToHex(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Globalization.CompareInfo.GetIgnoreCaseHash(), System.Text.RegularExpressions.Capture.GetLeftSubstring(), System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes(), System.Text.ValueStringBuilder.Insert(), System.__DTString.MatchSpecifiedWords(), System.DateTimeParse.MatchTimeMark(), System.DateTimeParse.MatchWord(), System.IPv6AddressHelper.ParseCanonicalName(), System.IPv4AddressHelper.ParseCanonicalName(), System.IO.UnmanagedMemoryStream.Read(), System.IO.StreamReader.Read(), System.Net.Sockets.NetworkStream.ReadAsync(), System.IO.StreamReader.ReadSpan(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.ReceiveFrom(), System.__DTString.RemoveTrailingInQuoteSpaces(), System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), System.Convert.ToBase64String(), System.Globalization.DateTimeFormatInfo.Tokenize(), System.IO.Enumeration.FileSystemEntry.ToSpecifiedFullPath(), System.Text.ValueStringBuilder.ToString(), System.Guid.ToString(), System.__DTString.TrimTail(), System.Text.ValueStringBuilder.TryCopyTo(), System.Convert.TryFromBase64Chars(), System.Guid.TryParseGuidWithHexPrefix(), System.Security.Cryptography.DSA.TrySignData(), System.Security.Cryptography.RSA.TrySignData(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.RSA.VerifyData(), System.IO.UnmanagedMemoryStream.Write(), System.IO.StreamWriter.Write(), and System.Net.Sockets.NetworkStream.WriteAsync().