terraria-cpp2il-methodrecon: System.ThrowHelper.ThrowArgumentOutOfRangeException
ThrowArgumentOutOfRangeException() [3/3]
static void System.ThrowHelper.ThrowArgumentOutOfRangeException (ExceptionArgument argument, ExceptionResource resource) inline static package
Definition at line 284 of file ThrowHelper.cs.
        {
            string argumentName = ThrowHelper.GetArgumentName(argument);
            string resourceString = Environment.GetResourceString(ThrowHelper.GetResourceName(resource));
        }
References System.ThrowHelper.GetArgumentName(), System.ThrowHelper.GetResourceName(), System.Environment.GetResourceString(), and j__TPar.