terraria-cpp2il-methodrecon: System.ThrowHelper.ThrowNotSupportedException
ThrowNotSupportedException() [1/2]
static void System.ThrowHelper.ThrowNotSupportedException () inline static package
Definition at line 193 of file ThrowHelper.cs.
        {
            /*
An exception occurred when decompiling this method (06000BAB)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void System.ThrowHelper::ThrowNotSupportedException()
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:Exception(var_0_05, call:Exception(ThrowHelper::CreateThrowNotSupportedException))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by System.Collections.ObjectModel.ReadOnlyCollection< T >.Add(), System.ArraySegment< T >.Add(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Add(), System.ArraySegment< T >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Clear(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Clear(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Insert(), System.ArraySegment< T >.Insert(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Insert(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Remove(), System.ArraySegment< T >.RemoveAt(), and System.Collections.ObjectModel.ReadOnlyCollection< T >.RemoveAt().