terraria-cpp2il-methodrecon: GUIBuilderAccToggles.Draw
Draw()
void GUIBuilderAccToggles.Draw () inline
Definition at line 86 of file GUIBuilderAccToggles.cs.
    {
        if (this.Enabled)
        {
            Rectangle region = this.GetRegion();
            TransactionButton_Layout transactionButton_Layout;
            Rectangle region2 = GUITransactionButton.GetRegion(transactionButton_Layout);
            bool useCollpasedCoinsAmmo = RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo;
            float x = transactionButton_Layout.Location.X;
            transactionButton_Layout.Location.X = x;
            this.Close();
            return;
        }
        bool useCollpasedCoinsAmmo2 = RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo;
        int myPlayer = Main.myPlayer;
        BuilderAccToggles_Layout instance = BuilderAccToggles_Layout.Instance;
        bool enabled = this.Enabled;
        if (this.Enabled)
        {
        }
        bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
    }
References Controller.ControllerActionManager.AnyControllerConnected, Close(), Enabled, GetRegion(), GUITransactionButton.GetRegion(), BuilderAccToggles_Layout.Instance, j__TPar, Terraria.Main.myPlayer, and RightSideHUDAnchorUpdator.UseCollpasedCoinsAmmo.