terraria-cpp2il-methodrecon: GUIBuilderAccToggles.IsOverBuilderTools
IsOverBuilderTools()
bool GUIBuilderAccToggles.IsOverBuilderTools (Vector2 position) inline private
Definition at line 229 of file GUIBuilderAccToggles.cs.
    {
        if (this.Enabled)
        {
            BuilderAccToggles_Layout instance = BuilderAccToggles_Layout.Instance;
            Rectangle pageGroupRegion = ControlAnchor.PageGroupRegion;
            Rectangle pageContentRegion = ControlAnchor.PageContentRegion;
            GUIPageIconGrouping categoryGrouping = InterfaceStyles_Layout.Active.GetCategoryGrouping(GUIPageIcons.Category.Inventory, 16777216 != 0);
            categoryGrouping.LoadPageAnchor();
            Rectangle region = this.GetRegion();
            ControlAnchor.PageGroupRegion = pageGroupRegion;
            ControlAnchor.PageContentRegion = pageContentRegion;
        }
        bool flag;
        return flag;
    }
References InterfaceStyles_Layout.Active, Enabled, InterfaceProfile_Layout.GetCategoryGrouping(), GetRegion(), BuilderAccToggles_Layout.Instance, j__TPar, GUIPageIconGrouping.LoadPageAnchor(), ControlAnchor.PageContentRegion, and ControlAnchor.PageGroupRegion.