terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexCharClass.ToStringClass
ToStringClass()
string System.Text.RegularExpressions.RegexCharClass.ToStringClass () inline
Definition at line 281 of file RegexCharClass.cs.
        {
            if (!this._canonical)
            {
                this.Canonicalize();
            }
            List<RegexCharClass.SingleRange> rangelist = this._rangelist;
            StringBuilder categories = this._categories;
            int size = rangelist._size;
            StringBuilder stringBuilder = StringBuilderCache.Acquire(categories.Length);
            bool negate = this._negate;
            StringBuilder stringBuilder2 = stringBuilder.Append(negate ? '\u0001' : '\0');
            StringBuilder stringBuilder3 = stringBuilder.Append(negate ? '\u0001' : '\0');
            int length = this._categories.Length;
            StringBuilder stringBuilder4 = stringBuilder.Append((char)length);
            int size2 = this._rangelist._size;
            long num = 0L;
            int size3 = this._rangelist._size;
            int length2 = stringBuilder.Length;
            int num2 = 1;
            stringBuilder[num2] = (char)num;
            StringBuilder categories2 = this._categories;
            StringBuilder stringBuilder5 = stringBuilder.Append(categories2);
            RegexCharClass subtractor = this._subtractor;
            if (subtractor != null)
            {
                string text = subtractor.ToStringClass();
                StringBuilder stringBuilder6 = stringBuilder.Append(text);
            }
            return StringBuilderCache.GetStringAndRelease(stringBuilder);
        }
References System.Text.RegularExpressions.RegexCharClass._canonical, System.Text.RegularExpressions.RegexCharClass._categories, System.Text.RegularExpressions.RegexCharClass._negate, System.Text.RegularExpressions.RegexCharClass._rangelist, System.Text.RegularExpressions.RegexCharClass._subtractor, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Text.RegularExpressions.RegexCharClass.Canonicalize(), System.Text.StringBuilderCache.GetStringAndRelease(), j__TPar, System.L, System.length, System.Text.StringBuilder.Length, System.text, and System.Text.RegularExpressions.RegexCharClass.ToStringClass().
Referenced by System.Text.RegularExpressions.RegexFC.GetFirstChars(), System.Text.RegularExpressions.RegexParser.ScanRegex(), and System.Text.RegularExpressions.RegexCharClass.ToStringClass().