terraria-cpp2il-methodrecon: Terraria.Localization.LanguageManager.SetLanguage
SetLanguage() [1/3]
void Terraria.Localization.LanguageManager.SetLanguage (GameCulture culture) inline
Definition at line 174 of file LanguageManager.cs.
        {
            if (this.intialLoadDone)
            {
                GameCulture gameCulture = this.<ActiveCulture>k__BackingField;
                GameCulture fallbackCulture = this._fallbackCulture;
                this.SetAllTextValuesToKeys();
                GameCulture fallbackCulture2 = this._fallbackCulture;
                this.LoadLanguage(fallbackCulture2, true);
                this.LoadLanguage(culture, true);
                this.<ActiveCulture>k__BackingField = culture;
                Thread currentThread = Thread.CurrentThread;
                CultureInfo cultureInfo = culture.CultureInfo;
                currentThread.CurrentCulture = cultureInfo;
                Thread currentThread2 = Thread.CurrentThread;
                CultureInfo cultureInfo2 = culture.CultureInfo;
                currentThread2.CurrentUICulture = cultureInfo2;
                LanguageChangeCallback onLanguageChanged = this.OnLanguageChanged;
                if (onLanguageChanged != null)
                {
                    IntPtr invoke_impl = onLanguageChanged.invoke_impl;
                    IntPtr method_code = onLanguageChanged.method_code;
                    IntPtr method = onLanguageChanged.method;
                }
                if (onLanguageChanged == null)
                {
                    return;
                }
            }
            else
            {
                this.delayedActiveCulture = culture;
            }
        }
References System.Globalization.CultureInfo.CultureInfo(), Terraria.Localization.LanguageManager._fallbackCulture, Terraria.Localization.LanguageManager.ActiveCulture, System.culture, System.Threading.Thread.CurrentThread, Terraria.Localization.LanguageManager.intialLoadDone, j__TPar, Terraria.Localization.LanguageManager.k__BackingField, Terraria.Localization.LanguageManager.LoadLanguage(), Terraria.Localization.LanguageManager.OnLanguageChanged, and Terraria.Localization.LanguageManager.SetAllTextValuesToKeys().