terraria-cpp2il-methodrecon: Terraria.Localization.LanguageManager.LoadLanguage
LoadLanguage()
void Terraria.Localization.LanguageManager.LoadLanguage (GameCulture culture, bool processCopyCommands = true) inline private
Definition at line 210 of file LanguageManager.cs.
        {
            this.LoadFilesForCulture(culture);
            LanguageChangeCallback onLanguageChanging = this.OnLanguageChanging;
            if (onLanguageChanging != null)
            {
                IntPtr invoke_impl = onLanguageChanging.invoke_impl;
                IntPtr method_code = onLanguageChanging.method_code;
                IntPtr method = onLanguageChanging.method;
            }
            this.ProcessCopyCommandsInTexts();
            ChatInitializer.PrepareAliases();
        }
References j__TPar, Terraria.Localization.LanguageManager.LoadFilesForCulture(), Terraria.Localization.LanguageManager.OnLanguageChanging, Terraria.Initializers.ChatInitializer.PrepareAliases(), and Terraria.Localization.LanguageManager.ProcessCopyCommandsInTexts().
Referenced by Terraria.Localization.LanguageManager.SetLanguage().