terraria-cpp2il-methodrecon: System.Security.Cryptography.SHA512Managed.SHATransform
SHATransform()
static unsafe void System.Security.Cryptography.SHA512Managed.SHATransform (ulong * expandedBuffer, ulong * state, byte * block) inline static private
Definition at line 106 of file SHA512Managed.cs.
        {
            int num = 1;
            ulong value = state->m_value;
            if (num == 0)
            {
            }
            int num2 = 16;
            Utils.QuadWordFromBigEndian(expandedBuffer, num2, block);
            if (num == 0)
            {
            }
            SHA512Managed.SHA512Expand(expandedBuffer);
            if (num == 0)
            {
            }
            ulong num3 = SHA512Managed.Sigma_1((ulong)42184584L);
            ulong num4 = SHA512Managed.Sigma_0(value);
            ulong num5 = SHA512Managed.Sigma_0(SHA512Managed.Sigma_1(state));
            ulong num7;
            ulong num6 = SHA512Managed.Sigma_1(SHA512Managed.Sigma_0(SHA512Managed.Sigma_1(SHA512Managed.Sigma_0(num7))));
            ulong num8 = SHA512Managed.Sigma_0(value);
            ulong num9 = SHA512Managed.Sigma_0(SHA512Managed.Sigma_1(state));
            ulong num11;
            ulong num10 = SHA512Managed.Sigma_0(SHA512Managed.Sigma_1(SHA512Managed.Sigma_0(num11)));
        }
References j__TPar, System.L, System.Security.Cryptography.Utils.QuadWordFromBigEndian(), System.Security.Cryptography.SHA512Managed.SHA512Expand(), System.Security.Cryptography.SHA512Managed.Sigma_0(), System.Security.Cryptography.SHA512Managed.Sigma_1(), System.state, and System.value.