terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Rectangle.Intersects
Intersects() [2/2]
void Microsoft.Xna.Framework.Rectangle.Intersects (Rectangle value, [Out] bool result) inline
Definition at line 263 of file Rectangle.cs.
        {
            int width = this.Width;
            int width2 = value.Width;
            int y = this.Y;
            int height = this.Height;
            int y2 = value.Y;
            int height2 = value.Height;
        }
References Microsoft.Xna.Framework.Rectangle.Height, j__TPar, System.value, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.NPC.AddIntoPlayersTownNPCSlots(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_032(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_185_LifeDrain(), Terraria.NPC.CheckActive(), Terraria.Player.CollideWithNPCs(), Terraria.Main.DrawProj(), Terraria.NPC.GetMeleeCollisionData(), Terraria.Item.GetPickedUpByMonsters_Special(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.JumpMovement(), and Terraria.GameContent.Drawing.WindGrid.ScanPlayer().