terraria-cpp2il-methodrecon: Terraria.Tile_PC.SmoothSlope
SmoothSlope()
static void Terraria.Tile_PC.SmoothSlope (int x, int y, bool applyToNeighbors = true, bool sync = false) inline static
Definition at line 873 of file Tile_PC.cs.
        {
            int num = 1;
            long num2 = 0L;
            Tile_PC.SmoothSlope(0, y, num2 != 0L, applyToNeighbors);
            long num3 = 0L;
            Tile_PC.SmoothSlope(0, y, num3 != 0L, applyToNeighbors);
            long num4 = 0L;
            Tile_PC.SmoothSlope(x, y, num4 != 0L, applyToNeighbors);
            long num5 = 0L;
            Tile_PC.SmoothSlope(x, y, num5 != 0L, applyToNeighbors);
            if (num == 0)
            {
            }
            bool flag = WorldGen.CanPoundTile(x, y);
            bool flag2 = WorldGen.SolidOrSlopedTile(x, y);
            bool flag3 = WorldGen.TileEmpty(x, 0);
            bool flag4 = WorldGen.SolidOrSlopedTile(x, 0);
            bool flag5 = WorldGen.SolidOrSlopedTile(WorldGen.SolidOrSlopedTile(WorldGen.SolidOrSlopedTile(x, 0) ? 1 : 0, y) ? 1 : 0, y);
        }
References Terraria.WorldGen.CanPoundTile(), j__TPar, System.L, Terraria.Tile_PC.SmoothSlope(), Terraria.WorldGen.SolidOrSlopedTile(), and Terraria.WorldGen.TileEmpty().
Referenced by Terraria.Tile_PC.SmoothSlope().