terraria-cpp2il-methodrecon: Mono.Net.Security.MonoTlsProviderFactory.InitializeProviderRegistration
InitializeProviderRegistration()
static void Mono.Net.Security.MonoTlsProviderFactory.InitializeProviderRegistration () inline static private
Definition at line 82 of file MonoTlsProviderFactory.cs.
        {
            if ("<?xml version=\"" == null)
            {
            }
            if ("<?xml version=\"" == null)
            {
            }
            if ("<?xml version=\"" == null)
            {
            }
            Mono.Unity.UnityTls.unitytls_interface_struct nativeInterface = Mono.Unity.UnityTls.NativeInterface;
            if (nativeInterface != null)
            {
                if ("<?xml version=\"" == null)
                {
                }
                MonoTlsProviderFactory.PopulateUnityProviders();
                return;
            }
            if ("<?xml version=\"" == null)
            {
            }
            MonoTlsProviderFactory.PopulateProviders();
            long num = 0L;
            if (nativeInterface != null)
            {
            }
            if (num == 0L)
            {
                return;
            }
            throw new OutOfMemoryException();
        }
References j__TPar, System.L, Mono.Unity.UnityTls.NativeInterface, Mono.Net.Security.MonoTlsProviderFactory.PopulateProviders(), and Mono.Net.Security.MonoTlsProviderFactory.PopulateUnityProviders().
Referenced by Mono.Net.Security.MonoTlsProviderFactory.InitializeInternal(), and Mono.Net.Security.MonoTlsProviderFactory.LookupProvider().