terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Graphics.Color.ToVector3
ToVector3()
Vector3 Microsoft.Xna.Framework.Graphics.Color.ToVector3 () inline
Definition at line 362 of file Color.cs.
        {
            byte r = this.R;
            byte g = this.G;
            byte b = this.B;
            return 17279;
        }
References Microsoft.Xna.Framework.Graphics.Color.B, Microsoft.Xna.Framework.Graphics.Color.G, and Microsoft.Xna.Framework.Graphics.Color.R.
Referenced by Terraria.Projectile.AI_001(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_156_BatOfLight(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), and Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.GetLight().