terraria-cpp2il-methodrecon: Mono.Security.X509.X509Crl.VerifySignature
VerifySignature() [4/4]
bool Mono.Security.X509.X509Crl.VerifySignature (X509Certificate x509) inline
Definition at line 270 of file X509Crl.cs.
        {
            while (x509 == null)
            {
            }
            int num = x509.version;
            if (x509.extensions["2.5.29.19"] != null)
            {
            }
            long num2 = 0L;
            if (x509.extensions["2.5.29.15"] == null || num2 != 0L)
            {
                string text = this.issuer;
            }
            bool flag = this.signatureOID == "1.2.840.10040.4.3";
            DSA dsa = x509.DSA;
            return this.VerifySignature(dsa);
        }
References System.Security.Cryptography.DSA.DSA(), Mono.Security.X509.X509Crl.issuer, j__TPar, System.L, System.text, and Mono.Security.X509.X509Crl.VerifySignature().
Referenced by System.Security.Cryptography.X509Certificates.X509ChainImplMono.CheckRevocation(), and Mono.Security.X509.X509Crl.VerifySignature().