terraria-cpp2il-methodrecon: System.Runtime.Remoting.Messaging.MethodCall.MethodCall
MethodCall() [2/3]
System.Runtime.Remoting.Messaging.MethodCall.MethodCall (CADMethodCallMessage msg) inline package
Definition at line 25 of file MethodCall.cs.
        {
            string text = string.Copy(msg._uri);
            this._uri = text;
            ArrayList arguments = msg.GetArguments();
            object[] args = msg._args;
            object[] array;
            this._args = array;
            LogicalCallContext logicalCallContext = msg.GetLogicalCallContext(arguments);
            this._callContext = logicalCallContext;
            if (logicalCallContext == null)
            {
            }
            MethodBase method = msg.GetMethod();
            this._methodBase = method;
            int propertyCount = msg._propertyCount;
            int propertyCount2 = msg._propertyCount;
        }
References System.Runtime.Remoting.Messaging.CADMessageBase._args, System.Runtime.Remoting.Messaging.CADMessageBase._propertyCount, System.Runtime.Remoting.Messaging.CADMethodCallMessage._uri, System.array, System.Runtime.Remoting.Messaging.CADMethodCallMessage.GetArguments(), System.Runtime.Remoting.Messaging.CADMessageBase.GetLogicalCallContext(), System.Runtime.Remoting.Messaging.CADMessageBase.GetMethod(), j__TPar, and System.text.