terraria-cpp2il-methodrecon: System.Net.ResponseStream.GetHeaders
GetHeaders()
MemoryStream System.Net.ResponseStream.GetHeaders (bool closing) inline private
Definition at line 123 of file ResponseStream.cs.
        {
            object headers_lock = this.response.headers_lock;
            Monitor.Enter(headers_lock, closing);
            if (this.response.HeadersSent)
            {
            }
            HttpListenerResponse httpListenerResponse = this.response;
            long num = 0L;
            Monitor.Exit(headers_lock);
            if (num == 0L)
            {
            }
            throw new OutOfMemoryException();
        }
References System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Net.HttpListenerResponse.headers_lock, System.Net.HttpListenerResponse.HeadersSent, j__TPar, System.L, and System.Net.ResponseStream.response.
Referenced by System.Net.ResponseStream.Close().