terraria-cpp2il-methodrecon: System.Net.ResponseStream.Close
Close()
override void System.Net.ResponseStream.Close () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 77 of file ResponseStream.cs.
        {
            if (this.disposed)
            {
                return;
            }
            int num = 1;
            int num2 = 1;
            this.disposed = num != 0;
            MemoryStream headers = this.GetHeaders(num2 != 0);
            Stream stream = this.stream;
            bool chunked = this.response.chunked;
            if (headers != null)
            {
                if (chunked)
                {
                    bool flag = this.trailer_sent;
                    if (!flag)
                    {
                        if (!flag)
{
                        }
                        int num3 = 1;
                        byte[] chunkSizeBytes = ResponseStream.GetChunkSizeBytes(0, num3 != 0);
                    }
                }
                int num4 = 1;
                this.trailer_sent = num4 != 0;
                this.response.Close();
                return;
            }
            while (!chunked)
            {
            }
            bool flag2 = this.trailer_sent;
            while (flag2)
            {
            }
            if (!flag2)
            {
            }
            int num5 = 1;
            byte[] chunkSizeBytes2 = ResponseStream.GetChunkSizeBytes(0, num5 != 0);
        }
References System.Net.HttpListenerResponse.chunked, System.Net.HttpListenerResponse.Close(), System.Net.ResponseStream.disposed, System.Net.ResponseStream.GetChunkSizeBytes(), System.Net.ResponseStream.GetHeaders(), j__TPar, System.Net.ResponseStream.response, System.Net.ResponseStream.stream, and System.Net.ResponseStream.trailer_sent.