terraria-cpp2il-methodrecon: Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.AttemptPushingChange
AttemptPushingChange()
void Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.AttemptPushingChange () inline inherited
Definition at line 1166 of file CreativePowers.cs.
            {
                bool needsToCommitChange = this._needsToCommitChange;
                if (needsToCommitChange)
                {
                    if (!needsToCommitChange)
                    {
                    }
                    DateTime utcNow = DateTime.UtcNow;
                    DateTime nextTimeWeCanPush = this._nextTimeWeCanPush;
                    int num = utcNow.CompareTo(nextTimeWeCanPush);
                    float currentTargetValue = this._currentTargetValue;
                    this._sliderCurrentValueCache = currentTargetValue;
                    if (currentTargetValue == null)
                    {
                    }
                    DateTime utcNow2 = DateTime.UtcNow;
                    this._nextTimeWeCanPush = utcNow2;
                    ushort num2 = this.<PowerId>k__BackingField;
                    if (currentTargetValue == null)
                    {
                    }
                    BinaryWriter writer = NetCreativePowersModule.PreparePacket(num2, 4).Writer;
                    float currentTargetValue2 = this._currentTargetValue;
                }
            }
References Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower._currentTargetValue, Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower._needsToCommitChange, Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower._nextTimeWeCanPush, System.DateTime.CompareTo(), j__TPar, Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.k__BackingField, Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.PowerId, Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket(), System.DateTime.UtcNow, and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.categoryButton_OnUpdate().