terraria-cpp2il-methodrecon: Android_UserManager.Update
Update()
static void Android_UserManager.Update () inline static
Definition at line 150 of file Android_UserManager.cs.
    {
        if (true)
        {
            Debug.Log("Attempting player sign in");
            Android_UserManager.AttemptSignIn();
            bool isEditor = Application.isEditor;
            DateTime now = DateTime.Now;
            TimeSpan timeSpan;
            double totalSeconds = timeSpan.TotalSeconds;
            float editorSignInProcessTimeout = Android_UserManager.EditorSignInProcessTimeout;
            bool editorSignedIn = Android_UserManager.EditorSignedIn;
            return;
        }
    }
References AttemptSignIn(), EditorSignedIn, EditorSignInProcessTimeout, UnityEngine.Application.isEditor, j__TPar, UnityEngine.Debug.Log(), System.DateTime.Now, and System.TimeSpan.TotalSeconds.
Referenced by DrPlatform.Android.Update().