terraria-cpp2il-methodrecon: Android_UserManager.playerAuthenticated
playerAuthenticated()
static void Android_UserManager.playerAuthenticated () inline static private
Definition at line 180 of file Android_UserManager.cs.
    {
        bool isEditor = Application.isEditor;
        if (!true)
        {
        }
        bool editorSignedIn = Android_UserManager.EditorSignedIn;
        if (!true)
        {
        }
        string editorUserId = Android_UserManager.EditorUserId;
        string editorUserId2 = Android_UserManager.EditorUserId;
        string editorUserAlias = Android_UserManager.EditorUserAlias;
        PlayerPrefs.Save();
        DrPlatform.User.OnPlatformUserChanged();
        PlayerPrefs.Save();
    }
References EditorSignedIn, EditorUserAlias, EditorUserId, UnityEngine.Application.isEditor, j__TPar, DrPlatform.User.OnPlatformUserChanged(), and UnityEngine.PlayerPrefs.Save().
Referenced by _authenticationSucceededEvent().