terraria-cpp2il-methodrecon: System.Xml.Schema.XmlUntypedConverter.ChangeType
ChangeType() [9/9]
override object System.Xml.Schema.XmlUntypedConverter.ChangeType (string value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 436 of file XmlUntypedConverter.cs.
        {
            if (value != null)
            {
                if (!true)
                {
                }
                if (!true)
                {
                }
                Type clrTypeDefault = this.clrTypeDefault;
                bool flag = XmlConvert.ToBoolean(value);
                byte b = XmlBaseConverter.Int32ToByte(XmlConvert.ToInt32(value));
                int num2;
                short num = XmlBaseConverter.Int32ToInt16(num2);
                int num3;
                sbyte b2 = XmlBaseConverter.Int32ToSByte(num3);
                int num5;
                ushort num4 = XmlBaseConverter.Int32ToUInt16(num5);
                long num7;
                uint num6 = XmlBaseConverter.Int64ToUInt32(num7);
                decimal num9;
                ulong num8 = XmlBaseConverter.DecimalToUInt64(num9);
                XmlSchemaType schemaType = this.schemaType;
                object obj;
                return obj;
            }
            return "value";
        }
References System.Xml.Schema.XmlBaseConverter.clrTypeDefault, System.Xml.Schema.XmlBaseConverter.DecimalToUInt64(), System.Xml.Schema.XmlBaseConverter.Int32ToByte(), System.Xml.Schema.XmlBaseConverter.Int32ToInt16(), System.Xml.Schema.XmlBaseConverter.Int32ToSByte(), System.Xml.Schema.XmlBaseConverter.Int32ToUInt16(), System.Xml.Schema.XmlBaseConverter.Int64ToUInt32(), j__TPar, System.obj, System.Xml.Schema.XmlBaseConverter.schemaType, System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToInt32(), and System.value.