terraria-cpp2il-methodrecon: InControl.InControlInputModule.Process
Process()
override void InControl.InControlInputModule.Process () inline
Definition at line 127 of file InControlInputModule.cs.
        {
            bool flag = this.SendUpdateEventToSelectedObject();
            if (this.m_EventSystem.m_sendNavigationEvents)
            {
                bool flag2 = this.SendVectorEventToSelectedObject();
                bool flag3 = this.SendButtonEventToSelectedObject();
            }
            if (this.allowTouchInput)
            {
                bool flag4 = this.ProcessTouchEvents();
            }
            if (this.allowMouseInput)
            {
                long num = 0L;
                this.ProcessMouseEvent((int)num);
                return;
            }
        }
References InControl.InControlInputModule.allowMouseInput, InControl.InControlInputModule.allowTouchInput, j__TPar, InControl.L, UnityEngine.EventSystems.BaseInputModule.m_EventSystem, UnityEngine.EventSystems.EventSystem.m_sendNavigationEvents, InControl.InControlInputModule.ProcessMouseEvent(), InControl.InControlInputModule.ProcessTouchEvents(), InControl.InControlInputModule.SendButtonEventToSelectedObject(), InControl.InControlInputModule.SendUpdateEventToSelectedObject(), and InControl.InControlInputModule.SendVectorEventToSelectedObject().