terraria-cpp2il-methodrecon: GUIControllerMappingEntry.Draw
Draw()
override void GUIControllerMappingEntry.Draw () inline virtual
Reimplemented from GUISettingEntry.
Definition at line 110 of file GUIControllerMappingEntry.cs.
    {
        bool flag = this.displayOptions;
        if (flag && !this.drawingOverlay)
        {
            Rectangle gridItemRegion = ControlAnchor._gridItemRegion;
            return;
        }
        if (this._optionsBlocker != null)
        {
        }
        bool flag2;
        if (flag)
        {
            flag2 = this.displayOptions;
        }
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            if (!flag2)
            {
            }
            return;
        }
        string title = this.GetTitle();
        if (this.displayOptions)
        {
            int num = 1;
            GUITransactionButton.InputState inputState2;
            if (inputState2 != GUITransactionButton.InputState.Clicked || num == 0)
            {
            }
            GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
            if (this.displayOptions)
            {
                ControllerDevice controllerDevice;
                if (controllerDevice == null)
                {
                    goto IL_0243;
                }
                if (this.vector != null)
                {
                    return;
                }
                return;
            }
        }
        ControllerActionVector controllerActionVector = this.vector;
        if (controllerActionVector != null)
        {
            bool hasMappingExcludeLinked = controllerActionVector.HasMappingExcludeLinked;
            ControllerActionButton.RequiredButtonState requiredStateExcludeLinked = this.vector.RequiredStateExcludeLinked;
            float num2;
            if (requiredStateExcludeLinked != null && requiredStateExcludeLinked.state)
            {
                GUIControllerInputButton.LinkedControlType linkedControlType = GUIControlsBanner.FromButton(requiredStateExcludeLinked.Button);
                GUIControllerInputButton.AxisControl axisControl = GUIControlsBanner.FromAxis(this.vector.X.FirstEntry.Axis0, num2);
                return;
            }
            ControllerActionAxis.Entry firstEntry = this.vector.X.FirstEntry;
            ControllerActionVector controllerActionVector2 = this.vector;
            Axis axis = firstEntry.Axis0;
            float threshold = controllerActionVector2.X.FirstEntry.Threshold;
            GUIControllerInputButton.AxisControl axisControl2 = GUIControlsBanner.FromAxis(axis, num2);
            return;
        }
        else
        {
            ControllerActionButton controllerActionButton = this.button;
            if (controllerActionButton != null)
            {
                bool hasMapping = controllerActionButton.HasMapping;
                ControllerActionButton.RequiredButtonState requiredState = this.button.RequiredState;
                if (requiredState != null && requiredState.state)
                {
                    GUIControllerInputButton.LinkedControlType linkedControlType2 = GUIControlsBanner.FromButton(requiredState.Button);
                    ControllerActionButton.Entry.Type mappingType = this.button.FirstEntry.MappingType;
                    GUIControllerInputButton.LinkedControlType linkedControlType3 = GUIControlsBanner.FromButton(this.button.FirstEntry.Button);
                    return;
                }
                ControllerActionButton.Entry entry;
                ControllerActionButton.Entry.Type mappingType2 = entry.MappingType;
                ControllerActionButton.Entry entry2;
                GUIControllerInputButton.LinkedControlType linkedControlType4 = GUIControlsBanner.FromButton(entry2.Button);
                return;
            }
        }
        IL_0243:
        int num3;
        if (num3 == 0)
        {
            return;
        }
    }
References ControlAnchor._gridItemRegion, _optionsBlocker, button, displayOptions, drawingOverlay, Controller.ControllerActionAxis.FirstEntry, Controller.ControllerActionButton.FirstEntry, GUIControlsBanner.FromAxis(), GUIControlsBanner.FromButton(), GetTitle(), Controller.ControllerActionButton.HasMapping, Controller.ControllerActionVector.HasMappingExcludeLinked, j__TPar, Controller.ControllerActionButton.Entry.MappingType, Controller.ControllerActionButton.RequiredState, Controller.ControllerActionVector.RequiredStateExcludeLinked, Controller.ControllerActionButton.RequiredButtonState.state, vector, and Controller.ControllerActionVector.X.