terraria-cpp2il-methodrecon: LocalUser.LoadState
LoadState()
void LocalUser.LoadState () inline
Definition at line 47 of file LocalUser.cs.
    {
        if (!true)
        {
        }
        LocalUserGameState gameState = this.GameState;
        LocalUserXNAState xnastate = this.XNAState;
        FileManager fileManager = this.fileManager;
        CursorManager cursorManager = this.cursorManager;
        ControllerActionManager controllerActionManager = this.controllerActionManager;
        ControllerDevice activeController = this.ActiveController;
        GUIInputRegionManager guiinputRegionManager = this.guiInputRegionManager;
        XNAUIInputLayer xnauiinputLayer = this.xnaUIInputLayer;
        GUIInstance guiinstance = this.GUIInstance;
        MPSessionManager mpsessionManager = this.mpSessionManager;
        LiquidRenderer liquidRenderer = this.liquidRenderer;
        SkyManager skyManager = this.SkyManager;
        FilterManager filterManager = this.FilterManager;
        OverlayManager overlayManager = this.OverlayManager;
        InterfaceProfile_Layout[] customProfiles = this.CustomProfiles;
        XNAUICameraSettings uicameraSettings = this.UICameraSettings;
        GeometryBufferInstance.SetActive(this.UserIndex);
    }
References ActiveController, controllerActionManager, cursorManager, CustomProfiles, fileManager, FilterManager, GameState, guiInputRegionManager, GUIInstance, j__TPar, liquidRenderer, mpSessionManager, OverlayManager, Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.SetActive(), SkyManager, UICameraSettings, UserIndex, XNAState, and xnaUIInputLayer.
Referenced by Terraria.Player.KillMe(), Terraria.Player.OnHit(), and SetupState().