terraria-cpp2il-methodrecon: UnityEngine.UI.ToggleGroup.EnsureValidState
EnsureValidState()
void UnityEngine.UI.ToggleGroup.EnsureValidState () inline
Definition at line 80 of file ToggleGroup.cs.
        {
            if (!this.m_AllowSwitchOff)
            {
                bool flag = this.AnyTogglesOn();
                if (this.m_Toggles._size != 0)
                {
                    List<Toggle> toggles = this.m_Toggles;
                }
            }
            IEnumerable<Toggle> enumerable = this.ActiveToggles();
            int num = Enumerable.Count(enumerable);
            Toggle firstActiveToggle = this.GetFirstActiveToggle();
        }
References UnityEngine.UI.ToggleGroup.ActiveToggles(), UnityEngine.UI.ToggleGroup.AnyTogglesOn(), UnityEngine.UI.ToggleGroup.GetFirstActiveToggle(), j__TPar, UnityEngine.UI.ToggleGroup.m_AllowSwitchOff, and UnityEngine.UI.ToggleGroup.m_Toggles.
Referenced by UnityEngine.UI.Toggle.OnDestroy(), UnityEngine.UI.ToggleGroup.OnEnable(), and UnityEngine.UI.ToggleGroup.Start().