terraria-cpp2il-methodrecon: Newtonsoft.Json.Converters.BinaryConverter.GetByteArray
GetByteArray()
byte[] Newtonsoft.Json.Converters.BinaryConverter.GetByteArray (object value) inline private
Definition at line 24 of file BinaryConverter.cs.
        {
            bool flag = value.GetType().AssignableToTypeName("System.Data.Linq.Binary");
            Type type = value.GetType();
            this.EnsureReflectionObject(type);
            object value2 = this._reflectionObject.GetValue(value, "ToArray");
            if (value2 == null || value2 != null)
            {
                CultureInfo invariantCulture = CultureInfo.InvariantCulture;
                Type type2 = value2.GetType();
                string text = "Unexpected value type when writing binary: {0}".FormatWith(invariantCulture, type2);
            }
            throw new InvalidCastException();
        }
References Newtonsoft.Json.Converters.BinaryConverter._reflectionObject, Newtonsoft.Json.Converters.BinaryConverter.EnsureReflectionObject(), System.Type.GetType(), Newtonsoft.Json.Utilities.ReflectionObject.GetValue(), System.Globalization.CultureInfo.InvariantCulture, j__TPar, System.text, and System.value.
Referenced by Newtonsoft.Json.Converters.BinaryConverter.WriteJson().