terraria-cpp2il-methodrecon: Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket
PreparePacket()
static NetPacket Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket (ushort powerId, int specificInfoBytesInPacketCount) inline static
Definition at line 11 of file NetCreativePowersModule.cs.
        {
            /*
An exception occurred when decompiling this method (06004B75)
ICSharpCode.Decompiler.DecompilerException: Error decompiling Terraria.Net.NetPacket Terraria.GameContent.NetModules.NetCreativePowersModule::PreparePacket(System.UInt16,System.Int32)
 ---> System.Exception: Basic block has to end with unconditional control flow.
{
    Block_0:
    stloc:BinaryWriter(var_0_0F, callgetter:BinaryWriter(NetPacket::get_Writer, call:NetPacket[exp:valuetype Terraria.Net.NetPacket&](NetModule::CreatePacket, ldc.i4:int32(41607168))))
}
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.FlattenBasicBlocks(ILNode node) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 1852
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, AutoPropertyProvider autoPropertyProvider, StateMachineKind& stateMachineKind, MethodDef& inlinedMethod, AsyncMethodDebugInfo& asyncInfo, ILAstOptimizationStep abortBeforeStep) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 355
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 123
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethodBody(EntityDeclaration methodNode, EntityDeclaration& updatedNode, MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1683
*/;
        }
Referenced by Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.AttemptPushingChange(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.DebugCall(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DebugCall(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChange(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.RequestUse(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.RequestUse(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.RequestUse(), and Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.SetEnabledState().