terraria-cpp2il-methodrecon: Ionic.Zlib.DeflateManager._InitializeLazyMatch
_InitializeLazyMatch()
void Ionic.Zlib.DeflateManager._InitializeLazyMatch () inline private
Definition at line 21 of file DeflateManager.cs.
        {
            int num = this.w_size;
            short[] array = this.head;
            int num2 = this.hash_size;
            long num3 = 0L;
            this.window_size = num;
            Array.Clear(array, (int)num3, num2);
            CompressionLevel compressionLevel = this.compressionLevel;
            if (num == 0)
            {
            }
            DeflateManager.Config config = DeflateManager.Config.Lookup(compressionLevel);
            this.config = config;
            this.SetDeflater();
            if (num == 0)
            {
            }
            this.prev_length = num;
            this.match_length = num;
        }
References System.array, System.Array.Clear(), Ionic.Zlib.DeflateManager.compressionLevel, Ionic.Zlib.DeflateManager.config, Ionic.Zlib.DeflateManager.hash_size, Ionic.Zlib.DeflateManager.head, j__TPar, System.L, Ionic.Zlib.DeflateManager.Config.Lookup(), Ionic.Zlib.DeflateManager.SetDeflater(), and Ionic.Zlib.DeflateManager.w_size.
Referenced by Ionic.Zlib.DeflateManager.Reset().