terraria-cpp2il-methodrecon: Ionic.Zlib.DeflateManager.copy_block
copy_block()
void Ionic.Zlib.DeflateManager.copy_block (int buf, int len, bool header) inline package
Definition at line 297 of file DeflateManager.cs.
        {
            this.bi_windup();
            int num = 8;
            this.last_eob_len = num;
            byte[] array = this.pending;
            byte[] array2 = this.pending;
            byte[] array3 = this.pending;
            byte[] array4 = this.pending;
            byte[] array5 = this.window;
            byte[] array6 = this.pending;
            int num2 = this.pendingCount;
            Array.Copy(array5, buf, array6, num2, len);
            int num3 = this.pendingCount;
            this.pendingCount = num3;
        }
References System.array, Ionic.Zlib.DeflateManager.bi_windup(), System.Array.Copy(), j__TPar, Ionic.Zlib.DeflateManager.pending, Ionic.Zlib.DeflateManager.pendingCount, and Ionic.Zlib.DeflateManager.window.
Referenced by Ionic.Zlib.DeflateManager._tr_stored_block().