terraria-cpp2il-methodrecon: Mono.Security.Authenticode.AuthenticodeBase.ProcessFirstBlock
ProcessFirstBlock()
int Mono.Security.Authenticode.AuthenticodeBase.ProcessFirstBlock () inline package inherited
Definition at line 59 of file AuthenticodeBase.cs.
        {
            Stream stream;
            int num;
            do
            {
                stream = this.fs;
                num = 1;
            }
            while (stream == null);
            byte[] array = this.fileblock;
            Stream stream2 = this.fs;
            this.blockNo = num;
            this.peOffset = stream2;
            byte[] array2 = this.fileblock;
            long num2 = 0L;
            ushort num3 = BitConverterLE.ToUInt16(array2, (int)num2);
            byte[] array3 = this.fileblock;
            int num4 = 60;
            int num5 = BitConverterLE.ToInt32(array3, num4);
            byte[] array4 = this.fileblock;
            this.peOffset = num5;
            Stream stream3 = this.fs;
            return 3;
        }
References System.array, Mono.Security.Authenticode.AuthenticodeBase.fileblock, Mono.Security.Authenticode.AuthenticodeBase.fs, j__TPar, System.L, Mono.Security.BitConverterLE.ToInt32(), and Mono.Security.BitConverterLE.ToUInt16().
Referenced by Mono.Security.Authenticode.AuthenticodeBase.ReadFirstBlock().