terraria-cpp2il-methodrecon: System.Xml.HtmlUtf8RawTextWriter.OutputRestAmps
OutputRestAmps()
void System.Xml.HtmlUtf8RawTextWriter.OutputRestAmps () inline private inherited
Definition at line 337 of file HtmlUtf8RawTextWriter.cs.
        {
            byte[] bufBytes = this.bufBytes;
            byte[] bufBytes2 = this.bufBytes;
            byte[] bufBytes3 = this.bufBytes;
            byte[] bufBytes4 = this.bufBytes;
        }
References System.Xml.XmlUtf8RawTextWriter.bufBytes, and j__TPar.
Referenced by System.Xml.HtmlUtf8RawTextWriter.WriteEndAttribute(), System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeText(), and System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText().