terraria-cpp2il-methodrecon: System.Environment.GetEnvironmentVariable
GetEnvironmentVariable()
static string System.Environment.GetEnvironmentVariable (string variable) inline static
Definition at line 238 of file Environment.cs.
        {
            string text;
            return text;
        }
References System.text.
Referenced by System.Diagnostics.DefaultTraceListener.DefaultTraceListener(), System.IO.MonoIO.MonoIO(), System.Net.Sockets.SafeSocketHandle.SafeSocketHandle(), System.Uri.Uri(), Mono.Net.Security.MonoTlsProviderFactory.CreateDefaultProviderImpl(), ReLogic.OS.Linux.PathService.GetStoragePath(), ReLogic.OS.OSX.PathService.GetStoragePath(), System.TimeZoneInfo.GetTimeZoneDirectory(), and System.TimeZoneInfo.GetTzEnvironmentVariable().