terraria-cpp2il-methodrecon: UnityEngine.UI.GraphicRegistry.RegisterGraphicForCanvas
RegisterGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.RegisterGraphicForCanvas (Canvas c, Graphic graphic) inline static
Definition at line 38 of file GraphicRegistry.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
            if (!true)
            {
            }
            if (GraphicRegistry.instance.m_Graphics != null)
            {
                return;
            }
            Dictionary<Canvas, IndexedSet<Graphic>> graphics = GraphicRegistry.instance.m_Graphics;
            GraphicRegistry.RegisterRaycastGraphicForCanvas(c, graphic);
        }
References UnityEngine.UI.GraphicRegistry.instance, UnityEngine.UI.GraphicRegistry.m_Graphics, and UnityEngine.UI.GraphicRegistry.RegisterRaycastGraphicForCanvas().
Referenced by UnityEngine.UI.Graphic.OnCanvasHierarchyChanged(), UnityEngine.UI.Graphic.OnEnable(), and UnityEngine.UI.Graphic.OnTransformParentChanged().