terraria-cpp2il-methodrecon: UnityEngine.UI.GraphicRegistry.DisableGraphicForCanvas
DisableGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.DisableGraphicForCanvas (Canvas c, Graphic graphic) inline static
Definition at line 111 of file GraphicRegistry.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
            Dictionary<Canvas, IndexedSet<Graphic>> graphics = GraphicRegistry.instance.m_Graphics;
            int num;
            if (num == 0)
            {
                Dictionary<Canvas, IndexedSet<Graphic>> graphics2 = GraphicRegistry.instance.m_Graphics;
            }
            GraphicRegistry.DisableRaycastGraphicForCanvas(c, graphic);
        }
References UnityEngine.UI.GraphicRegistry.DisableRaycastGraphicForCanvas(), UnityEngine.UI.GraphicRegistry.instance, j__TPar, and UnityEngine.UI.GraphicRegistry.m_Graphics.
Referenced by UnityEngine.UI.Graphic.OnBeforeTransformParentChanged(), and UnityEngine.UI.Graphic.OnDisable().