terraria-cpp2il-methodrecon: System.Xml.XmlEventCache.NewEvent
NewEvent()
int System.Xml.XmlEventCache.NewEvent () inline private
Definition at line 281 of file XmlEventCache.cs.
        {
            throw new AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");
        }
Referenced by System.Xml.XmlEventCache.AddEvent(), System.Xml.XmlEventCache.AddEvent(), System.Xml.XmlEventCache.AddEvent(), System.Xml.XmlEventCache.AddEvent(), System.Xml.XmlEventCache.AddEvent(), System.Xml.XmlEventCache.AddEvent(), System.Xml.XmlEventCache.Close(), System.Xml.XmlEventCache.Dispose(), System.Xml.XmlEventCache.EndEvents(), System.Xml.XmlEventCache.Flush(), System.Xml.XmlEventCache.StartElementContent(), System.Xml.XmlEventCache.WriteBase64(), System.Xml.XmlEventCache.WriteBinHex(), System.Xml.XmlEventCache.WriteCData(), System.Xml.XmlEventCache.WriteCharEntity(), System.Xml.XmlEventCache.WriteComment(), System.Xml.XmlEventCache.WriteDocType(), System.Xml.XmlEventCache.WriteEndAttribute(), System.Xml.XmlEventCache.WriteEndBase64(), System.Xml.XmlEventCache.WriteEndElement(), System.Xml.XmlEventCache.WriteEntityRef(), System.Xml.XmlEventCache.WriteFullEndElement(), System.Xml.XmlEventCache.WriteNamespaceDeclaration(), System.Xml.XmlEventCache.WriteProcessingInstruction(), System.Xml.XmlEventCache.WriteRaw(), System.Xml.XmlEventCache.WriteStartAttribute(), System.Xml.XmlEventCache.WriteStartElement(), System.Xml.XmlEventCache.WriteString(), System.Xml.XmlEventCache.WriteSurrogateCharEntity(), System.Xml.XmlEventCache.WriteWhitespace(), System.Xml.XmlEventCache.WriteXmlDeclaration(), and System.Xml.XmlEventCache.WriteXmlDeclaration().