terraria-cpp2il-methodrecon: System.Text.RegularExpressions.RegexReplacement.RegexReplacement
RegexReplacement()
System.Text.RegularExpressions.RegexReplacement.RegexReplacement (string rep, RegexNode concat, Hashtable _caps) inline
Definition at line 13 of file RegexReplacement.cs.
        {
            int ntype = concat.NType;
            StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
            long num = 0L;
            List<RegexNode> children = concat.Children;
            if (children != null)
            {
                int size = children._size;
            }
            RegexNode regexNode = concat.Child((int)num);
            int ntype2 = regexNode.NType;
            string str = regexNode.Str;
            StringBuilder stringBuilder2 = stringBuilder.Append(str);
        }
References System.Collections.Generic.List< T >._size, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Text.RegularExpressions.RegexNode.Child(), j__TPar, System.L, and System.Text.RegularExpressions.RegexNode.NType.