terraria-cpp2il-methodrecon: Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddTownNPCs_Manual
AddTownNPCs_Manual()
void Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddTownNPCs_Manual () inline private
Definition at line 114 of file BestiaryDatabaseNPCsPopulator.cs.
        {
            BestiaryEntry bestiaryEntry = BestiaryEntry.TownNPC(22);
            BestiaryEntry bestiaryEntry2 = this._currentDatabase.Register(bestiaryEntry);
            BestiaryEntry bestiaryEntry3 = BestiaryEntry.TownNPC(17);
            BestiaryEntry bestiaryEntry4 = this._currentDatabase.Register(bestiaryEntry3);
            BestiaryEntry bestiaryEntry5 = BestiaryEntry.TownNPC(18);
            BestiaryEntry bestiaryEntry6 = this._currentDatabase.Register(bestiaryEntry5);
            BestiaryEntry bestiaryEntry7 = BestiaryEntry.TownNPC(19);
            BestiaryEntry bestiaryEntry8 = this._currentDatabase.Register(bestiaryEntry7);
            BestiaryEntry bestiaryEntry9 = BestiaryEntry.TownNPC(20);
            BestiaryEntry bestiaryEntry10 = this._currentDatabase.Register(bestiaryEntry9);
            BestiaryEntry bestiaryEntry11 = BestiaryEntry.TownNPC(37);
            BestiaryEntry bestiaryEntry12 = this._currentDatabase.Register(bestiaryEntry11);
            BestiaryEntry bestiaryEntry13 = BestiaryEntry.TownNPC(54);
            BestiaryEntry bestiaryEntry14 = this._currentDatabase.Register(bestiaryEntry13);
            BestiaryEntry bestiaryEntry15 = BestiaryEntry.TownNPC(38);
            BestiaryEntry bestiaryEntry16 = this._currentDatabase.Register(bestiaryEntry15);
            BestiaryEntry bestiaryEntry17 = BestiaryEntry.TownNPC(107);
            BestiaryEntry bestiaryEntry18 = this._currentDatabase.Register(bestiaryEntry17);
            BestiaryEntry bestiaryEntry19 = BestiaryEntry.TownNPC(108);
            BestiaryEntry bestiaryEntry20 = this._currentDatabase.Register(bestiaryEntry19);
            BestiaryEntry bestiaryEntry21 = BestiaryEntry.TownNPC(124);
            BestiaryEntry bestiaryEntry22 = this._currentDatabase.Register(bestiaryEntry21);
            BestiaryEntry bestiaryEntry23 = BestiaryEntry.TownNPC(142);
            BestiaryEntry bestiaryEntry24 = this._currentDatabase.Register(bestiaryEntry23);
            BestiaryEntry bestiaryEntry25 = BestiaryEntry.TownNPC(160);
            BestiaryEntry bestiaryEntry26 = this._currentDatabase.Register(bestiaryEntry25);
            BestiaryEntry bestiaryEntry27 = BestiaryEntry.TownNPC(178);
            BestiaryEntry bestiaryEntry28 = this._currentDatabase.Register(bestiaryEntry27);
            BestiaryEntry bestiaryEntry29 = BestiaryEntry.TownNPC(207);
            BestiaryEntry bestiaryEntry30 = this._currentDatabase.Register(bestiaryEntry29);
            BestiaryEntry bestiaryEntry31 = BestiaryEntry.TownNPC(208);
            BestiaryEntry bestiaryEntry32 = this._currentDatabase.Register(bestiaryEntry31);
            BestiaryEntry bestiaryEntry33 = BestiaryEntry.TownNPC(209);
            BestiaryEntry bestiaryEntry34 = this._currentDatabase.Register(bestiaryEntry33);
            BestiaryEntry bestiaryEntry35 = BestiaryEntry.TownNPC(227);
            BestiaryEntry bestiaryEntry36 = this._currentDatabase.Register(bestiaryEntry35);
            BestiaryEntry bestiaryEntry37 = BestiaryEntry.TownNPC(228);
            BestiaryEntry bestiaryEntry38 = this._currentDatabase.Register(bestiaryEntry37);
            BestiaryEntry bestiaryEntry39 = BestiaryEntry.TownNPC(229);
            BestiaryEntry bestiaryEntry40 = this._currentDatabase.Register(bestiaryEntry39);
            BestiaryEntry bestiaryEntry41 = BestiaryEntry.TownNPC(353);
            BestiaryEntry bestiaryEntry42 = this._currentDatabase.Register(bestiaryEntry41);
            BestiaryEntry bestiaryEntry43 = BestiaryEntry.TownNPC(369);
            BestiaryEntry bestiaryEntry44 = this._currentDatabase.Register(bestiaryEntry43);
            BestiaryEntry bestiaryEntry45 = BestiaryEntry.TownNPC(441);
            BestiaryEntry bestiaryEntry46 = this._currentDatabase.Register(bestiaryEntry45);
            BestiaryEntry bestiaryEntry47 = BestiaryEntry.TownNPC(550);
            BestiaryEntry bestiaryEntry48 = this._currentDatabase.Register(bestiaryEntry47);
            BestiaryEntry bestiaryEntry49 = BestiaryEntry.TownNPC(588);
            BestiaryEntry bestiaryEntry50 = this._currentDatabase.Register(bestiaryEntry49);
            BestiaryEntry bestiaryEntry51 = BestiaryEntry.TownNPC(368);
            BestiaryEntry bestiaryEntry52 = this._currentDatabase.Register(bestiaryEntry51);
            BestiaryEntry bestiaryEntry53 = BestiaryEntry.TownNPC(453);
            BestiaryEntry bestiaryEntry54 = this._currentDatabase.Register(bestiaryEntry53);
            BestiaryEntry bestiaryEntry55 = BestiaryEntry.TownNPC(633);
            BestiaryEntry bestiaryEntry56 = this._currentDatabase.Register(bestiaryEntry55);
            BestiaryEntry bestiaryEntry57 = BestiaryEntry.TownNPC(663);
            BestiaryEntry bestiaryEntry58 = this._currentDatabase.Register(bestiaryEntry57);
            BestiaryEntry bestiaryEntry59 = BestiaryEntry.TownNPC(638);
            BestiaryEntry bestiaryEntry60 = this._currentDatabase.Register(bestiaryEntry59);
            BestiaryEntry bestiaryEntry61 = BestiaryEntry.TownNPC(637);
            BestiaryEntry bestiaryEntry62 = this._currentDatabase.Register(bestiaryEntry61);
            BestiaryEntry bestiaryEntry63 = BestiaryEntry.TownNPC(656);
            BestiaryEntry bestiaryEntry64 = this._currentDatabase.Register(bestiaryEntry63);
            BestiaryEntry bestiaryEntry65 = BestiaryEntry.TownNPC(670);
            BestiaryEntry bestiaryEntry66 = this._currentDatabase.Register(bestiaryEntry65);
            BestiaryEntry bestiaryEntry67 = BestiaryEntry.TownNPC(678);
            BestiaryEntry bestiaryEntry68 = this._currentDatabase.Register(bestiaryEntry67);
            BestiaryEntry bestiaryEntry69 = BestiaryEntry.TownNPC(679);
            BestiaryEntry bestiaryEntry70 = this._currentDatabase.Register(bestiaryEntry69);
            BestiaryEntry bestiaryEntry71 = BestiaryEntry.TownNPC(680);
            BestiaryEntry bestiaryEntry72 = this._currentDatabase.Register(bestiaryEntry71);
            BestiaryEntry bestiaryEntry73 = BestiaryEntry.TownNPC(681);
            BestiaryEntry bestiaryEntry74 = this._currentDatabase.Register(bestiaryEntry73);
            BestiaryEntry bestiaryEntry75 = BestiaryEntry.TownNPC(682);
            BestiaryEntry bestiaryEntry76 = this._currentDatabase.Register(bestiaryEntry75);
            BestiaryEntry bestiaryEntry77 = BestiaryEntry.TownNPC(683);
            BestiaryEntry bestiaryEntry78 = this._currentDatabase.Register(bestiaryEntry77);
            BestiaryEntry bestiaryEntry79 = BestiaryEntry.TownNPC(684);
            BestiaryEntry bestiaryEntry80 = this._currentDatabase.Register(bestiaryEntry79);
        }
References Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator._currentDatabase, j__TPar, Terraria.GameContent.Bestiary.BestiaryDatabase.Register(), and Terraria.GameContent.Bestiary.BestiaryEntry.TownNPC().
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate().