terraria-cpp2il-methodrecon: System.Net.FtpControlStream.PipelineCallback
PipelineCallback()
override CommandStream.PipelineInstruction System.Net.FtpControlStream.PipelineCallback (CommandStream::PipelineEntry entry, ResponseDescription response, bool timeout, Stream stream) inline protected virtual
Reimplemented from System.Net.CommandStream.
Definition at line 112 of file FtpControlStream.cs.
        {
            if (!true)
            {
            }
            bool isEnabled = NetEventSource.IsEnabled;
            if (entry != null)
            {
                string command = entry.Command;
                if (command == null || command == null)
                {
                }
            }
            if (response != null)
            {
                string statusDescription = response.StatusDescription;
                if (statusDescription != null && statusDescription == null)
                {
                    throw new ArrayTypeMismatchException();
                }
            }
            FormattableString formattableString;
            NetEventSource.Info(this, formattableString, "PipelineCallback");
            if (response != null)
            {
                int status = response.Status;
                this.StatusCode = (FtpStatusCode)status;
                string statusDescription2 = response.StatusDescription;
                this.StatusLine = statusDescription2;
                int index = this._index;
                bool flag = entry.Command == "OPTS utf8 on\r\n";
                int status2 = response.Status;
                Encoding utf = Encoding.UTF8;
                string statusLine = this.StatusLine;
                int num = entry.Command.IndexOf("USER");
                int num2 = 1;
                this._loginState = (FtpLoginState)num2;
                this._index = "USER";
                FtpLoginState loginState = this._loginState;
                int num3 = entry.Command.IndexOf("PASS");
                int num4 = 1;
                this._loginState = (FtpLoginState)num4;
                if (entry.Flags == (CommandStream.PipelineEntryFlags)0)
                {
                    goto IL_0178;
                }
                if (this._dataSocket != null)
                {
                    string command2 = entry.Command;
                    string text;
                    this._abortReason = text;
                }
            }
            Encoding @default = Encoding.Default;
            this._encoding = @default;
            this._decoder = @default;
            StringBuilder welcomeMessage = this._welcomeMessage;
            string statusLine2 = this.StatusLine;
            StringBuilder stringBuilder = welcomeMessage.Append(statusLine2);
            StringBuilder stringBuilder2 = this._exitMessage.Append(statusLine2);
            base.CloseSocket();
            bool usingSecureStream = base.UsingSecureStream;
            bool flag2 = entry.Command == "AUTH TLS\r\n";
            IL_0178:
            this.TryUpdateContentLength("AUTH TLS\r\n");
            WebRequest request = this._request;
            if (request != null)
            {
            }
            return this.QueueOrCreateFtpDataStream(stream);
        }
References System.Net.FtpControlStream._dataSocket, System.Net.FtpControlStream._exitMessage, System.Net.CommandStream._index, System.Net.FtpControlStream._loginState, System.Net.CommandStream._request, System.Net.FtpControlStream._welcomeMessage, System.Text.StringBuilder.Append(), System.Text.Encoding.Default, System.index, System.Net.NetEventSource.Info(), System.Net.NetEventSource.IsEnabled, j__TPar, System.Net.FtpControlStream.QueueOrCreateFtpDataStream(), System.Net.ResponseDescription.Status, System.Net.ResponseDescription.StatusDescription, System.Net.FtpControlStream.StatusLine, System.text, System.Net.FtpControlStream.TryUpdateContentLength(), and System.Text.Encoding.UTF8.