terraria-cpp2il-methodrecon: System.IO.FileSystem.MoveFile
MoveFile()
static void System.IO.FileSystem.MoveFile (string sourceFullPath, string destFullPath) inline static
Definition at line 61 of file FileSystem.cs.
        {
            if (!true)
            {
            }
            int num;
            if (num == 0)
            {
                if (!true)
                {
                }
                int num2;
                if (num2 != 0)
                {
                    if (!true)
                    {
                    }
                    if (Interop.Sys.Rename(sourceFullPath, destFullPath) == 0)
                    {
                        return;
                    }
                }
            }
            FileSystem.LinkOrCopyFile(sourceFullPath, destFullPath);
            FileSystem.DeleteFile(sourceFullPath);
        }
References System.IO.FileSystem.DeleteFile(), j__TPar, and System.IO.FileSystem.LinkOrCopyFile().
Referenced by System.IO.File.Move().