terraria-cpp2il-methodrecon: InControl.UnityInputDevice.UnityInputDevice
UnityInputDevice() [2/2]
InControl.UnityInputDevice.UnityInputDevice (InputDeviceProfile deviceProfile, int joystickId, string joystickName) inline
Definition at line 69 of file UnityInputDevice.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            base..ctor();
            this.profile = deviceProfile;
            this.JoystickId = joystickId;
            if (joystickId != 0)
            {
                if (num == 0)
                {
                }
                this.<SortOrder>k__BackingField = num;
            }
            UnityInputDevice.SetupAnalogQueries();
            UnityInputDevice.SetupButtonQueries();
            if (num == 0)
            {
            }
            string deviceName = this.profile.deviceName;
            InputDeviceProfile inputDeviceProfile = this.profile;
            this.<Name>k__BackingField = deviceName;
            string deviceNotes = inputDeviceProfile.deviceNotes;
            this.<Meta>k__BackingField = deviceNotes;
            InputDeviceClass deviceClass = inputDeviceProfile.deviceClass;
            bool invert = inputDeviceProfile.analogMappings.invert;
            string deviceNotes2 = inputDeviceProfile.deviceNotes;
            if (inputDeviceProfile == null)
            {
            }
            string text;
            string text2;
            if (("Cannot map control \"" == null || "Cannot map control \"" != null) && (text == null || text != null) && ("\" as InputControlType." == null || "\" as InputControlType." != null) && (text2 == null || text2 != null) && (" in profile \"" == null || " in profile \"" != null))
            {
                string deviceName2 = deviceProfile.deviceName;
                if ((deviceName2 == null || deviceName2 != null) && ("\" because this target is reserved as an alias. The mapping will be ignored." == null || "\" because this target is reserved as an alias. The mapping will be ignored." != null))
                {
                    string text3;
                    Debug.LogError(text3);
                    return;
                }
            }
            throw new ArrayTypeMismatchException();
        }
References InControl.InputDeviceProfile.deviceName, j__TPar, InControl.UnityInputDevice.k__BackingField, UnityEngine.Debug.LogError(), InControl.InputDevice.Meta, InControl.InputDevice.Name, InControl.UnityInputDevice.profile, InControl.UnityInputDevice.SetupAnalogQueries(), InControl.UnityInputDevice.SetupButtonQueries(), InControl.InputDevice.SortOrder, and System.text.