terraria-cpp2il-methodrecon: System.DateTime.FromFileTime
FromFileTime()
static DateTime System.DateTime.FromFileTime (long fileTime) inline static
Definition at line 358 of file DateTime.cs.
        {
            if (!true)
            {
            }
            DateTime dateTime = DateTime.FromFileTimeUtc(fileTime);
            long num = 0L;
            DateTime dateTime2 = dateTime.ToLocalTime(num != 0L);
            return 1;
        }
References System.DateTime.FromFileTimeUtc(), j__TPar, System.L, and System.DateTime.ToLocalTime().
Referenced by System.DateTimeOffset.FromFileTime().