terraria-cpp2il-methodrecon: System.DateTime.ToLocalTime
ToLocalTime() [1/2]
DateTime System.DateTime.ToLocalTime () inline
Definition at line 801 of file DateTime.cs.
        {
            long num = 0L;
            DateTime dateTime = this.ToLocalTime(num != 0L);
            DateTime dateTime2;
            return dateTime2;
        }
References j__TPar, System.L, and System.DateTime.ToLocalTime().
Referenced by Terraria.Graphics.Capture.CaptureSettings.CaptureSettings(), Terraria.Utilities.CrashDump.CreateDumpName(), System.DateTime.FromFileTime(), System.DateTime.ToLocalTime(), System.DateTimeOffset.ToLocalTime(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeMicrosoft().