terraria-cpp2il-methodrecon: Terraria.ID.NPCID.Sets.NPCBestiaryDrawOffsetCreation
NPCBestiaryDrawOffsetCreation()
static Dictionary< int, NPCID.Sets.NPCBestiaryDrawModifiers > Terraria.ID.NPCID.Sets.NPCBestiaryDrawOffsetCreation () inline static
Definition at line 2358 of file NPCID.cs.
            {
                if (!true)
                {
                }
                Dictionary<int, NPCID.Sets.NPCBestiaryDrawModifiers> redigitEntries = NPCID.Sets.GetRedigitEntries();
                Dictionary<int, NPCID.Sets.NPCBestiaryDrawModifiers> leinforsEntries = NPCID.Sets.GetLeinforsEntries();
                Dictionary<int, NPCID.Sets.NPCBestiaryDrawModifiers> groxEntries = NPCID.Sets.GetGroxEntries();
                throw new OutOfMemoryException();
            }
References Terraria.ID.NPCID.Sets.GetGroxEntries(), Terraria.ID.NPCID.Sets.GetLeinforsEntries(), Terraria.ID.NPCID.Sets.GetRedigitEntries(), and j__TPar.
Referenced by Terraria.ID.NPCID.Sets.Sets().