terraria-cpp2il-methodrecon: System.Runtime.Serialization.SerializationInfo.AddValue
AddValue() [8/10]
void System.Runtime.Serialization.SerializationInfo.AddValue (string name, object value, Type type) inline
Definition at line 178 of file SerializationInfo.cs.
        {
            while (name != null)
            {
                if (type != null)
                {
                    this.AddValueInternal(name, value, type);
                    return;
                }
            }
        }
References System.Runtime.Serialization.SerializationInfo.AddValueInternal(), System.name, and System.value.
Referenced by System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Remoting.Messaging.ObjRefSurrogate.GetObjectData(), Mono.Security.X509.X509Certificate.GetObjectData(), System.Collections.Comparer.GetObjectData(), System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData(), System.Collections.Hashtable.GetObjectData(), System.CultureAwareComparer.GetObjectData(), System.DateTimeOffset.GetObjectData(), System.Exception.GetObjectData(), System.Reflection.AssemblyName.GetObjectData(), System.Reflection.StrongNameKeyPair.GetObjectData(), System.Runtime.Remoting.Messaging.LogicalCallContext.GetObjectData(), System.Runtime.Remoting.Messaging.MethodCall.GetObjectData(), System.Runtime.Remoting.Messaging.MethodResponse.GetObjectData(), System.Security.Claims.ClaimsIdentity.GetObjectData(), System.Security.Principal.WindowsIdentity.GetObjectData(), System.Security.SecurityException.GetObjectData(), System.Text.DecoderReplacementFallback.GetObjectData(), System.Text.EncoderReplacementFallback.GetObjectData(), System.Text.Encoding.DefaultEncoder.GetObjectData(), System.Text.Encoding.DefaultDecoder.GetObjectData(), System.Text.StringBuilder.GetObjectData(), System.TimeZoneInfo.GetObjectData(), System.TimeZoneInfo.AdjustmentRule.GetObjectData(), System.TimeZoneInfo.TransitionTime.GetObjectData(), System.TypeLoadException.GetObjectData(), System.WeakReference< T >.GetObjectData(), System.Collections.Generic.HashSet< T >.GetObjectData(), System.Xml.Schema.XmlSchemaException.GetObjectData(), System.Xml.XmlException.GetObjectData(), System.Collections.Generic.LinkedList< T >.GetObjectData(), System.Collections.Specialized.NameObjectCollectionBase.GetObjectData(), System.Collections.Specialized.OrderedDictionary.GetObjectData(), System.ComponentModel.LicenseException.GetObjectData(), System.ComponentModel.WarningException.GetObjectData(), System.ComponentModel.Win32Exception.GetObjectData(), System.Text.RegularExpressions.RegexMatchTimeoutException.GetObjectData(), System.Net.FileWebRequest.GetObjectData(), System.Net.FileWebResponse.GetObjectData(), System.Net.HttpWebResponse.GetObjectData(), System.Net.WebProxy.GetObjectData(), and System.Text.Encoding.SerializeEncoding().