terraria-cpp2il-methodrecon: Newtonsoft.Json.Serialization.JsonContract.JsonContract
JsonContract()
Newtonsoft.Json.Serialization.JsonContract.JsonContract (Type underlyingType) inline package
Definition at line 390 of file JsonContract.cs.
        {
            ValidationUtils.ArgumentNotNull(underlyingType, "underlyingType");
            this.UnderlyingType = underlyingType;
            if (!true)
            {
            }
            bool flag = ReflectionUtils.IsNullable(underlyingType);
            this.IsNullable = true;
            if (!true)
            {
            }
            bool flag2 = ReflectionUtils.IsNullableType(underlyingType);
            Type underlyingType2 = Nullable.GetUnderlyingType(underlyingType);
            this.NonNullableUnderlyingType = underlyingType2;
            this.CreatedType = underlyingType2;
            Type nonNullableUnderlyingType = this.NonNullableUnderlyingType;
            if (!true)
            {
            }
            bool flag3 = ConvertUtils.IsConvertible(nonNullableUnderlyingType);
            Type nonNullableUnderlyingType2 = this.NonNullableUnderlyingType;
            bool flag4 = nonNullableUnderlyingType2.IsEnum();
            this.IsEnum = nonNullableUnderlyingType2 != null;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Nullable< T >.GetUnderlyingType(), Newtonsoft.Json.Utilities.ConvertUtils.IsConvertible(), System.Type.IsEnum, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), j__TPar, and Newtonsoft.Json.Serialization.JsonContract.NonNullableUnderlyingType.