terraria-cpp2il-methodrecon: Terraria.Graphics.Capture.CaptureInterface.Update
Update()
void Terraria.Graphics.Capture.CaptureInterface.Update () inline
Definition at line 50 of file CaptureInterface.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            PlayerInput.SetZoom_UI();
            if (num == 0)
            {
            }
            if (num == 0)
            {
                if (num == 0)
                {
                }
                TriggersSet current = PlayerInput.Triggers.Current;
                long num2 = 0L;
                bool toggleCameraMode = current.ToggleCameraMode;
                bool keyToggleActiveHeld = this.KeyToggleActiveHeld;
                if (!keyToggleActiveHeld)
                {
                    if (!keyToggleActiveHeld)
                    {
                    }
                    bool active;
                    if (Main.mouseItem.type != 0)
                    {
                        active = this.Active;
                        if (!active)
{
                            goto IL_0083;
                        }
                    }
                    if (!active)
                    {
                    }
                    int myPlayer = Main.myPlayer;
                    int myPlayer2 = Main.myPlayer;
                    bool active2 = this.Active;
                    this.ToggleCamera(num2 != 0L);
                }
                IL_0083:
                bool active3 = this.Active;
                if (active3)
                {
                    if (!active3)
                    {
                    }
                    if (!active3)
                    {
                    }
                    if (active3)
                    {
                        if (!active3)
{
                        }
                        bool mouseLeftRelease = Main.mouseLeftRelease;
                        if (!active3)
{
                        }
                        bool mouseLeft = Main.mouseLeft;
                        if (!active3)
{
                        }
                    }
                    if (!active3)
                    {
                    }
                    int mouseX = Main.mouseX;
                    int mouseY = Main.mouseY;
                    if (!active3)
                    {
                    }
                    bool mouseLeft2 = Main.mouseLeft;
                    if (!active3)
                    {
                    }
                    int selectedMode = this.SelectedMode;
                    return;
                }
            }
        }
References Terraria.Graphics.Capture.CaptureInterface.Active, Terraria.GameInput.TriggersPack.Current, j__TPar, Terraria.Graphics.Capture.CaptureInterface.KeyToggleActiveHeld, System.L, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Graphics.Capture.CaptureInterface.SelectedMode, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Graphics.Capture.CaptureInterface.ToggleCamera(), Terraria.GameInput.TriggersSet.ToggleCameraMode, Terraria.GameInput.PlayerInput.Triggers, and Terraria.Item.type.
Referenced by Terraria.Graphics.Capture.CaptureManager.Update().