terraria-cpp2il-methodrecon: InControl.PlayerAction.Update
Update()
void InControl.PlayerAction.Update (ulong updateTick, float deltaTime, InputDevice device) inline package
Definition at line 398 of file PlayerAction.cs.
        {
            do
            {
                InputDevice inputDevice = this.device;
                this.device = device;
                this.UpdateVisibleBindings();
                this.UpdateBindings(updateTick, deltaTime);
                if (this.triggerBindingChanged)
                {
                    Action onBindingsChanged = this.OnBindingsChanged;
                    if (onBindingsChanged != null)
                    {
                        IntPtr invoke_impl = onBindingsChanged.invoke_impl;
                        IntPtr method_code = onBindingsChanged.method_code;
                        IntPtr method = onBindingsChanged.method;
                    }
                }
                if (!this.triggerBindingEnded)
                {
                    goto IL_0066;
                }
            }
            while (this.ListenOptions != null);
            if (this.<Owner>k__BackingField.listenOptions.OnBindingEnded != null)
            {
            }
            IL_0066:
            this.DetectBindings();
        }
References InControl.PlayerAction.DetectBindings(), InControl.PlayerAction.device, j__TPar, InControl.PlayerAction.k__BackingField, InControl.PlayerAction.ListenOptions, InControl.PlayerAction.OnBindingsChanged, InControl.PlayerAction.Owner, InControl.PlayerAction.triggerBindingChanged, InControl.PlayerAction.triggerBindingEnded, InControl.PlayerAction.UpdateBindings(), and InControl.PlayerAction.UpdateVisibleBindings().