terraria-cpp2il-methodrecon: System.Net.WebHeaderCollection.SetInternal
SetInternal() [1/2]
void System.Net.WebHeaderCollection.SetInternal (HttpResponseHeader header, string value) inline package
Definition at line 583 of file WebHeaderCollection.cs.
        {
            if (this.m_Type == WebHeaderCollectionType.Unknown)
            {
                this.m_Type = WebHeaderCollectionType.WebResponse;
                return;
            }
            if (value != null)
            {
                int stringLength = value._stringLength;
            }
            string text;
            this.SetInternal(text, value);
        }
References j__TPar, System.Net.WebHeaderCollection.m_Type, System.Net.WebHeaderCollection.SetInternal(), System.text, and System.value.
Referenced by System.Net.HttpListenerResponse.SendHeaders(), and System.Net.WebHeaderCollection.SetInternal().