terraria-cpp2il-methodrecon: System.Net.WebHeaderCollection.ThrowOnRestrictedHeader
ThrowOnRestrictedHeader()
void System.Net.WebHeaderCollection.ThrowOnRestrictedHeader (string headerName) inline package
Definition at line 742 of file WebHeaderCollection.cs.
        {
            if (this.m_Type == WebHeaderCollectionType.Unknown)
            {
            }
            HeaderInfo headerInfo;
            if (!headerInfo.IsRequestRestricted)
            {
                return;
            }
            throw new ArrayTypeMismatchException();
        }
References j__TPar, and System.Net.WebHeaderCollection.m_Type.
Referenced by System.Net.WebHeaderCollection.Add(), System.Net.WebHeaderCollection.Add(), System.Net.WebHeaderCollection.Remove(), and System.Net.WebHeaderCollection.Set().