terraria-cpp2il-methodrecon: System.Net.WebHeaderCollection.Set
Set() [3/3]
override void System.Net.WebHeaderCollection.Set (string name, string value) inline
Definition at line 808 of file WebHeaderCollection.cs.
        {
            if (!true)
            {
            }
            if (name != null && name._stringLength != 0)
            {
                long num = 0L;
                string text = WebHeaderCollection.CheckBadChars(name, num != 0L);
                this.ThrowOnRestrictedHeader(text);
                string text2 = WebHeaderCollection.CheckBadChars(value, true);
                if (text2 != null)
                {
                    WebHeaderCollectionType type = this.m_Type;
                    int stringLength = text2._stringLength;
                }
                this.NormalizeCommonHeaders();
                base.InvalidateCachedArrays();
                global::System.Collections.Specialized.NameValueCollection innerCollection = this.InnerCollection;
                return;
            }
            throw new ArrayTypeMismatchException();
        }
References System.Net.WebHeaderCollection.CheckBadChars(), System.Net.WebHeaderCollection.InnerCollection, j__TPar, System.L, System.Net.WebHeaderCollection.m_Type, System.name, System.Net.WebHeaderCollection.NormalizeCommonHeaders(), System.text, System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(), and System.value.