terraria-cpp2il-methodrecon: System.Net.WebHeaderCollection.Add
Add() [3/4]
void System.Net.WebHeaderCollection.Add (string header) inline
Definition at line 776 of file WebHeaderCollection.cs.
        {
            if (!true)
            {
            }
            if (header != null && header._stringLength != 0)
            {
                int num = 58;
                int num2 = header.IndexOf((char)num);
                long num3 = 0L;
                string text = header.Substring((int)num3, num2);
                string text2 = header.Substring((int)num3);
                long num4 = 0L;
                string text3 = WebHeaderCollection.CheckBadChars(text, num4 != 0L);
                this.ThrowOnRestrictedHeader(text3);
                int num5 = 1;
                string text4 = WebHeaderCollection.CheckBadChars(text2, num5 != 0);
                if (text4 != null)
                {
                    WebHeaderCollectionType type = this.m_Type;
                    int stringLength = text4._stringLength;
                }
                this.NormalizeCommonHeaders();
                base.InvalidateCachedArrays();
                global::System.Collections.Specialized.NameValueCollection innerCollection = this.InnerCollection;
                return;
            }
            string @string = SR.GetString("Specified value does not have a ':' separator.");
            throw new ArrayTypeMismatchException();
        }
References System.Net.WebHeaderCollection.CheckBadChars(), SR.GetString(), System.Net.WebHeaderCollection.InnerCollection, j__TPar, System.L, System.Net.WebHeaderCollection.m_Type, System.Net.WebHeaderCollection.NormalizeCommonHeaders(), System.text, and System.Net.WebHeaderCollection.ThrowOnRestrictedHeader().