terraria-cpp2il-methodrecon: System.Net.WebHeaderCollection.Remove
Remove() [3/3]
override void System.Net.WebHeaderCollection.Remove (string name) inline
Definition at line 856 of file WebHeaderCollection.cs.
        {
            int stringLength;
            for (;;)
            {
                if (!true)
                {
                }
                if (name != null)
                {
                    stringLength = name._stringLength;
                    if (stringLength != 0)
                    {
                        break;
                    }
                }
            }
            this.ThrowOnRestrictedHeader(name);
            if (stringLength == 0)
            {
            }
            long num = 0L;
            string text = WebHeaderCollection.CheckBadChars(name, num != 0L);
            this.NormalizeCommonHeaders();
            if (this.m_InnerCollection != null)
            {
                base.InvalidateCachedArrays();
                global::System.Collections.Specialized.NameValueCollection innerCollection = this.m_InnerCollection;
                return;
            }
        }
References System.Net.WebHeaderCollection.CheckBadChars(), j__TPar, System.L, System.Net.WebHeaderCollection.m_InnerCollection, System.name, System.Net.WebHeaderCollection.NormalizeCommonHeaders(), System.text, and System.Net.WebHeaderCollection.ThrowOnRestrictedHeader().