terraria-cpp2il-methodrecon: Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemCraft
NotifyItemCraft()
static void Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemCraft (Recipe recipe) inline static
Definition at line 167 of file AchievementsHelper.cs.
        {
            int myPlayer = Main.myPlayer;
            Item createItem = recipe.createItem;
            int netID = createItem.netID;
            int stack = createItem.stack;
            Item createItem2 = recipe.createItem;
            bool flag = AchievementsHelper.IsMetalBar(createItem2.type);
            if (createItem2 == null)
            {
            }
            int myPlayer2 = Main.myPlayer;
            if (createItem == null)
            {
            }
            LocalUser localUser;
            uint totalBarsCrafted;
            if (localUser != null)
            {
                PersistentUserData persistentUserData = localUser.PersistentUserData;
                totalBarsCrafted = persistentUserData.TotalBarsCrafted;
                persistentUserData.TotalBarsCrafted = totalBarsCrafted;
                IPlatformAwardNotifier platformAwards = localUser.PlatformAwards;
                if (totalBarsCrafted != 0U)
                {
                }
                return;
            }
            if (recipe.requiredTile == null)
            {
            }
            int myPlayer3 = Main.myPlayer;
            if (totalBarsCrafted == 0U)
            {
            }
            LocalUser localUser2;
            uint totalAnvilCrafting;
            if (localUser2 != null)
            {
                PersistentUserData persistentUserData2 = localUser2.PersistentUserData;
                totalAnvilCrafting = persistentUserData2.TotalAnvilCrafting;
                persistentUserData2.TotalAnvilCrafting = totalAnvilCrafting;
                IPlatformAwardNotifier platformAwards2 = localUser2.PlatformAwards;
                if (totalAnvilCrafting != 0U)
                {
                }
                return;
            }
            if (recipe.requiredTile == null)
            {
            }
            int myPlayer4 = Main.myPlayer;
            if (totalAnvilCrafting == 0U)
            {
            }
        }
References PersistentUserData.PersistentUserData(), Terraria.Recipe.createItem, Terraria.GameContent.Achievements.AchievementsHelper.IsMetalBar(), j__TPar, Terraria.Main.myPlayer, Terraria.Item.netID, LocalUser.PersistentUserData, LocalUser.PlatformAwards, Terraria.Recipe.requiredTile, System.stack, Terraria.Item.stack, PersistentUserData.TotalBarsCrafted, and System.U.
Referenced by Terraria.Recipe.Create().