terraria-cpp2il-methodrecon: Terraria.GameContent.Achievements.AchievementsHelper.NotifyNPCKilledDirect
NotifyNPCKilledDirect()
static void Terraria.GameContent.Achievements.AchievementsHelper.NotifyNPCKilledDirect (Player player, int npcNetID) inline static
Definition at line 269 of file AchievementsHelper.cs.
        {
            PlatformAwardNotifierUtility.NoteTriggerForPlayer(player, eTrigger.KilledGuideWithWeapon);
            eSlimeKillStatistics slimeStatIDFromNetID = PlatformAwardNotifierUtility.GetSlimeStatIDFromNetID(npcNetID);
            PlatformAwardNotifierUtility.NoteSlimeDefeatedForPlayer(player, slimeStatIDFromNetID);
        }
References PlatformAwardNotifierUtility.GetSlimeStatIDFromNetID(), j__TPar, PlatformAwardNotifierUtility.NoteSlimeDefeatedForPlayer(), and PlatformAwardNotifierUtility.NoteTriggerForPlayer().