terraria-cpp2il-methodrecon: Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent
NotifyProgressionEvent()
static void Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent (int eventID) inline static
Definition at line 277 of file AchievementsHelper.cs.
        {
            if (!true)
            {
            }
            bool netHost = Main.NetHost;
        }
References j__TPar, and Terraria.Main.NetHost.
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.GameContent.Events.BirthdayParty.CheckForAchievement(), Terraria.WorldGen.FinaliseHardModeOnMainThread(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.WorldGen.SpawnTownNPC(), Terraria.Main.UpdateInvasion(), Terraria.Main.UpdateTime_StartDay(), Terraria.Main.UpdateTime_StartNight(), and Terraria.GameContent.Events.DD2Event.WinInvasionInternal().