terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Game.UnityDraw
UnityDraw()
void Microsoft.Xna.Framework.Game.UnityDraw () inline inherited
Definition at line 300 of file Game.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            GeometryBufferInstance.ClearInstances();
            if (num == 0)
            {
            }
            MaterialBuffer.ClearInstances();
            if (num == 0)
            {
            }
            ScreenPostProcessor.BeginUpdate();
            Main.FlushBatches();
            GeometryBufferInstance.FinaliseInstances();
            ScreenPostProcessor.EndUpdate();
        }
References ScreenPostProcessor.BeginUpdate(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.ClearInstances(), Microsoft.Xna.Framework.Graphics.MaterialBuffer.ClearInstances(), ScreenPostProcessor.EndUpdate(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.FinaliseInstances(), and Terraria.Main.FlushBatches().