terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Game.UnityServerUpdate
UnityServerUpdate()
void Microsoft.Xna.Framework.Game.UnityServerUpdate (float elapsedTime) inline inherited
Definition at line 149 of file Game.cs.
        {
            bool serverRunning = this._serverRunning;
            if (serverRunning)
            {
                TimeSpan totalTime = this._totalTime;
                if (!serverRunning)
                {
                }
                DateTime now = DateTime.Now;
                DateTime lastUpdate = this._lastUpdate;
                TimeSpan timeSpan = now - lastUpdate;
                TimeSpan timeSpan2 = TimeSpan.FromSeconds((double)elapsedTime);
                bool flag = timeSpan > timeSpan2;
                DateTime now2 = DateTime.Now;
                DateTime dateTime;
                this._lastUpdate = dateTime;
                DateTime now3 = DateTime.Now;
                DateTime lastUpdate2 = this._lastUpdate;
                TimeSpan timeSpan3 = now3 - lastUpdate2;
                WorldGen.ExecuteThreadTime();
                bool serverRunning2 = this._serverRunning;
                if (serverRunning2)
                {
                    if (!serverRunning2)
                    {
                    }
                    Netplay.ServerLoopUpdateFrame();
                    Netplay.ServerUpdateFrame();
                }
                DateTime lastUpdate3 = this._lastUpdate;
                if (!serverRunning2)
                {
                }
                DateTime dateTime2;
                this._lastUpdate = dateTime2;
                TimeSpan totalTime2 = this._totalTime;
                TimeSpan timeSpan4;
                this._totalTime = timeSpan4;
                return;
            }
        }
References Microsoft.Xna.Framework.Game._lastUpdate, Microsoft.Xna.Framework.Game._serverRunning, Microsoft.Xna.Framework.Game._totalTime, Terraria.WorldGen.ExecuteThreadTime(), System.TimeSpan.FromSeconds(), j__TPar, System.DateTime.Now, Terraria.Netplay.ServerLoopUpdateFrame(), and Terraria.Netplay.ServerUpdateFrame().