terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Game.UnityUpdate
UnityUpdate()
void Microsoft.Xna.Framework.Game.UnityUpdate (float elapsedTime) inline inherited
Definition at line 193 of file Game.cs.
        {
            bool initialised = this._initialised;
            if (!initialised)
            {
                return;
            }
            if (!initialised)
            {
            }
            Main.UpdateTrialMode();
            int num;
            if (!this._uiHidden)
            {
                num = 1;
                this._uiHidden = num != 0;
            }
            if (num == 0)
            {
            }
            bool flag = TextureAtlasDB.PendingAssetUnload();
            DateTime now = DateTime.Now;
            DateTime lastUpdate = this._lastUpdate;
            TimeSpan timeSpan = now - lastUpdate;
            bool flag2 = this.highFrameRate;
            if (flag2)
            {
                if (!flag2)
                {
                }
                if (!flag2)
                {
                }
                TimeSpan timeSpan2;
                Thread.Sleep(timeSpan2);
                DateTime now2 = DateTime.Now;
                DateTime lastUpdate2 = this._lastUpdate;
                TimeSpan timeSpan3 = now2 - lastUpdate2;
                return;
            }
            DateTime now3 = DateTime.Now;
            int num2 = this.updateCount;
            this.updateCount = num2;
            DateTime dateTime = this.updateTimeStart;
            if (num2 == 0)
            {
            }
            double totalMilliseconds = (now3 - dateTime).TotalMilliseconds;
            int num3 = this.updateCount;
            this.updateTimeStart = now3;
            this.fpsCount = num3;
            int num4 = 1;
            this.highFrameRate = num4 != 0;
            int num5;
            if (!this.updateModeVariable)
            {
                num5 = 1;
                this.updateModeVariable = num5 != 0;
                return;
            }
            if (num5 == 0)
            {
            }
            Main.ProcessAsyncLoad();
            if (num5 == 0)
            {
            }
            TextureAtlasDB.ActionPendingUnloadAssets(false);
            this.UnityUpdate((float)totalMilliseconds);
            if (num5 == 0)
            {
            }
            TimeSpan totalTime = this._totalTime;
            DateTime lastUpdate3 = this._lastUpdate;
            if (num5 == 0)
            {
            }
            TimeSpan timeSpan4 = now3 - lastUpdate3;
            TimeSpan timeSpan5 = TimeSpan.FromSeconds(totalMilliseconds);
            bool flag3 = timeSpan4 > timeSpan5;
            DateTime dateTime2;
            this._lastUpdate = dateTime2;
            TimeSpan timeSpan6 = now3 - dateTime2;
            DateTime lastUpdate4 = this._lastUpdate;
            TimeSpan timeSpan7 = now3 - lastUpdate4;
            Netplay.UpdateClientNet();
            bool serverRunning = this._serverRunning;
            if (serverRunning)
            {
                if (!serverRunning)
                {
                }
                Netplay.ServerLoopUpdateFrame();
                Netplay.ServerUpdateFrame();
            }
            DateTime lastUpdate5 = this._lastUpdate;
            if (!serverRunning)
            {
            }
            DateTime dateTime3;
            this._lastUpdate = dateTime3;
            TimeSpan totalTime2 = this._totalTime;
            TimeSpan timeSpan8;
            this._totalTime = timeSpan8;
        }
References Microsoft.Xna.Framework.Game._initialised, Microsoft.Xna.Framework.Game._lastUpdate, Microsoft.Xna.Framework.Game._serverRunning, Microsoft.Xna.Framework.Game._totalTime, Microsoft.Xna.Framework.Game._uiHidden, TextureAtlasDB.ActionPendingUnloadAssets(), System.TimeSpan.FromSeconds(), Microsoft.Xna.Framework.Game.highFrameRate, j__TPar, System.DateTime.Now, TextureAtlasDB.PendingAssetUnload(), Terraria.Main.ProcessAsyncLoad(), Terraria.Netplay.ServerLoopUpdateFrame(), Terraria.Netplay.ServerUpdateFrame(), System.Threading.Thread.Sleep(), Microsoft.Xna.Framework.Game.UnityUpdate(), Terraria.Netplay.UpdateClientNet(), Microsoft.Xna.Framework.Game.updateCount, Microsoft.Xna.Framework.Game.updateModeVariable, Microsoft.Xna.Framework.Game.updateTimeStart, and Terraria.Main.UpdateTrialMode().
Referenced by Microsoft.Xna.Framework.Game.UnityUpdate().