terraria-cpp2il-methodrecon: Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes
SetPropertySettingsFromAttributes()
void Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes (JsonProperty property, object attributeProvider, string name, Type declaringType, MemberSerialization memberSerialization, [Out] bool allowNonPublicAccess) inline private
Definition at line 784 of file DefaultContractResolver.cs.
        {
            if (!true)
            {
            }
            DataContractAttribute dataContractAttribute = JsonTypeReflector.GetDataContractAttribute(declaringType);
            if (attributeProvider != null)
            {
            }
            long num = 0L;
            JsonPropertyAttribute attribute = JsonTypeReflector.GetAttribute<JsonPropertyAttribute>(attributeProvider);
            JsonRequiredAttribute attribute2 = JsonTypeReflector.GetAttribute<JsonRequiredAttribute>(attributeProvider);
            if ((attribute != null && attribute.<PropertyName>k__BackingField != null) || num != 0L)
            {
            }
            property.<UnderlyingName>k__BackingField = name;
            int num2;
            bool? itemIsReference;
            if (attribute == null)
            {
                while (num2 == 0)
                {
                }
                property._required = itemIsReference;
                return;
            }
            DefaultValueHandling? defaultValueHandling = attribute._defaultValueHandling;
            property.<DefaultValueHandling>k__BackingField = defaultValueHandling;
            if (attribute2 != null)
            {
                num2 = 1;
                property._required = defaultValueHandling;
            }
            property.<HasMemberAttribute>k__BackingField = num2 != 0;
            if (defaultValueHandling == null)
            {
            }
            BindingFlags bindingFlags;
            Type <ItemConverterType>k__BackingField;
            if (JsonTypeReflector.GetAttribute<JsonIgnoreAttribute>(attributeProvider) == null)
            {
                if (defaultValueHandling == null)
                {
                }
                if (JsonTypeReflector.GetAttribute<JsonExtensionDataAttribute>(attributeProvider) == null)
                {
                    if (bindingFlags == BindingFlags.Default)
                    {
                    }
                    NonSerializedAttribute attribute3 = JsonTypeReflector.GetAttribute<NonSerializedAttribute>(<ItemConverterType>k__BackingField);
                    return;
                }
            }
            int num3 = 1;
            property.<Ignored>k__BackingField = num3 != 0;
            if (num3 == 0)
            {
            }
            JsonConverter jsonConverter = JsonTypeReflector.GetJsonConverter(attributeProvider);
            property.<Converter>k__BackingField = jsonConverter;
            JsonConverter jsonConverter2 = JsonTypeReflector.GetJsonConverter(attributeProvider);
            property.<MemberConverter>k__BackingField = jsonConverter2;
            DefaultValueAttribute attribute4 = JsonTypeReflector.GetAttribute<DefaultValueAttribute>(attributeProvider);
            if (attribute4 != null)
            {
                int num4 = 1;
                property._hasExplicitDefaultValue = num4 != 0;
                property._defaultValue = attribute4;
            }
            if (attribute == null)
            {
                return;
            }
            NullValueHandling? nullValueHandling = attribute._nullValueHandling;
            ReferenceLoopHandling? referenceLoopHandling = attribute._referenceLoopHandling;
            ObjectCreationHandling? objectCreationHandling = attribute._objectCreationHandling;
            TypeNameHandling? typeNameHandling = attribute._typeNameHandling;
            bool? isReference = attribute._isReference;
            itemIsReference = attribute._itemIsReference;
            <ItemConverterType>k__BackingField = attribute.<ItemConverterType>k__BackingField;
            if (<ItemConverterType>k__BackingField != null)
            {
                object[] <ItemConverterParameters>k__BackingField = attribute.<ItemConverterParameters>k__BackingField;
                if (itemIsReference == null)
                {
                }
                JsonConverter jsonConverter3 = JsonTypeReflector.CreateJsonConverterInstance(<ItemConverterType>k__BackingField, <ItemConverterParameters>k__BackingField);
                return;
            }
            long num5 = 0L;
            property.<ItemConverter>k__BackingField = num5;
            ReferenceLoopHandling? itemReferenceLoopHandling = attribute._itemReferenceLoopHandling;
            TypeNameHandling? itemTypeNameHandling = attribute._itemTypeNameHandling;
            bindingFlags = this.<DefaultMembersSearchFlags>k__BackingField;
            allowNonPublicAccess.m_value = bindingFlags != BindingFlags.Default;
        }
References Newtonsoft.Json.JsonPropertyAttribute._defaultValueHandling, Newtonsoft.Json.JsonPropertyAttribute._isReference, Newtonsoft.Json.JsonPropertyAttribute._itemIsReference, Newtonsoft.Json.JsonPropertyAttribute._itemReferenceLoopHandling, Newtonsoft.Json.JsonPropertyAttribute._itemTypeNameHandling, Newtonsoft.Json.JsonPropertyAttribute._nullValueHandling, Newtonsoft.Json.JsonPropertyAttribute._objectCreationHandling, Newtonsoft.Json.JsonPropertyAttribute._referenceLoopHandling, Newtonsoft.Json.JsonPropertyAttribute._typeNameHandling, Newtonsoft.Json.Serialization.JsonTypeReflector.CreateJsonConverterInstance(), Newtonsoft.Json.Serialization.DefaultContractResolver.DefaultMembersSearchFlags, Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataContractAttribute(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetJsonConverter(), j__TPar, Newtonsoft.Json.Serialization.DefaultContractResolver.k__BackingField, System.L, System.name, and Newtonsoft.Json.PropertyName.