terraria-cpp2il-methodrecon: System.Net.NetworkInformation.MacOsStructs.sockaddr_dl.Read
Read()
void System.Net.NetworkInformation.MacOsStructs.sockaddr_dl.Read (IntPtr ptr) inline package
Definition at line 10 of file sockaddr_dl.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            long num2 = 0L;
            byte b = Marshal.ReadByte(ptr, (int)num2);
            this.sdl_len = b;
            int num3 = 1;
            byte b2 = Marshal.ReadByte(ptr, num3);
            this.sdl_family = b2;
            int num4 = 2;
            short num5 = Marshal.ReadInt16(ptr, num4);
            this.sdl_index = (ushort)num5;
            int num6 = 4;
            byte b3 = Marshal.ReadByte(ptr, num6);
            this.sdl_type = b3;
            int num7 = 5;
            byte b4 = Marshal.ReadByte(ptr, num7);
            this.sdl_nlen = b4;
            int num8 = 6;
            byte b5 = Marshal.ReadByte(ptr, num8);
            this.sdl_alen = b5;
            int num9 = 7;
            byte b6 = Marshal.ReadByte(ptr, num9);
            this.sdl_slen = b6;
            if (num == 0)
            {
            }
            int num10 = Math.Max(12, num9);
            byte[] array = this.sdl_data;
        }
References System.array, j__TPar, System.L, System.Math.Max(), System.Runtime.InteropServices.Marshal.ReadByte(), System.Runtime.InteropServices.Marshal.ReadInt16(), and System.Net.NetworkInformation.MacOsStructs.sockaddr_dl.sdl_data.