terraria-cpp2il-methodrecon: UnityEngine.Resources.Load
Load() [1/2]
static Object UnityEngine.Resources.Load (string path) inline static
Definition at line 20 of file Resources.cs.
        {
            if (!true)
            {
            }
            Object @object;
            return @object;
        }
Referenced by CSVReader.Begin(), Microsoft.Xna.Framework.Content.ContentManager.ConstructFromUnityResources< ResourceType >(), Microsoft.Xna.Framework.Content.ContentManager.ConstructFromUnityResources< ResourceType >(), UnityEngine.ResourceRequest.GetResult(), Terraria.IO.WorldFile.GetTutorialMetadata(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Initialize(), Terraria.WorldBuilding.WorldGenConfiguration.LoadOnMainThread(), LayoutDefinition.LoadReleaseLayout(), Terraria.IO.WorldFile.LoadTutorialOnMainThread(), Terraria.Player.LoadTutorialPlayer(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), and Microsoft.Xna.Framework.Content.ContentManager.TextureLoadEntry.Update().