terraria-cpp2il-methodrecon: UnityEngine.UI.Graphic.OnDisable
OnDisable()
override void UnityEngine.UI.Graphic.OnDisable () inline protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
Reimplemented in UnityEngine.UI.Image, UnityEngine.UI.MaskableGraphic, and UnityEngine.UI.Text.
Definition at line 410 of file Graphic.cs.
        {
            GraphicRegistry.DisableGraphicForCanvas(this.canvas, this);
            CanvasUpdateRegistry.DisableCanvasElementForRebuild(this);
            CanvasRenderer canvasRenderer = this.canvasRenderer;
            this.canvasRenderer.Clear();
            LayoutRebuilder.MarkLayoutForRebuild(this.rectTransform);
            base.OnDisable();
        }
References UnityEngine.UI.Graphic.canvas, UnityEngine.UI.Graphic.canvasRenderer, UnityEngine.CanvasRenderer.Clear(), UnityEngine.UI.CanvasUpdateRegistry.DisableCanvasElementForRebuild(), UnityEngine.UI.GraphicRegistry.DisableGraphicForCanvas(), j__TPar, UnityEngine.UI.LayoutRebuilder.MarkLayoutForRebuild(), and UnityEngine.UI.Graphic.rectTransform.
Referenced by UnityEngine.UI.BaseMeshEffect.OnDisable().