terraria-cpp2il-methodrecon: GUIInstance.ClosePopups
ClosePopups()
void GUIInstance.ClosePopups () inline
Definition at line 11 of file GUIInstance.cs.
    {
        GUIInventorySplitStack guiinventorySplitStack = this.GUIInventorySplitStack;
        this.GUIChestSplitStack.Close();
        this.GUIBuilderAccToggles.Close();
        GUIPVPIcons guipvpicons = this.GUIPVPIcons;
        this.GUIAccessoryInfoToggles.CloseExpandedFilter();
        this.GUIEquipmentLoadout.CloseExpandedFilter();
        this.GUICrafting.Filter.CloseExpandedFilter();
        this.GUIItemDuplication.Filter.CloseExpandedFilter();
    }
References GUIBuilderAccToggles.Close(), GUIChestSplitStack.Close(), GUIAccessoryInfoToggles.CloseExpandedFilter(), GUIEquipmentLoadout.CloseExpandedFilter(), GUIItemFilter.CloseExpandedFilter(), GUICrafting.Filter, GUIItemDuplication.Filter, GUIInventorySplitStack, GUIPVPIcons, and j__TPar.
Referenced by CloseDialoguesAndPopups().