terraria-cpp2il-methodrecon: UnityEngine.UI.Graphic.SetRaycastDirty
SetRaycastDirty()
void UnityEngine.UI.Graphic.SetRaycastDirty () inline inherited
Definition at line 205 of file Graphic.cs.
        {
            bool raycastTargetCache = this.m_RaycastTargetCache;
            if (this.m_RaycastTarget)
            {
                bool isActiveAndEnabled = base.isActiveAndEnabled;
                Canvas canvas = this.canvas;
                if (!raycastTargetCache)
                {
                }
                GraphicRegistry.RegisterRaycastGraphicForCanvas(canvas, this);
                return;
            }
            Canvas canvas2 = this.canvas;
            if (!raycastTargetCache)
            {
            }
            GraphicRegistry.UnregisterRaycastGraphicForCanvas(canvas2, this);
            bool raycastTarget = this.m_RaycastTarget;
            this.m_RaycastTargetCache = raycastTarget;
        }
References UnityEngine.UI.Graphic.canvas, UnityEngine.Behaviour.isActiveAndEnabled, j__TPar, UnityEngine.UI.Graphic.m_RaycastTarget, UnityEngine.UI.Graphic.m_RaycastTargetCache, UnityEngine.UI.Graphic.raycastTarget, UnityEngine.UI.GraphicRegistry.RegisterRaycastGraphicForCanvas(), and UnityEngine.UI.GraphicRegistry.UnregisterRaycastGraphicForCanvas().
Referenced by UnityEngine.UI.Graphic.SetAllDirty().