terraria-cpp2il-methodrecon: GUIInstance.CloseDialoguesAndPopups
CloseDialoguesAndPopups()
void GUIInstance.CloseDialoguesAndPopups () inline
Definition at line 24 of file GUIInstance.cs.
    {
        this.ClosePopups();
        this.GUIWiresUI.Close();
        this.GUIRubbleMaker.Close();
        this.GUIResearch.Close();
        this.GUIReforgePopup.ClosePopup();
        this.GUICraftGuidePopup.ClosePopup();
        GUIEmotesWindow guiemotesWindow = this.GUIEmotesWindow;
        long num = 0L;
        guiemotesWindow.SetDisplayingEmotes(num != 0L);
        if (this.GUIPVPIcons == null)
        {
        }
        Main.CancelClothesWindow(false);
        Main.CancelHairWindow();
    }
References Terraria.Main.CancelClothesWindow(), Terraria.Main.CancelHairWindow(), GUIResearch.Close(), GUIRubbleMaker.Close(), GUIWiresUI.Close(), GUICraftGuidePopup.ClosePopup(), GUIReforgePopup.ClosePopup(), ClosePopups(), GUIEmotesWindow, j__TPar, System.L, and GUIEmotesWindow.SetDisplayingEmotes().