terraria-cpp2il-methodrecon: Mono.Security.Authenticode.AuthenticodeDeformatter.VerifyCounterSignature
VerifyCounterSignature()
bool Mono.Security.Authenticode.AuthenticodeDeformatter.VerifyCounterSignature (PKCS7::SignerInfo cs, byte[] signature) inline private
Definition at line 165 of file AuthenticodeDeformatter.cs.
        {
            byte version = cs.version;
            ArrayList authenticatedAttributes = cs.authenticatedAttributes;
            if (cs.authenticatedAttributes != null)
            {
            }
            ASN1 asn;
            string text = ASN1Convert.ToOid(asn);
            bool flag = text == "1.2.840.113549.1.9.3";
            long num = 0L;
            ASN1 asn2;
            string text2 = ASN1Convert.ToOid(asn2[(int)num]);
            bool flag2 = text == "1.2.840.113549.1.9.4";
            long num2 = 0L;
            ASN1 asn4;
            ASN1 asn3 = asn4[(int)num2];
            bool flag3 = text == "1.2.840.113549.1.9.5";
            long num3 = 0L;
            ASN1 asn5;
            DateTime dateTime = ASN1Convert.ToDateTime(asn5[(int)num3]);
            ArrayList authenticatedAttributes2 = cs.authenticatedAttributes;
            long num4 = 0L;
            ArrayList authenticatedAttributes3;
            if (num4 != 0L)
            {
                byte[] array = HashAlgorithm.Create("SHA256").ComputeHash(signature);
                byte[] signature2 = cs.Signature;
                authenticatedAttributes3 = cs.authenticatedAttributes;
                if (authenticatedAttributes3 != null)
                {
                }
            }
            long num5 = 0L;
            int num6 = 21;
            if (authenticatedAttributes3 != null)
            {
            }
            if (num5 == 0L)
            {
                while (num6 != 0)
                {
                }
                string issuer = cs.issuer;
                byte[] serialNumber = cs.SerialNumber;
                X509CertificateCollection.X509CertificateEnumerator x509CertificateEnumerator;
                bool flag4 = x509CertificateEnumerator.MoveNext();
                X509Certificate x509Certificate = x509CertificateEnumerator.Current;
                if (num5 != 0L)
                {
                }
                bool flag5;
                return flag5;
            }
            throw new OutOfMemoryException();
        }
References System.array, System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.Create(), j__TPar, System.L, Mono.Security.X509.X509CertificateCollection.X509CertificateEnumerator.MoveNext(), System.text, Mono.Security.ASN1Convert.ToDateTime(), and Mono.Security.ASN1Convert.ToOid().