terraria-cpp2il-methodrecon: Terraria.Graphics.Light.LegacyLighting.PreRenderPhase
PreRenderPhase()
void Terraria.Graphics.Light.LegacyLighting.PreRenderPhase (Rectangle area) inline private
Definition at line 266 of file LegacyLighting.cs.
        {
            if (!true)
            {
            }
            this._workingLightMap.Clear();
            int num = 20;
            int num2 = 20;
            this._workingLightMap.SetSize(num, num2);
            SceneMetrics sceneMetrics = Main.SceneMetrics;
            Vector2 center = Main.LocalPlayer.Center;
            bool accOreFinder = Main.LocalPlayer.accOreFinder;
            this._tileScanner.Update();
            int width = this._workingProcessedArea.Width;
            TileLightScanner tileScanner = this._tileScanner;
            LightMap workingLightMap = this._workingLightMap;
            Rectangle workingProcessedArea = this._workingProcessedArea;
            if (!accOreFinder)
            {
            }
            Vector3[] colors = this._workingLightMap._colors;
            if (colors != null)
            {
                return;
            }
            if (colors == null)
            {
            }
            if (colors == null)
            {
            }
            float z = colors.Z;
            LightMap workingLightMap2 = this._workingLightMap;
            Rectangle workingProcessedArea2 = this._workingProcessedArea;
            int width2 = this._workingProcessedArea.Width;
            int <Height>k__BackingField = workingLightMap2.<Height>k__BackingField;
        }
References Terraria.Graphics.Light.LightMap._colors, Terraria.Graphics.Light.LegacyLighting._tileScanner, Terraria.Graphics.Light.LegacyLighting._workingLightMap, Terraria.Graphics.Light.LegacyLighting._workingProcessedArea, Terraria.Player.accOreFinder, Terraria.Entity.Center, Terraria.Graphics.Light.LightMap.Clear(), j__TPar, Terraria.Graphics.Light.LegacyLighting.k__BackingField, Terraria.Main.LocalPlayer, Terraria.Main.SceneMetrics, Terraria.Graphics.Light.LightMap.SetSize(), Terraria.Graphics.Light.TileLightScanner.Update(), Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Vector3.Z.