terraria-cpp2il-methodrecon: Terraria.Main.UpdateTime_StartDay
UpdateTime_StartDay()
static void Terraria.Main.UpdateTime_StartDay (bool stopEvents) inline static
Definition at line 17991 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            WorldGen.ResetTreeShakes();
            if (num == 0)
            {
            }
            Main.UpdateTimeRate();
            Main.AnglerQuestSwap();
            BirthdayParty.CheckMorning();
            LanternNight.CheckMorning();
            bool logicHost = Main.LogicHost;
            AchievementsHelper.NotifyProgressionEvent(5);
            Main.CheckForMoonEventsScoreDisplay();
            Main.CheckForMoonEventsStartingTemporarySeasons();
            Main.checkXMas();
            Main.checkHalloween();
            Main.stopMoonEvent();
            int num2 = 1;
            if (num2 == 0)
            {
            }
            bool logicHost2 = Main.LogicHost;
            bool netHost = Main.NetHost;
            bool logicHost3 = Main.LogicHost;
            AchievementsHelper.NotifyProgressionEvent(1);
            int num3;
            if (num3 != 0)
            {
                int num4;
                if (num4 != 0)
                {
                    return;
                }
                Main.StartInvasion(1);
                int num5;
                if (num5 != 0)
                {
                    return;
                }
                if (num5 == 0)
                {
                }
                int num6;
                if (num6 != 0)
                {
                    int num7;
                    while (num7 != 0)
                    {
                    }
                }
                Main.StartInvasion(3);
                return;
            }
            else
            {
                int num5 = 1;
                AchievementsHelper.NotifyProgressionEvent(2);
                if (num5 != 0)
                {
                    if (num5 != 0)
                    {
                        if (num2 != 0)
{
                            if (num5 == 0)
{
                            }
                            return;
                        }
                    }
                    else if (num5 == 0)
                    {
                    }
                    if (num5 == 0)
                    {
                    }
                    if (num5 == 0)
                    {
                    }
                    return;
                }
                bool netHost2 = Main.NetHost;
                return;
            }
        }
References Terraria.Main.AnglerQuestSwap(), Terraria.Main.CheckForMoonEventsScoreDisplay(), Terraria.Main.CheckForMoonEventsStartingTemporarySeasons(), Terraria.Main.checkHalloween(), Terraria.GameContent.Events.BirthdayParty.CheckMorning(), Terraria.GameContent.Events.LanternNight.CheckMorning(), Terraria.Main.checkXMas(), j__TPar, Terraria.Main.LogicHost, Terraria.Main.NetHost, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.WorldGen.ResetTreeShakes(), Terraria.Main.StartInvasion(), Terraria.Main.stopMoonEvent(), and Terraria.Main.UpdateTimeRate().