terraria-cpp2il-methodrecon: Terraria.Main.CancelHairWindow
CancelHairWindow()
static void Terraria.Main.CancelHairWindow () inline static
Definition at line 12319 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            bool hairWindow = Main.hairWindow;
            if (num == 0)
            {
            }
            int myPlayer = Main.myPlayer;
            int oldHairStyle = Main.oldHairStyle;
            int myPlayer2 = Main.myPlayer;
            Microsoft.Xna.Framework.Graphics.Color oldHairColor = Main.oldHairColor;
            Main.hairWindow = false;
            int myPlayer3 = Main.myPlayer;
            int myPlayer4 = Main.myPlayer;
            int myPlayer5 = Main.myPlayer;
        }
References Terraria.Main.hairWindow, j__TPar, Terraria.Main.myPlayer, Terraria.Main.oldHairColor, and Terraria.Main.oldHairStyle.
Referenced by GUIPageIcons.Close(), GUIInstance.CloseDialoguesAndPopups(), GUIInstance.CloseNonPageDialogues(), GUIHairWindow.Draw(), and GUIHairWindow.DrawCancelButton().