terraria-cpp2il-methodrecon: Terraria.Main.RenderBlack
RenderBlack()
void Terraria.Main.RenderBlack () inline protected
Definition at line 15255 of file Main.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
                GraphicsDevice graphicsDevice = base.GraphicsDevice;
                RenderTarget2D renderTarget2D = this.blackTarget;
                graphicsDevice.SetRenderTarget(renderTarget2D);
                GraphicsDevice graphicsDevice2 = base.GraphicsDevice;
                GraphicsDevice graphicsDevice3 = base.GraphicsDevice;
                TimeLogger.DetailedDrawReset();
                Main.FlushBatches();
                TimeLogger.DetailedDrawTime(30);
                GraphicsDevice graphicsDevice4 = base.GraphicsDevice;
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Terraria.Main.blackTarget, Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.FlushBatches(), Microsoft.Xna.Framework.Game.graphicsDevice, j__TPar, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget().
Referenced by Terraria.Main.RenderTiles().