terraria-cpp2il-methodrecon: Terraria.Main.DrawSurfaceBG_Corrupt
DrawSurfaceBG_Corrupt()
void Terraria.Main.DrawSurfaceBG_Corrupt (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 16539 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            float num2 = this.scAdj;
            int num3 = 32768;
            long num4 = -1717986919L;
            this.bgParallax = (double)num4;
            this.bgTopY = num;
            this.SetBackgroundOffsets(pushBGTopHack, backgroundTopMagicNumber, pushBGTopHack);
            this.LoadBackground(pushBGTopHack);
            if (num3 != 0)
            {
                if (num3 == 0)
                {
                }
                if (num3 != 0)
                {
                    if (num3 == 0)
                    {
                    }
                    int num5 = 32640;
                    int num6 = 32768;
                    if (num5 == 0)
                    {
                    }
                    double num7 = this.bgParallax;
                    Microsoft.Xna.Framework.Vector2 screenPosition = Main.screenPosition;
                    double num8 = this.bgParallax;
                    double num9 = Math.IEEERemainder(num7, (double)0f);
                    this.bgStartX = int.MinValue;
                    bool gameMenu = Main.gameMenu;
                    this.bgTopY = int.MinValue;
                    int num10 = this.bgTopY;
                    this.bgTopY = num10;
                    if (num10 == 0)
                    {
                    }
                    int screenWidth = Main.screenWidth;
                    this.bgLoops = int.MinValue;
                    Microsoft.Xna.Framework.Vector2 screenPosition2 = Main.screenPosition;
                    if (this.bgLoops == 0)
                    {
                    }
                    if (num6 == 0)
                    {
                    }
                    int num11 = this.bgTopY;
                    int num12 = this.bgStartX;
                    long num13 = 0L;
                    int num14 = this.bgLoops;
                    if (num14 == 0)
                    {
                    }
                    int num15 = 44564;
                    float num16 = this.scAdj;
                    long num17 = 60293L;
                    int num18 = 32768;
                    this.bgParallax = (double)num17;
                    this.bgTopY = num14;
                    this.SetBackgroundOffsets((int)num13, backgroundTopMagicNumber, pushBGTopHack);
                    this.LoadBackground((int)num13);
                    if (num15 == 0)
                    {
                    }
                    double num19 = this.bgParallax;
                    Microsoft.Xna.Framework.Vector2 screenPosition3 = Main.screenPosition;
                    double num20 = this.bgParallax;
                    double num21 = Math.IEEERemainder(num19, (double)0f);
                    int num22 = 32768;
                    this.bgStartX = int.MinValue;
                    bool gameMenu2 = Main.gameMenu;
                    int num23 = this.bgStartX;
                    this.bgTopY = num22;
                    this.bgStartX = num23;
                    int num24 = this.bgTopY;
                    this.bgTopY = num24;
                    if (num24 == 0)
                    {
                    }
                    if (num22 == 0)
                    {
                        if (num22 == 0)
{
                        }
                    }
                    if (num24 == 0)
                    {
                    }
                    int screenWidth2 = Main.screenWidth;
                    this.bgLoops = int.MinValue;
                    Microsoft.Xna.Framework.Vector2 screenPosition4 = Main.screenPosition;
                    int num27;
                    if (num18 != 0)
                    {
                        if (this.bgLoops == 0)
{
                        }
                        int num25 = this.bgStartX;
                        int num26 = this.bgTopY;
                        num27 = this.bgLoops;
                    }
                    if (num27 == 0)
                    {
                    }
                    int num28 = 34079;
                    float num29 = this.scAdj;
                    int num30 = 32640;
                    long num31 = 36700L;
                    this.bgParallax = (double)num31;
                    this.bgTopY = num27;
                    this.SetBackgroundOffsets(num18, backgroundTopMagicNumber, pushBGTopHack);
                    this.LoadBackground(num18);
                    int num32;
                    if (num28 == 0)
                    {
                        if (num28 == 0)
{
                        }
                        num32 = 150;
                    }
                    if (num32 == 0)
                    {
                    }
                    if (num32 == 0)
                    {
                    }
                    double num33 = this.bgParallax;
                    Microsoft.Xna.Framework.Vector2 screenPosition5 = Main.screenPosition;
                    double num34 = this.bgParallax;
                    double num35 = Math.IEEERemainder(num33, (double)0f);
                    int num36 = 32768;
                    this.bgStartX = int.MinValue;
                    bool gameMenu3 = Main.gameMenu;
                    int num37 = this.bgStartX;
                    this.bgTopY = num36;
                    this.bgStartX = num37;
                    int num38 = this.bgTopY;
                    this.bgTopY = num38;
                    if (num38 == 0)
                    {
                    }
                    int screenWidth3 = Main.screenWidth;
                    this.bgLoops = int.MinValue;
                    Microsoft.Xna.Framework.Vector2 screenPosition6 = Main.screenPosition;
                    if (this.bgLoops == 0)
                    {
                    }
                    if (num30 == 0)
                    {
                    }
                    int num39 = this.bgTopY;
                    int num40 = this.bgStartX;
                    int num41 = this.bgLoops;
                    return;
                }
            }
        }
References Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.gameMenu, System.Math.IEEERemainder(), j__TPar, Microsoft.Xna.Framework.Input.L, Terraria.Main.LoadBackground(), Terraria.Main.scAdj, Terraria.Main.screenPosition, Terraria.Main.screenWidth, and Terraria.Main.SetBackgroundOffsets().