terraria-cpp2il-methodrecon: Terraria.Main.ResetWindCounter
ResetWindCounter()
static void Terraria.Main.ResetWindCounter (bool resetExtreme = false) inline static
Definition at line 15466 of file Main.cs.
        {
            int num = FastRandom.CreateWithRandomSeed().Next(900, 2701);
        }
References Terraria.Utilities.FastRandom.CreateWithRandomSeed(), and Terraria.Utilities.FastRandom.Next().
Referenced by Terraria.WorldGen.clearWorld().