terraria-cpp2il-methodrecon: Terraria.Main.SaveSettings
SaveSettings()
static bool Terraria.Main.SaveSettings () inline static
Definition at line 5792 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            Main.SettingsSavePending = false;
            if (num == 0)
            {
            }
            DateTime now = DateTime.Now;
            Preferences configuration = Main.Configuration;
            bool mapEnabled = Main.mapEnabled;
            Preferences configuration2 = Main.Configuration;
            Preferences configuration3 = Main.Configuration;
            int invasionProgressMode = Main.invasionProgressMode;
            Preferences configuration4 = Main.Configuration;
            bool autoSave = Main.autoSave;
            Preferences configuration5 = Main.Configuration;
            Preferences configuration6 = Main.Configuration;
            Main.AutoPauseMode autoPause = Main.autoPause;
            Preferences configuration7 = Main.Configuration;
            Preferences configuration8 = Main.Configuration;
            Preferences configuration9 = Main.Configuration;
            Preferences configuration10 = Main.Configuration;
            Preferences configuration11 = Main.Configuration;
            Preferences configuration12 = Main.Configuration;
            Preferences configuration13 = Main.Configuration;
            Preferences configuration14 = Main.Configuration;
            Preferences configuration15 = Main.Configuration;
            Preferences configuration16 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration17 = Main.Configuration;
            Preferences configuration18 = Main.Configuration;
            if ("CameraMovementMode" != null)
            {
            }
            Preferences configuration19 = Main.Configuration;
            bool placementPreview = Main.placementPreview;
            Preferences configuration20 = Main.Configuration;
            bool disabled = ChildSafety.Disabled;
            Preferences configuration21 = Main.Configuration;
            Preferences configuration22 = Main.Configuration;
            Preferences configuration23 = Main.Configuration;
            Preferences configuration24 = Main.Configuration;
            bool disableIntenseVisualEffects = Main.DisableIntenseVisualEffects;
            string text;
            Main.Configuration.Put("PlayerResourcesSet", text);
            string text2;
            Main.Configuration.Put("MinimapFrame", text2);
            Preferences configuration25 = Main.Configuration;
            bool useLargeMinimap = Map_Layout.UseLargeMinimap;
            Preferences configuration26 = Main.Configuration;
            int tooltipTime = Main.tooltipTime;
            Preferences configuration27 = Main.Configuration;
            int inventoryTooltipTime = Main.inventoryTooltipTime;
            Preferences configuration28 = Main.Configuration;
            bool settingsEnabled_OpaqueBoxBehindTooltips = Main.SettingsEnabled_OpaqueBoxBehindTooltips;
            Preferences configuration29 = Main.Configuration;
            VirtualControlsProfile_Layout virtualControlsProfile_Layout;
            string id = virtualControlsProfile_Layout.Id;
            configuration29.Put("TouchControlsProfile", id);
            Preferences configuration30 = Main.Configuration;
            float soundVolume = Main.soundVolume;
            Preferences configuration31 = Main.Configuration;
            float ambientVolume = Main.ambientVolume;
            Preferences configuration32 = Main.Configuration;
            float musicVolume = Main.musicVolume;
            Preferences configuration33 = Main.Configuration;
            bool towmusicUnlocked = Main.TOWMusicUnlocked;
            Preferences configuration34 = Main.Configuration;
            Preferences configuration35 = Main.Configuration;
            Preferences configuration36 = Main.Configuration;
            Preferences configuration37 = Main.Configuration;
            Preferences configuration38 = Main.Configuration;
            int qaStyle = Main.qaStyle;
            Preferences configuration39 = Main.Configuration;
            bool backgroundEnabled = Main.BackgroundEnabled;
            Preferences configuration40 = Main.Configuration;
            Preferences configuration41 = Main.Configuration;
            LightMode mode = Lighting.Mode;
            Preferences configuration42 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseColor = Main.mouseColor;
            Preferences configuration43 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseColor2 = Main.mouseColor;
            Preferences configuration44 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseColor3 = Main.mouseColor;
            Preferences configuration45 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseBorderColor = Main.MouseBorderColor;
            Preferences configuration46 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseBorderColor2 = Main.MouseBorderColor;
            Preferences configuration47 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseBorderColor3 = Main.MouseBorderColor;
            Preferences configuration48 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color mouseBorderColor4 = Main.MouseBorderColor;
            Preferences configuration49 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerColor = Main.ControllerColor;
            Preferences configuration50 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerColor2 = Main.ControllerColor;
            Preferences configuration51 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerColor3 = Main.ControllerColor;
            Preferences configuration52 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerBorderColor = Main.ControllerBorderColor;
            Preferences configuration53 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerBorderColor2 = Main.ControllerBorderColor;
            Preferences configuration54 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerBorderColor3 = Main.ControllerBorderColor;
            Preferences configuration55 = Main.Configuration;
            Microsoft.Xna.Framework.Graphics.Color controllerBorderColor4 = Main.ControllerBorderColor;
            Preferences configuration56 = Main.Configuration;
            float caveParallax = Main.caveParallax;
            Preferences configuration57 = Main.Configuration;
            bool showItemText = Main.showItemText;
            Preferences configuration58 = Main.Configuration;
            Preferences configuration59 = Main.Configuration;
            Preferences configuration60 = Main.Configuration;
            bool smartBlocksEnabled = Player.SmartCursorSettings.SmartBlocksEnabled;
            Preferences configuration61 = Main.Configuration;
            bool smartAxeAfterPickaxe = Player.SmartCursorSettings.SmartAxeAfterPickaxe;
            Preferences configuration62 = Main.Configuration;
            bool disableLeftShiftTrashCan = ItemSlot.Options.DisableLeftShiftTrashCan;
            Preferences configuration63 = Main.Configuration;
            bool highlightNewItems = ItemSlot.Options.HighlightNewItems;
            Preferences configuration64 = Main.Configuration;
            bool hidePassword = Main.HidePassword;
            Preferences configuration65 = Main.Configuration;
            bool thickMouse = Main.ThickMouse;
            Preferences configuration66 = Main.Configuration;
            bool reversedUpDownArmorSetBonuses = Main.ReversedUpDownArmorSetBonuses;
            Preferences configuration67 = Main.Configuration;
            LockOnHelper.LockOnMode useMode = LockOnHelper.UseMode;
            Preferences configuration68 = Main.Configuration;
            int num2 = 1;
            if (num2 == 0)
            {
            }
            if (num2 == 0)
            {
            }
            if (num2 == 0)
            {
            }
            int width = Screen.width;
            int width2 = Screen.width;
            int height = Screen.height;
            int height2 = Screen.height;
            Preferences configuration69 = Main.Configuration;
            Preferences configuration70 = Main.Configuration;
            Preferences configuration71 = Main.Configuration;
            Preferences configuration72 = Main.Configuration;
            Preferences configuration73 = Main.Configuration;
            Preferences configuration74 = Main.Configuration;
            Preferences configuration75 = Main.Configuration;
            Preferences configuration76 = Main.Configuration;
            int waveQuality = Main.WaveQuality;
            Preferences configuration77 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration78 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration79 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration80 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration81 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration82 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration83 = Main.Configuration;
            if (!true)
            {
            }
            Preferences configuration84 = Main.Configuration;
            bool enabled = ScreenPostProcessor.Enabled;
            Preferences configuration85 = Main.Configuration;
            bool showFrameRate = Main.showFrameRate;
            Preferences configuration86 = Main.Configuration;
            ItemGrid_Layout.ReorderStyle reorder = MultiplayerChat_Layout.Instance.TextGrid.Reorder;
            Preferences configuration87 = Main.Configuration;
            Preferences configuration88 = Main.Configuration;
            Preferences configuration89 = Main.Configuration;
            Preferences configuration90 = Main.Configuration;
            Preferences configuration91 = Main.Configuration;
            Preferences configuration92 = Main.Configuration;
            Preferences configuration93 = Main.Configuration;
            Preferences configuration94 = Main.Configuration;
            bool settingsEnabled_MinersWobble = Main.SettingsEnabled_MinersWobble;
            Preferences configuration95 = Main.Configuration;
            bool mouseShowBuildingGrid = Main.MouseShowBuildingGrid;
            Preferences configuration96 = Main.Configuration;
            bool settingsEnabled_TilesSwayInWind = Main.SettingsEnabled_TilesSwayInWind;
            Preferences configuration97 = Main.Configuration;
            bool cSmartCursorModeIsToggleAndNotHold = Main.cSmartCursorModeIsToggleAndNotHold;
            Preferences configuration98 = Main.Configuration;
            Preferences configuration99 = Main.Configuration;
            int num3 = 45683;
            if ("AutoSaveFrequency" == null)
            {
            }
            InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
            if (num3 == 0)
            {
            }
            Preferences configuration100 = Main.Configuration;
            Preferences configuration101 = Main.Configuration;
            Preferences configuration102 = Main.Configuration;
            Preferences configuration103 = Main.Configuration;
            Preferences configuration104 = Main.Configuration;
            Preferences configuration105 = Main.Configuration;
            int num4 = 1;
            return configuration105.Save(num4 != 0);
        }
References InterfaceStyles_Layout.Active, Terraria.Main.ambientVolume, Terraria.Main.autoPause, Terraria.Main.autoSave, Terraria.Main.BackgroundEnabled, Terraria.Main.caveParallax, Terraria.Main.Configuration, Terraria.Main.ControllerBorderColor, Terraria.Main.ControllerColor, Terraria.Main.cSmartCursorModeIsToggleAndNotHold, Terraria.GameContent.ChildSafety.Disabled, Terraria.Main.DisableIntenseVisualEffects, Terraria.UI.ItemSlot.Options.DisableLeftShiftTrashCan, ScreenPostProcessor.Enabled, UnityEngine.Screen.height, Terraria.Main.HidePassword, Terraria.UI.ItemSlot.Options.HighlightNewItems, VirtualControlsProfile_Layout.Id, MultiplayerChat_Layout.Instance, Terraria.Main.invasionProgressMode, Terraria.Main.inventoryTooltipTime, j__TPar, Terraria.Main.mapEnabled, System.mode, Terraria.Lighting.Mode, Terraria.Main.MouseBorderColor, Terraria.Main.mouseColor, Terraria.Main.MouseShowBuildingGrid, Terraria.Main.musicVolume, System.DateTime.Now, Terraria.Main.placementPreview, Terraria.IO.Preferences.Put(), Terraria.Main.qaStyle, ItemGrid_Layout.Reorder, Terraria.Main.ReversedUpDownArmorSetBonuses, Terraria.IO.Preferences.Save(), Terraria.Main.SettingsEnabled_MinersWobble, Terraria.Main.SettingsEnabled_OpaqueBoxBehindTooltips, Terraria.Main.SettingsEnabled_TilesSwayInWind, Terraria.Main.showFrameRate, Terraria.Main.showItemText, Terraria.Player.SmartCursorSettings.SmartAxeAfterPickaxe, Terraria.Player.SmartCursorSettings.SmartBlocksEnabled, Terraria.Main.soundVolume, System.text, MultiplayerChat_Layout.TextGrid, Terraria.Main.ThickMouse, Terraria.Main.tooltipTime, Terraria.Main.TOWMusicUnlocked, Map_Layout.UseLargeMinimap, Terraria.GameInput.LockOnHelper.UseMode, Terraria.Main.WaveQuality, and UnityEngine.Screen.width.
Referenced by GUISettings.Draw(), GUISettingsPauseMenu.Draw(), Terraria.Main.QuitGame(), Terraria.Main.ResetSettings(), and Terraria.WorldGen.saveToonWhilePlayingCallBack().