terraria-cpp2il-methodrecon: Terraria.Main.DoDraw_DrawNPCsOverTiles
DoDraw_DrawNPCsOverTiles()
void Terraria.Main.DoDraw_DrawNPCsOverTiles () inline private
Definition at line 17359 of file Main.cs.
        {
            int num = 1;
            List<int> drawCacheProjsBehindNPCs = this.DrawCacheProjsBehindNPCs;
            int num2 = 1;
            this.DrawCachedProjs(drawCacheProjsBehindNPCs, num2 != 0);
            if (num == 0)
            {
            }
            SamplerState defaultSamplerState = Main.DefaultSamplerState;
            Matrix transform = Main.Transform;
            SamplerState defaultSamplerState2 = Main.DefaultSamplerState;
            Matrix transform2 = Main.Transform;
            long num3 = 0L;
            this.DrawNPCs(num3 != 0L);
            List<int> drawCacheNPCProjectiles = this.DrawCacheNPCProjectiles;
            long num4 = 0L;
            this.DrawCachedNPCs(drawCacheNPCProjectiles, num4 != 0L);
            TimeLogger.DetailedDrawTime(19);
            Main.FlushBatches();
        }
References Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.DrawCachedNPCs(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawCacheNPCProjectiles, Terraria.Main.DrawCacheProjsBehindNPCs, Terraria.Main.DrawNPCs(), Terraria.Main.FlushBatches(), j__TPar, Microsoft.Xna.Framework.Input.L, and Terraria.Main.Transform.