terraria-cpp2il-methodrecon: Terraria.Main.ResetSettings
ResetSettings()
void Terraria.Main.ResetSettings () inline
Definition at line 6027 of file Main.cs.
        {
            if (!true)
            {
            }
            string text2;
            string text = Main.SavePath + text2 + "config.json";
            long num = 0L;
            bool flag = FileUtilities.Exists(text, num != 0L);
            string text4;
            string text3 = Main.SavePath + text4 + "config.json";
            long num2 = 0L;
            FileUtilities.Delete(text3, num2 != 0L);
            TextureAtlasDB.UnloadAssets();
            bool flag2 = Main.SaveSettings();
        }
References Terraria.Utilities.FileUtilities.Delete(), Terraria.Utilities.FileUtilities.Exists(), j__TPar, Microsoft.Xna.Framework.Input.L, Terraria.Main.SaveSettings(), System.text, and TextureAtlasDB.UnloadAssets().