terraria-cpp2il-methodrecon: Terraria.Main.CloseKeyboard
CloseKeyboard()
static void Terraria.Main.CloseKeyboard () inline static
Definition at line 8523 of file Main.cs.
        {
            if (!true)
            {
            }
            if (true)
            {
            }
        }
Referenced by GUIItemFilter.Close(), GUINPCDialogue.Close(), GUIMultiplayerChat.CloseChat(), GUINPCDialogue.CloseClicked(), GUIItemFilter.CloseExpandedFilter(), GUIInterfaceEdit.CloseNameEdit(), GUIPlayerCreateMenu.CloseNameEdit(), GUIVirtualInputControllerEdit.CloseNameEdit(), GUIWorldCreateMenu.CloseNameEdit(), GUIBestiary.CloseSearchInput(), GUIWorldCreateMenu.CloseSeedEdit(), GUIMultiplayerJoin.CloseServerIPEdit(), GUIMultiplayerHost.CloseServerPasswordEdit(), GUIMultiplayerJoin.CloseServerPortEdit(), GUIMultiplayerServerIP.Draw(), GUIMultiplayerServerPassword.Draw(), GUIMultiplayerServerPort.Draw(), GUIMultiplayerServerRequestedPassword.Draw(), GUIMultiplayerChat.DrawNotification(), GUIItemFilter.DrawSearch(), and GUINPCDialogue.Option1Clicked().