terraria-cpp2il-methodrecon: Terraria.Main.RenderTiles2
RenderTiles2()
void Terraria.Main.RenderTiles2 () inline protected
Definition at line 14981 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
                GraphicsDevice graphicsDevice = base.GraphicsDevice;
                RenderTarget2D renderTarget2D = this.tile2Target;
                graphicsDevice.SetRenderTarget(renderTarget2D);
                GraphicsDevice graphicsDevice2 = base.GraphicsDevice;
                TileDrawing tilesRenderer = this.TilesRenderer;
                int num2 = 1;
                long num3 = 0L;
                long num4 = 0L;
                long num5 = 0L;
                tilesRenderer.PreDrawTiles(num3 != 0L, num4 != 0L, num2 != 0);
                TileDrawing tilesRenderer2 = this.TilesRenderer;
                int num6 = 1;
                long num7 = 0L;
                long num8 = 0L;
                tilesRenderer2.Draw(num7 != 0L, num8 != 0L, num6 != 0, (int)num5);
                TimeLogger.DetailedDrawReset();
                TileDrawing tilesRenderer3 = this.TilesRenderer;
                int num9 = 1;
                long num10 = 0L;
                long num11 = 0L;
                tilesRenderer3.PostDrawTiles(num10 != 0L, num11 != 0L, num9 != 0);
                TimeLogger.DetailedDrawTime(29);
                GraphicsDevice graphicsDevice3 = base.GraphicsDevice;
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.GameContent.Drawing.TileDrawing.Draw(), Microsoft.Xna.Framework.Game.graphicsDevice, j__TPar, Microsoft.Xna.Framework.Input.L, Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles(), Terraria.GameContent.Drawing.TileDrawing.PreDrawTiles(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.tile2Target, and Terraria.Main.TilesRenderer.