terraria-cpp2il-methodrecon: Terraria.Main.NewText
NewText()
static void Terraria.Main.NewText (string newText, byte R = 255, byte G = 255, byte B = 255) inline static
Definition at line 17778 of file Main.cs.
        {
            if (!true)
            {
            }
        }
Referenced by Terraria.Net.LegacyNetBufferPool.DisplayBufferSizes(), Terraria.TimeLogger.EndDrawFrame(), Terraria.WorldGen.MoveTownNPC(), Terraria.NPC.NewNPC(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.WorldGen.SpawnTownNPC(), and Terraria.GameContent.DontStarveDarknessDamageDealer.UpdateDarknessState().