terraria-cpp2il-methodrecon: Terraria.Main.DoUpdate_HandleInput
DoUpdate_HandleInput()
void Terraria.Main.DoUpdate_HandleInput () inline private
Definition at line 7949 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            PlayerInput.UpdateInput();
            PlayerInput.SetZoom_Unscaled();
            PlayerInput.CacheMousePositionForZoom();
            PlayerInput.SetZoom_MouseInWorld();
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            KeyboardState state = Keyboard.GetState();
        }
References Terraria.GameInput.PlayerInput.CacheMousePositionForZoom(), Microsoft.Xna.Framework.Input.Keyboard.GetState(), Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), System.state, and Terraria.GameInput.PlayerInput.UpdateInput().