terraria-cpp2il-methodrecon: Terraria.Main.hslToRgb
hslToRgb() [3/3]
static Microsoft.Xna.Framework.Graphics.Color Terraria.Main.hslToRgb (Microsoft::Xna::Framework::Vector3 hslVector) inline static
Definition at line 13783 of file Main.cs.
        {
            if (!true)
            {
            }
            return 1;
        }
Referenced by Terraria.Projectile.AI_180_FairyQueenSunDance(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.NPC.HitEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch().