terraria-cpp2il-methodrecon: Terraria.Main.UpdateTime_StartNight
UpdateTime_StartNight()
static void Terraria.Main.UpdateTime_StartNight (bool stopEvents) inline static
Definition at line 17934 of file Main.cs.
        {
            if (!true)
            {
            }
            int num = 4600;
            if (num != 0)
            {
                if (num == 0)
                {
                }
                Main.UpdateTimeRate();
            }
            NPC.ResetBadgerHatTime();
            Star.NightSetup();
            NPC.setFireFlyChance();
            BirthdayParty.CheckNight();
            LanternNight.CheckNight();
            int num2;
            if (num2 == 0)
            {
                bool logicHost = Main.LogicHost;
            }
            bool lanternsUp = LanternNight.LanternsUp;
            int num3 = 1;
            stopEvents.m_value = num3 != 0;
            if (num3 == 0)
            {
            }
            if (num3 != 0)
            {
                if (num3 == 0)
                {
                }
                bool logicHost2 = Main.LogicHost;
                AchievementsHelper.NotifyProgressionEvent(3);
            }
            if (num3 == 0)
            {
            }
            AchievementsHelper.NotifyProgressionEvent(0);
            if (num3 == 0)
            {
            }
            bool flag = Main.IsFastForwardingTime();
            bool logicHost3 = Main.LogicHost;
            bool logicHost4 = Main.LogicHost;
            int num4;
            if (num4 == 0)
            {
                bool logicHost5 = Main.LogicHost;
                return;
            }
            bool netHost = Main.NetHost;
        }
References Terraria.GameContent.Events.BirthdayParty.CheckNight(), Terraria.GameContent.Events.LanternNight.CheckNight(), Terraria.Main.IsFastForwardingTime(), j__TPar, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Main.LogicHost, Terraria.Main.NetHost, Terraria.Star.NightSetup(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.NPC.ResetBadgerHatTime(), Terraria.NPC.setFireFlyChance(), and Terraria.Main.UpdateTimeRate().
Referenced by Terraria.Main.SkipToTime().