terraria-cpp2il-methodrecon: Terraria.Main.CacheSupportedDisplaySizes
CacheSupportedDisplaySizes()
static void Terraria.Main.CacheSupportedDisplaySizes () inline static private
Definition at line 6928 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            IEnumerator<DisplayMode> enumerator = GraphicsAdapter.DefaultAdapter._supportedDisplayModes.GetEnumerator();
        }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter._supportedDisplayModes, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.DefaultAdapter, and Microsoft.Xna.Framework.Graphics.DisplayModeCollection.GetEnumerator().
Referenced by Terraria.Main.ClientInitialize(), and Terraria.Main.PostContentLoadInitialize().