terraria-cpp2il-methodrecon: Terraria.Main.FlushBatches
FlushBatches()
static void Terraria.Main.FlushBatches () inline static
Definition at line 5092 of file Main.cs.
        {
            if (!true)
            {
            }
        }
Referenced by Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Main.DoDraw_WallsTilesNPCs(), GUICraftGuidePopup.Draw(), GUIEmotesWindow.Draw(), GUIHairWindow.Draw(), GUIPVPIcons.Draw(), GUIReforgePopup.Draw(), GUIResearch.Draw(), GUITalkerList.Draw(), GUIWorldGenerateMenu.Draw(), GUIReturnToTouch.Draw(), GUIHairWindow.DrawButtons(), GUIHairWindow.DrawBuyButton(), Terraria.Main.DrawInterface_36_Cursor(), GUIRubbleMaker.DrawOverlay(), GUIWiresUI.DrawOverlay(), GUIVirtualInputControllerEdit.DrawProfile(), Terraria.GameContent.Drawing.WallDrawing.DrawWallsThreaded(), Microsoft.Xna.Framework.Graphics.GeometryBufferInstance.EndBuffer(), Terraria.Main.RenderBlack(), and Microsoft.Xna.Framework.Game.UnityDraw().