terraria-cpp2il-methodrecon: Terraria.Main.RenderWater
RenderWater()
void Terraria.Main.RenderWater () inline protected
Definition at line 15016 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
                GraphicsDevice graphicsDevice = base.GraphicsDevice;
                GraphicsDevice graphicsDevice2 = base.GraphicsDevice;
                int num2 = 1;
                long num3 = 0L;
                this.DrawWaters(num3 != 0L);
                TimeLogger.DetailedDrawReset();
                if (num2 == 0)
                {
                }
                TimeLogger.DetailedDrawTime(31);
                GraphicsDevice graphicsDevice3 = base.GraphicsDevice;
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.DrawWaters(), Microsoft.Xna.Framework.Game.graphicsDevice, j__TPar, and Microsoft.Xna.Framework.Input.L.