terraria-cpp2il-methodrecon: Terraria.Main.RenderTiles
RenderTiles()
void Terraria.Main.RenderTiles () inline protected
Definition at line 14945 of file Main.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
                this.RenderBlack();
                GraphicsDevice graphicsDevice = base.GraphicsDevice;
                RenderTarget2D renderTarget2D = this.tileTarget;
                graphicsDevice.SetRenderTarget(renderTarget2D);
                GraphicsDevice graphicsDevice2 = base.GraphicsDevice;
                TileDrawing tilesRenderer = this.TilesRenderer;
                int num2 = 1;
                int num3 = 1;
                long num4 = 0L;
                long num5 = 0L;
                tilesRenderer.PreDrawTiles(num2 != 0, num4 != 0L, num3 != 0);
                TileDrawing tilesRenderer2 = this.TilesRenderer;
                int num6 = 1;
                int num7 = 1;
                long num8 = 0L;
                tilesRenderer2.Draw(num6 != 0, num8 != 0L, num7 != 0, (int)num5);
                TimeLogger.DetailedDrawReset();
                TileDrawing tilesRenderer3 = this.TilesRenderer;
                int num9 = 1;
                int num10 = 1;
                long num11 = 0L;
                tilesRenderer3.PostDrawTiles(num9 != 0, num11 != 0L, num10 != 0);
                TimeLogger.DetailedDrawTime(28);
                GraphicsDevice graphicsDevice3 = base.GraphicsDevice;
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.GameContent.Drawing.TileDrawing.Draw(), Microsoft.Xna.Framework.Game.graphicsDevice, j__TPar, Microsoft.Xna.Framework.Input.L, Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles(), Terraria.GameContent.Drawing.TileDrawing.PreDrawTiles(), Terraria.Main.RenderBlack(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.TilesRenderer, and Terraria.Main.tileTarget.