terraria-cpp2il-methodrecon: Terraria.Main.DoDraw_DrawNPCsBehindTiles
DoDraw_DrawNPCsBehindTiles()
void Terraria.Main.DoDraw_DrawNPCsBehindTiles () inline private
Definition at line 17382 of file Main.cs.
        {
            int num = 1;
            List<int> drawCacheProjsBehindNPCsAndTiles = this.DrawCacheProjsBehindNPCsAndTiles;
            int num2 = 1;
            this.DrawCachedProjs(drawCacheProjsBehindNPCsAndTiles, num2 != 0);
            if (num == 0)
            {
            }
            SamplerState defaultSamplerState = Main.DefaultSamplerState;
            Matrix transform = Main.Transform;
            SamplerState defaultSamplerState2 = Main.DefaultSamplerState;
            Matrix transform2 = Main.Transform;
            int num3 = 1;
            this.DrawNPCs(num3 != 0);
            TimeLogger.DetailedDrawTime(18);
            Main.FlushBatches();
        }
References Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawCacheProjsBehindNPCsAndTiles, Terraria.Main.DrawNPCs(), Terraria.Main.FlushBatches(), j__TPar, and Terraria.Main.Transform.