terraria-cpp2il-methodrecon: System.TermInfoDriver.ReadKeyInternal
ReadKeyInternal()
ConsoleKeyInfo System.TermInfoDriver.ReadKeyInternal ([Out] bool fresh) inline private
Definition at line 356 of file TermInfoDriver.cs.
        {
            do
            {
                bool flag = this.inited;
                if (!flag)
                {
                    this.Init();
                }
                this.InitKeys();
                if (this.GetKeyFromBuffer(true) != null)
                {
                }
                if (!flag)
                {
                }
                StreamReader streamReader = this.stdin;
                bool flag2 = this.stdin.DataAvailable();
                StreamReader streamReader2 = this.stdin;
                bool flag3 = this.stdin.DataAvailable();
                long num = 0L;
                if (this.GetKeyFromBuffer(num != 0L) != null)
                {
                    goto IL_0071;
                }
                StreamReader streamReader3 = this.stdin;
            }
            while (this.GetKeyFromBuffer(true) == null);
            fresh.m_value = true;
            IL_0071:
            throw new InvalidCastException();
        }
References System.IO.StreamReader.DataAvailable(), System.TermInfoDriver.GetKeyFromBuffer(), System.TermInfoDriver.Init(), System.TermInfoDriver.inited, System.TermInfoDriver.InitKeys(), j__TPar, System.L, and System.TermInfoDriver.stdin.
Referenced by System.TermInfoDriver.ReadKey(), and System.TermInfoDriver.ReadUntilConditionInternal().