terraria-cpp2il-methodrecon: Ionic.Zip.ZipInputStream.GetNextEntry
GetNextEntry()
ZipEntry Ionic.Zip.ZipInputStream.GetNextEntry () inline
Definition at line 173 of file ZipInputStream.cs.
        {
            bool findRequired = this._findRequired;
            if (findRequired)
            {
                Stream inputStream = this._inputStream;
                if (!findRequired)
                {
                }
                long num = SharedUtilities.FindSignature(inputStream, 19280);
                Stream inputStream2 = this._inputStream;
            }
            long num2;
            if (this._firstEntry)
            {
                Stream inputStream3 = this._inputStream;
                long endOfEntry = this._endOfEntry;
                Stream inputStream4 = this._inputStream;
                num2 = 0L;
                SharedUtilities.Workaround_Ladybug318918(inputStream4);
            }
            ZipContainer container = this._container;
            bool firstEntry = this._firstEntry;
            ZipEntry zipEntry = ZipEntry.ReadEntry(container, num2 != 0L);
            Stream inputStream5 = this._inputStream;
            this._currentEntry = zipEntry;
            this._endOfEntry = inputStream5;
            ZipEntry currentEntry = this._currentEntry;
            this._firstEntry = 257 != 0;
            return currentEntry;
        }
References Ionic.Zip.ZipInputStream._container, Ionic.Zip.ZipInputStream._currentEntry, Ionic.Zip.ZipInputStream._endOfEntry, Ionic.Zip.ZipInputStream._findRequired, Ionic.Zip.ZipInputStream._firstEntry, Ionic.Zip.ZipInputStream._inputStream, Ionic.Zip.SharedUtilities.FindSignature(), j__TPar, System.L, Ionic.Zip.ZipEntry.ReadEntry(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().