terraria-cpp2il-methodrecon: GUIAmmo.ItemOver
ItemOver()
void GUIAmmo.ItemOver (int index) inline
Definition at line 68 of file GUIAmmo.cs.
    {
        int myPlayer = Main.myPlayer;
        bool isAir = Main.mouseItem.IsAir;
        int myPlayer2 = Main.myPlayer;
        int myPlayer3 = Main.myPlayer;
        int myPlayer4 = Main.myPlayer;
        int myPlayer5 = Main.myPlayer;
        int myPlayer6 = Main.myPlayer;
        global::Cursor cursor;
        if (cursor != null)
        {
            return;
        }
        long num = 0L;
        global::Cursor cursor2;
        if (cursor2 != null)
        {
            return;
        }
        bool flag = this.rightClickHeld;
        int num3;
        if (num == 0L && !flag)
        {
            float num2 = this.doubleClickTimer;
            num3 = this.lastItemClicked;
            this.lastItemClicked = num3;
        }
        if (flag)
        {
            int num4 = this.lastItemClicked;
            int num5 = this.lastItemClicked;
            if (num5 == 0)
            {
            }
            bool mouseLeft = Main.mouseLeft;
            int type;
            if (num5 != 0)
            {
                if (num5 == 0)
                {
                }
                if (Main.mouseItem != null)
                {
                    if (num5 == 0)
                    {
                    }
                    type = Main.mouseItem.type;
                    if (type != 0)
                    {
                    }
                }
            }
            if (type == 0)
            {
            }
            Main.mouseRight = Main.mouseLeft;
            int myPlayer7 = Main.myPlayer;
            if (num3 == 0)
            {
            }
            bool mouseRight = Main.mouseRight;
            int myPlayer8 = Main.myPlayer;
            return;
        }
        int myPlayer9 = Main.myPlayer;
        int myPlayer10 = Main.myPlayer;
        int myPlayer11 = Main.myPlayer;
        if (num3 == 0)
        {
        }
        Recipe.FindRecipes(false);
        if (num3 == 0)
        {
            GUIControllerAmmo guicontrollerAmmo;
            if (guicontrollerAmmo != null)
            {
                guicontrollerAmmo.itemRow = index;
                return;
            }
            return;
        }
        else
        {
            bool mouseLeft2 = Main.mouseLeft;
            int type2;
            if (Main.mouseItem == null || Main.mouseItem.type == 0)
            {
                int num6 = this.itemDragStart;
                if (num6 == 0)
                {
                }
                bool mouseLeftRelease = Main.mouseLeftRelease;
                if (num6 == 0)
                {
                }
                bool mouseLeft3 = Main.mouseLeft;
                if (num6 == 0)
                {
                }
                if (Main.mouseItem != null)
                {
                    if (num6 == 0)
                    {
                    }
                    type2 = Main.mouseItem.type;
                    if (type2 != 0)
                    {
                    }
                }
            }
            if (type2 == 0)
            {
            }
            int myPlayer12 = Main.myPlayer;
            int cursorOverride = Main.cursorOverride;
            int num7;
            int num8;
            if (num7 != 0)
            {
                if (type2 == 0)
                {
                }
                int myPlayer13 = Main.myPlayer;
                if (num8 == 0)
                {
                }
                if (type2 == 0)
                {
                }
                Recipe.FindRecipes(false);
                this.itemDragStart = type2;
                this.itemOver = type2;
            }
            if (num8 != 0)
            {
                string textValue = Language.GetTextValue("ControllerMappings.TakeOne");
                int myPlayer14 = Main.myPlayer;
                Recipe.FindRecipes(false);
                return;
            }
            return;
        }
    }
References Terraria.Main.cursorOverride, doubleClickTimer, Terraria.Recipe.FindRecipes(), Terraria.Localization.Language.GetTextValue(), System.index, Terraria.Item.IsAir, itemDragStart, j__TPar, Microsoft.Xna.Framework.Input.L, lastItemClicked, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseRight, Terraria.Main.myPlayer, rightClickHeld, and Terraria.Item.type.
Referenced by ItemDraw().