terraria-cpp2il-methodrecon: Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab
PlaceSlab()
void Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab (MarbleBiome::Slab slab, int originX, int originY, int scale) inline private
Definition at line 23 of file MarbleBiome.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            int num2 = 180;
            if (num == 0)
            {
            }
            UnifiedRandom genRand = WorldGen.genRand;
            int num3 = 2;
            if (genRand.Next(num3) != 0)
            {
                if (num == 0)
                {
                }
                UnifiedRandom genRand2 = WorldGen.genRand;
                int num4 = 2;
                int num5 = genRand2.Next(num4);
                if (num2 == 0)
                {
                }
                UnifiedRandom genRand3 = WorldGen.genRand;
                int num6 = 2;
                int num7 = genRand3.Next(num6);
                if (!true)
                {
                }
                int num8 = 1;
                ushort num9;
                WorldUtils.TileFrame((int)num9, (int)num9, num8 != 0);
                int num10 = 1;
                WorldGen.SquareWallFrame(0, (int)num9, num10 != 0);
                int num11 = 1;
                long num12 = 0L;
                Tile.SmoothSlope(1073741824, (int)num9, num11 != 0, num12 != 0L);
                long num13 = 0L;
                bool flag = WorldGen.SolidTile(1073741824, 0, num13 != 0L);
                UnifiedRandom random = GenBase._random;
                int num14 = 4;
                if (random.Next(num14) == 0)
                {
                    if (1073741824 == 0)
                    {
                    }
                    long num15 = 0L;
                    WorldGen.PlaceTight(0, num14, num15 != 0L);
                }
                if (1073741824 == 0)
                {
                }
                long num16 = 0L;
                bool flag2 = WorldGen.SolidTile(0, num14, num16 != 0L);
                UnifiedRandom random2 = GenBase._random;
                int num17 = 4;
                if (random2.Next(num17) == 0)
                {
                    if (1073741824 == 0)
                    {
                    }
                    long num18 = 0L;
                    WorldGen.PlaceTight(0, 0, num18 != 0L);
                }
            }
        }
References Terraria.WorldBuilding.GenBase._random, Terraria.WorldGen.genRand, j__TPar, System.L, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTight(), Terraria.Tile.SmoothSlope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareWallFrame(), and Terraria.WorldBuilding.WorldUtils.TileFrame().