terraria-cpp2il-methodrecon: Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.DecodeRSA
DecodeRSA()
static RSA Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.DecodeRSA (byte[] keypair) inline static
Definition at line 141 of file PKCS8.cs.
            {
                ASN1 asn;
                byte nTag = asn.m_nTag;
                ASN1 asn2;
                byte[] array = PKCS8.PrivateKeyInfo.RemoveLeadingZero(asn2.Value);
                ASN1 asn3;
                byte[] array2 = PKCS8.PrivateKeyInfo.Normalize(asn3.Value, 43151360);
                long num = 0L;
                ASN1 asn4;
                byte[] array3 = PKCS8.PrivateKeyInfo.Normalize(asn4.Value, (int)num);
                long num2 = 0L;
                ASN1 asn5;
                byte[] array4 = PKCS8.PrivateKeyInfo.Normalize(asn5.Value, (int)num2);
                ASN1 asn6;
                byte[] array5 = PKCS8.PrivateKeyInfo.RemoveLeadingZero(asn6.Value);
                long num3 = 0L;
                ASN1 asn7;
                byte[] array6 = PKCS8.PrivateKeyInfo.Normalize(asn7.Value, (int)num3);
                long num4 = 0L;
                ASN1 asn8;
                byte[] array7 = PKCS8.PrivateKeyInfo.Normalize(asn8.Value, (int)num4);
                long num5 = 0L;
                ASN1 asn9;
                byte[] array8 = PKCS8.PrivateKeyInfo.Normalize(asn9.Value, (int)num5);
                return RSA.Create();
            }
References System.array, System.Security.Cryptography.RSA.Create(), j__TPar, System.L, Mono.Security.ASN1.m_nTag, Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.Normalize(), and Mono.Security.Cryptography.PKCS8.PrivateKeyInfo.RemoveLeadingZero().
Referenced by Mono.Security.X509.PKCS12.AddPrivateKey(), Mono.Security.X509.PKCS12.GetAsymmetricAlgorithm(), and Mono.Security.X509.PKCS12.GetAttributes().