terraria-cpp2il-methodrecon: System.Security.Cryptography.HashAlgorithm.Create
Create() [1/2]
static HashAlgorithm System.Security.Cryptography.HashAlgorithm.Create () inline static
Definition at line 16 of file HashAlgorithm.cs.
        {
            return CryptoConfigForwarder.CreateDefaultHashAlgorithm();
        }
References System.Security.Cryptography.CryptoConfigForwarder.CreateDefaultHashAlgorithm().
Referenced by System.Security.Cryptography.PKCS1MaskGenerationMethod.GenerateMask(), System.Security.Cryptography.RSACryptoServiceProvider.GetHashFromString(), Mono.Security.X509.X509Builder.Sign(), Mono.Security.X509.X509Builder.Sign(), System.Security.Cryptography.RSACryptoServiceProvider.SignHash(), Mono.Security.Authenticode.AuthenticodeDeformatter.VerifyCounterSignature(), and System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash().