terraria-cpp2il-methodrecon: GUISettings.Draw
Draw()
bool GUISettings.Draw () inline
Definition at line 29 of file GUISettings.cs.
    {
        int num = 1;
        bool visible = this.Visible;
        if (num == 0)
        {
        }
        bool gameMenu = Main.gameMenu;
        if (!this.Visible)
        {
            return gameMenu;
        }
        bool flag;
        while (!flag)
        {
        }
        int num2 = 1;
        bool visible2 = this.Visible;
        this.Visible = num2 != 0;
        if (visible2)
        {
            bool flag2 = Main.SaveSettings();
            return Main.inFancyUI;
        }
        if ("Mobile.TooltipWiringKM" == null)
        {
        }
        bool flag3 = InterfaceStyles_Layout.Active.AnyOpen();
        if ("Mobile.TooltipWiringKM" == null)
        {
        }
        int gameMode = Main.GameMode;
        if ("Mobile.TooltipWiringKM" == null)
        {
        }
        InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
        Settings_Layout instance = Settings_Layout.Instance;
        bool visible3 = this.Visible;
        TransactionButton_Layout jmsettingsButton = instance.JMSettingsButton;
        string textValue = Language.GetTextValue("Mobile.JourneySettingsMenu");
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            int num3 = 1;
            this.Visible = num3 != 0;
            SoundEffectInstance soundEffectInstance;
            soundEffectInstance._effect = num3;
        }
        InterfaceProfile_Layout active2 = InterfaceStyles_Layout.Active;
        Settings_Layout instance2 = Settings_Layout.Instance;
        bool visible4 = this.Visible;
        TransactionButton_Layout bestiaryButton = instance2.BestiaryButton;
        string textValue2 = Language.GetTextValue("Mobile.Bestiary");
        int num4 = 1;
        GUITransactionButton.InputState inputState2;
        if (inputState2 == GUITransactionButton.InputState.Clicked)
        {
            this.Visible = num4 != 0;
            Main.mouseLeft = false;
            Main.mouseLeftRelease = true;
        }
        InterfaceProfile_Layout active3 = InterfaceStyles_Layout.Active;
        Settings_Layout instance3 = Settings_Layout.Instance;
        bool visible5 = this.Visible;
        TransactionButton_Layout mapButton = instance3.MapButton;
        if (!visible5)
        {
        }
        GUITransactionButton.InputState inputState3;
        if (inputState3 == GUITransactionButton.InputState.Clicked)
        {
            InterfaceProfile_Layout active4 = InterfaceStyles_Layout.Active;
            long num5 = 0L;
            active4.Close(num5 != 0L);
            Main.playerInventory = false;
            int myPlayer = Main.myPlayer;
            Main.npcChatCornerItem = 0;
            Main.mapFullscreen = true;
            Main.resetMapFull = true;
        }
        InterfaceProfile_Layout active5 = InterfaceStyles_Layout.Active;
        Settings_Layout instance4 = Settings_Layout.Instance;
        bool visible6 = this.Visible;
        TransactionButton_Layout housingMenuButton = instance4.HousingMenuButton;
        if (!visible6)
        {
        }
        GUITransactionButton.InputState inputState4;
        if (inputState4 == GUITransactionButton.InputState.Clicked)
        {
            InterfaceProfile_Layout active6 = InterfaceStyles_Layout.Active;
            long num6 = 0L;
            active6.Close(num6 != 0L);
        }
        InterfaceProfile_Layout active7 = InterfaceStyles_Layout.Active;
        Settings_Layout instance5 = Settings_Layout.Instance;
        bool visible7 = this.Visible;
        TransactionButton_Layout emotesButton = instance5.EmotesButton;
        string textValue3 = Language.GetTextValue("Mobile.ToggleEmotes");
        GUITransactionButton.InputState inputState5;
        if (inputState5 == GUITransactionButton.InputState.Clicked)
        {
        }
        InterfaceProfile_Layout active8 = InterfaceStyles_Layout.Active;
        Settings_Layout instance6 = Settings_Layout.Instance;
        bool visible8 = this.Visible;
        TransactionButton_Layout chatButton = instance6.ChatButton;
        if (!visible8)
        {
        }
        GUITransactionButton.InputState inputState6;
        if (inputState6 == GUITransactionButton.InputState.Clicked)
        {
        }
        InterfaceProfile_Layout active9 = InterfaceStyles_Layout.Active;
        bool visible9 = this.Visible;
        if (visible9)
        {
            bool flag4;
            return flag4;
        }
        if (!visible9)
        {
        }
        int num7 = 3;
        bool flag5 = InterfaceStyles_Layout.Active.AnyOpen();
        List<GUIPageIconGrouping> leftGroupings = InterfaceStyles_Layout.Active.LeftGroupings;
        InterfaceProfile_Layout active10 = InterfaceStyles_Layout.Active;
        Settings_Layout instance7 = Settings_Layout.Instance;
        bool visible10 = this.Visible;
        TransactionButton_Layout jmsettingsButton2 = instance7.JMSettingsButton;
        string textValue4 = Language.GetTextValue("Mobile.JourneySettingsMenu");
        GUITransactionButton.InputState inputState7;
        if (inputState7 == GUITransactionButton.InputState.Clicked)
        {
            this.Visible = num7 != 0;
            SoundEffectInstance soundEffectInstance2;
            soundEffectInstance2._effect = num7;
        }
        bool flag6 = InterfaceStyles_Layout.Active.AnyOpen();
        List<GUIPageIconGrouping> leftGroupings2 = InterfaceStyles_Layout.Active.LeftGroupings;
        InterfaceProfile_Layout active11 = InterfaceStyles_Layout.Active;
        Settings_Layout instance8 = Settings_Layout.Instance;
        bool visible11 = this.Visible;
        TransactionButton_Layout bestiaryButton2 = instance8.BestiaryButton;
        string textValue5 = Language.GetTextValue("Mobile.Bestiary");
        int num8 = 1;
        GUITransactionButton.InputState inputState8;
        if (inputState8 == GUITransactionButton.InputState.Clicked)
        {
            this.Visible = num8 != 0;
            Main.mouseLeft = false;
            Main.mouseLeftRelease = true;
        }
        return XNAUnityRunner.TouchInputKeyboardLocked;
    }
References InterfaceStyles_Layout.Active, InterfaceProfile_Layout.AnyOpen(), InterfaceProfile_Layout.Close(), Terraria.Main.gameMenu, Terraria.Main.GameMode, Terraria.Localization.Language.GetTextValue(), Terraria.Main.inFancyUI, Settings_Layout.Instance, j__TPar, Settings_Layout.JMSettingsButton, System.L, InterfaceProfile_Layout.LeftGroupings, Terraria.Main.myPlayer, Terraria.Main.SaveSettings(), XNAUnityRunner.TouchInputKeyboardLocked, and Visible.