terraria-cpp2il-methodrecon: System.Runtime.InteropServices.HandleCollector.Remove
Remove()
void System.Runtime.InteropServices.HandleCollector.Remove () inline
Definition at line 116 of file HandleCollector.cs.
        {
            long num = 0L;
            int num2 = Interlocked.Decrement(int.MinValue);
            int num3 = this.handleCount;
            Monitor.Enter(this, num != 0L);
            int num4 = this.initialThreshold;
            long num5 = 0L;
            this.threshold = num4;
            int num6 = 5;
            if (num4 != 0)
            {
                Monitor.Exit(this);
            }
            if (num5 == 0L)
            {
                if (num6 == 0)
                {
                    int[] array = this.gc_counts;
                    if (num4 == 0)
                    {
                    }
                    int num7 = GC.CollectionCount(int.MinValue);
                    array.m_value = num7;
                }
                return;
            }
            throw new OutOfMemoryException();
        }
References System.array, System.GC.CollectionCount(), System.Threading.Interlocked.Decrement(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Runtime.InteropServices.HandleCollector.gc_counts, System.Runtime.InteropServices.HandleCollector.handleCount, System.Runtime.InteropServices.HandleCollector.initialThreshold, j__TPar, and System.L.