terraria-cpp2il-methodrecon: Terraria.Social.Discord.RichPresenceSocialModule.PublishPresence
PublishPresence()
void Terraria.Social.Discord.RichPresenceSocialModule.PublishPresence (RichPresenceState state) inline private
Definition at line 42 of file RichPresenceSocialModule.cs.
        {
            RichPresenceState.GameModeState gameMode = state.GameMode;
            string text;
            string textValue = Language.GetTextValue("RichPresence." + text);
            RichPresenceState.GameModeState gameMode2 = state.GameMode;
            string text2 = this._infoAboutNetGroup.ComposeInfo();
        }
References Terraria.Social.Discord.RichPresenceSocialModule._infoAboutNetGroup, Terraria.Net.NetGroupInfo.ComposeInfo(), Terraria.Localization.Language.GetTextValue(), j__TPar, System.state, and System.text.
Referenced by Terraria.Social.Discord.RichPresenceSocialModule.UpdatePresence().