terraria-cpp2il-methodrecon: Microsoft.Xna.Framework.Input.Keyboard.GetState
GetState() [1/2]
static KeyboardState Microsoft.Xna.Framework.Input.Keyboard.GetState () inline static
Definition at line 12 of file Keyboard.cs.
        {
            if (!true)
            {
            }
            KeyboardState keyboardState = Keyboard.PlatformGetState();
            KeyboardState keyboardState2;
            keyboardState2.<CapsLock>k__BackingField = true;
            return 1;
        }
References Microsoft.Xna.Framework.Input.CapsLock, j__TPar, and Microsoft.Xna.Framework.Input.Keyboard.PlatformGetState().
Referenced by Terraria.Main.DoUpdate_HandleInput(), and Terraria.GameInput.PlayerInput.ResetInputsOnActiveStateChange().