terraria-cpp2il-methodrecon: Terraria.TimeLogger.EndDrawFrame
EndDrawFrame()
static void Terraria.TimeLogger.EndDrawFrame () inline static
Definition at line 40 of file TimeLogger.cs.
        {
            StringBuilder stringBuilder;
            int length = stringBuilder.AppendLine().AppendLine("Logging ended early").Length;
            int num = 250;
            int num2 = 250;
            long num3 = 0L;
            Main.NewText("Detailed logging ended.", (byte)num, (byte)num2, (byte)num3);
        }
References System.Text.StringBuilder.AppendLine(), j__TPar, System.L, System.length, System.Text.StringBuilder.Length, and Terraria.Main.NewText().
Referenced by Terraria.Main.DoDraw().