terraria-cpp2il-methodrecon: Telepathy.Common.SendLoop
SendLoop()
static void Telepathy.Common.SendLoop (int connectionId, TcpClient client, SafeQueue< byte[]> sendQueue, ManualResetEvent sendPending) inline static protected inherited
Definition at line 87 of file Common.cs.
        {
            int num = 1;
            NetworkStream stream = client.GetStream();
            bool connected = client.Connected;
            bool flag = sendPending.Reset();
            if (num == 0)
            {
            }
        }
References System.Net.Sockets.TcpClient.Connected, System.Net.Sockets.TcpClient.GetStream(), j__TPar, and System.Threading.EventWaitHandle.Reset().
Referenced by Telepathy.Client.b__11_0().