terraria-cpp2il-methodrecon: GUIHairWindow.Draw
Draw()
void GUIHairWindow.Draw () inline
Definition at line 20 of file GUIHairWindow.cs.
    {
        Main.FlushBatches();
        int num = 1;
        bool flag = Main.npcChatText != "";
        if (num == 0)
        {
        }
        int myPlayer = Main.myPlayer;
        if (num == 0)
        {
        }
        if (Main.npcShop != 0)
        {
            if (num == 0)
            {
            }
            Main.CancelHairWindow();
            return;
        }
        if (num == 0)
        {
        }
        int myPlayer2 = Main.myPlayer;
        if (num == 0)
        {
        }
        bool inGuideCraftMenu = Main.InGuideCraftMenu;
        GUIControllerHairStylist controller = this._controller;
        this._controller.Activate();
        int num2 = 154;
        this.unlockedMaxHair = num2;
        if (num2 == 0)
        {
        }
        int num3 = this.unlockedMaxHair;
        this.unlockedMaxHair = num3;
        if (num3 == 0)
        {
        }
        int num4 = this.unlockedMaxHair;
        this.unlockedMaxHair = num4;
        if (num4 == 0)
        {
        }
        int myPlayer3 = Main.myPlayer;
        Rectangle rectangle;
        ControlAnchor.SetGridItemRegion(rectangle);
        bool drawSliders;
        if (!this.DrawSliders)
        {
            this.DrawHairGrid();
            drawSliders = this.DrawSliders;
            if (!drawSliders)
            {
                goto IL_00DA;
            }
        }
        this.DrawHSLSlider();
        IL_00DA:
        if (!drawSliders)
        {
        }
        Main.FlushBatches();
        this.DrawPlayer();
        Main.FlushBatches();
        this.DrawCategoryButtons();
        this.DrawButtons();
    }
References _controller, GUIControllerHairStylist.Activate(), Terraria.Main.CancelHairWindow(), DrawButtons(), DrawCategoryButtons(), DrawHairGrid(), DrawHSLSlider(), DrawPlayer(), DrawSliders, Terraria.Main.FlushBatches(), Terraria.Main.InGuideCraftMenu, j__TPar, Terraria.Main.myPlayer, Terraria.Main.npcShop, ControlAnchor.SetGridItemRegion(), and unlockedMaxHair.