terraria-cpp2il-methodrecon: GUIHairWindow.DrawButtons
DrawButtons()
void GUIHairWindow.DrawButtons () inline private
Definition at line 268 of file GUIHairWindow.cs.
    {
        Main.FlushBatches();
        this.DrawBuyButton();
        Main.FlushBatches();
        this.DrawCancelButton();
    }
References DrawBuyButton(), DrawCancelButton(), and Terraria.Main.FlushBatches().
Referenced by Draw().