terraria-cpp2il-methodrecon: Terraria.Utils.RandomInt
RandomInt() [1/2]
static int Terraria.Utils.RandomInt (ulong seed, int max) inline static
Definition at line 1687 of file Utils.cs.
        {
            if (!true)
            {
            }
            int num = 31;
            return Utils.RandomNext((ulong)4720931368828141568L, num);
        }
References Microsoft.Xna.Framework.Input.L, and Terraria.Utils.RandomNext().
Referenced by Terraria.Graphics.Renderers.FlameParticle.Draw(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItem(), and Terraria.Utils.RandomInt().