terraria-cpp2il-methodrecon: Terraria.Utils.Height
Height()
static int Terraria.Utils.Height (this Asset< Texture2D > asset) inline static
Definition at line 701 of file Utils.cs.
        {
        }
Referenced by Terraria.GameContent.UI.Elements.UIImage.UIImage(), Terraria.GameContent.UI.Elements.UIImageButton.UIImageButton(), Terraria.GameContent.UI.Elements.UISlicedImage.UISlicedImage(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawPanelBottom(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawPanelTop(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.Mount.SetAsHorse(), Terraria.Mount.SetAsMinecart(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetImage(), Terraria.GameContent.UI.Elements.UIImage.SetImage(), Terraria.GameContent.UI.Elements.UIImageButton.SetImage(), and Terraria.GameContent.UI.Elements.UIIconTextButton.SetText().