terraria-cpp2il-methodrecon: Newtonsoft.Json.JsonTextReader.ReadData
ReadData() [1/2]
int Newtonsoft.Json.JsonTextReader.ReadData (bool append) inline private
Definition at line 100 of file JsonTextReader.cs.
        {
            long num = 0L;
            return this.ReadData(append, (int)num);
        }
References System.L, and Newtonsoft.Json.JsonTextReader.ReadData().
Referenced by Newtonsoft.Json.JsonTextReader.EatWhitespace(), Newtonsoft.Json.JsonTextReader.ReadData(), and Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer().