terraria-cpp2il-methodrecon: Mono.Net.Security.ChainValidationHelper.ChainValidationHelper
ChainValidationHelper()
Mono.Net.Security.ChainValidationHelper.ChainValidationHelper (global::System::Net::Security::SslStream owner, MobileTlsProvider provider, MonoTlsSettings settings, bool cloneSettings, MonoTlsStream stream) inline private
Definition at line 32 of file ChainValidationHelper.cs.
        {
            MonoTlsSettings monoTlsSettings;
            MobileTlsProvider providerInternal;
            if (settings != null)
            {
                if (provider == null)
                {
                    return;
                }
            }
            else
            {
                monoTlsSettings = MonoTlsSettings.CopyDefaultSettings().CloneWithValidator(this);
                if (provider == null)
                {
                    providerInternal = MonoTlsProviderFactory.GetProviderInternal();
                }
            }
            this.settings = monoTlsSettings;
            this.provider = providerInternal;
            this.tlsStream = stream;
            if (owner != null)
            {
            }
            if (monoTlsSettings != null)
            {
                global::System.Net.ServerCertValidationCallback validationCallback = ChainValidationHelper.GetValidationCallback(monoTlsSettings);
                this.certValidationCallback = validationCallback;
                global::System.Net.Security.LocalCertSelectionCallback localCertSelectionCallback = Mono.Net.Security.Private.CallbackHelpers.MonoToInternal(monoTlsSettings.<ClientCertificateSelectionCallback>k__BackingField);
                this.certSelectionCallback = localCertSelectionCallback;
                if (stream == null)
                {
                    if (owner == null)
                    {
                        return;
                    }
                    goto IL_00A0;
                }
            }
            else
            {
                while (stream == null)
                {
                }
            }
            global::System.Net.HttpWebRequest httpWebRequest = stream.request;
            global::System.Net.ServerCertValidationCallback serverCertValidationCallback = this.certValidationCallback;
            this.request = httpWebRequest;
            if (serverCertValidationCallback == null)
            {
                global::System.Net.ServerCertValidationCallback serverCertValidationCallback2 = httpWebRequest.certValidationCallback;
            }
            if (this.certSelectionCallback == null)
            {
            }
            IL_00A0:
            global::System.Net.ServerCertValidationCallback serverCertValidationCallback3 = this.certValidationCallback;
            if (serverCertValidationCallback3 == null)
            {
                if (serverCertValidationCallback3 == null)
                {
                }
                if (!true)
                {
                }
                this.certValidationCallback = 1;
            }
        }
References Mono.Net.Security.ChainValidationHelper.certSelectionCallback, Mono.Net.Security.ChainValidationHelper.certValidationCallback, Mono.Security.Interface.MonoTlsSettings.CloneWithValidator(), Mono.Security.Interface.MonoTlsSettings.CopyDefaultSettings(), Mono.Net.Security.MonoTlsProviderFactory.GetProviderInternal(), Mono.Net.Security.ChainValidationHelper.GetValidationCallback(), j__TPar, Mono.Net.Security.Private.CallbackHelpers.MonoToInternal(), Mono.Net.Security.ChainValidationHelper.owner, Mono.Net.Security.ChainValidationHelper.provider, Mono.Net.Security.MonoTlsStream.request, and Mono.Net.Security.ChainValidationHelper.settings.