terraria-cpp2il-methodrecon: Terraria.GameContent.Tile_Entities.TELogicSensor.Place
Place()
static int Terraria.GameContent.Tile_Entities.TELogicSensor.Place (int x, int y) inline static
Definition at line 271 of file TELogicSensor.cs.
        {
            if (!true)
            {
            }
            int num = TileEntity.AssignNewID();
            if (!true)
            {
            }
            Monitor.Enter(x, x != 0);
            long num2 = 0L;
            Monitor.Exit(x);
            if (num2 == 0L)
            {
                return x;
            }
            throw new OutOfMemoryException();
        }
References Terraria.DataStructures.TileEntity.AssignNewID(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), j__TPar, and System.L.
Referenced by Terraria.GameContent.Tile_Entities.TELogicSensor.NetPlaceEntity().