terraria-cpp2il-methodrecon: System.IO.UnmanagedMemoryStream.SetLength
SetLength()
override void System.IO.UnmanagedMemoryStream.SetLength (long value) inline inherited
Definition at line 342 of file UnmanagedMemoryStream.cs.
        {
            if (this._buffer == null)
            {
                this.EnsureNotClosed();
                this.EnsureWriteable();
                long capacity = this._capacity;
                long num = 0L;
                long num3;
                long num2 = Interlocked.Read(num3);
                Buffer.ZeroMemory(this._mem, num);
                long num5;
                long num4 = Interlocked.Exchange(num5, value);
                return;
            }
        }
References System.IO.UnmanagedMemoryStream._buffer, System.IO.UnmanagedMemoryStream._capacity, System.IO.UnmanagedMemoryStream._mem, System.capacity, System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureWriteable(), System.Threading.Interlocked.Exchange(), j__TPar, System.L, System.Threading.Interlocked.Read(), System.value, and System.Buffer.ZeroMemory().