terraria-cpp2il-methodrecon: System.Net.NetEventSource.IdOf
IdOf()
static string System.Net.NetEventSource.IdOf (object value) inline static
Definition at line 387 of file NetEventSource.cs.
        {
            string text;
            return text;
        }
References System.text.
Referenced by System.Net.NetEventSource.Associate(), System.Net.NetEventSource.Associate(), System.Net.NetEventSource.Enter(), System.Net.NetEventSource.Enter(), System.Net.NetEventSource.Enter(), System.Net.NetEventSource.Enter(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Exit(), System.Net.NetEventSource.Exit(), System.Net.NetEventSource.Exit(), System.Net.NetEventSource.Fail(), System.Net.NetEventSource.Fail(), System.Net.NetEventSource.Format(), System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Info().