terraria-cpp2il-methodrecon: System.Net.NetEventSource.Info
Info() [1/3]
static void System.Net.NetEventSource.Info (object thisOrContextObject, [Optional] FormattableString formattableString, [Optional] string memberName) inline static
Definition at line 156 of file NetEventSource.cs.
        {
            if (!true)
            {
            }
            bool isEnabled = NetEventSource.IsEnabled;
            if (!true)
            {
            }
            string text = NetEventSource.IdOf(thisOrContextObject);
            if (formattableString != null)
            {
                if (!true)
                {
                }
                string text2 = NetEventSource.Format(formattableString);
                return;
            }
        }
References System.Net.NetEventSource.Format(), System.Net.NetEventSource.IdOf(), System.Net.NetEventSource.IsEnabled, j__TPar, and System.text.
Referenced by System.Net.FtpWebRequest.FtpWebRequest(), System.Net.CommandStream.Abort(), System.Net.FtpWebRequest.AttemptedRecovery(), System.Net.FtpWebRequest.BeginGetRequestStream(), System.Net.FtpWebRequest.BeginGetResponse(), System.Net.ContextAwareResult.CaptureOrComplete(), System.Net.FtpControlStream.CheckValid(), System.Net.FtpDataStream.CloseEx(), System.Net.ContextAwareResult.Complete(), System.Net.CommandStream.ContinueCommandPipeline(), System.Net.FtpWebRequest.EnsureFtpWebResponse(), System.Net.NTAuthentication.GetClientSpecifiedSpn(), System.Net.NTAuthentication.GetOutgoingBlob(), System.Net.FtpWebRequest.GetRequestStream(), System.Net.NTAuthentication.Initialize(), System.Net.FtpControlStream.PipelineCallback(), System.Net.FtpControlStream.QueueOrCreateDataConection(), System.Net.FtpWebRequest.SubmitRequest(), and System.Net.FtpWebRequest.TimerCallback().