terraria-cpp2il-methodrecon: Ionic.Zip.SharedUtilities.InternalGetTempFileName
InternalGetTempFileName()
static string Ionic.Zip.SharedUtilities.InternalGetTempFileName () inline static
Definition at line 223 of file SharedUtilities.cs.
        {
            if (!true)
            {
            }
            long num = 0L;
            string text = SharedUtilities.GenerateRandomStringImpl(8, (int)num);
            return "DotNetZip-" + text + ".tmp";
        }
References Ionic.Zip.SharedUtilities.GenerateRandomStringImpl(), System.L, and System.text.
Referenced by Ionic.Zip.SharedUtilities.CreateAndOpenUniqueTempFile(), and Ionic.Zip.ZipSegmentedStream.TruncateBackward().