terraria-cpp2il-methodrecon: GUIWiresUI.IsOver
IsOver()
bool GUIWiresUI.IsOver (Microsoft::Xna::Framework::Vector2 cursorPosition) inline
Definition at line 221 of file GUIWiresUI.cs.
    {
        if (!true)
        {
        }
        bool gameMenu = Main.gameMenu;
        if (this.DisplayOptions)
        {
            bool drawToolModeUI = WiresUI.Settings.DrawToolModeUI;
            InterfaceProfile_Layout active = InterfaceStyles_Layout.Active;
            bool flag = active.AnyOpen();
            bool flag2 = active.IsPageSelected(GUIPageIcons.Category.Inventory);
            if (this.CalculateRegion() == null)
            {
            }
            bool flag3;
            return flag3;
        }
    }
References InterfaceStyles_Layout.Active, InterfaceProfile_Layout.AnyOpen(), CalculateRegion(), DisplayOptions, Terraria.GameContent.UI.WiresUI.Settings.DrawToolModeUI, Terraria.Main.gameMenu, InterfaceProfile_Layout.IsPageSelected(), and j__TPar.