terraria-cpp2il-methodrecon: GUIWiresUI.Close
Close()
void GUIWiresUI.Close () inline
Definition at line 210 of file GUIWiresUI.cs.
    {
        if (this.DisplayOptions)
        {
            GUIControllerWiresUI controller = this._controller;
            int selectedItem = Main.LocalPlayer.selectedItem;
            return;
        }
    }
References _controller, DisplayOptions, j__TPar, Terraria.Main.LocalPlayer, and Terraria.Player.selectedItem.
Referenced by GUIInstance.CloseDialoguesAndPopups(), DrawOverlay(), and PlayerMenuDisplayToggle().