terraria-cpp2il-methodrecon: GUIWiresUI.DrawOverlay
DrawOverlay()
void GUIWiresUI.DrawOverlay () inline
Definition at line 153 of file GUIWiresUI.cs.
    {
        if (this.DisplayOptions)
        {
            Rectangle rectangle = this.CalculateRegion();
            this.Close();
        }
        bool drawToolModeUI = WiresUI.Settings.DrawToolModeUI;
        global::Cursor cursor;
        if (cursor != null)
        {
            Microsoft.Xna.Framework.Vector2 uicursorPosition = Mouse.GetUICursorPosition();
            if (this.CalculateRegion() == null)
            {
            }
            bool key = KeyboardInput.GetKey(KeyCode.Mouse1);
        }
        bool drawToolModeUI2 = WiresUI.Settings.DrawToolModeUI;
        if (this.DisplayOptions)
        {
            Main.FlushBatches();
            GUIControllerWiresUI controller = this._controller;
            this._controller.Activate();
            string textValue = Language.GetTextValue("Mobile.FilterItemsClose");
            bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
            return;
        }
    }
References _controller, GUIControllerWiresUI.Activate(), Controller.ControllerActionManager.AnyControllerConnected, CalculateRegion(), Close(), DisplayOptions, Terraria.GameContent.UI.WiresUI.Settings.DrawToolModeUI, Terraria.Main.FlushBatches(), KeyboardInput.GetKey(), Terraria.Localization.Language.GetTextValue(), Microsoft.Xna.Framework.Input.Mouse.GetUICursorPosition(), j__TPar, and System.key.