terraria-cpp2il-methodrecon: Ionic.Zip.ZipFile.AddDirectoryByName
AddDirectoryByName()
ZipEntry Ionic.Zip.ZipFile.AddDirectoryByName (string directoryNameInArchive) inline
Definition at line 346 of file ZipFile.cs.
        {
            if (!true)
            {
            }
            ZipEntry zipEntry = ZipEntry.CreateFromNothing(directoryNameInArchive);
            zipEntry.MarkAsDirectory();
            Encoding alternateEncoding = this._alternateEncoding;
            zipEntry.<AlternateEncoding>k__BackingField = alternateEncoding;
            ZipOption alternateEncodingUsage = this._alternateEncodingUsage;
            zipEntry.<AlternateEncodingUsage>k__BackingField = alternateEncodingUsage;
            if (alternateEncodingUsage == ZipOption.Default)
            {
            }
            DateTime now = DateTime.Now;
            DateTime now2 = DateTime.Now;
            DateTime now3 = DateTime.Now;
            zipEntry.SetEntryTimes(now, now2, now3);
            bool emitNtfsTimes = this._emitNtfsTimes;
            string fileNameInArchive = zipEntry._FileNameInArchive;
            zipEntry._emitNtfsTimes = emitNtfsTimes;
            bool emitUnixTimes = this._emitUnixTimes;
            zipEntry._metadataChanged = true;
            zipEntry._emitUnixTimes = emitUnixTimes;
            zipEntry._Source = ZipEntrySource.Stream;
            this.InternalAddEntry(fileNameInArchive, zipEntry);
            this.AfterAddEntry(zipEntry);
            return zipEntry;
        }
References Ionic.Zip.ZipFile._alternateEncoding, Ionic.Zip.ZipFile._alternateEncodingUsage, Ionic.Zip.ZipFile._emitNtfsTimes, Ionic.Zip.ZipFile._emitUnixTimes, Ionic.Zip.ZipEntry._FileNameInArchive, Ionic.Zip.ZipFile.AfterAddEntry(), Ionic.Zip.ZipFile.AlternateEncoding, Ionic.Zip.ZipFile.AlternateEncodingUsage, Ionic.Zip.ZipEntry.CreateFromNothing(), Ionic.Zip.ZipFile.InternalAddEntry(), j__TPar, Ionic.Zip.ZipFile.k__BackingField, Ionic.Zip.ZipEntry.MarkAsDirectory(), and System.DateTime.Now.