terraria-cpp2il-methodrecon: Ionic.Zip.ZipFile.OnZipErrorSaving
OnZipErrorSaving()
bool Ionic.Zip.ZipFile.OnZipErrorSaving (ZipEntry entry, Exception exc) inline package
Definition at line 2039 of file ZipFile.cs.
        {
            if (this.ZipError != null)
            {
                object @lock = this.LOCK;
                Monitor.Enter(@lock);
                ZipErrorEventArgs zipErrorEventArgs = ZipErrorEventArgs.Saving(this._name, entry, exc);
                EventHandler<ZipErrorEventArgs> zipError = this.ZipError;
                if (zipErrorEventArgs._cancel)
                {
                    this._saveOperationCanceled = true;
                }
                Monitor.Exit(@lock);
            }
            return this._saveOperationCanceled;
        }
References Ionic.Zip.ZipProgressEventArgs._cancel, Ionic.Zip.ZipFile._name, Ionic.Zip.ZipFile._saveOperationCanceled, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), j__TPar, Ionic.Zip.ZipFile.LOCK, Ionic.Zip.ZipErrorEventArgs.Saving(), and Ionic.Zip.ZipFile.ZipError.
Referenced by Ionic.Zip.ZipEntry.OnZipErrorWhileSaving().