terraria-cpp2il-methodrecon: Ionic.Zip.ZipFile.OnExtractExisting
OnExtractExisting()
bool Ionic.Zip.ZipFile.OnExtractExisting (ZipEntry entry, string path) inline package
Definition at line 1918 of file ZipFile.cs.
        {
            if (this.ExtractProgress != null)
            {
                string name = this._name;
                if (ExtractProgressEventArgs.ExtractExisting("(stream)", entry, path)._cancel)
                {
                    this._extractOperationCanceled = true;
                }
            }
            return this._extractOperationCanceled;
        }
References Ionic.Zip.ZipProgressEventArgs._cancel, Ionic.Zip.ZipFile._extractOperationCanceled, Ionic.Zip.ZipFile._name, Ionic.Zip.ExtractProgressEventArgs.ExtractExisting(), Ionic.Zip.ZipFile.ExtractProgress, j__TPar, and System.name.
Referenced by Ionic.Zip.ZipEntry.CheckExtractExistingFile(), and Ionic.Zip.ZipEntry.OnExtractExisting().