terraria-cpp2il-methodrecon: Ionic.Zip.ZipFile._InternalAddEntry
_InternalAddEntry()
ZipEntry Ionic.Zip.ZipFile._InternalAddEntry (ZipEntry ze) inline private
Definition at line 221 of file ZipFile.cs.
        {
            CompressionMethod compressionMethod = this._compressionMethod;
            ze.CompressionMethod = compressionMethod;
            CompressionLevel compressionLevel = this.<CompressionLevel>k__BackingField;
            ze.CompressionLevel = compressionLevel;
            ExtractExistingFileAction extractExistingFileAction = this.<ExtractExistingFile>k__BackingField;
            ze.<ExtractExistingFile>k__BackingField = extractExistingFileAction;
            if (this.ZipError != null)
            {
                this._zipErrorAction = ZipErrorAction.InvokeErrorEvent;
                return ze;
            }
            ZipErrorAction zipErrorAction = this._zipErrorAction;
            ze.<ZipErrorAction>k__BackingField = zipErrorAction;
            SetCompressionCallback setCompressionCallback = this.<SetCompression>k__BackingField;
            ze.<SetCompression>k__BackingField = setCompressionCallback;
            Encoding alternateEncoding = this._alternateEncoding;
            ze.<AlternateEncoding>k__BackingField = alternateEncoding;
            ZipOption alternateEncodingUsage = this._alternateEncodingUsage;
            ze.<AlternateEncodingUsage>k__BackingField = alternateEncodingUsage;
            string password = this._Password;
            ze._Password = password;
            if (password != null)
            {
                ZipEntrySource source = ze._Source;
                if (!ze._sourceIsEncrypted)
                {
                    ze._restreamRequiredOnSave = true;
                }
                if (ze._Encryption == EncryptionAlgorithm.None)
                {
                    ze._Encryption = EncryptionAlgorithm.PkzipWeak;
                    return ze;
                }
            }
            EncryptionAlgorithm encryption = this._Encryption;
            ze.Encryption = encryption;
            bool emitNtfsTimes = this._emitNtfsTimes;
            string fileNameInArchive = ze._FileNameInArchive;
            ze._emitNtfsTimes = emitNtfsTimes;
            bool emitUnixTimes = this._emitUnixTimes;
            ze._metadataChanged = true;
            ze._emitUnixTimes = emitUnixTimes;
            this.InternalAddEntry(fileNameInArchive, ze);
            this.AfterAddEntry(ze);
            return ze;
        }
References Ionic.Zip.ZipFile._alternateEncoding, Ionic.Zip.ZipFile._alternateEncodingUsage, Ionic.Zip.ZipFile._compressionMethod, Ionic.Zip.ZipFile._emitNtfsTimes, Ionic.Zip.ZipFile._emitUnixTimes, Ionic.Zip.ZipFile._Encryption, Ionic.Zip.ZipEntry._FileNameInArchive, Ionic.Zip.ZipFile._Password, Ionic.Zip.ZipFile._zipErrorAction, Ionic.Zip.ZipFile.AfterAddEntry(), Ionic.Zip.ZipFile.AlternateEncoding, Ionic.Zip.ZipFile.AlternateEncodingUsage, Ionic.Zip.ZipFile.ExtractExistingFile, Ionic.Zip.ZipFile.InternalAddEntry(), j__TPar, Ionic.Zip.ZipFile.k__BackingField, Ionic.Zip.ZipFile.SetCompression, System.source, and Ionic.Zip.ZipFile.ZipError.
Referenced by Ionic.Zip.ZipFile.AddEntry(), Ionic.Zip.ZipFile.AddEntry(), Ionic.Zip.ZipFile.AddEntry(), and Ionic.Zip.ZipFile.AddFile().