terraria-cpp2il-methodrecon: GUIPS4MultiplayerChecks.Draw
Draw()
void GUIPS4MultiplayerChecks.Draw () inline
Definition at line 54 of file GUIPS4MultiplayerChecks.cs.
    {
        if (this.displayingGenericError)
        {
            string text = this.genericError;
            GUITransactionButton.InputState inputState;
            if (inputState == GUITransactionButton.InputState.Clicked)
            {
                long num = 0L;
                this.Complete(num != 0L);
                return;
            }
        }
        else
        {
            string textValue = Language.GetTextValue("PS4.PermissionsCheck");
            if ("PS4.PermissionsCheck" == null)
            {
            }
            if (6899 == 0)
            {
            }
        }
        if (this.EditorCheckingPermissions)
        {
            this.EditorCheckPermissionsUpdate();
        }
        if (this.parentalFailed)
        {
            long num2 = 0L;
            this.Complete(num2 != 0L);
        }
        if (this.displayedPlusSignup)
        {
            long num3 = 0L;
            this.Complete(num3 != 0L);
        }
    }
References Complete(), displayedPlusSignup, displayingGenericError, EditorCheckingPermissions, EditorCheckPermissionsUpdate(), genericError, Terraria.Localization.Language.GetTextValue(), j__TPar, System.L, parentalFailed, and System.text.