terraria-cpp2il-methodrecon: UnityEngine.UI.Mask.GetModifiedMaterial
GetModifiedMaterial()
virtual Material UnityEngine.UI.Mask.GetModifiedMaterial (Material baseMaterial) inline virtual
Implements UnityEngine.UI.IMaterialModifier.
Definition at line 140 of file Mask.cs.
        {
            Transform transform = MaskUtilities.FindRootSortOverrideCanvas(base.transform);
            int stencilDepth = MaskUtilities.GetStencilDepth(base.transform, transform);
            bool showMaskGraphic = this.m_ShowMaskGraphic;
            StencilMaterial.Remove(this.m_MaskMaterial);
            Material material;
            this.m_MaskMaterial = material;
            CanvasRenderer canvasRenderer = this.graphic.canvasRenderer;
            int num = 1;
            canvasRenderer.hasPopInstruction = num != 0;
            Material material2;
            return material2;
        }
References UnityEngine.UI.Graphic.canvasRenderer, UnityEngine.UI.MaskUtilities.FindRootSortOverrideCanvas(), UnityEngine.UI.MaskUtilities.GetStencilDepth(), UnityEngine.UI.Mask.graphic, j__TPar, UnityEngine.UI.Mask.m_MaskMaterial, UnityEngine.UI.Mask.m_ShowMaskGraphic, UnityEngine.UI.StencilMaterial.Remove(), UnityEngine.UI.Mask.showMaskGraphic, and UnityEngine.Component.transform.