terraria-cpp2il-methodrecon: System.Net.FileWebRequest.BeginGetRequestStream
BeginGetRequestStream()
override IAsyncResult System.Net.FileWebRequest.BeginGetRequestStream (AsyncCallback callback, object state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 285 of file FileWebRequest.cs.
        {
            if (this.m_Aborted == 0)
            {
                bool flag = this.CanGetRequestStream();
                WebResponse response = this.m_response;
                if (this.m_writePending)
                {
                    goto IL_006F;
                }
                int num = 1;
                long num2 = 0L;
                this.m_writePending = num != 0;
                int num3 = 14;
                if (num != 0)
                {
                    Monitor.Exit(this);
                }
                if (num2 != 0L)
                {
                    goto IL_007B;
                }
                if (num3 == 0)
                {
                    LazyAsyncResult readAResult = this.m_ReadAResult;
                    LazyAsyncResult readAResult2 = this.m_ReadAResult;
                }
            }
            WebException requestAbortedException = ExceptionHelper.RequestAbortedException;
            string @string = SR.GetString("Cannot send a content-body with this verb-type.");
            string string2 = SR.GetString("This operation cannot be performed after the request has been submitted.");
            IL_006F:
            string string3 = SR.GetString("Cannot re-call BeginGetRequestStream/BeginGetResponse while a previous call is still in progress.");
            IL_007B:
            throw new OutOfMemoryException();
        }
References System.Net.FileWebRequest.CanGetRequestStream(), System.Threading.Monitor.Exit(), SR.GetString(), j__TPar, System.L, System.Net.FileWebRequest.m_Aborted, System.Net.FileWebRequest.m_ReadAResult, System.Net.FileWebRequest.m_response, System.Net.FileWebRequest.m_writePending, and System.Net.ExceptionHelper.RequestAbortedException.