terraria-cpp2il-methodrecon: System.Runtime.Remoting.SingletonIdentity.GetServerObject
GetServerObject()
MarshalByRefObject System.Runtime.Remoting.SingletonIdentity.GetServerObject () inline
Definition at line 18 of file SingletonIdentity.cs.
        {
            while (this._serverObject != null)
            {
            }
            if (this._serverObject != null)
            {
            }
            Type objectType = this._objectType;
            int num = 1;
            object obj = Activator.CreateInstance(objectType, num != 0);
            if (obj != null)
            {
            }
            Context context = AppDomain.InternalGetDefaultContext();
            if (obj != null && obj == null)
            {
                throw new InvalidCastException();
            }
            long num2 = 0L;
            Monitor.Exit(this);
            if (num2 == 0L)
            {
                return this._serverObject;
            }
            throw new OutOfMemoryException();
        }
References System.Runtime.Remoting.ServerIdentity._objectType, System.Runtime.Remoting.ServerIdentity._serverObject, System.Activator.CreateInstance(), System.Threading.Monitor.Exit(), System.AppDomain.InternalGetDefaultContext(), j__TPar, System.L, and System.obj.