terraria-cpp2il-methodrecon: Terraria.UI.ItemSlot.UpdateTooltipContext
UpdateTooltipContext()
static void Terraria.UI.ItemSlot.UpdateTooltipContext (int context, int slot) inline static
Definition at line 972 of file ItemSlot.cs.
        {
            global::Cursor cursor;
            if (cursor != null)
            {
            }
        }
References j__TPar.
Referenced by GUICraftGuidePopup.CraftItemOver(), GUICraftGuide.GuideItemOver(), GUIAccessoryInfoToggles.InfoAccOver(), GUIBuffs.ItemOver(), GUIBuilderAccToggles.ItemOver(), GUIHotbar.ItemOver(), GUIEquipmentLoadout.LoadoutOver(), GUICraftGuidePopup.MaterialItemOver(), GUICrafting.MaterialItemOver(), GUIHousingMenu.NPCOver(), GUIPVPIcons.PlayerOver(), GUIReforge.ReforgeItemOver(), and GUIPVPIcons.TeamOver().