terraria-cpp2il-methodrecon: Terraria.UI.ItemSlot.SetSelectHighlight
SetSelectHighlight()
static void Terraria.UI.ItemSlot.SetSelectHighlight (bool hasFocus, float highlightScale = -1f) inline static
Definition at line 702 of file ItemSlot.cs.
        {
            if (!true)
            {
            }
        }
Referenced by GUIEquipment.AccessoryDraw(), GUIDisplayDoll.AccessoryDraw(), GUIEquipment.AccessoryDyeDraw(), GUIDisplayDoll.AccessoryDyeDraw(), GUIEquipment.AccessoryVanityDraw(), GUIEquipment.ArmourDraw(), GUIDisplayDoll.ArmourDraw(), GUIEquipment.ArmourDyeDraw(), GUIDisplayDoll.ArmourDyeDraw(), GUIEquipment.ArmourVanityDraw(), GUICraftGuidePopup.CraftItemDraw(), GUIItemDuplication.CraftItemDraw(), GUIHatRack.HatDraw(), GUIHatRack.HatDyeDraw(), GUIAmmo.ItemDraw(), GUIChest.ItemDraw(), GUICoins.ItemDraw(), GUIShop.ItemDraw(), GUIEquipment.QuickSlotDyeDraw(), and GUIResearchPage.ResearchItemDraw().