terraria-cpp2il-methodrecon: System.Threading.Thread.GetMutableExecutionContext
GetMutableExecutionContext()
ExecutionContext System.Threading.Thread.GetMutableExecutionContext () inline package
Definition at line 139 of file Thread.cs.
        {
            ExecutionContext executionContext;
            do
            {
                executionContext = this.m_ExecutionContext;
            }
            while (executionContext == null || !this.m_ExecutionContextBelongsToOuterScope);
            ExecutionContext executionContext2 = executionContext.CreateMutableCopy();
            this.m_ExecutionContext = executionContext2;
            return executionContext2;
        }
References System.Threading.ExecutionContext.CreateMutableCopy(), j__TPar, System.Threading.Thread.m_ExecutionContext, and System.Threading.Thread.m_ExecutionContextBelongsToOuterScope.
Referenced by System.Runtime.Remoting.RemotingServices.DeserializeCallData(), System.Runtime.Remoting.Messaging.CallContext.LogicalSetData(), System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(), System.Threading.ExecutionContext.SetLocalValue(), System.Runtime.Remoting.Messaging.CallContext.SetLogicalCallContext(), and System.Threading.SynchronizationContext.SetSynchronizationContext().