terraria-cpp2il-methodrecon: GUIReforge.Draw
Draw()
void GUIReforge.Draw () inline
Definition at line 96 of file GUIReforge.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        int myPlayer = Main.myPlayer;
        if (num == 0)
        {
        }
        if (Main.npcShop != 0)
        {
            if (num == 0)
            {
            }
            Main.InReforgeMenu = false;
            int myPlayer2 = Main.myPlayer;
            long num2 = 0L;
            Recipe.FindRecipes(num2 != 0L);
            return;
        }
        int myPlayer3 = Main.myPlayer;
        bool inGuideCraftMenu = Main.InGuideCraftMenu;
        !0 instance = PageControllerLayoutDefinition.Instance;
        !0 instance2 = PageControllerLayoutDefinition.Instance;
        !0 instance3 = PageControllerLayoutDefinition.Instance;
        DraggableItemGrid_Layout draggableItemGrid_Layout;
        int itemCount = draggableItemGrid_Layout.ItemCount;
        Rectangle rectangle;
        if (rectangle == null)
        {
        }
        int mouseX = Main.mouseX;
        int mouseY = Main.mouseY;
        !0 instance4 = PageControllerLayoutDefinition.Instance;
        if (PageControllerLayoutDefinition.Instance == null)
        {
        }
        GUIControllerReforge guicontrollerReforge;
        long num3;
        if (guicontrollerReforge != null)
        {
            num3 = 0L;
            GUIControllerDynamicGridNavigator guicontrollerDynamicGridNavigator;
            guicontrollerDynamicGridNavigator.DisableScrollUntilChange();
        }
        Item item;
        int type = item.type;
        Item item2;
        bool flag = item2.Prefix((int)num3);
        !0 instance5 = PageControllerLayoutDefinition.Instance;
        !0 instance6 = PageControllerLayoutDefinition.Instance;
        if (PageControllerLayoutDefinition.Instance == null)
        {
        }
        !0 instance7 = PageControllerLayoutDefinition.Instance;
        !0 instance8 = PageControllerLayoutDefinition.Instance;
        !0 instance9 = PageControllerLayoutDefinition.Instance;
        !0 instance10 = PageControllerLayoutDefinition.Instance;
        if (PageControllerLayoutDefinition.Instance == null)
        {
        }
        !0 instance11 = PageControllerLayoutDefinition.Instance;
    }
References GUIControllerDynamicGridNavigator.DisableScrollUntilChange(), Terraria.Recipe.FindRecipes(), Terraria.Main.InGuideCraftMenu, PageControllerLayoutDefinition< T >.Instance, System.item, ItemGrid_Layout.ItemCount, j__TPar, System.L, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npcShop, Terraria.Item.Prefix(), and Terraria.Item.type.