terraria-cpp2il-methodrecon: Terraria.IO.WorldFile.SaveWorld
SaveWorld() [1/2]
static void Terraria.IO.WorldFile.SaveWorld (bool useCloudSaving, bool resetTime = false, WorldFile::WorldSaveContext saveContext = WorldFile::WorldSaveContext::Normal) inline static
Definition at line 233 of file WorldFile.cs.
        {
            if (!true)
            {
            }
            if ("World" == null)
            {
            }
            string text = DateTime.Now.ToString() + " Saving the world";
            Debug.Log(text);
            if (text != null)
            {
                string text3;
                string text2 = text + " " + text3 + "%";
                Thread.Sleep(0);
                return;
            }
            long num = 0L;
            int num2 = 14;
            if (num != 0L)
            {
                throw new OutOfMemoryException();
            }
            if (num2 == 0)
            {
                Debug.Log(DateTime.Now.ToString() + " World saving locked out");
                long num3 = 0L;
                Thread.Sleep((int)num3);
                return;
            }
        }
References j__TPar, System.L, UnityEngine.Debug.Log(), System.DateTime.Now, System.Threading.Thread.Sleep(), System.text, and System.DateTime.ToString().