terraria-cpp2il-methodrecon: Terraria.IO.WorldFile.LoadWorld_LastMinuteFixes
LoadWorld_LastMinuteFixes()
static void Terraria.IO.WorldFile.LoadWorld_LastMinuteFixes () inline static private
Definition at line 869 of file WorldFile.cs.
        {
            if (!true)
            {
            }
            if (!true)
            {
            }
            WorldFile.ConvertIlluminantPaintToNewField();
            if (!true)
            {
            }
            WorldFile.FixAgainstExploits();
        }
References Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), and Terraria.IO.WorldFile.FixAgainstExploits().
Referenced by Terraria.IO.WorldFile.LoadWorld_Version2().