terraria-cpp2il-methodrecon: System.Xml.DomNameTable.AddName
AddName()
XmlName System.Xml.DomNameTable.AddName (string prefix, string localName, string ns, IXmlSchemaInfo schemaInfo) inline
Definition at line 46 of file DomNameTable.cs.
        {
            XmlName xmlName;
            if (prefix != null)
            {
                if (ns != null)
                {
                    int hashCode = XmlName.GetHashCode(localName);
                    int num = this.mask;
                    XmlName[] array = this.entries;
                    XmlNameTable xmlNameTable = this.nameTable;
                    XmlNameTable xmlNameTable2 = this.nameTable;
                    XmlNameTable xmlNameTable3 = this.nameTable;
                    int num2 = this.mask;
                    XmlName[] array2 = this.entries;
                    XmlDocument xmlDocument = this.ownerDocument;
                    XmlName[] array3 = this.entries;
                    if (xmlName == null || xmlName != null)
                    {
                        int num3 = this.count;
                        XmlDocument xmlDocument2 = this.ownerDocument;
                        this.Grow();
                        return xmlName;
                    }
                    throw new ArrayTypeMismatchException();
                }
            }
            else
            {
                while (ns != null)
                {
                }
            }
            return xmlName;
        }
References System.array, System.Xml.DomNameTable.count, System.Xml.DomNameTable.entries, System.Xml.XmlName.GetHashCode(), System.Xml.DomNameTable.Grow(), j__TPar, System.Xml.DomNameTable.mask, System.Xml.DomNameTable.nameTable, and System.Xml.DomNameTable.ownerDocument.
Referenced by System.Xml.XmlDocument.AddAttrXmlName(), and System.Xml.XmlDocument.AddXmlName().