terraria-cpp2il-methodrecon: Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer
IsAvailableForPlayer()
static bool Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer (ICreativePower power, int playerIndex) inline static
Definition at line 201 of file CreativePowersHelper.cs.
        {
            if (!true)
            {
                return;
            }
        }
Referenced by Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnClick(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.button_OnClick(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnClick(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChangeAndSetSlider(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.SetValueKeyboard(), and Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.SetValueKeyboardForced().