terraria-cpp2il-methodrecon: Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded
AddPermissionTextIfNeeded()
static void Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded (ICreativePower power, string originalText) inline static
Definition at line 133 of file CreativePowersHelper.cs.
        {
            if (!true)
            {
            }
            int myPlayer = Main.myPlayer;
            bool flag = CreativePowersHelper.IsAvailableForPlayer(power, myPlayer);
            string textValue = Language.GetTextValue("CreativePowers.CantUsePowerBecauseOfNoPermissionFromServer");
        }
References Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer(), j__TPar, and Terraria.Main.myPlayer.
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.UpdateSliderAndShowMultiplierMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateSliderAndShowMultiplierMouseOver(), and Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver().