terraria-cpp2il-methodrecon: GUIHearts.GetHeartsRegion
GetHeartsRegion()
Rectangle GUIHearts.GetHeartsRegion () inline
Definition at line 48 of file GUIHearts.cs.
    {
        RightSideHUDAnchorUpdator.Update();
        Rectangle right_Root = ControlAnchor.Right_Root;
        if (!true)
        {
        }
        Microsoft.Xna.Framework.Vector2 vector = right_Root.TopLeft();
        ItemGrid_Layout heartsGrid = this.HeartsGrid;
        int num = this.lastHeartCount;
        int num2 = this.heartCount;
        bool flag = this.LayoutCache.Dirty(heartsGrid);
        float x = this.lastAnchorPoint.X;
        float y = this.lastAnchorPoint.Y;
        int num3 = this.heartCount;
        CachedGridLayoutSettings layoutCache = this.LayoutCache;
        this.lastHeartCount = num3;
        layoutCache.Cache(heartsGrid);
        int num4 = this.heartCount;
        if (num3 == 0)
        {
        }
        if (num2 == 0)
        {
        }
        Rectangle rectangle;
        this.HeartsRegion = rectangle;
        Rectangle heartsRegion = this.HeartsRegion;
        int width = this.HeartsRegion.Width;
        return heartsRegion;
    }
References CachedGridLayoutSettings.Cache(), CachedGridLayoutSettings.Dirty(), heartCount, HeartsGrid, HeartsRegion, j__TPar, lastAnchorPoint, lastHeartCount, LayoutCache, ControlAnchor.Right_Root, RightSideHUDAnchorUpdator.Update(), and Microsoft.Xna.Framework.Rectangle.Width.