terraria-cpp2il-methodrecon: System.Globalization.CultureInfo.ConstructInvariant
ConstructInvariant()
void System.Globalization.CultureInfo.ConstructInvariant (bool read_only) inline private
Definition at line 559 of file CultureInfo.cs.
        {
            this.cultureID = 127;
            NumberFormatInfo invariantInfo = NumberFormatInfo.InvariantInfo;
            this.numInfo = invariantInfo;
            object obj = invariantInfo.Clone();
            if (obj != null)
            {
                this.numInfo = obj;
                throw new InvalidCastException();
            }
            TextInfo invariant = TextInfo.Invariant;
            this.textInfo = invariant;
            this.englishname = "Invariant Language (Invariant Country)";
            this.nativename = "Invariant Language (Invariant Country)";
            this.default_calendar_type = 257;
            this.win3lang = "IVL";
            this.iso3lang = "IVL";
            this.iso2lang = "iv";
        }
References System.Globalization.NumberFormatInfo.Clone(), System.Globalization.TextInfo.Invariant, System.Globalization.NumberFormatInfo.InvariantInfo, j__TPar, and System.obj.
Referenced by System.Globalization.CultureInfo.CultureInfo(), and System.Globalization.CultureInfo.CultureInfo().