terraria-cpp2il-methodrecon: ReLogic.OS.Windows.STATaskInvoker.TaskThreadStart
TaskThreadStart()
void ReLogic.OS.Windows.STATaskInvoker.TaskThreadStart () inline private
Definition at line 77 of file STATaskInvoker.cs.
        {
            if (this._shouldThreadContinue)
            {
                Action action = this._staTasks.Take();
                object taskCompletionLock = this._taskCompletionLock;
                Monitor.Enter(taskCompletionLock, true);
                IntPtr method_code = action.method_code;
                IntPtr method = action.method;
                IntPtr invoke_impl = action.invoke_impl;
                Monitor.Pulse(this._taskCompletionLock);
                long num = 0L;
                if (invoke_impl != 0)
                {
                    Monitor.Exit(taskCompletionLock);
                }
                while (num == 0L)
                {
                }
                return;
            }
        }
References ReLogic.OS.Windows.STATaskInvoker._shouldThreadContinue, ReLogic.OS.Windows.STATaskInvoker._staTasks, ReLogic.OS.Windows.STATaskInvoker._taskCompletionLock, System.action, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), j__TPar, System.L, System.Threading.Monitor.Pulse(), and System.Collections.Concurrent.BlockingCollection< T >.Take().