terraria-cpp2il-methodrecon: System.Globalization.CultureInfo.CultureInfo
CultureInfo() [6/8]
unsafe System.Globalization.CultureInfo.CultureInfo (string name, bool useUserOverride, bool read_only) inline private
Definition at line 635 of file CultureInfo.cs.
        {
            if (name == null)
            {
                return;
            }
            this.constructed = true;
            this.m_useUserOverride = true;
            Type type;
            bool flag = base.GetType() != type;
            long num3;
            if (name._stringLength != 0)
            {
                string text = name.ToLowerInvariant();
                bool flag2 = this.ConstructLocaleFromName(text);
                void* ptr = this.textinfo_data;
                string name2 = this.m_name;
                int num = this.datetime_index;
                int calendarType = this.CalendarType;
                int num2 = this.number_index;
                string text2 = this.iso2lang;
                num3 = 0L;
                CultureData cultureData;
                this.m_cultureData = cultureData;
                return;
            }
            CultureData invariant = CultureData.Invariant;
            this.m_cultureData = invariant;
            this.ConstructInvariant(num3 != 0L);
        }
References System.Globalization.CultureInfo.CalendarType, System.Globalization.CultureInfo.ConstructInvariant(), System.Globalization.CultureInfo.ConstructLocaleFromName(), System.Globalization.CultureInfo.datetime_index, System.Type.GetType(), System.Globalization.CultureData.Invariant, System.Globalization.CultureInfo.iso2lang, j__TPar, System.L, System.Globalization.CultureInfo.m_name, System.name, System.Globalization.CultureInfo.number_index, System.text, and System.Globalization.CultureInfo.textinfo_data.