terraria-cpp2il-methodrecon: Terraria.Social.Steam.CoreSocialModule.SteamTickLoop
SteamTickLoop()
void Terraria.Social.Steam.CoreSocialModule.SteamTickLoop (object context) inline private
Definition at line 66 of file CoreSocialModule.cs.
        {
            do
            {
                Monitor.Enter(this._steamTickLock);
                if (!this.IsSteamValid)
                {
                    break;
                }
                bool flag = Monitor.Wait(this._steamTickLock);
            }
            while (this.IsSteamValid);
            Monitor.Exit(this._steamTickLock);
        }
References Terraria.Social.Steam.CoreSocialModule._steamTickLock, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Terraria.Social.Steam.CoreSocialModule.IsSteamValid, and System.Threading.Monitor.Wait().