terraria-cpp2il-methodrecon: Terraria.Social.Steam.CoreSocialModule.PulseSteamCallback
PulseSteamCallback()
void Terraria.Social.Steam.CoreSocialModule.PulseSteamCallback () inline
Definition at line 53 of file CoreSocialModule.cs.
        {
            bool flag = Monitor.TryEnter(this._steamCallbackLock);
            Monitor.Pulse(this._steamCallbackLock);
            Monitor.Exit(this._steamCallbackLock);
        }
References Terraria.Social.Steam.CoreSocialModule._steamCallbackLock, System.Threading.Monitor.Exit(), System.Threading.Monitor.Pulse(), and System.Threading.Monitor.TryEnter().