terraria-cpp2il-methodrecon: System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet
GrovelForResourceSet()
ResourceSet System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (CultureInfo culture, Dictionary< string, ResourceSet > localResourceSets, bool tryParents, bool createIfNotExists, StackCrawlMark stackMark) inline
Implements System.Resources.IResourceGroveler.
Definition at line 21 of file ManifestBasedResourceGroveler.cs.
        {
            CultureInfo cultureInfo = this.UltimateFallbackFixup(culture);
            bool hasInvariantCultureName = cultureInfo.HasInvariantCultureName;
            if (this._mediator._rm._fallbackLoc != UltimateResourceFallbackLocation.MainAssembly && this.GetSatelliteAssembly(cultureInfo, stackMark) == null)
            {
                bool hasInvariantCultureName2 = culture.HasInvariantCultureName;
                UltimateResourceFallbackLocation fallbackLoc = this._mediator._rm._fallbackLoc;
            }
            ResourceManager rm = this._mediator._rm;
            RuntimeAssembly runtimeAssembly;
            if (runtimeAssembly != null)
            {
                long num = 0L;
                Monitor.Exit(localResourceSets);
                if (num != 0L || 7 != 0)
                {
                    goto IL_0082;
                }
                Stream stream;
                if (stream != null)
                {
                    return this.CreateResourceSet(stream, runtimeAssembly);
                }
            }
            if (true)
            {
                bool hasInvariantCultureName3 = culture.HasInvariantCultureName;
            }
            IL_0082:
            throw new OutOfMemoryException();
        }
References System.Resources.ResourceManager._fallbackLoc, System.Resources.ManifestBasedResourceGroveler._mediator, System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), System.culture, System.Threading.Monitor.Exit(), j__TPar, System.L, and System.Resources.ManifestBasedResourceGroveler.UltimateFallbackFixup().