terraria-cpp2il-methodrecon: System.Net.CookieTokenizer.Next
Next()
CookieToken System.Net.CookieTokenizer.Next (bool first, bool parseResponseCookies) inline package
Definition at line 207 of file CookieTokenizer.cs.
        {
            this.Reset();
            long num = 0L;
            long num2 = 0L;
            CookieToken cookieToken = this.FindNext(num != 0L, num2 != 0L);
            this.m_eofCookie = true;
            string text = this.Extract();
            this.m_name = text;
            if (text._stringLength != 0)
            {
                CookieToken cookieToken2 = this.TokenFromName(num != 0L);
                this.m_token = cookieToken2;
                return cookieToken2;
            }
            return CookieToken.Attribute;
        }
References System.Net.CookieTokenizer.Extract(), System.Net.CookieTokenizer.FindNext(), j__TPar, System.L, System.Net.CookieTokenizer.Reset(), System.text, and System.Net.CookieTokenizer.TokenFromName().
Referenced by System.Net.CookieParser.GetServer().