terraria-cpp2il-methodrecon: System.Runtime.Serialization.Formatters.Binary.SerStack.Push
Push()
void System.Runtime.Serialization.Formatters.Binary.SerStack.Push (object obj) inline package
Definition at line 14 of file SerStack.cs.
        {
            object[] array = this.objects;
            int num = this.top;
            this.IncreaseCapacity();
            if (obj == null || obj != null)
            {
                return;
            }
            throw new ArrayTypeMismatchException();
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.SerStack.IncreaseCapacity(), System.obj, System.Runtime.Serialization.Formatters.Binary.SerStack.objects, and System.Runtime.Serialization.Formatters.Binary.SerStack.top.
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.ObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseSerializedStreamHeader(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.PutObjectInfo(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup().