terraria-cpp2il-methodrecon: Terraria.GameContent.Shaders.WaterShaderData.PreDraw
PreDraw()
void Terraria.GameContent.Shaders.WaterShaderData.PreDraw (GameTime gameTime) inline private
Definition at line 191 of file WaterShaderData.cs.
        {
            this.ValidateRenderTargets();
            if (this._usingRenderTargets)
            {
                bool isGraphicsDeviceAvailable = Main.IsGraphicsDeviceAvailable;
                bool usePlayerWaves;
                if (!this._useProjectileWaves && !this._useRippleWaves && !this._useCustomWaves)
                {
                    usePlayerWaves = this._usePlayerWaves;
                    if (!usePlayerWaves)
                    {
                        if (this._isWaveBufferDirty || this._clearNextFrame)
{
                            DistortionRenderTargetManager.Instance.ClearRenderTarget();
                            return;
                        }
                        return;
                    }
                }
                int queuedSteps = this._queuedSteps;
                if (!usePlayerWaves)
                {
                }
                int num = 1;
                int num2 = Math.Min(queuedSteps, num);
                this.StepLiquids();
                return;
            }
        }
References Terraria.GameContent.Shaders.WaterShaderData._clearNextFrame, Terraria.GameContent.Shaders.WaterShaderData._isWaveBufferDirty, Terraria.GameContent.Shaders.WaterShaderData._queuedSteps, Terraria.GameContent.Shaders.WaterShaderData._useCustomWaves, Terraria.GameContent.Shaders.WaterShaderData._usePlayerWaves, Terraria.GameContent.Shaders.WaterShaderData._useProjectileWaves, Terraria.GameContent.Shaders.WaterShaderData._useRippleWaves, Terraria.GameContent.Shaders.WaterShaderData._usingRenderTargets, DistortionRenderTargetManager.ClearRenderTarget(), DistortionRenderTargetManager.Instance, Terraria.Main.IsGraphicsDeviceAvailable, j__TPar, System.Math.Min(), Terraria.GameContent.Shaders.WaterShaderData.StepLiquids(), and Terraria.GameContent.Shaders.WaterShaderData.ValidateRenderTargets().