terraria-cpp2il-methodrecon: VirtualDeviceExample.VirtualDevice.Update
Update()
override void VirtualDeviceExample.VirtualDevice.Update (ulong updateTick, float deltaTime) inline virtual
Reimplemented from InControl.InputDevice.
Definition at line 33 of file VirtualDevice.cs.
        {
            Vector2 vectorFromKeyboard = this.GetVectorFromKeyboard(deltaTime, true);
            Vector2 vectorFromMouse = this.GetVectorFromMouse(deltaTime, true);
            long num = 0L;
            bool key = Input.GetKey(KeyCode.Space);
            base.UpdateWithState(InputControlType.Action1, num != 0L, updateTick, deltaTime);
            bool key2 = Input.GetKey(KeyCode.S);
            base.UpdateWithState(InputControlType.Action2, num != 0L, updateTick, deltaTime);
            bool key3 = Input.GetKey(KeyCode.D);
            base.UpdateWithState(InputControlType.Action3, num != 0L, updateTick, deltaTime);
            bool key4 = Input.GetKey(KeyCode.F);
            base.UpdateWithState(InputControlType.Action4, num != 0L, updateTick, deltaTime);
        }
References UnityEngine.Input.GetKey(), VirtualDeviceExample.VirtualDevice.GetVectorFromKeyboard(), VirtualDeviceExample.VirtualDevice.GetVectorFromMouse(), j__TPar, System.key, and InControl.L.