terraria-cpp2il-methodrecon: Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Load
Load()
void Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Load (BinaryReader reader, int gameVersionSaveWasMadeOn) inline
Implements Terraria.GameContent.IPersistentPerWorldContent.
Definition at line 16 of file BestiaryUnlocksTracker.cs.
        {
            this.Kills.Load(reader, gameVersionSaveWasMadeOn);
            this.Sights.Load(reader, gameVersionSaveWasMadeOn);
            this.Chats.Load(reader, gameVersionSaveWasMadeOn);
        }
References Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Chats, j__TPar, Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Kills, Terraria.GameContent.Bestiary.NPCKillsTracker.Load(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.Load(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Load(), and Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Sights.