terraria-cpp2il-methodrecon: Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.CheckScrollBar
CheckScrollBar()
void Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.CheckScrollBar () inline private
Definition at line 60 of file UIBestiaryEntryInfoPage.cs.
        {
            UIScrollbar scrollbar = this._scrollbar;
            if (scrollbar != null)
            {
                bool canScroll = scrollbar.CanScroll;
                if (!this._isScrollbarAttached)
                {
                    UIScrollbar scrollbar2 = this._scrollbar;
                    base.Append(scrollbar2);
                    UIList list = this._list;
                    int num = 1;
                    this._isScrollbarAttached = num != 0;
                    return;
                }
            }
        }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage._isScrollbarAttached, Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage._list, Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage._scrollbar, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIScrollbar.CanScroll, j__TPar, and System.list.
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), and Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.Recalculate().