terraria-cpp2il-methodrecon: GUIReturnToTouch.Draw
Draw()
void GUIReturnToTouch.Draw (bool inBatch = false) inline
Definition at line 17 of file GUIReturnToTouch.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        XNAUnityRunner.ForcedInputMode primaryInputMode = XNAUnityRunner.PrimaryInputMode;
        if (num == 0)
        {
        }
        bool controllerModeLocked = XNAUnityRunner.ControllerModeLocked;
        if (num == 0)
        {
        }
        bool keyboardModeLocked = XNAUnityRunner.KeyboardModeLocked;
        GUIControllerModalResponse controller = this._controller;
        bool flag = this.displayPopup;
        bool flag2;
        int num2;
        if (flag)
        {
            if (!flag)
            {
            }
            Main.FlushBatches();
            if (!flag)
            {
            }
            Settings_Layout instance = Settings_Layout.Instance;
            if (this._displayBlocker != null)
            {
            }
            Panel_Layout returnTouch_Backing = instance.ReturnTouch_Backing;
            Panel_Layout returnTouch_MenuDivider = instance.ReturnTouch_MenuDivider;
            GUIControllerModalResponse controller2 = this._controller;
            String_Layout returnTouch_Prompt = instance.ReturnTouch_Prompt;
            string textValue = Language.GetTextValue("Mobile.ReturnTouchPrompt");
            if (controller == null)
            {
            }
            GUIString.Draw(returnTouch_Prompt, textValue);
            TransactionButton_Layout returnTouch_Accept = instance.ReturnTouch_Accept;
            string textValue2 = Language.GetTextValue("Mobile.ReturnTouchAccept");
            TransactionButton_Layout returnTouch_Cancel = instance.ReturnTouch_Cancel;
            if (controller == null)
            {
            }
            if (controller == null)
            {
            }
            bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
            GUITransactionButton.InputState inputState;
            if (inputState != GUITransactionButton.InputState.Clicked)
            {
                return;
            }
            GUIControllerModalResponse controller3 = this._controller;
            XNAUnityRunner.MobileControllerLocked = false;
            XNAUnityRunner.MobileKeyboardLocked = false;
            GUIControllerModalResponse controller4 = this._controller;
            GUIInputRegionExclusive displayBlocker = this._displayBlocker;
            if (displayBlocker != null)
            {
                flag2 = this.displayPopup;
                displayBlocker.Active = flag2;
            }
            if (displayBlocker == null)
            {
            }
            Main.FlushBatches();
            if (displayBlocker == null)
            {
            }
            num2 = 1;
        }
        if (num2 == 0)
        {
        }
        bool controllerModeLocked2 = XNAUnityRunner.ControllerModeLocked;
        if (num2 == 0)
        {
        }
        bool keyboardModeLocked2 = XNAUnityRunner.KeyboardModeLocked;
        if (num2 == 0)
        {
        }
        bool gameMenu = Main.gameMenu;
        if (!flag2)
        {
            return;
        }
        TransactionButton_Layout returnTouch_Menu = Settings_Layout.Instance.ReturnTouch_Menu;
        Main.FlushBatches();
        GUITransactionButton.InputState inputState2;
        if (inputState2 == GUITransactionButton.InputState.Clicked && !this.displayPopup)
        {
            int num3 = 1;
            this.displayPopup = num3 != 0;
            GUIInputRegionExclusive guiinputRegionExclusive;
            if (this._displayBlocker == null)
            {
                this._displayBlocker = guiinputRegionExclusive;
            }
            bool flag3 = this.displayPopup;
            guiinputRegionExclusive.Active = flag3;
            this._controller.Activate();
        }
        Main.FlushBatches();
    }
References _controller, _displayBlocker, GUIControllerModalResponse.Activate(), Controller.ControllerActionManager.AnyControllerConnected, XNAUnityRunner.ControllerModeLocked, displayPopup, GUIString.Draw(), Terraria.Main.FlushBatches(), Terraria.Main.gameMenu, Terraria.Localization.Language.GetTextValue(), Settings_Layout.Instance, j__TPar, XNAUnityRunner.KeyboardModeLocked, XNAUnityRunner.PrimaryInputMode, Settings_Layout.ReturnTouch_Accept, Settings_Layout.ReturnTouch_Backing, Settings_Layout.ReturnTouch_Cancel, Settings_Layout.ReturnTouch_Menu, Settings_Layout.ReturnTouch_MenuDivider, and Settings_Layout.ReturnTouch_Prompt.