terraria-cpp2il-methodrecon: System.Security.Cryptography.X509Certificates.X509Certificate2ImplMono.ImportPkcs12
ImportPkcs12() [1/2]
X509Certificate System.Security.Cryptography.X509Certificates.X509Certificate2ImplMono.ImportPkcs12 (byte[] rawData, SafePasswordHandle password) inline private
Definition at line 191 of file X509Certificate2ImplMono.cs.
        {
            string text;
            if (password != null)
            {
                text = password.Mono_DangerousGetString();
            }
            return this.ImportPkcs12(rawData, text);
        }
References System.Security.Cryptography.X509Certificates.X509Certificate2ImplMono.ImportPkcs12(), Microsoft.Win32.SafeHandles.SafePasswordHandle.Mono_DangerousGetString(), and System.text.
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2ImplMono.ImportPkcs12().