terraria-cpp2il-methodrecon: UnityEngine.GameObject.GetComponent
GetComponent()
Component UnityEngine.GameObject.GetComponent (Type type) inline
Definition at line 27 of file GameObject.cs.
        {
            throw new MissingMethodException();
        }
Referenced by UnityEngine.UI.Dropdown.AlphaFadeList(), UnityEngine.UI.DefaultControls.CreateButton(), UnityEngine.UI.DefaultControls.CreateInputField(), UnityEngine.UI.DefaultControls.CreatePanel(), UnityEngine.UI.DefaultControls.CreateScrollbar(), UnityEngine.UI.DefaultControls.CreateScrollView(), UnityEngine.UI.DefaultControls.CreateSlider(), UnityEngine.UI.DefaultControls.CreateText(), UnityEngine.UI.DefaultControls.CreateToggle(), Alert.GetAlertDelayObject(), LocalUser.GetCamera(), TransactionButtonStyleDefinitions.GetDefinition(), DistortionRenderTargetManager.InitialiseCamera(), WaterRenderTargetManager.InitialiseCamera(), UnityEngine.UI.AspectRatioFitter.IsComponentValidOnObject(), UnityEngine.UI.Dropdown.SetAlpha(), and UnityEngine.UI.Dropdown.SetupTemplate().