terraria-cpp2il-methodrecon: System.ComponentModel.EventDescriptorCollection.InternalSort
InternalSort() [2/2]
void System.ComponentModel.EventDescriptorCollection.InternalSort (string[] names) inline protected
Definition at line 413 of file EventDescriptorCollection.cs.
        {
            string displayName = this._events.displayName;
            if (displayName != null)
            {
                IComparer comparer = this._comparer;
                this.InternalSort(comparer);
                if (names != null && displayName != null)
                {
                    EventDescriptor[] events = this._events;
                    string displayName2 = this._events.displayName;
                    return;
                }
            }
        }
References System.ComponentModel.EventDescriptorCollection._comparer, System.ComponentModel.EventDescriptorCollection._events, System.comparer, System.ComponentModel.MemberDescriptor.displayName, System.ComponentModel.EventDescriptorCollection.InternalSort(), and j__TPar.
Referenced by System.ComponentModel.EventDescriptorCollection.EnsureEventsOwned(), and System.ComponentModel.EventDescriptorCollection.InternalSort().