terraria-cpp2il-methodrecon: System.ComponentModel.EventDescriptorCollection.EnsureEventsOwned
EnsureEventsOwned()
void System.ComponentModel.EventDescriptorCollection.EnsureEventsOwned () inline private
Definition at line 163 of file EventDescriptorCollection.cs.
        {
            if (!this._eventsOwned)
            {
                EventDescriptor[] events = this._events;
                this._eventsOwned = true;
                if (events != null)
                {
                    int num = this.<Count>k__BackingField;
                    EventDescriptor[] events2 = this._events;
                    int num2 = this.<Count>k__BackingField;
                }
            }
            if (this._needSort)
            {
                string[] namedSort = this._namedSort;
                this.InternalSort(namedSort);
                return;
            }
        }
References System.ComponentModel.EventDescriptorCollection._events, System.ComponentModel.EventDescriptorCollection._eventsOwned, System.ComponentModel.EventDescriptorCollection._namedSort, System.ComponentModel.EventDescriptorCollection._needSort, System.ComponentModel.EventDescriptorCollection.Count, System.ComponentModel.EventDescriptorCollection.InternalSort(), j__TPar, and System.ComponentModel.EventDescriptorCollection.k__BackingField.
Referenced by System.ComponentModel.EventDescriptorCollection.CopyTo(), and System.ComponentModel.EventDescriptorCollection.EnsureSize().