terraria-cpp2il-methodrecon: Mono.Security.Cryptography.PKCS1.CreateFromName
CreateFromName() [2/2]
static HashAlgorithm Mono.Security.Cryptography.PKCS1.CreateFromName (string name) inline static package
Definition at line 240 of file PKCS1.cs.
        {
            uint num = <PrivateImplementationDetails>.ComputeStringHash("RIPEMD160");
            SHA1 sha = SHA1.Create();
            MD2 md = MD2.Create();
            MD5 md2 = MD5.Create();
            SHA384 sha2 = SHA384.Create();
            RIPEMD160 ripemd = RIPEMD160.Create();
            SHA256 sha3 = SHA256.Create();
            MD4 md3 = MD4.Create();
            SHA512 sha4 = SHA512.Create();
            object obj;
            if (obj != null)
            {
            }
            throw new InvalidCastException();
        }
References Mono.Security.Cryptography.MD2.Create(), Mono.Security.Cryptography.MD4.Create(), System.Security.Cryptography.MD5.Create(), System.Security.Cryptography.RIPEMD160.Create(), System.Security.Cryptography.SHA1.Create(), System.Security.Cryptography.SHA256.Create(), System.Security.Cryptography.SHA384.Create(), System.Security.Cryptography.SHA512.Create(), j__TPar, and System.obj.