terraria-cpp2il-methodrecon: GUIPlayerCreateMenu.Draw
Draw()
void GUIPlayerCreateMenu.Draw () inline
Definition at line 30 of file GUIPlayerCreateMenu.cs.
    {
        GUIPlayerCreateController controllerInput = this._controllerInput;
        this._controllerInput.Activate();
        this.DrawCategoryButtons();
        this.DrawMainButtons();
        this.DrawPlayer();
        if (this.CurrentSelection != GUIPlayerCreateMenu.ItemSelection.Info)
        {
            this.DrawHSLSlider();
            return;
        }
        this.DrawInfo();
        if (this.displayOptions)
        {
            this.DrawName();
            this.DrawDifficulty();
            return;
        }
        this.DrawDifficulty();
        this.DrawName();
        string textValue = Language.GetTextValue("Mobile.ControlsSelect");
    }
References _controllerInput, GUIPlayerCreateController.Activate(), CurrentSelection, displayOptions, DrawCategoryButtons(), DrawDifficulty(), DrawHSLSlider(), DrawInfo(), DrawMainButtons(), DrawName(), DrawPlayer(), Terraria.Localization.Language.GetTextValue(), and j__TPar.