terraria-cpp2il-methodrecon: GUIPlayerCreateMenu.RandomisePlayer
RandomisePlayer()
void GUIPlayerCreateMenu.RandomisePlayer () inline
Definition at line 587 of file GUIPlayerCreateMenu.cs.
    {
        if (!true)
        {
        }
        Player pendingPlayer = Main.PendingPlayer;
        Player pendingPlayer2 = Main.PendingPlayer;
        Color color = Main.randColor();
        pendingPlayer2.eyeColor = color;
        byte r = Main.PendingPlayer.eyeColor.R;
        byte g = Main.PendingPlayer.eyeColor.G;
        byte b = Main.PendingPlayer.eyeColor.B;
        Player pendingPlayer3 = Main.PendingPlayer;
        Color color2 = Main.randColor();
        pendingPlayer3.hairColor = color2;
        Player pendingPlayer4 = Main.PendingPlayer;
        Color color3 = Main.randColor();
        pendingPlayer4.pantsColor = color3;
        Player pendingPlayer5 = Main.PendingPlayer;
        Color color4 = Main.randColor();
        pendingPlayer5.shirtColor = color4;
        Player pendingPlayer6 = Main.PendingPlayer;
        Color color5 = Main.randColor();
        pendingPlayer6.shoeColor = color5;
        Player pendingPlayer7 = Main.PendingPlayer;
        Color color6 = Main.randColor();
        pendingPlayer7.skinColor = color6;
        Player pendingPlayer8 = Main.PendingPlayer;
        Player pendingPlayer9 = Main.PendingPlayer;
        Player pendingPlayer10 = Main.PendingPlayer;
        Player pendingPlayer11 = Main.PendingPlayer;
        Color color7 = Main.randColor();
        pendingPlayer11.underShirtColor = color7;
        int[] array = this.actualStyleOrder;
        Player pendingPlayer12 = Main.PendingPlayer;
        int[] array2 = this.actualStyleOrder;
        this.styleOver = array2;
    }
References actualStyleOrder, System.array, Terraria.Player.eyeColor, j__TPar, Terraria.Main.PendingPlayer, and Terraria.Main.randColor().
Referenced by DrawInfo(), and Setup().