terraria-cpp2il-methodrecon: GUIPlayerCreateMenu.DrawMainButtons
DrawMainButtons()
void GUIPlayerCreateMenu.DrawMainButtons () inline private
Definition at line 388 of file GUIPlayerCreateMenu.cs.
    {
        bool mouseLeft = Main.mouseLeft;
        bool mouseLeftRelease = Main.mouseLeftRelease;
        string textValue = Language.GetTextValue("LegacyMenu.28");
        if (this.displayOptions)
        {
            return;
        }
        bool flag = this.editingPlayerName;
        string textValue2 = Language.GetTextValue("LegacyMenu.5");
        if (this.displayOptions)
        {
            return;
        }
        bool flag2 = this.editingPlayerName;
        if (this.displayOptions)
        {
            this.CloseOptions();
            return;
        }
        if (this.editingPlayerName)
        {
            return;
        }
        this.Back();
    }
References Back(), CloseOptions(), displayOptions, editingPlayerName, Terraria.Localization.Language.GetTextValue(), j__TPar, Terraria.Main.mouseLeft, and Terraria.Main.mouseLeftRelease.
Referenced by Draw().