terraria-cpp2il-methodrecon: GUIPlayerCreateMenu.CloseNameEdit
CloseNameEdit()
void GUIPlayerCreateMenu.CloseNameEdit () inline private
Definition at line 365 of file GUIPlayerCreateMenu.cs.
    {
        if (!true)
        {
        }
        Main.CloseKeyboard();
        GUIInputRegionExclusive optionsBlocker = this._optionsBlocker;
        this._controllerInput.InfoPage.DeactivateName();
    }
References _controllerInput, _optionsBlocker, Terraria.Main.CloseKeyboard(), GUIPlayerCreateController_Info.DeactivateName(), GUIPlayerCreateController.InfoPage, and j__TPar.
Referenced by DrawCategoryButtons().