terraria-cpp2il-methodrecon: GUIPlayerCreateMenu.DrawCategoryButtons
DrawCategoryButtons()
void GUIPlayerCreateMenu.DrawCategoryButtons () inline private
Definition at line 426 of file GUIPlayerCreateMenu.cs.
    {
        int num = 1;
        if (num == 0)
        {
        }
        bool mouseLeft = Main.mouseLeft;
        if (num == 0)
        {
        }
        bool mouseLeftRelease = Main.mouseLeftRelease;
        int num2 = 17096;
        this.TimeSinceItemChange = (float)num2;
        string textValue = Language.GetTextValue("Mobile.ControlsPageNext");
        string textValue2 = Language.GetTextValue("Mobile.ControlsPagePrevious");
        GUIPlayerCreateMenu.ItemSelection currentSelection = this.CurrentSelection;
        this.CurrentSelection = currentSelection;
        if (currentSelection == GUIPlayerCreateMenu.ItemSelection.Info)
        {
        }
        if (this.displayOptions)
        {
            this.CloseOptions();
        }
        if (this.editingPlayerName)
        {
            this.CloseNameEdit();
        }
        this._controllerInput.Activate();
        GUIPlayerCreateMenu.ItemSelection currentSelection2 = this.CurrentSelection;
        this.CurrentSelection = currentSelection2;
        if (currentSelection2 == GUIPlayerCreateMenu.ItemSelection.Info)
        {
        }
        this._controllerInput.Activate();
        string textValue3 = Language.GetTextValue("LegacyMenu.33");
        Color shirtColor = Main.PendingPlayer.shirtColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection3 = this.CurrentSelection;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            int num3 = 6;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num3;
            if (num3 == 0)
            {
            }
        }
        string textValue4 = Language.GetTextValue("LegacyMenu.34");
        Color underShirtColor = Main.PendingPlayer.underShirtColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection4 = this.CurrentSelection;
        GUITransactionButton.InputState inputState2;
        if (inputState2 == GUITransactionButton.InputState.Clicked)
        {
            int num4 = 7;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num4;
            if (num4 == 0)
            {
            }
        }
        string textValue5 = Language.GetTextValue("LegacyMenu.35");
        Color pantsColor = Main.PendingPlayer.pantsColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection5 = this.CurrentSelection;
        GUITransactionButton.InputState inputState3;
        if (inputState3 == GUITransactionButton.InputState.Clicked)
        {
            int num5 = 8;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num5;
            if (num5 == 0)
            {
            }
        }
        string textValue6 = Language.GetTextValue("LegacyMenu.36");
        Color shoeColor = Main.PendingPlayer.shoeColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection6 = this.CurrentSelection;
        GUITransactionButton.InputState inputState4;
        if (inputState4 == GUITransactionButton.InputState.Clicked)
        {
            int num6 = 9;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num6;
            if (num6 == 0)
            {
            }
        }
        string textValue7 = Language.GetTextValue("LegacyMenu.18");
        Color hairColor = Main.PendingPlayer.hairColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection7 = this.CurrentSelection;
        GUITransactionButton.InputState inputState5;
        if (inputState5 == GUITransactionButton.InputState.Clicked)
        {
            GUIPlayerCreateController controllerInput = this._controllerInput;
            int num7 = 4;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num7;
            controllerInput.HairStlyePage.Activate();
            if (controllerInput == null)
            {
            }
        }
        string textValue8 = Language.GetTextValue("LegacyMenu.18");
        GUIPlayerCreateMenu.ItemSelection currentSelection8 = this.CurrentSelection;
        GUITransactionButton.InputState inputState6;
        if (inputState6 == GUITransactionButton.InputState.Clicked)
        {
            if (currentSelection8 == GUIPlayerCreateMenu.ItemSelection.Info)
            {
            }
        }
        if (currentSelection8 == GUIPlayerCreateMenu.ItemSelection.Info)
        {
        }
        int hair = Main.PendingPlayer.hair;
        string textValue9 = Language.GetTextValue("LegacyMenu.18");
        Color hairColor2 = Main.PendingPlayer.hairColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection9 = this.CurrentSelection;
        GUITransactionButton.InputState inputState7;
        if (inputState7 == GUITransactionButton.InputState.Clicked)
        {
            int num8 = 5;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num8;
        }
        string textValue10 = Language.GetTextValue("LegacyMenu.19");
        Color skinColor = Main.PendingPlayer.skinColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection10 = this.CurrentSelection;
        GUITransactionButton.InputState inputState8;
        if (inputState8 == GUITransactionButton.InputState.Clicked)
        {
            int num9 = 2;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num9;
        }
        string textValue11 = Language.GetTextValue("LegacyMenu.20");
        Color eyeColor = Main.PendingPlayer.eyeColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection11 = this.CurrentSelection;
        GUITransactionButton.InputState inputState9;
        if (inputState9 == GUITransactionButton.InputState.Clicked)
        {
            int num10 = 3;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num10;
        }
        bool male = Main.PendingPlayer.Male;
        string textValue12 = Language.GetTextValue("Mobile.PlayerCreateGender");
        Color skinColor2 = Main.PendingPlayer.skinColor;
        GUIPlayerCreateMenu.ItemSelection currentSelection12 = this.CurrentSelection;
        GUITransactionButton.InputState inputState10;
        if (inputState10 == GUITransactionButton.InputState.Clicked)
        {
            int num11 = 1;
            this.CurrentSelection = (GUIPlayerCreateMenu.ItemSelection)num11;
        }
        GUIPlayerCreateMenu.ItemSelection currentSelection13 = this.CurrentSelection;
    }
References _controllerInput, GUIPlayerCreateController.Activate(), GUIPlayerCreateController_HairStyle.Activate(), CloseNameEdit(), CloseOptions(), CurrentSelection, displayOptions, editingPlayerName, Terraria.Player.eyeColor, Terraria.Localization.Language.GetTextValue(), Terraria.Player.hair, Terraria.Player.hairColor, GUIPlayerCreateController.HairStlyePage, j__TPar, Terraria.Player.Male, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Player.pantsColor, Terraria.Main.PendingPlayer, Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, and Terraria.Player.underShirtColor.
Referenced by Draw().