terraria-cpp2il-methodrecon: GUIPlayerCreateMenu.DrawHairGrid
DrawHairGrid()
void GUIPlayerCreateMenu.DrawHairGrid () inline private
Definition at line 156 of file GUIPlayerCreateMenu.cs.
    {
        int mouseX = Main.mouseX;
        int mouseY = Main.mouseY;
        string textValue = Language.GetTextValue("Mobile.Randomize");
        if (this.displayOptions)
        {
            return;
        }
        if (!this.editingPlayerName)
        {
        }
        Player pendingPlayer = Main.PendingPlayer;
        this._controllerInput.HairStlyePage.Activate();
        this._controllerInput.ActivateRandomise();
    }
References _controllerInput, GUIPlayerCreateController_HairStyle.Activate(), GUIPlayerCreateController.ActivateRandomise(), displayOptions, editingPlayerName, Terraria.Localization.Language.GetTextValue(), GUIPlayerCreateController.HairStlyePage, j__TPar, Terraria.Main.mouseX, Terraria.Main.mouseY, and Terraria.Main.PendingPlayer.