terraria-cpp2il-methodrecon: Mono.X509PalImpl.ImportFallback
ImportFallback() [1/2]
global.System.Security.Cryptography.X509Certificates.X509Certificate2Impl Mono.X509PalImpl.ImportFallback (byte[] data) inline package inherited
Definition at line 45 of file X509PalImpl.cs.
        {
            if (!true)
            {
            }
            byte[] array = X509PalImpl.ConvertData(data);
            long num = 0L;
            if (data != null)
            {
                byte value = data.m_value;
            }
            if (num == 0L)
            {
            }
            throw new OutOfMemoryException();
        }
References System.array, Mono.X509PalImpl.ConvertData(), System.L, and System.value.
Referenced by Mono.SystemCertificateProvider.Import(), and Mono.SystemCertificateProvider.Import().