terraria-cpp2il-methodrecon: System.Net.NetworkInformation.AixNetworkInterfaceAPI.GetAllNetworkInterfaces
GetAllNetworkInterfaces()
override NetworkInterface[] System.Net.NetworkInformation.AixNetworkInterfaceAPI.GetAllNetworkInterfaces () inline
Definition at line 34 of file AixNetworkInterfaceAPI.cs.
        {
            IntPtr intPtr = Marshal.AllocHGlobal(43159552);
            long num;
            Type type;
            object obj = Marshal.PtrToStructure((IntPtr)num, type);
            string text = Marshal.PtrToStringAnsi(-2147483648);
            int num2 = 16;
            bool flag;
            Type type2;
            object obj2 = Marshal.PtrToStructure((flag ? 1 : 0) + num2, type2);
            return int.MinValue;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), j__TPar, System.obj, System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), System.Runtime.InteropServices.Marshal.PtrToStructure(), and System.text.