terraria-cpp2il-methodrecon: GUIJourneyModeSettings.DrawCategories
DrawCategories()
void GUIJourneyModeSettings.DrawCategories () inline
Definition at line 167 of file GUIJourneyModeSettings.cs.
    {
        if (this._categoriesBlocker != null)
        {
        }
        bool mouseLeft = Main.mouseLeft;
        bool mouseLeftRelease = Main.mouseLeftRelease;
        int num = 17096;
        this.TimeSinceItemChange = (float)num;
        if (num == 0)
        {
        }
        GUIJourneyModeSettings.Category selected = this.Selected;
        GUIControllerJourneyModeSettings controllerInput = this._controllerInput;
        int num2 = 3;
        controllerInput.selectedControl = (GUIControllerJourneyModeSettings.Controls)num2;
        controllerInput.Activate();
        GUIControllerJourneyModeSettings controllerInput2 = this._controllerInput;
        int num3 = 3;
        controllerInput2.selectedControl = (GUIControllerJourneyModeSettings.Controls)num3;
        controllerInput2.Activate();
        string textValue = Language.GetTextValue("Mobile.JourneyCategoryTime");
        GUIJourneyModeSettings.Category selected2 = this.Selected;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            this._controllerInput.Activate();
        }
        string textValue2 = Language.GetTextValue("Mobile.JourneyCategoryWeather");
        GUIJourneyModeSettings.Category selected3 = this.Selected;
        GUITransactionButton.InputState inputState2;
        if (inputState2 == GUITransactionButton.InputState.Clicked)
        {
            this._controllerInput.Activate();
        }
        string textValue3 = Language.GetTextValue("Mobile.JourneyCategoryPowers");
        GUIJourneyModeSettings.Category selected4 = this.Selected;
        GUITransactionButton.InputState inputState3;
        if (inputState3 == GUITransactionButton.InputState.Clicked)
        {
            this._controllerInput.Activate();
        }
        float timeSinceItemChange = this.TimeSinceItemChange;
        float deltaTime = Time.deltaTime;
        this.DrawMainButtons();
        GUIInputRegionExclusive categoriesBlocker = this._categoriesBlocker;
        if (categoriesBlocker != null)
        {
            int num4 = 1;
            categoriesBlocker.Active = num4 != 0;
        }
    }
References _categoriesBlocker, _controllerInput, GUIControllerJourneyModeSettings.Activate(), UnityEngine.Time.deltaTime, DrawMainButtons(), Terraria.Localization.Language.GetTextValue(), j__TPar, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Selected, and TimeSinceItemChange.