terraria-cpp2il-methodrecon: Terraria.GameContent.PressurePlateHelper.Reset
Reset()
static void Terraria.GameContent.PressurePlateHelper.Reset () inline static
Definition at line 19 of file PressurePlateHelper.cs.
        {
            int num = 1;
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
            if (num == 0)
            {
            }
        }
Referenced by Terraria.WorldGen.clearWorld(), Terraria.IO.WorldFile.LoadWeightedPressurePlates(), WorldFile_OldConsole.LoadWeightedPressurePlates(), and WorldFile_OldSwitch.LoadWeightedPressurePlates().