terraria-cpp2il-methodrecon: System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType
GetType()
Type System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType (BinaryAssemblyInfo assemblyInfo, string name) inline package
Definition at line 451 of file ObjectReader.cs.
        {
            string text = this.previousName;
            if (text != null)
            {
                int stringLength = text._stringLength;
                int stringLength2 = name._stringLength;
                bool flag = text.Equals(name);
                string text2 = this.previousAssemblyString;
                if (text2 != null)
                {
                    string assemblyString = assemblyInfo.assemblyString;
                    int stringLength3 = text2._stringLength;
                    int stringLength4 = assemblyString._stringLength;
                    bool flag2 = text2.Equals(assemblyString);
                    Type type = this.previousType;
                }
            }
            string assemblyString2 = assemblyInfo.assemblyString;
            Type type2 = this.Bind(assemblyString2, name);
            if (type2 != null)
            {
                return type2;
            }
            Assembly assembly = assemblyInfo.GetAssembly();
            if (this.bSimpleAssembly)
            {
            }
            Type typeFromAssembly = FormatterServices.GetTypeFromAssembly(assembly, name);
            string assemblyString3 = assemblyInfo.assemblyString;
            this.previousType = typeFromAssembly;
            this.previousAssemblyString = assemblyString3;
            this.previousName = name;
            return typeFromAssembly;
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.assemblyString, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Bind(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.bSimpleAssembly, System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly(), System.Runtime.Serialization.FormatterServices.GetTypeFromAssembly(), j__TPar, System.name, System.Runtime.Serialization.Formatters.Binary.ObjectReader.previousAssemblyString, System.Runtime.Serialization.Formatters.Binary.ObjectReader.previousName, System.Runtime.Serialization.Formatters.Binary.ObjectReader.previousType, and System.text.