terraria-cpp2il-methodrecon: GUIEquipment.ItemOver
ItemOver()
void GUIEquipment.ItemOver (Item[] inv, int index, GUIEquipment::EquipmentItemType equipmentType, int itemContext, int itemDragStart) inline private
Definition at line 141 of file GUIEquipment.cs.
    {
        this.cursorOver = index;
        global::Cursor cursor;
        if (cursor != null)
        {
            return;
        }
        global::Cursor cursor2;
        if (cursor2 != null)
        {
            return;
        }
        this.itemOver = index;
        this.itemType = equipmentType;
        this.UnequipButtonScale = (float)index;
        bool flag = this.rightClickHeld;
        if (flag)
        {
            int num = this.lastItemClicked;
        }
        GUIEquipment.EquipmentItemType equipmentItemType = this.lastItemTypeClicked;
        if (flag)
        {
            int num2 = this.lastItemClicked;
            bool mouseLeft = Main.mouseLeft;
            if (Main.mouseItem != null && Main.mouseItem.type != 0)
            {
                this.itemOver = index;
            }
            Main.mouseRight = Main.mouseLeft;
            bool flag2 = ItemSlot.RightClick(inv, itemContext, index);
            bool mouseRight = Main.mouseRight;
            long num3 = 0L;
            this.itemOver = index;
            this.itemType = equipmentType;
            this.UnequipButtonScale = (float)index;
            if (num2 == 0 && num3 != 0L)
            {
                return;
            }
        }
        else
        {
            long num4 = 0L;
            this.itemOver = index;
            this.itemType = equipmentType;
            this.UnequipButtonScale = (float)index;
            if (equipmentType == GUIEquipment.EquipmentItemType.Armour && num4 != 0L)
            {
                return;
            }
        }
        ItemSlot.LeftClick(inv, itemContext, index);
        long num5 = 0L;
        ItemSlot.OverrideHover(inv, itemContext, index);
        ItemSlot.MouseHover(inv, itemContext, index);
        int cursorOverride = Main.cursorOverride;
        if (num5 != 0L)
        {
            ItemSlot.LeftClick(inv, itemContext, index);
            Recipe.FindRecipes(false);
        }
    }
References Terraria.Main.cursorOverride, Terraria.Recipe.FindRecipes(), System.index, j__TPar, System.L, lastItemClicked, lastItemTypeClicked, Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseRight, Terraria.UI.ItemSlot.OverrideHover(), Terraria.UI.ItemSlot.RightClick(), rightClickHeld, and Terraria.Item.type.