terraria-cpp2il-methodrecon: GUIEquipment.Draw
Draw()
void GUIEquipment.Draw () inline
Definition at line 1069 of file GUIEquipment.cs.
    {
        float num = this.doubleClickTimer;
        float deltaTime = Time.deltaTime;
        this.lastItemClicked = 1;
        this.DrawArmour();
        this.DrawAccesories();
        this.DrawQuickSlots();
        this.DrawHeaders();
        this.DrawArmourBonus();
        bool hasFocus = this.HasFocus;
        GUIControllerEquipment guicontrollerEquipment;
        if (!guicontrollerEquipment.inAccessories && this.GetSelectedItem().type != 0)
        {
            int stack = this.GetSelectedItem().stack;
            return;
        }
    }
References UnityEngine.Time.deltaTime, doubleClickTimer, DrawAccesories(), DrawArmour(), DrawArmourBonus(), DrawHeaders(), DrawQuickSlots(), GetSelectedItem(), HasFocus, j__TPar, System.stack, and Terraria.Item.stack.