terraria-cpp2il-methodrecon: GUIControllerMappings.DrawMainButtons
DrawMainButtons()
void GUIControllerMappings.DrawMainButtons () inline private
Definition at line 334 of file GUIControllerMappings.cs.
    {
        bool mouseLeft = Main.mouseLeft;
        bool mouseLeftRelease = Main.mouseLeftRelease;
        GUIControllerMappingEntryBase guicontrollerMappingEntryBase = this._controllerInput._overlayEntry;
        int num = 1;
        GUITransactionButton.InputState inputState;
        if (inputState == GUITransactionButton.InputState.Clicked)
        {
            if (num == 0)
            {
            }
            Main.mouseLeftRelease = false;
        }
        if (guicontrollerMappingEntryBase == null)
        {
        }
        GUIControllerMappingEntryBase guicontrollerMappingEntryBase2 = this._controllerInput._overlayEntry;
        int num2 = 1;
        GUITransactionButton.InputState inputState2;
        if (inputState2 == GUITransactionButton.InputState.Clicked)
        {
            if (num2 == 0)
            {
            }
            Main.mouseLeftRelease = false;
            this.RestoreBackup();
        }
        bool anyControllerConnected = ControllerActionManager.AnyControllerConnected;
        GUIControllerMappingOverlay controllerInput = this._controllerInput;
        GUIControllerMappingOverlay.Controls selectedControl = controllerInput.selectedControl;
        List<GUIControllerMappingEntryBase> categorySettings = this._categorySettings;
        int selectedItem = controllerInput._selectedItem;
        int size = categorySettings._size;
        if (categorySettings != null)
        {
            int num3 = 1;
            GUIControllerMappingEntryBase guicontrollerMappingEntryBase3 = this._controllerInput._overlayEntry;
            if (guicontrollerMappingEntryBase3 != null)
            {
                return;
            }
            GUISettingID id = guicontrollerMappingEntryBase3._id;
            GUITransactionButton.InputState inputState3;
            if (inputState3 == GUITransactionButton.InputState.Clicked)
            {
                if (num3 == 0)
                {
                }
                Main.mouseLeftRelease = false;
                this.ClearMapping();
                this.RefreshConfigurationState();
            }
        }
        bool anyControllerConnected2 = ControllerActionManager.AnyControllerConnected;
        GUIControllerMappingOverlay controllerInput2 = this._controllerInput;
        GUIControllerMappingOverlay.Controls selectedControl2 = controllerInput2.selectedControl;
        List<GUIControllerMappingEntryBase> categorySettings2 = this._categorySettings;
        int selectedItem2 = controllerInput2._selectedItem;
        int size2 = categorySettings2._size;
        if (controllerInput2._overlayEntry != null)
        {
            return;
        }
        while (categorySettings2 == null)
        {
        }
    }
References _categorySettings, _controllerInput, GUISettingEntry._id, GUIControllerMappingOverlay._overlayEntry, GUIControllerMappingOverlay._selectedItem, System.Collections.Generic.List< T >._size, Controller.ControllerActionManager.AnyControllerConnected, ClearMapping(), j__TPar, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, RefreshConfigurationState(), RestoreBackup(), and GUIControllerMappingOverlay.selectedControl.