terraria-cpp2il-methodrecon: GUIControllerMappings.ClearWorldMappings
ClearWorldMappings()
void GUIControllerMappings.ClearWorldMappings () inline private
Definition at line 23 of file GUIControllerMappings.cs.
    {
        this.MovementAxisX.Clear();
        this.MovementAxisY.Clear();
        this.MovementAxisAltX.Clear();
        this.MovementAxisAltY.Clear();
        this.FireAxisX.Clear();
        this.FireAxisY.Clear();
        this.FireAxisAltX.Clear();
        this.FireAxisAltY.Clear();
        this.GrappleAxisX.Clear();
        this.GrappleAxisY.Clear();
        this.HotbarAxisX.Clear();
        this.HotbarAxisY.Clear();
        this.GrappleFire.Clear();
        this.GridSnapAxisX.Clear();
        this.GridSnapAxisY.Clear();
        this.Jump.Clear();
        this.Fire.Clear();
        this.FireAlt.Clear();
        this.Interact.Clear();
        this.TargetLockOn.Clear();
        this.InventoryToggle.Clear();
        this.AutoSelect.Clear();
        this.SmartCursor.Clear();
        this.AutoFire.Clear();
        this.HotbarNext.Clear();
        this.HotbarPrevious.Clear();
        this.ZoomIn.Clear();
        this.ZoomOut.Clear();
        this.MapZoomIn.Clear();
        this.MapZoomOut.Clear();
        this.MapZoomDefault.Clear();
        this.QuickHeal.Clear();
        this.QuickMana.Clear();
        this.QuickBuff.Clear();
        this.QuickMount.Clear();
        this.MapToggle.Clear();
        this.ChatToggle.Clear();
        this.MiniMapToggle.Clear();
        this.BuffNext.Clear();
        this.BuffPrevious.Clear();
        this.BuffRemove.Clear();
        this.Hotbar1.Clear();
        this.Hotbar2.Clear();
        this.Hotbar3.Clear();
        this.Hotbar4.Clear();
        this.Hotbar5.Clear();
        this.Hotbar6.Clear();
        this.Hotbar7.Clear();
        this.Hotbar8.Clear();
        this.Hotbar9.Clear();
        this.Hotbar10.Clear();
        this.DynamicHotbar1.Clear();
        this.DynamicHotbar2.Clear();
        this.DynamicHotbar3.Clear();
        this.DynamicHotbar4.Clear();
        this.Loadout1.Clear();
        this.Loadout2.Clear();
        this.Loadout3.Clear();
        this.LoadoutCycle.Clear();
    }
References AutoFire, AutoSelect, BuffNext, BuffPrevious, BuffRemove, ChatToggle, Controller.ControllerActionAxis.Clear(), Controller.ControllerActionButton.Clear(), DynamicHotbar1, DynamicHotbar2, DynamicHotbar3, DynamicHotbar4, Fire, FireAlt, FireAxisAltX, FireAxisAltY, FireAxisX, FireAxisY, GrappleAxisX, GrappleAxisY, GrappleFire, GridSnapAxisX, GridSnapAxisY, Hotbar1, Hotbar10, Hotbar2, Hotbar3, Hotbar4, Hotbar5, Hotbar6, Hotbar7, Hotbar8, Hotbar9, HotbarAxisX, HotbarAxisY, HotbarNext, HotbarPrevious, Interact, InventoryToggle, Jump, Loadout1, Loadout2, Loadout3, LoadoutCycle, MapToggle, MapZoomDefault, MapZoomIn, MapZoomOut, MiniMapToggle, MovementAxisAltX, MovementAxisAltY, MovementAxisX, MovementAxisY, QuickBuff, QuickHeal, QuickMana, QuickMount, SmartCursor, TargetLockOn, ZoomIn, and ZoomOut.
Referenced by LoadMappingValues().