terraria-cpp2il-methodrecon: GUIControllerMappings.ClearInventoryMappings
ClearInventoryMappings()
void GUIControllerMappings.ClearInventoryMappings () inline private
Definition at line 87 of file GUIControllerMappings.cs.
    {
        this.InventoryNavigationX.Clear();
        this.InventoryNavigationY.Clear();
        this.InventoryNavigationAltX.Clear();
        this.InventoryNavigationAltY.Clear();
        this.LeftPageCycle.Clear();
        this.RightPageCycle.Clear();
        this.WorldFocusToggle.Clear();
        this.ThrowItem.Clear();
        this.TrashItem.Clear();
        this.DepositHeldItem.Clear();
        this.FavouriteItem.Clear();
        this.ResearchItem.Clear();
        this.SplitItem.Clear();
        this.PickupPlaceItem.Clear();
        this.CraftItem.Clear();
        this.FilterItems.Clear();
        this.ToggleCraftDuplicate.Clear();
        this.HousingQuery.Clear();
        this.TakeOne.Clear();
        this.Sort.Clear();
        this.BuilderTools.Clear();
        this.ReforgeItem.Clear();
        this.InventoryClose.Clear();
        this.ShowHideItem.Clear();
        this.InfoAccessories.Clear();
        this.ChestQuickStack.Clear();
        this.ChestLootAll.Clear();
        this.ChestDepositAll.Clear();
        this.ChestRestock.Clear();
        this.ChestRename.Clear();
        this.ChestLoot.Clear();
        this.ChestDeposit.Clear();
        this.ChestSort.Clear();
        this.EquipmentEquip.Clear();
        this.EquipmentUnequip.Clear();
        this.ShopSell.Clear();
        this.ShopBuy.Clear();
        this.PVPEnableToggle.Clear();
        this.PVPSwitchTeam.Clear();
    }
References BuilderTools, ChestDeposit, ChestDepositAll, ChestLoot, ChestLootAll, ChestQuickStack, ChestRename, ChestRestock, ChestSort, Controller.ControllerActionAxis.Clear(), Controller.ControllerActionButton.Clear(), CraftItem, DepositHeldItem, EquipmentEquip, EquipmentUnequip, FavouriteItem, FilterItems, HousingQuery, InfoAccessories, InventoryClose, InventoryNavigationAltX, InventoryNavigationAltY, InventoryNavigationX, InventoryNavigationY, LeftPageCycle, PickupPlaceItem, PVPEnableToggle, PVPSwitchTeam, ReforgeItem, ResearchItem, RightPageCycle, ShopBuy, ShopSell, ShowHideItem, Sort, SplitItem, TakeOne, ThrowItem, ToggleCraftDuplicate, TrashItem, and WorldFocusToggle.
Referenced by LoadMappingValues().