terraria-cpp2il-methodrecon: GUIControllerMappings.SetMapping
SetMapping()
void GUIControllerMappings.SetMapping (GUIControllerMappings::MappingType mappingType) inline
Definition at line 601 of file GUIControllerMappings.cs.
    {
        this.mapping = mappingType;
        GUIControllerMappingScheme defaultScheme = this.GetDefaultScheme(mappingType);
        if (defaultScheme != null)
        {
            this.World.ClearMappings();
            this.BaseInventory.ClearMappings();
            GUIControllerMappingStateTable world = this.World;
            GUIControllerMappingStateTable worldMappings = defaultScheme.WorldMappings;
            world.Copy(worldMappings);
            GUIControllerMappingStateTable worldShared = this.WorldShared;
            GUIControllerMappingStateTable worldSharedMappings = defaultScheme.WorldSharedMappings;
            worldShared.Copy(worldSharedMappings);
            GUIControllerMappingStateTable worldInteract = this.WorldInteract;
            GUIControllerMappingStateTable worldInteractMappings = defaultScheme.WorldInteractMappings;
            worldInteract.Copy(worldInteractMappings);
            GUIControllerMappingStateTable worldInteractFallback = this.WorldInteractFallback;
            GUIControllerMappingStateTable worldInteractFallbackMappings = defaultScheme.WorldInteractFallbackMappings;
            worldInteractFallback.Copy(worldInteractFallbackMappings);
            GUIControllerMappingStateTable baseInventory = this.BaseInventory;
            GUIControllerMappingStateTable baseInventoryMappings = defaultScheme.BaseInventoryMappings;
            baseInventory.Copy(baseInventoryMappings);
            GUIControllerMappingStateTable inventory = this.Inventory;
            GUIControllerMappingStateTable inventoryMappings = defaultScheme.InventoryMappings;
            inventory.Copy(inventoryMappings);
            GUIControllerMappingStateTable pvp = this.PVP;
            GUIControllerMappingStateTable pvpmappings = defaultScheme.PVPMappings;
            pvp.Copy(pvpmappings);
            GUIControllerMappingStateTable housing = this.Housing;
            GUIControllerMappingStateTable housingMappings = defaultScheme.HousingMappings;
            housing.Copy(housingMappings);
            GUIControllerMappingStateTable itemHeld = this.ItemHeld;
            GUIControllerMappingStateTable heldMappings = defaultScheme.HeldMappings;
            itemHeld.Copy(heldMappings);
            GUIControllerMappingStateTable equipment = this.Equipment;
            GUIControllerMappingStateTable equipmentMappings = defaultScheme.EquipmentMappings;
            equipment.Copy(equipmentMappings);
            GUIControllerMappingStateTable chestInv = this.ChestInv;
            GUIControllerMappingStateTable chestInvMappings = defaultScheme.ChestInvMappings;
            chestInv.Copy(chestInvMappings);
            GUIControllerMappingStateTable chest = this.Chest;
            GUIControllerMappingStateTable chestMappings = defaultScheme.ChestMappings;
            chest.Copy(chestMappings);
            GUIControllerMappingStateTable shopInv = this.ShopInv;
            GUIControllerMappingStateTable shopInvMappings = defaultScheme.ShopInvMappings;
            shopInv.Copy(shopInvMappings);
            GUIControllerMappingStateTable shop = this.Shop;
            GUIControllerMappingStateTable shopMappings = defaultScheme.ShopMappings;
            shop.Copy(shopMappings);
            GUIControllerMappingStateTable crafting = this.Crafting;
            GUIControllerMappingStateTable craftingMappings = defaultScheme.CraftingMappings;
            crafting.Copy(craftingMappings);
            GUIControllerMappingStateTable reforge = this.Reforge;
            GUIControllerMappingStateTable reforgeMappings = defaultScheme.ReforgeMappings;
            reforge.Copy(reforgeMappings);
            GUIControllerMappingStateTable chat = this.Chat;
            GUIControllerMappingStateTable chatMappings = defaultScheme.ChatMappings;
            chat.Copy(chatMappings);
            this.LoadMappingValues();
            return;
        }
    }
References BaseInventory, GUIControllerMappingScheme.BaseInventoryMappings, Chat, GUIControllerMappingScheme.ChatMappings, Chest, ChestInv, GUIControllerMappingScheme.ChestInvMappings, GUIControllerMappingScheme.ChestMappings, GUIControllerMappingStateTable.ClearMappings(), GUIControllerMappingStateTable.Copy(), Crafting, GUIControllerMappingScheme.CraftingMappings, Equipment, GUIControllerMappingScheme.EquipmentMappings, GetDefaultScheme(), GUIControllerMappingScheme.HeldMappings, Housing, GUIControllerMappingScheme.HousingMappings, Inventory, GUIControllerMappingScheme.InventoryMappings, ItemHeld, j__TPar, LoadMappingValues(), PVP, GUIControllerMappingScheme.PVPMappings, Reforge, GUIControllerMappingScheme.ReforgeMappings, Shop, ShopInv, GUIControllerMappingScheme.ShopInvMappings, GUIControllerMappingScheme.ShopMappings, World, WorldInteract, WorldInteractFallback, GUIControllerMappingScheme.WorldInteractFallbackMappings, GUIControllerMappingScheme.WorldInteractMappings, GUIControllerMappingScheme.WorldMappings, WorldShared, and GUIControllerMappingScheme.WorldSharedMappings.