terraria-cpp2il-methodrecon: GUIControllerMappings.LoadConfiguration
LoadConfiguration()
void GUIControllerMappings.LoadConfiguration (Preferences preferences, bool existingConfiguration) inline
Definition at line 482 of file GUIControllerMappings.cs.
    {
        bool flag;
        ControllerDevice.SwapBumpersTriggers = flag;
        GUIControllerMappingStateTable worldShared = this.WorldShared;
        List<ControllerActionButton> worldButtonMappings = this.WorldButtonMappings;
        List<ControllerActionAxis> worldAxisTable = this.WorldAxisTable;
        GUIControllerMappingStateTable worldInteractFallback = this.WorldInteractFallback;
        List<ControllerActionButton> worldButtonMappings2 = this.WorldButtonMappings;
        List<ControllerActionAxis> worldAxisTable2 = this.WorldAxisTable;
        GUIControllerMappingStateTable worldInteract = this.WorldInteract;
        List<ControllerActionButton> worldButtonMappings3 = this.WorldButtonMappings;
        List<ControllerActionAxis> worldAxisTable3 = this.WorldAxisTable;
        GUIControllerMappingStateTable world = this.World;
        List<ControllerActionButton> worldButtonMappings4 = this.WorldButtonMappings;
        List<ControllerActionAxis> worldAxisTable4 = this.WorldAxisTable;
        GUIControllerMappingStateTable world2 = this.World;
        ControllerActionButton interact = this.Interact;
        GUIControllerMappingStateTable worldInteract2 = this.WorldInteract;
        world2.TransferMapping(interact, worldInteract2);
        GUIControllerMappingStateTable world3 = this.World;
        ControllerActionButton fire = this.Fire;
        GUIControllerMappingStateTable worldInteractFallback2 = this.WorldInteractFallback;
        world3.TransferMapping(fire, worldInteractFallback2);
        GUIControllerMappingStateTable world4 = this.World;
        ControllerActionButton fireAlt = this.FireAlt;
        GUIControllerMappingStateTable worldInteractFallback3 = this.WorldInteractFallback;
        world4.TransferMapping(fireAlt, worldInteractFallback3);
        GUIControllerMappingStateTable world5 = this.World;
        ControllerActionButton grappleFire = this.GrappleFire;
        GUIControllerMappingStateTable worldInteractFallback4 = this.WorldInteractFallback;
        long num = 0L;
        world5.TransferMapping(grappleFire, worldInteractFallback4);
        GUIControllerMappingStateTable baseInventory = this.BaseInventory;
        List<ControllerActionButton> baseInventoryTable = this.BaseInventoryTable;
        List<ControllerActionAxis> inventoryAxisTable = this.InventoryAxisTable;
        baseInventory.LoadConfiguration("BaseInventoryControls", preferences, num != 0L, baseInventoryTable, inventoryAxisTable);
        GUIControllerMappingStateTable inventory = this.Inventory;
        List<ControllerActionButton> inventoryTable = this.InventoryTable;
        List<ControllerActionAxis> axisTableEmpty = this.AxisTableEmpty;
        inventory.LoadConfiguration("InventoryControls", preferences, num != 0L, inventoryTable, axisTableEmpty);
        GUIControllerMappingStateTable equipment = this.Equipment;
        List<ControllerActionButton> equipmentTable = this.EquipmentTable;
        List<ControllerActionAxis> axisTableEmpty2 = this.AxisTableEmpty;
        equipment.LoadConfiguration("EquipmentControls", preferences, num != 0L, equipmentTable, axisTableEmpty2);
        GUIControllerMappingStateTable pvp = this.PVP;
        List<ControllerActionButton> pvptable = this.PVPTable;
        List<ControllerActionAxis> axisTableEmpty3 = this.AxisTableEmpty;
        pvp.LoadConfiguration("PVPControls", preferences, num != 0L, pvptable, axisTableEmpty3);
        GUIControllerMappingStateTable itemHeld = this.ItemHeld;
        List<ControllerActionButton> itemHeldTable = this.ItemHeldTable;
        List<ControllerActionAxis> axisTableEmpty4 = this.AxisTableEmpty;
        itemHeld.LoadConfiguration("ItemHeldControls", preferences, num != 0L, itemHeldTable, axisTableEmpty4);
        GUIControllerMappingStateTable chestInv = this.ChestInv;
        List<ControllerActionButton> chestInvTable = this.ChestInvTable;
        List<ControllerActionAxis> axisTableEmpty5 = this.AxisTableEmpty;
        chestInv.LoadConfiguration("ChestInvControls", preferences, num != 0L, chestInvTable, axisTableEmpty5);
        GUIControllerMappingStateTable chest = this.Chest;
        List<ControllerActionButton> chestTable = this.ChestTable;
        List<ControllerActionAxis> axisTableEmpty6 = this.AxisTableEmpty;
        chest.LoadConfiguration("ChestControls", preferences, num != 0L, chestTable, axisTableEmpty6);
        GUIControllerMappingStateTable shopInv = this.ShopInv;
        List<ControllerActionButton> shopInvTable = this.ShopInvTable;
        List<ControllerActionAxis> axisTableEmpty7 = this.AxisTableEmpty;
        shopInv.LoadConfiguration("ShopInvControls", preferences, num != 0L, shopInvTable, axisTableEmpty7);
        GUIControllerMappingStateTable shop = this.Shop;
        List<ControllerActionButton> shopTable = this.ShopTable;
        List<ControllerActionAxis> axisTableEmpty8 = this.AxisTableEmpty;
        shop.LoadConfiguration("ShopControls", preferences, num != 0L, shopTable, axisTableEmpty8);
        GUIControllerMappingStateTable crafting = this.Crafting;
        List<ControllerActionButton> craftingTable = this.CraftingTable;
        List<ControllerActionAxis> axisTableEmpty9 = this.AxisTableEmpty;
        crafting.LoadConfiguration("CraftingControls", preferences, num != 0L, craftingTable, axisTableEmpty9);
        GUIControllerMappingStateTable reforge = this.Reforge;
        List<ControllerActionButton> reforgeTable = this.ReforgeTable;
        List<ControllerActionAxis> axisTableEmpty10 = this.AxisTableEmpty;
        reforge.LoadConfiguration("ReforgeControls", preferences, num != 0L, reforgeTable, axisTableEmpty10);
        GUIControllerMappingStateTable housing = this.Housing;
        List<ControllerActionButton> housingTable = this.HousingTable;
        List<ControllerActionAxis> axisTableEmpty11 = this.AxisTableEmpty;
        housing.LoadConfiguration("HousingControls", preferences, num != 0L, housingTable, axisTableEmpty11);
        GUIControllerMappingStateTable chat = this.Chat;
        List<ControllerActionButton> chatTable = this.ChatTable;
        List<ControllerActionAxis> axisTableEmpty12 = this.AxisTableEmpty;
        chat.LoadConfiguration("ChatControls", preferences, num != 0L, chatTable, axisTableEmpty12);
        if ("ChatControls" != null)
        {
            this.RefreshConfigurationState();
            return;
        }
    }
References AxisTableEmpty, BaseInventory, BaseInventoryTable, Chat, ChatTable, Chest, ChestInv, ChestInvTable, ChestTable, Crafting, CraftingTable, Equipment, EquipmentTable, Fire, FireAlt, GrappleFire, Housing, HousingTable, Interact, Inventory, InventoryAxisTable, InventoryTable, ItemHeld, ItemHeldTable, j__TPar, System.L, GUIControllerMappingStateTable.LoadConfiguration(), PVP, PVPTable, Reforge, ReforgeTable, RefreshConfigurationState(), Shop, ShopInv, ShopInvTable, ShopTable, GUIControllerMappingStateTable.TransferMapping(), World, WorldAxisTable, WorldButtonMappings, WorldInteract, WorldInteractFallback, and WorldShared.